/**
 * L12.6 — Persistence / read / replay / repair / downstream violation codes
 * (§12.6.20).
 *
 * Disjoint namespace `L12P_` (persistence/serving law).
 */

export enum L12PersistenceViolationCode {
  // Persistence envelope / L5 routing
  L12P_L5_ROUTE_MISSING = 'L12P_L5_ROUTE_MISSING',
  L12P_DIRECT_WRITE_ATTEMPT = 'L12P_DIRECT_WRITE_ATTEMPT',
  L12P_REDIS_USED_AS_AUTHORITY = 'L12P_REDIS_USED_AS_AUTHORITY',
  L12P_CACHE_USED_AS_AUTHORITY = 'L12P_CACHE_USED_AS_AUTHORITY',

  // Surface / authority mismatches
  L12P_SURFACE_AUTHORITY_MISMATCH = 'L12P_SURFACE_AUTHORITY_MISMATCH',
  L12P_SURFACE_DISCIPLINE_MISMATCH = 'L12P_SURFACE_DISCIPLINE_MISMATCH',
  L12P_MATERIALIZATION_MODE_NOT_ALLOWED_FOR_SURFACE = 'L12P_MATERIALIZATION_MODE_NOT_ALLOWED_FOR_SURFACE',
  L12P_DURABLE_SURFACE_UNREGISTERED = 'L12P_DURABLE_SURFACE_UNREGISTERED',

  // Materialization mode safety
  L12P_CURRENT_AUTHORITY_WRITTEN_BY_REPLAY = 'L12P_CURRENT_AUTHORITY_WRITTEN_BY_REPLAY',
  L12P_CURRENT_AUTHORITY_WRITTEN_BY_SHADOW = 'L12P_CURRENT_AUTHORITY_WRITTEN_BY_SHADOW',
  L12P_CURRENT_WRITE_FROM_NON_LIVE_RUN = 'L12P_CURRENT_WRITE_FROM_NON_LIVE_RUN',
  L12P_REPLAY_WRITES_CURRENT = 'L12P_REPLAY_WRITES_CURRENT',
  L12P_BACKFILL_WRITES_CURRENT = 'L12P_BACKFILL_WRITES_CURRENT',
  L12P_HISTORICAL_APPEND_MISSING_LINEAGE = 'L12P_HISTORICAL_APPEND_MISSING_LINEAGE',
  L12P_HISTORICAL_FACT_MUTATED = 'L12P_HISTORICAL_FACT_MUTATED',
  L12P_HISTORICAL_CORRECTION_MISSING_REASON = 'L12P_HISTORICAL_CORRECTION_MISSING_REASON',
  L12P_HISTORICAL_FAMILY_REF_MISMATCH = 'L12P_HISTORICAL_FAMILY_REF_MISMATCH',

  // Current authority record
  L12P_CURRENT_RECORD_INCOMPLETE = 'L12P_CURRENT_RECORD_INCOMPLETE',
  L12P_CURRENT_RECORD_MISSING_EVIDENCE = 'L12P_CURRENT_RECORD_MISSING_EVIDENCE',
  L12P_CURRENT_RECORD_MISSING_REPLAY_HASH = 'L12P_CURRENT_RECORD_MISSING_REPLAY_HASH',
  L12P_CURRENT_SUPERSESSION_REASON_MISSING = 'L12P_CURRENT_SUPERSESSION_REASON_MISSING',
  L12P_CURRENT_SUPERSEDES_REF_MISSING = 'L12P_CURRENT_SUPERSEDES_REF_MISSING',
  L12P_CURRENT_RECORD_BLOCKED_READINESS = 'L12P_CURRENT_RECORD_BLOCKED_READINESS',

  // Evidence
  L12P_EVIDENCE_POINTER_INCOMPLETE = 'L12P_EVIDENCE_POINTER_INCOMPLETE',
  L12P_EVIDENCE_PATH_NON_DETERMINISTIC = 'L12P_EVIDENCE_PATH_NON_DETERMINISTIC',
  L12P_EVIDENCE_CHECKSUM_MISSING = 'L12P_EVIDENCE_CHECKSUM_MISSING',
  L12P_EVIDENCE_REPLAY_REF_MISSING = 'L12P_EVIDENCE_REPLAY_REF_MISSING',
  L12P_EVIDENCE_SUBJECT_KIND_MISMATCH = 'L12P_EVIDENCE_SUBJECT_KIND_MISMATCH',
  L12P_EVIDENCE_LINEAGE_MISSING = 'L12P_EVIDENCE_LINEAGE_MISSING',
  L12P_EVIDENCE_ORPHANED = 'L12P_EVIDENCE_ORPHANED',
  L12P_EVIDENCE_ARCHIVE_OUTSIDE_L5 = 'L12P_EVIDENCE_ARCHIVE_OUTSIDE_L5',

  // Read surface / read request / read result
  L12P_READ_SURFACE_UNREGISTERED = 'L12P_READ_SURFACE_UNREGISTERED',
  L12P_READ_MODE_ILLEGAL = 'L12P_READ_MODE_ILLEGAL',
  L12P_CONSUMER_NOT_ALLOWED = 'L12P_CONSUMER_NOT_ALLOWED',
  L12P_READ_SCOPE_REQUIRED_BUT_MISSING = 'L12P_READ_SCOPE_REQUIRED_BUT_MISSING',
  L12P_READ_SCENARIO_ID_REQUIRED_BUT_MISSING = 'L12P_READ_SCENARIO_ID_REQUIRED_BUT_MISSING',
  L12P_READ_SCENARIO_SET_ID_REQUIRED_BUT_MISSING = 'L12P_READ_SCENARIO_SET_ID_REQUIRED_BUT_MISSING',
  L12P_READ_RUN_ID_REQUIRED_BUT_MISSING = 'L12P_READ_RUN_ID_REQUIRED_BUT_MISSING',
  L12P_READ_EVIDENCE_REQUIRED_BUT_MISSING = 'L12P_READ_EVIDENCE_REQUIRED_BUT_MISSING',
  L12P_READ_LINEAGE_REQUIRED_BUT_MISSING = 'L12P_READ_LINEAGE_REQUIRED_BUT_MISSING',
  L12P_READ_REPLAY_HASH_REQUIRED_BUT_MISSING = 'L12P_READ_REPLAY_HASH_REQUIRED_BUT_MISSING',
  L12P_READ_RESTRICTION_PROFILE_REQUIRED_BUT_MISSING = 'L12P_READ_RESTRICTION_PROFILE_REQUIRED_BUT_MISSING',
  L12P_BLOCKED_READINESS_READ_BY_UNALLOWED_CONSUMER = 'L12P_BLOCKED_READINESS_READ_BY_UNALLOWED_CONSUMER',
  L12P_RAW_STORAGE_EXPOSED = 'L12P_RAW_STORAGE_EXPOSED',
  L12P_READ_RESULT_PAYLOAD_MISSING = 'L12P_READ_RESULT_PAYLOAD_MISSING',
  L12P_READ_FRESHNESS_MISMATCH = 'L12P_READ_FRESHNESS_MISMATCH',

  // Downstream consumption
  L12P_DOWNSTREAM_REBUILD_ATTEMPT = 'L12P_DOWNSTREAM_REBUILD_ATTEMPT',
  L12P_DOWNSTREAM_LOWER_LAYER_REF_REQUESTED = 'L12P_DOWNSTREAM_LOWER_LAYER_REF_REQUESTED',
  L12P_DOWNSTREAM_RESTRICTION_BYPASS = 'L12P_DOWNSTREAM_RESTRICTION_BYPASS',
  L12P_DOWNSTREAM_IGNORES_INVALIDATION = 'L12P_DOWNSTREAM_IGNORES_INVALIDATION',
  L12P_DOWNSTREAM_IGNORES_CONFIDENCE = 'L12P_DOWNSTREAM_IGNORES_CONFIDENCE',
  L12P_DOWNSTREAM_IGNORES_READINESS = 'L12P_DOWNSTREAM_IGNORES_READINESS',
  L12P_DOWNSTREAM_EVIDENCE_OMISSION = 'L12P_DOWNSTREAM_EVIDENCE_OMISSION',
  L12P_DOWNSTREAM_LINEAGE_OMISSION = 'L12P_DOWNSTREAM_LINEAGE_OMISSION',
  L12P_SCENARIO_AS_RECOMMENDATION = 'L12P_SCENARIO_AS_RECOMMENDATION',
  L12P_SCENARIO_AS_FINAL_JUDGMENT = 'L12P_SCENARIO_AS_FINAL_JUDGMENT',
  L12P_SCENARIO_AS_TRADE_INSTRUCTION = 'L12P_SCENARIO_AS_TRADE_INSTRUCTION',
  L12P_SCENARIO_AS_PREDICTION_CERTAINTY = 'L12P_SCENARIO_AS_PREDICTION_CERTAINTY',

  // Replay
  L12P_REPLAY_INPUT_SNAPSHOT_MISSING = 'L12P_REPLAY_INPUT_SNAPSHOT_MISSING',
  L12P_REPLAY_HASH_MISMATCH_HIDDEN = 'L12P_REPLAY_HASH_MISMATCH_HIDDEN',
  L12P_REPLAY_INVENTED_EVIDENCE = 'L12P_REPLAY_INVENTED_EVIDENCE',
  L12P_REPLAY_ERASED_TRIGGER = 'L12P_REPLAY_ERASED_TRIGGER',
  L12P_REPLAY_ERASED_INVALIDATION = 'L12P_REPLAY_ERASED_INVALIDATION',
  L12P_REPLAY_UPGRADED_READINESS = 'L12P_REPLAY_UPGRADED_READINESS',
  L12P_REPLAY_IGNORES_TEMPLATE_VERSION = 'L12P_REPLAY_IGNORES_TEMPLATE_VERSION',

  // Repair
  L12P_REPAIR_PARENT_MISSING = 'L12P_REPAIR_PARENT_MISSING',
  L12P_REPAIR_REASON_MISSING = 'L12P_REPAIR_REASON_MISSING',
  L12P_REPAIR_LINEAGE_MISSING = 'L12P_REPAIR_LINEAGE_MISSING',
  L12P_REPAIR_MUTATES_PRIOR_RUN = 'L12P_REPAIR_MUTATES_PRIOR_RUN',
  L12P_REPAIR_MASQUERADES_AS_LIVE = 'L12P_REPAIR_MASQUERADES_AS_LIVE',
  L12P_REPAIR_BYPASSES_SUPERSESSION = 'L12P_REPAIR_BYPASSES_SUPERSESSION',
  L12P_REPAIR_REMOVED_TRIGGER_WITHOUT_EVIDENCE = 'L12P_REPAIR_REMOVED_TRIGGER_WITHOUT_EVIDENCE',
  L12P_REPAIR_REMOVED_INVALIDATION_WITHOUT_EVIDENCE = 'L12P_REPAIR_REMOVED_INVALIDATION_WITHOUT_EVIDENCE',
  L12P_REPAIR_UPGRADED_CONFIDENCE_WITHOUT_EVIDENCE = 'L12P_REPAIR_UPGRADED_CONFIDENCE_WITHOUT_EVIDENCE',
  L12P_REPAIR_INVENTED_EVIDENCE = 'L12P_REPAIR_INVENTED_EVIDENCE',
  L12P_REPAIR_REUSES_PARENT_COMPUTE_RUN_ID = 'L12P_REPAIR_REUSES_PARENT_COMPUTE_RUN_ID',
}

export const ALL_L12_PERSISTENCE_VIOLATION_CODES: readonly L12PersistenceViolationCode[] =
  Object.values(L12PersistenceViolationCode);

export interface L12PersistenceViolationIssue {
  readonly code: L12PersistenceViolationCode;
  readonly message: string;
  readonly subject_ref?: string;
}

export function l12PersistenceIssueOf(
  code: L12PersistenceViolationCode,
  message: string,
  subject_ref?: string,
): L12PersistenceViolationIssue {
  return { code, message, subject_ref };
}

export interface L12PersistenceValidationResult {
  readonly ok: boolean;
  readonly issues: readonly L12PersistenceViolationIssue[];
}
