/**
 * L9.1 — Constitutional Violation Codes
 *
 * §9.1.8.2 / §9.1.10.1 — Every constitutional boundary failure carries a
 * typed code so audit records and validator decisions remain
 * deterministic.
 */

export enum L9ConstitutionalViolationCode {
  UNREGISTERED_DEPENDENCY = 'L9_UNREG_DEPENDENCY',
  UNREGISTERED_OUTPUT = 'L9_UNREG_OUTPUT',
  ILLEGAL_DEPENDENCY_USAGE = 'L9_ILLEGAL_DEP_USAGE',
  ILLEGAL_OUTPUT_CLASS = 'L9_ILLEGAL_OUTPUT_CLASS',
  ILLEGAL_CAPABILITY_CLAIM = 'L9_ILLEGAL_CAPABILITY',
  FORBIDDEN_JUDGMENT_SEMANTICS = 'L9_FORBIDDEN_JUDGMENT',
  FORBIDDEN_RECOMMENDATION_SEMANTICS = 'L9_FORBIDDEN_RECOMMENDATION',
  FORBIDDEN_SCENARIO_SEMANTICS = 'L9_FORBIDDEN_SCENARIO',
  FORBIDDEN_SCORE_SEMANTICS = 'L9_FORBIDDEN_SCORE',
  FORBIDDEN_HYPOTHESIS_SEMANTICS = 'L9_FORBIDDEN_HYPOTHESIS',
  FORBIDDEN_ACTION_BIAS = 'L9_FORBIDDEN_ACTION_BIAS',
  VALIDATION_TRUTH_REDEFINITION = 'L9_VALIDATION_TRUTH_REDEFINE',
  CONTRADICTION_POSTURE_IGNORED = 'L9_CONTRADICTION_POSTURE_IGNORED',
  RESTRICTION_POSTURE_IGNORED = 'L9_RESTRICTION_POSTURE_IGNORED',
  RESTRICTION_BYPASS = 'L9_RESTRICTION_BYPASS',
  REGIME_POSTURE_IGNORED = 'L9_REGIME_POSTURE_IGNORED',
  REGIME_REINTERPRETATION = 'L9_REGIME_REINTERPRETATION',
  AMBIGUITY_LAUNDERING = 'L9_AMBIGUITY_LAUNDERING',
  CAUSAL_LAUNDERING = 'L9_CAUSAL_LAUNDERING',
  TEMPORAL_THEATRICS = 'L9_TEMPORAL_THEATRICS',
  STALE_SEQUENCE_MASQUERADE = 'L9_STALE_SEQUENCE_MASQUERADE',
  RAW_DATA_SEQUENCE_INVENTION = 'L9_RAW_DATA_SEQUENCE_INVENTION',
  RAW_L6_REVALIDATION_BYPASS = 'L9_RAW_L6_REVALIDATION_BYPASS',
  LOWER_LAYER_REDEFINITION = 'L9_LOWER_LAYER_REDEFINE',
  PRIMITIVE_REINTERPRETATION = 'L9_PRIMITIVE_REINTERPRETATION',
  STORAGE_BYPASS = 'L9_STORAGE_BYPASS',
  CONFIDENCE_LAW_OVERRIDE = 'L9_CONFIDENCE_LAW_OVERRIDE',
  MISSING_LINEAGE = 'L9_MISSING_LINEAGE',
  EVIDENCE_ONLY_AS_DECISIVE = 'L9_EVIDENCE_ONLY_AS_DECISIVE',
  LATE_LAYER_CONSUMPTION = 'L9_LATE_LAYER_CONSUMPTION',
}

export const ALL_L9_VIOLATION_CODES: readonly L9ConstitutionalViolationCode[] =
  Object.values(L9ConstitutionalViolationCode);

export class L9ConstitutionalError extends Error {
  public readonly code: L9ConstitutionalViolationCode;
  public readonly details: Record<string, unknown>;

  constructor(
    code: L9ConstitutionalViolationCode,
    message: string,
    details: Record<string, unknown> = {},
  ) {
    super(`[${code}] ${message}`);
    this.name = 'L9ConstitutionalError';
    this.code = code;
    this.details = details;
  }
}
