/**
 * Bridge Certification Scope
 *
 * §8 — Scope honesty contract. Every bridge cert artifact declares
 * its scope so it cannot be confused with full unified CIP.1.
 */

export enum BridgeCertificationScope {
  AJP1_ACTIVE_PRODUCT_PIPELINE = 'AJP1_ACTIVE_PRODUCT_PIPELINE',
  CIP05_CERTIFIED_DOWNSTREAM_RUNTIME = 'CIP05_CERTIFIED_DOWNSTREAM_RUNTIME',
}

export type BridgeUpstreamLayer =
  | 'L1' | 'L2' | 'L3' | 'L4' | 'L5' | 'L6'
  | 'L7' | 'L8' | 'L9' | 'L10' | 'L11' | 'L12';

export enum BridgeReconciliationFlag {
  ACTIVE_PIPELINE_LACKS_CERTIFIED_IDENTITY_GATING =
    'ACTIVE_PIPELINE_LACKS_CERTIFIED_IDENTITY_GATING',
  ACTIVE_TIMING_SEMANTICS_DIVERGE_FROM_L9 =
    'ACTIVE_TIMING_SEMANTICS_DIVERGE_FROM_L9',
  ACTIVE_SCENARIO_SHAPE_DIVERGES_FROM_L12 =
    'ACTIVE_SCENARIO_SHAPE_DIVERGES_FROM_L12',
  ACTIVE_AI_PATH_NOT_L13_GOVERNED =
    'ACTIVE_AI_PATH_NOT_L13_GOVERNED',
  CERTIFIED_RUNTIME_DEPENDS_ON_SYNTHETIC_UPSTREAM =
    'CERTIFIED_RUNTIME_DEPENDS_ON_SYNTHETIC_UPSTREAM',
  PRODUCT_DELIVERY_NOT_YET_FULLY_L14_WIRED =
    'PRODUCT_DELIVERY_NOT_YET_FULLY_L14_WIRED',
  CIP05_L13_RUNTIME_INVOCATION_DEFERRED_TO_CIP06 =
    'CIP05_L13_RUNTIME_INVOCATION_DEFERRED_TO_CIP06',
}
