/**
 * L8.2 — Regime Output Classes and Object Violation Codes
 *
 * §8.2.10.4 — Object-level audit codes for L8.2. Disjoint from L8.1
 * boundary violations so audit records remain unambiguous about which
 * tier rejected a regime artifact.
 *
 * §8.2.8 — Regime outputs that L8.2 is responsible for contract-wise
 * are the four object-model surfaces below. The read-surface is
 * provided by L8.1 at the boundary level and wraps these.
 */

/**
 * §8.2.10.2 — The four L8.2 first-class regime output objects.
 *
 * Distinct from the L8.1 output-surface taxonomy, which additionally
 * registers an evidence-backed read surface. The L8.2 objects must
 * remain separate contracts and can never collapse into one "does-
 * everything" regime verdict (§8.2.8).
 */
export enum L8RegimeOutputClass {
  REGIME_STATE = 'REGIME_STATE',
  REGIME_CONFIDENCE_PROFILE = 'REGIME_CONFIDENCE_PROFILE',
  REGIME_TRANSITION_PROFILE = 'REGIME_TRANSITION_PROFILE',
  REGIME_MULTIPLIER_PROFILE = 'REGIME_MULTIPLIER_PROFILE',
}

export const ALL_L8_REGIME_OUTPUT_CLASSES: readonly L8RegimeOutputClass[] =
  Object.values(L8RegimeOutputClass);

/**
 * §8.2.10.4 — Object-level violation codes. Prefixed `L8O_` so the L8.1
 * boundary log and L8.2 object log remain easy to distinguish.
 */
export enum L8RegimeObjectViolationCode {
  // Subject / template
  SUBJECT_UNREGISTERED_FAMILY = 'L8O_SUBJECT_UNREGISTERED_FAMILY',
  SUBJECT_MISSING_IDENTITY = 'L8O_SUBJECT_MISSING_IDENTITY',
  SUBJECT_MISSING_SCOPE = 'L8O_SUBJECT_MISSING_SCOPE',
  SUBJECT_SCOPE_ILLEGAL_FOR_FAMILY = 'L8O_SUBJECT_SCOPE_ILLEGAL_FOR_FAMILY',
  SUBJECT_MISSING_TIME_ANCHOR = 'L8O_SUBJECT_MISSING_TIME_ANCHOR',
  SUBJECT_MISSING_TEMPLATE = 'L8O_SUBJECT_MISSING_TEMPLATE',
  SUBJECT_LIFECYCLE_FLAG_MISMATCH = 'L8O_SUBJECT_LIFECYCLE_FLAG_MISMATCH',

  // Family / class legality
  FAMILY_UNREGISTERED = 'L8O_FAMILY_UNREGISTERED',
  CLASS_UNREGISTERED = 'L8O_CLASS_UNREGISTERED',
  CLASS_NOT_IN_FAMILY = 'L8O_CLASS_NOT_IN_FAMILY',
  CLASS_SCOPE_ILLEGAL = 'L8O_CLASS_SCOPE_ILLEGAL',

  // Regime state identity / completeness
  STATE_MISSING_STATE_ID = 'L8O_STATE_MISSING_STATE_ID',
  STATE_MISSING_PRIMARY_REGIME = 'L8O_STATE_MISSING_PRIMARY_REGIME',
  STATE_SECONDARY_EQUALS_PRIMARY = 'L8O_STATE_SECONDARY_EQUALS_PRIMARY',
  STATE_SECONDARY_WRONG_FAMILY = 'L8O_STATE_SECONDARY_WRONG_FAMILY',
  STATE_MISSING_SCOPE = 'L8O_STATE_MISSING_SCOPE',
  STATE_MISSING_TIME_ANCHOR = 'L8O_STATE_MISSING_TIME_ANCHOR',
  STATE_MISSING_TEMPLATE = 'L8O_STATE_MISSING_TEMPLATE',
  STATE_MISSING_VERSION = 'L8O_STATE_MISSING_VERSION',
  STATE_MISSING_EVIDENCE = 'L8O_STATE_MISSING_EVIDENCE',
  STATE_MISSING_VALIDATION_REFS = 'L8O_STATE_MISSING_VALIDATION_REFS',
  STATE_MISSING_EVIDENCE_PACK = 'L8O_STATE_MISSING_EVIDENCE_PACK',
  STATE_MISSING_INPUT_SNAPSHOT = 'L8O_STATE_MISSING_INPUT_SNAPSHOT',
  STATE_MISSING_MULTIPLIER_PROFILE = 'L8O_STATE_MISSING_MULTIPLIER_PROFILE',
  STATE_MISSING_LINEAGE = 'L8O_STATE_MISSING_LINEAGE',
  STATE_MISSING_REPLAY_HASH = 'L8O_STATE_MISSING_REPLAY_HASH',
  STATE_MISSING_COMPUTE_RUN_ID = 'L8O_STATE_MISSING_COMPUTE_RUN_ID',
  STATE_MISSING_POLICY_VERSION = 'L8O_STATE_MISSING_POLICY_VERSION',
  STATE_MISSING_MATERIALIZATION_MODE = 'L8O_STATE_MISSING_MATERIALIZATION',

  // Confidence / transition
  STATE_CONFIDENCE_OUT_OF_RANGE = 'L8O_STATE_CONFIDENCE_OUT_OF_RANGE',
  STATE_CONFIDENCE_BAND_INCONSISTENT = 'L8O_STATE_CONFIDENCE_BAND_INCONSISTENT',
  STATE_SECONDARY_CONFIDENCE_MISSING = 'L8O_STATE_SECONDARY_CONFIDENCE_MISSING',
  STATE_SECONDARY_CONFIDENCE_PRESENT_BUT_NO_SECONDARY =
    'L8O_STATE_SECONDARY_CONFIDENCE_DANGLING',
  STATE_TRANSITION_SCORE_OUT_OF_RANGE = 'L8O_STATE_TRANSITION_SCORE_OOR',
  STATE_TRANSITION_CLASS_INCONSISTENT = 'L8O_STATE_TRANSITION_CLASS_INCONSISTENT',
  STATE_AMBIGUITY_SCORE_OUT_OF_RANGE = 'L8O_STATE_AMBIGUITY_SCORE_OOR',
  STATE_STALENESS_SCORE_OUT_OF_RANGE = 'L8O_STATE_STALENESS_SCORE_OOR',
  STATE_DEGRADATION_SCORE_OUT_OF_RANGE = 'L8O_STATE_DEGRADATION_SCORE_OOR',

  // Coexistence / collision law
  COEXISTENCE_ILLEGAL_COLLISION = 'L8O_COEXISTENCE_ILLEGAL_COLLISION',
  COEXISTENCE_FAKE_CLEAN_SINGLE = 'L8O_COEXISTENCE_FAKE_CLEAN_SINGLE',
  COEXISTENCE_MISSING_TRANSITION = 'L8O_COEXISTENCE_MISSING_TRANSITION',
  COEXISTENCE_MISSING_AMBIGUITY = 'L8O_COEXISTENCE_MISSING_AMBIGUITY',
  COEXISTENCE_LIFECYCLE_VIOLATION = 'L8O_COEXISTENCE_LIFECYCLE_VIOLATION',
  COEXISTENCE_CROSS_FAMILY_ILLEGAL = 'L8O_COEXISTENCE_CROSS_FAMILY_ILLEGAL',
  COEXISTENCE_CROSS_FAMILY_DUPLICATE = 'L8O_COEXISTENCE_CROSS_FAMILY_DUPLICATE',

  // Output object legality
  OUTPUT_UNREGISTERED_CLASS = 'L8O_OUTPUT_UNREGISTERED_CLASS',
  OUTPUT_MISSING_REGIME_ANCHOR = 'L8O_OUTPUT_MISSING_REGIME_ANCHOR',
  OUTPUT_JUDGMENT_LEAK = 'L8O_OUTPUT_JUDGMENT_LEAK',
  OUTPUT_SCENARIO_LEAK = 'L8O_OUTPUT_SCENARIO_LEAK',
  OUTPUT_SCORE_OVERRIDE = 'L8O_OUTPUT_SCORE_OVERRIDE',
  OUTPUT_MISSING_EVIDENCE = 'L8O_OUTPUT_MISSING_EVIDENCE',
  OUTPUT_MISSING_CONTRADICTION_POSTURE = 'L8O_OUTPUT_MISSING_CONTRADICTION_POSTURE',
  OUTPUT_MISSING_RESTRICTION_POSTURE = 'L8O_OUTPUT_MISSING_RESTRICTION_POSTURE',
  OUTPUT_MISSING_AMBIGUITY_POSTURE = 'L8O_OUTPUT_MISSING_AMBIGUITY_POSTURE',
}

export const ALL_L8_REGIME_OBJECT_VIOLATION_CODES:
  readonly L8RegimeObjectViolationCode[] =
    Object.values(L8RegimeObjectViolationCode);
