/**
 * L7.3 — Contract Violation Codes
 *
 * §7.3.8.2 — `L7ContractViolationCode`. Disjoint from L7.1 boundary codes
 * and L7.2 object codes so audit records remain unambiguous about which
 * tier rejected an artifact.
 */

export enum L7ContractViolationCode {
  // Subject contract (§7.3.2.5)
  SUBJECT_CONTRACT_INCOMPLETE_FIELD = 'L7C_SUBJECT_CONTRACT_INCOMPLETE_FIELD',
  SUBJECT_CONTRACT_MISSING_VERSION = 'L7C_SUBJECT_CONTRACT_MISSING_VERSION',
  SUBJECT_CONTRACT_MISSING_INTENT = 'L7C_SUBJECT_CONTRACT_MISSING_INTENT',
  SUBJECT_CONTRACT_MISSING_SUPPORT_INPUTS = 'L7C_SUBJECT_CONTRACT_MISSING_SUPPORT_INPUTS',
  SUBJECT_CONTRACT_MISSING_CHALLENGE_INPUTS = 'L7C_SUBJECT_CONTRACT_MISSING_CHALLENGE_INPUTS',
  SUBJECT_CONTRACT_MISSING_TEMPORAL = 'L7C_SUBJECT_CONTRACT_MISSING_TEMPORAL',
  SUBJECT_CONTRACT_MISSING_STALENESS_POLICY = 'L7C_SUBJECT_CONTRACT_MISSING_STALENESS_POLICY',
  SUBJECT_CONTRACT_MISSING_RULE_REFS = 'L7C_SUBJECT_CONTRACT_MISSING_RULE_REFS',
  SUBJECT_CONTRACT_MISSING_CONFIDENCE_SPEC = 'L7C_SUBJECT_CONTRACT_MISSING_CONFIDENCE_SPEC',
  SUBJECT_CONTRACT_MISSING_RESTRICTION_SPEC = 'L7C_SUBJECT_CONTRACT_MISSING_RESTRICTION_SPEC',
  SUBJECT_CONTRACT_MISSING_MATERIALIZATION_POLICY = 'L7C_SUBJECT_CONTRACT_MISSING_MATERIALIZATION_POLICY',
  SUBJECT_CONTRACT_MISSING_EVIDENCE_PACK_POLICY = 'L7C_SUBJECT_CONTRACT_MISSING_EVIDENCE_PACK_POLICY',
  SUBJECT_CONTRACT_MISSING_LINEAGE = 'L7C_SUBJECT_CONTRACT_MISSING_LINEAGE',

  // Output contract (§7.3.3.5 + §7.3.3.7)
  OUTPUT_CONTRACT_INCOMPLETE_FIELD = 'L7C_OUTPUT_CONTRACT_INCOMPLETE_FIELD',
  OUTPUT_CONTRACT_MISSING_VERSION = 'L7C_OUTPUT_CONTRACT_MISSING_VERSION',
  OUTPUT_CONTRACT_MISSING_SUBJECT_LINK = 'L7C_OUTPUT_CONTRACT_MISSING_SUBJECT_LINK',
  OUTPUT_CONTRACT_MISSING_SUPPORT_REFS = 'L7C_OUTPUT_CONTRACT_MISSING_SUPPORT_REFS',
  OUTPUT_CONTRACT_MISSING_CONTRADICTION_BUNDLE = 'L7C_OUTPUT_CONTRACT_MISSING_CONTRADICTION_BUNDLE',
  OUTPUT_CONTRACT_MISSING_CONFIDENCE_LINK = 'L7C_OUTPUT_CONTRACT_MISSING_CONFIDENCE_LINK',
  OUTPUT_CONTRACT_MISSING_RESTRICTION_PROFILE = 'L7C_OUTPUT_CONTRACT_MISSING_RESTRICTION_PROFILE',
  OUTPUT_CONTRACT_MISSING_REPLAY_LINEAGE = 'L7C_OUTPUT_CONTRACT_MISSING_REPLAY_LINEAGE',
  OUTPUT_CONTRACT_HIDDEN_CLEANLINESS = 'L7C_OUTPUT_CONTRACT_HIDDEN_CLEANLINESS',
  OUTPUT_CONTRACT_CLASS_MODIFIER_INCONSISTENT = 'L7C_OUTPUT_CONTRACT_CLASS_MODIFIER_INCONSISTENT',
  OUTPUT_CONTRACT_BAND_SCORE_MISMATCH = 'L7C_OUTPUT_CONTRACT_BAND_SCORE_MISMATCH',
  OUTPUT_CONTRACT_SCORE_OUT_OF_RANGE = 'L7C_OUTPUT_CONTRACT_SCORE_OUT_OF_RANGE',
  OUTPUT_CONTRACT_RUNTIME_INTEGRITY_VIOLATION = 'L7C_OUTPUT_CONTRACT_RUNTIME_INTEGRITY_VIOLATION',
  OUTPUT_CONTRACT_MATERIALIZATION_NOT_READY = 'L7C_OUTPUT_CONTRACT_MATERIALIZATION_NOT_READY',

  // Contradiction bundle contract (§7.3.4.5)
  CONTRADICTION_CONTRACT_INCOMPLETE_FIELD = 'L7C_CONTRADICTION_CONTRACT_INCOMPLETE_FIELD',
  CONTRADICTION_CONTRACT_MISSING_VERSION = 'L7C_CONTRADICTION_CONTRACT_MISSING_VERSION',
  CONTRADICTION_CONTRACT_UNTYPED_RECORD = 'L7C_CONTRADICTION_CONTRACT_UNTYPED_RECORD',
  CONTRADICTION_CONTRACT_SEVERITY_MISMATCH = 'L7C_CONTRADICTION_CONTRACT_SEVERITY_MISMATCH',
  CONTRADICTION_CONTRACT_DOMINANT_FAMILY_MISMATCH = 'L7C_CONTRADICTION_CONTRACT_DOMINANT_FAMILY_MISMATCH',
  CONTRADICTION_CONTRACT_CLUSTER_COUNT_MISMATCH = 'L7C_CONTRADICTION_CONTRACT_CLUSTER_COUNT_MISMATCH',
  CONTRADICTION_CONTRACT_BLOCKED_SURFACES_MISSING = 'L7C_CONTRADICTION_CONTRACT_BLOCKED_SURFACES_MISSING',
  CONTRADICTION_CONTRACT_STALE_REFS_MISSING = 'L7C_CONTRADICTION_CONTRACT_STALE_REFS_MISSING',
  CONTRADICTION_CONTRACT_MISSING_LINEAGE = 'L7C_CONTRADICTION_CONTRACT_MISSING_LINEAGE',
  CONTRADICTION_CONTRACT_MISSING_REPLAY_HASH = 'L7C_CONTRADICTION_CONTRACT_MISSING_REPLAY_HASH',

  // Confidence assessment contract (§7.3.5.4)
  CONFIDENCE_CONTRACT_INCOMPLETE_FIELD = 'L7C_CONFIDENCE_CONTRACT_INCOMPLETE_FIELD',
  CONFIDENCE_CONTRACT_MISSING_VERSION = 'L7C_CONFIDENCE_CONTRACT_MISSING_VERSION',
  CONFIDENCE_CONTRACT_SCORE_OUT_OF_RANGE = 'L7C_CONFIDENCE_CONTRACT_SCORE_OUT_OF_RANGE',
  CONFIDENCE_CONTRACT_BAND_MISMATCH = 'L7C_CONFIDENCE_CONTRACT_BAND_MISMATCH',
  CONFIDENCE_CONTRACT_FACTORS_INCOMPLETE = 'L7C_CONFIDENCE_CONTRACT_FACTORS_INCOMPLETE',
  CONFIDENCE_CONTRACT_WEIGHTS_INCOMPLETE = 'L7C_CONFIDENCE_CONTRACT_WEIGHTS_INCOMPLETE',
  CONFIDENCE_CONTRACT_CAP_CHAIN_ILLEGAL = 'L7C_CONFIDENCE_CONTRACT_CAP_CHAIN_ILLEGAL',
  CONFIDENCE_CONTRACT_PENALTY_MISSING = 'L7C_CONFIDENCE_CONTRACT_PENALTY_MISSING',
  CONFIDENCE_CONTRACT_RATIONALE_MISSING = 'L7C_CONFIDENCE_CONTRACT_RATIONALE_MISSING',
  CONFIDENCE_CONTRACT_RESTRICTION_LINK_MISSING = 'L7C_CONFIDENCE_CONTRACT_RESTRICTION_LINK_MISSING',
  CONFIDENCE_CONTRACT_MISSING_LINEAGE = 'L7C_CONFIDENCE_CONTRACT_MISSING_LINEAGE',

  // Restriction profile contract (§7.3.6.4)
  RESTRICTION_CONTRACT_INCOMPLETE_FIELD = 'L7C_RESTRICTION_CONTRACT_INCOMPLETE_FIELD',
  RESTRICTION_CONTRACT_MISSING_VERSION = 'L7C_RESTRICTION_CONTRACT_MISSING_VERSION',
  RESTRICTION_CONTRACT_RIGHT_UNREGISTERED = 'L7C_RESTRICTION_CONTRACT_RIGHT_UNREGISTERED',
  RESTRICTION_CONTRACT_RIGHTS_INTERNAL_INCONSISTENT = 'L7C_RESTRICTION_CONTRACT_RIGHTS_INTERNAL_INCONSISTENT',
  RESTRICTION_CONTRACT_RIGHTS_CONFLICT = 'L7C_RESTRICTION_CONTRACT_RIGHTS_CONFLICT',
  RESTRICTION_CONTRACT_REASONS_MISSING = 'L7C_RESTRICTION_CONTRACT_REASONS_MISSING',
  RESTRICTION_CONTRACT_DISCLOSURE_REQUIRED_BUT_MISSING = 'L7C_RESTRICTION_CONTRACT_DISCLOSURE_REQUIRED_BUT_MISSING',
  RESTRICTION_CONTRACT_INCONSISTENT_WITH_VALIDATION = 'L7C_RESTRICTION_CONTRACT_INCONSISTENT_WITH_VALIDATION',
  RESTRICTION_CONTRACT_INCONSISTENT_WITH_CONFIDENCE = 'L7C_RESTRICTION_CONTRACT_INCONSISTENT_WITH_CONFIDENCE',
  RESTRICTION_CONTRACT_INCONSISTENT_WITH_CONTRADICTION = 'L7C_RESTRICTION_CONTRACT_INCONSISTENT_WITH_CONTRADICTION',
  RESTRICTION_CONTRACT_DOWNSTREAM_AMBIGUOUS = 'L7C_RESTRICTION_CONTRACT_DOWNSTREAM_AMBIGUOUS',
  RESTRICTION_CONTRACT_MISSING_LINEAGE = 'L7C_RESTRICTION_CONTRACT_MISSING_LINEAGE',

  // Compatibility (§7.3.7.3)
  COMPATIBILITY_PROHIBITED_CHANGE = 'L7C_COMPATIBILITY_PROHIBITED_CHANGE',
  COMPATIBILITY_BREAKING_SEMANTIC = 'L7C_COMPATIBILITY_BREAKING_SEMANTIC',
  COMPATIBILITY_MIGRATION_REQUIRED_NOT_FLAGGED = 'L7C_COMPATIBILITY_MIGRATION_REQUIRED_NOT_FLAGGED',
  COMPATIBILITY_VERSION_REGRESSION = 'L7C_COMPATIBILITY_VERSION_REGRESSION',

  // Replay (§7.3.7.4 + §7.3.7.5)
  REPLAY_HASH_MISSING = 'L7C_REPLAY_HASH_MISSING',
  REPLAY_HASH_UNSTABLE = 'L7C_REPLAY_HASH_UNSTABLE',
  REPLAY_LINEAGE_MISSING = 'L7C_REPLAY_LINEAGE_MISSING',
}

export const ALL_CONTRACT_VIOLATION_CODES: readonly L7ContractViolationCode[] =
  Object.values(L7ContractViolationCode);

export interface L7ContractViolation {
  readonly code: L7ContractViolationCode;
  readonly message: string;
  readonly path: string;
  readonly details?: Record<string, unknown>;
}

export class L7ContractError extends Error {
  public readonly code: L7ContractViolationCode;
  public readonly details: Record<string, unknown>;

  constructor(
    code: L7ContractViolationCode,
    message: string,
    details: Record<string, unknown> = {},
  ) {
    super(`[${code}] ${message}`);
    this.name = 'L7ContractError';
    this.code = code;
    this.details = details;
  }
}
