/**
 * L7.6 — Confidence Violation Codes
 *
 * §7.6 — Disjoint code space for the reliance-governance layer. These
 * codes describe failures in:
 *
 *   - factor model legality
 *   - raw-score / band derivation
 *   - cap-chain legality and precedence
 *   - contradiction-penalty legality
 *   - restriction-derivation legality
 *   - local-regime-compatibility legality
 *   - historical-reliability legality
 *   - replay-fidelity of confidence/restriction outputs
 *
 * They live in their own enum so an audit consumer can read a code's
 * prefix and immediately know it came from the L7.6 reliance layer
 * (not L7.1 boundary law, L7.2 object law, L7.3 contract law,
 *  L7.4 runtime law, or L7.5 semantic law).
 */

export enum L7ConfidenceViolationCode {
  // Factor model
  UNKNOWN_FACTOR_GROUP = 'L7_6_UNKNOWN_FACTOR_GROUP',
  FACTOR_GROUP_NOT_REGISTERED = 'L7_6_FACTOR_GROUP_NOT_REGISTERED',
  FACTOR_COMPONENT_MISSING = 'L7_6_FACTOR_COMPONENT_MISSING',
  FACTOR_COMPONENT_OUT_OF_RANGE = 'L7_6_FACTOR_COMPONENT_OUT_OF_RANGE',
  FACTOR_WEIGHT_NOT_DECLARED = 'L7_6_FACTOR_WEIGHT_NOT_DECLARED',
  FACTOR_WEIGHT_OUT_OF_RANGE = 'L7_6_FACTOR_WEIGHT_OUT_OF_RANGE',
  FACTOR_WEIGHTS_NOT_VERSIONED = 'L7_6_FACTOR_WEIGHTS_NOT_VERSIONED',

  // Score / band law
  RAW_SCORE_OUT_OF_RANGE = 'L7_6_RAW_SCORE_OUT_OF_RANGE',
  CAPPED_SCORE_OUT_OF_RANGE = 'L7_6_CAPPED_SCORE_OUT_OF_RANGE',
  CAPPED_SCORE_EXCEEDS_RAW = 'L7_6_CAPPED_SCORE_EXCEEDS_RAW',
  BAND_DOES_NOT_MATCH_SCORE = 'L7_6_BAND_DOES_NOT_MATCH_SCORE',
  UNKNOWN_BAND = 'L7_6_UNKNOWN_BAND',

  // Cap-chain law
  UNKNOWN_CAP_CLASS = 'L7_6_UNKNOWN_CAP_CLASS',
  CAP_CLASS_NOT_REGISTERED = 'L7_6_CAP_CLASS_NOT_REGISTERED',
  CAP_CHAIN_NOT_TRUTH_RESTRICTIVE = 'L7_6_CAP_CHAIN_NOT_TRUTH_RESTRICTIVE',
  CAP_CHAIN_PRECEDENCE_VIOLATED = 'L7_6_CAP_CHAIN_PRECEDENCE_VIOLATED',
  CAP_REQUIRED_BUT_NOT_APPLIED = 'L7_6_CAP_REQUIRED_BUT_NOT_APPLIED',
  CLEAN_CONFIDENCE_MASQUERADE = 'L7_6_CLEAN_CONFIDENCE_MASQUERADE',

  // Contradiction-penalty law
  UNKNOWN_PENALTY_CLASS = 'L7_6_UNKNOWN_PENALTY_CLASS',
  CONTRADICTION_PRESENT_NO_PENALTY = 'L7_6_CONTRADICTION_PRESENT_NO_PENALTY',
  PENALTY_INFLATED_BEYOND_BUNDLE = 'L7_6_PENALTY_INFLATED_BEYOND_BUNDLE',
  PENALTY_AND_CAP_BLURRED = 'L7_6_PENALTY_AND_CAP_BLURRED',

  // Restriction-derivation law
  UNKNOWN_RIGHT = 'L7_6_UNKNOWN_RIGHT',
  RIGHT_NOT_REGISTERED = 'L7_6_RIGHT_NOT_REGISTERED',
  RIGHTS_BROADER_THAN_STATE_JUSTIFIES = 'L7_6_RIGHTS_BROADER_THAN_STATE_JUSTIFIES',
  RIGHTS_NARROWER_THAN_STATE_REQUIRES = 'L7_6_RIGHTS_NARROWER_THAN_STATE_REQUIRES',
  REQUIRED_DISCLOSURE_MISSING = 'L7_6_REQUIRED_DISCLOSURE_MISSING',
  REQUIRED_CONFIRMATION_MISSING = 'L7_6_REQUIRED_CONFIRMATION_MISSING',
  EVIDENCE_ONLY_INCONSISTENT = 'L7_6_EVIDENCE_ONLY_INCONSISTENT',
  RESTRICTION_REASONS_MISSING = 'L7_6_RESTRICTION_REASONS_MISSING',
  RESTRICTION_PROFILE_REF_MISSING = 'L7_6_RESTRICTION_PROFILE_REF_MISSING',

  // Local-regime-compatibility law
  REGIME_FACTOR_OUT_OF_BOUNDS = 'L7_6_REGIME_FACTOR_OUT_OF_BOUNDS',
  REGIME_FACTOR_IMPERSONATES_FINAL_REGIME = 'L7_6_REGIME_FACTOR_IMPERSONATES_FINAL_REGIME',
  REGIME_FACTOR_OVERRIDES_CONTRADICTION = 'L7_6_REGIME_FACTOR_OVERRIDES_CONTRADICTION',
  REGIME_FACTOR_OVERRIDES_STALE_OR_DEGRADED = 'L7_6_REGIME_FACTOR_OVERRIDES_STALE_OR_DEGRADED',
  REGIME_FACTOR_USED_WITHOUT_DECLARATION = 'L7_6_REGIME_FACTOR_USED_WITHOUT_DECLARATION',

  // Historical-reliability law
  HISTORICAL_RELIABILITY_OUT_OF_BOUNDS = 'L7_6_HISTORICAL_RELIABILITY_OUT_OF_BOUNDS',
  HISTORICAL_RELIABILITY_OVERRIDES_CONTRADICTION = 'L7_6_HISTORICAL_RELIABILITY_OVERRIDES_CONTRADICTION',
  HISTORICAL_RELIABILITY_LINEAGE_MISSING = 'L7_6_HISTORICAL_RELIABILITY_LINEAGE_MISSING',

  // Replay / lineage law
  CONFIDENCE_REPLAY_HASH_MISSING = 'L7_6_CONFIDENCE_REPLAY_HASH_MISSING',
  CONFIDENCE_LINEAGE_INCOMPLETE = 'L7_6_CONFIDENCE_LINEAGE_INCOMPLETE',
  RESTRICTION_REPLAY_HASH_MISSING = 'L7_6_RESTRICTION_REPLAY_HASH_MISSING',

  // Policy versioning law
  CONFIDENCE_POLICY_VERSION_MISSING = 'L7_6_CONFIDENCE_POLICY_VERSION_MISSING',
  CONFIDENCE_POLICY_VERSION_NOT_REGISTERED = 'L7_6_CONFIDENCE_POLICY_VERSION_NOT_REGISTERED',
}

export const ALL_L7_CONFIDENCE_VIOLATION_CODES: readonly L7ConfidenceViolationCode[] =
  Object.values(L7ConfidenceViolationCode);

export interface L7ConfidenceViolation {
  readonly code: L7ConfidenceViolationCode;
  readonly source: string;
  readonly subject_id: string | null;
  readonly factor_group: string | null;
  readonly cap_class: string | null;
  readonly right: string | null;
  readonly detail: string;
  readonly context: Record<string, unknown>;
}
