/**
 * L7.4 — Runtime Violation Codes
 *
 * §7.4.9.4 — `L7RuntimeViolationCode`. Disjoint from L7.1 boundary codes,
 * L7.2 object codes, and L7.3 contract codes so an audit record's tier
 * remains unambiguous from its violation code alone.
 *
 * Every code begins with the prefix `L7R_` to identify the runtime tier.
 */

export enum L7RuntimeViolationCode {
  // DAG legality (§7.4.1)
  DAG_ILLEGAL_NODE_CLASS = 'L7R_DAG_ILLEGAL_NODE_CLASS',
  DAG_ILLEGAL_EDGE_CLASS = 'L7R_DAG_ILLEGAL_EDGE_CLASS',
  DAG_ILLEGAL_EDGE_TRANSITION = 'L7R_DAG_ILLEGAL_EDGE_TRANSITION',
  DAG_NODE_STAGE_MISMATCH = 'L7R_DAG_NODE_STAGE_MISMATCH',
  DAG_CYCLE_DETECTED = 'L7R_DAG_CYCLE_DETECTED',
  DAG_UNRESOLVED_DEPENDENCY = 'L7R_DAG_UNRESOLVED_DEPENDENCY',
  DAG_MISSING_TERMINAL_NODE = 'L7R_DAG_MISSING_TERMINAL_NODE',
  DAG_NON_DETERMINISTIC_ORDER = 'L7R_DAG_NON_DETERMINISTIC_ORDER',
  DAG_DUPLICATE_NODE_ID = 'L7R_DAG_DUPLICATE_NODE_ID',

  // Claim assembly (§7.4.3)
  ASSEMBLY_UNREGISTERED_TEMPLATE = 'L7R_ASSEMBLY_UNREGISTERED_TEMPLATE',
  ASSEMBLY_ILLEGAL_SCOPE_BINDING = 'L7R_ASSEMBLY_ILLEGAL_SCOPE_BINDING',
  ASSEMBLY_MISSING_SUPPORT_SURFACE = 'L7R_ASSEMBLY_MISSING_SUPPORT_SURFACE',
  ASSEMBLY_MISSING_CHALLENGE_SURFACE = 'L7R_ASSEMBLY_MISSING_CHALLENGE_SURFACE',
  ASSEMBLY_MATERIALITY_MISSING = 'L7R_ASSEMBLY_MATERIALITY_MISSING',
  ASSEMBLY_LINEAGE_INCOMPLETE = 'L7R_ASSEMBLY_LINEAGE_INCOMPLETE',
  ASSEMBLY_JUDGMENT_LEAK = 'L7R_ASSEMBLY_JUDGMENT_LEAK',
  ASSEMBLY_RISK_OVERHANG_UNDECLARED = 'L7R_ASSEMBLY_RISK_OVERHANG_UNDECLARED',
  ASSEMBLY_INSTANCE_INCOMPLETE = 'L7R_ASSEMBLY_INSTANCE_INCOMPLETE',
  ASSEMBLY_NON_DETERMINISTIC_ID = 'L7R_ASSEMBLY_NON_DETERMINISTIC_ID',

  // Support surface resolution (§7.4.4)
  SUPPORT_UNDECLARED_SURFACE = 'L7R_SUPPORT_UNDECLARED_SURFACE',
  SUPPORT_ILLEGAL_SCOPE_PROJECTION = 'L7R_SUPPORT_ILLEGAL_SCOPE_PROJECTION',
  SUPPORT_STALE_MASQUERADING_CURRENT = 'L7R_SUPPORT_STALE_MASQUERADING_CURRENT',
  SUPPORT_EVIDENCE_ONLY_LEAK = 'L7R_SUPPORT_EVIDENCE_ONLY_LEAK',
  SUPPORT_MISSING_FOR_REQUIRED_PATTERN = 'L7R_SUPPORT_MISSING_FOR_REQUIRED_PATTERN',
  SUPPORT_RESOLUTION_NON_DETERMINISTIC = 'L7R_SUPPORT_RESOLUTION_NON_DETERMINISTIC',

  // Challenge surface resolution (§7.4.4)
  CHALLENGE_UNDECLARED_SURFACE = 'L7R_CHALLENGE_UNDECLARED_SURFACE',
  CHALLENGE_CONTRADICTION_AS_MISSINGNESS = 'L7R_CHALLENGE_CONTRADICTION_AS_MISSINGNESS',
  CHALLENGE_MISSINGNESS_AS_CONTRADICTION = 'L7R_CHALLENGE_MISSINGNESS_AS_CONTRADICTION',
  CHALLENGE_ILLEGAL_CLASS = 'L7R_CHALLENGE_ILLEGAL_CLASS',
  CHALLENGE_RESOLUTION_NON_DETERMINISTIC = 'L7R_CHALLENGE_RESOLUTION_NON_DETERMINISTIC',

  // Contradiction detection / clustering (§7.4.5)
  CONTRADICTION_DETECTION_EMITTED_FINAL_CLASS = 'L7R_CONTRADICTION_DETECTION_EMITTED_FINAL_CLASS',
  CONTRADICTION_DETECTION_ILLEGAL_MUTATION = 'L7R_CONTRADICTION_DETECTION_ILLEGAL_MUTATION',
  CONTRADICTION_DETECTION_UNTYPED_FAMILY = 'L7R_CONTRADICTION_DETECTION_UNTYPED_FAMILY',
  CONTRADICTION_DETECTION_SEVERITY_OUT_OF_RANGE = 'L7R_CONTRADICTION_DETECTION_SEVERITY_OUT_OF_RANGE',
  CONTRADICTION_DETECTION_LAUNDERING = 'L7R_CONTRADICTION_DETECTION_LAUNDERING',
  CONTRADICTION_CLUSTERING_NON_DETERMINISTIC = 'L7R_CONTRADICTION_CLUSTERING_NON_DETERMINISTIC',
  CONTRADICTION_CRITICAL_FOLDED = 'L7R_CONTRADICTION_CRITICAL_FOLDED',
  CONTRADICTION_BUNDLE_EMIT_BEFORE_CLUSTER = 'L7R_CONTRADICTION_BUNDLE_EMIT_BEFORE_CLUSTER',

  // Evaluation (§7.4.6)
  EVAL_DOMAINS_COLLAPSED = 'L7R_EVAL_DOMAINS_COLLAPSED',
  EVAL_STALENESS_AS_CONTRADICTION = 'L7R_EVAL_STALENESS_AS_CONTRADICTION',
  EVAL_AMBIGUITY_AS_INCOMPLETENESS = 'L7R_EVAL_AMBIGUITY_AS_INCOMPLETENESS',
  EVAL_OUT_OF_ORDER = 'L7R_EVAL_OUT_OF_ORDER',
  EVAL_SCORE_OUT_OF_RANGE = 'L7R_EVAL_SCORE_OUT_OF_RANGE',

  // Classification (§7.4.7)
  CLASSIFY_BEFORE_EVALUATION = 'L7R_CLASSIFY_BEFORE_EVALUATION',
  CLASSIFY_IGNORED_CRITICAL_CONTRADICTION = 'L7R_CLASSIFY_IGNORED_CRITICAL_CONTRADICTION',
  CLASSIFY_ILLEGAL_CLASS = 'L7R_CLASSIFY_ILLEGAL_CLASS',
  CLASSIFY_MODIFIER_INCONSISTENT = 'L7R_CLASSIFY_MODIFIER_INCONSISTENT',
  CLASSIFY_SILENT_AMBIGUITY = 'L7R_CLASSIFY_SILENT_AMBIGUITY',
  CLASSIFY_DEGRADED_AS_CLEAN = 'L7R_CLASSIFY_DEGRADED_AS_CLEAN',
  CLASSIFY_DOUBLE_ASSIGNMENT = 'L7R_CLASSIFY_DOUBLE_ASSIGNMENT',

  // Confidence runtime (§7.4.7)
  CONFIDENCE_BEFORE_CLASSIFICATION = 'L7R_CONFIDENCE_BEFORE_CLASSIFICATION',
  CONFIDENCE_MISSING_CONTRADICTION_PENALTY = 'L7R_CONFIDENCE_MISSING_CONTRADICTION_PENALTY',
  CONFIDENCE_CAP_CHAIN_ILLEGAL = 'L7R_CONFIDENCE_CAP_CHAIN_ILLEGAL',
  CONFIDENCE_SCORE_OUT_OF_RANGE = 'L7R_CONFIDENCE_SCORE_OUT_OF_RANGE',

  // Restriction runtime (§7.4.7)
  RESTRICTION_BEFORE_CONFIDENCE = 'L7R_RESTRICTION_BEFORE_CONFIDENCE',
  RESTRICTION_BROADER_THAN_STATE_JUSTIFIES = 'L7R_RESTRICTION_BROADER_THAN_STATE_JUSTIFIES',
  RESTRICTION_REASONS_MISSING = 'L7R_RESTRICTION_REASONS_MISSING',

  // Evidence pack (§7.4.8.1)
  EVIDENCE_PACK_INCOMPLETE = 'L7R_EVIDENCE_PACK_INCOMPLETE',
  EVIDENCE_PACK_MISSING_LINEAGE = 'L7R_EVIDENCE_PACK_MISSING_LINEAGE',
  EVIDENCE_PACK_NON_DETERMINISTIC = 'L7R_EVIDENCE_PACK_NON_DETERMINISTIC',

  // Materialization + L5 (§7.4.8.3-8.7)
  MATERIALIZATION_DIRECT_STORE_WRITE = 'L7R_MATERIALIZATION_DIRECT_STORE_WRITE',
  MATERIALIZATION_BYPASSES_L5 = 'L7R_MATERIALIZATION_BYPASSES_L5',
  MATERIALIZATION_PREREQUISITES_MISSING = 'L7R_MATERIALIZATION_PREREQUISITES_MISSING',
  MATERIALIZATION_CONTRACT_INVALID = 'L7R_MATERIALIZATION_CONTRACT_INVALID',

  // Replay / repair (§7.4.8.5-8.6)
  REPLAY_HASH_DIVERGED = 'L7R_REPLAY_HASH_DIVERGED',
  REPLAY_PRETENDS_LIVE = 'L7R_REPLAY_PRETENDS_LIVE',
  REPLAY_INVENTED_SUPPORT = 'L7R_REPLAY_INVENTED_SUPPORT',
  REPLAY_ERASED_CONTRADICTION = 'L7R_REPLAY_ERASED_CONTRADICTION',
  REPAIR_LINEAGE_BROKEN = 'L7R_REPAIR_LINEAGE_BROKEN',
  REPAIR_UNMARKED = 'L7R_REPAIR_UNMARKED',
  LATE_DATA_UNCLASSIFIED = 'L7R_LATE_DATA_UNCLASSIFIED',

  // Run-level
  RUN_ENGINE_SET_INCOMPLETE = 'L7R_RUN_ENGINE_SET_INCOMPLETE',
  RUN_MODE_MISSING = 'L7R_RUN_MODE_MISSING',
  RUN_LINEAGE_MISSING = 'L7R_RUN_LINEAGE_MISSING',
  RUN_DETERMINISM_BROKEN = 'L7R_RUN_DETERMINISM_BROKEN',
}

export const ALL_RUNTIME_VIOLATION_CODES: readonly L7RuntimeViolationCode[] =
  Object.values(L7RuntimeViolationCode);

export interface L7RuntimeViolation {
  readonly code: L7RuntimeViolationCode;
  readonly source: string;
  readonly nodeId: string | null;
  readonly validation_run_id: string | null;
  readonly validation_subject_id: string | null;
  readonly detail: string;
  readonly context: Record<string, unknown>;
}

export class L7RuntimeError extends Error {
  public readonly code: L7RuntimeViolationCode;
  public readonly details: Record<string, unknown>;

  constructor(code: L7RuntimeViolationCode, message: string, details: Record<string, unknown> = {}) {
    super(`[${code}] ${message}`);
    this.name = 'L7RuntimeError';
    this.code = code;
    this.details = details;
  }
}
