/**
 * L7.5 — Semantic Violation Codes
 *
 * §7.5 — Layer 7.5 governs the semantic lawbook of the Validation &
 * Contradiction Engine: primary validation classes, modifiers, contradiction
 * families, contradiction templates, and the first production validation
 * families.
 *
 * These violation codes are disjoint from:
 *   - L7.1 constitutional violation codes  (boundary/mission/dependency law)
 *   - L7.2 object violation codes          (object-shape / subject-model law)
 *   - L7.3 contract violation codes        (contract legality / replay law)
 *   - L7.4 runtime violation codes         (deterministic execution law)
 *
 * so that any audit record's semantic tier is unambiguous from its code.
 */

export enum L7SemanticViolationCode {
  // Primary validation class law.
  UNKNOWN_PRIMARY_CLASS = 'L7_5_UNKNOWN_PRIMARY_CLASS',
  MULTIPLE_PRIMARY_CLASSES = 'L7_5_MULTIPLE_PRIMARY_CLASSES',
  PRIMARY_CLASS_REDEFINED_BY_FAMILY = 'L7_5_PRIMARY_CLASS_REDEFINED_BY_FAMILY',
  PRECEDENCE_VIOLATED = 'L7_5_PRECEDENCE_VIOLATED',
  CLEAN_CONFIRMATION_MASQUERADE = 'L7_5_CLEAN_CONFIRMATION_MASQUERADE',
  CLASS_MISUSED_AS_MODIFIER = 'L7_5_CLASS_MISUSED_AS_MODIFIER',

  // Modifier law.
  UNKNOWN_MODIFIER = 'L7_5_UNKNOWN_MODIFIER',
  MODIFIER_USED_AS_PRIMARY_CLASS = 'L7_5_MODIFIER_USED_AS_PRIMARY_CLASS',
  MODIFIER_ILLEGAL_FOR_PRIMARY_CLASS = 'L7_5_MODIFIER_ILLEGAL_FOR_PRIMARY_CLASS',
  MODIFIER_DUPLICATE = 'L7_5_MODIFIER_DUPLICATE',
  MODIFIER_CONFLICTS_WITH_PRIMARY_CLASS = 'L7_5_MODIFIER_CONFLICTS_WITH_PRIMARY_CLASS',

  // Contradiction ontology law.
  UNKNOWN_CONTRADICTION_FAMILY = 'L7_5_UNKNOWN_CONTRADICTION_FAMILY',
  CONTRADICTION_FAMILY_NOT_REGISTERED = 'L7_5_CONTRADICTION_FAMILY_NOT_REGISTERED',
  CONTRADICTION_FAMILY_SCOPE_MISMATCH = 'L7_5_CONTRADICTION_FAMILY_SCOPE_MISMATCH',
  CONTRADICTION_FAMILY_SUBJECT_CLASS_ILLEGAL = 'L7_5_CONTRADICTION_FAMILY_SUBJECT_CLASS_ILLEGAL',
  CONTRADICTION_FAMILY_SUPPORT_DOMAIN_MISSING = 'L7_5_CONTRADICTION_FAMILY_SUPPORT_DOMAIN_MISSING',
  CONTRADICTION_FAMILY_CHALLENGE_DOMAIN_MISSING = 'L7_5_CONTRADICTION_FAMILY_CHALLENGE_DOMAIN_MISSING',
  CONTRADICTION_FAMILY_TEMPORALLY_IRRELEVANT = 'L7_5_CONTRADICTION_FAMILY_TEMPORALLY_IRRELEVANT',

  // Contradiction template law.
  TEMPLATE_INVALID = 'L7_5_TEMPLATE_INVALID',
  TEMPLATE_NOT_REGISTERED = 'L7_5_TEMPLATE_NOT_REGISTERED',
  TEMPLATE_FAMILY_UNKNOWN = 'L7_5_TEMPLATE_FAMILY_UNKNOWN',
  TEMPLATE_SUBJECT_CLASS_ILLEGAL = 'L7_5_TEMPLATE_SUBJECT_CLASS_ILLEGAL',
  TEMPLATE_FAMILY_ILLEGAL = 'L7_5_TEMPLATE_FAMILY_ILLEGAL',
  TEMPLATE_SUPPORT_PATTERN_MISSING = 'L7_5_TEMPLATE_SUPPORT_PATTERN_MISSING',
  TEMPLATE_CHALLENGE_PATTERN_MISSING = 'L7_5_TEMPLATE_CHALLENGE_PATTERN_MISSING',
  TEMPLATE_SEVERITY_MODEL_MISSING = 'L7_5_TEMPLATE_SEVERITY_MODEL_MISSING',
  TEMPLATE_BLOCKING_CAP_BOTH_MISSING = 'L7_5_TEMPLATE_BLOCKING_CAP_BOTH_MISSING',
  TEMPLATE_LINEAGE_INCOMPLETE = 'L7_5_TEMPLATE_LINEAGE_INCOMPLETE',
  TEMPLATE_FREEFORM_CONTRADICTION_EMITTED = 'L7_5_TEMPLATE_FREEFORM_CONTRADICTION_EMITTED',
  TEMPLATE_OUTSIDE_REGISTRY = 'L7_5_TEMPLATE_OUTSIDE_REGISTRY',

  // Validation family law.
  FAMILY_UNKNOWN = 'L7_5_FAMILY_UNKNOWN',
  FAMILY_SUBJECT_CLASS_UNREGISTERED = 'L7_5_FAMILY_SUBJECT_CLASS_UNREGISTERED',
  FAMILY_SCOPE_ILLEGAL = 'L7_5_FAMILY_SCOPE_ILLEGAL',
  FAMILY_SUPPORT_DOMAIN_MISSING = 'L7_5_FAMILY_SUPPORT_DOMAIN_MISSING',
  FAMILY_CHALLENGE_DOMAIN_MISSING = 'L7_5_FAMILY_CHALLENGE_DOMAIN_MISSING',
  FAMILY_CONTRADICTION_COVERAGE_MISSING = 'L7_5_FAMILY_CONTRADICTION_COVERAGE_MISSING',
  FAMILY_TEMPLATE_COVERAGE_MISSING = 'L7_5_FAMILY_TEMPLATE_COVERAGE_MISSING',
  FAMILY_SEMANTIC_DRIFT = 'L7_5_FAMILY_SEMANTIC_DRIFT',

  // Rollout law.
  ROLLOUT_OUT_OF_ORDER = 'L7_5_ROLLOUT_OUT_OF_ORDER',
  ROLLOUT_PHASE_UNKNOWN = 'L7_5_ROLLOUT_PHASE_UNKNOWN',
  ROLLOUT_CERTIFICATION_MISSING = 'L7_5_ROLLOUT_CERTIFICATION_MISSING',
  ROLLOUT_RUNTIME_INTEGRATION_MISSING = 'L7_5_ROLLOUT_RUNTIME_INTEGRATION_MISSING',
  ROLLOUT_RESTRICTION_POSTURE_UNVALIDATED = 'L7_5_ROLLOUT_RESTRICTION_POSTURE_UNVALIDATED',
  ROLLOUT_DEPENDENCY_NOT_ENABLED = 'L7_5_ROLLOUT_DEPENDENCY_NOT_ENABLED',
}

export const ALL_L7_SEMANTIC_VIOLATION_CODES: readonly L7SemanticViolationCode[] =
  Object.values(L7SemanticViolationCode);

export interface L7SemanticViolation {
  readonly code: L7SemanticViolationCode;
  readonly detail: string;
  readonly subjectClass?: string;
  readonly familyId?: string;
  readonly templateId?: string;
  readonly contradictionFamily?: string;
  readonly modifier?: string;
  readonly primaryClass?: string;
}

export function isL7SemanticViolationCode(code: string): code is L7SemanticViolationCode {
  return (ALL_L7_SEMANTIC_VIOLATION_CODES as readonly string[]).includes(code);
}
