/**
 * L10.1 — Constitutional Violation Codes
 *
 * §10.1.10.4 — Every constitutional boundary failure carries a typed
 * code so audit records and validator decisions remain deterministic.
 */

export enum L10ConstitutionalViolationCode {
  UNREGISTERED_DEPENDENCY = 'L10_UNREG_DEPENDENCY',
  UNREGISTERED_OUTPUT = 'L10_UNREG_OUTPUT',
  ILLEGAL_DEPENDENCY_USAGE = 'L10_ILLEGAL_DEP_USAGE',
  ILLEGAL_OUTPUT_CLASS = 'L10_ILLEGAL_OUTPUT_CLASS',
  ILLEGAL_CAPABILITY_CLAIM = 'L10_ILLEGAL_CAPABILITY',
  FORBIDDEN_JUDGMENT_SEMANTICS = 'L10_FORBIDDEN_JUDGMENT',
  FORBIDDEN_RECOMMENDATION_SEMANTICS = 'L10_FORBIDDEN_RECOMMENDATION',
  FORBIDDEN_SCENARIO_SEMANTICS = 'L10_FORBIDDEN_SCENARIO',
  FORBIDDEN_SCORE_SEMANTICS = 'L10_FORBIDDEN_SCORE',
  FORBIDDEN_FINAL_EXPLANATION_SEMANTICS = 'L10_FORBIDDEN_FINAL_EXPLANATION',
  FORBIDDEN_CONVICTION_SEMANTICS = 'L10_FORBIDDEN_CONVICTION',
  LOWER_LAYER_REDEFINITION = 'L10_LOWER_LAYER_REDEFINE',
  VALIDATION_TRUTH_REDEFINITION = 'L10_VALIDATION_TRUTH_REDEFINE',
  CONTRADICTION_POSTURE_OVERWRITE = 'L10_CONTRADICTION_POSTURE_OVERWRITE',
  RESTRICTION_POSTURE_IGNORED = 'L10_RESTRICTION_POSTURE_IGNORED',
  RESTRICTION_BYPASS = 'L10_RESTRICTION_BYPASS',
  REGIME_POSTURE_OVERWRITE = 'L10_REGIME_POSTURE_OVERWRITE',
  REGIME_POSTURE_IGNORED = 'L10_REGIME_POSTURE_IGNORED',
  SEQUENCE_POSTURE_OVERWRITE = 'L10_SEQUENCE_POSTURE_OVERWRITE',
  SEQUENCE_POSTURE_IGNORED = 'L10_SEQUENCE_POSTURE_IGNORED',
  SINGLE_STORY_COLLAPSE = 'L10_SINGLE_STORY_COLLAPSE',
  ALTERNATIVE_SUPPRESSION = 'L10_ALTERNATIVE_SUPPRESSION',
  CLOSE_SPREAD_CONCEALMENT = 'L10_CLOSE_SPREAD_CONCEALMENT',
  CONFIRMATION_GAP_CONCEALMENT = 'L10_CONFIRMATION_GAP_CONCEALMENT',
  INVALIDATION_POSTURE_CONCEALMENT = 'L10_INVALIDATION_POSTURE_CONCEALMENT',
  EXPLANATION_LAUNDERING = 'L10_EXPLANATION_LAUNDERING',
  CAUSAL_LAUNDERING = 'L10_CAUSAL_LAUNDERING',
  L7_LIVE_REVALIDATION = 'L10_L7_LIVE_REVALIDATION',
  REGIME_RECLASSIFICATION = 'L10_REGIME_RECLASSIFICATION',
  SEQUENCE_REINTERPRETATION = 'L10_SEQUENCE_REINTERPRETATION',
  PRIMARY_AS_FINAL_TRUTH = 'L10_PRIMARY_AS_FINAL_TRUTH',
  RAW_DATA_HYPOTHESIS_INVENTION = 'L10_RAW_DATA_HYPOTHESIS_INVENTION',
  STORAGE_BYPASS = 'L10_STORAGE_BYPASS',
  MISSING_LINEAGE = 'L10_MISSING_LINEAGE',
  LATE_LAYER_CONSUMPTION = 'L10_LATE_LAYER_CONSUMPTION',
  EVIDENCE_ASYMMETRY_CONCEALMENT = 'L10_EVIDENCE_ASYMMETRY_CONCEALMENT',
}

export const ALL_L10_VIOLATION_CODES: readonly L10ConstitutionalViolationCode[] =
  Object.values(L10ConstitutionalViolationCode);

export class L10ConstitutionalError extends Error {
  public readonly code: L10ConstitutionalViolationCode;
  public readonly details: Record<string, unknown>;

  constructor(
    code: L10ConstitutionalViolationCode,
    message: string,
    details: Record<string, unknown> = {},
  ) {
    super(`[${code}] ${message}`);
    this.name = 'L10ConstitutionalError';
    this.code = code;
    this.details = details;
  }
}
