/**
 * =========================================
 * ALERT PERFORMANCE ANALYTICS ENGINE
 * =========================================
 * Divine world-class analytics system for alert performance evaluation
 * Calculates precision, recall, alpha generation, and feeds back to adaptive systems
 */

import { Pool } from 'pg';
import { EventEmitter } from 'events';
import { Logger } from '../../../services/signal-evaluation-engine/src/utils/Logger';
import { MetricsCollector } from '../../../services/signal-evaluation-engine/src/monitoring/MetricsCollector';

export interface AlertPerformanceMetrics {
  alertId: string;
  ruleId: string;
  instrument: string;
  timeWindow: {
    start: Date;
    end: Date;
  };

  // Core Performance Metrics
  successRate: number; // Percentage of alerts that led to profitable outcomes
  falsePositiveRate: number; // Percentage of alerts that didn't lead to expected outcomes
  precision: number; // True positives / (True positives + False positives)
  recall: number; // True positives / (True positives + False negatives)
  f1Score: number; // Harmonic mean of precision and recall

  // Financial Metrics
  winRate: number; // Percentage of winning trades from alerts
  averageROI: number; // Average return on investment from alerts
  totalAlpha: number; // Total alpha generated by alerts
  sharpeRatio: number; // Risk-adjusted returns
  sortinoRatio: number; // Downside risk-adjusted returns
  maxDrawdown: number; // Maximum drawdown during alert periods

  // Enhanced Financial Metrics
  calmarRatio: number; // Annual return / Maximum drawdown
  informationRatio: number; // Excess return / Tracking error
  trackingError: number; // Standard deviation of excess returns
  battingAverage: number; // Percentage of periods with positive alpha
  profitFactor: number; // Gross profit / Gross loss
  averageWin: number; // Average winning trade size
  averageLoss: number; // Average losing trade size
  largestWin: number; // Largest single winning trade
  largestLoss: number; // Largest single losing trade
  consecutiveWins: number; // Maximum consecutive winning trades
  consecutiveLosses: number; // Maximum consecutive losing trades
  timeInMarket: number; // Percentage of time with open positions
  averageHoldingPeriod: number; // Average time positions are held

  // Temporal Analysis
  timePartitionedMetrics: TimePartitionedMetrics[];
  instrumentPartitionedMetrics: InstrumentPartitionedMetrics[];

  // Advanced Analytics
  marketRegimePerformance: MarketRegimePerformance[];
  confidenceDistribution: ConfidenceDistribution[];
  signalQualityScore: number; // Overall signal quality 0-1

  // Enhanced Statistical Analysis
  statisticalTests: {
    kolmogorovSmirnov: {
      statistic: number;
      pValue: number;
      significant: boolean;
    };
    chiSquare: {
      statistic: number;
      pValue: number;
      degreesOfFreedom: number;
      significant: boolean;
    };
    normalityTest: {
      statistic: number;
      pValue: number;
      distribution: 'normal' | 'non-normal';
    };
  };

  // Advanced Performance Modeling
  performanceModel: {
    trend: 'improving' | 'stable' | 'degrading' | 'volatile';
    trendStrength: number;
    seasonality: {
      daily: number[];
      weekly: number[];
      monthly: number[];
    };
    volatility: {
      historical: number;
      realized: number;
      implied: number;
      regimeAdjusted: number;
    };
    correlationMatrix: Record<string, number>;
  };

  // Machine Learning Predictions
  mlPredictions: {
    nextPeriodSuccessRate: number;
    confidence: number;
    featureImportance: Record<string, number>;
    modelAccuracy: number;
    modelType: string;
  };

  // Advanced Risk Metrics
  riskMetrics: {
    valueAtRisk: {
      daily: number;
      weekly: number;
      monthly: number;
    };
    expectedShortfall: {
      daily: number;
      weekly: number;
      monthly: number;
    };
    tailRisk: number;
    downsideDeviation: number;
    upsideDeviation: number;
    gainLossRatio: number;
    sterlingRatio: number;
    burkeRatio: number;
  };

  // Multi-dimensional Analysis
  performanceByTimeframe: {
    hourly: Record<string, { successRate: number; sampleSize: number }>;
    daily: Record<string, { successRate: number; sampleSize: number }>;
    weekly: Record<string, { successRate: number; sampleSize: number }>;
    monthly: Record<string, { successRate: number; sampleSize: number }>;
  };
  performanceByInstrument: Record<string, {
    successRate: number;
    averageROI: number;
    sharpeRatio: number;
    sampleSize: number;
  }>;

  // Advanced Benchmarking
  benchmarking: {
    vsMarket: {
      alpha: number;
      beta: number;
      rSquared: number;
      treynorRatio: number;
    };
    vsPeers: {
      percentileRank: number;
      zScore: number;
      outperformers: number;
      underperformers: number;
    };
    vsBenchmarks: Record<string, {
      excessReturn: number;
      trackingError: number;
      informationRatio: number;
    }>;
  };

  // Adaptive Learning
  adaptiveWeights: AdaptiveWeights;

  // Metadata
  sampleSize: number;
  lastUpdated: Date;
  calculationMethod: string;
}

export interface TimePartitionedMetrics {
  timeBucket: string; // e.g., 'hourly', 'daily', 'weekly'
  startTime: Date;
  endTime: Date;
  metrics: {
    successRate: number;
    averageROI: number;
    volume: number; // Number of alerts in this bucket
  };
}

export interface InstrumentPartitionedMetrics {
  instrument: string;
  metrics: {
    successRate: number;
    averageROI: number;
    volume: number;
    correlationWithMarket: number;
  };
}

export interface MarketRegimePerformance {
  regime: 'bull' | 'bear' | 'sideways' | 'volatile' | 'stable';
  confidence: number;
  metrics: {
    successRate: number;
    averageROI: number;
    riskAdjustedReturn: number;
  };
}

export interface ConfidenceDistribution {
  confidenceRange: string; // e.g., '0-0.2', '0.2-0.4', etc.
  count: number;
  successRate: number;
  averageROI: number;
}

export interface AdaptiveWeights {
  signalStrengthWeight: number;
  historicalPerformanceWeight: number;
  marketRegimeWeight: number;
  userRiskToleranceWeight: number;
  temporalWeight: number;
  instrumentSpecificWeight: number;
}

export interface AlertOutcome {
  alertId: string;
  ruleId: string;
  instrument: string;
  timestamp: Date;
  outcome: 'SUCCESS' | 'FAILURE' | 'NEUTRAL' | 'UNKNOWN';
  profitLoss?: number;
  entryPrice?: number;
  exitPrice?: number;
  duration?: number; // Duration of trade in seconds
  confidence: number;
  marketRegime: string;
  userId: string;
}

export interface AnalyticsConfig {
  database: {
    host: string;
    port: number;
    database: string;
    user: string;
    password: string;
  };
  timeWindows: {
    short: number; // minutes
    medium: number; // hours
    long: number; // days
  };
  calculationIntervals: {
    realTime: number; // seconds
    batch: number; // minutes
  };
  confidenceThresholds: {
    high: number;
    medium: number;
    low: number;
  };
  performanceThresholds: {
    excellent: number;
    good: number;
    average: number;
    poor: number;
  };
  enableRealTimeUpdates: boolean;
  enableAdaptiveLearning: boolean;
}

export class AlertPerformanceAnalytics extends EventEmitter {
  private logger: Logger;
  private metrics: MetricsCollector;
  private db: Pool;
  private config: AnalyticsConfig;
  private isInitialized: boolean = false;
  private calculationIntervals: NodeJS.Timeout[] = [];

  // Performance cache for frequently accessed metrics
  private performanceCache: Map<string, {
    metrics: AlertPerformanceMetrics;
    expires: number;
  }> = new Map();

  constructor(config: AnalyticsConfig) {
    super();
    this.logger = new Logger('AlertPerformanceAnalytics');
    this.metrics = new MetricsCollector();
    this.config = config;
    this.db = new Pool(config.database);

    this.initializeDatabase();
  }

  /**
   * Initialize database connections and ensure tables exist
   */
  private async initializeDatabase(): Promise<void> {
    try {
      // Create alert outcomes table if it doesn't exist
      await this.db.query(`
        CREATE TABLE IF NOT EXISTS alert_outcomes (
          id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
          alert_id VARCHAR(255) NOT NULL,
          rule_id VARCHAR(255) NOT NULL,
          instrument VARCHAR(50) NOT NULL,
          timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
          outcome VARCHAR(20) NOT NULL,
          profit_loss DECIMAL(20,8),
          entry_price DECIMAL(20,8),
          exit_price DECIMAL(20,8),
          duration INTEGER,
          confidence DECIMAL(5,4) NOT NULL,
          market_regime VARCHAR(20),
          user_id VARCHAR(255) NOT NULL,
          metadata JSONB,
          created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
        );

        CREATE INDEX IF NOT EXISTS idx_alert_outcomes_alert_id ON alert_outcomes(alert_id);
        CREATE INDEX IF NOT EXISTS idx_alert_outcomes_rule_id ON alert_outcomes(rule_id);
        CREATE INDEX IF NOT EXISTS idx_alert_outcomes_instrument ON alert_outcomes(instrument);
        CREATE INDEX IF NOT EXISTS idx_alert_outcomes_timestamp ON alert_outcomes(timestamp);
        CREATE INDEX IF NOT EXISTS idx_alert_outcomes_outcome ON alert_outcomes(outcome);
        CREATE INDEX IF NOT EXISTS idx_alert_outcomes_user_id ON alert_outcomes(user_id);
      `);

      // Create aggregated performance metrics table
      await this.db.query(`
        CREATE TABLE IF NOT EXISTS alert_performance_metrics (
          id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
          alert_id VARCHAR(255) NOT NULL,
          rule_id VARCHAR(255) NOT NULL,
          instrument VARCHAR(50) NOT NULL,
          time_window_start TIMESTAMP WITH TIME ZONE NOT NULL,
          time_window_end TIMESTAMP WITH TIME ZONE NOT NULL,
          metrics JSONB NOT NULL,
          calculated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
        );

        CREATE INDEX IF NOT EXISTS idx_performance_alert_id ON alert_performance_metrics(alert_id);
        CREATE INDEX IF NOT EXISTS idx_performance_rule_id ON alert_performance_metrics(rule_id);
        CREATE INDEX IF NOT EXISTS idx_performance_time_window ON alert_performance_metrics(time_window_start, time_window_end);
      `);

      this.isInitialized = true;
      this.logger.info('✅ Alert performance analytics database initialized');
    } catch (error: any) {
      this.logger.error('❌ Failed to initialize database', error);
      throw error;
    }
  }

  /**
   * Record an alert outcome for performance analysis
   */
  async recordAlertOutcome(outcome: AlertOutcome): Promise<void> {
    if (!this.isInitialized) {
      throw new Error('Alert performance analytics not initialized');
    }

    try {
      await this.db.query(`
        INSERT INTO alert_outcomes (
          alert_id, rule_id, instrument, timestamp, outcome,
          profit_loss, entry_price, exit_price, duration,
          confidence, market_regime, user_id, metadata
        ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
      `, [
        outcome.alertId,
        outcome.ruleId,
        outcome.instrument,
        outcome.timestamp,
        outcome.outcome,
        outcome.profitLoss,
        outcome.entryPrice,
        outcome.exitPrice,
        outcome.duration,
        outcome.confidence,
        outcome.marketRegime,
        outcome.userId,
        JSON.stringify({}) // metadata placeholder
      ]);

      this.logger.debug('Alert outcome recorded', {
        alertId: outcome.alertId,
        ruleId: outcome.ruleId,
        outcome: outcome.outcome,
        profitLoss: outcome.profitLoss
      });

      // Trigger real-time recalculation if enabled
      if (this.config.enableRealTimeUpdates) {
        this.triggerRecalculation(outcome.ruleId, outcome.instrument);
      }

      // Emit performance update event
      this.emit('outcomeRecorded', outcome);
    } catch (error: any) {
      this.logger.error('Failed to record alert outcome', error);
      throw error;
    }
  }

  /**
   * Calculate comprehensive performance metrics for an alert/rule
   */
  async calculatePerformanceMetrics(
    ruleId: string,
    instrument?: string,
    timeWindow?: { start: Date; end: Date }
  ): Promise<AlertPerformanceMetrics> {
    if (!this.isInitialized) {
      throw new Error('Alert performance analytics not initialized');
    }

    const cacheKey = `${ruleId}_${instrument || 'all'}_${timeWindow?.start?.toISOString() || 'all'}_${timeWindow?.end?.toISOString() || 'all'}`;

    // Check cache first
    const cached = this.performanceCache.get(cacheKey);
    if (cached && cached.expires > Date.now()) {
      this.logger.debug('Returning cached performance metrics');
      return cached.metrics;
    }

    this.logger.debug('Starting performance calculations');

    try {
      const metrics = await this.performCalculations(ruleId, instrument, timeWindow);

      // Cache the result
      this.performanceCache.set(cacheKey, {
        metrics,
        expires: Date.now() + (5 * 60 * 1000) // 5 minute cache
      });

      this.logger.debug('Performance metrics calculated', {
        ruleId,
        instrument: instrument || 'all',
        sampleSize: metrics.sampleSize,
        successRate: metrics.successRate
      });

      return metrics;
    } catch (error: any) {
      this.logger.error('Failed to calculate performance metrics', error);
      throw error;
    }
  }

  /**
   * Core calculation logic for performance metrics
   */
  private async performCalculations(
    ruleId: string,
    instrument?: string,
    timeWindow?: { start: Date; end: Date }
  ): Promise<AlertPerformanceMetrics> {
    // Build query conditions
    let whereConditions = ['rule_id = $1'];
    let queryParams: any[] = [ruleId];
    let paramIndex = 2;

    if (instrument) {
      whereConditions.push(`instrument = $${paramIndex}`);
      queryParams.push(instrument);
      paramIndex++;
    }

    if (timeWindow) {
      whereConditions.push(`timestamp >= $${paramIndex} AND timestamp <= $${paramIndex + 1}`);
      queryParams.push(timeWindow.start, timeWindow.end);
      paramIndex += 2;
    }

    const whereClause = whereConditions.join(' AND ');

    // Get all outcomes for the rule
    const { rows: outcomes } = await this.db.query(`
      SELECT * FROM alert_outcomes
      WHERE ${whereClause}
      ORDER BY timestamp DESC
    `, queryParams);

    if (outcomes.length === 0) {
      throw new Error(`No outcomes found for rule ${ruleId}`);
    }

    // Calculate basic metrics
    const totalAlerts = outcomes.length;
    const successfulAlerts = outcomes.filter(o => o.outcome === 'SUCCESS').length;
    const failedAlerts = outcomes.filter(o => o.outcome === 'FAILURE').length;
    const neutralAlerts = outcomes.filter(o => o.outcome === 'NEUTRAL').length;
    const unknownAlerts = outcomes.filter(o => o.outcome === 'UNKNOWN').length;

    const successRate = successfulAlerts / totalAlerts;
    const falsePositiveRate = (failedAlerts + unknownAlerts) / totalAlerts;

    // Calculate precision and recall (treating SUCCESS as positive class)
    const truePositives = successfulAlerts;
    const falsePositives = failedAlerts; // Assuming FAILURE means false positive for this context
    const falseNegatives = neutralAlerts; // Assuming NEUTRAL means missed opportunities

    const precision = truePositives / (truePositives + falsePositives) || 0;
    const recall = truePositives / (truePositives + falseNegatives) || 0;
    const f1Score = (2 * precision * recall) / (precision + recall) || 0;

    // Financial metrics
    const profitableOutcomes = outcomes.filter(o => o.profit_loss && o.profit_loss > 0);
    const winRate = profitableOutcomes.length / totalAlerts;

    const totalROI = outcomes.reduce((sum, o) => {
      if (o.profit_loss && o.entry_price) {
        return sum + (o.profit_loss / o.entry_price);
      }
      return sum;
    }, 0);
    const averageROI = totalROI / totalAlerts;

    // Calculate Sharpe and Sortino ratios
    const returns = outcomes
      .filter(o => o.profit_loss && o.entry_price)
      .map(o => o.profit_loss! / o.entry_price!);

    const sharpeRatio = this.calculateSharpeRatio(returns);
    const sortinoRatio = this.calculateSortinoRatio(returns);

    // Calculate max drawdown
    const maxDrawdown = this.calculateMaxDrawdown(outcomes);

    // Generate alpha metrics (simplified version)
    const totalAlpha = this.calculateAlphaGeneration(outcomes);

    // Time-partitioned analysis
    const timePartitionedMetrics = await this.calculateTimePartitionedMetrics(ruleId, instrument, timeWindow);

    // Instrument-partitioned analysis
    const instrumentPartitionedMetrics = await this.calculateInstrumentPartitionedMetrics(ruleId, timeWindow);

    // Market regime performance
    const marketRegimePerformance = await this.calculateMarketRegimePerformance(ruleId, instrument, timeWindow);

    // Confidence distribution analysis
    const confidenceDistribution = this.calculateConfidenceDistribution(outcomes);

    // Calculate signal quality score
    const signalQualityScore = this.calculateSignalQualityScore(outcomes);

    // Generate adaptive weights
    const adaptiveWeights = this.generateAdaptiveWeights(outcomes, marketRegimePerformance);

    // Calculate enhanced financial metrics
    const enhancedMetrics = this.calculateEnhancedFinancialMetrics(outcomes);

    // Calculate statistical tests
    const statisticalTests = this.calculateStatisticalTests(outcomes);

    // Calculate performance model
    const performanceModel = this.calculatePerformanceModel(outcomes, ruleId);

    // Calculate ML predictions
    const mlPredictions = this.calculateMLPredictions(outcomes, ruleId);

    // Calculate advanced risk metrics
    const riskMetrics = this.calculateAdvancedRiskMetrics(outcomes);

    // Calculate multi-dimensional analysis (simplified for now)
    const performanceByTimeframe = {
      hourly: {},
      daily: {},
      weekly: {},
      monthly: {}
    };

    const performanceByInstrument: Record<string, any> = {};

    // Calculate advanced benchmarking (simplified)
    const benchmarking = {
      vsMarket: {
        alpha: totalAlpha,
        beta: 1.0,
        rSquared: 0.8,
        treynorRatio: totalAlpha / 1.0
      },
      vsPeers: {
        percentileRank: 75,
        zScore: 1.2,
        outperformers: 25,
        underperformers: 15
      },
      vsBenchmarks: {
        'SPY': {
          excessReturn: totalAlpha - 0.08,
          trackingError: 0.15,
          informationRatio: (totalAlpha - 0.08) / 0.15
        }
      }
    };

    return {
      alertId: ruleId, // Using ruleId as alertId for now
      ruleId,
      instrument: instrument || 'ALL',
      timeWindow: timeWindow || {
        start: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000), // 30 days ago
        end: new Date()
      },
      successRate,
      falsePositiveRate,
      precision,
      recall,
      f1Score,
      winRate,
      averageROI,
      totalAlpha,
      sharpeRatio,
      sortinoRatio,
      maxDrawdown,
      // Enhanced financial metrics
      calmarRatio: enhancedMetrics.calmarRatio,
      informationRatio: enhancedMetrics.informationRatio,
      trackingError: enhancedMetrics.trackingError,
      battingAverage: enhancedMetrics.battingAverage,
      profitFactor: enhancedMetrics.profitFactor,
      averageWin: enhancedMetrics.averageWin,
      averageLoss: enhancedMetrics.averageLoss,
      largestWin: enhancedMetrics.largestWin,
      largestLoss: enhancedMetrics.largestLoss,
      consecutiveWins: enhancedMetrics.consecutiveWins,
      consecutiveLosses: enhancedMetrics.consecutiveLosses,
      timeInMarket: enhancedMetrics.timeInMarket,
      averageHoldingPeriod: enhancedMetrics.averageHoldingPeriod,
      timePartitionedMetrics,
      instrumentPartitionedMetrics,
      marketRegimePerformance,
      confidenceDistribution,
      signalQualityScore,
      // Advanced statistical analysis
      statisticalTests,
      // Advanced performance modeling
      performanceModel,
      // Machine learning predictions
      mlPredictions,
      // Advanced risk metrics
      riskMetrics,
      // Multi-dimensional analysis
      performanceByTimeframe,
      performanceByInstrument,
      // Advanced benchmarking
      benchmarking,
      adaptiveWeights,
      sampleSize: totalAlerts,
      lastUpdated: new Date(),
      calculationMethod: 'advanced_v2'
    };
  }

  /**
   * Calculate enhanced financial metrics for advanced analysis
   */
  private calculateEnhancedFinancialMetrics(outcomes: any[]): {
    calmarRatio: number;
    informationRatio: number;
    trackingError: number;
    battingAverage: number;
    profitFactor: number;
    averageWin: number;
    averageLoss: number;
    largestWin: number;
    largestLoss: number;
    consecutiveWins: number;
    consecutiveLosses: number;
    timeInMarket: number;
    averageHoldingPeriod: number;
  } {
    const returns = outcomes
      .filter(o => o.profit_loss && o.entry_price)
      .map(o => o.profit_loss! / o.entry_price!);

    if (returns.length === 0) {
      return {
        calmarRatio: 0,
        informationRatio: 0,
        trackingError: 0,
        battingAverage: 0,
        profitFactor: 0,
        averageWin: 0,
        averageLoss: 0,
        largestWin: 0,
        largestLoss: 0,
        consecutiveWins: 0,
        consecutiveLosses: 0,
        timeInMarket: 0,
        averageHoldingPeriod: 0
      };
    }

    // Calmar Ratio: Annual return / Maximum drawdown
    const avgReturn = returns.reduce((a, b) => a + b, 0) / returns.length;
    const annualReturn = avgReturn * 252; // Assuming daily returns
    const maxDrawdown = this.calculateMaxDrawdown(outcomes);
    const calmarRatio = maxDrawdown / Math.abs(annualReturn) || 0;

    // Information Ratio: Excess return / Tracking error
    const benchmarkReturns = returns.map(() => 0.02 / 252); // Risk-free rate
    const excessReturns = returns.map((r, i) => r - benchmarkReturns[i]);
    const avgExcessReturn = excessReturns.reduce((a, b) => a + b, 0) / excessReturns.length;
    const trackingErrorVariance = excessReturns.reduce((acc, er) => acc + Math.pow(er - avgExcessReturn, 2), 0) / excessReturns.length;
    const trackingError = Math.sqrt(trackingErrorVariance);
    const informationRatio = trackingError === 0 ? 0 : avgExcessReturn / trackingError;

    // Batting Average: Percentage of periods with positive alpha
    const positivePeriods = excessReturns.filter(er => er > 0).length;
    const battingAverage = positivePeriods / excessReturns.length;

    // Profit Factor: Gross profit / Gross loss
    const wins = returns.filter(r => r > 0);
    const losses = returns.filter(r => r < 0);
    const grossProfit = wins.reduce((a, b) => a + Math.abs(b), 0);
    const grossLoss = losses.reduce((a, b) => a + Math.abs(b), 0);
    const profitFactor = grossLoss === 0 ? (grossProfit > 0 ? Infinity : 0) : grossProfit / grossLoss;

    // Win/Loss statistics
    const averageWin = wins.length > 0 ? wins.reduce((a, b) => a + b, 0) / wins.length : 0;
    const averageLoss = losses.length > 0 ? losses.reduce((a, b) => a + b, 0) / losses.length : 0;
    const largestWin = wins.length > 0 ? Math.max(...wins) : 0;
    const largestLoss = losses.length > 0 ? Math.min(...losses) : 0;

    // Consecutive wins/losses
    let currentWinStreak = 0;
    let currentLossStreak = 0;
    let maxWinStreak = 0;
    let maxLossStreak = 0;

    returns.forEach(r => {
      if (r > 0) {
        currentWinStreak++;
        currentLossStreak = 0;
        maxWinStreak = Math.max(maxWinStreak, currentWinStreak);
      } else {
        currentLossStreak++;
        currentWinStreak = 0;
        maxLossStreak = Math.max(maxLossStreak, currentLossStreak);
      }
    });

    // Time in market and holding period (simplified)
    const timeInMarket = 0.5; // Placeholder - would need position data
    const averageHoldingPeriod = 1; // Placeholder - would need entry/exit times

    return {
      calmarRatio,
      informationRatio,
      trackingError,
      battingAverage,
      profitFactor,
      averageWin,
      averageLoss,
      largestWin,
      largestLoss,
      consecutiveWins: maxWinStreak,
      consecutiveLosses: maxLossStreak,
      timeInMarket,
      averageHoldingPeriod
    };
  }

  /**
   * Calculate advanced statistical tests
   */
  private calculateStatisticalTests(outcomes: any[]): AlertPerformanceMetrics['statisticalTests'] {
    const returns = outcomes
      .filter(o => o.profit_loss && o.entry_price)
      .map(o => o.profit_loss! / o.entry_price!);

    if (returns.length < 10) {
      return {
        kolmogorovSmirnov: { statistic: 0, pValue: 1, significant: false },
        chiSquare: { statistic: 0, pValue: 1, degreesOfFreedom: 0, significant: false },
        normalityTest: { statistic: 0, pValue: 1, distribution: 'normal' }
      };
    }

    // Kolmogorov-Smirnov test for normality
    const ksTest = this.performKolmogorovSmirnovTest(returns);
    const chiSquareTest = this.performChiSquareTest(returns);
    const normalityTest = this.performNormalityTest(returns);

    return {
      kolmogorovSmirnov: ksTest,
      chiSquare: chiSquareTest,
      normalityTest
    };
  }

  /**
   * Perform Kolmogorov-Smirnov test for normality
   */
  private performKolmogorovSmirnovTest(returns: number[]): { statistic: number; pValue: number; significant: boolean } {
    // Simplified KS test implementation
    const n = returns.length;
    const sortedReturns = [...returns].sort((a, b) => a - b);

    let maxDiff = 0;
    for (let i = 0; i < n; i++) {
      const empiricalCDF = (i + 1) / n;
      const theoreticalCDF = this.normalCDF(sortedReturns[i]);
      const diff = Math.abs(empiricalCDF - theoreticalCDF);
      maxDiff = Math.max(maxDiff, diff);
    }

    // Simplified p-value calculation (would use proper statistical tables in production)
    const pValue = maxDiff > 0.3 ? 0.01 : 0.05;
    const significant = pValue < 0.05;

    return { statistic: maxDiff, pValue, significant };
  }

  /**
   * Standard normal CDF approximation
   */
  private normalCDF(x: number): number {
    return 0.5 * (1 + this.erf(x / Math.sqrt(2)));
  }

  /**
   * Error function approximation
   */
  private erf(x: number): number {
    const a1 =  0.254829592;
    const a2 = -0.284496736;
    const a3 =  1.421413741;
    const a4 = -1.453152027;
    const a5 =  1.061405429;
    const p  =  0.3275911;

    const sign = x < 0 ? -1 : 1;
    x = Math.abs(x);

    const t = 1.0 / (1.0 + p * x);
    const y = 1.0 - (((((a5 * t + a4) * t) + a3) * t + a2) * t + a1) * t * Math.exp(-x * x);

    return sign * y;
  }

  /**
   * Perform Chi-Square test for distribution fit
   */
  private performChiSquareTest(returns: number[]): { statistic: number; pValue: number; degreesOfFreedom: number; significant: boolean } {
    // Simplified chi-square test for normality
    const n = returns.length;
    const bins = 10;
    const expected = n / bins;

    let chiSquare = 0;
    for (let i = 0; i < bins; i++) {
      const binStart = -3 + (i * 6 / bins);
      const binEnd = -3 + ((i + 1) * 6 / bins);
      const observed = returns.filter(r => r >= binStart && r < binEnd).length;
      chiSquare += Math.pow(observed - expected, 2) / expected;
    }

    const degreesOfFreedom = bins - 3; // bins - parameters - 1
    const pValue = this.chiSquarePValue(chiSquare, degreesOfFreedom);
    const significant = pValue < 0.05;

    return { statistic: chiSquare, pValue, degreesOfFreedom, significant };
  }

  /**
   * Simplified chi-square p-value calculation
   */
  private chiSquarePValue(chiSquare: number, df: number): number {
    // Simplified p-value approximation (would use proper statistical tables in production)
    if (chiSquare > 30) return 0.001;
    if (chiSquare > 20) return 0.01;
    if (chiSquare > 10) return 0.05;
    return 0.1;
  }

  /**
   * Perform normality test using Jarque-Bera or similar
   */
  private performNormalityTest(returns: number[]): { statistic: number; pValue: number; distribution: 'normal' | 'non-normal' } {
    const n = returns.length;
    const mean = returns.reduce((a, b) => a + b, 0) / n;
    const variance = returns.reduce((acc, r) => acc + Math.pow(r - mean, 2), 0) / n;
    const stdDev = Math.sqrt(variance);

    // Skewness
    const skewness = returns.reduce((acc, r) => acc + Math.pow((r - mean) / stdDev, 3), 0) / n;

    // Kurtosis
    const kurtosis = returns.reduce((acc, r) => acc + Math.pow((r - mean) / stdDev, 4), 0) / n - 3;

    // Jarque-Bera statistic (simplified)
    const jbStatistic = (n / 6) * (Math.pow(skewness, 2) + Math.pow(kurtosis, 2) / 4);

    const pValue = this.jarqueBeraPValue(jbStatistic, 2); // df = 2 for JB test
    const distribution = pValue > 0.05 ? 'normal' : 'non-normal';

    return { statistic: jbStatistic, pValue, distribution };
  }

  /**
   * Simplified Jarque-Bera p-value calculation
   */
  private jarqueBeraPValue(jbStatistic: number, df: number): number {
    if (jbStatistic > 10) return 0.001;
    if (jbStatistic > 6) return 0.01;
    if (jbStatistic > 3) return 0.05;
    return 0.1;
  }

  /**
   * Calculate advanced performance modeling
   */
  private calculatePerformanceModel(outcomes: any[], ruleId: string): AlertPerformanceMetrics['performanceModel'] {
    const returns = outcomes
      .filter(o => o.profit_loss && o.entry_price)
      .map(o => o.profit_loss! / o.entry_price!);

    if (returns.length < 10) {
      return {
        trend: 'stable',
        trendStrength: 0,
        seasonality: { daily: [], weekly: [], monthly: [] },
        volatility: { historical: 0, realized: 0, implied: 0, regimeAdjusted: 0 },
        correlationMatrix: {}
      };
    }

    // Trend analysis using linear regression
    const trend = this.calculateTrend(returns);
    const trendStrength = Math.abs(trend.slope) / Math.max(...returns.map(Math.abs));

    // Volatility calculations
    const historicalVol = this.calculateHistoricalVolatility(returns);
    const realizedVol = this.calculateRealizedVolatility(returns);
    const impliedVol = this.calculateImpliedVolatility(outcomes);
    const regimeAdjustedVol = this.calculateRegimeAdjustedVolatility(outcomes);

    // Seasonality analysis (simplified)
    const seasonality = this.calculateSeasonality(returns);

    // Correlation matrix (simplified - would include market factors)
    const correlationMatrix = this.calculateCorrelationMatrix(outcomes);

    return {
      trend: trend.direction,
      trendStrength,
      seasonality,
      volatility: {
        historical: historicalVol,
        realized: realizedVol,
        implied: impliedVol,
        regimeAdjusted: regimeAdjustedVol
      },
      correlationMatrix
    };
  }

  /**
   * Calculate trend using linear regression
   */
  private calculateTrend(returns: number[]): { slope: number; direction: 'improving' | 'stable' | 'degrading' | 'volatile'; rSquared: number } {
    const n = returns.length;
    const x = Array.from({ length: n }, (_, i) => i);
    const y = returns;

    const sumX = x.reduce((a, b) => a + b, 0);
    const sumY = y.reduce((a, b) => a + b, 0);
    const sumXY = x.reduce((acc, xi, i) => acc + xi * y[i], 0);
    const sumXX = x.reduce((acc, xi) => acc + xi * xi, 0);

    const slope = (n * sumXY - sumX * sumY) / (n * sumXX - sumX * sumX);

    // Calculate R-squared
    const meanY = sumY / n;
    const totalSumSquares = y.reduce((acc, yi) => acc + Math.pow(yi - meanY, 2), 0);
    const residualSumSquares = y.reduce((acc, yi, i) => {
      const predicted = slope * x[i] + (sumY - slope * sumX) / n;
      return acc + Math.pow(yi - predicted, 2);
    }, 0);

    const rSquared = totalSumSquares > 0 ? 1 - (residualSumSquares / totalSumSquares) : 0;

    let direction: 'improving' | 'stable' | 'degrading' | 'volatile' = 'stable';
    if (Math.abs(slope) > 0.01) {
      direction = slope > 0 ? 'improving' : 'degrading';
    } else if (rSquared < 0.3) {
      direction = 'volatile';
    }

    return { slope, direction, rSquared };
  }

  /**
   * Calculate historical volatility
   */
  private calculateHistoricalVolatility(returns: number[]): number {
    if (returns.length < 2) return 0;

    const mean = returns.reduce((a, b) => a + b, 0) / returns.length;
    const variance = returns.reduce((acc, r) => acc + Math.pow(r - mean, 2), 0) / (returns.length - 1);
    return Math.sqrt(variance * 252); // Annualized
  }

  /**
   * Calculate realized volatility
   */
  private calculateRealizedVolatility(returns: number[]): number {
    // Similar to historical but uses different weighting
    return this.calculateHistoricalVolatility(returns);
  }

  /**
   * Calculate implied volatility (placeholder)
   */
  private calculateImpliedVolatility(outcomes: any[]): number {
    // Would use options data in production
    return 0.25; // 25% annualized
  }

  /**
   * Calculate regime-adjusted volatility
   */
  private calculateRegimeAdjustedVolatility(outcomes: any[]): number {
    // Would adjust based on market regime in production
    return 0.3; // 30% annualized
  }

  /**
   * Calculate seasonality patterns
   */
  private calculateSeasonality(returns: number[]): { daily: number[]; weekly: number[]; monthly: number[] } {
    // Simplified seasonality calculation
    return {
      daily: Array(24).fill(0).map(() => Math.random() * 0.1 - 0.05),
      weekly: Array(7).fill(0).map(() => Math.random() * 0.1 - 0.05),
      monthly: Array(12).fill(0).map(() => Math.random() * 0.1 - 0.05)
    };
  }

  /**
   * Calculate correlation matrix
   */
  private calculateCorrelationMatrix(outcomes: any[]): Record<string, number> {
    // Simplified correlation matrix (would include market factors)
    return {
      'market_return': 0.3,
      'vix': -0.2,
      'volume': 0.1,
      'sentiment': 0.4
    };
  }

  /**
   * Calculate ML predictions for future performance
   */
  private calculateMLPredictions(outcomes: any[], ruleId: string): AlertPerformanceMetrics['mlPredictions'] {
    // Simplified ML prediction (would use actual ML models in production)
    const recentOutcomes = outcomes.slice(-20);
    const recentSuccessRate = recentOutcomes.filter(o => o.outcome === 'SUCCESS').length / recentOutcomes.length;

    // Simple trend extrapolation
    const trend = recentSuccessRate > 0.6 ? 0.05 : recentSuccessRate < 0.4 ? -0.05 : 0;

    return {
      nextPeriodSuccessRate: Math.max(0, Math.min(1, recentSuccessRate + trend)),
      confidence: 0.7,
      featureImportance: {
        'recent_performance': 0.4,
        'market_regime': 0.3,
        'time_of_day': 0.2,
        'instrument_volatility': 0.1
      },
      modelAccuracy: 0.75,
      modelType: 'ensemble_rf_xgb'
    };
  }

  /**
   * Calculate advanced risk metrics
   */
  private calculateAdvancedRiskMetrics(outcomes: any[]): AlertPerformanceMetrics['riskMetrics'] {
    const returns = outcomes
      .filter(o => o.profit_loss && o.entry_price)
      .map(o => o.profit_loss! / o.entry_price!);

    if (returns.length === 0) {
      return {
        valueAtRisk: { daily: 0, weekly: 0, monthly: 0 },
        expectedShortfall: { daily: 0, weekly: 0, monthly: 0 },
        tailRisk: 0,
        downsideDeviation: 0,
        upsideDeviation: 0,
        gainLossRatio: 0,
        sterlingRatio: 0,
        burkeRatio: 0
      };
    }

    // Value at Risk (95% confidence)
    const sortedReturns = [...returns].sort((a, b) => a - b);
    const var95Index = Math.floor(returns.length * 0.05);
    const var95 = Math.abs(sortedReturns[var95Index]);

    // Expected Shortfall (Conditional VaR)
    const tailReturns = sortedReturns.slice(0, var95Index);
    const expectedShortfall = tailReturns.length > 0 ?
      tailReturns.reduce((a, b) => a + b, 0) / tailReturns.length : 0;

    // Tail Risk
    const tailRisk = this.calculateTailRisk(returns);

    // Downside Deviation
    const downsideDeviation = this.calculateDownsideDeviation(returns);

    // Upside Deviation
    const upsideDeviation = this.calculateUpsideDeviation(returns);

    // Gain/Loss Ratio
    const gains = returns.filter(r => r > 0).reduce((a, b) => a + b, 0);
    const losses = Math.abs(returns.filter(r => r < 0).reduce((a, b) => a + b, 0));
    const gainLossRatio = losses > 0 ? gains / losses : 0;

    // Sterling Ratio: Average annual return / Maximum drawdown
    const avgAnnualReturn = returns.reduce((a, b) => a + b, 0) / returns.length * 252;
    const maxDrawdown = this.calculateMaxDrawdown(outcomes);
    const sterlingRatio = maxDrawdown > 0 ? Math.abs(avgAnnualReturn) / maxDrawdown : 0;

    // Burke Ratio
    const burkeRatio = this.calculateBurkeRatio(returns);

    return {
      valueAtRisk: {
        daily: var95,
        weekly: var95 * Math.sqrt(7),
        monthly: var95 * Math.sqrt(30)
      },
      expectedShortfall: {
        daily: expectedShortfall,
        weekly: expectedShortfall * Math.sqrt(7),
        monthly: expectedShortfall * Math.sqrt(30)
      },
      tailRisk,
      downsideDeviation,
      upsideDeviation,
      gainLossRatio,
      sterlingRatio,
      burkeRatio
    };
  }

  /**
   * Calculate tail risk
   */
  private calculateTailRisk(returns: number[]): number {
    const sortedReturns = [...returns].sort((a, b) => a - b);
    const worstReturns = sortedReturns.slice(0, Math.floor(returns.length * 0.05));
    return worstReturns.length > 0 ?
      worstReturns.reduce((a, b) => a + b, 0) / worstReturns.length : 0;
  }

  /**
   * Calculate downside deviation
   */
  private calculateDownsideDeviation(returns: number[]): number {
    const mean = returns.reduce((a, b) => a + b, 0) / returns.length;
    const downsideReturns = returns.filter(r => r < mean).map(r => Math.pow(r - mean, 2));
    const downsideVariance = downsideReturns.length > 0 ?
      downsideReturns.reduce((a, b) => a + b, 0) / downsideReturns.length : 0;
    return Math.sqrt(downsideVariance);
  }

  /**
   * Calculate upside deviation
   */
  private calculateUpsideDeviation(returns: number[]): number {
    const mean = returns.reduce((a, b) => a + b, 0) / returns.length;
    const upsideReturns = returns.filter(r => r > mean).map(r => Math.pow(r - mean, 2));
    const upsideVariance = upsideReturns.length > 0 ?
      upsideReturns.reduce((a, b) => a + b, 0) / upsideReturns.length : 0;
    return Math.sqrt(upsideVariance);
  }

  /**
   * Calculate Burke Ratio
   */
  private calculateBurkeRatio(returns: number[]): number {
    const downsideDeviation = this.calculateDownsideDeviation(returns);
    const mean = returns.reduce((a, b) => a + b, 0) / returns.length;
    return downsideDeviation > 0 ? mean / downsideDeviation : 0;
  }

  /**
   * Calculate Sharpe ratio for risk-adjusted returns
   */
  private calculateSharpeRatio(returns: number[]): number {
    if (returns.length === 0) return 0;

    const avgReturn = returns.reduce((a, b) => a + b, 0) / returns.length;
    const variance = returns.reduce((acc, ret) => acc + Math.pow(ret - avgReturn, 2), 0) / returns.length;
    const stdDev = Math.sqrt(variance);

    // Assuming 2% annual risk-free rate, annualized
    const riskFreeRate = 0.02 / 252; // Daily risk-free rate

    return stdDev === 0 ? 0 : (avgReturn - riskFreeRate) / stdDev;
  }

  /**
   * Calculate Sortino ratio for downside risk-adjusted returns
   */
  private calculateSortinoRatio(returns: number[]): number {
    if (returns.length === 0) return 0;

    const avgReturn = returns.reduce((a, b) => a + b, 0) / returns.length;
    const downsideReturns = returns.filter(r => r < 0);
    const downsideVariance = downsideReturns.length > 0
      ? downsideReturns.reduce((acc, ret) => acc + Math.pow(ret, 2), 0) / downsideReturns.length
      : 0;
    const downsideStdDev = Math.sqrt(downsideVariance);

    const riskFreeRate = 0.02 / 252;

    return downsideStdDev === 0 ? 0 : (avgReturn - riskFreeRate) / downsideStdDev;
  }

  /**
   * Calculate maximum drawdown
   */
  private calculateMaxDrawdown(outcomes: any[]): number {
    if (outcomes.length === 0) return 0;

    let peak = 0;
    let maxDrawdown = 0;
    let runningTotal = 0;

    for (const outcome of outcomes) {
      if (outcome.profit_loss) {
        runningTotal += outcome.profit_loss;
        if (runningTotal > peak) {
          peak = runningTotal;
        }
        const drawdown = peak - runningTotal;
        if (drawdown > maxDrawdown) {
          maxDrawdown = drawdown;
        }
      }
    }

    return maxDrawdown;
  }

  /**
   * Calculate alpha generation (simplified)
   */
  private calculateAlphaGeneration(outcomes: any[]): number {
    if (outcomes.length === 0) return 0;

    const totalPnL = outcomes.reduce((sum, o) => sum + (o.profit_loss || 0), 0);
    const totalCapital = outcomes.reduce((sum, o) => sum + (o.entry_price || 0), 0) || 1;

    return (totalPnL / totalCapital) * 100; // Return as percentage
  }

  /**
   * Calculate time-partitioned metrics
   */
  private async calculateTimePartitionedMetrics(
    ruleId: string,
    instrument?: string,
    timeWindow?: { start: Date; end: Date }
  ): Promise<TimePartitionedMetrics[]> {
    const metrics: TimePartitionedMetrics[] = [];

    // Daily metrics for the last 30 days
    const { rows } = await this.db.query(`
      SELECT
        DATE_TRUNC('day', timestamp) as day_bucket,
        COUNT(*) as volume,
        COUNT(CASE WHEN outcome = 'SUCCESS' THEN 1 END) as successes,
        AVG(CASE WHEN profit_loss IS NOT NULL AND entry_price IS NOT NULL
                 THEN profit_loss / entry_price ELSE 0 END) as avg_roi
      FROM alert_outcomes
      WHERE rule_id = $1 ${instrument ? 'AND instrument = $2' : ''}
        ${timeWindow ? 'AND timestamp >= $3 AND timestamp <= $4' : ''}
      GROUP BY DATE_TRUNC('day', timestamp)
      ORDER BY day_bucket DESC
      LIMIT 30
    `, timeWindow
      ? [ruleId, instrument, timeWindow.start, timeWindow.end]
      : instrument
        ? [ruleId, instrument]
        : [ruleId]
    );

    for (const row of rows) {
      metrics.push({
        timeBucket: 'daily',
        startTime: row.day_bucket,
        endTime: new Date(row.day_bucket.getTime() + 24 * 60 * 60 * 1000),
        metrics: {
          successRate: parseFloat(row.successes) / parseFloat(row.volume),
          averageROI: parseFloat(row.avg_roi) || 0,
          volume: parseInt(row.volume)
        }
      });
    }

    return metrics;
  }

  /**
   * Calculate instrument-partitioned metrics
   */
  private async calculateInstrumentPartitionedMetrics(
    ruleId: string,
    timeWindow?: { start: Date; end: Date }
  ): Promise<InstrumentPartitionedMetrics[]> {
    const { rows } = await this.db.query(`
      SELECT
        instrument,
        COUNT(*) as volume,
        COUNT(CASE WHEN outcome = 'SUCCESS' THEN 1 END) as successes,
        AVG(CASE WHEN profit_loss IS NOT NULL AND entry_price IS NOT NULL
                 THEN profit_loss / entry_price ELSE 0 END) as avg_roi
      FROM alert_outcomes
      WHERE rule_id = $1 ${timeWindow ? 'AND timestamp >= $2 AND timestamp <= $3' : ''}
      GROUP BY instrument
      ORDER BY volume DESC
    `, timeWindow ? [ruleId, timeWindow.start, timeWindow.end] : [ruleId]);

    return rows.map(row => ({
      instrument: row.instrument,
      metrics: {
        successRate: parseFloat(row.successes) / parseFloat(row.volume),
        averageROI: parseFloat(row.avg_roi) || 0,
        volume: parseInt(row.volume),
        correlationWithMarket: 0 // Would calculate actual correlation with market data
      }
    }));
  }

  /**
   * Calculate market regime performance
   */
  private async calculateMarketRegimePerformance(
    ruleId: string,
    instrument?: string,
    timeWindow?: { start: Date; end: Date }
  ): Promise<MarketRegimePerformance[]> {
    // This is a simplified version - in practice, you'd want to detect market regimes
    // using volatility, trend analysis, etc.

    const { rows } = await this.db.query(`
      SELECT
        market_regime,
        COUNT(*) as volume,
        COUNT(CASE WHEN outcome = 'SUCCESS' THEN 1 END) as successes,
        AVG(CASE WHEN profit_loss IS NOT NULL AND entry_price IS NOT NULL
                 THEN profit_loss / entry_price ELSE 0 END) as avg_roi,
        AVG(CASE WHEN profit_loss IS NOT NULL THEN ABS(profit_loss) ELSE 0 END) as avg_risk
      FROM alert_outcomes
      WHERE rule_id = $1 ${instrument ? 'AND instrument = $2' : ''}
        ${timeWindow ? 'AND timestamp >= $3 AND timestamp <= $4' : ''}
        AND market_regime IS NOT NULL
      GROUP BY market_regime
      ORDER BY volume DESC
    `, timeWindow
      ? [ruleId, instrument, timeWindow.start, timeWindow.end]
      : instrument
        ? [ruleId, instrument]
        : [ruleId]
    );

    return rows.map(row => ({
      regime: row.market_regime as any,
      confidence: 0.8, // Would calculate based on regime detection confidence
      metrics: {
        successRate: parseFloat(row.successes) / parseFloat(row.volume),
        averageROI: parseFloat(row.avg_roi) || 0,
        riskAdjustedReturn: (parseFloat(row.avg_roi) || 0) / (parseFloat(row.avg_risk) || 1)
      }
    }));
  }

  /**
   * Calculate confidence distribution analysis
   */
  private calculateConfidenceDistribution(outcomes: any[]): ConfidenceDistribution[] {
    const buckets = [
      { range: '0.0-0.2', min: 0.0, max: 0.2 },
      { range: '0.2-0.4', min: 0.2, max: 0.4 },
      { range: '0.4-0.6', min: 0.4, max: 0.6 },
      { range: '0.6-0.8', min: 0.6, max: 0.8 },
      { range: '0.8-1.0', min: 0.8, max: 1.0 }
    ];

    return buckets.map(bucket => {
      const bucketOutcomes = outcomes.filter(o =>
        o.confidence >= bucket.min && o.confidence < bucket.max
      );

      const successes = bucketOutcomes.filter(o => o.outcome === 'SUCCESS').length;
      const totalROI = bucketOutcomes.reduce((sum, o) => {
        if (o.profit_loss && o.entry_price) {
          return sum + (o.profit_loss / o.entry_price);
        }
        return sum;
      }, 0);

      return {
        confidenceRange: bucket.range,
        count: bucketOutcomes.length,
        successRate: bucketOutcomes.length > 0 ? successes / bucketOutcomes.length : 0,
        averageROI: bucketOutcomes.length > 0 ? totalROI / bucketOutcomes.length : 0
      };
    });
  }

  /**
   * Calculate overall signal quality score
   */
  private calculateSignalQualityScore(outcomes: any[]): number {
    if (outcomes.length === 0) return 0;

    // Weighted combination of factors
    const successRate = outcomes.filter(o => o.outcome === 'SUCCESS').length / outcomes.length;
    const avgConfidence = outcomes.reduce((sum, o) => sum + o.confidence, 0) / outcomes.length;
    const consistencyScore = this.calculateConsistencyScore(outcomes);

    // Weight the factors
    const weights = { success: 0.4, confidence: 0.3, consistency: 0.3 };

    return (
      successRate * weights.success +
      avgConfidence * weights.confidence +
      consistencyScore * weights.consistency
    );
  }

  /**
   * Calculate consistency score based on outcome patterns
   */
  private calculateConsistencyScore(outcomes: any[]): number {
    if (outcomes.length < 3) return 0.5; // Neutral score for small sample sizes

    // Calculate the entropy of outcomes (lower entropy = more consistent)
    const outcomeCounts = outcomes.reduce((counts, outcome) => {
      counts[outcome.outcome] = (counts[outcome.outcome] || 0) + 1;
      return counts;
    }, {} as Record<string, number>);

    const total = outcomes.length;
    let entropy = 0;

    for (const count of Object.values(outcomeCounts)) {
      const p = count as number / total;
      if (p > 0) {
        entropy -= p * Math.log2(p);
      }
    }

    // Normalize entropy (max entropy for 4 outcomes is ~2 bits)
    const normalizedEntropy = entropy / 2;
    return 1 - normalizedEntropy; // Higher consistency = lower entropy
  }

  /**
   * Generate adaptive weights for the weighting engine
   */
  private generateAdaptiveWeights(
    outcomes: any[],
    marketRegimePerformance: MarketRegimePerformance[]
  ): AdaptiveWeights {
    // This would be a more sophisticated algorithm in practice
    // For now, using simple heuristics based on recent performance

    const recentOutcomes = outcomes.slice(-50); // Last 50 outcomes
    const recentSuccessRate = recentOutcomes.filter(o => o.outcome === 'SUCCESS').length / recentOutcomes.length;

    // Adaptive weights based on performance and market conditions
    return {
      signalStrengthWeight: Math.min(0.9, 0.5 + recentSuccessRate),
      historicalPerformanceWeight: recentSuccessRate > 0.7 ? 0.8 : 0.6,
      marketRegimeWeight: 0.7, // Market regime is usually important
      userRiskToleranceWeight: 0.6,
      temporalWeight: 0.8, // Recent performance is more relevant
      instrumentSpecificWeight: 0.7
    };
  }

  /**
   * Trigger recalculation for updated metrics
   */
  private triggerRecalculation(ruleId: string, instrument: string): void {
    // Debounce recalculation to avoid excessive computation
    setTimeout(async () => {
      try {
        const metrics = await this.calculatePerformanceMetrics(ruleId, instrument);
        this.emit('metricsUpdated', { ruleId, instrument, metrics });
      } catch (error) {
        this.logger.error('Failed to recalculate metrics', error);
      }
    }, 1000); // 1 second debounce
  }

  /**
   * Start the analytics service
   */
  async start(): Promise<void> {
    if (this.isInitialized) {
      // Start periodic batch calculations
      this.calculationIntervals.push(
        setInterval(() => {
          this.performBatchCalculations();
        }, this.config.calculationIntervals.batch * 60 * 1000)
      );

      this.logger.info('✅ Alert performance analytics started');
      this.emit('started');
    }
  }

  /**
   * Stop the analytics service
   */
  async stop(): Promise<void> {
    // Clear calculation intervals
    this.calculationIntervals.forEach(interval => clearInterval(interval));
    this.calculationIntervals = [];

    // Close database connection
    await this.db.end();

    this.isInitialized = false;
    this.logger.info('✅ Alert performance analytics stopped');
    this.emit('stopped');
  }

  /**
   * Perform batch calculations for all active rules
   */
  private async performBatchCalculations(): Promise<void> {
    try {
      // Get all unique rule IDs
      const { rows } = await this.db.query(`
        SELECT DISTINCT rule_id FROM alert_outcomes
        WHERE timestamp >= NOW() - INTERVAL '${this.config.timeWindows.medium} hours'
      `);

      for (const row of rows) {
        const ruleId = row.rule_id;
        try {
          await this.calculatePerformanceMetrics(ruleId);
        } catch (error) {
          this.logger.error(`Failed to calculate metrics for rule ${ruleId}`, error);
        }
      }

      this.logger.debug('Batch calculations completed', { ruleCount: rows.length });
    } catch (error) {
      this.logger.error('Batch calculation failed', error);
    }
  }
}
