/**
 * L10.2 — Hypothesis Object Violation Codes
 *
 * §10.2 — Disjoint from L10.1 constitutional codes; prefixed `L10O_` so
 * constitutional and object-tier audit records remain unambiguous.
 */

export enum L10ObjectViolationCode {
  // Subject
  SUBJECT_MISSING_ID = 'L10O_SUBJECT_MISSING_ID',
  SUBJECT_MISSING_CLASS = 'L10O_SUBJECT_MISSING_CLASS',
  SUBJECT_CLASS_UNREGISTERED = 'L10O_SUBJECT_CLASS_UNREGISTERED',
  SUBJECT_MISSING_SCOPE = 'L10O_SUBJECT_MISSING_SCOPE',
  SUBJECT_SCOPE_ILLEGAL_FOR_CLASS = 'L10O_SUBJECT_SCOPE_ILLEGAL_FOR_CLASS',
  SUBJECT_MISSING_AS_OF = 'L10O_SUBJECT_MISSING_AS_OF',
  SUBJECT_MISSING_WINDOW = 'L10O_SUBJECT_MISSING_WINDOW',
  SUBJECT_ILLEGAL_WINDOW = 'L10O_SUBJECT_ILLEGAL_WINDOW',
  SUBJECT_MISSING_FAMILY_SET = 'L10O_SUBJECT_MISSING_FAMILY_SET',
  SUBJECT_FAMILY_UNREGISTERED = 'L10O_SUBJECT_FAMILY_UNREGISTERED',
  SUBJECT_FAMILY_SCOPE_ILLEGAL = 'L10O_SUBJECT_FAMILY_SCOPE_ILLEGAL',
  SUBJECT_MISSING_INPUT_DECLARATIONS = 'L10O_SUBJECT_MISSING_INPUT_DECLARATIONS',
  SUBJECT_MISSING_VALIDATION_INPUTS = 'L10O_SUBJECT_MISSING_VALIDATION_INPUTS',
  SUBJECT_MISSING_REGIME_INPUTS = 'L10O_SUBJECT_MISSING_REGIME_INPUTS',
  SUBJECT_MISSING_SEQUENCE_INPUTS = 'L10O_SUBJECT_MISSING_SEQUENCE_INPUTS',
  SUBJECT_MISSING_CANDIDATE_RULES = 'L10O_SUBJECT_MISSING_CANDIDATE_RULES',
  SUBJECT_PRESELECTED_CANDIDATE = 'L10O_SUBJECT_PRESELECTED_CANDIDATE',
  SUBJECT_MISSING_LINEAGE = 'L10O_SUBJECT_MISSING_LINEAGE',
  SUBJECT_MATERIALITY_UNREGISTERED = 'L10O_SUBJECT_MATERIALITY_UNREGISTERED',
  SUBJECT_MISSING_INPUT_SNAPSHOT = 'L10O_SUBJECT_MISSING_INPUT_SNAPSHOT',

  // Candidate
  CANDIDATE_MISSING_ID = 'L10O_CANDIDATE_MISSING_ID',
  CANDIDATE_MISSING_SUBJECT = 'L10O_CANDIDATE_MISSING_SUBJECT',
  CANDIDATE_MISSING_FAMILY = 'L10O_CANDIDATE_MISSING_FAMILY',
  CANDIDATE_FAMILY_UNREGISTERED = 'L10O_CANDIDATE_FAMILY_UNREGISTERED',
  CANDIDATE_MISSING_TEMPLATE = 'L10O_CANDIDATE_MISSING_TEMPLATE',
  CANDIDATE_MISSING_NAME = 'L10O_CANDIDATE_MISSING_NAME',
  CANDIDATE_NAME_LEAKS_SEMANTICS = 'L10O_CANDIDATE_NAME_LEAKS_SEMANTICS',
  CANDIDATE_MISSING_SUPPORT_DOMAINS = 'L10O_CANDIDATE_MISSING_SUPPORT_DOMAINS',
  CANDIDATE_MISSING_CHALLENGE_DOMAINS = 'L10O_CANDIDATE_MISSING_CHALLENGE_DOMAINS',
  CANDIDATE_MISSING_CONFIRMATION_DOMAINS = 'L10O_CANDIDATE_MISSING_CONFIRMATION_DOMAINS',
  CANDIDATE_MISSING_INVALIDATION_DOMAINS = 'L10O_CANDIDATE_MISSING_INVALIDATION_DOMAINS',
  CANDIDATE_MISSING_REGIME_CONDITIONING = 'L10O_CANDIDATE_MISSING_REGIME_CONDITIONING',
  CANDIDATE_MISSING_SEQUENCE_CONDITIONING = 'L10O_CANDIDATE_MISSING_SEQUENCE_CONDITIONING',
  CANDIDATE_CARRIES_FINALITY = 'L10O_CANDIDATE_CARRIES_FINALITY',

  // Support
  SUPPORT_MISSING_ID = 'L10O_SUPPORT_MISSING_ID',
  SUPPORT_MISSING_CANDIDATE = 'L10O_SUPPORT_MISSING_CANDIDATE',
  SUPPORT_CLAIMED_WITHOUT_REFS = 'L10O_SUPPORT_CLAIMED_WITHOUT_REFS',
  SUPPORT_MISSING_DOMAINS = 'L10O_SUPPORT_MISSING_DOMAINS',
  SUPPORT_STRENGTH_OUT_OF_RANGE = 'L10O_SUPPORT_STRENGTH_OOR',
  SUPPORT_COVERAGE_OUT_OF_RANGE = 'L10O_SUPPORT_COVERAGE_OOR',
  SUPPORT_MISSING_LINEAGE = 'L10O_SUPPORT_MISSING_LINEAGE',
  SUPPORT_HIDDEN_STALENESS = 'L10O_SUPPORT_HIDDEN_STALENESS',

  // Contradiction
  CONTRADICTION_MISSING_ID = 'L10O_CONTRADICTION_MISSING_ID',
  CONTRADICTION_MISSING_CANDIDATE = 'L10O_CONTRADICTION_MISSING_CANDIDATE',
  CONTRADICTION_CLAIMED_WITHOUT_REFS = 'L10O_CONTRADICTION_CLAIMED_WITHOUT_REFS',
  CONTRADICTION_MISSING_DOMAINS = 'L10O_CONTRADICTION_MISSING_DOMAINS',
  CONTRADICTION_PRESSURE_OUT_OF_RANGE = 'L10O_CONTRADICTION_PRESSURE_OOR',
  CONTRADICTION_BLOCKING_NOT_SEPARATED = 'L10O_CONTRADICTION_BLOCKING_NOT_SEPARATED',
  CONTRADICTION_MISSING_LINEAGE = 'L10O_CONTRADICTION_MISSING_LINEAGE',

  // Confirmation
  CONFIRMATION_MISSING_ID = 'L10O_CONFIRMATION_MISSING_ID',
  CONFIRMATION_MISSING_CANDIDATE = 'L10O_CONFIRMATION_MISSING_CANDIDATE',
  CONFIRMATION_REQUIRED_NOT_SURFACED = 'L10O_CONFIRMATION_REQUIRED_NOT_SURFACED',
  CONFIRMATION_PRESENT_MISSING_NOT_SEPARATED = 'L10O_CONFIRMATION_PRESENT_MISSING_NOT_SEPARATED',
  CONFIRMATION_GAP_OUT_OF_RANGE = 'L10O_CONFIRMATION_GAP_OOR',
  CONFIRMATION_MISSING_LINEAGE = 'L10O_CONFIRMATION_MISSING_LINEAGE',

  // Invalidation
  INVALIDATION_MISSING_ID = 'L10O_INVALIDATION_MISSING_ID',
  INVALIDATION_MISSING_CANDIDATE = 'L10O_INVALIDATION_MISSING_CANDIDATE',
  INVALIDATION_RISK_CLAIMED_WITHOUT_REFS = 'L10O_INVALIDATION_RISK_CLAIMED_WITHOUT_REFS',
  INVALIDATION_ACTIVE_POTENTIAL_NOT_SEPARATED = 'L10O_INVALIDATION_ACTIVE_POTENTIAL_NOT_SEPARATED',
  INVALIDATION_RISK_OUT_OF_RANGE = 'L10O_INVALIDATION_RISK_OOR',
  INVALIDATION_MISSING_LINEAGE = 'L10O_INVALIDATION_MISSING_LINEAGE',

  // Assessment
  ASSESSMENT_MISSING_ID = 'L10O_ASSESSMENT_MISSING_ID',
  ASSESSMENT_MISSING_SUBJECT = 'L10O_ASSESSMENT_MISSING_SUBJECT',
  ASSESSMENT_MISSING_CANDIDATE = 'L10O_ASSESSMENT_MISSING_CANDIDATE',
  ASSESSMENT_MISSING_FAMILY = 'L10O_ASSESSMENT_MISSING_FAMILY',
  ASSESSMENT_MISSING_TEMPLATE = 'L10O_ASSESSMENT_MISSING_TEMPLATE',
  ASSESSMENT_MISSING_NAME = 'L10O_ASSESSMENT_MISSING_NAME',
  ASSESSMENT_NAME_LEAKS_SEMANTICS = 'L10O_ASSESSMENT_NAME_LEAKS_SEMANTICS',
  ASSESSMENT_MISSING_SUPPORT_OBJECT = 'L10O_ASSESSMENT_MISSING_SUPPORT_OBJECT',
  ASSESSMENT_MISSING_CONTRADICTION_OBJECT = 'L10O_ASSESSMENT_MISSING_CONTRADICTION_OBJECT',
  ASSESSMENT_MISSING_CONFIRMATION_OBJECT = 'L10O_ASSESSMENT_MISSING_CONFIRMATION_OBJECT',
  ASSESSMENT_MISSING_INVALIDATION_OBJECT = 'L10O_ASSESSMENT_MISSING_INVALIDATION_OBJECT',
  ASSESSMENT_MISSING_RANK_POSITION = 'L10O_ASSESSMENT_MISSING_RANK_POSITION',
  ASSESSMENT_MISSING_RANK_SPREAD = 'L10O_ASSESSMENT_MISSING_RANK_SPREAD',
  ASSESSMENT_MISSING_RESTRICTION_PROFILE = 'L10O_ASSESSMENT_MISSING_RESTRICTION_PROFILE',
  ASSESSMENT_MISSING_EVIDENCE_PACK = 'L10O_ASSESSMENT_MISSING_EVIDENCE_PACK',
  ASSESSMENT_MISSING_INPUT_SNAPSHOT = 'L10O_ASSESSMENT_MISSING_INPUT_SNAPSHOT',
  ASSESSMENT_MISSING_COMPUTE_RUN = 'L10O_ASSESSMENT_MISSING_COMPUTE_RUN',
  ASSESSMENT_MISSING_REPLAY_HASH = 'L10O_ASSESSMENT_MISSING_REPLAY_HASH',
  ASSESSMENT_MISSING_LINEAGE = 'L10O_ASSESSMENT_MISSING_LINEAGE',
  ASSESSMENT_MISSING_POLICY_VERSION = 'L10O_ASSESSMENT_MISSING_POLICY_VERSION',
  ASSESSMENT_MISSING_CAUSAL_RESTRAINT = 'L10O_ASSESSMENT_MISSING_CAUSAL_RESTRAINT',
  ASSESSMENT_CONFIDENCE_OUT_OF_RANGE = 'L10O_ASSESSMENT_CONFIDENCE_OOR',
  ASSESSMENT_CONFIDENCE_BAND_INCONSISTENT = 'L10O_ASSESSMENT_CONFIDENCE_BAND_INCONSISTENT',
  ASSESSMENT_SUPPORT_SCORE_OUT_OF_RANGE = 'L10O_ASSESSMENT_SUPPORT_OOR',
  ASSESSMENT_CONTRADICTION_SCORE_OUT_OF_RANGE = 'L10O_ASSESSMENT_CONTRADICTION_OOR',
  ASSESSMENT_CONFIRMATION_SCORE_OUT_OF_RANGE = 'L10O_ASSESSMENT_CONFIRMATION_OOR',
  ASSESSMENT_INVALIDATION_SCORE_OUT_OF_RANGE = 'L10O_ASSESSMENT_INVALIDATION_OOR',

  // Ranking
  RANKING_MISSING_ID = 'L10O_RANKING_MISSING_ID',
  RANKING_MISSING_SUBJECT = 'L10O_RANKING_MISSING_SUBJECT',
  RANKING_MISSING_ORDERED_REFS = 'L10O_RANKING_MISSING_ORDERED_REFS',
  RANKING_MISSING_PRIMARY = 'L10O_RANKING_MISSING_PRIMARY',
  RANKING_MISSING_SECONDARY_WHEN_COMPETITION = 'L10O_RANKING_MISSING_SECONDARY_WHEN_COMPETITION',
  RANKING_PRIMARY_NOT_FIRST = 'L10O_RANKING_PRIMARY_NOT_FIRST',
  RANKING_MISSING_SPREAD_PROFILE = 'L10O_RANKING_MISSING_SPREAD_PROFILE',
  RANKING_MISSING_REPLAY_HASH = 'L10O_RANKING_MISSING_REPLAY_HASH',
  RANKING_MISSING_LINEAGE = 'L10O_RANKING_MISSING_LINEAGE',
  RANKING_SINGLE_STORY_COLLAPSE = 'L10O_RANKING_SINGLE_STORY_COLLAPSE',

  // Spread
  SPREAD_MISSING_ID = 'L10O_SPREAD_MISSING_ID',
  SPREAD_MISSING_PRIMARY = 'L10O_SPREAD_MISSING_PRIMARY',
  SPREAD_MISSING_SECONDARY_WHEN_COMPETITION = 'L10O_SPREAD_MISSING_SECONDARY_WHEN_COMPETITION',
  SPREAD_MISSING_MAGNITUDE = 'L10O_SPREAD_MISSING_MAGNITUDE',
  SPREAD_MAGNITUDE_OUT_OF_RANGE = 'L10O_SPREAD_MAGNITUDE_OOR',
  SPREAD_CLASS_INCONSISTENT = 'L10O_SPREAD_CLASS_INCONSISTENT',
  SPREAD_MISSING_CLASS = 'L10O_SPREAD_MISSING_CLASS',
  SPREAD_NARROW_FLAG_HIDDEN = 'L10O_SPREAD_NARROW_FLAG_HIDDEN',
  SPREAD_MISSING_LINEAGE = 'L10O_SPREAD_MISSING_LINEAGE',

  // Shift-condition
  SHIFT_MISSING_ID = 'L10O_SHIFT_MISSING_ID',
  SHIFT_MISSING_PRIMARY = 'L10O_SHIFT_MISSING_PRIMARY',
  SHIFT_MISSING_SECONDARY_WHEN_COMPETITION = 'L10O_SHIFT_MISSING_SECONDARY_WHEN_COMPETITION',
  SHIFT_MISSING_PROMOTION_CONDITIONS = 'L10O_SHIFT_MISSING_PROMOTION_CONDITIONS',
  SHIFT_MISSING_REINFORCEMENT_CONDITIONS = 'L10O_SHIFT_MISSING_REINFORCEMENT_CONDITIONS',
  SHIFT_MISSING_COLLAPSE_CONDITIONS = 'L10O_SHIFT_MISSING_COLLAPSE_CONDITIONS',
  SHIFT_MISSING_LINEAGE = 'L10O_SHIFT_MISSING_LINEAGE',

  // Restriction
  RESTRICTION_MISSING_ID = 'L10O_RESTRICTION_MISSING_ID',
  RESTRICTION_MISSING_BAND = 'L10O_RESTRICTION_MISSING_BAND',
  RESTRICTION_BAND_UNREGISTERED = 'L10O_RESTRICTION_BAND_UNREGISTERED',
  RESTRICTION_MISSING_ALLOWED_USES = 'L10O_RESTRICTION_MISSING_ALLOWED_USES',
  RESTRICTION_MISSING_BLOCKED_USES = 'L10O_RESTRICTION_MISSING_BLOCKED_USES',
  RESTRICTION_MISSING_MANDATORY_BLOCKED_USES = 'L10O_RESTRICTION_MISSING_MANDATORY_BLOCKED_USES',
  RESTRICTION_MISSING_NARROWING_REASONS = 'L10O_RESTRICTION_MISSING_NARROWING_REASONS',
  RESTRICTION_UNREGISTERED_RIGHT = 'L10O_RESTRICTION_UNREGISTERED_RIGHT',
  RESTRICTION_UNREGISTERED_BLOCKED_USE = 'L10O_RESTRICTION_UNREGISTERED_BLOCKED_USE',
  RESTRICTION_MISSING_LINEAGE = 'L10O_RESTRICTION_MISSING_LINEAGE',

  // Output semantics (cross-cutting)
  OUTPUT_UNREGISTERED_CLASS = 'L10O_OUTPUT_UNREGISTERED_CLASS',
  OUTPUT_JUDGMENT_LEAK = 'L10O_OUTPUT_JUDGMENT_LEAK',
  OUTPUT_RECOMMENDATION_LEAK = 'L10O_OUTPUT_RECOMMENDATION_LEAK',
  OUTPUT_SCENARIO_FINALITY_LEAK = 'L10O_OUTPUT_SCENARIO_FINALITY_LEAK',
  OUTPUT_FAKE_CERTAINTY_LEAK = 'L10O_OUTPUT_FAKE_CERTAINTY_LEAK',
  OUTPUT_CAUSAL_PROOF_LEAK = 'L10O_OUTPUT_CAUSAL_PROOF_LEAK',
  OUTPUT_FREEFORM_NARRATIVE = 'L10O_OUTPUT_FREEFORM_NARRATIVE',
}

export const ALL_L10_OBJECT_VIOLATION_CODES: readonly L10ObjectViolationCode[] =
  Object.values(L10ObjectViolationCode);

export interface L10ObjectValidationIssue {
  readonly code: L10ObjectViolationCode;
  readonly message: string;
  readonly details?: Record<string, unknown>;
}

export interface L10ObjectValidationReport {
  readonly valid: boolean;
  readonly issues: readonly L10ObjectValidationIssue[];
}

/**
 * §10.2.20.4 — Semantic-leak patterns at the object tier. Any hypothesis
 * object whose name or description matches these patterns is rejected.
 */
export const L10_OBJECT_LEAK_PATTERNS: readonly {
  readonly regex: RegExp;
  readonly code: L10ObjectViolationCode;
  readonly label: string;
}[] = [
  { regex: /\b(final\s*judgment|judgment|verdict\s*is|ruling|decided)\b/i,
    code: L10ObjectViolationCode.OUTPUT_JUDGMENT_LEAK, label: 'judgment' },
  { regex: /\b(recommend|recommendation|buy|sell|short|long|accumulate)\b/i,
    code: L10ObjectViolationCode.OUTPUT_RECOMMENDATION_LEAK, label: 'recommendation' },
  { regex: /\b(final\s*scenario|scenario\s*locked|scenario\s*confirmed|outcome\s*set)\b/i,
    code: L10ObjectViolationCode.OUTPUT_SCENARIO_FINALITY_LEAK, label: 'scenario-finality' },
  { regex: /\b(certain|certainty|guaranteed|proven|definitive|no\s*doubt)\b/i,
    code: L10ObjectViolationCode.OUTPUT_FAKE_CERTAINTY_LEAK, label: 'fake-certainty' },
  { regex: /\b(caused\s*by|because\s*of|proves\s*cause|causal\s*proof)\b/i,
    code: L10ObjectViolationCode.OUTPUT_CAUSAL_PROOF_LEAK, label: 'causal-proof' },
];

/**
 * Split camelCase and PascalCase into word-boundary-friendly text so
 * leak patterns can reliably match names like "BuyRecommendationVerdict".
 */
function splitCamelCase(s: string): string {
  return s
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1 $2');
}

export function checkL10ObjectLeak(
  text: string,
): { readonly leaks: boolean; readonly code?: L10ObjectViolationCode; readonly label?: string } {
  if (!text) return { leaks: false };
  const normalized = splitCamelCase(text);
  for (const p of L10_OBJECT_LEAK_PATTERNS) {
    if (p.regex.test(normalized)) return { leaks: true, code: p.code, label: p.label };
  }
  return { leaks: false };
}
