/**
 * L10.4 — Runtime Violation Codes
 *
 * §10.4.18.1 — `L10RuntimeViolationCode`. Disjoint from the
 * L10.1 boundary codes (`L10_*`), L10.2 object codes (`L10O_*`),
 * and L10.3 contract codes (`L10C_*`) so that an audit record's tier
 * is unambiguous from its violation code alone.
 *
 * Every code begins with the prefix `L10R_` to identify the runtime
 * tier of Layer 10.
 */

export enum L10RuntimeViolationCode {
  // ── DAG legality (§10.4.2, §10.4.4) ──
  DAG_ILLEGAL_NODE_CLASS = 'L10R_DAG_ILLEGAL_NODE_CLASS',
  DAG_ILLEGAL_EDGE_CLASS = 'L10R_DAG_ILLEGAL_EDGE_CLASS',
  DAG_ILLEGAL_EDGE_TRANSITION = 'L10R_DAG_ILLEGAL_EDGE_TRANSITION',
  DAG_NODE_STAGE_MISMATCH = 'L10R_DAG_NODE_STAGE_MISMATCH',
  DAG_CYCLE_DETECTED = 'L10R_DAG_CYCLE_DETECTED',
  DAG_UNRESOLVED_DEPENDENCY = 'L10R_DAG_UNRESOLVED_DEPENDENCY',
  DAG_MISSING_TERMINAL_NODE = 'L10R_DAG_MISSING_TERMINAL_NODE',
  DAG_NON_DETERMINISTIC_ORDER = 'L10R_DAG_NON_DETERMINISTIC_ORDER',
  DAG_DUPLICATE_NODE_ID = 'L10R_DAG_DUPLICATE_NODE_ID',
  DAG_INPUT_TO_RANKING_JUMP = 'L10R_DAG_INPUT_TO_RANKING_JUMP',
  DAG_SUBJECT_TO_SPREAD_JUMP = 'L10R_DAG_SUBJECT_TO_SPREAD_JUMP',
  DAG_SUPPORT_TO_MATERIALIZATION_JUMP = 'L10R_DAG_SUPPORT_TO_MATERIALIZATION_JUMP',
  DAG_CONFIDENCE_TO_CANDIDATE_BACKEDGE = 'L10R_DAG_CONFIDENCE_TO_CANDIDATE_BACKEDGE',
  DAG_RANKING_TO_SUBJECT_BACKEDGE = 'L10R_DAG_RANKING_TO_SUBJECT_BACKEDGE',
  DAG_CANDIDATE_NODE_MISSING_CANDIDATE_ID = 'L10R_DAG_CANDIDATE_NODE_MISSING_CANDIDATE_ID',
  DAG_SUBJECT_NODE_CARRIES_CANDIDATE_ID = 'L10R_DAG_SUBJECT_NODE_CARRIES_CANDIDATE_ID',
  DAG_SHIFT_WITHOUT_SPREAD = 'L10R_DAG_SHIFT_WITHOUT_SPREAD',
  DAG_SPREAD_WITHOUT_RANKING = 'L10R_DAG_SPREAD_WITHOUT_RANKING',

  // ── Run lineage (§10.4.2.7-8) ──
  RUN_LINEAGE_MISSING = 'L10R_RUN_LINEAGE_MISSING',
  RUN_MODE_MISSING = 'L10R_RUN_MODE_MISSING',
  RUN_ENGINE_SET_INCOMPLETE = 'L10R_RUN_ENGINE_SET_INCOMPLETE',
  RUN_DETERMINISM_BROKEN = 'L10R_RUN_DETERMINISM_BROKEN',
  RUN_PARENT_REQUIRED = 'L10R_RUN_PARENT_REQUIRED',
  RUN_TEMPLATE_SET_INCOMPLETE = 'L10R_RUN_TEMPLATE_SET_INCOMPLETE',

  // ── Subject assembly (§10.4.5) ──
  ASSEMBLY_UNREGISTERED_FAMILY = 'L10R_ASSEMBLY_UNREGISTERED_FAMILY',
  ASSEMBLY_UNREGISTERED_SUBJECT_CLASS = 'L10R_ASSEMBLY_UNREGISTERED_SUBJECT_CLASS',
  ASSEMBLY_ILLEGAL_SCOPE_BINDING = 'L10R_ASSEMBLY_ILLEGAL_SCOPE_BINDING',
  ASSEMBLY_FAMILY_SCOPE_ILLEGAL = 'L10R_ASSEMBLY_FAMILY_SCOPE_ILLEGAL',
  ASSEMBLY_LINEAGE_INCOMPLETE = 'L10R_ASSEMBLY_LINEAGE_INCOMPLETE',
  ASSEMBLY_CONTRACT_INCOMPLETE = 'L10R_ASSEMBLY_CONTRACT_INCOMPLETE',
  ASSEMBLY_JUDGMENT_LEAK = 'L10R_ASSEMBLY_JUDGMENT_LEAK',
  ASSEMBLY_NON_DETERMINISTIC_ID = 'L10R_ASSEMBLY_NON_DETERMINISTIC_ID',
  ASSEMBLY_REGIME_REQUIREMENT_MISSING = 'L10R_ASSEMBLY_REGIME_REQUIREMENT_MISSING',
  ASSEMBLY_SEQUENCE_REQUIREMENT_MISSING = 'L10R_ASSEMBLY_SEQUENCE_REQUIREMENT_MISSING',
  ASSEMBLY_RESTRICTION_REQUIREMENT_MISSING = 'L10R_ASSEMBLY_RESTRICTION_REQUIREMENT_MISSING',
  ASSEMBLY_NO_CANDIDATE_SPACE = 'L10R_ASSEMBLY_NO_CANDIDATE_SPACE',
  ASSEMBLY_NO_COMPETITION_SPACE = 'L10R_ASSEMBLY_NO_COMPETITION_SPACE',
  ASSEMBLY_TEMPORAL_WINDOW_MISSING = 'L10R_ASSEMBLY_TEMPORAL_WINDOW_MISSING',
  ASSEMBLY_MISSING_REQUIRED_INPUTS = 'L10R_ASSEMBLY_MISSING_REQUIRED_INPUTS',

  // ── Candidate generation (§10.4.6) ──
  CANDIDATE_UNREGISTERED_FAMILY = 'L10R_CANDIDATE_UNREGISTERED_FAMILY',
  CANDIDATE_UNREGISTERED_TEMPLATE = 'L10R_CANDIDATE_UNREGISTERED_TEMPLATE',
  CANDIDATE_FORBIDDEN_TEMPLATE = 'L10R_CANDIDATE_FORBIDDEN_TEMPLATE',
  CANDIDATE_FAMILY_SCOPE_ILLEGAL = 'L10R_CANDIDATE_FAMILY_SCOPE_ILLEGAL',
  CANDIDATE_SINGLE_STORY_COLLAPSE = 'L10R_CANDIDATE_SINGLE_STORY_COLLAPSE',
  CANDIDATE_PRE_SELECTED_PRIMARY = 'L10R_CANDIDATE_PRE_SELECTED_PRIMARY',
  CANDIDATE_MISSING_REQUIRED_TEMPLATE = 'L10R_CANDIDATE_MISSING_REQUIRED_TEMPLATE',
  CANDIDATE_MIN_COUNT_UNMET = 'L10R_CANDIDATE_MIN_COUNT_UNMET',
  CANDIDATE_MISSING_TEMPLATE_SEMANTICS = 'L10R_CANDIDATE_MISSING_TEMPLATE_SEMANTICS',
  CANDIDATE_REGIME_CONDITIONING_MISSING = 'L10R_CANDIDATE_REGIME_CONDITIONING_MISSING',
  CANDIDATE_SEQUENCE_CONDITIONING_MISSING = 'L10R_CANDIDATE_SEQUENCE_CONDITIONING_MISSING',
  CANDIDATE_COMPETITION_GROUP_MISMATCH = 'L10R_CANDIDATE_COMPETITION_GROUP_MISMATCH',
  CANDIDATE_NAME_LEAK = 'L10R_CANDIDATE_NAME_LEAK',
  CANDIDATE_DUPLICATE_ID = 'L10R_CANDIDATE_DUPLICATE_ID',
  CANDIDATE_SUPPRESSED_PLAUSIBLE = 'L10R_CANDIDATE_SUPPRESSED_PLAUSIBLE',

  // ── Support resolver (§10.4.7) ──
  SUPPORT_CLAIMED_WITHOUT_REFS = 'L10R_SUPPORT_CLAIMED_WITHOUT_REFS',
  SUPPORT_REF_OUT_OF_DOMAIN = 'L10R_SUPPORT_REF_OUT_OF_DOMAIN',
  SUPPORT_STALE_AS_CLEAN = 'L10R_SUPPORT_STALE_AS_CLEAN',
  SUPPORT_DEGRADED_AS_CLEAN = 'L10R_SUPPORT_DEGRADED_AS_CLEAN',
  SUPPORT_MISSING_REQUIRED = 'L10R_SUPPORT_MISSING_REQUIRED',
  SUPPORT_CANDIDATE_AGNOSTIC_REUSE = 'L10R_SUPPORT_CANDIDATE_AGNOSTIC_REUSE',
  SUPPORT_SCORE_OUT_OF_RANGE = 'L10R_SUPPORT_SCORE_OUT_OF_RANGE',
  SUPPORT_COVERAGE_OUT_OF_RANGE = 'L10R_SUPPORT_COVERAGE_OUT_OF_RANGE',

  // ── Contradiction resolver (§10.4.8) ──
  CONTRADICTION_OMITTED_BUT_PRESENT = 'L10R_CONTRADICTION_OMITTED_BUT_PRESENT',
  CONTRADICTION_BLOCKING_AS_NARROWING = 'L10R_CONTRADICTION_BLOCKING_AS_NARROWING',
  CONTRADICTION_DIRECT_AS_INDIRECT = 'L10R_CONTRADICTION_DIRECT_AS_INDIRECT',
  CONTRADICTION_ACTIVE_AS_DECAYED = 'L10R_CONTRADICTION_ACTIVE_AS_DECAYED',
  CONTRADICTION_IGNORES_L7_POSTURE = 'L10R_CONTRADICTION_IGNORES_L7_POSTURE',
  CONTRADICTION_CLAIMED_WITHOUT_REFS = 'L10R_CONTRADICTION_CLAIMED_WITHOUT_REFS',
  CONTRADICTION_PRESSURE_OUT_OF_RANGE = 'L10R_CONTRADICTION_PRESSURE_OUT_OF_RANGE',

  // ── Confirmation engine (§10.4.9) ──
  CONFIRMATION_GAP_HIDDEN = 'L10R_CONFIRMATION_GAP_HIDDEN',
  CONFIRMATION_REQUIRED_VS_PRESENT_COLLAPSED = 'L10R_CONFIRMATION_REQUIRED_VS_PRESENT_COLLAPSED',
  CONFIRMATION_NO_GAP_SCORE = 'L10R_CONFIRMATION_NO_GAP_SCORE',
  CONFIRMATION_HIGH_CONVICTION_DESPITE_GAP = 'L10R_CONFIRMATION_HIGH_CONVICTION_DESPITE_GAP',
  CONFIRMATION_GAP_OUT_OF_RANGE = 'L10R_CONFIRMATION_GAP_OUT_OF_RANGE',

  // ── Invalidation engine (§10.4.10) ──
  INVALIDATION_RISK_CLAIMED_WITHOUT_REFS = 'L10R_INVALIDATION_RISK_CLAIMED_WITHOUT_REFS',
  INVALIDATION_ACTIVE_AND_POTENTIAL_MERGED = 'L10R_INVALIDATION_ACTIVE_AND_POTENTIAL_MERGED',
  INVALIDATION_HIGH_RISK_HIDDEN = 'L10R_INVALIDATION_HIGH_RISK_HIDDEN',
  INVALIDATION_POSTURE_OMITTED = 'L10R_INVALIDATION_POSTURE_OMITTED',
  INVALIDATION_RISK_OUT_OF_RANGE = 'L10R_INVALIDATION_RISK_OUT_OF_RANGE',

  // ── Confidence engine (§10.4.11) ──
  CONFIDENCE_IGNORES_CONTRADICTION = 'L10R_CONFIDENCE_IGNORES_CONTRADICTION',
  CONFIDENCE_IGNORES_CONFIRMATION_GAP = 'L10R_CONFIDENCE_IGNORES_CONFIRMATION_GAP',
  CONFIDENCE_IGNORES_INVALIDATION = 'L10R_CONFIDENCE_IGNORES_INVALIDATION',
  CONFIDENCE_IGNORES_L7_POSTURE = 'L10R_CONFIDENCE_IGNORES_L7_POSTURE',
  CONFIDENCE_IGNORES_L8_REGIME = 'L10R_CONFIDENCE_IGNORES_L8_REGIME',
  CONFIDENCE_IGNORES_L9_SEQUENCE = 'L10R_CONFIDENCE_IGNORES_L9_SEQUENCE',
  CONFIDENCE_ASSIGNED_PRIMARY = 'L10R_CONFIDENCE_ASSIGNED_PRIMARY',
  CONFIDENCE_ASSIGNED_SPREAD = 'L10R_CONFIDENCE_ASSIGNED_SPREAD',
  CONFIDENCE_SCORE_OUT_OF_RANGE = 'L10R_CONFIDENCE_SCORE_OUT_OF_RANGE',
  CONFIDENCE_BAND_INCONSISTENT = 'L10R_CONFIDENCE_BAND_INCONSISTENT',

  // ── Ranking engine (§10.4.12) ──
  RANKING_PRIMARY_WITHOUT_COMPETITION_CONTEXT =
    'L10R_RANKING_PRIMARY_WITHOUT_COMPETITION_CONTEXT',
  RANKING_SECONDARY_SUPPRESSED = 'L10R_RANKING_SECONDARY_SUPPRESSED',
  RANKING_SINGLE_STORY_COLLAPSE = 'L10R_RANKING_SINGLE_STORY_COLLAPSE',
  RANKING_IGNORES_BLOCKING_CONTRADICTION = 'L10R_RANKING_IGNORES_BLOCKING_CONTRADICTION',
  RANKING_IGNORES_RESTRICTION = 'L10R_RANKING_IGNORES_RESTRICTION',
  RANKING_DOUBLE_ASSIGNMENT = 'L10R_RANKING_DOUBLE_ASSIGNMENT',
  RANKING_PRIMARY_NOT_IN_CANDIDATE_SET = 'L10R_RANKING_PRIMARY_NOT_IN_CANDIDATE_SET',
  RANKING_PRIMARY_SAME_AS_SECONDARY = 'L10R_RANKING_PRIMARY_SAME_AS_SECONDARY',
  RANKING_ORDER_INCONSISTENT_WITH_CONFIDENCE =
    'L10R_RANKING_ORDER_INCONSISTENT_WITH_CONFIDENCE',
  RANKING_NARRATIVE_PREFERENCE = 'L10R_RANKING_NARRATIVE_PREFERENCE',
  RANKING_FAMILY_TEMPLATE_ILLEGAL = 'L10R_RANKING_FAMILY_TEMPLATE_ILLEGAL',

  // ── Spread engine (§10.4.13) ──
  SPREAD_MISSING_DESPITE_COMPETITION = 'L10R_SPREAD_MISSING_DESPITE_COMPETITION',
  SPREAD_NARROW_HIDDEN = 'L10R_SPREAD_NARROW_HIDDEN',
  SPREAD_STABILITY_MISSING = 'L10R_SPREAD_STABILITY_MISSING',
  SPREAD_INCONSISTENT_CANDIDATE_SET = 'L10R_SPREAD_INCONSISTENT_CANDIDATE_SET',
  SPREAD_MAGNITUDE_OUT_OF_RANGE = 'L10R_SPREAD_MAGNITUDE_OUT_OF_RANGE',
  SPREAD_CLASS_INCONSISTENT = 'L10R_SPREAD_CLASS_INCONSISTENT',

  // ── Shift condition engine (§10.4.14) ──
  SHIFT_MISSING_PROMOTION = 'L10R_SHIFT_MISSING_PROMOTION',
  SHIFT_MISSING_COLLAPSE = 'L10R_SHIFT_MISSING_COLLAPSE',
  SHIFT_CONTRADICTS_SUPPORT = 'L10R_SHIFT_CONTRADICTS_SUPPORT',
  SHIFT_DETACHED_FROM_CANDIDATE = 'L10R_SHIFT_DETACHED_FROM_CANDIDATE',
  SHIFT_INVENTED_WITHOUT_EVIDENCE = 'L10R_SHIFT_INVENTED_WITHOUT_EVIDENCE',
  SHIFT_REQUIRED_BY_SPREAD_MISSING = 'L10R_SHIFT_REQUIRED_BY_SPREAD_MISSING',

  // ── Evidence pack (§10.4.15.1) ──
  EVIDENCE_PACK_INCOMPLETE = 'L10R_EVIDENCE_PACK_INCOMPLETE',
  EVIDENCE_PACK_MISSING_LINEAGE = 'L10R_EVIDENCE_PACK_MISSING_LINEAGE',
  EVIDENCE_PACK_NON_DETERMINISTIC = 'L10R_EVIDENCE_PACK_NON_DETERMINISTIC',
  EVIDENCE_PACK_MISSING_SUPPORT = 'L10R_EVIDENCE_PACK_MISSING_SUPPORT',
  EVIDENCE_PACK_MISSING_CONTRADICTION = 'L10R_EVIDENCE_PACK_MISSING_CONTRADICTION',
  EVIDENCE_PACK_MISSING_CONFIRMATION = 'L10R_EVIDENCE_PACK_MISSING_CONFIRMATION',
  EVIDENCE_PACK_MISSING_INVALIDATION = 'L10R_EVIDENCE_PACK_MISSING_INVALIDATION',
  EVIDENCE_PACK_MISSING_RANKING = 'L10R_EVIDENCE_PACK_MISSING_RANKING',
  EVIDENCE_PACK_MISSING_SPREAD = 'L10R_EVIDENCE_PACK_MISSING_SPREAD',
  EVIDENCE_PACK_MISSING_SHIFT_CONDITIONS = 'L10R_EVIDENCE_PACK_MISSING_SHIFT_CONDITIONS',
  EVIDENCE_PACK_MISSING_CONSUMED_REFS = 'L10R_EVIDENCE_PACK_MISSING_CONSUMED_REFS',

  // ── Materialization (§10.4.15.2) ──
  MATERIALIZATION_DIRECT_STORE_WRITE = 'L10R_MATERIALIZATION_DIRECT_STORE_WRITE',
  MATERIALIZATION_BYPASSES_L5 = 'L10R_MATERIALIZATION_BYPASSES_L5',
  MATERIALIZATION_PREREQUISITES_MISSING = 'L10R_MATERIALIZATION_PREREQUISITES_MISSING',
  MATERIALIZATION_CONTRACT_INVALID = 'L10R_MATERIALIZATION_CONTRACT_INVALID',
  MATERIALIZATION_READINESS_INCONSISTENT = 'L10R_MATERIALIZATION_READINESS_INCONSISTENT',
  MATERIALIZATION_SEMANTIC_REPAIR = 'L10R_MATERIALIZATION_SEMANTIC_REPAIR',
  MATERIALIZATION_CLEANED_NARROWED_COMPETITION =
    'L10R_MATERIALIZATION_CLEANED_NARROWED_COMPETITION',

  // ── Replay / repair (§10.4.15.3-4) ──
  REPLAY_HASH_DIVERGED = 'L10R_REPLAY_HASH_DIVERGED',
  REPLAY_PRETENDS_LIVE = 'L10R_REPLAY_PRETENDS_LIVE',
  REPLAY_INVENTED_CANDIDATE = 'L10R_REPLAY_INVENTED_CANDIDATE',
  REPLAY_ERASED_ALTERNATIVE = 'L10R_REPLAY_ERASED_ALTERNATIVE',
  REPLAY_SPREAD_SUPPRESSED = 'L10R_REPLAY_SPREAD_SUPPRESSED',
  REPLAY_RESTRICTION_DRIFT = 'L10R_REPLAY_RESTRICTION_DRIFT',
  REPLAY_LINEAGE_BROKEN = 'L10R_REPLAY_LINEAGE_BROKEN',
  REPLAY_RANKING_DRIFT = 'L10R_REPLAY_RANKING_DRIFT',
  REPAIR_LINEAGE_BROKEN = 'L10R_REPAIR_LINEAGE_BROKEN',
  REPAIR_UNMARKED = 'L10R_REPAIR_UNMARKED',
  REPAIR_REASON_MISSING = 'L10R_REPAIR_REASON_MISSING',
  REPAIR_LIVE_MASQUERADE = 'L10R_REPAIR_LIVE_MASQUERADE',
  REPAIR_SEMANTIC_DRIFT_UNJUSTIFIED = 'L10R_REPAIR_SEMANTIC_DRIFT_UNJUSTIFIED',
}

export const ALL_L10_RUNTIME_VIOLATION_CODES:
  readonly L10RuntimeViolationCode[] =
    Object.values(L10RuntimeViolationCode);

/**
 * §10.4.18.1 — Runtime violation record. Every engine emits these
 * into the `L10RuntimeAudit` log and carries context for replay-safe
 * auditing.
 */
export interface L10RuntimeViolation {
  readonly code: L10RuntimeViolationCode;
  readonly source: string;
  readonly nodeId: string | null;
  readonly hypothesis_run_id: string | null;
  readonly hypothesis_subject_id: string | null;
  readonly hypothesis_candidate_id: string | null;
  readonly detail: string;
  readonly context: Record<string, unknown>;
}

export class L10RuntimeError extends Error {
  public readonly code: L10RuntimeViolationCode;
  public readonly details: Record<string, unknown>;

  constructor(
    code: L10RuntimeViolationCode,
    message: string,
    details: Record<string, unknown> = {},
  ) {
    super(`[${code}] ${message}`);
    this.name = 'L10RuntimeError';
    this.code = code;
    this.details = details;
  }
}
