/**
 * L10.7 — Reliance-Governance Violation Codes
 *
 * §10.7.10.2 — Typed violation codes for every L10.7 validator.
 * Disjoint from the L10 constitutional (`L10_`), L10.2 object
 * (`L10O_`), L10.3 contract (`L10C_`), L10.4 runtime (`L10R_`), L10.5
 * evidence-semantics (`L10E_`), and L10.6 family/template (`L10F_`)
 * code spaces. L10.7 uses the `L10REL_` prefix (reliance).
 */

export enum L10HypothesisRelianceViolationCode {
  // ── Confidence-policy law (§10.7.2 / §10.7.3) ──
  CONF_FACTOR_GROUP_MISSING = 'L10REL_CONF_FACTOR_GROUP_MISSING',
  CONF_FACTOR_CLASS_UNREGISTERED = 'L10REL_CONF_FACTOR_CLASS_UNREGISTERED',
  CONF_FACTOR_EFFECT_UNREGISTERED = 'L10REL_CONF_FACTOR_EFFECT_UNREGISTERED',
  CONF_FACTOR_RAW_OUT_OF_RANGE = 'L10REL_CONF_FACTOR_RAW_OUT_OF_RANGE',
  CONF_FACTOR_NORMALIZED_OUT_OF_RANGE =
    'L10REL_CONF_FACTOR_NORMALIZED_OUT_OF_RANGE',
  CONF_FACTOR_ID_DUPLICATE = 'L10REL_CONF_FACTOR_ID_DUPLICATE',
  CONF_FACTOR_POLICY_VERSION_MISSING =
    'L10REL_CONF_FACTOR_POLICY_VERSION_MISSING',
  CONF_RAW_SCORE_OUT_OF_RANGE = 'L10REL_CONF_RAW_SCORE_OUT_OF_RANGE',
  CONF_CAPPED_SCORE_OUT_OF_RANGE = 'L10REL_CONF_CAPPED_SCORE_OUT_OF_RANGE',
  CONF_CAPPED_GT_RAW = 'L10REL_CONF_CAPPED_GT_RAW',
  CONF_BAND_INCONSISTENT_WITH_CAPPED =
    'L10REL_CONF_BAND_INCONSISTENT_WITH_CAPPED',
  CONF_BLOCKING_FACTOR_UNDER_CLEAN_BAND =
    'L10REL_CONF_BLOCKING_FACTOR_UNDER_CLEAN_BAND',
  CONF_PRIMARY_REF_MISSING = 'L10REL_CONF_PRIMARY_REF_MISSING',
  CONF_SECONDARY_IMPLIED_WITHOUT_REF =
    'L10REL_CONF_SECONDARY_IMPLIED_WITHOUT_REF',
  CONF_REPLAY_HASH_MISSING = 'L10REL_CONF_REPLAY_HASH_MISSING',

  // ── Cap-chain law (§10.7.6) ──
  CAP_REASON_UNREGISTERED = 'L10REL_CAP_REASON_UNREGISTERED',
  CAP_DUPLICATE_REASON = 'L10REL_CAP_DUPLICATE_REASON',
  CAP_PRECEDENCE_VIOLATED = 'L10REL_CAP_PRECEDENCE_VIOLATED',
  CAP_POST_CAP_EXCEEDS_CEILING = 'L10REL_CAP_POST_CAP_EXCEEDS_CEILING',
  CAP_POST_CAP_EXCEEDS_PRE_CAP = 'L10REL_CAP_POST_CAP_EXCEEDS_PRE_CAP',
  CAP_REQUIRED_CAP_MISSING = 'L10REL_CAP_REQUIRED_CAP_MISSING',
  CAP_TIGHTEST_INCONSISTENT = 'L10REL_CAP_TIGHTEST_INCONSISTENT',
  CAP_DOMINANT_INCONSISTENT = 'L10REL_CAP_DOMINANT_INCONSISTENT',
  CAP_WIDENING_ATTEMPTED = 'L10REL_CAP_WIDENING_ATTEMPTED',
  CAP_READINESS_HINT_INCONSISTENT = 'L10REL_CAP_READINESS_HINT_INCONSISTENT',
  CAP_EDGE_CEILING_MISMATCH = 'L10REL_CAP_EDGE_CEILING_MISMATCH',
  CAP_EDGE_RANK_MISMATCH = 'L10REL_CAP_EDGE_RANK_MISMATCH',

  // ── Restriction-rights law (§10.7.5) ──
  RESTR_PROFILE_MISSING = 'L10REL_RESTR_PROFILE_MISSING',
  RESTR_RIGHT_UNREGISTERED = 'L10REL_RESTR_RIGHT_UNREGISTERED',
  RESTR_BAND_UNREGISTERED = 'L10REL_RESTR_BAND_UNREGISTERED',
  RESTR_BROADER_THAN_STATE = 'L10REL_RESTR_BROADER_THAN_STATE',
  RESTR_SCORE_DRIVING_WITH_EVIDENCE_ONLY =
    'L10REL_RESTR_SCORE_DRIVING_WITH_EVIDENCE_ONLY',
  RESTR_IGNORES_CONTRADICTION_DISCLOSURE =
    'L10REL_RESTR_IGNORES_CONTRADICTION_DISCLOSURE',
  RESTR_IGNORES_NARROW_SPREAD = 'L10REL_RESTR_IGNORES_NARROW_SPREAD',
  RESTR_ADDITIONAL_CONFIRMATION_IGNORED =
    'L10REL_RESTR_ADDITIONAL_CONFIRMATION_IGNORED',
  RESTR_BLOCKED_RIGHT_STILL_GRANTED =
    'L10REL_RESTR_BLOCKED_RIGHT_STILL_GRANTED',
  RESTR_FINAL_JUDGMENT_UNDER_UNRESOLVED =
    'L10REL_RESTR_FINAL_JUDGMENT_UNDER_UNRESOLVED',

  // ── Readiness law (§10.7.7) ──
  READ_CLASS_UNREGISTERED = 'L10REL_READ_CLASS_UNREGISTERED',
  READ_STRONG_UNDER_NARROW_SPREAD = 'L10REL_READ_STRONG_UNDER_NARROW_SPREAD',
  READ_STRONG_UNDER_ACTIVE_INVALIDATION =
    'L10REL_READ_STRONG_UNDER_ACTIVE_INVALIDATION',
  READ_STRONG_UNDER_MISSING_CONFIRMATIONS =
    'L10REL_READ_STRONG_UNDER_MISSING_CONFIRMATIONS',
  READ_NARROWED_WITHOUT_CAUSE = 'L10REL_READ_NARROWED_WITHOUT_CAUSE',
  READ_UNRESOLVED_WITHOUT_COMPETITION =
    'L10REL_READ_UNRESOLVED_WITHOUT_COMPETITION',
  READ_BLOCKED_WHILE_BROAD_RIGHTS_GRANTED =
    'L10REL_READ_BLOCKED_WHILE_BROAD_RIGHTS_GRANTED',
  READ_INCONSISTENT_WITH_DERIVED = 'L10REL_READ_INCONSISTENT_WITH_DERIVED',

  // ── Reliance-profile law (§10.7.9) ──
  REL_PROFILE_MISSING = 'L10REL_REL_PROFILE_MISSING',
  REL_CONFIDENCE_MISMATCH = 'L10REL_REL_CONFIDENCE_MISMATCH',
  REL_BAND_MISMATCH = 'L10REL_REL_BAND_MISMATCH',
  REL_CAP_CHAIN_MISMATCH = 'L10REL_REL_CAP_CHAIN_MISMATCH',
  REL_SPREAD_MISMATCH = 'L10REL_REL_SPREAD_MISMATCH',
  REL_RESTRICTION_MISMATCH = 'L10REL_REL_RESTRICTION_MISMATCH',
  REL_READINESS_INCONSISTENT = 'L10REL_REL_READINESS_INCONSISTENT',
  REL_REPLAY_HASH_MISSING = 'L10REL_REL_REPLAY_HASH_MISSING',
  REL_POLICY_VERSION_MISMATCH = 'L10REL_REL_POLICY_VERSION_MISMATCH',

  // ── Regime / sequence interaction (§10.7.8 / INV-10.7-F) ──
  REGIME_LOCAL_IMPERSONATES_FINAL = 'L10REL_REGIME_LOCAL_IMPERSONATES_FINAL',
  REGIME_OVERRIDE_ATTEMPTED = 'L10REL_REGIME_OVERRIDE_ATTEMPTED',
  SEQUENCE_LOCAL_IMPERSONATES_FINAL =
    'L10REL_SEQUENCE_LOCAL_IMPERSONATES_FINAL',
  SEQUENCE_OVERRIDE_ATTEMPTED = 'L10REL_SEQUENCE_OVERRIDE_ATTEMPTED',
}

export const ALL_L10_HYPOTHESIS_RELIANCE_VIOLATION_CODES:
  readonly L10HypothesisRelianceViolationCode[] =
    Object.values(L10HypothesisRelianceViolationCode);

/**
 * §10.7.10.2 — Semantic tier label. Parallels L10.6
 * `L10FamilyViolationTier` so audits can distinguish which L10.7
 * sub-law raised a given rejection.
 */
export enum L10HypothesisRelianceViolationTier {
  CONFIDENCE = 'CONFIDENCE',
  CAP_CHAIN = 'CAP_CHAIN',
  RESTRICTION = 'RESTRICTION',
  READINESS = 'READINESS',
  RELIANCE = 'RELIANCE',
  REGIME = 'REGIME',
  SEQUENCE = 'SEQUENCE',
}

export const ALL_L10_HYPOTHESIS_RELIANCE_VIOLATION_TIERS:
  readonly L10HypothesisRelianceViolationTier[] =
    Object.values(L10HypothesisRelianceViolationTier);

export interface L10HypothesisRelianceViolation {
  readonly code: L10HypothesisRelianceViolationCode;
  readonly tier: L10HypothesisRelianceViolationTier;
  readonly detail: string;
  readonly offending_refs?: readonly string[];
}

export class L10HypothesisRelianceValidationError extends Error {
  constructor(
    public readonly violations: readonly L10HypothesisRelianceViolation[],
  ) {
    super(
      `L10.7 reliance validation failed with ${violations.length} ` +
        `violation(s): ${violations.map(v => v.code).join(', ')}`,
    );
    this.name = 'L10HypothesisRelianceValidationError';
  }
}

/**
 * §10.7.10.2 — Canonical code → tier mapping. Used by the audit layer
 * to group violations without hand-maintaining parallel switches.
 */
export function l10HypothesisRelianceViolationTier(
  code: L10HypothesisRelianceViolationCode,
): L10HypothesisRelianceViolationTier {
  const s = String(code);
  if (s.startsWith('L10REL_CONF_')) {
    return L10HypothesisRelianceViolationTier.CONFIDENCE;
  }
  if (s.startsWith('L10REL_CAP_')) {
    return L10HypothesisRelianceViolationTier.CAP_CHAIN;
  }
  if (s.startsWith('L10REL_RESTR_')) {
    return L10HypothesisRelianceViolationTier.RESTRICTION;
  }
  if (s.startsWith('L10REL_READ_')) {
    return L10HypothesisRelianceViolationTier.READINESS;
  }
  if (s.startsWith('L10REL_REL_')) {
    return L10HypothesisRelianceViolationTier.RELIANCE;
  }
  if (s.startsWith('L10REL_REGIME_')) {
    return L10HypothesisRelianceViolationTier.REGIME;
  }
  if (s.startsWith('L10REL_SEQUENCE_')) {
    return L10HypothesisRelianceViolationTier.SEQUENCE;
  }
  return L10HypothesisRelianceViolationTier.RELIANCE;
}
