/**
 * L10.3 — Contract Violation Codes
 *
 * §10.3.11 — Typed violation codes for every L10.3 contract validator.
 * Disjoint from L10.1 constitutional codes (`L10_`) and L10.2 object-
 * model codes (`L10O_`) so audit records are unambiguous about which
 * tier rejected an artifact. L10.3 uses the `L10C_` prefix.
 */

export enum L10HypothesisContractViolationCode {
  // ── Subject contract (§10.3.2) ──
  SUBJECT_MISSING_IDENTITY = 'L10C_SUBJECT_MISSING_IDENTITY',
  SUBJECT_MISSING_CLASS = 'L10C_SUBJECT_MISSING_CLASS',
  SUBJECT_CLASS_UNREGISTERED = 'L10C_SUBJECT_CLASS_UNREGISTERED',
  SUBJECT_MISSING_VERSION = 'L10C_SUBJECT_MISSING_VERSION',
  SUBJECT_MISSING_CONTRACT_VERSION = 'L10C_SUBJECT_MISSING_CONTRACT_VERSION',
  SUBJECT_MISSING_SCHEMA_VERSION = 'L10C_SUBJECT_MISSING_SCHEMA_VERSION',
  SUBJECT_MISSING_POLICY_VERSION = 'L10C_SUBJECT_MISSING_POLICY_VERSION',
  SUBJECT_MISSING_SCOPE = 'L10C_SUBJECT_MISSING_SCOPE',
  SUBJECT_MISSING_SCOPE_GRANULARITY = 'L10C_SUBJECT_MISSING_SCOPE_GRANULARITY',
  SUBJECT_MISSING_MATERIALITY = 'L10C_SUBJECT_MISSING_MATERIALITY',
  SUBJECT_MISSING_TEMPORAL = 'L10C_SUBJECT_MISSING_TEMPORAL',
  SUBJECT_MISSING_WINDOW = 'L10C_SUBJECT_MISSING_WINDOW',
  SUBJECT_MISSING_FAMILY_SET = 'L10C_SUBJECT_MISSING_FAMILY_SET',
  SUBJECT_FAMILY_UNREGISTERED = 'L10C_SUBJECT_FAMILY_UNREGISTERED',
  SUBJECT_FAMILY_SCOPE_ILLEGAL = 'L10C_SUBJECT_FAMILY_SCOPE_ILLEGAL',
  SUBJECT_MISSING_VALIDATION_INPUTS = 'L10C_SUBJECT_MISSING_VALIDATION_INPUTS',
  SUBJECT_MISSING_REGIME_INPUTS = 'L10C_SUBJECT_MISSING_REGIME_INPUTS',
  SUBJECT_MISSING_SEQUENCE_INPUTS = 'L10C_SUBJECT_MISSING_SEQUENCE_INPUTS',
  SUBJECT_MISSING_FEATURE_INPUTS = 'L10C_SUBJECT_MISSING_FEATURE_INPUTS',
  SUBJECT_MISSING_EVENT_INPUTS = 'L10C_SUBJECT_MISSING_EVENT_INPUTS',
  SUBJECT_INPUT_FAMILY_MIX = 'L10C_SUBJECT_INPUT_FAMILY_MIX',
  SUBJECT_MISSING_CANDIDATE_GENERATION = 'L10C_SUBJECT_MISSING_CANDIDATE_GENERATION',
  SUBJECT_CANDIDATE_GEN_PRESELECTED = 'L10C_SUBJECT_CANDIDATE_GEN_PRESELECTED',
  SUBJECT_CANDIDATE_GEN_TEMPLATE_CONFLICT = 'L10C_SUBJECT_CANDIDATE_GEN_TEMPLATE_CONFLICT',
  SUBJECT_MISSING_COMPETITION_POLICY = 'L10C_SUBJECT_MISSING_COMPETITION_POLICY',
  SUBJECT_MISSING_CLEANLINESS_POLICY = 'L10C_SUBJECT_MISSING_CLEANLINESS_POLICY',
  SUBJECT_MISSING_MATERIALIZATION_POLICY = 'L10C_SUBJECT_MISSING_MATERIALIZATION_POLICY',
  SUBJECT_MISSING_EVIDENCE_POLICY = 'L10C_SUBJECT_MISSING_EVIDENCE_POLICY',
  SUBJECT_MISSING_RESTRICTION_POLICY = 'L10C_SUBJECT_MISSING_RESTRICTION_POLICY',
  SUBJECT_MISSING_REGIME_POLICY = 'L10C_SUBJECT_MISSING_REGIME_POLICY',
  SUBJECT_MISSING_SEQUENCE_POLICY = 'L10C_SUBJECT_MISSING_SEQUENCE_POLICY',
  SUBJECT_MISSING_VALIDATION_POLICY = 'L10C_SUBJECT_MISSING_VALIDATION_POLICY',
  SUBJECT_MISSING_CAUSAL_RESTRAINT_POLICY = 'L10C_SUBJECT_MISSING_CAUSAL_RESTRAINT_POLICY',
  SUBJECT_MISSING_INPUT_SNAPSHOT = 'L10C_SUBJECT_MISSING_INPUT_SNAPSHOT',
  SUBJECT_MISSING_LINEAGE_POLICY = 'L10C_SUBJECT_MISSING_LINEAGE_POLICY',
  SUBJECT_MISSING_LINEAGE_REFS = 'L10C_SUBJECT_MISSING_LINEAGE_REFS',
  SUBJECT_JUDGMENT_LEAK = 'L10C_SUBJECT_JUDGMENT_LEAK',

  // ── Candidate contract (§10.3.3) ──
  CANDIDATE_MISSING_IDENTITY = 'L10C_CANDIDATE_MISSING_IDENTITY',
  CANDIDATE_MISSING_SUBJECT = 'L10C_CANDIDATE_MISSING_SUBJECT',
  CANDIDATE_MISSING_FAMILY = 'L10C_CANDIDATE_MISSING_FAMILY',
  CANDIDATE_FAMILY_UNREGISTERED = 'L10C_CANDIDATE_FAMILY_UNREGISTERED',
  CANDIDATE_MISSING_TEMPLATE = 'L10C_CANDIDATE_MISSING_TEMPLATE',
  CANDIDATE_MISSING_TEMPLATE_VERSION = 'L10C_CANDIDATE_MISSING_TEMPLATE_VERSION',
  CANDIDATE_MISSING_NAME = 'L10C_CANDIDATE_MISSING_NAME',
  CANDIDATE_NAME_LEAKS_SEMANTICS = 'L10C_CANDIDATE_NAME_LEAKS_SEMANTICS',
  CANDIDATE_MISSING_CONTRACT_VERSION = 'L10C_CANDIDATE_MISSING_CONTRACT_VERSION',
  CANDIDATE_MISSING_SUPPORT_PATTERNS = 'L10C_CANDIDATE_MISSING_SUPPORT_PATTERNS',
  CANDIDATE_MISSING_CHALLENGE_PATTERNS = 'L10C_CANDIDATE_MISSING_CHALLENGE_PATTERNS',
  CANDIDATE_MISSING_CONFIRMATION_PATTERNS = 'L10C_CANDIDATE_MISSING_CONFIRMATION_PATTERNS',
  CANDIDATE_MISSING_INVALIDATION_PATTERNS = 'L10C_CANDIDATE_MISSING_INVALIDATION_PATTERNS',
  CANDIDATE_MISSING_REGIME_CONDITIONING = 'L10C_CANDIDATE_MISSING_REGIME_CONDITIONING',
  CANDIDATE_MISSING_SEQUENCE_CONDITIONING = 'L10C_CANDIDATE_MISSING_SEQUENCE_CONDITIONING',
  CANDIDATE_MISSING_RESTRICTION_DEFAULTS = 'L10C_CANDIDATE_MISSING_RESTRICTION_DEFAULTS',
  CANDIDATE_MISSING_CONFIDENCE_SPEC = 'L10C_CANDIDATE_MISSING_CONFIDENCE_SPEC',
  CANDIDATE_MISSING_SUPPORT_THRESHOLDS = 'L10C_CANDIDATE_MISSING_SUPPORT_THRESHOLDS',
  CANDIDATE_MISSING_CHALLENGE_TOLERANCE = 'L10C_CANDIDATE_MISSING_CHALLENGE_TOLERANCE',
  CANDIDATE_MISSING_COMPETITION_GROUP = 'L10C_CANDIDATE_MISSING_COMPETITION_GROUP',
  CANDIDATE_MISSING_LINEAGE = 'L10C_CANDIDATE_MISSING_LINEAGE',
  CANDIDATE_CARRIES_FINALITY = 'L10C_CANDIDATE_CARRIES_FINALITY',

  // ── Output contract (§10.3.5) ──
  OUTPUT_MISSING_IDENTITY = 'L10C_OUTPUT_MISSING_IDENTITY',
  OUTPUT_MISSING_SUBJECT_REF = 'L10C_OUTPUT_MISSING_SUBJECT_REF',
  OUTPUT_MISSING_CANDIDATE_REF = 'L10C_OUTPUT_MISSING_CANDIDATE_REF',
  OUTPUT_MISSING_SUBJECT_CONTRACT_REF = 'L10C_OUTPUT_MISSING_SUBJECT_CONTRACT_REF',
  OUTPUT_MISSING_CANDIDATE_CONTRACT_REF = 'L10C_OUTPUT_MISSING_CANDIDATE_CONTRACT_REF',
  OUTPUT_MISSING_CONTRACT_VERSION = 'L10C_OUTPUT_MISSING_CONTRACT_VERSION',
  OUTPUT_MISSING_SCHEMA_VERSION = 'L10C_OUTPUT_MISSING_SCHEMA_VERSION',
  OUTPUT_MISSING_POLICY_VERSION = 'L10C_OUTPUT_MISSING_POLICY_VERSION',
  OUTPUT_MISSING_FAMILY = 'L10C_OUTPUT_MISSING_FAMILY',
  OUTPUT_MISSING_TEMPLATE = 'L10C_OUTPUT_MISSING_TEMPLATE',
  OUTPUT_MISSING_SCOPE = 'L10C_OUTPUT_MISSING_SCOPE',
  OUTPUT_MISSING_TIME_ANCHOR = 'L10C_OUTPUT_MISSING_TIME_ANCHOR',
  OUTPUT_MISSING_SUPPORT_SET = 'L10C_OUTPUT_MISSING_SUPPORT_SET',
  OUTPUT_MISSING_CONTRADICTION_SET = 'L10C_OUTPUT_MISSING_CONTRADICTION_SET',
  OUTPUT_MISSING_CONFIRMATION_SET = 'L10C_OUTPUT_MISSING_CONFIRMATION_SET',
  OUTPUT_MISSING_INVALIDATION_SET = 'L10C_OUTPUT_MISSING_INVALIDATION_SET',
  OUTPUT_SUPPORT_CLAIMED_WITHOUT_REFS = 'L10C_OUTPUT_SUPPORT_CLAIMED_WITHOUT_REFS',
  OUTPUT_CONTRADICTION_CLAIMED_WITHOUT_REFS = 'L10C_OUTPUT_CONTRADICTION_CLAIMED_WITHOUT_REFS',
  OUTPUT_CONFIRMATION_REQUIRED_BUT_MISSING = 'L10C_OUTPUT_CONFIRMATION_REQUIRED_BUT_MISSING',
  OUTPUT_INVALIDATION_CLAIMED_WITHOUT_REFS = 'L10C_OUTPUT_INVALIDATION_CLAIMED_WITHOUT_REFS',
  OUTPUT_SCORE_OUT_OF_RANGE = 'L10C_OUTPUT_SCORE_OOR',
  OUTPUT_CONFIDENCE_BAND_INCONSISTENT = 'L10C_OUTPUT_CONFIDENCE_BAND_INCONSISTENT',
  OUTPUT_MISSING_RANKING_REF = 'L10C_OUTPUT_MISSING_RANKING_REF',
  OUTPUT_MISSING_RANK_POSITION = 'L10C_OUTPUT_MISSING_RANK_POSITION',
  OUTPUT_MISSING_RANK_SPREAD = 'L10C_OUTPUT_MISSING_RANK_SPREAD',
  OUTPUT_MISSING_RESTRICTION_PROFILE = 'L10C_OUTPUT_MISSING_RESTRICTION_PROFILE',
  OUTPUT_MISSING_SPREAD_PROFILE = 'L10C_OUTPUT_MISSING_SPREAD_PROFILE',
  OUTPUT_MISSING_EVIDENCE_PACK = 'L10C_OUTPUT_MISSING_EVIDENCE_PACK',
  OUTPUT_MISSING_INPUT_SNAPSHOT = 'L10C_OUTPUT_MISSING_INPUT_SNAPSHOT',
  OUTPUT_MISSING_RUN_ID = 'L10C_OUTPUT_MISSING_RUN_ID',
  OUTPUT_MISSING_REPLAY_HASH = 'L10C_OUTPUT_MISSING_REPLAY_HASH',
  OUTPUT_MISSING_LINEAGE = 'L10C_OUTPUT_MISSING_LINEAGE',
  OUTPUT_MISSING_INTEGRITY_FLAGS = 'L10C_OUTPUT_MISSING_INTEGRITY_FLAGS',
  OUTPUT_MISSING_MATERIALIZATION = 'L10C_OUTPUT_MISSING_MATERIALIZATION',
  OUTPUT_MISSING_CAUSAL_RESTRAINT = 'L10C_OUTPUT_MISSING_CAUSAL_RESTRAINT',
  OUTPUT_MISSING_POSTURE_CONSUMPTION = 'L10C_OUTPUT_MISSING_POSTURE_CONSUMPTION',
  OUTPUT_JUDGMENT_LEAK = 'L10C_OUTPUT_JUDGMENT_LEAK',
  OUTPUT_RECOMMENDATION_LEAK = 'L10C_OUTPUT_RECOMMENDATION_LEAK',
  OUTPUT_SCENARIO_FINALITY_LEAK = 'L10C_OUTPUT_SCENARIO_FINALITY_LEAK',
  OUTPUT_FAKE_CERTAINTY_LEAK = 'L10C_OUTPUT_FAKE_CERTAINTY_LEAK',
  OUTPUT_CAUSAL_PROOF_LEAK = 'L10C_OUTPUT_CAUSAL_PROOF_LEAK',
  OUTPUT_PRIMARY_AS_FINAL_TRUTH = 'L10C_OUTPUT_PRIMARY_AS_FINAL_TRUTH',

  // ── Ranking contract (§10.3.6) ──
  RANKING_MISSING_IDENTITY = 'L10C_RANKING_MISSING_IDENTITY',
  RANKING_MISSING_SUBJECT = 'L10C_RANKING_MISSING_SUBJECT',
  RANKING_MISSING_CONTRACT_VERSION = 'L10C_RANKING_MISSING_CONTRACT_VERSION',
  RANKING_MISSING_ORDERED_REFS = 'L10C_RANKING_MISSING_ORDERED_REFS',
  RANKING_MISSING_PRIMARY = 'L10C_RANKING_MISSING_PRIMARY',
  RANKING_MISSING_SECONDARY_WHEN_COMPETITION = 'L10C_RANKING_MISSING_SECONDARY_WHEN_COMPETITION',
  RANKING_PRIMARY_NOT_FIRST = 'L10C_RANKING_PRIMARY_NOT_FIRST',
  RANKING_MISSING_COMPETITION_SIZE = 'L10C_RANKING_MISSING_COMPETITION_SIZE',
  RANKING_COMPETITION_SIZE_INCONSISTENT = 'L10C_RANKING_COMPETITION_SIZE_INCONSISTENT',
  RANKING_MISSING_SPREAD = 'L10C_RANKING_MISSING_SPREAD',
  RANKING_SPREAD_OUT_OF_RANGE = 'L10C_RANKING_SPREAD_OOR',
  RANKING_MISSING_STABILITY_CLASS = 'L10C_RANKING_MISSING_STABILITY_CLASS',
  RANKING_MISSING_SPREAD_PROFILE = 'L10C_RANKING_MISSING_SPREAD_PROFILE',
  RANKING_MISSING_REPLAY_HASH = 'L10C_RANKING_MISSING_REPLAY_HASH',
  RANKING_MISSING_LINEAGE = 'L10C_RANKING_MISSING_LINEAGE',
  RANKING_SINGLE_STORY_COLLAPSE = 'L10C_RANKING_SINGLE_STORY_COLLAPSE',

  // ── Spread contract (§10.3.7.1) ──
  SPREAD_MISSING_IDENTITY = 'L10C_SPREAD_MISSING_IDENTITY',
  SPREAD_MISSING_CONTRACT_VERSION = 'L10C_SPREAD_MISSING_CONTRACT_VERSION',
  SPREAD_MISSING_RANKING_REF = 'L10C_SPREAD_MISSING_RANKING_REF',
  SPREAD_MISSING_PRIMARY = 'L10C_SPREAD_MISSING_PRIMARY',
  SPREAD_MISSING_SECONDARY_WHEN_COMPETITION = 'L10C_SPREAD_MISSING_SECONDARY_WHEN_COMPETITION',
  SPREAD_MISSING_MAGNITUDE = 'L10C_SPREAD_MISSING_MAGNITUDE',
  SPREAD_MAGNITUDE_OUT_OF_RANGE = 'L10C_SPREAD_MAGNITUDE_OOR',
  SPREAD_MISSING_CLASS = 'L10C_SPREAD_MISSING_CLASS',
  SPREAD_CLASS_INCONSISTENT = 'L10C_SPREAD_CLASS_INCONSISTENT',
  SPREAD_NARROW_FLAG_HIDDEN = 'L10C_SPREAD_NARROW_FLAG_HIDDEN',
  SPREAD_MISSING_STABILITY_CLASS = 'L10C_SPREAD_MISSING_STABILITY_CLASS',
  SPREAD_MISSING_LINEAGE = 'L10C_SPREAD_MISSING_LINEAGE',
  SPREAD_MISSING_REPLAY_HASH = 'L10C_SPREAD_MISSING_REPLAY_HASH',

  // ── Shift-condition contract (§10.3.7.2) ──
  SHIFT_MISSING_IDENTITY = 'L10C_SHIFT_MISSING_IDENTITY',
  SHIFT_MISSING_CONTRACT_VERSION = 'L10C_SHIFT_MISSING_CONTRACT_VERSION',
  SHIFT_MISSING_RANKING_REF = 'L10C_SHIFT_MISSING_RANKING_REF',
  SHIFT_MISSING_PRIMARY = 'L10C_SHIFT_MISSING_PRIMARY',
  SHIFT_MISSING_SECONDARY_WHEN_COMPETITION = 'L10C_SHIFT_MISSING_SECONDARY_WHEN_COMPETITION',
  SHIFT_MISSING_PROMOTION_CONDITIONS = 'L10C_SHIFT_MISSING_PROMOTION_CONDITIONS',
  SHIFT_MISSING_REINFORCEMENT_CONDITIONS = 'L10C_SHIFT_MISSING_REINFORCEMENT_CONDITIONS',
  SHIFT_MISSING_COLLAPSE_CONDITIONS = 'L10C_SHIFT_MISSING_COLLAPSE_CONDITIONS',
  SHIFT_MISSING_LINEAGE = 'L10C_SHIFT_MISSING_LINEAGE',
  SHIFT_MISSING_REPLAY_HASH = 'L10C_SHIFT_MISSING_REPLAY_HASH',

  // ── Restriction contract (§10.3.7.3) ──
  RESTRICTION_MISSING_IDENTITY = 'L10C_RESTRICTION_MISSING_IDENTITY',
  RESTRICTION_MISSING_CONTRACT_VERSION = 'L10C_RESTRICTION_MISSING_CONTRACT_VERSION',
  RESTRICTION_MISSING_BAND = 'L10C_RESTRICTION_MISSING_BAND',
  RESTRICTION_MISSING_ALLOWED_USES = 'L10C_RESTRICTION_MISSING_ALLOWED_USES',
  RESTRICTION_MISSING_BLOCKED_USES = 'L10C_RESTRICTION_MISSING_BLOCKED_USES',
  RESTRICTION_MISSING_MANDATORY_BLOCKED_USES = 'L10C_RESTRICTION_MISSING_MANDATORY_BLOCKED_USES',
  RESTRICTION_MISSING_NARROWING_REASONS = 'L10C_RESTRICTION_MISSING_NARROWING_REASONS',
  RESTRICTION_MISSING_LINEAGE = 'L10C_RESTRICTION_MISSING_LINEAGE',
  RESTRICTION_MISSING_REPLAY_HASH = 'L10C_RESTRICTION_MISSING_REPLAY_HASH',
  RESTRICTION_DECISIVE_WHILE_COMPETITION_LIVE = 'L10C_RESTRICTION_DECISIVE_WHILE_COMPETITION_LIVE',
  RESTRICTION_ALLOWED_AND_BLOCKED_OVERLAP = 'L10C_RESTRICTION_ALLOWED_AND_BLOCKED_OVERLAP',
  RESTRICTION_JUDGMENT_LEAK = 'L10C_RESTRICTION_JUDGMENT_LEAK',

  // ── Cleanliness / readiness (§10.3.5.5 / §10.3.9) ──
  CLEAN_WHILE_CONTRADICTION_MATERIAL = 'L10C_CLEAN_WHILE_CONTRADICTION_MATERIAL',
  CLEAN_WHILE_CONFIRMATION_GAP_MATERIAL = 'L10C_CLEAN_WHILE_CONFIRMATION_GAP_MATERIAL',
  CLEAN_WHILE_INVALIDATION_MATERIAL = 'L10C_CLEAN_WHILE_INVALIDATION_MATERIAL',
  CLEAN_WHILE_SPREAD_NARROW = 'L10C_CLEAN_WHILE_SPREAD_NARROW',
  CLEAN_WHILE_STALE = 'L10C_CLEAN_WHILE_STALE',
  CLEAN_WHILE_DEGRADED = 'L10C_CLEAN_WHILE_DEGRADED',
  REGIME_POSTURE_REQUIRED = 'L10C_REGIME_POSTURE_REQUIRED',
  SEQUENCE_POSTURE_REQUIRED = 'L10C_SEQUENCE_POSTURE_REQUIRED',
  VALIDATION_POSTURE_REQUIRED = 'L10C_VALIDATION_POSTURE_REQUIRED',
  RESTRICTION_POSTURE_REQUIRED = 'L10C_RESTRICTION_POSTURE_REQUIRED',
  CAUSAL_RESTRAINT_POSTURE_REQUIRED = 'L10C_CAUSAL_RESTRAINT_POSTURE_REQUIRED',
  SHIFT_CONDITIONS_REQUIRED_WHEN_CLOSE = 'L10C_SHIFT_CONDITIONS_REQUIRED_WHEN_CLOSE',

  // ── Compatibility (§10.3.8) ──
  COMPATIBILITY_PROHIBITED = 'L10C_COMPATIBILITY_PROHIBITED',
  COMPATIBILITY_BREAKING_SEMANTIC_UNAPPROVED = 'L10C_COMPATIBILITY_BREAKING_UNAPPROVED',
  COMPATIBILITY_NON_MONOTONIC_VERSION = 'L10C_COMPATIBILITY_NON_MONOTONIC',
  COMPATIBILITY_REQUIRED_FIELD_REMOVED = 'L10C_COMPATIBILITY_REQUIRED_FIELD_REMOVED',
  COMPATIBILITY_CLASSIFICATION_MISMATCH = 'L10C_COMPATIBILITY_CLASSIFICATION_MISMATCH',
}

export const ALL_L10_HYPOTHESIS_CONTRACT_VIOLATION_CODES:
  readonly L10HypothesisContractViolationCode[] =
    Object.values(L10HypothesisContractViolationCode);

export interface L10ContractIssue {
  readonly code: L10HypothesisContractViolationCode;
  readonly message: string;
  readonly details?: Record<string, unknown>;
}

export interface L10ContractReport {
  readonly valid: boolean;
  readonly issues: readonly L10ContractIssue[];
}
