/**
 * L10.5 — Evidence-Semantics Violation Codes
 *
 * §10.5.9.2 — Typed violation codes for every L10.5 semantic law:
 * support, contradiction, confirmation, invalidation, shift-condition,
 * evidence posture, and evidence-role interaction.
 *
 * Disjoint from:
 *   L10_*   constitutional (§10.1)
 *   L10O_*  object-model   (§10.2)
 *   L10C_*  universal contracts (§10.3)
 *   L10R_*  runtime (§10.4)
 *
 * L10.5 uses the `L10E_` prefix so audit records remain unambiguous
 * about which semantic tier rejected an artifact.
 */

export enum L10EvidenceSemanticViolationCode {
  // ── Support doctrine (§10.5.2) ──
  SUPPORT_MISSING_ROLE = 'L10E_SUPPORT_MISSING_ROLE',
  SUPPORT_ROLE_UNREGISTERED = 'L10E_SUPPORT_ROLE_UNREGISTERED',
  SUPPORT_ROLE_DISALLOWED = 'L10E_SUPPORT_ROLE_DISALLOWED',
  SUPPORT_PRIMARY_FROM_EVIDENCE_ONLY =
    'L10E_SUPPORT_PRIMARY_FROM_EVIDENCE_ONLY',
  SUPPORT_PRIMARY_FROM_DEGRADED =
    'L10E_SUPPORT_PRIMARY_FROM_DEGRADED',
  SUPPORT_CLAIM_WITHOUT_REF = 'L10E_SUPPORT_CLAIM_WITHOUT_REF',
  SUPPORT_STRENGTH_WITHOUT_ROLE = 'L10E_SUPPORT_STRENGTH_WITHOUT_ROLE',
  SUPPORT_STRENGTH_OUT_OF_RANGE = 'L10E_SUPPORT_STRENGTH_OUT_OF_RANGE',
  SUPPORT_DERIVABILITY_FACET_MISSING =
    'L10E_SUPPORT_DERIVABILITY_FACET_MISSING',
  SUPPORT_TEMPLATE_DOMAIN_MISSING =
    'L10E_SUPPORT_TEMPLATE_DOMAIN_MISSING',
  SUPPORT_STALE_PRESENTED_AS_CLEAN =
    'L10E_SUPPORT_STALE_PRESENTED_AS_CLEAN',
  SUPPORT_DEGRADED_PRESENTED_AS_CLEAN =
    'L10E_SUPPORT_DEGRADED_PRESENTED_AS_CLEAN',
  SUPPORT_MISSING_EXPECTED_HIDDEN =
    'L10E_SUPPORT_MISSING_EXPECTED_HIDDEN',
  SUPPORT_LINEAGE_DOMAIN_FOREIGN =
    'L10E_SUPPORT_LINEAGE_DOMAIN_FOREIGN',

  // ── Contradiction doctrine (§10.5.3) ──
  CONTRADICTION_CLASS_UNREGISTERED =
    'L10E_CONTRADICTION_CLASS_UNREGISTERED',
  CONTRADICTION_CLASS_DISALLOWED =
    'L10E_CONTRADICTION_CLASS_DISALLOWED',
  CONTRADICTION_EFFECT_MISSING = 'L10E_CONTRADICTION_EFFECT_MISSING',
  CONTRADICTION_EFFECT_DISALLOWED =
    'L10E_CONTRADICTION_EFFECT_DISALLOWED',
  CONTRADICTION_BLOCKING_MISLABELED_AS_NARROWING =
    'L10E_CONTRADICTION_BLOCKING_MISLABELED_AS_NARROWING',
  CONTRADICTION_ACTIVE_MISLABELED_AS_DECAYED =
    'L10E_CONTRADICTION_ACTIVE_MISLABELED_AS_DECAYED',
  CONTRADICTION_TEMPORAL_POSTURE_MISSING =
    'L10E_CONTRADICTION_TEMPORAL_POSTURE_MISSING',
  CONTRADICTION_DIRECTNESS_MISSING =
    'L10E_CONTRADICTION_DIRECTNESS_MISSING',
  CONTRADICTION_DERIVABILITY_FACET_MISSING =
    'L10E_CONTRADICTION_DERIVABILITY_FACET_MISSING',
  CONTRADICTION_DOMAIN_OMITTED =
    'L10E_CONTRADICTION_DOMAIN_OMITTED',
  CONTRADICTION_NETTED_INTO_CONFIDENCE =
    'L10E_CONTRADICTION_NETTED_INTO_CONFIDENCE',
  CONTRADICTION_PRESSURE_OUT_OF_RANGE =
    'L10E_CONTRADICTION_PRESSURE_OUT_OF_RANGE',

  // ── Confirmation doctrine (§10.5.4) ──
  CONFIRMATION_CLASS_UNREGISTERED =
    'L10E_CONFIRMATION_CLASS_UNREGISTERED',
  CONFIRMATION_CLASS_DISALLOWED =
    'L10E_CONFIRMATION_CLASS_DISALLOWED',
  CONFIRMATION_PRESENCE_MISSING =
    'L10E_CONFIRMATION_PRESENCE_MISSING',
  CONFIRMATION_REQUIRED_AND_PRESENT_COLLAPSED =
    'L10E_CONFIRMATION_REQUIRED_AND_PRESENT_COLLAPSED',
  CONFIRMATION_MISSING_HIDDEN = 'L10E_CONFIRMATION_MISSING_HIDDEN',
  CONFIRMATION_UPGRADE_CRITICAL_OMITTED =
    'L10E_CONFIRMATION_UPGRADE_CRITICAL_OMITTED',
  CONFIRMATION_TEMPLATE_DOMAIN_MISSING =
    'L10E_CONFIRMATION_TEMPLATE_DOMAIN_MISSING',
  CONFIRMATION_PRIMARY_WITH_MISSING_UPGRADES =
    'L10E_CONFIRMATION_PRIMARY_WITH_MISSING_UPGRADES',
  CONFIRMATION_DEGRADED_TREATED_AS_FULL =
    'L10E_CONFIRMATION_DEGRADED_TREATED_AS_FULL',

  // ── Invalidation doctrine (§10.5.5) ──
  INVALIDATION_CLASS_UNREGISTERED =
    'L10E_INVALIDATION_CLASS_UNREGISTERED',
  INVALIDATION_CLASS_DISALLOWED =
    'L10E_INVALIDATION_CLASS_DISALLOWED',
  INVALIDATION_RISK_CLAIMED_WITHOUT_SIGNALS =
    'L10E_INVALIDATION_RISK_CLAIMED_WITHOUT_SIGNALS',
  INVALIDATION_ACTIVE_HIDDEN_IN_POTENTIAL =
    'L10E_INVALIDATION_ACTIVE_HIDDEN_IN_POTENTIAL',
  INVALIDATION_COLLAPSE_THRESHOLD_MISSING =
    'L10E_INVALIDATION_COLLAPSE_THRESHOLD_MISSING',
  INVALIDATION_THRESHOLD_BASIS_MISSING =
    'L10E_INVALIDATION_THRESHOLD_BASIS_MISSING',
  INVALIDATION_THRESHOLD_OUT_OF_RANGE =
    'L10E_INVALIDATION_THRESHOLD_OUT_OF_RANGE',
  INVALIDATION_ACTIVE_NOT_CAPPING_CONFIDENCE =
    'L10E_INVALIDATION_ACTIVE_NOT_CAPPING_CONFIDENCE',
  INVALIDATION_PRIMARY_STABLE_UNDER_ACTIVE =
    'L10E_INVALIDATION_PRIMARY_STABLE_UNDER_ACTIVE',
  INVALIDATION_ACTIVE_VS_POTENTIAL_NOT_SPLIT =
    'L10E_INVALIDATION_ACTIVE_VS_POTENTIAL_NOT_SPLIT',

  // ── Shift-condition doctrine (§10.5.6) ──
  SHIFT_CONDITION_CLASS_UNREGISTERED =
    'L10E_SHIFT_CONDITION_CLASS_UNREGISTERED',
  SHIFT_CONDITION_CLASS_DISALLOWED =
    'L10E_SHIFT_CONDITION_CLASS_DISALLOWED',
  SHIFT_CONDITION_MISSING_ANCHOR = 'L10E_SHIFT_CONDITION_MISSING_ANCHOR',
  SHIFT_CONDITION_MISSING_DRIVER = 'L10E_SHIFT_CONDITION_MISSING_DRIVER',
  SHIFT_CONDITION_DRIVER_UNREGISTERED =
    'L10E_SHIFT_CONDITION_DRIVER_UNREGISTERED',
  SHIFT_CONDITION_PROMOTION_DETACHED =
    'L10E_SHIFT_CONDITION_PROMOTION_DETACHED',
  SHIFT_CONDITION_COLLAPSE_ABSENT_WITH_ACTIVE_INVALIDATION =
    'L10E_SHIFT_CONDITION_COLLAPSE_ABSENT_WITH_ACTIVE_INVALIDATION',
  SHIFT_CONDITION_STATIC_RANKING_WITH_LIVE_COMPETITION =
    'L10E_SHIFT_CONDITION_STATIC_RANKING_WITH_LIVE_COMPETITION',
  SHIFT_CONDITION_SPREAD_NARROWING_MISSING =
    'L10E_SHIFT_CONDITION_SPREAD_NARROWING_MISSING',
  SHIFT_CONDITION_BELOW_MIN_WHEN_LIVE =
    'L10E_SHIFT_CONDITION_BELOW_MIN_WHEN_LIVE',
  SHIFT_CONDITION_MANDATORY_CLASS_MISSING =
    'L10E_SHIFT_CONDITION_MANDATORY_CLASS_MISSING',
  SHIFT_CONDITION_EVIDENCE_DOMAIN_MISSING =
    'L10E_SHIFT_CONDITION_EVIDENCE_DOMAIN_MISSING',

  // ── Evidence posture (§10.5.8) ──
  POSTURE_MISSING_WHEN_MATERIAL = 'L10E_POSTURE_MISSING_WHEN_MATERIAL',
  POSTURE_EVIDENCE_ONLY_ANCHORING_PRIMARY =
    'L10E_POSTURE_EVIDENCE_ONLY_ANCHORING_PRIMARY',
  POSTURE_STALE_TREATED_AS_CURRENT =
    'L10E_POSTURE_STALE_TREATED_AS_CURRENT',
  POSTURE_DECAYED_TREATED_AS_ACTIVE =
    'L10E_POSTURE_DECAYED_TREATED_AS_ACTIVE',
  POSTURE_DEGRADED_TREATED_AS_FULL =
    'L10E_POSTURE_DEGRADED_TREATED_AS_FULL',

  // ── Interaction law (§10.5.7) ──
  INTERACTION_NETTED_SUPPORT_MINUS_CONTRADICTION =
    'L10E_INTERACTION_NETTED_SUPPORT_MINUS_CONTRADICTION',
  INTERACTION_SEMANTIC_ORDER_VIOLATED =
    'L10E_INTERACTION_SEMANTIC_ORDER_VIOLATED',
  INTERACTION_FRAGILE_CANDIDATE_MARKED_STABLE =
    'L10E_INTERACTION_FRAGILE_CANDIDATE_MARKED_STABLE',
  INTERACTION_FLATTENED_INTO_SINGLE_STORY =
    'L10E_INTERACTION_FLATTENED_INTO_SINGLE_STORY',
  INTERACTION_CONFIDENCE_UNCAPPED_UNDER_ACTIVE_INVALIDATION =
    'L10E_INTERACTION_CONFIDENCE_UNCAPPED_UNDER_ACTIVE_INVALIDATION',
  INTERACTION_SPREAD_NARROW_WITHOUT_SHIFT_CONDITIONS =
    'L10E_INTERACTION_SPREAD_NARROW_WITHOUT_SHIFT_CONDITIONS',
  INTERACTION_MISSING_CONFIRMATION_NOT_FRAGILE =
    'L10E_INTERACTION_MISSING_CONFIRMATION_NOT_FRAGILE',
}

/**
 * Stable issue shape (parallel to the L10.2/L10.3/L10.4 reports) so
 * validators and audits can be composed uniformly.
 */
export interface L10EvidenceSemanticValidationIssue {
  readonly code: L10EvidenceSemanticViolationCode;
  readonly message: string;
  readonly subject?: string;
}

export interface L10EvidenceSemanticValidationReport {
  readonly valid: boolean;
  readonly issues: readonly L10EvidenceSemanticValidationIssue[];
}
