/**
 * L12.1 — Constitutional Violation Codes
 *
 * §12.1.13 / §12.1.14 — Every constitutional boundary failure carries
 * a typed code in the disjoint `L12C_` namespace so audit records and
 * validator decisions remain deterministic and disjoint from L11.
 */

export enum L12ConstitutionalViolationCode {
  // Mission and registration
  L12C_MISSION_MISMATCH = 'L12C_MISSION_MISMATCH',
  L12C_OUTPUT_SURFACE_UNREGISTERED = 'L12C_OUTPUT_SURFACE_UNREGISTERED',
  L12C_DEPENDENCY_SURFACE_UNREGISTERED = 'L12C_DEPENDENCY_SURFACE_UNREGISTERED',
  L12C_ILLEGAL_DEPENDENCY_USAGE = 'L12C_ILLEGAL_DEPENDENCY_USAGE',
  L12C_ILLEGAL_OUTPUT_CLASS = 'L12C_ILLEGAL_OUTPUT_CLASS',
  L12C_ILLEGAL_CAPABILITY_CLAIM = 'L12C_ILLEGAL_CAPABILITY_CLAIM',
  L12C_FORBIDDEN_NAMING = 'L12C_FORBIDDEN_NAMING',

  // Prediction theater / certainty / leakage
  L12C_PREDICTION_THEATER = 'L12C_PREDICTION_THEATER',
  L12C_CERTAINTY_CLAIM = 'L12C_CERTAINTY_CLAIM',
  L12C_RECOMMENDATION_LEAK = 'L12C_RECOMMENDATION_LEAK',
  L12C_JUDGMENT_LEAK = 'L12C_JUDGMENT_LEAK',
  L12C_TRADE_ACTION_LEAK = 'L12C_TRADE_ACTION_LEAK',
  L12C_SCENARIO_AS_GUARANTEE = 'L12C_SCENARIO_AS_GUARANTEE',
  L12C_SINGLE_PATH_FAKE_CERTAINTY = 'L12C_SINGLE_PATH_FAKE_CERTAINTY',

  // Conditionality / structure
  L12C_INVALIDATION_OMITTED = 'L12C_INVALIDATION_OMITTED',
  L12C_TRIGGER_OMITTED = 'L12C_TRIGGER_OMITTED',
  L12C_CONDITION_OMITTED = 'L12C_CONDITION_OMITTED',
  L12C_PATH_CONFIDENCE_LAUNDERING = 'L12C_PATH_CONFIDENCE_LAUNDERING',
  L12C_SCENARIO_SPREAD_HIDDEN = 'L12C_SCENARIO_SPREAD_HIDDEN',

  // Lower-layer rebuild / redefinition
  L12C_LOWER_LAYER_REDEFINITION = 'L12C_LOWER_LAYER_REDEFINITION',
  L12C_VALIDATION_REBUILD = 'L12C_VALIDATION_REBUILD',
  L12C_REGIME_REBUILD = 'L12C_REGIME_REBUILD',
  L12C_SEQUENCE_REBUILD = 'L12C_SEQUENCE_REBUILD',
  L12C_HYPOTHESIS_REBUILD = 'L12C_HYPOTHESIS_REBUILD',
  L12C_SCORE_REBUILD = 'L12C_SCORE_REBUILD',

  // L11 score-context law
  L12C_L11_SCORE_VALUE_ONLY = 'L12C_L11_SCORE_VALUE_ONLY',
  L12C_SCORE_CONTEXT_INCOMPLETE = 'L12C_SCORE_CONTEXT_INCOMPLETE',
  L12C_DRIFT_STATUS_HIDDEN = 'L12C_DRIFT_STATUS_HIDDEN',
  L12C_MISSING_VISIBILITY_HIDDEN = 'L12C_MISSING_VISIBILITY_HIDDEN',

  // Restriction / posture
  L12C_RESTRICTION_BYPASS = 'L12C_RESTRICTION_BYPASS',
  L12C_CONTRADICTION_DOWNGRADED = 'L12C_CONTRADICTION_DOWNGRADED',
  L12C_REGIME_POSTURE_IGNORED = 'L12C_REGIME_POSTURE_IGNORED',
  L12C_SEQUENCE_POSTURE_IGNORED = 'L12C_SEQUENCE_POSTURE_IGNORED',
  L12C_HYPOTHESIS_POSTURE_IGNORED = 'L12C_HYPOTHESIS_POSTURE_IGNORED',
  L12C_ACTIVE_INVALIDATION_HIDDEN = 'L12C_ACTIVE_INVALIDATION_HIDDEN',

  // Persistence and consumption
  L12C_L5_BYPASS = 'L12C_L5_BYPASS',
  L12C_RAW_STORAGE_BYPASS = 'L12C_RAW_STORAGE_BYPASS',
  L12C_LATE_LAYER_CONSUMPTION = 'L12C_LATE_LAYER_CONSUMPTION',
  L12C_REPLAY_HASH_MISSING = 'L12C_REPLAY_HASH_MISSING',
  L12C_LINEAGE_MISSING = 'L12C_LINEAGE_MISSING',
}

export const ALL_L12_VIOLATION_CODES:
  readonly L12ConstitutionalViolationCode[] =
  Object.values(L12ConstitutionalViolationCode);

export class L12ConstitutionalError extends Error {
  public readonly code: L12ConstitutionalViolationCode;
  public readonly details: Record<string, unknown>;

  constructor(
    code: L12ConstitutionalViolationCode,
    message: string,
    details: Record<string, unknown> = {},
  ) {
    super(`[${code}] ${message}`);
    this.name = 'L12ConstitutionalError';
    this.code = code;
    this.details = details;
  }
}
