/**
 * L12.1 — Constitutional Types
 *
 * §12.1.0 — Core enums for the entire Layer 12 constitution. Layer 12
 * is the Scenario Engine — the first layer that converts governed
 * lower-layer truth (L3–L11) into conditional future paths. L12.1
 * freezes the boundary before any scenario logic exists.
 *
 * §12.1.1 / §12.1.2 / §12.1.4 / §12.1.5 — Layer 12 may consume only
 * frozen handoff/read surfaces from L3–L11, may emit only conditional
 * paths with explicit triggers and invalidations, and may never act as
 * a prediction, recommendation, judgment, or trade-action layer.
 */

/**
 * §12.1.0 — Layer 12 sublayer identities, as anticipated by L12.1
 * during the constitutional bring-up. The canonical, frozen sublayer
 * enumeration after L12.7 closure is `L12SublayerId` from
 * `l12-final-definition.ts` (7 sublayers). This enum is preserved
 * here for L12.1 internal references only and must not be re-exported
 * outside L12.1's audit / boundary surfaces.
 */
export enum L12ConstitutionalSublayerId {
  L12_1_CONSTITUTION = 'L12_1_CONSTITUTION',
  L12_2_SCENARIO_DOCTRINE = 'L12_2_SCENARIO_DOCTRINE',
  L12_3_SCENARIO_TEMPLATES = 'L12_3_SCENARIO_TEMPLATES',
  L12_4_TRIGGER_INVALIDATION = 'L12_4_TRIGGER_INVALIDATION',
  L12_5_PATH_CONFIDENCE = 'L12_5_PATH_CONFIDENCE',
  L12_6_SHIFT_AND_RESTRICTION = 'L12_6_SHIFT_AND_RESTRICTION',
  L12_7_PERSISTENCE = 'L12_7_PERSISTENCE',
  L12_8_REPLAY_REPAIR = 'L12_8_REPLAY_REPAIR',
  L12_9_RATIFICATION = 'L12_9_RATIFICATION',
}

export const ALL_L12_CONSTITUTIONAL_SUBLAYER_IDS:
  readonly L12ConstitutionalSublayerId[] =
  Object.values(L12ConstitutionalSublayerId);

/**
 * §12.1.0 — Subjects that L12 reasons about.
 */
export enum L12SubjectClass {
  SCENARIO_SUBJECT = 'SCENARIO_SUBJECT',
  SCENARIO_SET_SUBJECT = 'SCENARIO_SET_SUBJECT',
  CONDITIONAL_PATH_SUBJECT = 'CONDITIONAL_PATH_SUBJECT',
  TRIGGER_SUBJECT = 'TRIGGER_SUBJECT',
  INVALIDATION_SUBJECT = 'INVALIDATION_SUBJECT',
  PATH_CONFIDENCE_SUBJECT = 'PATH_CONFIDENCE_SUBJECT',
  SHIFT_CONDITION_SUBJECT = 'SHIFT_CONDITION_SUBJECT',
  SCENARIO_RESTRICTION_SUBJECT = 'SCENARIO_RESTRICTION_SUBJECT',
  SCENARIO_EVIDENCE_SUBJECT = 'SCENARIO_EVIDENCE_SUBJECT',
}

export const ALL_L12_SUBJECT_CLASSES: readonly L12SubjectClass[] =
  Object.values(L12SubjectClass);

/**
 * §12.1.6 — Allowed Layer 12 capabilities. Allowed only inside the
 * legal capability contexts defined below.
 */
export enum L12AllowedCapability {
  INGEST_GOVERNED_LOWER_LAYER_SURFACES = 'INGEST_GOVERNED_LOWER_LAYER_SURFACES',
  ASSEMBLE_SCENARIO_SUBJECT = 'ASSEMBLE_SCENARIO_SUBJECT',
  RESOLVE_SCENARIO_INPUTS = 'RESOLVE_SCENARIO_INPUTS',
  GENERATE_SCENARIO_CANDIDATES = 'GENERATE_SCENARIO_CANDIDATES',
  RESOLVE_SCENARIO_CONDITIONS = 'RESOLVE_SCENARIO_CONDITIONS',
  RESOLVE_SCENARIO_TRIGGERS = 'RESOLVE_SCENARIO_TRIGGERS',
  RESOLVE_SCENARIO_INVALIDATIONS = 'RESOLVE_SCENARIO_INVALIDATIONS',
  CONSTRUCT_CONDITIONAL_PATHS = 'CONSTRUCT_CONDITIONAL_PATHS',
  COMPUTE_PATH_CONFIDENCE = 'COMPUTE_PATH_CONFIDENCE',
  RANK_SCENARIO_PATHS = 'RANK_SCENARIO_PATHS',
  DERIVE_SHIFT_CONDITIONS = 'DERIVE_SHIFT_CONDITIONS',
  DERIVE_SCENARIO_RESTRICTIONS = 'DERIVE_SCENARIO_RESTRICTIONS',
  BUILD_SCENARIO_EVIDENCE_PACK = 'BUILD_SCENARIO_EVIDENCE_PACK',
  MATERIALIZE_THROUGH_L5 = 'MATERIALIZE_THROUGH_L5',
  SUPPORT_REPLAY = 'SUPPORT_REPLAY',
  SUPPORT_REPAIR = 'SUPPORT_REPAIR',
  EXPOSE_GOVERNED_READ_SURFACES = 'EXPOSE_GOVERNED_READ_SURFACES',
}

export const ALL_L12_ALLOWED_CAPABILITIES: readonly L12AllowedCapability[] =
  Object.values(L12AllowedCapability);

/**
 * §12.1.6 — Capability groups for the Scenario Engine.
 */
export enum L12CapabilityGroup {
  A_INPUT_INGESTION = 'A_INPUT_INGESTION',
  B_SCENARIO_ASSEMBLY = 'B_SCENARIO_ASSEMBLY',
  C_PATH_CONSTRUCTION = 'C_PATH_CONSTRUCTION',
  D_PATH_CONFIDENCE_AND_RANKING = 'D_PATH_CONFIDENCE_AND_RANKING',
  E_RESTRICTION_AND_EVIDENCE = 'E_RESTRICTION_AND_EVIDENCE',
  F_DURABILITY_AND_SERVING = 'F_DURABILITY_AND_SERVING',
}

export const ALL_L12_CAPABILITY_GROUPS: readonly L12CapabilityGroup[] =
  Object.values(L12CapabilityGroup);

/**
 * §12.1.11 — Capability contexts. Each capability is allowed only in
 * specific contexts; outside them the policy map returns DENIED.
 */
export enum L12CapabilityContext {
  CONTRACT_DEFINITION = 'CONTRACT_DEFINITION',
  RUNTIME_EXECUTION = 'RUNTIME_EXECUTION',
  INPUT_RESOLUTION = 'INPUT_RESOLUTION',
  SCENARIO_GENERATION = 'SCENARIO_GENERATION',
  CONDITION_RESOLUTION = 'CONDITION_RESOLUTION',
  TRIGGER_RESOLUTION = 'TRIGGER_RESOLUTION',
  INVALIDATION_RESOLUTION = 'INVALIDATION_RESOLUTION',
  PATH_CONFIDENCE = 'PATH_CONFIDENCE',
  SHIFT_CONDITION_DERIVATION = 'SHIFT_CONDITION_DERIVATION',
  OUTPUT_EMISSION = 'OUTPUT_EMISSION',
  MATERIALIZATION = 'MATERIALIZATION',
  REPLAY = 'REPLAY',
  REPAIR = 'REPAIR',
  READ_SERVING = 'READ_SERVING',
}

export const ALL_L12_CAPABILITY_CONTEXTS: readonly L12CapabilityContext[] =
  Object.values(L12CapabilityContext);

/**
 * §12.1.11 — Decision return type for the capability policy.
 */
export enum L12CapabilityDecision {
  ALLOWED = 'ALLOWED',
  CONDITIONALLY_ALLOWED = 'CONDITIONALLY_ALLOWED',
  DENIED = 'DENIED',
}

/**
 * §12.1.7 — Forbidden actions at Layer 12. Each is rejected by the
 * forbidden-action registry and boundary validators.
 */
export enum L12ForbiddenAction {
  PREDICTION_THEATER = 'PREDICTION_THEATER',
  CERTAINTY_CLAIM = 'CERTAINTY_CLAIM',
  FINAL_JUDGMENT_EMISSION = 'FINAL_JUDGMENT_EMISSION',
  RECOMMENDATION_EMISSION = 'RECOMMENDATION_EMISSION',
  TRADE_ACTION_EMISSION = 'TRADE_ACTION_EMISSION',
  SCENARIO_AS_GUARANTEE = 'SCENARIO_AS_GUARANTEE',
  SINGLE_PATH_FAKE_CERTAINTY = 'SINGLE_PATH_FAKE_CERTAINTY',
  INVALIDATION_OMISSION = 'INVALIDATION_OMISSION',
  TRIGGER_OMISSION = 'TRIGGER_OMISSION',
  CONDITION_OMISSION = 'CONDITION_OMISSION',
  LOWER_LAYER_TRUTH_REDEFINITION = 'LOWER_LAYER_TRUTH_REDEFINITION',
  VALIDATION_REBUILD = 'VALIDATION_REBUILD',
  REGIME_REBUILD = 'REGIME_REBUILD',
  SEQUENCE_REBUILD = 'SEQUENCE_REBUILD',
  HYPOTHESIS_REBUILD = 'HYPOTHESIS_REBUILD',
  SCORE_REBUILD = 'SCORE_REBUILD',
  L11_SCORE_VALUE_ONLY_CONSUMPTION = 'L11_SCORE_VALUE_ONLY_CONSUMPTION',
  L7_RESTRICTION_BYPASS = 'L7_RESTRICTION_BYPASS',
  L8_REGIME_POSTURE_IGNORE = 'L8_REGIME_POSTURE_IGNORE',
  L9_SEQUENCE_POSTURE_IGNORE = 'L9_SEQUENCE_POSTURE_IGNORE',
  L10_HYPOTHESIS_POSTURE_IGNORE = 'L10_HYPOTHESIS_POSTURE_IGNORE',
  L11_SCORE_RESTRICTION_IGNORE = 'L11_SCORE_RESTRICTION_IGNORE',
  CONTRADICTION_DOWNGRADE = 'CONTRADICTION_DOWNGRADE',
  ACTIVE_INVALIDATION_HIDE = 'ACTIVE_INVALIDATION_HIDE',
  MISSING_VISIBILITY_HIDE = 'MISSING_VISIBILITY_HIDE',
  DRIFT_STATUS_HIDE = 'DRIFT_STATUS_HIDE',
  PATH_CONFIDENCE_LAUNDERING = 'PATH_CONFIDENCE_LAUNDERING',
  SCENARIO_SPREAD_HIDE = 'SCENARIO_SPREAD_HIDE',
  RAW_STORAGE_BYPASS = 'RAW_STORAGE_BYPASS',
  L5_PERSISTENCE_BYPASS = 'L5_PERSISTENCE_BYPASS',
  L13_PLUS_CONSUMPTION = 'L13_PLUS_CONSUMPTION',
}

export const ALL_L12_FORBIDDEN_ACTIONS: readonly L12ForbiddenAction[] =
  Object.values(L12ForbiddenAction);

/**
 * §12.1.5 — Hard dependency law. Layer 12 depends on L3–L11 only.
 */
export enum L12DependencyLayer {
  L3 = 'L3',
  L4 = 'L4',
  L5 = 'L5',
  L6 = 'L6',
  L7 = 'L7',
  L8 = 'L8',
  L9 = 'L9',
  L10 = 'L10',
  L11 = 'L11',
}

export const ALL_L12_DEPENDENCY_LAYERS: readonly L12DependencyLayer[] =
  Object.values(L12DependencyLayer);

/**
 * §12.1.5 / §12.1.9 — Dependency surface classes. Stable-handoff from
 * each frozen lower layer.
 */
export enum L12DependencySurfaceClass {
  // L3
  L3_CANONICAL_ENTITY_IDENTITY = 'L3_CANONICAL_ENTITY_IDENTITY',
  L3_SCOPE_CONTRACT = 'L3_SCOPE_CONTRACT',
  L3_METRIC_CONTRACT = 'L3_METRIC_CONTRACT',
  L3_VERSION_CONTRACT = 'L3_VERSION_CONTRACT',
  L3_MUTATION_CONTRACT = 'L3_MUTATION_CONTRACT',
  L3_CONFIDENCE_RIGHTS_CONTRACT = 'L3_CONFIDENCE_RIGHTS_CONTRACT',
  // L4
  L4_GRAPH_CONTEXT_PACKAGE = 'L4_GRAPH_CONTEXT_PACKAGE',
  L4_RELATION_EVIDENCE = 'L4_RELATION_EVIDENCE',
  L4_PROPAGATION_OUTPUT = 'L4_PROPAGATION_OUTPUT',
  L4_ECOSYSTEM_CONTEXT = 'L4_ECOSYSTEM_CONTEXT',
  L4_SECTOR_CONTEXT = 'L4_SECTOR_CONTEXT',
  L4_TEMPORAL_GRAPH_STATE = 'L4_TEMPORAL_GRAPH_STATE',
  // L5
  L5_CURRENT_STATE_READ = 'L5_CURRENT_STATE_READ',
  L5_HISTORICAL_STATE_READ = 'L5_HISTORICAL_STATE_READ',
  L5_EVIDENCE_READ = 'L5_EVIDENCE_READ',
  L5_LINEAGE_READ = 'L5_LINEAGE_READ',
  L5_REPLAY_CONTEXT = 'L5_REPLAY_CONTEXT',
  L5_REPAIR_CONTEXT = 'L5_REPAIR_CONTEXT',
  L5_MATERIALIZATION_ROUTE = 'L5_MATERIALIZATION_ROUTE',
  // L6 — only allowed via governed handoff
  L6_FEATURE_STATE_READ_SURFACE = 'L6_FEATURE_STATE_READ_SURFACE',
  L6_FEATURE_HISTORY_READ_SURFACE = 'L6_FEATURE_HISTORY_READ_SURFACE',
  L6_EVENT_STATE_READ_SURFACE = 'L6_EVENT_STATE_READ_SURFACE',
  L6_EVENT_HISTORY_READ_SURFACE = 'L6_EVENT_HISTORY_READ_SURFACE',
  L6_PRIMITIVE_EVIDENCE_PACK = 'L6_PRIMITIVE_EVIDENCE_PACK',
  L6_FRESHNESS_PROFILE = 'L6_FRESHNESS_PROFILE',
  L6_QUALITY_PROFILE = 'L6_QUALITY_PROFILE',
  // L7 — stable handoff only
  L7_VALIDATION_ASSESSMENT = 'L7_VALIDATION_ASSESSMENT',
  L7_CONTRADICTION_BUNDLE = 'L7_CONTRADICTION_BUNDLE',
  L7_CONFIDENCE_ASSESSMENT = 'L7_CONFIDENCE_ASSESSMENT',
  L7_RESTRICTION_PROFILE = 'L7_RESTRICTION_PROFILE',
  L7_VALIDATION_EVIDENCE_READ_SURFACE = 'L7_VALIDATION_EVIDENCE_READ_SURFACE',
  L7_HISTORICAL_VALIDATION_WINDOW = 'L7_HISTORICAL_VALIDATION_WINDOW',
  // L8 — stable handoff only
  L8_CURRENT_REGIME_STATE = 'L8_CURRENT_REGIME_STATE',
  L8_CURRENT_TRANSITION_PROFILE = 'L8_CURRENT_TRANSITION_PROFILE',
  L8_CURRENT_REGIME_CONFIDENCE = 'L8_CURRENT_REGIME_CONFIDENCE',
  L8_CURRENT_MULTIPLIER_PROFILE = 'L8_CURRENT_MULTIPLIER_PROFILE',
  L8_REGIME_HISTORY_WINDOW = 'L8_REGIME_HISTORY_WINDOW',
  L8_REGIME_EVIDENCE_BUNDLE = 'L8_REGIME_EVIDENCE_BUNDLE',
  L8_REGIME_LINEAGE = 'L8_REGIME_LINEAGE',
  // L9 — stable handoff only
  L9_CURRENT_SEQUENCE_STATE = 'L9_CURRENT_SEQUENCE_STATE',
  L9_CURRENT_PHASE_PROFILE = 'L9_CURRENT_PHASE_PROFILE',
  L9_CURRENT_DECAY_PROFILE = 'L9_CURRENT_DECAY_PROFILE',
  L9_LEAD_LAG_PROFILE = 'L9_LEAD_LAG_PROFILE',
  L9_POST_EVENT_WINDOW_PROFILE = 'L9_POST_EVENT_WINDOW_PROFILE',
  L9_SEQUENCE_CONFIDENCE_PROFILE = 'L9_SEQUENCE_CONFIDENCE_PROFILE',
  L9_SEQUENCE_RESTRICTION_PROFILE = 'L9_SEQUENCE_RESTRICTION_PROFILE',
  L9_SEQUENCE_EVIDENCE_BUNDLE = 'L9_SEQUENCE_EVIDENCE_BUNDLE',
  L9_SEQUENCE_HISTORY_WINDOW = 'L9_SEQUENCE_HISTORY_WINDOW',
  // L10 — stable handoff only
  L10_CURRENT_HYPOTHESIS_RANKING = 'L10_CURRENT_HYPOTHESIS_RANKING',
  L10_PRIMARY_HYPOTHESIS = 'L10_PRIMARY_HYPOTHESIS',
  L10_SECONDARY_HYPOTHESIS = 'L10_SECONDARY_HYPOTHESIS',
  L10_HYPOTHESIS_SPREAD_PROFILE = 'L10_HYPOTHESIS_SPREAD_PROFILE',
  L10_CONFIRMATION_POSTURE = 'L10_CONFIRMATION_POSTURE',
  L10_INVALIDATION_POSTURE = 'L10_INVALIDATION_POSTURE',
  L10_SHIFT_CONDITION_SET = 'L10_SHIFT_CONDITION_SET',
  L10_HYPOTHESIS_RESTRICTION_PROFILE = 'L10_HYPOTHESIS_RESTRICTION_PROFILE',
  L10_HYPOTHESIS_EVIDENCE_BUNDLE = 'L10_HYPOTHESIS_EVIDENCE_BUNDLE',
  // L11 — stable handoff only, score CONTEXT BUNDLE required
  L11_CURRENT_SCORE_SNAPSHOT = 'L11_CURRENT_SCORE_SNAPSHOT',
  L11_SCORE_COMPONENT_BREAKDOWN = 'L11_SCORE_COMPONENT_BREAKDOWN',
  L11_SCORE_ATTRIBUTION = 'L11_SCORE_ATTRIBUTION',
  L11_SCORE_MISSING_DATA_PROFILE = 'L11_SCORE_MISSING_DATA_PROFILE',
  L11_SCORE_MODIFIER_PROFILE = 'L11_SCORE_MODIFIER_PROFILE',
  L11_SCORE_CALIBRATION_HOOK = 'L11_SCORE_CALIBRATION_HOOK',
  L11_SCORE_DRIFT_REPORT = 'L11_SCORE_DRIFT_REPORT',
  L11_SCORE_RESTRICTION_PROFILE = 'L11_SCORE_RESTRICTION_PROFILE',
  L11_SCORE_EVIDENCE_BUNDLE = 'L11_SCORE_EVIDENCE_BUNDLE',
  L11_SCORE_LINEAGE = 'L11_SCORE_LINEAGE',
}

export const ALL_L12_DEPENDENCY_SURFACE_CLASSES:
  readonly L12DependencySurfaceClass[] =
  Object.values(L12DependencySurfaceClass);

/**
 * §12.1.8 — Legal Layer 12 output surface classes. Exactly eleven
 * conditional, evidence-bound, lineage-bound, replay-safe surfaces.
 */
export enum L12OutputSurfaceClass {
  SCENARIO_SET = 'SCENARIO_SET',
  BASE_CASE_SCENARIO = 'BASE_CASE_SCENARIO',
  BULLISH_CONTINUATION_SCENARIO = 'BULLISH_CONTINUATION_SCENARIO',
  BEARISH_FAILURE_SCENARIO = 'BEARISH_FAILURE_SCENARIO',
  TRIGGER_PROFILE = 'TRIGGER_PROFILE',
  INVALIDATION_PROFILE = 'INVALIDATION_PROFILE',
  PATH_CONFIDENCE_PROFILE = 'PATH_CONFIDENCE_PROFILE',
  SCENARIO_SHIFT_CONDITION_SET = 'SCENARIO_SHIFT_CONDITION_SET',
  SCENARIO_RESTRICTION_PROFILE = 'SCENARIO_RESTRICTION_PROFILE',
  SCENARIO_EVIDENCE_READ_SURFACE = 'SCENARIO_EVIDENCE_READ_SURFACE',
  SCENARIO_LINEAGE_READ_SURFACE = 'SCENARIO_LINEAGE_READ_SURFACE',
}

export const ALL_L12_OUTPUT_SURFACE_CLASSES:
  readonly L12OutputSurfaceClass[] =
  Object.values(L12OutputSurfaceClass);

/**
 * §12.1.5 / §12.1.9 — How L12 may consume each dependency surface.
 */
export type L12DependencyUsability =
  | 'IDENTITY_INPUT'
  | 'CONTEXT_ONLY'
  | 'EVIDENCE_ONLY'
  | 'PERSISTENCE_PATH'
  | 'CURRENT_READ'
  | 'HISTORICAL_READ'
  | 'LINEAGE_REFERENCE'
  | 'REPLAY_REFERENCE'
  | 'REPAIR_REFERENCE'
  | 'VALIDATION_INPUT'
  | 'CONTRADICTION_INPUT'
  | 'CONFIDENCE_INPUT'
  | 'RESTRICTION_INPUT'
  | 'REGIME_CONDITIONING'
  | 'SEQUENCE_CONDITIONING'
  | 'HYPOTHESIS_CONDITIONING'
  | 'SCORE_CONTEXT_BUNDLE'
  | 'SHIFT_CONDITION_INPUT';

/**
 * §12.1.7 — Allowed downstream consumers of L12 output surfaces.
 * Layer 12 may not be consumed by sublayers below itself.
 */
export enum L12DownstreamConsumer {
  L13_JUDGMENT_LAYER = 'L13_JUDGMENT_LAYER',
  L14_DELIVERY_LAYER = 'L14_DELIVERY_LAYER',
  L15_FEEDBACK_LAYER = 'L15_FEEDBACK_LAYER',
  L16_GOVERNANCE_LAYER = 'L16_GOVERNANCE_LAYER',
  L17_PLUS_LAYER = 'L17_PLUS_LAYER',
}

export const ALL_L12_DOWNSTREAM_CONSUMERS: readonly L12DownstreamConsumer[] =
  Object.values(L12DownstreamConsumer);
