/**
 * L12.1 — Dependency Surface Contract
 *
 * §12.1.5 / §12.1.9 — Hard constitutional dependency law for the
 * Scenario Engine. Every registered dependency surface declares its
 * source layer, authority class, freshness, replay legality, and
 * posture awareness (regime, sequence, hypothesis, restriction).
 *
 * §12.1.5.6–§12.1.5.9 — L7, L8, L9, L10 and L11 surfaces are stable
 * handoff only. Internal runtime state of those layers is forbidden.
 * §12.1.5.9 — L11 score consumption requires the full score CONTEXT
 * BUNDLE; naked score values are illegal.
 */

import {
  L12CapabilityContext,
  L12DependencyLayer,
  L12DependencySurfaceClass,
  L12ForbiddenAction,
  type L12DependencyUsability,
} from './l12-constitutional-types';

export interface L12DependencySurfaceDescriptor {
  readonly surfaceId: string;
  readonly layer: L12DependencyLayer;
  readonly surfaceClass: L12DependencySurfaceClass;
  readonly authorityClass:
    | 'CANONICAL'
    | 'DERIVED'
    | 'CONTEXTUAL'
    | 'EVIDENCE'
    | 'STABLE_HANDOFF';
  readonly freshnessExpectation:
    | 'REAL_TIME'
    | 'NEAR_REAL_TIME'
    | 'PERIODIC'
    | 'ON_DEMAND';
  readonly replayCompatible: boolean;
  readonly stableHandoffRequired: boolean;
  readonly restrictionAware: boolean;
  readonly contradictionAware: boolean;
  readonly regimePostureAware: boolean;
  readonly sequencePostureAware: boolean;
  readonly hypothesisPostureAware: boolean;
  readonly scoreContextRequired: boolean;
  readonly usableFor: readonly L12DependencyUsability[];
  readonly legalConsumptionContexts: readonly L12CapabilityContext[];
  readonly forbiddenUseCases: readonly L12ForbiddenAction[];
  readonly required: boolean;
  readonly policyVersion: string;
  readonly description: string;
}

const POLICY_V = 'l12.constitution.v1';
const STD_CTX: readonly L12CapabilityContext[] = [
  L12CapabilityContext.INPUT_RESOLUTION,
  L12CapabilityContext.SCENARIO_GENERATION,
  L12CapabilityContext.CONDITION_RESOLUTION,
  L12CapabilityContext.TRIGGER_RESOLUTION,
  L12CapabilityContext.INVALIDATION_RESOLUTION,
  L12CapabilityContext.PATH_CONFIDENCE,
  L12CapabilityContext.REPLAY,
  L12CapabilityContext.REPAIR,
];
const PERSISTENCE_CTX: readonly L12CapabilityContext[] = [
  L12CapabilityContext.MATERIALIZATION,
  L12CapabilityContext.REPLAY,
  L12CapabilityContext.REPAIR,
  L12CapabilityContext.READ_SERVING,
];

export const L12_DEPENDENCY_SURFACES:
  readonly L12DependencySurfaceDescriptor[] = [
  // ── L3 — identity, scope, metric, version, mutation, confidence rights ──
  {
    surfaceId: 'l3:canonical_entity_identity',
    layer: L12DependencyLayer.L3,
    surfaceClass: L12DependencySurfaceClass.L3_CANONICAL_ENTITY_IDENTITY,
    authorityClass: 'CANONICAL',
    freshnessExpectation: 'NEAR_REAL_TIME',
    replayCompatible: true,
    stableHandoffRequired: false,
    restrictionAware: false,
    contradictionAware: false,
    regimePostureAware: false,
    sequencePostureAware: false,
    hypothesisPostureAware: false,
    scoreContextRequired: false,
    usableFor: ['IDENTITY_INPUT', 'CONTEXT_ONLY'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.LOWER_LAYER_TRUTH_REDEFINITION],
    required: true,
    policyVersion: POLICY_V,
    description: 'L3 canonical entity identity — never re-resolve in L12',
  },
  {
    surfaceId: 'l3:scope_contract',
    layer: L12DependencyLayer.L3,
    surfaceClass: L12DependencySurfaceClass.L3_SCOPE_CONTRACT,
    authorityClass: 'CANONICAL',
    freshnessExpectation: 'ON_DEMAND',
    replayCompatible: true,
    stableHandoffRequired: false,
    restrictionAware: false,
    contradictionAware: false,
    regimePostureAware: false,
    sequencePostureAware: false,
    hypothesisPostureAware: false,
    scoreContextRequired: false,
    usableFor: ['IDENTITY_INPUT', 'CONTEXT_ONLY'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.LOWER_LAYER_TRUTH_REDEFINITION],
    required: true,
    policyVersion: POLICY_V,
    description: 'L3 scope contract — scope semantics may not be redefined',
  },
  {
    surfaceId: 'l3:metric_contract',
    layer: L12DependencyLayer.L3,
    surfaceClass: L12DependencySurfaceClass.L3_METRIC_CONTRACT,
    authorityClass: 'CANONICAL',
    freshnessExpectation: 'ON_DEMAND',
    replayCompatible: true,
    stableHandoffRequired: false,
    restrictionAware: false,
    contradictionAware: false,
    regimePostureAware: false,
    sequencePostureAware: false,
    hypothesisPostureAware: false,
    scoreContextRequired: false,
    usableFor: ['CONTEXT_ONLY'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.LOWER_LAYER_TRUTH_REDEFINITION],
    required: true,
    policyVersion: POLICY_V,
    description: 'L3 metric contract — units, precision, valid ranges',
  },
  {
    surfaceId: 'l3:version_contract',
    layer: L12DependencyLayer.L3,
    surfaceClass: L12DependencySurfaceClass.L3_VERSION_CONTRACT,
    authorityClass: 'CANONICAL',
    freshnessExpectation: 'ON_DEMAND',
    replayCompatible: true,
    stableHandoffRequired: false,
    restrictionAware: false,
    contradictionAware: false,
    regimePostureAware: false,
    sequencePostureAware: false,
    hypothesisPostureAware: false,
    scoreContextRequired: false,
    usableFor: ['CONTEXT_ONLY'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.LOWER_LAYER_TRUTH_REDEFINITION],
    required: true,
    policyVersion: POLICY_V,
    description: 'L3 version contract',
  },
  {
    surfaceId: 'l3:mutation_contract',
    layer: L12DependencyLayer.L3,
    surfaceClass: L12DependencySurfaceClass.L3_MUTATION_CONTRACT,
    authorityClass: 'CANONICAL',
    freshnessExpectation: 'ON_DEMAND',
    replayCompatible: true,
    stableHandoffRequired: false,
    restrictionAware: false,
    contradictionAware: false,
    regimePostureAware: false,
    sequencePostureAware: false,
    hypothesisPostureAware: false,
    scoreContextRequired: false,
    usableFor: ['CONTEXT_ONLY'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.LOWER_LAYER_TRUTH_REDEFINITION],
    required: true,
    policyVersion: POLICY_V,
    description: 'L3 mutation contract',
  },
  {
    surfaceId: 'l3:confidence_rights_contract',
    layer: L12DependencyLayer.L3,
    surfaceClass: L12DependencySurfaceClass.L3_CONFIDENCE_RIGHTS_CONTRACT,
    authorityClass: 'CANONICAL',
    freshnessExpectation: 'ON_DEMAND',
    replayCompatible: true,
    stableHandoffRequired: false,
    restrictionAware: true,
    contradictionAware: false,
    regimePostureAware: false,
    sequencePostureAware: false,
    hypothesisPostureAware: false,
    scoreContextRequired: false,
    usableFor: ['RESTRICTION_INPUT', 'CONTEXT_ONLY'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.LOWER_LAYER_TRUTH_REDEFINITION],
    required: true,
    policyVersion: POLICY_V,
    description: 'L3 confidence-rights contract',
  },

  // ── L4 — graph, ecosystem, sector, propagation, temporal ──
  {
    surfaceId: 'l4:graph_context_package',
    layer: L12DependencyLayer.L4,
    surfaceClass: L12DependencySurfaceClass.L4_GRAPH_CONTEXT_PACKAGE,
    authorityClass: 'CONTEXTUAL',
    freshnessExpectation: 'PERIODIC',
    replayCompatible: true,
    stableHandoffRequired: false,
    restrictionAware: false,
    contradictionAware: false,
    regimePostureAware: false,
    sequencePostureAware: false,
    hypothesisPostureAware: false,
    scoreContextRequired: false,
    usableFor: ['CONTEXT_ONLY'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.LOWER_LAYER_TRUTH_REDEFINITION],
    required: false,
    policyVersion: POLICY_V,
    description: 'L4 graph context package',
  },
  {
    surfaceId: 'l4:relation_evidence',
    layer: L12DependencyLayer.L4,
    surfaceClass: L12DependencySurfaceClass.L4_RELATION_EVIDENCE,
    authorityClass: 'EVIDENCE',
    freshnessExpectation: 'PERIODIC',
    replayCompatible: true,
    stableHandoffRequired: false,
    restrictionAware: false,
    contradictionAware: false,
    regimePostureAware: false,
    sequencePostureAware: false,
    hypothesisPostureAware: false,
    scoreContextRequired: false,
    usableFor: ['EVIDENCE_ONLY', 'CONTEXT_ONLY'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.LOWER_LAYER_TRUTH_REDEFINITION],
    required: false,
    policyVersion: POLICY_V,
    description: 'L4 relation evidence',
  },
  {
    surfaceId: 'l4:propagation_output',
    layer: L12DependencyLayer.L4,
    surfaceClass: L12DependencySurfaceClass.L4_PROPAGATION_OUTPUT,
    authorityClass: 'DERIVED',
    freshnessExpectation: 'PERIODIC',
    replayCompatible: true,
    stableHandoffRequired: false,
    restrictionAware: false,
    contradictionAware: false,
    regimePostureAware: false,
    sequencePostureAware: false,
    hypothesisPostureAware: false,
    scoreContextRequired: false,
    usableFor: ['CONTEXT_ONLY', 'EVIDENCE_ONLY'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.LOWER_LAYER_TRUTH_REDEFINITION],
    required: false,
    policyVersion: POLICY_V,
    description: 'L4 propagation output',
  },
  {
    surfaceId: 'l4:ecosystem_context',
    layer: L12DependencyLayer.L4,
    surfaceClass: L12DependencySurfaceClass.L4_ECOSYSTEM_CONTEXT,
    authorityClass: 'CONTEXTUAL',
    freshnessExpectation: 'PERIODIC',
    replayCompatible: true,
    stableHandoffRequired: false,
    restrictionAware: false,
    contradictionAware: false,
    regimePostureAware: false,
    sequencePostureAware: false,
    hypothesisPostureAware: false,
    scoreContextRequired: false,
    usableFor: ['CONTEXT_ONLY'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.LOWER_LAYER_TRUTH_REDEFINITION],
    required: false,
    policyVersion: POLICY_V,
    description: 'L4 ecosystem context',
  },
  {
    surfaceId: 'l4:sector_context',
    layer: L12DependencyLayer.L4,
    surfaceClass: L12DependencySurfaceClass.L4_SECTOR_CONTEXT,
    authorityClass: 'CONTEXTUAL',
    freshnessExpectation: 'PERIODIC',
    replayCompatible: true,
    stableHandoffRequired: false,
    restrictionAware: false,
    contradictionAware: false,
    regimePostureAware: false,
    sequencePostureAware: false,
    hypothesisPostureAware: false,
    scoreContextRequired: false,
    usableFor: ['CONTEXT_ONLY'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.LOWER_LAYER_TRUTH_REDEFINITION],
    required: false,
    policyVersion: POLICY_V,
    description: 'L4 sector context',
  },
  {
    surfaceId: 'l4:temporal_graph_state',
    layer: L12DependencyLayer.L4,
    surfaceClass: L12DependencySurfaceClass.L4_TEMPORAL_GRAPH_STATE,
    authorityClass: 'CANONICAL',
    freshnessExpectation: 'PERIODIC',
    replayCompatible: true,
    stableHandoffRequired: false,
    restrictionAware: false,
    contradictionAware: false,
    regimePostureAware: false,
    sequencePostureAware: false,
    hypothesisPostureAware: false,
    scoreContextRequired: false,
    usableFor: ['CONTEXT_ONLY', 'EVIDENCE_ONLY'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.LOWER_LAYER_TRUTH_REDEFINITION],
    required: false,
    policyVersion: POLICY_V,
    description: 'L4 temporal graph state',
  },

  // ── L5 — persistence, replay, repair, reads ──
  {
    surfaceId: 'l5:current_state_read',
    layer: L12DependencyLayer.L5,
    surfaceClass: L12DependencySurfaceClass.L5_CURRENT_STATE_READ,
    authorityClass: 'CANONICAL',
    freshnessExpectation: 'REAL_TIME',
    replayCompatible: true,
    stableHandoffRequired: false,
    restrictionAware: false,
    contradictionAware: false,
    regimePostureAware: false,
    sequencePostureAware: false,
    hypothesisPostureAware: false,
    scoreContextRequired: false,
    usableFor: ['CURRENT_READ'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [
      L12ForbiddenAction.RAW_STORAGE_BYPASS,
      L12ForbiddenAction.L5_PERSISTENCE_BYPASS,
    ],
    required: true,
    policyVersion: POLICY_V,
    description: 'L5 current-state read (governed)',
  },
  {
    surfaceId: 'l5:historical_state_read',
    layer: L12DependencyLayer.L5,
    surfaceClass: L12DependencySurfaceClass.L5_HISTORICAL_STATE_READ,
    authorityClass: 'CANONICAL',
    freshnessExpectation: 'ON_DEMAND',
    replayCompatible: true,
    stableHandoffRequired: false,
    restrictionAware: false,
    contradictionAware: false,
    regimePostureAware: false,
    sequencePostureAware: false,
    hypothesisPostureAware: false,
    scoreContextRequired: false,
    usableFor: ['HISTORICAL_READ', 'REPLAY_REFERENCE'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [
      L12ForbiddenAction.RAW_STORAGE_BYPASS,
      L12ForbiddenAction.L5_PERSISTENCE_BYPASS,
    ],
    required: true,
    policyVersion: POLICY_V,
    description: 'L5 historical-state read (governed)',
  },
  {
    surfaceId: 'l5:evidence_read',
    layer: L12DependencyLayer.L5,
    surfaceClass: L12DependencySurfaceClass.L5_EVIDENCE_READ,
    authorityClass: 'CANONICAL',
    freshnessExpectation: 'ON_DEMAND',
    replayCompatible: true,
    stableHandoffRequired: false,
    restrictionAware: false,
    contradictionAware: false,
    regimePostureAware: false,
    sequencePostureAware: false,
    hypothesisPostureAware: false,
    scoreContextRequired: false,
    usableFor: ['EVIDENCE_ONLY'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.RAW_STORAGE_BYPASS],
    required: true,
    policyVersion: POLICY_V,
    description: 'L5 evidence read',
  },
  {
    surfaceId: 'l5:lineage_read',
    layer: L12DependencyLayer.L5,
    surfaceClass: L12DependencySurfaceClass.L5_LINEAGE_READ,
    authorityClass: 'CANONICAL',
    freshnessExpectation: 'ON_DEMAND',
    replayCompatible: true,
    stableHandoffRequired: false,
    restrictionAware: false,
    contradictionAware: false,
    regimePostureAware: false,
    sequencePostureAware: false,
    hypothesisPostureAware: false,
    scoreContextRequired: false,
    usableFor: ['LINEAGE_REFERENCE'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.RAW_STORAGE_BYPASS],
    required: true,
    policyVersion: POLICY_V,
    description: 'L5 lineage read',
  },
  {
    surfaceId: 'l5:replay_context',
    layer: L12DependencyLayer.L5,
    surfaceClass: L12DependencySurfaceClass.L5_REPLAY_CONTEXT,
    authorityClass: 'CANONICAL',
    freshnessExpectation: 'ON_DEMAND',
    replayCompatible: true,
    stableHandoffRequired: false,
    restrictionAware: false,
    contradictionAware: false,
    regimePostureAware: false,
    sequencePostureAware: false,
    hypothesisPostureAware: false,
    scoreContextRequired: false,
    usableFor: ['REPLAY_REFERENCE'],
    legalConsumptionContexts: PERSISTENCE_CTX,
    forbiddenUseCases: [L12ForbiddenAction.RAW_STORAGE_BYPASS],
    required: false,
    policyVersion: POLICY_V,
    description: 'L5 replay context',
  },
  {
    surfaceId: 'l5:repair_context',
    layer: L12DependencyLayer.L5,
    surfaceClass: L12DependencySurfaceClass.L5_REPAIR_CONTEXT,
    authorityClass: 'CANONICAL',
    freshnessExpectation: 'ON_DEMAND',
    replayCompatible: true,
    stableHandoffRequired: false,
    restrictionAware: false,
    contradictionAware: false,
    regimePostureAware: false,
    sequencePostureAware: false,
    hypothesisPostureAware: false,
    scoreContextRequired: false,
    usableFor: ['REPAIR_REFERENCE'],
    legalConsumptionContexts: PERSISTENCE_CTX,
    forbiddenUseCases: [L12ForbiddenAction.RAW_STORAGE_BYPASS],
    required: false,
    policyVersion: POLICY_V,
    description: 'L5 repair context',
  },
  {
    surfaceId: 'l5:materialization_route',
    layer: L12DependencyLayer.L5,
    surfaceClass: L12DependencySurfaceClass.L5_MATERIALIZATION_ROUTE,
    authorityClass: 'CANONICAL',
    freshnessExpectation: 'REAL_TIME',
    replayCompatible: true,
    stableHandoffRequired: false,
    restrictionAware: false,
    contradictionAware: false,
    regimePostureAware: false,
    sequencePostureAware: false,
    hypothesisPostureAware: false,
    scoreContextRequired: false,
    usableFor: ['PERSISTENCE_PATH'],
    legalConsumptionContexts: PERSISTENCE_CTX,
    forbiddenUseCases: [
      L12ForbiddenAction.RAW_STORAGE_BYPASS,
      L12ForbiddenAction.L5_PERSISTENCE_BYPASS,
    ],
    required: true,
    policyVersion: POLICY_V,
    description: 'L5 materialization route — only path to persistence',
  },

  // ── L6 — only via governed read surfaces, never raw primitives ──
  {
    surfaceId: 'l6:feature_state_read_surface',
    layer: L12DependencyLayer.L6,
    surfaceClass: L12DependencySurfaceClass.L6_FEATURE_STATE_READ_SURFACE,
    authorityClass: 'STABLE_HANDOFF',
    freshnessExpectation: 'NEAR_REAL_TIME',
    replayCompatible: true,
    stableHandoffRequired: true,
    restrictionAware: false,
    contradictionAware: false,
    regimePostureAware: false,
    sequencePostureAware: false,
    hypothesisPostureAware: false,
    scoreContextRequired: false,
    usableFor: ['EVIDENCE_ONLY', 'CONTEXT_ONLY'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.LOWER_LAYER_TRUTH_REDEFINITION],
    required: false,
    policyVersion: POLICY_V,
    description: 'L6 feature-state read surface (no raw primitive use)',
  },
  {
    surfaceId: 'l6:feature_history_read_surface',
    layer: L12DependencyLayer.L6,
    surfaceClass: L12DependencySurfaceClass.L6_FEATURE_HISTORY_READ_SURFACE,
    authorityClass: 'STABLE_HANDOFF',
    freshnessExpectation: 'ON_DEMAND',
    replayCompatible: true,
    stableHandoffRequired: true,
    restrictionAware: false,
    contradictionAware: false,
    regimePostureAware: false,
    sequencePostureAware: false,
    hypothesisPostureAware: false,
    scoreContextRequired: false,
    usableFor: ['EVIDENCE_ONLY', 'HISTORICAL_READ'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.LOWER_LAYER_TRUTH_REDEFINITION],
    required: false,
    policyVersion: POLICY_V,
    description: 'L6 feature-history read surface',
  },
  {
    surfaceId: 'l6:event_state_read_surface',
    layer: L12DependencyLayer.L6,
    surfaceClass: L12DependencySurfaceClass.L6_EVENT_STATE_READ_SURFACE,
    authorityClass: 'STABLE_HANDOFF',
    freshnessExpectation: 'NEAR_REAL_TIME',
    replayCompatible: true,
    stableHandoffRequired: true,
    restrictionAware: false,
    contradictionAware: false,
    regimePostureAware: false,
    sequencePostureAware: false,
    hypothesisPostureAware: false,
    scoreContextRequired: false,
    usableFor: ['EVIDENCE_ONLY', 'CONTEXT_ONLY'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.LOWER_LAYER_TRUTH_REDEFINITION],
    required: false,
    policyVersion: POLICY_V,
    description: 'L6 event-state read surface',
  },
  {
    surfaceId: 'l6:event_history_read_surface',
    layer: L12DependencyLayer.L6,
    surfaceClass: L12DependencySurfaceClass.L6_EVENT_HISTORY_READ_SURFACE,
    authorityClass: 'STABLE_HANDOFF',
    freshnessExpectation: 'ON_DEMAND',
    replayCompatible: true,
    stableHandoffRequired: true,
    restrictionAware: false,
    contradictionAware: false,
    regimePostureAware: false,
    sequencePostureAware: false,
    hypothesisPostureAware: false,
    scoreContextRequired: false,
    usableFor: ['EVIDENCE_ONLY', 'HISTORICAL_READ'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.LOWER_LAYER_TRUTH_REDEFINITION],
    required: false,
    policyVersion: POLICY_V,
    description: 'L6 event-history read surface',
  },
  {
    surfaceId: 'l6:primitive_evidence_pack',
    layer: L12DependencyLayer.L6,
    surfaceClass: L12DependencySurfaceClass.L6_PRIMITIVE_EVIDENCE_PACK,
    authorityClass: 'EVIDENCE',
    freshnessExpectation: 'ON_DEMAND',
    replayCompatible: true,
    stableHandoffRequired: true,
    restrictionAware: false,
    contradictionAware: false,
    regimePostureAware: false,
    sequencePostureAware: false,
    hypothesisPostureAware: false,
    scoreContextRequired: false,
    usableFor: ['EVIDENCE_ONLY'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.LOWER_LAYER_TRUTH_REDEFINITION],
    required: false,
    policyVersion: POLICY_V,
    description: 'L6 primitive evidence pack',
  },
  {
    surfaceId: 'l6:freshness_profile',
    layer: L12DependencyLayer.L6,
    surfaceClass: L12DependencySurfaceClass.L6_FRESHNESS_PROFILE,
    authorityClass: 'CONTEXTUAL',
    freshnessExpectation: 'NEAR_REAL_TIME',
    replayCompatible: true,
    stableHandoffRequired: true,
    restrictionAware: false,
    contradictionAware: false,
    regimePostureAware: false,
    sequencePostureAware: false,
    hypothesisPostureAware: false,
    scoreContextRequired: false,
    usableFor: ['CONTEXT_ONLY'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.LOWER_LAYER_TRUTH_REDEFINITION],
    required: false,
    policyVersion: POLICY_V,
    description: 'L6 freshness profile',
  },
  {
    surfaceId: 'l6:quality_profile',
    layer: L12DependencyLayer.L6,
    surfaceClass: L12DependencySurfaceClass.L6_QUALITY_PROFILE,
    authorityClass: 'CONTEXTUAL',
    freshnessExpectation: 'NEAR_REAL_TIME',
    replayCompatible: true,
    stableHandoffRequired: true,
    restrictionAware: false,
    contradictionAware: false,
    regimePostureAware: false,
    sequencePostureAware: false,
    hypothesisPostureAware: false,
    scoreContextRequired: false,
    usableFor: ['CONTEXT_ONLY'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.LOWER_LAYER_TRUTH_REDEFINITION],
    required: false,
    policyVersion: POLICY_V,
    description: 'L6 quality profile',
  },

  // ── L7 — stable handoff only ──
  {
    surfaceId: 'l7:validation_assessment',
    layer: L12DependencyLayer.L7,
    surfaceClass: L12DependencySurfaceClass.L7_VALIDATION_ASSESSMENT,
    authorityClass: 'STABLE_HANDOFF',
    freshnessExpectation: 'NEAR_REAL_TIME',
    replayCompatible: true,
    stableHandoffRequired: true,
    restrictionAware: true,
    contradictionAware: true,
    regimePostureAware: false,
    sequencePostureAware: false,
    hypothesisPostureAware: false,
    scoreContextRequired: false,
    usableFor: ['VALIDATION_INPUT', 'CONFIDENCE_INPUT'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [
      L12ForbiddenAction.VALIDATION_REBUILD,
      L12ForbiddenAction.L7_RESTRICTION_BYPASS,
    ],
    required: true,
    policyVersion: POLICY_V,
    description: 'L7 validation assessment (stable handoff)',
  },
  {
    surfaceId: 'l7:contradiction_bundle',
    layer: L12DependencyLayer.L7,
    surfaceClass: L12DependencySurfaceClass.L7_CONTRADICTION_BUNDLE,
    authorityClass: 'STABLE_HANDOFF',
    freshnessExpectation: 'NEAR_REAL_TIME',
    replayCompatible: true,
    stableHandoffRequired: true,
    restrictionAware: true,
    contradictionAware: true,
    regimePostureAware: false,
    sequencePostureAware: false,
    hypothesisPostureAware: false,
    scoreContextRequired: false,
    usableFor: ['CONTRADICTION_INPUT', 'CONFIDENCE_INPUT'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.CONTRADICTION_DOWNGRADE],
    required: true,
    policyVersion: POLICY_V,
    description: 'L7 contradiction bundle (stable handoff) — never downgrade',
  },
  {
    surfaceId: 'l7:confidence_assessment',
    layer: L12DependencyLayer.L7,
    surfaceClass: L12DependencySurfaceClass.L7_CONFIDENCE_ASSESSMENT,
    authorityClass: 'STABLE_HANDOFF',
    freshnessExpectation: 'NEAR_REAL_TIME',
    replayCompatible: true,
    stableHandoffRequired: true,
    restrictionAware: true,
    contradictionAware: true,
    regimePostureAware: false,
    sequencePostureAware: false,
    hypothesisPostureAware: false,
    scoreContextRequired: false,
    usableFor: ['CONFIDENCE_INPUT'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.PATH_CONFIDENCE_LAUNDERING],
    required: true,
    policyVersion: POLICY_V,
    description: 'L7 confidence assessment (stable handoff)',
  },
  {
    surfaceId: 'l7:restriction_profile',
    layer: L12DependencyLayer.L7,
    surfaceClass: L12DependencySurfaceClass.L7_RESTRICTION_PROFILE,
    authorityClass: 'STABLE_HANDOFF',
    freshnessExpectation: 'NEAR_REAL_TIME',
    replayCompatible: true,
    stableHandoffRequired: true,
    restrictionAware: true,
    contradictionAware: false,
    regimePostureAware: false,
    sequencePostureAware: false,
    hypothesisPostureAware: false,
    scoreContextRequired: false,
    usableFor: ['RESTRICTION_INPUT'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.L7_RESTRICTION_BYPASS],
    required: true,
    policyVersion: POLICY_V,
    description: 'L7 restriction profile (binding, stable handoff)',
  },
  {
    surfaceId: 'l7:validation_evidence_read_surface',
    layer: L12DependencyLayer.L7,
    surfaceClass: L12DependencySurfaceClass.L7_VALIDATION_EVIDENCE_READ_SURFACE,
    authorityClass: 'STABLE_HANDOFF',
    freshnessExpectation: 'ON_DEMAND',
    replayCompatible: true,
    stableHandoffRequired: true,
    restrictionAware: true,
    contradictionAware: false,
    regimePostureAware: false,
    sequencePostureAware: false,
    hypothesisPostureAware: false,
    scoreContextRequired: false,
    usableFor: ['EVIDENCE_ONLY', 'REPLAY_REFERENCE'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.VALIDATION_REBUILD],
    required: false,
    policyVersion: POLICY_V,
    description: 'L7 validation evidence read surface (stable handoff)',
  },
  {
    surfaceId: 'l7:historical_validation_window',
    layer: L12DependencyLayer.L7,
    surfaceClass: L12DependencySurfaceClass.L7_HISTORICAL_VALIDATION_WINDOW,
    authorityClass: 'STABLE_HANDOFF',
    freshnessExpectation: 'ON_DEMAND',
    replayCompatible: true,
    stableHandoffRequired: true,
    restrictionAware: true,
    contradictionAware: false,
    regimePostureAware: false,
    sequencePostureAware: false,
    hypothesisPostureAware: false,
    scoreContextRequired: false,
    usableFor: ['HISTORICAL_READ', 'REPLAY_REFERENCE'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.VALIDATION_REBUILD],
    required: false,
    policyVersion: POLICY_V,
    description: 'L7 historical validation window (stable handoff)',
  },

  // ── L8 — stable handoff only ──
  {
    surfaceId: 'l8:current_regime_state',
    layer: L12DependencyLayer.L8,
    surfaceClass: L12DependencySurfaceClass.L8_CURRENT_REGIME_STATE,
    authorityClass: 'STABLE_HANDOFF',
    freshnessExpectation: 'NEAR_REAL_TIME',
    replayCompatible: true,
    stableHandoffRequired: true,
    restrictionAware: true,
    contradictionAware: false,
    regimePostureAware: true,
    sequencePostureAware: false,
    hypothesisPostureAware: false,
    scoreContextRequired: false,
    usableFor: ['REGIME_CONDITIONING'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [
      L12ForbiddenAction.REGIME_REBUILD,
      L12ForbiddenAction.L8_REGIME_POSTURE_IGNORE,
    ],
    required: true,
    policyVersion: POLICY_V,
    description: 'L8 current regime state (stable handoff)',
  },
  {
    surfaceId: 'l8:current_transition_profile',
    layer: L12DependencyLayer.L8,
    surfaceClass: L12DependencySurfaceClass.L8_CURRENT_TRANSITION_PROFILE,
    authorityClass: 'STABLE_HANDOFF',
    freshnessExpectation: 'NEAR_REAL_TIME',
    replayCompatible: true,
    stableHandoffRequired: true,
    restrictionAware: true,
    contradictionAware: false,
    regimePostureAware: true,
    sequencePostureAware: false,
    hypothesisPostureAware: false,
    scoreContextRequired: false,
    usableFor: ['REGIME_CONDITIONING'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.L8_REGIME_POSTURE_IGNORE],
    required: true,
    policyVersion: POLICY_V,
    description: 'L8 current transition profile (stable handoff)',
  },
  {
    surfaceId: 'l8:current_regime_confidence',
    layer: L12DependencyLayer.L8,
    surfaceClass: L12DependencySurfaceClass.L8_CURRENT_REGIME_CONFIDENCE,
    authorityClass: 'STABLE_HANDOFF',
    freshnessExpectation: 'NEAR_REAL_TIME',
    replayCompatible: true,
    stableHandoffRequired: true,
    restrictionAware: true,
    contradictionAware: false,
    regimePostureAware: true,
    sequencePostureAware: false,
    hypothesisPostureAware: false,
    scoreContextRequired: false,
    usableFor: ['REGIME_CONDITIONING', 'CONFIDENCE_INPUT'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.L8_REGIME_POSTURE_IGNORE],
    required: true,
    policyVersion: POLICY_V,
    description: 'L8 current regime confidence (stable handoff)',
  },
  {
    surfaceId: 'l8:current_multiplier_profile',
    layer: L12DependencyLayer.L8,
    surfaceClass: L12DependencySurfaceClass.L8_CURRENT_MULTIPLIER_PROFILE,
    authorityClass: 'STABLE_HANDOFF',
    freshnessExpectation: 'NEAR_REAL_TIME',
    replayCompatible: true,
    stableHandoffRequired: true,
    restrictionAware: true,
    contradictionAware: false,
    regimePostureAware: true,
    sequencePostureAware: false,
    hypothesisPostureAware: false,
    scoreContextRequired: false,
    usableFor: ['REGIME_CONDITIONING'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.L8_REGIME_POSTURE_IGNORE],
    required: false,
    policyVersion: POLICY_V,
    description: 'L8 current multiplier profile (stable handoff)',
  },
  {
    surfaceId: 'l8:regime_history_window',
    layer: L12DependencyLayer.L8,
    surfaceClass: L12DependencySurfaceClass.L8_REGIME_HISTORY_WINDOW,
    authorityClass: 'STABLE_HANDOFF',
    freshnessExpectation: 'ON_DEMAND',
    replayCompatible: true,
    stableHandoffRequired: true,
    restrictionAware: true,
    contradictionAware: false,
    regimePostureAware: true,
    sequencePostureAware: false,
    hypothesisPostureAware: false,
    scoreContextRequired: false,
    usableFor: ['HISTORICAL_READ', 'REPLAY_REFERENCE'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.REGIME_REBUILD],
    required: false,
    policyVersion: POLICY_V,
    description: 'L8 regime history window',
  },
  {
    surfaceId: 'l8:regime_evidence_bundle',
    layer: L12DependencyLayer.L8,
    surfaceClass: L12DependencySurfaceClass.L8_REGIME_EVIDENCE_BUNDLE,
    authorityClass: 'STABLE_HANDOFF',
    freshnessExpectation: 'ON_DEMAND',
    replayCompatible: true,
    stableHandoffRequired: true,
    restrictionAware: true,
    contradictionAware: false,
    regimePostureAware: true,
    sequencePostureAware: false,
    hypothesisPostureAware: false,
    scoreContextRequired: false,
    usableFor: ['EVIDENCE_ONLY'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.REGIME_REBUILD],
    required: false,
    policyVersion: POLICY_V,
    description: 'L8 regime evidence bundle',
  },
  {
    surfaceId: 'l8:regime_lineage',
    layer: L12DependencyLayer.L8,
    surfaceClass: L12DependencySurfaceClass.L8_REGIME_LINEAGE,
    authorityClass: 'STABLE_HANDOFF',
    freshnessExpectation: 'ON_DEMAND',
    replayCompatible: true,
    stableHandoffRequired: true,
    restrictionAware: true,
    contradictionAware: false,
    regimePostureAware: true,
    sequencePostureAware: false,
    hypothesisPostureAware: false,
    scoreContextRequired: false,
    usableFor: ['LINEAGE_REFERENCE'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.REGIME_REBUILD],
    required: false,
    policyVersion: POLICY_V,
    description: 'L8 regime lineage',
  },

  // ── L9 — stable handoff only ──
  {
    surfaceId: 'l9:current_sequence_state',
    layer: L12DependencyLayer.L9,
    surfaceClass: L12DependencySurfaceClass.L9_CURRENT_SEQUENCE_STATE,
    authorityClass: 'STABLE_HANDOFF',
    freshnessExpectation: 'NEAR_REAL_TIME',
    replayCompatible: true,
    stableHandoffRequired: true,
    restrictionAware: true,
    contradictionAware: false,
    regimePostureAware: false,
    sequencePostureAware: true,
    hypothesisPostureAware: false,
    scoreContextRequired: false,
    usableFor: ['SEQUENCE_CONDITIONING'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [
      L12ForbiddenAction.SEQUENCE_REBUILD,
      L12ForbiddenAction.L9_SEQUENCE_POSTURE_IGNORE,
    ],
    required: true,
    policyVersion: POLICY_V,
    description: 'L9 current sequence state (stable handoff)',
  },
  {
    surfaceId: 'l9:current_phase_profile',
    layer: L12DependencyLayer.L9,
    surfaceClass: L12DependencySurfaceClass.L9_CURRENT_PHASE_PROFILE,
    authorityClass: 'STABLE_HANDOFF',
    freshnessExpectation: 'NEAR_REAL_TIME',
    replayCompatible: true,
    stableHandoffRequired: true,
    restrictionAware: true,
    contradictionAware: false,
    regimePostureAware: false,
    sequencePostureAware: true,
    hypothesisPostureAware: false,
    scoreContextRequired: false,
    usableFor: ['SEQUENCE_CONDITIONING'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.L9_SEQUENCE_POSTURE_IGNORE],
    required: true,
    policyVersion: POLICY_V,
    description: 'L9 current phase profile (stable handoff)',
  },
  {
    surfaceId: 'l9:current_decay_profile',
    layer: L12DependencyLayer.L9,
    surfaceClass: L12DependencySurfaceClass.L9_CURRENT_DECAY_PROFILE,
    authorityClass: 'STABLE_HANDOFF',
    freshnessExpectation: 'NEAR_REAL_TIME',
    replayCompatible: true,
    stableHandoffRequired: true,
    restrictionAware: true,
    contradictionAware: false,
    regimePostureAware: false,
    sequencePostureAware: true,
    hypothesisPostureAware: false,
    scoreContextRequired: false,
    usableFor: ['SEQUENCE_CONDITIONING'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.L9_SEQUENCE_POSTURE_IGNORE],
    required: true,
    policyVersion: POLICY_V,
    description: 'L9 current decay profile (stable handoff)',
  },
  {
    surfaceId: 'l9:lead_lag_profile',
    layer: L12DependencyLayer.L9,
    surfaceClass: L12DependencySurfaceClass.L9_LEAD_LAG_PROFILE,
    authorityClass: 'STABLE_HANDOFF',
    freshnessExpectation: 'NEAR_REAL_TIME',
    replayCompatible: true,
    stableHandoffRequired: true,
    restrictionAware: true,
    contradictionAware: false,
    regimePostureAware: false,
    sequencePostureAware: true,
    hypothesisPostureAware: false,
    scoreContextRequired: false,
    usableFor: ['SEQUENCE_CONDITIONING'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.L9_SEQUENCE_POSTURE_IGNORE],
    required: true,
    policyVersion: POLICY_V,
    description: 'L9 lead-lag profile (stable handoff)',
  },
  {
    surfaceId: 'l9:post_event_window_profile',
    layer: L12DependencyLayer.L9,
    surfaceClass: L12DependencySurfaceClass.L9_POST_EVENT_WINDOW_PROFILE,
    authorityClass: 'STABLE_HANDOFF',
    freshnessExpectation: 'NEAR_REAL_TIME',
    replayCompatible: true,
    stableHandoffRequired: true,
    restrictionAware: true,
    contradictionAware: false,
    regimePostureAware: false,
    sequencePostureAware: true,
    hypothesisPostureAware: false,
    scoreContextRequired: false,
    usableFor: ['SEQUENCE_CONDITIONING'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.L9_SEQUENCE_POSTURE_IGNORE],
    required: false,
    policyVersion: POLICY_V,
    description: 'L9 post-event window profile (stable handoff)',
  },
  {
    surfaceId: 'l9:sequence_confidence_profile',
    layer: L12DependencyLayer.L9,
    surfaceClass: L12DependencySurfaceClass.L9_SEQUENCE_CONFIDENCE_PROFILE,
    authorityClass: 'STABLE_HANDOFF',
    freshnessExpectation: 'NEAR_REAL_TIME',
    replayCompatible: true,
    stableHandoffRequired: true,
    restrictionAware: true,
    contradictionAware: false,
    regimePostureAware: false,
    sequencePostureAware: true,
    hypothesisPostureAware: false,
    scoreContextRequired: false,
    usableFor: ['CONFIDENCE_INPUT', 'SEQUENCE_CONDITIONING'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.PATH_CONFIDENCE_LAUNDERING],
    required: true,
    policyVersion: POLICY_V,
    description: 'L9 sequence confidence profile (stable handoff)',
  },
  {
    surfaceId: 'l9:sequence_restriction_profile',
    layer: L12DependencyLayer.L9,
    surfaceClass: L12DependencySurfaceClass.L9_SEQUENCE_RESTRICTION_PROFILE,
    authorityClass: 'STABLE_HANDOFF',
    freshnessExpectation: 'NEAR_REAL_TIME',
    replayCompatible: true,
    stableHandoffRequired: true,
    restrictionAware: true,
    contradictionAware: false,
    regimePostureAware: false,
    sequencePostureAware: true,
    hypothesisPostureAware: false,
    scoreContextRequired: false,
    usableFor: ['RESTRICTION_INPUT'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.L9_SEQUENCE_POSTURE_IGNORE],
    required: true,
    policyVersion: POLICY_V,
    description: 'L9 sequence restriction profile (stable handoff)',
  },
  {
    surfaceId: 'l9:sequence_evidence_bundle',
    layer: L12DependencyLayer.L9,
    surfaceClass: L12DependencySurfaceClass.L9_SEQUENCE_EVIDENCE_BUNDLE,
    authorityClass: 'STABLE_HANDOFF',
    freshnessExpectation: 'ON_DEMAND',
    replayCompatible: true,
    stableHandoffRequired: true,
    restrictionAware: true,
    contradictionAware: false,
    regimePostureAware: false,
    sequencePostureAware: true,
    hypothesisPostureAware: false,
    scoreContextRequired: false,
    usableFor: ['EVIDENCE_ONLY'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.SEQUENCE_REBUILD],
    required: false,
    policyVersion: POLICY_V,
    description: 'L9 sequence evidence bundle',
  },
  {
    surfaceId: 'l9:sequence_history_window',
    layer: L12DependencyLayer.L9,
    surfaceClass: L12DependencySurfaceClass.L9_SEQUENCE_HISTORY_WINDOW,
    authorityClass: 'STABLE_HANDOFF',
    freshnessExpectation: 'ON_DEMAND',
    replayCompatible: true,
    stableHandoffRequired: true,
    restrictionAware: true,
    contradictionAware: false,
    regimePostureAware: false,
    sequencePostureAware: true,
    hypothesisPostureAware: false,
    scoreContextRequired: false,
    usableFor: ['HISTORICAL_READ'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.SEQUENCE_REBUILD],
    required: false,
    policyVersion: POLICY_V,
    description: 'L9 sequence history window',
  },

  // ── L10 — stable handoff only ──
  {
    surfaceId: 'l10:current_hypothesis_ranking',
    layer: L12DependencyLayer.L10,
    surfaceClass: L12DependencySurfaceClass.L10_CURRENT_HYPOTHESIS_RANKING,
    authorityClass: 'STABLE_HANDOFF',
    freshnessExpectation: 'NEAR_REAL_TIME',
    replayCompatible: true,
    stableHandoffRequired: true,
    restrictionAware: true,
    contradictionAware: false,
    regimePostureAware: false,
    sequencePostureAware: false,
    hypothesisPostureAware: true,
    scoreContextRequired: false,
    usableFor: ['HYPOTHESIS_CONDITIONING'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [
      L12ForbiddenAction.HYPOTHESIS_REBUILD,
      L12ForbiddenAction.L10_HYPOTHESIS_POSTURE_IGNORE,
    ],
    required: true,
    policyVersion: POLICY_V,
    description: 'L10 current hypothesis ranking (stable handoff)',
  },
  {
    surfaceId: 'l10:primary_hypothesis',
    layer: L12DependencyLayer.L10,
    surfaceClass: L12DependencySurfaceClass.L10_PRIMARY_HYPOTHESIS,
    authorityClass: 'STABLE_HANDOFF',
    freshnessExpectation: 'NEAR_REAL_TIME',
    replayCompatible: true,
    stableHandoffRequired: true,
    restrictionAware: true,
    contradictionAware: false,
    regimePostureAware: false,
    sequencePostureAware: false,
    hypothesisPostureAware: true,
    scoreContextRequired: false,
    usableFor: ['HYPOTHESIS_CONDITIONING'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.HYPOTHESIS_REBUILD],
    required: true,
    policyVersion: POLICY_V,
    description: 'L10 primary hypothesis (stable handoff)',
  },
  {
    surfaceId: 'l10:secondary_hypothesis',
    layer: L12DependencyLayer.L10,
    surfaceClass: L12DependencySurfaceClass.L10_SECONDARY_HYPOTHESIS,
    authorityClass: 'STABLE_HANDOFF',
    freshnessExpectation: 'NEAR_REAL_TIME',
    replayCompatible: true,
    stableHandoffRequired: true,
    restrictionAware: true,
    contradictionAware: false,
    regimePostureAware: false,
    sequencePostureAware: false,
    hypothesisPostureAware: true,
    scoreContextRequired: false,
    usableFor: ['HYPOTHESIS_CONDITIONING'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.HYPOTHESIS_REBUILD],
    required: true,
    policyVersion: POLICY_V,
    description: 'L10 secondary hypothesis (stable handoff)',
  },
  {
    surfaceId: 'l10:hypothesis_spread_profile',
    layer: L12DependencyLayer.L10,
    surfaceClass: L12DependencySurfaceClass.L10_HYPOTHESIS_SPREAD_PROFILE,
    authorityClass: 'STABLE_HANDOFF',
    freshnessExpectation: 'NEAR_REAL_TIME',
    replayCompatible: true,
    stableHandoffRequired: true,
    restrictionAware: true,
    contradictionAware: false,
    regimePostureAware: false,
    sequencePostureAware: false,
    hypothesisPostureAware: true,
    scoreContextRequired: false,
    usableFor: ['HYPOTHESIS_CONDITIONING', 'CONFIDENCE_INPUT'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.SCENARIO_SPREAD_HIDE],
    required: true,
    policyVersion: POLICY_V,
    description: 'L10 hypothesis spread profile — narrow spread must be honoured',
  },
  {
    surfaceId: 'l10:confirmation_posture',
    layer: L12DependencyLayer.L10,
    surfaceClass: L12DependencySurfaceClass.L10_CONFIRMATION_POSTURE,
    authorityClass: 'STABLE_HANDOFF',
    freshnessExpectation: 'NEAR_REAL_TIME',
    replayCompatible: true,
    stableHandoffRequired: true,
    restrictionAware: true,
    contradictionAware: false,
    regimePostureAware: false,
    sequencePostureAware: false,
    hypothesisPostureAware: true,
    scoreContextRequired: false,
    usableFor: ['HYPOTHESIS_CONDITIONING'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.L10_HYPOTHESIS_POSTURE_IGNORE],
    required: true,
    policyVersion: POLICY_V,
    description: 'L10 confirmation posture (stable handoff)',
  },
  {
    surfaceId: 'l10:invalidation_posture',
    layer: L12DependencyLayer.L10,
    surfaceClass: L12DependencySurfaceClass.L10_INVALIDATION_POSTURE,
    authorityClass: 'STABLE_HANDOFF',
    freshnessExpectation: 'NEAR_REAL_TIME',
    replayCompatible: true,
    stableHandoffRequired: true,
    restrictionAware: true,
    contradictionAware: false,
    regimePostureAware: false,
    sequencePostureAware: false,
    hypothesisPostureAware: true,
    scoreContextRequired: false,
    usableFor: ['HYPOTHESIS_CONDITIONING'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.ACTIVE_INVALIDATION_HIDE],
    required: true,
    policyVersion: POLICY_V,
    description: 'L10 invalidation posture — active invalidations must be surfaced',
  },
  {
    surfaceId: 'l10:shift_condition_set',
    layer: L12DependencyLayer.L10,
    surfaceClass: L12DependencySurfaceClass.L10_SHIFT_CONDITION_SET,
    authorityClass: 'STABLE_HANDOFF',
    freshnessExpectation: 'NEAR_REAL_TIME',
    replayCompatible: true,
    stableHandoffRequired: true,
    restrictionAware: true,
    contradictionAware: false,
    regimePostureAware: false,
    sequencePostureAware: false,
    hypothesisPostureAware: true,
    scoreContextRequired: false,
    usableFor: ['SHIFT_CONDITION_INPUT', 'HYPOTHESIS_CONDITIONING'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.HYPOTHESIS_REBUILD],
    required: false,
    policyVersion: POLICY_V,
    description: 'L10 shift condition set (stable handoff)',
  },
  {
    surfaceId: 'l10:hypothesis_restriction_profile',
    layer: L12DependencyLayer.L10,
    surfaceClass: L12DependencySurfaceClass.L10_HYPOTHESIS_RESTRICTION_PROFILE,
    authorityClass: 'STABLE_HANDOFF',
    freshnessExpectation: 'NEAR_REAL_TIME',
    replayCompatible: true,
    stableHandoffRequired: true,
    restrictionAware: true,
    contradictionAware: false,
    regimePostureAware: false,
    sequencePostureAware: false,
    hypothesisPostureAware: true,
    scoreContextRequired: false,
    usableFor: ['RESTRICTION_INPUT'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.L10_HYPOTHESIS_POSTURE_IGNORE],
    required: true,
    policyVersion: POLICY_V,
    description: 'L10 hypothesis restriction profile',
  },
  {
    surfaceId: 'l10:hypothesis_evidence_bundle',
    layer: L12DependencyLayer.L10,
    surfaceClass: L12DependencySurfaceClass.L10_HYPOTHESIS_EVIDENCE_BUNDLE,
    authorityClass: 'STABLE_HANDOFF',
    freshnessExpectation: 'ON_DEMAND',
    replayCompatible: true,
    stableHandoffRequired: true,
    restrictionAware: true,
    contradictionAware: false,
    regimePostureAware: false,
    sequencePostureAware: false,
    hypothesisPostureAware: true,
    scoreContextRequired: false,
    usableFor: ['EVIDENCE_ONLY'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.HYPOTHESIS_REBUILD],
    required: false,
    policyVersion: POLICY_V,
    description: 'L10 hypothesis evidence bundle',
  },

  // ── L11 — stable handoff only; score CONTEXT BUNDLE required ──
  {
    surfaceId: 'l11:current_score_snapshot',
    layer: L12DependencyLayer.L11,
    surfaceClass: L12DependencySurfaceClass.L11_CURRENT_SCORE_SNAPSHOT,
    authorityClass: 'STABLE_HANDOFF',
    freshnessExpectation: 'NEAR_REAL_TIME',
    replayCompatible: true,
    stableHandoffRequired: true,
    restrictionAware: true,
    contradictionAware: true,
    regimePostureAware: true,
    sequencePostureAware: true,
    hypothesisPostureAware: true,
    scoreContextRequired: true,
    usableFor: ['SCORE_CONTEXT_BUNDLE'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [
      L12ForbiddenAction.SCORE_REBUILD,
      L12ForbiddenAction.L11_SCORE_VALUE_ONLY_CONSUMPTION,
      L12ForbiddenAction.L11_SCORE_RESTRICTION_IGNORE,
    ],
    required: true,
    policyVersion: POLICY_V,
    description: 'L11 current score snapshot — context bundle required',
  },
  {
    surfaceId: 'l11:score_component_breakdown',
    layer: L12DependencyLayer.L11,
    surfaceClass: L12DependencySurfaceClass.L11_SCORE_COMPONENT_BREAKDOWN,
    authorityClass: 'STABLE_HANDOFF',
    freshnessExpectation: 'NEAR_REAL_TIME',
    replayCompatible: true,
    stableHandoffRequired: true,
    restrictionAware: true,
    contradictionAware: true,
    regimePostureAware: false,
    sequencePostureAware: false,
    hypothesisPostureAware: false,
    scoreContextRequired: true,
    usableFor: ['SCORE_CONTEXT_BUNDLE', 'EVIDENCE_ONLY'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.SCORE_REBUILD],
    required: true,
    policyVersion: POLICY_V,
    description: 'L11 score component breakdown — part of score-context bundle',
  },
  {
    surfaceId: 'l11:score_attribution',
    layer: L12DependencyLayer.L11,
    surfaceClass: L12DependencySurfaceClass.L11_SCORE_ATTRIBUTION,
    authorityClass: 'STABLE_HANDOFF',
    freshnessExpectation: 'NEAR_REAL_TIME',
    replayCompatible: true,
    stableHandoffRequired: true,
    restrictionAware: true,
    contradictionAware: true,
    regimePostureAware: false,
    sequencePostureAware: false,
    hypothesisPostureAware: false,
    scoreContextRequired: true,
    usableFor: ['SCORE_CONTEXT_BUNDLE', 'EVIDENCE_ONLY'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.L11_SCORE_VALUE_ONLY_CONSUMPTION],
    required: true,
    policyVersion: POLICY_V,
    description: 'L11 score attribution — part of score-context bundle',
  },
  {
    surfaceId: 'l11:score_missing_data_profile',
    layer: L12DependencyLayer.L11,
    surfaceClass: L12DependencySurfaceClass.L11_SCORE_MISSING_DATA_PROFILE,
    authorityClass: 'STABLE_HANDOFF',
    freshnessExpectation: 'NEAR_REAL_TIME',
    replayCompatible: true,
    stableHandoffRequired: true,
    restrictionAware: true,
    contradictionAware: true,
    regimePostureAware: false,
    sequencePostureAware: false,
    hypothesisPostureAware: false,
    scoreContextRequired: true,
    usableFor: ['SCORE_CONTEXT_BUNDLE'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.MISSING_VISIBILITY_HIDE],
    required: true,
    policyVersion: POLICY_V,
    description: 'L11 score missing-data profile — part of score-context bundle',
  },
  {
    surfaceId: 'l11:score_modifier_profile',
    layer: L12DependencyLayer.L11,
    surfaceClass: L12DependencySurfaceClass.L11_SCORE_MODIFIER_PROFILE,
    authorityClass: 'STABLE_HANDOFF',
    freshnessExpectation: 'NEAR_REAL_TIME',
    replayCompatible: true,
    stableHandoffRequired: true,
    restrictionAware: true,
    contradictionAware: false,
    regimePostureAware: true,
    sequencePostureAware: true,
    hypothesisPostureAware: true,
    scoreContextRequired: true,
    usableFor: ['SCORE_CONTEXT_BUNDLE'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.L11_SCORE_VALUE_ONLY_CONSUMPTION],
    required: true,
    policyVersion: POLICY_V,
    description: 'L11 score modifier profile — part of score-context bundle',
  },
  {
    surfaceId: 'l11:score_calibration_hook',
    layer: L12DependencyLayer.L11,
    surfaceClass: L12DependencySurfaceClass.L11_SCORE_CALIBRATION_HOOK,
    authorityClass: 'STABLE_HANDOFF',
    freshnessExpectation: 'ON_DEMAND',
    replayCompatible: true,
    stableHandoffRequired: true,
    restrictionAware: true,
    contradictionAware: false,
    regimePostureAware: false,
    sequencePostureAware: false,
    hypothesisPostureAware: false,
    scoreContextRequired: true,
    usableFor: ['SCORE_CONTEXT_BUNDLE'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.L11_SCORE_VALUE_ONLY_CONSUMPTION],
    required: true,
    policyVersion: POLICY_V,
    description: 'L11 score calibration hook — part of score-context bundle',
  },
  {
    surfaceId: 'l11:score_drift_report',
    layer: L12DependencyLayer.L11,
    surfaceClass: L12DependencySurfaceClass.L11_SCORE_DRIFT_REPORT,
    authorityClass: 'STABLE_HANDOFF',
    freshnessExpectation: 'NEAR_REAL_TIME',
    replayCompatible: true,
    stableHandoffRequired: true,
    restrictionAware: true,
    contradictionAware: false,
    regimePostureAware: false,
    sequencePostureAware: false,
    hypothesisPostureAware: false,
    scoreContextRequired: true,
    usableFor: ['SCORE_CONTEXT_BUNDLE'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.DRIFT_STATUS_HIDE],
    required: true,
    policyVersion: POLICY_V,
    description: 'L11 score drift report — part of score-context bundle',
  },
  {
    surfaceId: 'l11:score_restriction_profile',
    layer: L12DependencyLayer.L11,
    surfaceClass: L12DependencySurfaceClass.L11_SCORE_RESTRICTION_PROFILE,
    authorityClass: 'STABLE_HANDOFF',
    freshnessExpectation: 'NEAR_REAL_TIME',
    replayCompatible: true,
    stableHandoffRequired: true,
    restrictionAware: true,
    contradictionAware: false,
    regimePostureAware: false,
    sequencePostureAware: false,
    hypothesisPostureAware: false,
    scoreContextRequired: true,
    usableFor: ['SCORE_CONTEXT_BUNDLE', 'RESTRICTION_INPUT'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.L11_SCORE_RESTRICTION_IGNORE],
    required: true,
    policyVersion: POLICY_V,
    description: 'L11 score restriction profile — part of score-context bundle',
  },
  {
    surfaceId: 'l11:score_evidence_bundle',
    layer: L12DependencyLayer.L11,
    surfaceClass: L12DependencySurfaceClass.L11_SCORE_EVIDENCE_BUNDLE,
    authorityClass: 'STABLE_HANDOFF',
    freshnessExpectation: 'ON_DEMAND',
    replayCompatible: true,
    stableHandoffRequired: true,
    restrictionAware: true,
    contradictionAware: false,
    regimePostureAware: false,
    sequencePostureAware: false,
    hypothesisPostureAware: false,
    scoreContextRequired: true,
    usableFor: ['SCORE_CONTEXT_BUNDLE', 'EVIDENCE_ONLY'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.SCORE_REBUILD],
    required: true,
    policyVersion: POLICY_V,
    description: 'L11 score evidence bundle — part of score-context bundle',
  },
  {
    surfaceId: 'l11:score_lineage',
    layer: L12DependencyLayer.L11,
    surfaceClass: L12DependencySurfaceClass.L11_SCORE_LINEAGE,
    authorityClass: 'STABLE_HANDOFF',
    freshnessExpectation: 'ON_DEMAND',
    replayCompatible: true,
    stableHandoffRequired: true,
    restrictionAware: true,
    contradictionAware: false,
    regimePostureAware: false,
    sequencePostureAware: false,
    hypothesisPostureAware: false,
    scoreContextRequired: true,
    usableFor: ['SCORE_CONTEXT_BUNDLE', 'LINEAGE_REFERENCE'],
    legalConsumptionContexts: STD_CTX,
    forbiddenUseCases: [L12ForbiddenAction.SCORE_REBUILD],
    required: true,
    policyVersion: POLICY_V,
    description: 'L11 score lineage — part of score-context bundle',
  },
];

/**
 * §12.1.5.9 — The L11 score-context bundle. A scenario must consume
 * ALL of these surfaces; consuming `current_score_snapshot` alone is
 * an L12C_L11_SCORE_VALUE_ONLY violation.
 */
export const L11_SCORE_CONTEXT_BUNDLE_SURFACE_IDS: readonly string[] = [
  'l11:current_score_snapshot',
  'l11:score_component_breakdown',
  'l11:score_attribution',
  'l11:score_missing_data_profile',
  'l11:score_modifier_profile',
  'l11:score_calibration_hook',
  'l11:score_drift_report',
  'l11:score_restriction_profile',
  'l11:score_evidence_bundle',
  'l11:score_lineage',
];

export function getL12DependencySurface(
  surfaceId: string,
): L12DependencySurfaceDescriptor | undefined {
  return L12_DEPENDENCY_SURFACES.find(s => s.surfaceId === surfaceId);
}

export function isL12RegisteredDependency(surfaceId: string): boolean {
  return L12_DEPENDENCY_SURFACES.some(s => s.surfaceId === surfaceId);
}

export function getL12SurfacesForLayer(
  layer: L12DependencyLayer,
): readonly L12DependencySurfaceDescriptor[] {
  return L12_DEPENDENCY_SURFACES.filter(s => s.layer === layer);
}

export function getL12SurfacesUsableFor(
  usage: L12DependencyUsability,
): readonly L12DependencySurfaceDescriptor[] {
  return L12_DEPENDENCY_SURFACES.filter(s => s.usableFor.includes(usage));
}

export function isL12UsableFor(
  surfaceId: string,
  usage: L12DependencyUsability,
): boolean {
  const s = getL12DependencySurface(surfaceId);
  if (!s) return false;
  return s.usableFor.includes(usage);
}

export function getL12RequiredDependencySurfaces():
  readonly L12DependencySurfaceDescriptor[] {
  return L12_DEPENDENCY_SURFACES.filter(s => s.required);
}

export function getL12RestrictionAwareSurfaces():
  readonly L12DependencySurfaceDescriptor[] {
  return L12_DEPENDENCY_SURFACES.filter(s => s.restrictionAware);
}

export function getL12RegimePostureAwareSurfaces():
  readonly L12DependencySurfaceDescriptor[] {
  return L12_DEPENDENCY_SURFACES.filter(s => s.regimePostureAware);
}

export function getL12SequencePostureAwareSurfaces():
  readonly L12DependencySurfaceDescriptor[] {
  return L12_DEPENDENCY_SURFACES.filter(s => s.sequencePostureAware);
}

export function getL12HypothesisPostureAwareSurfaces():
  readonly L12DependencySurfaceDescriptor[] {
  return L12_DEPENDENCY_SURFACES.filter(s => s.hypothesisPostureAware);
}

export function getL12ScoreContextSurfaces():
  readonly L12DependencySurfaceDescriptor[] {
  return L12_DEPENDENCY_SURFACES.filter(s => s.scoreContextRequired);
}
