/**
 * L12.2 — Scenario summary code (compact path label).
 *
 * Summary codes are a finite, governed vocabulary used to label a scenario
 * path inside its scenario object. They are NOT predictions, NOT
 * recommendations, NOT trade actions. Every code is conditional in nature.
 */

export enum L12ScenarioSummaryCode {
  BASE_CASE_LEVERAGE_DRIVEN = 'BASE_CASE_LEVERAGE_DRIVEN',
  BASE_CASE_SPOT_LED = 'BASE_CASE_SPOT_LED',
  BASE_CASE_CHOP = 'BASE_CASE_CHOP',
  BASE_CASE_POST_UNLOCK = 'BASE_CASE_POST_UNLOCK',

  BULLISH_CONTINUATION_SPOT_LED = 'BULLISH_CONTINUATION_SPOT_LED',
  BULLISH_CONTINUATION_LEVERAGE_LED = 'BULLISH_CONTINUATION_LEVERAGE_LED',
  BULLISH_CONTINUATION_RECOVERY = 'BULLISH_CONTINUATION_RECOVERY',
  BULLISH_CONTINUATION_NARRATIVE = 'BULLISH_CONTINUATION_NARRATIVE',

  BEARISH_FAILURE_THIN_LIQUIDITY = 'BEARISH_FAILURE_THIN_LIQUIDITY',
  BEARISH_FAILURE_DISTRIBUTION = 'BEARISH_FAILURE_DISTRIBUTION',
  BEARISH_FAILURE_RISK_OFF = 'BEARISH_FAILURE_RISK_OFF',
  BEARISH_FAILURE_HYPOTHESIS_FLIP = 'BEARISH_FAILURE_HYPOTHESIS_FLIP',

  STRESS_LEVERAGE_CASCADE = 'STRESS_LEVERAGE_CASCADE',
  STRESS_LIQUIDITY_DISLOCATION = 'STRESS_LIQUIDITY_DISLOCATION',
  STRESS_RISK_OFF_BREAK = 'STRESS_RISK_OFF_BREAK',

  RECOVERY_POST_UNLOCK = 'RECOVERY_POST_UNLOCK',
  RECOVERY_REACCUMULATION = 'RECOVERY_REACCUMULATION',
  RECOVERY_LIQUIDITY_RESTORATION = 'RECOVERY_LIQUIDITY_RESTORATION',

  INVALIDATION_SUPPORT_FAILURE = 'INVALIDATION_SUPPORT_FAILURE',
  INVALIDATION_REGIME_SHIFT = 'INVALIDATION_REGIME_SHIFT',
  INVALIDATION_HYPOTHESIS_FLIP = 'INVALIDATION_HYPOTHESIS_FLIP',
  INVALIDATION_CONTRADICTION_ESCALATION = 'INVALIDATION_CONTRADICTION_ESCALATION',

  NEUTRAL_CHOP_NO_DECISION = 'NEUTRAL_CHOP_NO_DECISION',

  INSUFFICIENT_DATA_NARROWED = 'INSUFFICIENT_DATA_NARROWED',
  INSUFFICIENT_DATA_BLOCKED = 'INSUFFICIENT_DATA_BLOCKED',
}

export const ALL_L12_SCENARIO_SUMMARY_CODES: readonly L12ScenarioSummaryCode[] =
  Object.values(L12ScenarioSummaryCode);
