/**
 * L14.1 — Forbidden Action Registry
 *
 * §14.1.8 — Frozen set of forbidden actions plus the canonical
 * mapping from forbidden-action → constitutional violation code.
 */

import {
  ALL_L14_FORBIDDEN_ACTIONS,
  L14ForbiddenAction,
} from '../contracts/l14-forbidden-actions';
import {
  L14ConstitutionalViolationCode as C,
} from '../contracts/l14-violation-codes';

const FORBIDDEN: ReadonlySet<L14ForbiddenAction> =
  new Set(ALL_L14_FORBIDDEN_ACTIONS);

export function l14ActionIsForbidden(a: L14ForbiddenAction): boolean {
  return FORBIDDEN.has(a);
}

export const L14_FORBIDDEN_ACTION_TO_CODE:
  Readonly<Record<L14ForbiddenAction, C>> = {
  [L14ForbiddenAction.REBUILD_L10_HYPOTHESIS]: C.L14C_L10_HYPOTHESIS_REBUILD_ATTEMPT,
  [L14ForbiddenAction.REBUILD_L11_SCORE]: C.L14C_L11_SCORE_REBUILD_ATTEMPT,
  [L14ForbiddenAction.REBUILD_L12_SCENARIO]: C.L14C_L12_SCENARIO_REBUILD_ATTEMPT,
  [L14ForbiddenAction.REBUILD_L13_EXPLANATION]: C.L14C_L13_EXPLANATION_REBUILD_ATTEMPT,
  [L14ForbiddenAction.TREAT_OPEN_RATE_AS_CORRECTNESS]: C.L14C_OPEN_RATE_AS_CORRECTNESS,
  [L14ForbiddenAction.TREAT_CLICK_RATE_AS_CORRECTNESS]: C.L14C_CLICK_RATE_AS_CORRECTNESS,
  [L14ForbiddenAction.TREAT_SAVE_RATE_AS_CORRECTNESS]: C.L14C_ENGAGEMENT_AS_TRUTH,
  [L14ForbiddenAction.TREAT_FEEDBACK_AS_AUTOMATIC_TRUTH]: C.L14C_FEEDBACK_AS_AUTOMATIC_TRUTH,
  [L14ForbiddenAction.SILENTLY_MUTATE_L11_FORMULA]: C.L14C_SILENT_LOWER_LAYER_MUTATION,
  [L14ForbiddenAction.SILENTLY_MUTATE_L11_THRESHOLD]: C.L14C_AUTO_THRESHOLD_MUTATION,
  [L14ForbiddenAction.SILENTLY_MUTATE_L12_SCENARIO_TEMPLATE]: C.L14C_AUTO_SCENARIO_TEMPLATE_MUTATION,
  [L14ForbiddenAction.SILENTLY_MUTATE_L13_GROUNDING_POLICY]: C.L14C_AUTO_L13_POLICY_MUTATION,
  [L14ForbiddenAction.SILENTLY_MUTATE_L13_SAFETY_POLICY]: C.L14C_AUTO_L13_POLICY_MUTATION,
  [L14ForbiddenAction.HIDE_OUTCOME_MISALIGNMENT]: C.L14C_OUTCOME_MISALIGNMENT_HIDDEN,
  [L14ForbiddenAction.HIDE_FALSE_POSITIVE_PATTERN]: C.L14C_FALSE_POSITIVE_HIDDEN,
  [L14ForbiddenAction.HIDE_FALSE_NEGATIVE_PATTERN]: C.L14C_FALSE_POSITIVE_HIDDEN,
  [L14ForbiddenAction.HIDE_CONFIDENCE_OVERSTATEMENT]: C.L14C_CONFIDENCE_OVERSTATEMENT_HIDDEN,
  [L14ForbiddenAction.DELIVER_UNGOVERNED_SOURCE_ARTIFACT]: C.L14C_DELIVERY_SOURCE_UNGOVERNED,
  [L14ForbiddenAction.DELIVERY_BYPASSES_RESTRICTION_PROFILE]: C.L14C_DELIVERY_BYPASSES_RESTRICTION,
  [L14ForbiddenAction.DELIVERY_BYPASSES_CHANNEL_ENTITLEMENT]: C.L14C_DELIVERY_BYPASSES_RESTRICTION,
  [L14ForbiddenAction.DELIVERY_REWRITES_SOURCE_MEANING]: C.L14C_DELIVERY_REWRITES_SOURCE_MEANING,
  [L14ForbiddenAction.CALIBRATION_PROPOSAL_AUTO_APPLIED]: C.L14C_CALIBRATION_PROPOSAL_AUTO_APPLY,
  [L14ForbiddenAction.CALIBRATION_EVIDENCE_WITHOUT_LINEAGE]: C.L14C_CALIBRATION_EVIDENCE_WITHOUT_LINEAGE,
  [L14ForbiddenAction.OUTCOME_EVALUATION_WITHOUT_DECLARED_HORIZON]: C.L14C_EVALUATION_WITHOUT_HORIZON,
  [L14ForbiddenAction.DIRECT_RAW_LOWER_LAYER_READ]: C.L14C_RAW_LOWER_LAYER_REBUILD_ATTEMPT,
  [L14ForbiddenAction.DIRECT_PERSISTENCE_BYPASS_L5]: C.L14C_OUTPUT_SURFACE_L5_ROUTE_MISSING,
  [L14ForbiddenAction.ENGAGEMENT_AS_TRUTH_SEMANTIC_LEAK]: C.L14C_ENGAGEMENT_AS_TRUTH,
  [L14ForbiddenAction.FEEDBACK_AS_TRUTH_SEMANTIC_LEAK]: C.L14C_FEEDBACK_AS_AUTOMATIC_TRUTH,
};

export function codeForL14ForbiddenAction(a: L14ForbiddenAction): C {
  return L14_FORBIDDEN_ACTION_TO_CODE[a];
}
