/**
 * L9.6 — Family / Template Violation Codes
 *
 * §9.6.13.2 — Typed violation codes for every L9.6 validator. Disjoint
 * from the L9.1 constitutional (`L9_`), L9.2 object (`L9O_`), L9.3
 * contract (`L9C_`), L9.4 runtime (`L9R_`), and L9.5 temporal-semantic
 * (`L9T_`) code spaces so audit records unambiguously identify the
 * tier rejecting an interpretation. L9.6 uses the `L9F_` prefix
 * (family / template).
 */

/**
 * §9.6.13.2 — `L9FamilyViolationCode` enum (the plan's name).
 */
export enum L9FamilyViolationCode {
  // ── Family-definition law (§9.6.3) ──
  FAM_UNREGISTERED = 'L9F_FAM_UNREGISTERED',
  FAM_DUPLICATE = 'L9F_FAM_DUPLICATE',
  FAM_PRIMARY_TAXONOMY_MISSING = 'L9F_FAM_PRIMARY_TAXONOMY_MISSING',
  FAM_PRIMARY_TAXONOMY_INVALID = 'L9F_FAM_PRIMARY_TAXONOMY_INVALID',
  FAM_SECONDARY_TAXONOMY_INVALID = 'L9F_FAM_SECONDARY_TAXONOMY_INVALID',
  FAM_LEGAL_SCOPES_EMPTY = 'L9F_FAM_LEGAL_SCOPES_EMPTY',
  FAM_LEGAL_SCOPE_UNREGISTERED = 'L9F_FAM_LEGAL_SCOPE_UNREGISTERED',
  FAM_STATE_OWNERSHIP_EMPTY = 'L9F_FAM_STATE_OWNERSHIP_EMPTY',
  FAM_STATE_UNREGISTERED = 'L9F_FAM_STATE_UNREGISTERED',
  FAM_TEMPLATE_UNREGISTERED = 'L9F_FAM_TEMPLATE_UNREGISTERED',
  FAM_TEMPLATE_DUPLICATE_ACROSS_FAMILIES =
    'L9F_FAM_TEMPLATE_DUPLICATE_ACROSS_FAMILIES',
  FAM_POST_EVENT_ANCHORS_REQUIRED_MISSING =
    'L9F_FAM_POST_EVENT_ANCHORS_REQUIRED_MISSING',
  FAM_POST_EVENT_ANCHORS_ILLEGAL_FOR_FAMILY =
    'L9F_FAM_POST_EVENT_ANCHORS_ILLEGAL_FOR_FAMILY',
  FAM_REGIME_REQUIREMENT_MISSING = 'L9F_FAM_REGIME_REQUIREMENT_MISSING',
  FAM_ROLLOUT_PHASE_MISMATCH = 'L9F_FAM_ROLLOUT_PHASE_MISMATCH',
  FAM_CONFIDENCE_CAP_OUT_OF_RANGE = 'L9F_FAM_CONFIDENCE_CAP_OUT_OF_RANGE',
  FAM_COEXISTENCE_WITH_SELF = 'L9F_FAM_COEXISTENCE_WITH_SELF',
  FAM_COEXISTENCE_WITH_UNKNOWN_FAMILY =
    'L9F_FAM_COEXISTENCE_WITH_UNKNOWN_FAMILY',
  FAM_LEAKAGE_JUDGMENT = 'L9F_FAM_LEAKAGE_JUDGMENT',

  // ── Template-definition law (§9.6.4) ──
  TPL_UNREGISTERED = 'L9F_TPL_UNREGISTERED',
  TPL_DUPLICATE = 'L9F_TPL_DUPLICATE',
  TPL_FAMILY_MISMATCH = 'L9F_TPL_FAMILY_MISMATCH',
  TPL_PRIMARY_STATE_NOT_OWNED = 'L9F_TPL_PRIMARY_STATE_NOT_OWNED',
  TPL_VERSION_MISSING = 'L9F_TPL_VERSION_MISSING',
  TPL_APPLICABLE_SCOPES_EMPTY = 'L9F_TPL_APPLICABLE_SCOPES_EMPTY',
  TPL_SCOPE_NOT_LEGAL_FOR_FAMILY = 'L9F_TPL_SCOPE_NOT_LEGAL_FOR_FAMILY',
  TPL_SUPPORT_DOMAINS_EMPTY = 'L9F_TPL_SUPPORT_DOMAINS_EMPTY',
  TPL_CHALLENGE_DOMAINS_EMPTY = 'L9F_TPL_CHALLENGE_DOMAINS_EMPTY',
  TPL_LEAD_LAG_REQUIREMENT_MISSING = 'L9F_TPL_LEAD_LAG_REQUIREMENT_MISSING',
  TPL_PHASE_REQUIREMENT_MISSING = 'L9F_TPL_PHASE_REQUIREMENT_MISSING',
  TPL_PHASE_NOT_IN_FAMILY_ENVELOPE = 'L9F_TPL_PHASE_NOT_IN_FAMILY_ENVELOPE',
  TPL_DECAY_REQUIREMENT_MISSING = 'L9F_TPL_DECAY_REQUIREMENT_MISSING',
  TPL_DECAY_EXCEEDS_FAMILY_CEILING = 'L9F_TPL_DECAY_EXCEEDS_FAMILY_CEILING',
  TPL_CONTRADICTION_REQUIREMENT_MISSING =
    'L9F_TPL_CONTRADICTION_REQUIREMENT_MISSING',
  TPL_POST_EVENT_REQUIREMENT_MISSING =
    'L9F_TPL_POST_EVENT_REQUIREMENT_MISSING',
  TPL_POST_EVENT_ANCHOR_ILLEGAL_FOR_FAMILY =
    'L9F_TPL_POST_EVENT_ANCHOR_ILLEGAL_FOR_FAMILY',
  TPL_REGIME_REQUIREMENT_MISSING = 'L9F_TPL_REGIME_REQUIREMENT_MISSING',
  TPL_CLEAN_EMISSION_MISSING = 'L9F_TPL_CLEAN_EMISSION_MISSING',
  TPL_CLEAN_COMPLETENESS_OUT_OF_RANGE =
    'L9F_TPL_CLEAN_COMPLETENESS_OUT_OF_RANGE',
  TPL_CLEAN_SUPPORT_COVERAGE_OUT_OF_RANGE =
    'L9F_TPL_CLEAN_SUPPORT_COVERAGE_OUT_OF_RANGE',
  TPL_ROLLOUT_PRIORITY_MISMATCH = 'L9F_TPL_ROLLOUT_PRIORITY_MISMATCH',
  TPL_LEAKAGE_JUDGMENT = 'L9F_TPL_LEAKAGE_JUDGMENT',

  // ── Rollout law (§9.6.10) ──
  ROLL_OWNING_STATES_NOT_REGISTERED = 'L9F_ROLL_OWNING_STATES_NOT_REGISTERED',
  ROLL_TEMPLATES_INCOMPLETE = 'L9F_ROLL_TEMPLATES_INCOMPLETE',
  ROLL_CONTRADICTION_HOOKUP_MISSING = 'L9F_ROLL_CONTRADICTION_HOOKUP_MISSING',
  ROLL_REGIME_CONSUMPTION_ILLEGAL = 'L9F_ROLL_REGIME_CONSUMPTION_ILLEGAL',
  ROLL_CERTIFICATION_NOT_GREEN = 'L9F_ROLL_CERTIFICATION_NOT_GREEN',
  ROLL_FAMILY_STATE_COLLISION = 'L9F_ROLL_FAMILY_STATE_COLLISION',
  ROLL_PHASE_ORDER_VIOLATED = 'L9F_ROLL_PHASE_ORDER_VIOLATED',

  // ── State-legality law (§9.6.2.4 / §9.6.2.5) ──
  STATE_NOT_OWNED_BY_FAMILY = 'L9F_STATE_NOT_OWNED_BY_FAMILY',
  STATE_SCOPE_ILLEGAL_FOR_FAMILY = 'L9F_STATE_SCOPE_ILLEGAL_FOR_FAMILY',
  STATE_PHASE_OUT_OF_FAMILY_ENVELOPE = 'L9F_STATE_PHASE_OUT_OF_FAMILY_ENVELOPE',
  STATE_LEAD_LAG_POSTURE_MISSING = 'L9F_STATE_LEAD_LAG_POSTURE_MISSING',
  STATE_POST_EVENT_ANCHOR_MISSING = 'L9F_STATE_POST_EVENT_ANCHOR_MISSING',
  STATE_BLOCKER_PRESENT_CLEAN_CLAIMED =
    'L9F_STATE_BLOCKER_PRESENT_CLEAN_CLAIMED',
  STATE_DECAY_EXCEEDS_TEMPLATE_TOLERANCE =
    'L9F_STATE_DECAY_EXCEEDS_TEMPLATE_TOLERANCE',
  STATE_AMBIGUITY_UNRESOLVED_CLEAN_CLAIMED =
    'L9F_STATE_AMBIGUITY_UNRESOLVED_CLEAN_CLAIMED',
  STATE_HOSTILE_REGIME_CLEAN_CLAIMED = 'L9F_STATE_HOSTILE_REGIME_CLEAN_CLAIMED',
  STATE_SUPPORT_COVERAGE_BELOW_MINIMUM =
    'L9F_STATE_SUPPORT_COVERAGE_BELOW_MINIMUM',
  STATE_COMPLETENESS_BELOW_MINIMUM = 'L9F_STATE_COMPLETENESS_BELOW_MINIMUM',
  STATE_ACTIVE_SHOCK_BLOCKS_CLEAN = 'L9F_STATE_ACTIVE_SHOCK_BLOCKS_CLEAN',
  STATE_CAUSAL_LEAK = 'L9F_STATE_CAUSAL_LEAK',
}

export const ALL_L9_FAMILY_VIOLATION_CODES:
  readonly L9FamilyViolationCode[] =
    Object.values(L9FamilyViolationCode);

/**
 * §9.6.13.2 — Semantic tier label for family/template violations.
 * Parallels `L9TemporalSemanticTier` from L9.5.
 */
export enum L9FamilyViolationTier {
  FAMILY = 'FAMILY',
  TEMPLATE = 'TEMPLATE',
  ROLLOUT = 'ROLLOUT',
  STATE_LEGALITY = 'STATE_LEGALITY',
}

export const ALL_L9_FAMILY_VIOLATION_TIERS:
  readonly L9FamilyViolationTier[] =
    Object.values(L9FamilyViolationTier);

export interface L9FamilyViolation {
  readonly code: L9FamilyViolationCode;
  readonly tier: L9FamilyViolationTier;
  readonly detail: string;
  readonly offending_refs?: readonly string[];
}

export class L9FamilyValidationError extends Error {
  constructor(public readonly violations: readonly L9FamilyViolation[]) {
    super(
      `L9.6 family/template validation failed with ${violations.length} ` +
        `violation(s): ${violations.map(v => v.code).join(', ')}`,
    );
    this.name = 'L9FamilyValidationError';
  }
}
