/**
 * L9.4 — Runtime Violation Codes
 *
 * §9.4.9.1 / §9.4.18.1 — `L9RuntimeViolationCode`. Disjoint from the
 * L9.1 boundary codes (`L9C_*` — constitutional), L9.2 object codes,
 * and L9.3 contract codes (`L9C_*` — contract) so that an audit
 * record's tier is unambiguous from its violation code alone.
 *
 * Every code begins with the prefix `L9R_` to identify the runtime
 * tier of Layer 9.
 */

export enum L9RuntimeViolationCode {
  // ── DAG legality (§9.4.2) ──
  DAG_ILLEGAL_NODE_CLASS = 'L9R_DAG_ILLEGAL_NODE_CLASS',
  DAG_ILLEGAL_EDGE_CLASS = 'L9R_DAG_ILLEGAL_EDGE_CLASS',
  DAG_ILLEGAL_EDGE_TRANSITION = 'L9R_DAG_ILLEGAL_EDGE_TRANSITION',
  DAG_NODE_STAGE_MISMATCH = 'L9R_DAG_NODE_STAGE_MISMATCH',
  DAG_CYCLE_DETECTED = 'L9R_DAG_CYCLE_DETECTED',
  DAG_UNRESOLVED_DEPENDENCY = 'L9R_DAG_UNRESOLVED_DEPENDENCY',
  DAG_MISSING_TERMINAL_NODE = 'L9R_DAG_MISSING_TERMINAL_NODE',
  DAG_NON_DETERMINISTIC_ORDER = 'L9R_DAG_NON_DETERMINISTIC_ORDER',
  DAG_DUPLICATE_NODE_ID = 'L9R_DAG_DUPLICATE_NODE_ID',
  DAG_ORPHAN_CLASSIFICATION = 'L9R_DAG_ORPHAN_CLASSIFICATION',
  DAG_INPUT_TO_CLASSIFICATION_JUMP = 'L9R_DAG_INPUT_TO_CLASSIFICATION_JUMP',
  DAG_ORDERED_SIGNAL_TO_MATERIALIZATION_JUMP = 'L9R_DAG_ORDERED_SIGNAL_TO_MATERIALIZATION_JUMP',
  DAG_LEAD_LAG_TO_MATERIALIZATION_JUMP = 'L9R_DAG_LEAD_LAG_TO_MATERIALIZATION_JUMP',
  DAG_DECAY_TO_SUBJECT_BACKEDGE = 'L9R_DAG_DECAY_TO_SUBJECT_BACKEDGE',
  DAG_CONFIDENCE_TO_ORDERED_SIGNAL_BACKEDGE = 'L9R_DAG_CONFIDENCE_TO_ORDERED_SIGNAL_BACKEDGE',
  DAG_RESTRICTION_TO_PHASE_BACKEDGE = 'L9R_DAG_RESTRICTION_TO_PHASE_BACKEDGE',
  DAG_CLASSIFICATION_BEFORE_CHAIN = 'L9R_DAG_CLASSIFICATION_BEFORE_CHAIN',
  DAG_DECAY_BEFORE_CHANGE_POINT = 'L9R_DAG_DECAY_BEFORE_CHANGE_POINT',
  DAG_POST_EVENT_WITHOUT_CHANGE_POINT = 'L9R_DAG_POST_EVENT_WITHOUT_CHANGE_POINT',

  // ── Run lineage (§9.4.2.7-8) ──
  RUN_LINEAGE_MISSING = 'L9R_RUN_LINEAGE_MISSING',
  RUN_MODE_MISSING = 'L9R_RUN_MODE_MISSING',
  RUN_ENGINE_SET_INCOMPLETE = 'L9R_RUN_ENGINE_SET_INCOMPLETE',
  RUN_DETERMINISM_BROKEN = 'L9R_RUN_DETERMINISM_BROKEN',
  RUN_PARENT_REQUIRED = 'L9R_RUN_PARENT_REQUIRED',
  RUN_TEMPLATE_SET_INCOMPLETE = 'L9R_RUN_TEMPLATE_SET_INCOMPLETE',

  // ── Subject assembly (§9.4.5) ──
  ASSEMBLY_UNREGISTERED_FAMILY = 'L9R_ASSEMBLY_UNREGISTERED_FAMILY',
  ASSEMBLY_UNREGISTERED_TEMPLATE = 'L9R_ASSEMBLY_UNREGISTERED_TEMPLATE',
  ASSEMBLY_ILLEGAL_SCOPE_BINDING = 'L9R_ASSEMBLY_ILLEGAL_SCOPE_BINDING',
  ASSEMBLY_FAMILY_SCOPE_ILLEGAL = 'L9R_ASSEMBLY_FAMILY_SCOPE_ILLEGAL',
  ASSEMBLY_LINEAGE_INCOMPLETE = 'L9R_ASSEMBLY_LINEAGE_INCOMPLETE',
  ASSEMBLY_CONTRACT_INCOMPLETE = 'L9R_ASSEMBLY_CONTRACT_INCOMPLETE',
  ASSEMBLY_JUDGMENT_LEAK = 'L9R_ASSEMBLY_JUDGMENT_LEAK',
  ASSEMBLY_NON_DETERMINISTIC_ID = 'L9R_ASSEMBLY_NON_DETERMINISTIC_ID',
  ASSEMBLY_POST_EVENT_ANCHOR_REQUIREMENT_MISSING =
    'L9R_ASSEMBLY_POST_EVENT_ANCHOR_REQUIREMENT_MISSING',
  ASSEMBLY_REGIME_REQUIREMENT_MISSING = 'L9R_ASSEMBLY_REGIME_REQUIREMENT_MISSING',
  ASSEMBLY_TEMPORAL_WINDOW_MISSING = 'L9R_ASSEMBLY_TEMPORAL_WINDOW_MISSING',

  // ── Temporal input resolution (§9.4.6) ──
  INPUT_UNREGISTERED_SURFACE = 'L9R_INPUT_UNREGISTERED_SURFACE',
  INPUT_RAW_UNGATED = 'L9R_INPUT_RAW_UNGATED',
  INPUT_STALE_MASQUERADING_CURRENT = 'L9R_INPUT_STALE_MASQUERADING_CURRENT',
  INPUT_MISSING_REQUIRED_VALIDATION = 'L9R_INPUT_MISSING_REQUIRED_VALIDATION',
  INPUT_MISSING_REQUIRED_EVENT = 'L9R_INPUT_MISSING_REQUIRED_EVENT',
  INPUT_MISSING_REQUIRED_FEATURE = 'L9R_INPUT_MISSING_REQUIRED_FEATURE',
  INPUT_EVIDENCE_ONLY_USED_AS_HARD = 'L9R_INPUT_EVIDENCE_ONLY_USED_AS_HARD',
  INPUT_RESTRICTION_BYPASS = 'L9R_INPUT_RESTRICTION_BYPASS',
  INPUT_BLOCKED_VALIDATION_ACCEPTED = 'L9R_INPUT_BLOCKED_VALIDATION_ACCEPTED',
  INPUT_REGIME_OMITTED_WHERE_REQUIRED = 'L9R_INPUT_REGIME_OMITTED_WHERE_REQUIRED',
  INPUT_READINESS_INCONSISTENT = 'L9R_INPUT_READINESS_INCONSISTENT',
  INPUT_HISTORICAL_WITHOUT_WINDOW = 'L9R_INPUT_HISTORICAL_WITHOUT_WINDOW',

  // ── Ordered-signal resolution (§9.4.7) ──
  ORDERED_SIGNAL_MISSING_EVIDENCE = 'L9R_ORDERED_SIGNAL_MISSING_EVIDENCE',
  ORDERED_SIGNAL_FALSE_CLEAN_ORDER = 'L9R_ORDERED_SIGNAL_FALSE_CLEAN_ORDER',
  ORDERED_SIGNAL_LATE_AS_INITIATOR = 'L9R_ORDERED_SIGNAL_LATE_AS_INITIATOR',
  ORDERED_SIGNAL_EVIDENCE_ONLY_AS_NODE = 'L9R_ORDERED_SIGNAL_EVIDENCE_ONLY_AS_NODE',
  ORDERED_SIGNAL_POST_EVENT_AS_PRE_EVENT = 'L9R_ORDERED_SIGNAL_POST_EVENT_AS_PRE_EVENT',
  ORDERED_SIGNAL_STALE_AS_FRESH_ANCHOR = 'L9R_ORDERED_SIGNAL_STALE_AS_FRESH_ANCHOR',
  ORDERED_SIGNAL_ROLE_MISSING = 'L9R_ORDERED_SIGNAL_ROLE_MISSING',
  ORDERED_SIGNAL_NON_DETERMINISTIC_ORDER = 'L9R_ORDERED_SIGNAL_NON_DETERMINISTIC_ORDER',
  ORDERED_SIGNAL_AMBIGUITY_ERASED = 'L9R_ORDERED_SIGNAL_AMBIGUITY_ERASED',

  // ── Lead-lag runtime (§9.4.8) ──
  LEAD_LAG_NEGATIVE_DURATION = 'L9R_LEAD_LAG_NEGATIVE_DURATION',
  LEAD_LAG_WITHOUT_ORDERING_EVIDENCE = 'L9R_LEAD_LAG_WITHOUT_ORDERING_EVIDENCE',
  LEAD_LAG_CAUSAL_WITHOUT_RESTRAINT = 'L9R_LEAD_LAG_CAUSAL_WITHOUT_RESTRAINT',
  LEAD_LAG_IGNORES_CONTRADICTION = 'L9R_LEAD_LAG_IGNORES_CONTRADICTION',
  LEAD_LAG_IGNORES_DECAY = 'L9R_LEAD_LAG_IGNORES_DECAY',
  LEAD_LAG_FAMILY_INCOMPATIBLE = 'L9R_LEAD_LAG_FAMILY_INCOMPATIBLE',
  LEAD_LAG_MISSING_CLASS = 'L9R_LEAD_LAG_MISSING_CLASS',
  LEAD_LAG_ASSIGNED_PRIMARY_STATE = 'L9R_LEAD_LAG_ASSIGNED_PRIMARY_STATE',

  // ── Phase progression runtime (§9.4.9) ──
  PHASE_ASSIGNED_WITHOUT_CHAIN = 'L9R_PHASE_ASSIGNED_WITHOUT_CHAIN',
  PHASE_JUMP_WITHOUT_CHANGE_POINT = 'L9R_PHASE_JUMP_WITHOUT_CHANGE_POINT',
  PHASE_VALIDATING_WHILE_CROWDED = 'L9R_PHASE_VALIDATING_WHILE_CROWDED',
  PHASE_DIGESTION_WITHOUT_POST_EVENT = 'L9R_PHASE_DIGESTION_WITHOUT_POST_EVENT',
  PHASE_EXPANSION_WHILE_DECAYING = 'L9R_PHASE_EXPANSION_WHILE_DECAYING',
  PHASE_CLASS_INCONSISTENT_WITH_SCORE = 'L9R_PHASE_CLASS_INCONSISTENT_WITH_SCORE',
  PHASE_ASSIGNED_PRIMARY_STATE = 'L9R_PHASE_ASSIGNED_PRIMARY_STATE',

  // ── Change-point runtime (§9.4.10) ──
  CHANGE_POINT_PRIOR_POSTURE_MISSING = 'L9R_CHANGE_POINT_PRIOR_POSTURE_MISSING',
  CHANGE_POINT_NEXT_POSTURE_MISSING = 'L9R_CHANGE_POINT_NEXT_POSTURE_MISSING',
  CHANGE_POINT_SHOCK_WITHOUT_ANCHOR = 'L9R_CHANGE_POINT_SHOCK_WITHOUT_ANCHOR',
  CHANGE_POINT_CONTRADICTION_WITHOUT_REFS = 'L9R_CHANGE_POINT_CONTRADICTION_WITHOUT_REFS',
  CHANGE_POINT_MICRO_PROMOTED = 'L9R_CHANGE_POINT_MICRO_PROMOTED',
  CHANGE_POINT_MISSING_TRIGGERS = 'L9R_CHANGE_POINT_MISSING_TRIGGERS',
  CHANGE_POINT_SEVERITY_INCONSISTENT = 'L9R_CHANGE_POINT_SEVERITY_INCONSISTENT',

  // ── Decay runtime (§9.4.11) ──
  DECAY_OMITTED_WHERE_REQUIRED = 'L9R_DECAY_OMITTED_WHERE_REQUIRED',
  DECAY_LEAVING_EARLY_UNADJUSTED = 'L9R_DECAY_LEAVING_EARLY_UNADJUSTED',
  DECAY_SHOCK_TREATED_EXPIRED_UNCHECKED = 'L9R_DECAY_SHOCK_TREATED_EXPIRED_UNCHECKED',
  DECAY_ACCUMULATION_STILL_PRIMARY = 'L9R_DECAY_ACCUMULATION_STILL_PRIMARY',
  DECAY_MISSING_REASON = 'L9R_DECAY_MISSING_REASON',
  DECAY_SCORE_OUT_OF_RANGE = 'L9R_DECAY_SCORE_OUT_OF_RANGE',
  DECAY_CLASS_INCONSISTENT_WITH_SCORE = 'L9R_DECAY_CLASS_INCONSISTENT_WITH_SCORE',
  DECAY_ASSIGNED_PRIMARY_STATE = 'L9R_DECAY_ASSIGNED_PRIMARY_STATE',

  // ── Post-event window runtime (§9.4.12) ──
  POST_EVENT_WITHOUT_ANCHOR = 'L9R_POST_EVENT_WITHOUT_ANCHOR',
  POST_EVENT_MISSING_BOUNDS = 'L9R_POST_EVENT_MISSING_BOUNDS',
  POST_EVENT_CLAIMS_WITHOUT_REFS = 'L9R_POST_EVENT_CLAIMS_WITHOUT_REFS',
  POST_EVENT_EXPIRED_AS_GOVERNING = 'L9R_POST_EVENT_EXPIRED_AS_GOVERNING',
  POST_EVENT_CLASS_MISSING = 'L9R_POST_EVENT_CLASS_MISSING',
  POST_EVENT_STATE_MISSING = 'L9R_POST_EVENT_STATE_MISSING',

  // ── Classification runtime (§9.4.13) ──
  CLASSIFY_BEFORE_DECAY = 'L9R_CLASSIFY_BEFORE_DECAY',
  CLASSIFY_ILLEGAL_COEXISTENCE = 'L9R_CLASSIFY_ILLEGAL_COEXISTENCE',
  CLASSIFY_FAKE_CLEAN_SINGLE = 'L9R_CLASSIFY_FAKE_CLEAN_SINGLE',
  CLASSIFY_VALIDATED_WHILE_DECAYING = 'L9R_CLASSIFY_VALIDATED_WHILE_DECAYING',
  CLASSIFY_EARLY_WHILE_LATE = 'L9R_CLASSIFY_EARLY_WHILE_LATE',
  CLASSIFY_POST_SHOCK_WITHOUT_WINDOW = 'L9R_CLASSIFY_POST_SHOCK_WITHOUT_WINDOW',
  CLASSIFY_DISTRIBUTION_OMITTED = 'L9R_CLASSIFY_DISTRIBUTION_OMITTED',
  CLASSIFY_PRIMARY_NOT_IN_FAMILY = 'L9R_CLASSIFY_PRIMARY_NOT_IN_FAMILY',
  CLASSIFY_SECONDARY_SAME_AS_PRIMARY = 'L9R_CLASSIFY_SECONDARY_SAME_AS_PRIMARY',
  CLASSIFY_DOUBLE_ASSIGNMENT = 'L9R_CLASSIFY_DOUBLE_ASSIGNMENT',
  CLASSIFY_CHAIN_DAMAGED_CLEAN = 'L9R_CLASSIFY_CHAIN_DAMAGED_CLEAN',
  CLASSIFY_AMBIGUITY_LAUNDERED = 'L9R_CLASSIFY_AMBIGUITY_LAUNDERED',

  // ── Confidence handoff (§9.4.14) ──
  CONFIDENCE_BEFORE_CLASSIFICATION = 'L9R_CONFIDENCE_BEFORE_CLASSIFICATION',
  CONFIDENCE_MISSING_HANDOFF_BUNDLE = 'L9R_CONFIDENCE_MISSING_HANDOFF_BUNDLE',
  CONFIDENCE_IGNORES_AMBIGUITY = 'L9R_CONFIDENCE_IGNORES_AMBIGUITY',
  CONFIDENCE_IGNORES_DECAY = 'L9R_CONFIDENCE_IGNORES_DECAY',
  CONFIDENCE_IGNORES_CHANGE_POINT = 'L9R_CONFIDENCE_IGNORES_CHANGE_POINT',
  CONFIDENCE_SCORE_OUT_OF_RANGE = 'L9R_CONFIDENCE_SCORE_OUT_OF_RANGE',

  // ── Restriction handoff (§9.4.14) ──
  RESTRICTION_BEFORE_CLASSIFICATION = 'L9R_RESTRICTION_BEFORE_CLASSIFICATION',
  RESTRICTION_MISSING_HANDOFF_BUNDLE = 'L9R_RESTRICTION_MISSING_HANDOFF_BUNDLE',
  RESTRICTION_BLOCKED_ALLOWS_STRONG = 'L9R_RESTRICTION_BLOCKED_ALLOWS_STRONG',
  RESTRICTION_DECISIVE_UNDER_AMBIGUITY = 'L9R_RESTRICTION_DECISIVE_UNDER_AMBIGUITY',
  RESTRICTION_MISSING_BAND = 'L9R_RESTRICTION_MISSING_BAND',

  // ── Evidence pack (§9.4.15.1) ──
  EVIDENCE_PACK_INCOMPLETE = 'L9R_EVIDENCE_PACK_INCOMPLETE',
  EVIDENCE_PACK_MISSING_LINEAGE = 'L9R_EVIDENCE_PACK_MISSING_LINEAGE',
  EVIDENCE_PACK_NON_DETERMINISTIC = 'L9R_EVIDENCE_PACK_NON_DETERMINISTIC',
  EVIDENCE_PACK_MISSING_ORDERED_SIGNAL = 'L9R_EVIDENCE_PACK_MISSING_ORDERED_SIGNAL',
  EVIDENCE_PACK_MISSING_CHAIN = 'L9R_EVIDENCE_PACK_MISSING_CHAIN',
  EVIDENCE_PACK_MISSING_PHASE = 'L9R_EVIDENCE_PACK_MISSING_PHASE',
  EVIDENCE_PACK_MISSING_DECAY = 'L9R_EVIDENCE_PACK_MISSING_DECAY',
  EVIDENCE_PACK_MISSING_CLASSIFICATION = 'L9R_EVIDENCE_PACK_MISSING_CLASSIFICATION',
  EVIDENCE_PACK_MISSING_CONSUMED_REFS = 'L9R_EVIDENCE_PACK_MISSING_CONSUMED_REFS',

  // ── Materialization (§9.4.15.2) ──
  MATERIALIZATION_DIRECT_STORE_WRITE = 'L9R_MATERIALIZATION_DIRECT_STORE_WRITE',
  MATERIALIZATION_BYPASSES_L5 = 'L9R_MATERIALIZATION_BYPASSES_L5',
  MATERIALIZATION_PREREQUISITES_MISSING = 'L9R_MATERIALIZATION_PREREQUISITES_MISSING',
  MATERIALIZATION_CONTRACT_INVALID = 'L9R_MATERIALIZATION_CONTRACT_INVALID',
  MATERIALIZATION_READINESS_INCONSISTENT = 'L9R_MATERIALIZATION_READINESS_INCONSISTENT',
  MATERIALIZATION_SEMANTIC_REPAIR = 'L9R_MATERIALIZATION_SEMANTIC_REPAIR',

  // ── Replay / repair (§9.4.15.3-4) ──
  REPLAY_HASH_DIVERGED = 'L9R_REPLAY_HASH_DIVERGED',
  REPLAY_PRETENDS_LIVE = 'L9R_REPLAY_PRETENDS_LIVE',
  REPLAY_INVENTED_EVIDENCE = 'L9R_REPLAY_INVENTED_EVIDENCE',
  REPLAY_ERASED_AMBIGUITY = 'L9R_REPLAY_ERASED_AMBIGUITY',
  REPLAY_STATE_DRIFT = 'L9R_REPLAY_STATE_DRIFT',
  REPLAY_FAMILY_DRIFT = 'L9R_REPLAY_FAMILY_DRIFT',
  REPAIR_LINEAGE_BROKEN = 'L9R_REPAIR_LINEAGE_BROKEN',
  REPAIR_UNMARKED = 'L9R_REPAIR_UNMARKED',
  REPAIR_REASON_MISSING = 'L9R_REPAIR_REASON_MISSING',
  REPAIR_LIVE_MASQUERADE = 'L9R_REPAIR_LIVE_MASQUERADE',
  REPAIR_SEMANTIC_DRIFT_UNJUSTIFIED = 'L9R_REPAIR_SEMANTIC_DRIFT_UNJUSTIFIED',
}

export const ALL_L9_RUNTIME_VIOLATION_CODES:
  readonly L9RuntimeViolationCode[] =
    Object.values(L9RuntimeViolationCode);

/**
 * §9.4.18.1 — Runtime violation record. Every engine emits these into
 * the `L9RuntimeAudit` log and carries context for replay-safe auditing.
 */
export interface L9RuntimeViolation {
  readonly code: L9RuntimeViolationCode;
  readonly source: string;
  readonly nodeId: string | null;
  readonly sequence_run_id: string | null;
  readonly sequence_subject_id: string | null;
  readonly detail: string;
  readonly context: Record<string, unknown>;
}

export class L9RuntimeError extends Error {
  public readonly code: L9RuntimeViolationCode;
  public readonly details: Record<string, unknown>;

  constructor(
    code: L9RuntimeViolationCode,
    message: string,
    details: Record<string, unknown> = {},
  ) {
    super(`[${code}] ${message}`);
    this.name = 'L9RuntimeError';
    this.code = code;
    this.details = details;
  }
}
