/**
 * L9.5 — Temporal Semantic Violation Codes
 *
 * §9.5.11.2 — Typed violation codes for every L9.5 validator. Disjoint
 * from the L9.1 constitutional codes (`L9_`), L9.2 object codes
 * (`L9O_`), L9.3 contract codes (`L9C_`), and L9.4 runtime codes
 * (`L9R_`) so audit records are unambiguous about which tier rejected
 * an interpretation. L9.5 uses the `L9T_` prefix (temporal semantics).
 */

import { L9TemporalSemanticTier } from '../contracts/l9-temporal-semantics-types';

export enum L9TemporalSemanticViolationCode {
  // ── Time-surface law (§9.5.3) ──
  TS_SURFACE_COLLAPSE = 'L9T_TS_SURFACE_COLLAPSE',
  TS_OBSERVED_EQUALS_INGESTED_WITHOUT_ANCHOR =
    'L9T_TS_OBSERVED_EQUALS_INGESTED_WITHOUT_ANCHOR',
  TS_AS_OF_COLLAPSED_TO_OBSERVED = 'L9T_TS_AS_OF_COLLAPSED_TO_OBSERVED',
  TS_EFFECTIVE_WITHOUT_AS_OF = 'L9T_TS_EFFECTIVE_WITHOUT_AS_OF',
  TS_POST_EVENT_HALF_BOUNDED = 'L9T_TS_POST_EVENT_HALF_BOUNDED',
  TS_SURFACE_ILLEGAL_FOR_PURPOSE = 'L9T_TS_SURFACE_ILLEGAL_FOR_PURPOSE',
  TS_AS_OF_MISSING = 'L9T_TS_AS_OF_MISSING',
  TS_MARKET_VS_SYSTEM_TIME_CONFUSION = 'L9T_TS_MARKET_VS_SYSTEM_TIME_CONFUSION',

  // ── Window law (§9.5.4) ──
  WIN_CLASS_ILLEGAL_FOR_FAMILY = 'L9T_WIN_CLASS_ILLEGAL_FOR_FAMILY',
  WIN_ANCHOR_MISSING = 'L9T_WIN_ANCHOR_MISSING',
  WIN_END_BEFORE_START = 'L9T_WIN_END_BEFORE_START',
  WIN_DRIFT_NEGATIVE = 'L9T_WIN_DRIFT_NEGATIVE',
  WIN_DRIFT_EXCEEDS_POLICY = 'L9T_WIN_DRIFT_EXCEEDS_POLICY',
  WIN_FRESHNESS_CEILING_NEGATIVE = 'L9T_WIN_FRESHNESS_CEILING_NEGATIVE',
  WIN_SPAN_EXCEEDS_POLICY = 'L9T_WIN_SPAN_EXCEEDS_POLICY',
  WIN_LATE_DATA_FLAG_MISMATCH = 'L9T_WIN_LATE_DATA_FLAG_MISMATCH',
  WIN_IMPLICIT_USAGE = 'L9T_WIN_IMPLICIT_USAGE',

  // ── Lead-lag law (§9.5.5) ──
  LL_UNREGISTERED_FAMILY = 'L9T_LL_UNREGISTERED_FAMILY',
  LL_LAG_OUTSIDE_ADMISSIBLE_WINDOW = 'L9T_LL_LAG_OUTSIDE_ADMISSIBLE_WINDOW',
  LL_LAG_NEGATIVE_OR_NON_FINITE = 'L9T_LL_LAG_NEGATIVE_OR_NON_FINITE',
  LL_SCOPE_MISMATCH = 'L9T_LL_SCOPE_MISMATCH',
  LL_LINEAGE_INCOMPLETE = 'L9T_LL_LINEAGE_INCOMPLETE',
  LL_DECISIVE_CONTRADICTION_NOT_VOIDED =
    'L9T_LL_DECISIVE_CONTRADICTION_NOT_VOIDED',
  LL_CAUSAL_INFERENCE_LAUNDERED = 'L9T_LL_CAUSAL_INFERENCE_LAUNDERED',
  LL_LATE_MARKED_AS_EARLY_CONFIRMATION =
    'L9T_LL_LATE_MARKED_AS_EARLY_CONFIRMATION',
  LL_QUALITY_CLASS_MISMATCH = 'L9T_LL_QUALITY_CLASS_MISMATCH',
  LL_ANCHOR_STALE_BEYOND_CONTRACT = 'L9T_LL_ANCHOR_STALE_BEYOND_CONTRACT',

  // ── Phase progression law (§9.5.6) ──
  PHASE_TRANSITION_ILLEGAL = 'L9T_PHASE_TRANSITION_ILLEGAL',
  PHASE_TRANSITION_MISSING_CHANGE_POINT =
    'L9T_PHASE_TRANSITION_MISSING_CHANGE_POINT',
  PHASE_TRANSITION_MISSING_SHOCK_ANCHOR =
    'L9T_PHASE_TRANSITION_MISSING_SHOCK_ANCHOR',
  PHASE_TRANSITION_MISSING_RECOVERY_POSTURE =
    'L9T_PHASE_TRANSITION_MISSING_RECOVERY_POSTURE',
  PHASE_AMBIGUITY_COLLAPSED = 'L9T_PHASE_AMBIGUITY_COLLAPSED',
  PHASE_NON_ADJACENT_CLAIM = 'L9T_PHASE_NON_ADJACENT_CLAIM',

  // ── Change-point law (§9.5.7) ──
  CP_ILLEGAL_TRIGGER_FAMILY = 'L9T_CP_ILLEGAL_TRIGGER_FAMILY',
  CP_SEVERITY_BELOW_MATERIALITY = 'L9T_CP_SEVERITY_BELOW_MATERIALITY',
  CP_MISSING_EVENT_ANCHOR = 'L9T_CP_MISSING_EVENT_ANCHOR',
  CP_MISSING_PRIOR_POSTURE = 'L9T_CP_MISSING_PRIOR_POSTURE',
  CP_MISSING_NEXT_POSTURE = 'L9T_CP_MISSING_NEXT_POSTURE',
  CP_MISSING_TRIGGERING_REFS = 'L9T_CP_MISSING_TRIGGERING_REFS',
  CP_SEVERITY_CLASS_MISMATCH = 'L9T_CP_SEVERITY_CLASS_MISMATCH',
  CP_NOISE_MASQUERADING_AS_BREAK = 'L9T_CP_NOISE_MASQUERADING_AS_BREAK',

  // ── Decay law (§9.5.8) ──
  DECAY_ZERO_UNDER_DOMINANT_CONTRADICTION =
    'L9T_DECAY_ZERO_UNDER_DOMINANT_CONTRADICTION',
  DECAY_STILL_EARLY_WHILE_MATERIALLY_DECAYED =
    'L9T_DECAY_STILL_EARLY_WHILE_MATERIALLY_DECAYED',
  DECAY_FRESH_CLASS_WITH_HIGH_CONTRADICTION =
    'L9T_DECAY_FRESH_CLASS_WITH_HIGH_CONTRADICTION',
  DECAY_RECOVERY_CLAIM_WHILE_SHOCK_DOMINANT =
    'L9T_DECAY_RECOVERY_CLAIM_WHILE_SHOCK_DOMINANT',
  DECAY_SCORE_OUT_OF_RANGE = 'L9T_DECAY_SCORE_OUT_OF_RANGE',
  DECAY_DOMINANCE_CLASS_MISMATCH = 'L9T_DECAY_DOMINANCE_CLASS_MISMATCH',
  DECAY_REFRESH_UNGOVERNED = 'L9T_DECAY_REFRESH_UNGOVERNED',
  DECAY_REFRESH_FAMILY_MISMATCH = 'L9T_DECAY_REFRESH_FAMILY_MISMATCH',
  DECAY_REFRESH_OUTSIDE_WINDOW = 'L9T_DECAY_REFRESH_OUTSIDE_WINDOW',
  DECAY_REFRESH_CONTRADICTION_NULLIFIES =
    'L9T_DECAY_REFRESH_CONTRADICTION_NULLIFIES',
  DECAY_STALENESS_SUBSTITUTED = 'L9T_DECAY_STALENESS_SUBSTITUTED',

  // ── Post-event window law (§9.5.9) ──
  PE_ANCHOR_MISSING = 'L9T_PE_ANCHOR_MISSING',
  PE_ANCHOR_CLASS_MISMATCH = 'L9T_PE_ANCHOR_CLASS_MISMATCH',
  PE_LIFECYCLE_TRANSITION_ILLEGAL = 'L9T_PE_LIFECYCLE_TRANSITION_ILLEGAL',
  PE_REACCUMULATION_UNDER_ACTIVE_SHOCK =
    'L9T_PE_REACCUMULATION_UNDER_ACTIVE_SHOCK',
  PE_STABILIZATION_WITHOUT_REFS = 'L9T_PE_STABILIZATION_WITHOUT_REFS',
  PE_EXPIRED_WINDOW_AS_GOVERNOR = 'L9T_PE_EXPIRED_WINDOW_AS_GOVERNOR',
  PE_WINDOW_BOUNDS_MISSING = 'L9T_PE_WINDOW_BOUNDS_MISSING',

  // ── Interaction law (§9.5.10) ──
  IX_EARLY_CLAIM_UNDER_DOMINANT_DECAY =
    'L9T_IX_EARLY_CLAIM_UNDER_DOMINANT_DECAY',
  IX_DIGESTION_WITHOUT_POST_EVENT_ANCHOR =
    'L9T_IX_DIGESTION_WITHOUT_POST_EVENT_ANCHOR',
  IX_VALIDATION_WITH_TOO_LATE_LEADS =
    'L9T_IX_VALIDATION_WITH_TOO_LATE_LEADS',
  IX_REACCUMULATION_WHILE_SHOCK_ACTIVE =
    'L9T_IX_REACCUMULATION_WHILE_SHOCK_ACTIVE',
  IX_PHASE_JUMP_WITHOUT_CHANGE_POINT =
    'L9T_IX_PHASE_JUMP_WITHOUT_CHANGE_POINT',
  IX_CONTRADICTION_DOES_NOT_VOID_LAG =
    'L9T_IX_CONTRADICTION_DOES_NOT_VOID_LAG',
  IX_AMBIGUITY_HIDDEN_UNDER_CLEAN_OUTPUT =
    'L9T_IX_AMBIGUITY_HIDDEN_UNDER_CLEAN_OUTPUT',
}

export const ALL_L9_TEMPORAL_SEMANTIC_VIOLATION_CODES:
  readonly L9TemporalSemanticViolationCode[] =
    Object.values(L9TemporalSemanticViolationCode);

/**
 * §9.5 — A single typed temporal-semantic violation. Downstream audit
 * aggregates these into `L9TemporalSemanticAuditReport`.
 */
export interface L9TemporalSemanticViolation {
  readonly code: L9TemporalSemanticViolationCode;
  readonly tier: L9TemporalSemanticTier;
  readonly message: string;
  readonly offending_refs?: readonly string[];
}

/**
 * §9.5 — A validator-layer error thrown for critical L9.5 violations.
 */
export class L9TemporalSemanticError extends Error {
  constructor(
    readonly code: L9TemporalSemanticViolationCode,
    readonly tier: L9TemporalSemanticTier,
    message: string,
    readonly offending_refs?: readonly string[],
  ) {
    super(`[${code}] ${message}`);
    this.name = 'L9TemporalSemanticError';
  }
}

/** §9.5 — Helper: build a violation record. */
export function violation(
  code: L9TemporalSemanticViolationCode,
  tier: L9TemporalSemanticTier,
  message: string,
  offending_refs?: readonly string[],
): L9TemporalSemanticViolation {
  return { code, tier, message, offending_refs };
}
