/**
 * L6.1 — Constitutional Types
 *
 * Core enums and type primitives for the entire Layer 6 constitution.
 * Every later L6 sublayer imports from here.
 */

export enum L6PrimitiveClass {
  FEATURE = 'FEATURE',
  EVENT = 'EVENT',
}

export const ALL_PRIMITIVE_CLASSES: readonly L6PrimitiveClass[] = Object.values(L6PrimitiveClass);

export enum L6AllowedCapability {
  GOVERNED_READ = 'GOVERNED_READ',
  PRIMITIVE_CONSTRUCTION = 'PRIMITIVE_CONSTRUCTION',
  CHANGE_DETECTION = 'CHANGE_DETECTION',
  PRIMITIVE_QUALIFICATION = 'PRIMITIVE_QUALIFICATION',
  PRIMITIVE_MATERIALIZATION = 'PRIMITIVE_MATERIALIZATION',
  HISTORICAL_PERSISTENCE = 'HISTORICAL_PERSISTENCE',
  EVIDENCE_FORMATION = 'EVIDENCE_FORMATION',
  REPLAY_SAFE_RECOMPUTATION = 'REPLAY_SAFE_RECOMPUTATION',
  REPAIR_SAFE_RECOMPUTATION = 'REPAIR_SAFE_RECOMPUTATION',
}

export const ALL_ALLOWED_CAPABILITIES: readonly L6AllowedCapability[] = Object.values(L6AllowedCapability);

export enum L6ForbiddenAction {
  ILLEGAL_IDENTITY_INFERENCE = 'ILLEGAL_IDENTITY_INFERENCE',
  MISSING_METRIC_CONTRACT_BYPASS = 'MISSING_METRIC_CONTRACT_BYPASS',
  RAW_PROVIDER_BYPASS = 'RAW_PROVIDER_BYPASS',
  HIDDEN_NEUTRAL_FILL = 'HIDDEN_NEUTRAL_FILL',
  LATE_DATA_SILENT_MUTATION = 'LATE_DATA_SILENT_MUTATION',
  JUDGMENT_LANGUAGE_LEAK = 'JUDGMENT_LANGUAGE_LEAK',
  ILLEGAL_GRAPH_REINTERPRETATION = 'ILLEGAL_GRAPH_REINTERPRETATION',
  ILLEGAL_STORAGE_BYPASS = 'ILLEGAL_STORAGE_BYPASS',
  CONFIDENCE_LAW_OVERRIDE = 'CONFIDENCE_LAW_OVERRIDE',
  LOWER_LAYER_REDEFINITION = 'LOWER_LAYER_REDEFINITION',
}

export const ALL_FORBIDDEN_ACTIONS: readonly L6ForbiddenAction[] = Object.values(L6ForbiddenAction);

export enum L6DependencyLayer {
  L3 = 'L3',
  L4 = 'L4',
  L5 = 'L5',
}

export const ALL_DEPENDENCY_LAYERS: readonly L6DependencyLayer[] = Object.values(L6DependencyLayer);

export enum L6DependencySurfaceClass {
  CANONICAL_OBJECT = 'CANONICAL_OBJECT',
  IDENTITY_RESOLUTION = 'IDENTITY_RESOLUTION',
  METRIC_CONTRACT = 'METRIC_CONTRACT',
  CONFIDENCE_SCORE = 'CONFIDENCE_SCORE',
  GRAPH_RELATION = 'GRAPH_RELATION',
  GRAPH_CONTEXT_PACKAGE = 'GRAPH_CONTEXT_PACKAGE',
  GRAPH_QUERY = 'GRAPH_QUERY',
  STORAGE_WRITE_COORDINATION = 'STORAGE_WRITE_COORDINATION',
  STORAGE_READ_RESOLUTION = 'STORAGE_READ_RESOLUTION',
  STORAGE_REPLAY = 'STORAGE_REPLAY',
  STORAGE_REPAIR = 'STORAGE_REPAIR',
}

export const ALL_DEPENDENCY_SURFACE_CLASSES: readonly L6DependencySurfaceClass[] = Object.values(L6DependencySurfaceClass);

export enum L6OutputSurfaceClass {
  FEATURE_HISTORY_FACT = 'FEATURE_HISTORY_FACT',
  CURRENT_FEATURE_STATE = 'CURRENT_FEATURE_STATE',
  EVENT_INSTANCE = 'EVENT_INSTANCE',
  EVIDENCE_PACK = 'EVIDENCE_PACK',
}

export const ALL_OUTPUT_SURFACE_CLASSES: readonly L6OutputSurfaceClass[] = Object.values(L6OutputSurfaceClass);

export type L6DependencyUsability = 'FEATURE_COMPUTE' | 'EVENT_DETECTION' | 'EVIDENCE_ONLY' | 'BASELINE_CONSTRUCTION';

export type L6CapabilityDecision = 'ALLOWED' | 'CONDITIONALLY_ALLOWED' | 'DENIED';

export type L6CapabilityContext = 'FEATURE_DEFINITION' | 'FEATURE_RUNTIME' | 'EVENT_DEFINITION' | 'EVENT_RUNTIME' | 'EVIDENCE_BUILDER' | 'REPLAY_PATH' | 'REPAIR_PATH';

export const ALL_CAPABILITY_CONTEXTS: readonly L6CapabilityContext[] = [
  'FEATURE_DEFINITION', 'FEATURE_RUNTIME', 'EVENT_DEFINITION', 'EVENT_RUNTIME',
  'EVIDENCE_BUILDER', 'REPLAY_PATH', 'REPAIR_PATH',
];
