FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install express
COPY src/app.js ./
USER node
EXPOSE 3000
HEALTHCHECK --interval=30s --timeout=3s CMD wget -qO- http://127.0.0.1:3000/health || exit 1
CMD ["node","app.js"]