/**
 * L13.7 — Mode Violation Codes
 *
 * §13.7.22 — Disjoint `L13M_` namespace for product-mode law
 * violations.
 */

export enum L13ModeViolationCode {
  L13M_ANSWER_MODE_UNREGISTERED = 'L13M_ANSWER_MODE_UNREGISTERED',
  L13M_ANSWER_MODE_STATUS_ILLEGAL = 'L13M_ANSWER_MODE_STATUS_ILLEGAL',
  L13M_MODE_PAYLOAD_MISSING = 'L13M_MODE_PAYLOAD_MISSING',
  L13M_MODE_ENVELOPE_MISSING = 'L13M_MODE_ENVELOPE_MISSING',
  L13M_CHAT_DIRECT_ANSWER_MISSING = 'L13M_CHAT_DIRECT_ANSWER_MISSING',
  L13M_CHAT_IGNORES_USER_INTENT = 'L13M_CHAT_IGNORES_USER_INTENT',
  L13M_CHAT_RAW_METRIC_DUMP_UNREQUESTED = 'L13M_CHAT_RAW_METRIC_DUMP_UNREQUESTED',
  L13M_WHAT_NEXT_WITHOUT_SCENARIO = 'L13M_WHAT_NEXT_WITHOUT_SCENARIO',
  L13M_WHAT_NEXT_WITHOUT_TRIGGER = 'L13M_WHAT_NEXT_WITHOUT_TRIGGER',
  L13M_WHAT_NEXT_WITHOUT_INVALIDATION = 'L13M_WHAT_NEXT_WITHOUT_INVALIDATION',
  L13M_ALERT_CHANGE_SUBJECT_MISSING = 'L13M_ALERT_CHANGE_SUBJECT_MISSING',
  L13M_ALERT_WHY_IT_MATTERS_MISSING = 'L13M_ALERT_WHY_IT_MATTERS_MISSING',
  L13M_ALERT_TRIGGER_OR_INVALIDATION_OMITTED = 'L13M_ALERT_TRIGGER_OR_INVALIDATION_OMITTED',
  L13M_ALERT_CONFIDENCE_SHIFT_HIDDEN = 'L13M_ALERT_CONFIDENCE_SHIFT_HIDDEN',
  L13M_REPORT_EXECUTIVE_SUMMARY_MISSING = 'L13M_REPORT_EXECUTIVE_SUMMARY_MISSING',
  L13M_REPORT_CONTRADICTION_SECTION_MISSING = 'L13M_REPORT_CONTRADICTION_SECTION_MISSING',
  L13M_REPORT_UNCERTAINTY_SECTION_MISSING = 'L13M_REPORT_UNCERTAINTY_SECTION_MISSING',
  L13M_REPORT_TRIGGER_SECTION_MISSING = 'L13M_REPORT_TRIGGER_SECTION_MISSING',
  L13M_REPORT_INVALIDATION_SECTION_MISSING = 'L13M_REPORT_INVALIDATION_SECTION_MISSING',
  L13M_REPORT_RESTRICTION_SECTION_MISSING = 'L13M_REPORT_RESTRICTION_SECTION_MISSING',
  L13M_REPORT_APPENDIX_OR_EVIDENCE_MISSING = 'L13M_REPORT_APPENDIX_OR_EVIDENCE_MISSING',
  L13M_ASSET_COMPARISON_RECOMMENDATION_LEAK = 'L13M_ASSET_COMPARISON_RECOMMENDATION_LEAK',
  L13M_ASSET_COMPARISON_PARITY_MISSING = 'L13M_ASSET_COMPARISON_PARITY_MISSING',
  L13M_ASSET_COMPARISON_MISSING_DATA_ASYMMETRY_HIDDEN = 'L13M_ASSET_COMPARISON_MISSING_DATA_ASYMMETRY_HIDDEN',
  L13M_ASSET_COMPARISON_DRIFT_ASYMMETRY_HIDDEN = 'L13M_ASSET_COMPARISON_DRIFT_ASYMMETRY_HIDDEN',
  L13M_ASSET_COMPARISON_RESTRICTION_ASYMMETRY_HIDDEN = 'L13M_ASSET_COMPARISON_RESTRICTION_ASYMMETRY_HIDDEN',
  L13M_ASSET_COMPARISON_DIMENSION_INCOMPLETE = 'L13M_ASSET_COMPARISON_DIMENSION_INCOMPLETE',
  L13M_THESIS_COMPARISON_FINALITY_LEAK = 'L13M_THESIS_COMPARISON_FINALITY_LEAK',
  L13M_THESIS_COMPARISON_MISSING_CONTRADICTION = 'L13M_THESIS_COMPARISON_MISSING_CONTRADICTION',
  L13M_SCENARIO_EXPLANATION_WITHOUT_CONDITIONALITY = 'L13M_SCENARIO_EXPLANATION_WITHOUT_CONDITIONALITY',
  L13M_SCENARIO_EXPLANATION_TRIGGER_MISSING = 'L13M_SCENARIO_EXPLANATION_TRIGGER_MISSING',
  L13M_SCENARIO_EXPLANATION_INVALIDATION_MISSING = 'L13M_SCENARIO_EXPLANATION_INVALIDATION_MISSING',
  L13M_SCORE_EXPLANATION_WITHOUT_ATTRIBUTION = 'L13M_SCORE_EXPLANATION_WITHOUT_ATTRIBUTION',
  L13M_SCORE_EXPLANATION_RECOMMENDATION_LEAK = 'L13M_SCORE_EXPLANATION_RECOMMENDATION_LEAK',
  L13M_CONTRADICTION_EXPLANATION_WITHOUT_L7_REF = 'L13M_CONTRADICTION_EXPLANATION_WITHOUT_L7_REF',
  L13M_CONTRADICTION_EXPLANATION_WITHOUT_AFFECTED_CONTEXT = 'L13M_CONTRADICTION_EXPLANATION_WITHOUT_AFFECTED_CONTEXT',
  L13M_CONTRADICTION_EXPLANATION_MINIMIZED = 'L13M_CONTRADICTION_EXPLANATION_MINIMIZED',
  L13M_DEBUG_MODE_USER_EMITTED = 'L13M_DEBUG_MODE_USER_EMITTED',
  L13M_MODE_READINESS_ILLEGAL = 'L13M_MODE_READINESS_ILLEGAL',
  L13M_MODE_LINEAGE_MISSING = 'L13M_MODE_LINEAGE_MISSING',
  L13M_MODE_REPLAY_HASH_MISSING = 'L13M_MODE_REPLAY_HASH_MISSING',
  L13M_MODE_FORBIDDEN_OMISSION = 'L13M_MODE_FORBIDDEN_OMISSION',
  L13M_MODE_REQUIRED_DISCLOSURE_MISSING = 'L13M_MODE_REQUIRED_DISCLOSURE_MISSING',
  L13M_MODE_REQUIRED_SECTION_MISSING = 'L13M_MODE_REQUIRED_SECTION_MISSING',
  L13M_MODE_REQUIRED_CONTEXT_MISSING = 'L13M_MODE_REQUIRED_CONTEXT_MISSING',
}

export const ALL_L13_MODE_VIOLATION_CODES:
  readonly L13ModeViolationCode[] =
  Object.values(L13ModeViolationCode);
