/**
 * L13.3 — Output Violation Codes
 *
 * §13.3.17 — Disjoint `L13O_` namespace for output-contract
 * violations. Every illegal output state maps to exactly one of
 * these codes.
 */

export enum L13OutputViolationCode {
  // Identity (§13.3.3.1)
  L13O_OUTPUT_ID_MISSING = 'L13O_OUTPUT_ID_MISSING',
  L13O_REQUEST_ID_MISSING = 'L13O_REQUEST_ID_MISSING',
  L13O_INPUT_PACKAGE_REF_MISSING = 'L13O_INPUT_PACKAGE_REF_MISSING',

  L13O_OUTPUT_CLASS_MISSING = 'L13O_OUTPUT_CLASS_MISSING',
  L13O_OUTPUT_CLASS_ILLEGAL = 'L13O_OUTPUT_CLASS_ILLEGAL',
  L13O_ANSWER_MODE_MISSING = 'L13O_ANSWER_MODE_MISSING',
  L13O_SCOPE_MISSING = 'L13O_SCOPE_MISSING',
  L13O_AS_OF_MISSING = 'L13O_AS_OF_MISSING',
  L13O_POLICY_VERSION_MISSING = 'L13O_POLICY_VERSION_MISSING',

  // Required content (§13.3.3.2)
  L13O_HEADLINE_MISSING = 'L13O_HEADLINE_MISSING',
  L13O_SUMMARY_MISSING = 'L13O_SUMMARY_MISSING',

  L13O_OBSERVATION_SECTION_MISSING = 'L13O_OBSERVATION_SECTION_MISSING',
  L13O_INFERENCE_SECTION_MISSING = 'L13O_INFERENCE_SECTION_MISSING',
  L13O_UNCERTAINTY_SECTION_MISSING = 'L13O_UNCERTAINTY_SECTION_MISSING',
  L13O_CONTRADICTION_SECTION_MISSING = 'L13O_CONTRADICTION_SECTION_MISSING',
  L13O_SCENARIO_SECTION_MISSING = 'L13O_SCENARIO_SECTION_MISSING',
  L13O_TRIGGER_INVALIDATION_SECTION_MISSING = 'L13O_TRIGGER_INVALIDATION_SECTION_MISSING',

  L13O_CONFIDENCE_DISCLOSURE_MISSING = 'L13O_CONFIDENCE_DISCLOSURE_MISSING',
  L13O_RESTRICTION_DISCLOSURE_MISSING = 'L13O_RESTRICTION_DISCLOSURE_MISSING',

  // Trace (§13.3.3.3)
  L13O_EVIDENCE_REFS_MISSING = 'L13O_EVIDENCE_REFS_MISSING',
  L13O_LINEAGE_REFS_MISSING = 'L13O_LINEAGE_REFS_MISSING',
  L13O_REPLAY_HASH_MISSING = 'L13O_REPLAY_HASH_MISSING',
  L13O_MODEL_METADATA_MISSING = 'L13O_MODEL_METADATA_MISSING',

  // Section discipline
  L13O_SECTION_INVALID = 'L13O_SECTION_INVALID',
  L13O_SECTION_CONTENT_EMPTY = 'L13O_SECTION_CONTENT_EMPTY',
  L13O_SECTION_REFS_MISSING = 'L13O_SECTION_REFS_MISSING',

  // Observation/inference separation (§13.3.5)
  L13O_OBSERVATION_INFERENCE_MIXED = 'L13O_OBSERVATION_INFERENCE_MIXED',
  L13O_INFERENCE_PRESENTED_AS_FACT = 'L13O_INFERENCE_PRESENTED_AS_FACT',

  // Adverse-state omission
  L13O_CONTRADICTION_OMITTED = 'L13O_CONTRADICTION_OMITTED',
  L13O_UNCERTAINTY_OMITTED = 'L13O_UNCERTAINTY_OMITTED',
  L13O_ACTIVE_INVALIDATION_OMITTED = 'L13O_ACTIVE_INVALIDATION_OMITTED',
  L13O_TRIGGER_CONTEXT_OMITTED = 'L13O_TRIGGER_CONTEXT_OMITTED',

  // Semantic leakage (§13.3.12)
  L13O_RECOMMENDATION_LEAK = 'L13O_RECOMMENDATION_LEAK',
  L13O_PREDICTION_THEATER = 'L13O_PREDICTION_THEATER',
  L13O_FINAL_JUDGMENT_LEAK = 'L13O_FINAL_JUDGMENT_LEAK',
  L13O_TRADE_ACTION_LEAK = 'L13O_TRADE_ACTION_LEAK',
  L13O_CERTAINTY_LEAK = 'L13O_CERTAINTY_LEAK',

  L13O_SCORE_AS_RECOMMENDATION = 'L13O_SCORE_AS_RECOMMENDATION',
  L13O_SCENARIO_AS_CERTAINTY = 'L13O_SCENARIO_AS_CERTAINTY',
  L13O_CONFIDENCE_AS_PROBABILITY = 'L13O_CONFIDENCE_AS_PROBABILITY',
  L13O_HYPOTHESIS_AS_FINAL_TRUTH = 'L13O_HYPOTHESIS_AS_FINAL_TRUTH',

  // Restriction / answer-mode law
  L13O_BLOCKED_ANSWER_MODE_VIOLATED = 'L13O_BLOCKED_ANSWER_MODE_VIOLATED',
  L13O_RESTRICTION_BYPASS = 'L13O_RESTRICTION_BYPASS',

  // Readiness law
  L13O_OUTPUT_READINESS_ILLEGAL = 'L13O_OUTPUT_READINESS_ILLEGAL',
  L13O_CLEAN_OUTPUT_UNDER_DISCLOSURE_REQUIREMENT = 'L13O_CLEAN_OUTPUT_UNDER_DISCLOSURE_REQUIREMENT',
  L13O_BLOCKED_UNGROUNDED_EMITTED = 'L13O_BLOCKED_UNGROUNDED_EMITTED',
  L13O_REFUSAL_NOT_REFUSAL_SHAPED = 'L13O_REFUSAL_NOT_REFUSAL_SHAPED',

  // Claims
  L13O_UNSUPPORTED_CLAIM_PRESENT = 'L13O_UNSUPPORTED_CLAIM_PRESENT',
  L13O_BLOCKED_CLAIM_NOT_RECORDED = 'L13O_BLOCKED_CLAIM_NOT_RECORDED',
  L13O_BLOCKED_CLAIM_INVALID = 'L13O_BLOCKED_CLAIM_INVALID',

  // Model metadata
  L13O_MODEL_METADATA_INVALID = 'L13O_MODEL_METADATA_INVALID',

  // Confidence / restriction disclosure
  L13O_CONFIDENCE_DISCLOSURE_INVALID = 'L13O_CONFIDENCE_DISCLOSURE_INVALID',
  L13O_RESTRICTION_DISCLOSURE_INVALID = 'L13O_RESTRICTION_DISCLOSURE_INVALID',
}

export const ALL_L13_OUTPUT_VIOLATION_CODES:
  readonly L13OutputViolationCode[] = Object.values(L13OutputViolationCode);

export class L13OutputError extends Error {
  public readonly code: L13OutputViolationCode;
  public readonly details: Record<string, unknown>;

  constructor(
    code: L13OutputViolationCode,
    message: string,
    details: Record<string, unknown> = {},
  ) {
    super(`[${code}] ${message}`);
    this.name = 'L13OutputError';
    this.code = code;
    this.details = details;
  }
}
