/**
 * L13.6 — Runtime Violation Codes
 *
 * §13.6.24 — Disjoint `L13R_` namespace for runtime violations.
 */

export enum L13RuntimeViolationCode {
  L13R_INTENT_CLASSIFICATION_MISSING = 'L13R_INTENT_CLASSIFICATION_MISSING',
  L13R_INTENT_CLASSIFICATION_NONDETERMINISTIC = 'L13R_INTENT_CLASSIFICATION_NONDETERMINISTIC',
  L13R_OUT_OF_SCOPE_CONTINUED_TO_MODEL = 'L13R_OUT_OF_SCOPE_CONTINUED_TO_MODEL',
  L13R_SCOPE_RESOLUTION_MISSING = 'L13R_SCOPE_RESOLUTION_MISSING',
  L13R_AMBIGUOUS_SCOPE_CONTINUED = 'L13R_AMBIGUOUS_SCOPE_CONTINUED',
  L13R_READ_PLAN_MISSING = 'L13R_READ_PLAN_MISSING',
  L13R_ILLEGAL_READ_SURFACE_SELECTED = 'L13R_ILLEGAL_READ_SURFACE_SELECTED',
  L13R_REQUIRED_SURFACE_MISSING = 'L13R_REQUIRED_SURFACE_MISSING',
  L13R_INPUT_PACKAGE_MISSING = 'L13R_INPUT_PACKAGE_MISSING',
  L13R_INPUT_PACKAGE_BLOCKED_BUT_MODEL_CALLED = 'L13R_INPUT_PACKAGE_BLOCKED_BUT_MODEL_CALLED',
  L13R_PROMPT_TEMPLATE_MISSING = 'L13R_PROMPT_TEMPLATE_MISSING',
  L13R_PROMPT_TEMPLATE_UNAPPROVED = 'L13R_PROMPT_TEMPLATE_UNAPPROVED',
  L13R_PROMPT_POLICY_BLOCK_MISSING = 'L13R_PROMPT_POLICY_BLOCK_MISSING',
  L13R_PROMPT_ASSEMBLY_MISSING = 'L13R_PROMPT_ASSEMBLY_MISSING',
  L13R_RAW_LOWER_LAYER_DATA_IN_PROMPT = 'L13R_RAW_LOWER_LAYER_DATA_IN_PROMPT',
  L13R_MODEL_GATEWAY_INPUT_PACKAGE_MISSING = 'L13R_MODEL_GATEWAY_INPUT_PACKAGE_MISSING',
  L13R_MODEL_GATEWAY_POLICY_REF_MISSING = 'L13R_MODEL_GATEWAY_POLICY_REF_MISSING',
  L13R_MODEL_GATEWAY_TEMPERATURE_ILLEGAL = 'L13R_MODEL_GATEWAY_TEMPERATURE_ILLEGAL',
  L13R_MODEL_GATEWAY_RAW_BYPASS = 'L13R_MODEL_GATEWAY_RAW_BYPASS',
  L13R_MODEL_RESPONSE_NOT_CAPTURED = 'L13R_MODEL_RESPONSE_NOT_CAPTURED',
  L13R_DRAFT_PARSE_FAILED = 'L13R_DRAFT_PARSE_FAILED',
  L13R_OUTPUT_OBJECT_BUILD_SKIPPED = 'L13R_OUTPUT_OBJECT_BUILD_SKIPPED',
  L13R_GROUNDING_PASS_SKIPPED = 'L13R_GROUNDING_PASS_SKIPPED',
  L13R_EXPRESSION_PASS_SKIPPED = 'L13R_EXPRESSION_PASS_SKIPPED',
  L13R_ILLEGAL_OUTPUT_REACHED_FINAL_GATE = 'L13R_ILLEGAL_OUTPUT_REACHED_FINAL_GATE',
  L13R_FINAL_GATE_BYPASSED = 'L13R_FINAL_GATE_BYPASSED',
  L13R_FINAL_GATE_EMITTED_BLOCKED_OUTPUT = 'L13R_FINAL_GATE_EMITTED_BLOCKED_OUTPUT',
  L13R_REWRITE_REQUIRED_BUT_SKIPPED = 'L13R_REWRITE_REQUIRED_BUT_SKIPPED',
  L13R_REWRITE_ATTEMPT_LIMIT_EXCEEDED = 'L13R_REWRITE_ATTEMPT_LIMIT_EXCEEDED',
  L13R_REFUSAL_REQUIRED_BUT_NOT_EMITTED = 'L13R_REFUSAL_REQUIRED_BUT_NOT_EMITTED',
  L13R_RUNTIME_LINEAGE_MISSING = 'L13R_RUNTIME_LINEAGE_MISSING',
  L13R_RUNTIME_REPLAY_HASH_MISSING = 'L13R_RUNTIME_REPLAY_HASH_MISSING',
  L13R_CAPTURED_RESPONSE_REPLAY_MISMATCH = 'L13R_CAPTURED_RESPONSE_REPLAY_MISMATCH',
  L13R_STAGE_BYPASS_DETECTED = 'L13R_STAGE_BYPASS_DETECTED',
  L13R_REFUSAL_ENVELOPE_INVALID = 'L13R_REFUSAL_ENVELOPE_INVALID',
}

export const ALL_L13_RUNTIME_VIOLATION_CODES:
  readonly L13RuntimeViolationCode[] =
  Object.values(L13RuntimeViolationCode);
