/**
 * L13.2 — Input Package Violation Codes
 *
 * §13.2.19 — Disjoint `L13P_` namespace for AI input package and
 * context assembly violations. Every illegal package state maps to
 * exactly one of these codes.
 */

export enum L13InputPackageViolationCode {
  // Identity fields (§13.2.3.1)
  L13P_INPUT_PACKAGE_ID_MISSING = 'L13P_INPUT_PACKAGE_ID_MISSING',
  L13P_REQUEST_ID_MISSING = 'L13P_REQUEST_ID_MISSING',
  L13P_USER_INTENT_MISSING = 'L13P_USER_INTENT_MISSING',
  L13P_SCOPE_MISSING = 'L13P_SCOPE_MISSING',
  L13P_AS_OF_MISSING = 'L13P_AS_OF_MISSING',
  L13P_POLICY_VERSION_MISSING = 'L13P_POLICY_VERSION_MISSING',

  // Required summaries (§13.2.3.2)
  L13P_ENTITY_SUMMARY_MISSING = 'L13P_ENTITY_SUMMARY_MISSING',
  L13P_VALIDATION_SUMMARY_MISSING = 'L13P_VALIDATION_SUMMARY_MISSING',
  L13P_CONTRADICTION_SUMMARY_MISSING = 'L13P_CONTRADICTION_SUMMARY_MISSING',
  L13P_REGIME_SUMMARY_MISSING = 'L13P_REGIME_SUMMARY_MISSING',
  L13P_SEQUENCE_SUMMARY_MISSING = 'L13P_SEQUENCE_SUMMARY_MISSING',
  L13P_HYPOTHESIS_SUMMARY_MISSING = 'L13P_HYPOTHESIS_SUMMARY_MISSING',
  L13P_SCORE_SUMMARY_MISSING = 'L13P_SCORE_SUMMARY_MISSING',
  L13P_SCENARIO_SUMMARY_MISSING = 'L13P_SCENARIO_SUMMARY_MISSING',
  L13P_CONFIDENCE_BREAKDOWN_MISSING = 'L13P_CONFIDENCE_BREAKDOWN_MISSING',
  L13P_UNCERTAINTY_PROFILE_MISSING = 'L13P_UNCERTAINTY_PROFILE_MISSING',
  L13P_RESTRICTION_PROFILE_MISSING = 'L13P_RESTRICTION_PROFILE_MISSING',

  // Trace fields (§13.2.3.3)
  L13P_EVIDENCE_REFS_MISSING = 'L13P_EVIDENCE_REFS_MISSING',
  L13P_LINEAGE_REFS_MISSING = 'L13P_LINEAGE_REFS_MISSING',
  L13P_REPLAY_HASH_MISSING = 'L13P_REPLAY_HASH_MISSING',
  L13P_PROMPT_BUDGET_MISSING = 'L13P_PROMPT_BUDGET_MISSING',
  L13P_ALLOWED_ANSWER_MODES_MISSING = 'L13P_ALLOWED_ANSWER_MODES_MISSING',
  L13P_BLOCKED_ANSWER_MODES_MISSING = 'L13P_BLOCKED_ANSWER_MODES_MISSING',

  // Lower-layer bypass and naked context
  L13P_RAW_LOWER_LAYER_CONTEXT = 'L13P_RAW_LOWER_LAYER_CONTEXT',
  L13P_NAKED_L11_SCORE_CONTEXT = 'L13P_NAKED_L11_SCORE_CONTEXT',
  L13P_INCOMPLETE_L11_SCORE_CONTEXT = 'L13P_INCOMPLETE_L11_SCORE_CONTEXT',
  L13P_NAKED_L12_SCENARIO_CONTEXT = 'L13P_NAKED_L12_SCENARIO_CONTEXT',
  L13P_INCOMPLETE_L12_SCENARIO_CONTEXT = 'L13P_INCOMPLETE_L12_SCENARIO_CONTEXT',

  // Adverse-state omissions
  L13P_ACTIVE_CONTRADICTION_OMITTED = 'L13P_ACTIVE_CONTRADICTION_OMITTED',
  L13P_ACTIVE_INVALIDATION_OMITTED = 'L13P_ACTIVE_INVALIDATION_OMITTED',
  L13P_TRIGGER_CONTEXT_OMITTED = 'L13P_TRIGGER_CONTEXT_OMITTED',
  L13P_CONFIDENCE_CAP_OMITTED = 'L13P_CONFIDENCE_CAP_OMITTED',

  // Disclosure law
  L13P_MISSING_DATA_DISCLOSURE_OMITTED = 'L13P_MISSING_DATA_DISCLOSURE_OMITTED',
  L13P_DRIFT_DISCLOSURE_OMITTED = 'L13P_DRIFT_DISCLOSURE_OMITTED',

  // Priority and compression
  L13P_CONTEXT_PRIORITY_VIOLATED = 'L13P_CONTEXT_PRIORITY_VIOLATED',
  L13P_CONTRADICTION_DROPPED_BEFORE_POSITIVE = 'L13P_CONTRADICTION_DROPPED_BEFORE_POSITIVE',
  L13P_REQUIRED_CONTEXT_DROPPED = 'L13P_REQUIRED_CONTEXT_DROPPED',
  L13P_ILLEGAL_COMPRESSION = 'L13P_ILLEGAL_COMPRESSION',

  // Restriction binding and answer modes
  L13P_BLOCKED_ANSWER_MODE_ALLOWED = 'L13P_BLOCKED_ANSWER_MODE_ALLOWED',
  L13P_RESTRICTION_BYPASS = 'L13P_RESTRICTION_BYPASS',

  // Budget and readiness
  L13P_PROMPT_BUDGET_INVALID = 'L13P_PROMPT_BUDGET_INVALID',
  L13P_PACKAGE_READINESS_ILLEGAL = 'L13P_PACKAGE_READINESS_ILLEGAL',

  // Evidence/digest/confidence/uncertainty law
  L13P_EVIDENCE_DIGEST_INVALID = 'L13P_EVIDENCE_DIGEST_INVALID',
  L13P_CONFIDENCE_BREAKDOWN_INVALID = 'L13P_CONFIDENCE_BREAKDOWN_INVALID',
  L13P_UNCERTAINTY_PROFILE_INVALID = 'L13P_UNCERTAINTY_PROFILE_INVALID',

  // Intent-specific context law
  L13P_FORWARD_INTENT_WITHOUT_SCENARIO = 'L13P_FORWARD_INTENT_WITHOUT_SCENARIO',
  L13P_SCORE_INTENT_WITHOUT_SCORE = 'L13P_SCORE_INTENT_WITHOUT_SCORE',
  L13P_HYPOTHESIS_INTENT_WITHOUT_HYPOTHESIS = 'L13P_HYPOTHESIS_INTENT_WITHOUT_HYPOTHESIS',
  L13P_COMPARISON_INTENT_WITHOUT_PEER = 'L13P_COMPARISON_INTENT_WITHOUT_PEER',
}

export const ALL_L13_INPUT_PACKAGE_VIOLATION_CODES:
  readonly L13InputPackageViolationCode[] =
  Object.values(L13InputPackageViolationCode);

export class L13InputPackageError extends Error {
  public readonly code: L13InputPackageViolationCode;
  public readonly details: Record<string, unknown>;

  constructor(
    code: L13InputPackageViolationCode,
    message: string,
    details: Record<string, unknown> = {},
  ) {
    super(`[${code}] ${message}`);
    this.name = 'L13InputPackageError';
    this.code = code;
    this.details = details;
  }
}
