/**
 * L13.9 — Safety Violation Codes
 *
 * §13.9.26 — Disjoint `L13Y_` namespace. ("S" is L13.8's style
 * namespace; "Y" is safetY.)
 */

export enum L13SafetyViolationCode {
  L13Y_SAFETY_POLICY_MISSING = 'L13Y_SAFETY_POLICY_MISSING',
  L13Y_SAFETY_SCAN_MISSING = 'L13Y_SAFETY_SCAN_MISSING',
  L13Y_SAFETY_CLASSIFICATION_MISSING = 'L13Y_SAFETY_CLASSIFICATION_MISSING',
  L13Y_FINAL_SAFETY_GATE_MISSING = 'L13Y_FINAL_SAFETY_GATE_MISSING',
  L13Y_BUY_SELL_INSTRUCTION_EMITTED = 'L13Y_BUY_SELL_INSTRUCTION_EMITTED',
  L13Y_HOLD_AVOID_INSTRUCTION_EMITTED = 'L13Y_HOLD_AVOID_INSTRUCTION_EMITTED',
  L13Y_LONG_SHORT_INSTRUCTION_EMITTED = 'L13Y_LONG_SHORT_INSTRUCTION_EMITTED',
  L13Y_ENTRY_EXIT_INSTRUCTION_EMITTED = 'L13Y_ENTRY_EXIT_INSTRUCTION_EMITTED',
  L13Y_LEVERAGE_RECOMMENDATION_EMITTED = 'L13Y_LEVERAGE_RECOMMENDATION_EMITTED',
  L13Y_POSITION_SIZING_INSTRUCTION_EMITTED = 'L13Y_POSITION_SIZING_INSTRUCTION_EMITTED',
  L13Y_STOP_LOSS_TAKE_PROFIT_INSTRUCTION_EMITTED = 'L13Y_STOP_LOSS_TAKE_PROFIT_INSTRUCTION_EMITTED',
  L13Y_LIQUIDATION_TARGET_ADVICE_EMITTED = 'L13Y_LIQUIDATION_TARGET_ADVICE_EMITTED',
  L13Y_GUARANTEED_OUTCOME_EMITTED = 'L13Y_GUARANTEED_OUTCOME_EMITTED',
  L13Y_PUMP_DUMP_PROPHECY_EMITTED = 'L13Y_PUMP_DUMP_PROPHECY_EMITTED',
  L13Y_UNSUPPORTED_CERTAINTY_EMITTED = 'L13Y_UNSUPPORTED_CERTAINTY_EMITTED',
  L13Y_TAX_LEGAL_ADVICE_EMITTED = 'L13Y_TAX_LEGAL_ADVICE_EMITTED',
  L13Y_MARKET_MANIPULATION_ASSISTANCE_EMITTED = 'L13Y_MARKET_MANIPULATION_ASSISTANCE_EMITTED',
  L13Y_ADVICE_ADJACENT_OUTPUT_NOT_REWRITTEN = 'L13Y_ADVICE_ADJACENT_OUTPUT_NOT_REWRITTEN',
  L13Y_REWRITE_REQUIRED_BUT_EMITTED = 'L13Y_REWRITE_REQUIRED_BUT_EMITTED',
  L13Y_REFUSAL_REQUIRED_BUT_NOT_EMITTED = 'L13Y_REFUSAL_REQUIRED_BUT_NOT_EMITTED',
  L13Y_BLOCK_REQUIRED_BUT_OUTPUT_CONTINUED = 'L13Y_BLOCK_REQUIRED_BUT_OUTPUT_CONTINUED',
  L13Y_SAFETY_TRIED_TO_OVERRIDE_GROUNDING = 'L13Y_SAFETY_TRIED_TO_OVERRIDE_GROUNDING',
  L13Y_GROUNDING_TRIED_TO_OVERRIDE_SAFETY = 'L13Y_GROUNDING_TRIED_TO_OVERRIDE_SAFETY',
  L13Y_SAFETY_GATE_NOT_CONSUMED_BY_FINAL_GATE = 'L13Y_SAFETY_GATE_NOT_CONSUMED_BY_FINAL_GATE',
  L13Y_SAFETY_LINEAGE_MISSING = 'L13Y_SAFETY_LINEAGE_MISSING',
  L13Y_SAFETY_REPLAY_HASH_MISSING = 'L13Y_SAFETY_REPLAY_HASH_MISSING',
}

export const ALL_L13_SAFETY_VIOLATION_CODES:
  readonly L13SafetyViolationCode[] =
  Object.values(L13SafetyViolationCode);
