/**
 * L13.4 — Grounding Violation Codes
 *
 * §13.4.17 — Disjoint `L13G_` namespace.
 */

export enum L13GroundingViolationCode {
  L13G_CLAIM_ID_MISSING = 'L13G_CLAIM_ID_MISSING',
  L13G_OUTPUT_REF_MISSING = 'L13G_OUTPUT_REF_MISSING',
  L13G_INPUT_PACKAGE_REF_MISSING = 'L13G_INPUT_PACKAGE_REF_MISSING',
  L13G_CLAIM_TEXT_MISSING = 'L13G_CLAIM_TEXT_MISSING',
  L13G_CLAIM_TYPE_MISSING = 'L13G_CLAIM_TYPE_MISSING',
  L13G_GROUNDING_CLASS_MISSING = 'L13G_GROUNDING_CLASS_MISSING',
  L13G_SECTION_REF_MISSING = 'L13G_SECTION_REF_MISSING',
  L13G_POLICY_VERSION_MISSING = 'L13G_POLICY_VERSION_MISSING',

  L13G_ALLOWED_CLAIM_WITHOUT_EVIDENCE = 'L13G_ALLOWED_CLAIM_WITHOUT_EVIDENCE',
  L13G_EVIDENCE_REF_NOT_IN_PACKAGE = 'L13G_EVIDENCE_REF_NOT_IN_PACKAGE',
  L13G_CONTRADICTION_REF_NOT_IN_PACKAGE = 'L13G_CONTRADICTION_REF_NOT_IN_PACKAGE',
  L13G_SOURCE_LAYER_REF_MISSING = 'L13G_SOURCE_LAYER_REF_MISSING',
  L13G_LINEAGE_REF_MISSING = 'L13G_LINEAGE_REF_MISSING',
  L13G_REPLAY_HASH_MISSING = 'L13G_REPLAY_HASH_MISSING',

  L13G_UNSUPPORTED_CLAIM_EMITTED = 'L13G_UNSUPPORTED_CLAIM_EMITTED',
  L13G_CONTRADICTED_CLAIM_EMITTED = 'L13G_CONTRADICTED_CLAIM_EMITTED',
  L13G_WEAK_MATCH_USED_AS_STRONG_SUPPORT = 'L13G_WEAK_MATCH_USED_AS_STRONG_SUPPORT',
  L13G_SEMANTIC_MATCH_OVERRIDES_CONTRADICTION = 'L13G_SEMANTIC_MATCH_OVERRIDES_CONTRADICTION',

  L13G_INVENTED_EVIDENCE = 'L13G_INVENTED_EVIDENCE',
  L13G_INVENTED_SCORE_DRIVER = 'L13G_INVENTED_SCORE_DRIVER',
  L13G_INVENTED_SCENARIO_TRIGGER = 'L13G_INVENTED_SCENARIO_TRIGGER',
  L13G_INVENTED_SCENARIO_INVALIDATION = 'L13G_INVENTED_SCENARIO_INVALIDATION',
  L13G_INVENTED_HYPOTHESIS_SUPPORT = 'L13G_INVENTED_HYPOTHESIS_SUPPORT',
  L13G_INVENTED_CONTRADICTION_ABSENCE = 'L13G_INVENTED_CONTRADICTION_ABSENCE',
  L13G_INVENTED_CONFIDENCE = 'L13G_INVENTED_CONFIDENCE',
  L13G_INVENTED_REGIME_STATE = 'L13G_INVENTED_REGIME_STATE',
  L13G_INVENTED_SEQUENCE_STATE = 'L13G_INVENTED_SEQUENCE_STATE',
  L13G_INVENTED_DATA_COMPLETENESS = 'L13G_INVENTED_DATA_COMPLETENESS',
  L13G_INVENTED_FINANCIAL_INSTRUCTION = 'L13G_INVENTED_FINANCIAL_INSTRUCTION',

  L13G_CITATION_PACK_MISSING = 'L13G_CITATION_PACK_MISSING',
  L13G_CITATION_CLAIM_MISSING = 'L13G_CITATION_CLAIM_MISSING',
  L13G_CITATION_REF_UNGOVERNED = 'L13G_CITATION_REF_UNGOVERNED',
  L13G_SCENARIO_CLAIM_WITHOUT_SCENARIO_REF = 'L13G_SCENARIO_CLAIM_WITHOUT_SCENARIO_REF',
  L13G_SCORE_CLAIM_WITHOUT_SCORE_REF = 'L13G_SCORE_CLAIM_WITHOUT_SCORE_REF',
  L13G_HYPOTHESIS_CLAIM_WITHOUT_HYPOTHESIS_REF = 'L13G_HYPOTHESIS_CLAIM_WITHOUT_HYPOTHESIS_REF',
  L13G_CONTRADICTION_CLAIM_WITHOUT_CONTRADICTION_REF = 'L13G_CONTRADICTION_CLAIM_WITHOUT_CONTRADICTION_REF',
  L13G_REGIME_CLAIM_WITHOUT_REGIME_REF = 'L13G_REGIME_CLAIM_WITHOUT_REGIME_REF',
  L13G_SEQUENCE_CLAIM_WITHOUT_SEQUENCE_REF = 'L13G_SEQUENCE_CLAIM_WITHOUT_SEQUENCE_REF',

  L13G_GROUNDING_READINESS_ILLEGAL = 'L13G_GROUNDING_READINESS_ILLEGAL',
  L13G_BLOCK_REQUIRED_BUT_OUTPUT_ALLOWED = 'L13G_BLOCK_REQUIRED_BUT_OUTPUT_ALLOWED',
  L13G_REWRITE_REQUIRED_BUT_NOT_MARKED = 'L13G_REWRITE_REQUIRED_BUT_NOT_MARKED',

  L13G_EXTRACTION_DROPPED_MATERIAL_CLAIM = 'L13G_EXTRACTION_DROPPED_MATERIAL_CLAIM',
  L13G_EXTRACTION_HASH_MISSING = 'L13G_EXTRACTION_HASH_MISSING',

  L13G_EVIDENCE_MATCH_INVALID = 'L13G_EVIDENCE_MATCH_INVALID',
  L13G_CONTRADICTION_MATCH_INVALID = 'L13G_CONTRADICTION_MATCH_INVALID',
  L13G_NO_INVENTION_GATE_INVALID = 'L13G_NO_INVENTION_GATE_INVALID',
  L13G_NO_INVENTION_GATE_BLOCKED = 'L13G_NO_INVENTION_GATE_BLOCKED',

  L13G_ENVELOPE_INVALID = 'L13G_ENVELOPE_INVALID',
  L13G_ENVELOPE_EMIT_WHILE_BLOCK_REQUIRED = 'L13G_ENVELOPE_EMIT_WHILE_BLOCK_REQUIRED',
}

export const ALL_L13_GROUNDING_VIOLATION_CODES:
  readonly L13GroundingViolationCode[] =
  Object.values(L13GroundingViolationCode);

export class L13GroundingError extends Error {
  public readonly code: L13GroundingViolationCode;
  public readonly details: Record<string, unknown>;
  constructor(
    code: L13GroundingViolationCode,
    message: string,
    details: Record<string, unknown> = {},
  ) {
    super(`[${code}] ${message}`);
    this.name = 'L13GroundingError';
    this.code = code;
    this.details = details;
  }
}
