/**
 * L13.5 — Expression Violation Codes
 *
 * §13.5.24 — Disjoint `L13U_` namespace for expression-governance
 * violations. Mirrors the L13.2 / L13.3 / L13.4 violation-code
 * pattern.
 */

export enum L13ExpressionViolationCode {
  L13U_UNCERTAINTY_PROFILE_MISSING = 'L13U_UNCERTAINTY_PROFILE_MISSING',
  L13U_CONFIDENCE_CEILING_MISSING = 'L13U_CONFIDENCE_CEILING_MISSING',
  L13U_REQUIRED_DISCLOSURE_PHRASE_MISSING = 'L13U_REQUIRED_DISCLOSURE_PHRASE_MISSING',
  L13U_FORBIDDEN_CERTAINTY_PHRASE_PRESENT = 'L13U_FORBIDDEN_CERTAINTY_PHRASE_PRESENT',
  L13U_CONTRADICTION_DISCLOSURE_MISSING = 'L13U_CONTRADICTION_DISCLOSURE_MISSING',
  L13U_CONTRADICTION_MINIMIZED = 'L13U_CONTRADICTION_MINIMIZED',
  L13U_CONTRADICTION_OVERRIDDEN = 'L13U_CONTRADICTION_OVERRIDDEN',
  L13U_CONTRADICTION_HIDDEN = 'L13U_CONTRADICTION_HIDDEN',
  L13U_ACTIVE_INVALIDATION_NOT_DISCLOSED = 'L13U_ACTIVE_INVALIDATION_NOT_DISCLOSED',
  L13U_UNRESOLVED_TRIGGER_NOT_DISCLOSED = 'L13U_UNRESOLVED_TRIGGER_NOT_DISCLOSED',
  L13U_MISSING_DATA_NOT_DISCLOSED = 'L13U_MISSING_DATA_NOT_DISCLOSED',
  L13U_DRIFT_NOT_DISCLOSED = 'L13U_DRIFT_NOT_DISCLOSED',
  L13U_SCENARIO_SPREAD_NOT_DISCLOSED = 'L13U_SCENARIO_SPREAD_NOT_DISCLOSED',
  L13U_HYPOTHESIS_SPREAD_NOT_DISCLOSED = 'L13U_HYPOTHESIS_SPREAD_NOT_DISCLOSED',
  L13U_TRANSITION_RISK_NOT_DISCLOSED = 'L13U_TRANSITION_RISK_NOT_DISCLOSED',
  L13U_SEQUENCE_AMBIGUITY_NOT_DISCLOSED = 'L13U_SEQUENCE_AMBIGUITY_NOT_DISCLOSED',
  L13U_CONFIDENCE_OUTRUN = 'L13U_CONFIDENCE_OUTRUN',
  L13U_ASSERTIVE_LANGUAGE_UNDER_LOW_CONFIDENCE = 'L13U_ASSERTIVE_LANGUAGE_UNDER_LOW_CONFIDENCE',
  L13U_CLEAN_LANGUAGE_UNDER_ACTIVE_INVALIDATION = 'L13U_CLEAN_LANGUAGE_UNDER_ACTIVE_INVALIDATION',
  L13U_CERTAINTY_LANGUAGE_UNDER_NARROW_SPREAD = 'L13U_CERTAINTY_LANGUAGE_UNDER_NARROW_SPREAD',
  L13U_RESTRICTION_PROFILE_MISSING = 'L13U_RESTRICTION_PROFILE_MISSING',
  L13U_RESTRICTION_COMPOSITION_ILLEGAL = 'L13U_RESTRICTION_COMPOSITION_ILLEGAL',
  L13U_BLOCKED_USE_REOPENED = 'L13U_BLOCKED_USE_REOPENED',
  L13U_ALLOWED_PHRASE_STRENGTH_EXCEEDS_RESTRICTION = 'L13U_ALLOWED_PHRASE_STRENGTH_EXCEEDS_RESTRICTION',
  L13U_BLOCKED_OUTPUT_USE_EMITTED = 'L13U_BLOCKED_OUTPUT_USE_EMITTED',
  L13U_EXPRESSION_READINESS_ILLEGAL = 'L13U_EXPRESSION_READINESS_ILLEGAL',
  L13U_REWRITE_REQUIRED_BUT_NOT_MARKED = 'L13U_REWRITE_REQUIRED_BUT_NOT_MARKED',
  L13U_REFUSAL_REQUIRED_BUT_NOT_MARKED = 'L13U_REFUSAL_REQUIRED_BUT_NOT_MARKED',
  L13U_BLOCK_REQUIRED_BUT_OUTPUT_ALLOWED = 'L13U_BLOCK_REQUIRED_BUT_OUTPUT_ALLOWED',
  L13U_LINEAGE_MISSING = 'L13U_LINEAGE_MISSING',
  L13U_REPLAY_HASH_MISSING = 'L13U_REPLAY_HASH_MISSING',
  L13U_CONFIDENCE_RAISED_ABOVE_INHERITED = 'L13U_CONFIDENCE_RAISED_ABOVE_INHERITED',
  L13U_ENVELOPE_REF_MISMATCH = 'L13U_ENVELOPE_REF_MISMATCH',
  L13U_PHRASE_CLASS_NOT_PERMITTED = 'L13U_PHRASE_CLASS_NOT_PERMITTED',
}

export const ALL_L13_EXPRESSION_VIOLATION_CODES:
  readonly L13ExpressionViolationCode[] =
  Object.values(L13ExpressionViolationCode);
