/**
 * L13.10 — Persistence/Feedback Violation Codes
 *
 * §13.10.34 — Disjoint `L13D_` namespace (D = durability /
 * data-surfaces).
 */

export enum L13PersistenceFeedbackViolationCode {
  L13D_PERSISTENCE_ENVELOPE_MISSING = 'L13D_PERSISTENCE_ENVELOPE_MISSING',
  L13D_L5_ROUTE_MISSING = 'L13D_L5_ROUTE_MISSING',
  L13D_DIRECT_WRITE_ATTEMPT = 'L13D_DIRECT_WRITE_ATTEMPT',
  L13D_STORAGE_AUTHORITY_ILLEGAL = 'L13D_STORAGE_AUTHORITY_ILLEGAL',
  L13D_INPUT_PACKAGE_NOT_PERSISTED = 'L13D_INPUT_PACKAGE_NOT_PERSISTED',
  L13D_OUTPUT_NOT_PERSISTED = 'L13D_OUTPUT_NOT_PERSISTED',
  L13D_GROUNDED_CLAIM_NOT_PERSISTED = 'L13D_GROUNDED_CLAIM_NOT_PERSISTED',
  L13D_BLOCKED_CLAIM_NOT_PERSISTED = 'L13D_BLOCKED_CLAIM_NOT_PERSISTED',
  L13D_MODEL_RUN_NOT_PERSISTED = 'L13D_MODEL_RUN_NOT_PERSISTED',
  L13D_MODEL_RESPONSE_ARTIFACT_NOT_PERSISTED = 'L13D_MODEL_RESPONSE_ARTIFACT_NOT_PERSISTED',
  L13D_SAFETY_GATE_RESULT_NOT_PERSISTED = 'L13D_SAFETY_GATE_RESULT_NOT_PERSISTED',
  L13D_FINAL_GATE_RESULT_NOT_PERSISTED = 'L13D_FINAL_GATE_RESULT_NOT_PERSISTED',
  L13D_CURRENT_OUTPUT_AUTHORITY_MISSING = 'L13D_CURRENT_OUTPUT_AUTHORITY_MISSING',
  L13D_CURRENT_OUTPUT_SUPERSESSION_ILLEGAL = 'L13D_CURRENT_OUTPUT_SUPERSESSION_ILLEGAL',
  L13D_HISTORICAL_FACT_APPEND_MISSING = 'L13D_HISTORICAL_FACT_APPEND_MISSING',
  L13D_HISTORICAL_FACT_MUTATION_ATTEMPT = 'L13D_HISTORICAL_FACT_MUTATION_ATTEMPT',
  L13D_FEEDBACK_RECORD_INVALID = 'L13D_FEEDBACK_RECORD_INVALID',
  L13D_FEEDBACK_OUTPUT_REF_MISSING = 'L13D_FEEDBACK_OUTPUT_REF_MISSING',
  L13D_FEEDBACK_REASON_CODES_MISSING = 'L13D_FEEDBACK_REASON_CODES_MISSING',
  L13D_FEEDBACK_SUMMARY_NOT_RECOMPUTABLE = 'L13D_FEEDBACK_SUMMARY_NOT_RECOMPUTABLE',
  L13D_QUALITY_METRIC_DEFINITION_INVALID = 'L13D_QUALITY_METRIC_DEFINITION_INVALID',
  L13D_QUALITY_METRIC_DENOMINATOR_INVALID = 'L13D_QUALITY_METRIC_DENOMINATOR_INVALID',
  L13D_QUALITY_EVALUATION_MISSING = 'L13D_QUALITY_EVALUATION_MISSING',
  L13D_AUDIT_EVENT_NOT_DETERMINISTIC = 'L13D_AUDIT_EVENT_NOT_DETERMINISTIC',
  L13D_OUTPUT_FAILURE_NOT_RECORDED = 'L13D_OUTPUT_FAILURE_NOT_RECORDED',
  L13D_READ_SURFACE_UNREGISTERED = 'L13D_READ_SURFACE_UNREGISTERED',
  L13D_READ_SURFACE_EXPOSES_RAW_AUTHORITY = 'L13D_READ_SURFACE_EXPOSES_RAW_AUTHORITY',
  L13D_LINEAGE_MISSING = 'L13D_LINEAGE_MISSING',
  L13D_REPLAY_HASH_MISSING = 'L13D_REPLAY_HASH_MISSING',
}

export const ALL_L13_PERSISTENCE_FEEDBACK_VIOLATION_CODES:
  readonly L13PersistenceFeedbackViolationCode[] =
  Object.values(L13PersistenceFeedbackViolationCode);
