/**
 * L13.8 — Style Violation Codes
 *
 * §13.8.33 — Disjoint `L13S_` namespace.
 */

export enum L13StyleViolationCode {
  L13S_STYLE_CONTROL_PLAN_MISSING = 'L13S_STYLE_CONTROL_PLAN_MISSING',
  L13S_VERBOSITY_PROFILE_MISSING = 'L13S_VERBOSITY_PROFILE_MISSING',
  L13S_PERSONA_PROFILE_MISSING = 'L13S_PERSONA_PROFILE_MISSING',
  L13S_LANGUAGE_PROFILE_MISSING = 'L13S_LANGUAGE_PROFILE_MISSING',
  L13S_RESOLVED_VERBOSITY_MISSING = 'L13S_RESOLVED_VERBOSITY_MISSING',
  L13S_VERBOSITY_BELOW_DISCLOSURE_FLOOR = 'L13S_VERBOSITY_BELOW_DISCLOSURE_FLOOR',
  L13S_ALERT_TOO_LONG = 'L13S_ALERT_TOO_LONG',
  L13S_DEEP_MODE_NOT_EXPANDED = 'L13S_DEEP_MODE_NOT_EXPANDED',
  L13S_REPORT_MODE_NOT_REPORT_SHAPED = 'L13S_REPORT_MODE_NOT_REPORT_SHAPED',
  L13S_PERSONA_HYPE_DETECTED = 'L13S_PERSONA_HYPE_DETECTED',
  L13S_PERSONA_FINANCIAL_ADVISOR_DETECTED = 'L13S_PERSONA_FINANCIAL_ADVISOR_DETECTED',
  L13S_PERSONA_PROPHECY_ENGINE_DETECTED = 'L13S_PERSONA_PROPHECY_ENGINE_DETECTED',
  L13S_PERSONA_SALES_COPY_DETECTED = 'L13S_PERSONA_SALES_COPY_DETECTED',
  L13S_PERSONA_DISCLAIMER_MACHINE_DETECTED = 'L13S_PERSONA_DISCLAIMER_MACHINE_DETECTED',
  L13S_PERSONA_ROBOTIC_DASHBOARD_DETECTED = 'L13S_PERSONA_ROBOTIC_DASHBOARD_DETECTED',
  L13S_OUTPUT_LANGUAGE_UNSUPPORTED = 'L13S_OUTPUT_LANGUAGE_UNSUPPORTED',
  L13S_LANGUAGE_RESOLUTION_MISSING = 'L13S_LANGUAGE_RESOLUTION_MISSING',
  L13S_OUTPUT_LANGUAGE_MISMATCH = 'L13S_OUTPUT_LANGUAGE_MISMATCH',
  L13S_UNAUTHORIZED_CODE_SWITCH = 'L13S_UNAUTHORIZED_CODE_SWITCH',
  L13S_MULTILINGUAL_TRADE_ADVICE_LEAK = 'L13S_MULTILINGUAL_TRADE_ADVICE_LEAK',
  L13S_MULTILINGUAL_CERTAINTY_LEAK = 'L13S_MULTILINGUAL_CERTAINTY_LEAK',
  L13S_MULTILINGUAL_PUMP_DUMP_PROPHECY = 'L13S_MULTILINGUAL_PUMP_DUMP_PROPHECY',
  L13S_MULTILINGUAL_SCORE_AS_ACTION = 'L13S_MULTILINGUAL_SCORE_AS_ACTION',
  L13S_MULTILINGUAL_SCENARIO_AS_CERTAINTY = 'L13S_MULTILINGUAL_SCENARIO_AS_CERTAINTY',
  L13S_STYLE_REMOVED_UNCERTAINTY = 'L13S_STYLE_REMOVED_UNCERTAINTY',
  L13S_STYLE_REMOVED_CONTRADICTION = 'L13S_STYLE_REMOVED_CONTRADICTION',
  L13S_STYLE_REMOVED_TRIGGER = 'L13S_STYLE_REMOVED_TRIGGER',
  L13S_STYLE_REMOVED_INVALIDATION = 'L13S_STYLE_REMOVED_INVALIDATION',
  L13S_STYLE_REMOVED_RESTRICTION = 'L13S_STYLE_REMOVED_RESTRICTION',
  L13S_STYLE_ADDED_NEW_CLAIM = 'L13S_STYLE_ADDED_NEW_CLAIM',
  L13S_STYLE_STRENGTHENED_CONFIDENCE = 'L13S_STYLE_STRENGTHENED_CONFIDENCE',
  L13S_STYLE_WEAKENED_DISCLOSURE = 'L13S_STYLE_WEAKENED_DISCLOSURE',
  L13S_STYLED_ENVELOPE_MISSING = 'L13S_STYLED_ENVELOPE_MISSING',
  L13S_STYLE_READINESS_ILLEGAL = 'L13S_STYLE_READINESS_ILLEGAL',
  L13S_STYLE_LINEAGE_MISSING = 'L13S_STYLE_LINEAGE_MISSING',
  L13S_STYLE_REPLAY_HASH_MISSING = 'L13S_STYLE_REPLAY_HASH_MISSING',
}

export const ALL_L13_STYLE_VIOLATION_CODES:
  readonly L13StyleViolationCode[] =
  Object.values(L13StyleViolationCode);
