/**
 * L13.12 — Final / Freeze Violation Codes
 *
 * §13.12.20 — Disjoint `L13F_` namespace.
 */

export enum L13FinalViolationCode {
  L13F_FINAL_DEFINITION_MISSING = 'L13F_FINAL_DEFINITION_MISSING',
  L13F_COMPLETION_STANDARD_MISSING = 'L13F_COMPLETION_STANDARD_MISSING',
  L13F_REQUIRED_SUBLAYER_NOT_GREEN = 'L13F_REQUIRED_SUBLAYER_NOT_GREEN',
  L13F_REQUIRED_BAND_NOT_GREEN = 'L13F_REQUIRED_BAND_NOT_GREEN',
  L13F_FINAL_INVARIANT_NOT_GREEN = 'L13F_FINAL_INVARIANT_NOT_GREEN',
  L13F_CERTIFICATION_REPORT_MISSING = 'L13F_CERTIFICATION_REPORT_MISSING',
  L13F_CERTIFICATION_LEVEL_ILLEGAL = 'L13F_CERTIFICATION_LEVEL_ILLEGAL',
  L13F_CRITICAL_VIOLATION_COUNT_NONZERO = 'L13F_CRITICAL_VIOLATION_COUNT_NONZERO',
  L13F_ROLLOUT_BLOCKING_REGRESSION_NONZERO = 'L13F_ROLLOUT_BLOCKING_REGRESSION_NONZERO',
  L13F_RATIFICATION_ARTIFACT_MISSING = 'L13F_RATIFICATION_ARTIFACT_MISSING',
  L13F_RATIFICATION_FINGERPRINT_MISSING = 'L13F_RATIFICATION_FINGERPRINT_MISSING',
  L13F_RATIFICATION_EMITTED_BEFORE_GREEN = 'L13F_RATIFICATION_EMITTED_BEFORE_GREEN',
  L13F_ROLLOUT_GATE_NOT_APPROVED = 'L13F_ROLLOUT_GATE_NOT_APPROVED',
  L13F_ROLLBACK_POLICY_MISSING = 'L13F_ROLLBACK_POLICY_MISSING',
  L13F_FAILURE_PLAYBOOKS_MISSING = 'L13F_FAILURE_PLAYBOOKS_MISSING',
  L13F_FREEZE_POLICY_MISSING = 'L13F_FREEZE_POLICY_MISSING',
  L13F_FREEZE_ACTIVATED_WITHOUT_GREEN = 'L13F_FREEZE_ACTIVATED_WITHOUT_GREEN',
  L13F_PROHIBITED_EXTENSION_ALLOWED = 'L13F_PROHIBITED_EXTENSION_ALLOWED',
  L13F_L14_HANDOFF_NOT_APPROVED = 'L13F_L14_HANDOFF_NOT_APPROVED',
  L13F_L14_REBUILD_ALLOWANCE_DETECTED = 'L13F_L14_REBUILD_ALLOWANCE_DETECTED',
  L13F_FINAL_AUDIT_NONDETERMINISTIC = 'L13F_FINAL_AUDIT_NONDETERMINISTIC',
  L13F_LINEAGE_MISSING = 'L13F_LINEAGE_MISSING',
  L13F_REPLAY_HASH_MISSING = 'L13F_REPLAY_HASH_MISSING',
}

export const ALL_L13_FINAL_VIOLATION_CODES:
  readonly L13FinalViolationCode[] =
  Object.values(L13FinalViolationCode);
