import React from 'react';
import { Card } from '@/components/ui/Card/Card';
import { useTheme } from '@/contexts/ThemeContext';

const VideoAI = () => {
  const { tokens } = useTheme();
  return (
    <Card style={{ borderRadius: tokens.borderRadius.lg, boxShadow: tokens.shadow.md, padding: '24px', minWidth: 400 }}>
      <div style={{ fontSize: 24, fontWeight: 600, marginBottom: 16 }}>AI Insights</div>
      <div style={{ fontSize: 16, fontWeight: 400, marginBottom: 8 }}>Summary: This video covers advanced trading strategies for BTC and ETH.</div>
      <div style={{ fontSize: 16, fontWeight: 400, color: tokens.colors.accent, marginBottom: 8 }}>Recommendation: Try the "MomentumX" strategy for higher returns.</div>
      <div style={{ fontSize: 13, fontWeight: 400, color: tokens.colors.primary }}>Generated by Coinet AI</div>
    </Card>
  );
};
export default VideoAI; 