apiVersion: v1
kind: Secret
metadata:
  name: coinet-secrets
  labels:
    app: coinet
    managed-by: helm
    environment: production
    chart: coinet-secrets
    release: coinet
    heritage: Helm
    version: v1
    description: "Secrets for Coinet platform"
stringData:
  POSTGRES_PASSWORD: "supersecurepassword"
  DATABASE_URL: "postgres://coinet:supersecurepassword@coinet-postgres:5432/coinet" 