/**
 * Canonical evidence key → signal extraction mapping.
 * Shared between evidence-mapper.ts and invalidation-engine.ts.
 */

import type { SignalSnapshot } from '../judgment/types';

export interface EvidenceKeyMapping {
  key: string;
  extract: (s: SignalSnapshot) => number;
  sourceDomains: string[];
}

export const EVIDENCE_KEY_MAP: Record<string, EvidenceKeyMapping> = {
  'whale.activity.rising':         { key: 'whale.activity.rising',         extract: s => s.whale_activity,               sourceDomains: ['onchain_behavior'] },
  'whale.activity.absent':         { key: 'whale.activity.absent',         extract: s => 1 - s.whale_activity,           sourceDomains: ['onchain_behavior'] },
  'whale.activity.declining':      { key: 'whale.activity.declining',      extract: s => 1 - s.whale_activity,           sourceDomains: ['onchain_behavior'] },
  'whale.activity.moderate':       { key: 'whale.activity.moderate',       extract: s => Math.min(1, s.whale_activity * 2), sourceDomains: ['onchain_behavior'] },
  'whale.activity.low':            { key: 'whale.activity.low',            extract: s => 1 - s.whale_activity,           sourceDomains: ['onchain_behavior'] },
  'whale.accumulation.clean':      { key: 'whale.accumulation.clean',      extract: s => s.whale_activity,               sourceDomains: ['onchain_behavior', 'entity_context'] },
  'whale.accumulation.present':    { key: 'whale.accumulation.present',    extract: s => s.whale_activity,               sourceDomains: ['onchain_behavior'] },
  'whale.still_active':            { key: 'whale.still_active',            extract: s => s.whale_activity,               sourceDomains: ['onchain_behavior'] },
  'whale.accumulation.absorbing_supply': { key: 'whale.accumulation.absorbing_supply', extract: s => s.whale_activity, sourceDomains: ['onchain_behavior'] },
  'whale.activity.distribution_pattern': { key: 'whale.activity.distribution_pattern', extract: s => s.exchange_inflow * (1 - s.whale_activity), sourceDomains: ['onchain_behavior'] },
  'exchange.outflow.elevated':     { key: 'exchange.outflow.elevated',     extract: s => s.exchange_outflow,             sourceDomains: ['onchain_behavior'] },
  'exchange.inflow.elevated':      { key: 'exchange.inflow.elevated',      extract: s => s.exchange_inflow,              sourceDomains: ['onchain_behavior'] },
  'leverage.pressure.low':         { key: 'leverage.pressure.low',         extract: s => 1 - s.leverage_pressure,        sourceDomains: ['derivatives_pressure'] },
  'leverage.pressure.moderate':    { key: 'leverage.pressure.moderate',    extract: s => 1 - Math.abs(s.leverage_pressure - 0.4), sourceDomains: ['derivatives_pressure'] },
  'leverage.pressure.extreme':     { key: 'leverage.pressure.extreme',     extract: s => s.leverage_pressure,            sourceDomains: ['derivatives_pressure'] },
  'leverage.over.spot':            { key: 'leverage.over.spot',            extract: s => Math.max(0, s.leverage_pressure - s.volume_24h), sourceDomains: ['derivatives_pressure', 'market_surface'] },
  'narrative.intensity.low':       { key: 'narrative.intensity.low',       extract: s => 1 - s.narrative_intensity,      sourceDomains: ['narrative_attention'] },
  'narrative.intensity.moderate':  { key: 'narrative.intensity.moderate',  extract: s => 1 - Math.abs(s.narrative_intensity - 0.4) * 2, sourceDomains: ['narrative_attention'] },
  'narrative.intensity.high':      { key: 'narrative.intensity.high',      extract: s => s.narrative_intensity,          sourceDomains: ['narrative_attention'] },
  'narrative.intensity.high_without_fundamentals': { key: 'narrative.intensity.high_without_fundamentals', extract: s => s.narrative_intensity * (1 - s.fundamentals_strength), sourceDomains: ['narrative_attention', 'protocol_substance'] },
  'narrative.specific_to_asset':   { key: 'narrative.specific_to_asset',   extract: () => 0.5,                           sourceDomains: ['narrative_attention'] },
  'price.momentum.modest_positive': { key: 'price.momentum.modest_positive', extract: s => Math.max(0, Math.min(1, (s.price_momentum_24h + 0.1) / 0.3)), sourceDomains: ['market_surface'] },
  'price.momentum.positive':      { key: 'price.momentum.positive',       extract: s => Math.max(0, Math.min(1, s.price_momentum_24h / 0.3)), sourceDomains: ['market_surface'] },
  'price.momentum.moderate_positive': { key: 'price.momentum.moderate_positive', extract: s => Math.max(0, Math.min(1, s.price_momentum_24h / 0.2)), sourceDomains: ['market_surface'] },
  'price.momentum.negative':      { key: 'price.momentum.negative',       extract: s => Math.max(0, -s.price_momentum_24h / 0.2), sourceDomains: ['market_surface'] },
  'price.momentum.sharp_negative': { key: 'price.momentum.sharp_negative', extract: s => Math.max(0, -s.price_momentum_24h / 0.3), sourceDomains: ['market_surface'] },
  'price.momentum.flat':          { key: 'price.momentum.flat',            extract: s => 1 - Math.min(1, Math.abs(s.price_momentum_24h) / 0.1), sourceDomains: ['market_surface'] },
  'price.momentum.rapid':         { key: 'price.momentum.rapid',           extract: s => Math.min(1, Math.abs(s.price_momentum_1h) / 0.2), sourceDomains: ['market_surface'] },
  'price.momentum.stabilizing':   { key: 'price.momentum.stabilizing',    extract: s => 1 - Math.min(1, Math.abs(s.price_momentum_24h) / 0.05), sourceDomains: ['market_surface'] },
  'price.momentum.stalling':      { key: 'price.momentum.stalling',       extract: s => 1 - Math.min(1, Math.abs(s.price_momentum_24h) / 0.05), sourceDomains: ['market_surface'] },
  'volume.moderate':              { key: 'volume.moderate',                extract: s => Math.max(0, 1 - Math.abs(s.volume_24h - 0.3) * 3), sourceDomains: ['market_surface'] },
  'volume.strong':                { key: 'volume.strong',                  extract: s => Math.min(1, s.volume_24h / 0.5), sourceDomains: ['market_surface'] },
  'volume.still_elevated':        { key: 'volume.still_elevated',          extract: s => Math.min(1, s.volume_24h / 0.4), sourceDomains: ['market_surface'] },
  'volume.declining':             { key: 'volume.declining',               extract: s => Math.max(0, 1 - s.volume_24h),   sourceDomains: ['market_surface'] },
  'oi.velocity.high':             { key: 'oi.velocity.high',              extract: s => s.leverage_pressure,             sourceDomains: ['derivatives_pressure'] },
  'oi.velocity.collapsing':       { key: 'oi.velocity.collapsing',        extract: s => 1 - s.leverage_pressure,         sourceDomains: ['derivatives_pressure'] },
  'funding.rate.stretched':       { key: 'funding.rate.stretched',         extract: s => s.funding_rate,                 sourceDomains: ['derivatives_pressure'] },
  'funding.rate.reset':           { key: 'funding.rate.reset',             extract: s => 1 - s.funding_rate,             sourceDomains: ['derivatives_pressure'] },
  'funding.rate.extreme':         { key: 'funding.rate.extreme',           extract: s => s.funding_rate,                 sourceDomains: ['derivatives_pressure'] },
  'funding.cooling_while_price_holds': { key: 'funding.cooling_while_price_holds', extract: s => Math.max(0, (1 - s.funding_rate) * Math.max(0, s.price_momentum_24h + 0.05)), sourceDomains: ['derivatives_pressure', 'market_surface'] },
  'liquidation.cluster.near_spot': { key: 'liquidation.cluster.near_spot', extract: s => s.liquidation_density,         sourceDomains: ['derivatives_pressure'] },
  'liquidation.density.elevated': { key: 'liquidation.density.elevated',   extract: s => s.liquidation_density,          sourceDomains: ['derivatives_pressure'] },
  'liquidation.density.extreme':  { key: 'liquidation.density.extreme',    extract: s => s.liquidation_density,          sourceDomains: ['derivatives_pressure'] },
  'liquidation.density.low':      { key: 'liquidation.density.low',        extract: s => 1 - s.liquidation_density,      sourceDomains: ['derivatives_pressure'] },
  'spot.volume.strong_relative':  { key: 'spot.volume.strong_relative',    extract: s => Math.max(0, s.volume_24h - s.leverage_pressure), sourceDomains: ['market_surface', 'derivatives_pressure'] },
  'spot.over.leverage':           { key: 'spot.over.leverage',             extract: s => Math.max(0, s.volume_24h - s.leverage_pressure), sourceDomains: ['market_surface', 'derivatives_pressure'] },
  'fundamentals.strength.high':   { key: 'fundamentals.strength.high',    extract: s => s.fundamentals_strength,         sourceDomains: ['protocol_substance'] },
  'fundamentals.strength.improving': { key: 'fundamentals.strength.improving', extract: s => s.fundamentals_strength,    sourceDomains: ['protocol_substance'] },
  'fundamentals.weak':            { key: 'fundamentals.weak',              extract: s => 1 - s.fundamentals_strength,    sourceDomains: ['protocol_substance'] },
  'tvl.trend.positive':           { key: 'tvl.trend.positive',            extract: s => s.tvl_trend,                    sourceDomains: ['protocol_substance'] },
  'tvl.trend.negative':           { key: 'tvl.trend.negative',            extract: s => 1 - s.tvl_trend,               sourceDomains: ['protocol_substance'] },
  'tvl.vs_inflows.divergent':     { key: 'tvl.vs_inflows.divergent',      extract: s => Math.abs(s.tvl_trend - s.fundamentals_strength), sourceDomains: ['protocol_substance'] },
  'revenue.quality.improving':    { key: 'revenue.quality.improving',      extract: s => s.revenue_quality,              sourceDomains: ['protocol_substance'] },
  'protocol.inflows.strong':      { key: 'protocol.inflows.strong',        extract: s => s.fundamentals_strength,        sourceDomains: ['protocol_substance'] },
  'security.risk.elevated':       { key: 'security.risk.elevated',        extract: s => s.security_risk,                sourceDomains: ['structural_safety'] },
  'security.risk.low':            { key: 'security.risk.low',             extract: s => 1 - s.security_risk,            sourceDomains: ['structural_safety'] },
  'holder.concentration.high':    { key: 'holder.concentration.high',      extract: s => s.holder_concentration,         sourceDomains: ['structural_safety'] },
  'holder.distribution.healthy':  { key: 'holder.distribution.healthy',    extract: s => 1 - s.holder_concentration,     sourceDomains: ['structural_safety'] },
  'liquidity.thin':               { key: 'liquidity.thin',                extract: s => 1 - s.liquidity,                sourceDomains: ['dex_emergence'] },
  'liquidity.improving':          { key: 'liquidity.improving',            extract: s => s.liquidity,                    sourceDomains: ['dex_emergence'] },
  'liquidity.depth.improving':    { key: 'liquidity.depth.improving',      extract: s => s.liquidity,                    sourceDomains: ['dex_emergence'] },
  'pair.age.very_new':            { key: 'pair.age.very_new',             extract: s => s.pair_age_hours !== null && s.pair_age_hours < 48 ? 1 : s.pair_age_hours !== null && s.pair_age_hours < 168 ? 0.5 : 0, sourceDomains: ['dex_emergence'] },
  'sentiment.elevated':           { key: 'sentiment.elevated',            extract: s => Math.max(0, s.sentiment),        sourceDomains: ['narrative_attention'] },
  'sentiment.negative':           { key: 'sentiment.negative',            extract: s => Math.max(0, -s.sentiment + 0.3), sourceDomains: ['narrative_attention'] },
  'buy_sell.ratio.healthy':       { key: 'buy_sell.ratio.healthy',        extract: s => s.buy_sell_ratio,               sourceDomains: ['market_surface'] },
  'buy_sell.ratio.weak':          { key: 'buy_sell.ratio.weak',           extract: s => 1 - s.buy_sell_ratio,           sourceDomains: ['market_surface'] },
  'unlock.pressure.high':         { key: 'unlock.pressure.high',          extract: s => s.unlock_pressure,              sourceDomains: ['protocol_substance'] },
  'price.vs_fundamentals.overextended': { key: 'price.vs_fundamentals.overextended', extract: s => Math.max(0, s.price_momentum_24h - s.fundamentals_strength), sourceDomains: ['market_surface', 'protocol_substance'] },
  'whale.entry.late_stage':       { key: 'whale.entry.late_stage',        extract: s => s.whale_activity * s.narrative_intensity, sourceDomains: ['onchain_behavior', 'narrative_attention'] },
};
