/**
 * L11.4 — Attribution Summary Codes (§11.4.12)
 *
 * Stable enum of explanation summary codes. The summary-code
 * deriver is the only path that may attach codes; validators reject
 * codes that lack supporting contributions.
 */

export enum L11AttributionSummaryCode {
  SCORE_HIGH_DUE_TO_PRIMARY_COMPONENTS = 'SCORE_HIGH_DUE_TO_PRIMARY_COMPONENTS',
  SCORE_LOW_DUE_TO_PRIMARY_WEAKNESS = 'SCORE_LOW_DUE_TO_PRIMARY_WEAKNESS',
  SCORE_CAPPED_BY_CONTRADICTION = 'SCORE_CAPPED_BY_CONTRADICTION',
  SCORE_CAPPED_BY_MISSING_DATA = 'SCORE_CAPPED_BY_MISSING_DATA',
  SCORE_REDUCED_BY_REGIME = 'SCORE_REDUCED_BY_REGIME',
  SCORE_REDUCED_BY_SEQUENCE = 'SCORE_REDUCED_BY_SEQUENCE',
  SCORE_REDUCED_BY_HYPOTHESIS_RELIANCE = 'SCORE_REDUCED_BY_HYPOTHESIS_RELIANCE',
  SCORE_RAISED_BY_REGIME = 'SCORE_RAISED_BY_REGIME',
  SCORE_RAISED_BY_SEQUENCE = 'SCORE_RAISED_BY_SEQUENCE',
  SCORE_RAISED_BY_HYPOTHESIS_RELIANCE = 'SCORE_RAISED_BY_HYPOTHESIS_RELIANCE',
  SCORE_LIMITED_BY_MISSING_REQUIRED_INPUTS = 'SCORE_LIMITED_BY_MISSING_REQUIRED_INPUTS',
  SCORE_LIMITED_BY_DEGRADED_VISIBILITY = 'SCORE_LIMITED_BY_DEGRADED_VISIBILITY',
}

export const ALL_L11_ATTRIBUTION_SUMMARY_CODES:
  readonly L11AttributionSummaryCode[] =
  Object.values(L11AttributionSummaryCode);
