/**
 * L11.1 — Constitutional Violation Codes
 *
 * §11.1.13 / §11.1.16 — Every constitutional boundary failure carries
 * a typed code so audit records and validator decisions remain
 * deterministic.
 */

export enum L11ConstitutionalViolationCode {
  UNREGISTERED_DEPENDENCY = 'L11_UNREG_DEPENDENCY',
  UNREGISTERED_OUTPUT = 'L11_UNREG_OUTPUT',
  ILLEGAL_DEPENDENCY_USAGE = 'L11_ILLEGAL_DEP_USAGE',
  ILLEGAL_OUTPUT_CLASS = 'L11_ILLEGAL_OUTPUT_CLASS',
  ILLEGAL_CAPABILITY_CLAIM = 'L11_ILLEGAL_CAPABILITY',

  FORBIDDEN_JUDGMENT_SEMANTICS = 'L11_FORBIDDEN_JUDGMENT',
  FORBIDDEN_RECOMMENDATION_SEMANTICS = 'L11_FORBIDDEN_RECOMMENDATION',
  FORBIDDEN_SCENARIO_SEMANTICS = 'L11_FORBIDDEN_SCENARIO',
  FORBIDDEN_TRADE_ACTION_SEMANTICS = 'L11_FORBIDDEN_TRADE_ACTION',
  FORBIDDEN_VIBE_SCORE = 'L11_FORBIDDEN_VIBE_SCORE',

  MEANING_CLAIM_ABSENT = 'L11_MEANING_CLAIM_ABSENT',
  DIRECTION_UNDECLARED = 'L11_DIRECTION_UNDECLARED',
  DIRECTION_MIXED = 'L11_DIRECTION_MIXED',
  ATTRIBUTION_ABSENT = 'L11_ATTRIBUTION_ABSENT',
  VERSION_ABSENT = 'L11_VERSION_ABSENT',

  MISSING_DATA_LAUNDERING = 'L11_MISSING_DATA_LAUNDERING',
  CONTRADICTION_LAUNDERING = 'L11_CONTRADICTION_LAUNDERING',

  HYPOTHESIS_SPREAD_IGNORED = 'L11_HYPOTHESIS_SPREAD_IGNORED',
  HYPOTHESIS_RELIANCE_IGNORED = 'L11_HYPOTHESIS_RELIANCE_IGNORED',
  HYPOTHESIS_POSTURE_IGNORED = 'L11_HYPOTHESIS_POSTURE_IGNORED',
  L10_HYPOTHESIS_REBUILD = 'L11_L10_HYPOTHESIS_REBUILD',

  LOWER_LAYER_REBUILD = 'L11_LOWER_LAYER_REBUILD',
  L7_LIVE_REVALIDATION = 'L11_L7_LIVE_REVALIDATION',
  REGIME_RECLASSIFICATION = 'L11_REGIME_RECLASSIFICATION',
  SEQUENCE_REINTERPRETATION = 'L11_SEQUENCE_REINTERPRETATION',
  IDENTITY_REDEFINITION = 'L11_IDENTITY_REDEFINITION',
  METRIC_REDEFINITION = 'L11_METRIC_REDEFINITION',
  GRAPH_REDEFINITION = 'L11_GRAPH_REDEFINITION',
  PRIMITIVE_REDEFINITION = 'L11_PRIMITIVE_REDEFINITION',

  RESTRICTION_BYPASS = 'L11_RESTRICTION_BYPASS',
  RESTRICTION_POSTURE_IGNORED = 'L11_RESTRICTION_POSTURE_IGNORED',
  REGIME_POSTURE_IGNORED = 'L11_REGIME_POSTURE_IGNORED',
  SEQUENCE_POSTURE_IGNORED = 'L11_SEQUENCE_POSTURE_IGNORED',

  STORAGE_BYPASS = 'L11_STORAGE_BYPASS',
  MISSING_LINEAGE = 'L11_MISSING_LINEAGE',
  LATE_LAYER_CONSUMPTION = 'L11_LATE_LAYER_CONSUMPTION',

  CALIBRATION_HOOK_ABSENT = 'L11_CALIBRATION_HOOK_ABSENT',
  DRIFT_HOOK_ABSENT = 'L11_DRIFT_HOOK_ABSENT',
  SCORE_AS_ACTION = 'L11_SCORE_AS_ACTION',
}

export const ALL_L11_VIOLATION_CODES:
  readonly L11ConstitutionalViolationCode[] =
  Object.values(L11ConstitutionalViolationCode);

export class L11ConstitutionalError extends Error {
  public readonly code: L11ConstitutionalViolationCode;
  public readonly details: Record<string, unknown>;

  constructor(
    code: L11ConstitutionalViolationCode,
    message: string,
    details: Record<string, unknown> = {},
  ) {
    super(`[${code}] ${message}`);
    this.name = 'L11ConstitutionalError';
    this.code = code;
    this.details = details;
  }
}
