/**
 * L1.2 CI Authority Registry
 */

import type { CryptoTruthDomain, SourceAuthorityObject } from './types';

export const CRYPTO_FIELD_DOMAIN_MAP: Record<string, CryptoTruthDomain> = {
  signature_scheme_family: 'protocol_structure',
  signature_scheme_variant: 'protocol_structure',
  address_or_account_model: 'protocol_structure',
  public_key_exposure_model: 'protocol_structure',
  trusted_setup_dependency: 'protocol_structure',
  validator_key_model: 'governance_upgrade',
  admin_key_model: 'governance_upgrade',

  key_exposure_state: 'onchain_exposure',
  address_reuse_rate: 'onchain_exposure',
  cross_chain_exposure_risk: 'onchain_exposure',
  exposure_surface_class: 'onchain_exposure',
  exposure_confidence: 'onchain_exposure',

  pqc_support_status: 'pqc_readiness',
  pqc_migration_stage: 'pqc_readiness',
  migration_velocity: 'pqc_readiness',
  upgrade_dependency_risk: 'governance_upgrade',

  cryptographic_attack_surface: 'vulnerability_modeling',
  overall_fragility_class: 'vulnerability_modeling',

  dormant_vulnerable_supply: 'dormant_supply',
};

const NOW = () => new Date().toISOString();

export const CRYPTO_AUTHORITY_SOURCES: SourceAuthorityObject[] = [
  {
    source_id: 'client_repo',
    source_type: 'code_repository',
    truth_domain: 'protocol_structure',
    authority_level: 'primary',
    trust_class: 'verified',
    freshness: 0.9,
    coverage: 0.85,
    reliability_score: 0.92,
    last_updated: NOW(),
    conflict_history: [],
  },
  {
    source_id: 'audited_spec',
    source_type: 'specification',
    truth_domain: 'protocol_structure',
    authority_level: 'primary',
    trust_class: 'audited',
    freshness: 0.85,
    coverage: 0.88,
    reliability_score: 0.9,
    last_updated: NOW(),
    conflict_history: [],
  },
  {
    source_id: 'official_docs',
    source_type: 'statement',
    truth_domain: 'protocol_structure',
    authority_level: 'secondary',
    trust_class: 'official',
    freshness: 0.9,
    coverage: 0.9,
    reliability_score: 0.82,
    last_updated: NOW(),
    conflict_history: [],
  },
  {
    source_id: 'onchain_observer',
    source_type: 'onchain_observation',
    truth_domain: 'onchain_exposure',
    authority_level: 'primary',
    trust_class: 'verified',
    freshness: 0.95,
    coverage: 0.86,
    reliability_score: 0.94,
    last_updated: NOW(),
    conflict_history: [],
  },
  {
    source_id: 'validated_indexer',
    source_type: 'indexing_system',
    truth_domain: 'onchain_exposure',
    authority_level: 'secondary',
    trust_class: 'third_party',
    freshness: 0.9,
    coverage: 0.9,
    reliability_score: 0.82,
    last_updated: NOW(),
    conflict_history: [],
  },
  {
    source_id: 'mainnet_activation',
    source_type: 'deployed_reality',
    truth_domain: 'pqc_readiness',
    authority_level: 'primary',
    trust_class: 'verified',
    freshness: 0.9,
    coverage: 0.7,
    reliability_score: 0.95,
    last_updated: NOW(),
    conflict_history: [],
  },
  {
    source_id: 'testnet_activation',
    source_type: 'deployed_reality',
    truth_domain: 'pqc_readiness',
    authority_level: 'secondary',
    trust_class: 'verified',
    freshness: 0.85,
    coverage: 0.65,
    reliability_score: 0.86,
    last_updated: NOW(),
    conflict_history: [],
  },
  {
    source_id: 'governance_proposal',
    source_type: 'proposal',
    truth_domain: 'pqc_readiness',
    authority_level: 'supporting',
    trust_class: 'official',
    freshness: 0.75,
    coverage: 0.55,
    reliability_score: 0.7,
    last_updated: NOW(),
    conflict_history: [],
  },
  {
    source_id: 'peer_reviewed_research',
    source_type: 'research',
    truth_domain: 'vulnerability_modeling',
    authority_level: 'primary',
    trust_class: 'audited',
    freshness: 0.75,
    coverage: 0.68,
    reliability_score: 0.88,
    last_updated: NOW(),
    conflict_history: [],
  },
  {
    source_id: 'security_firm_report',
    source_type: 'security_report',
    truth_domain: 'vulnerability_modeling',
    authority_level: 'secondary',
    trust_class: 'third_party',
    freshness: 0.82,
    coverage: 0.72,
    reliability_score: 0.8,
    last_updated: NOW(),
    conflict_history: [],
  },
  {
    source_id: 'internal_model',
    source_type: 'inference',
    truth_domain: 'vulnerability_modeling',
    authority_level: 'supporting',
    trust_class: 'modeled',
    freshness: 0.9,
    coverage: 0.8,
    reliability_score: 0.66,
    last_updated: NOW(),
    conflict_history: [],
  },
  {
    source_id: 'onchain_cluster_estimator',
    source_type: 'onchain_observation',
    truth_domain: 'dormant_supply',
    authority_level: 'primary',
    trust_class: 'verified',
    freshness: 0.8,
    coverage: 0.7,
    reliability_score: 0.9,
    last_updated: NOW(),
    conflict_history: [],
  },
  {
    source_id: 'statistical_model',
    source_type: 'inference',
    truth_domain: 'dormant_supply',
    authority_level: 'secondary',
    trust_class: 'modeled',
    freshness: 0.85,
    coverage: 0.75,
    reliability_score: 0.72,
    last_updated: NOW(),
    conflict_history: [],
  },
  {
    source_id: 'executed_governance',
    source_type: 'governance_action',
    truth_domain: 'governance_upgrade',
    authority_level: 'primary',
    trust_class: 'verified',
    freshness: 0.85,
    coverage: 0.8,
    reliability_score: 0.9,
    last_updated: NOW(),
    conflict_history: [],
  },
  {
    source_id: 'approved_proposal',
    source_type: 'proposal',
    truth_domain: 'governance_upgrade',
    authority_level: 'secondary',
    trust_class: 'official',
    freshness: 0.8,
    coverage: 0.65,
    reliability_score: 0.78,
    last_updated: NOW(),
    conflict_history: [],
  },
  {
    source_id: 'governance_discussion',
    source_type: 'statement',
    truth_domain: 'governance_upgrade',
    authority_level: 'supporting',
    trust_class: 'official',
    freshness: 0.75,
    coverage: 0.55,
    reliability_score: 0.62,
    last_updated: NOW(),
    conflict_history: [],
  },
];

export function getDomainForField(fieldId: string): CryptoTruthDomain {
  return CRYPTO_FIELD_DOMAIN_MAP[fieldId] ?? 'vulnerability_modeling';
}

export function getSourcesForDomain(domain: CryptoTruthDomain): SourceAuthorityObject[] {
  return CRYPTO_AUTHORITY_SOURCES.filter(s => s.truth_domain === domain);
}

export function getSourceById(sourceId: string): SourceAuthorityObject | undefined {
  return CRYPTO_AUTHORITY_SOURCES.find(s => s.source_id === sourceId);
}
