/**
 * L5.5 Write Coordination — Error Codes
 */

export enum L5CoordinationErrorCode {
  PREFLIGHT_REJECTED = 'L5_COORD_PREFLIGHT_REJECTED',
  DUPLICATE_CONFLICT = 'L5_COORD_DUPLICATE_CONFLICT',
  ARCHIVE_WRITE_RETRYABLE = 'L5_COORD_ARCHIVE_WRITE_RETRYABLE',
  ARCHIVE_INTEGRITY_FATAL = 'L5_COORD_ARCHIVE_INTEGRITY_FATAL',
  AUTHORITY_TX_FAILED = 'L5_COORD_AUTHORITY_TX_FAILED',
  AUTHORITY_WRITE_FATAL = 'L5_COORD_AUTHORITY_WRITE_FATAL',
  OUTBOX_EMIT_FAILED = 'L5_COORD_OUTBOX_EMIT_FAILED',
  PROJECTION_RETRYABLE = 'L5_COORD_PROJECTION_RETRYABLE',
  PROJECTION_FATAL = 'L5_COORD_PROJECTION_FATAL',
  PROJECTION_QUARANTINED = 'L5_COORD_PROJECTION_QUARANTINED',
  FINALIZATION_BLOCKED = 'L5_COORD_FINALIZATION_BLOCKED',
  REPAIR_EXHAUSTED = 'L5_COORD_REPAIR_EXHAUSTED',
  DIRECT_DUAL_WRITE = 'L5_COORD_DIRECT_DUAL_WRITE',
  ENVELOPE_NOT_RESOLVED = 'L5_COORD_ENVELOPE_NOT_RESOLVED',
  ILLEGAL_MANIFEST_TRANSITION = 'L5_COORD_ILLEGAL_MANIFEST_TRANSITION',
  LATE_DATA_SILENT_OVERWRITE = 'L5_COORD_LATE_DATA_SILENT_OVERWRITE',
  READ_PROJECTION_AS_AUTHORITY = 'L5_COORD_READ_PROJECTION_AS_AUTHORITY',
}

export class L5CoordinationError extends Error {
  public readonly code: L5CoordinationErrorCode;
  public readonly details: Record<string, unknown>;

  constructor(code: L5CoordinationErrorCode, message: string, details: Record<string, unknown> = {}) {
    super(`[${code}] ${message}`);
    this.name = 'L5CoordinationError';
    this.code = code;
    this.details = details;
  }
}
