/**
 * L8.8 — Persistence / Materialization / Read Violation Codes
 *
 * §8.8 — A dedicated, disjoint code space for the persistence-and-
 * serving constitution of Layer 8. These codes are emitted by the
 * durable-surface registry, persistence validators, evidence-storage
 * validator, read-surface validator, and downstream-consumption
 * validator.
 *
 * Disjoint from:
 *   - L8.1 constitutional violation codes
 *   - L8.3 contract violation codes
 *   - L8.4 runtime violation codes
 *   - L8.5 input violation codes
 *   - L8.6 template violation codes
 *   - L8.7 reliance violation codes
 */

export enum L8PersistenceViolationCode {
  // ── Durable surfaces + authority ───────────────────────────────────
  UNKNOWN_DURABLE_SURFACE = 'L8_8_UNKNOWN_DURABLE_SURFACE',
  DURABLE_SURFACE_NOT_REGISTERED = 'L8_8_DURABLE_SURFACE_NOT_REGISTERED',
  AUTHORITY_STORE_MISMATCH = 'L8_8_AUTHORITY_STORE_MISMATCH',
  AUTHORITY_STORE_INVALID_FOR_SURFACE =
    'L8_8_AUTHORITY_STORE_INVALID_FOR_SURFACE',
  MUTATION_DISCIPLINE_VIOLATED = 'L8_8_MUTATION_DISCIPLINE_VIOLATED',
  SHADOW_AUTHORITY_DETECTED = 'L8_8_SHADOW_AUTHORITY_DETECTED',
  REDIS_AS_AUTHORITY_ATTEMPT = 'L8_8_REDIS_AS_AUTHORITY_ATTEMPT',
  OBJECT_STORE_AS_CURRENT_AUTHORITY =
    'L8_8_OBJECT_STORE_AS_CURRENT_AUTHORITY',
  CLICKHOUSE_AS_CURRENT_AUTHORITY =
    'L8_8_CLICKHOUSE_AS_CURRENT_AUTHORITY',
  DIRECT_STORE_BYPASS = 'L8_8_DIRECT_STORE_BYPASS',
  L5_BYPASS_ATTEMPT = 'L8_8_L5_BYPASS_ATTEMPT',

  // ── Current-state materialization ──────────────────────────────────
  CURRENT_STATE_OVERWRITE_WITHOUT_SUPERSESSION =
    'L8_8_CURRENT_STATE_OVERWRITE_WITHOUT_SUPERSESSION',
  SUPERSEDED_PRIOR_REF_MISSING = 'L8_8_SUPERSEDED_PRIOR_REF_MISSING',
  CURRENT_MATERIALIZATION_NOT_READY =
    'L8_8_CURRENT_MATERIALIZATION_NOT_READY',
  CURRENT_MATERIALIZATION_MODE_INVALID =
    'L8_8_CURRENT_MATERIALIZATION_MODE_INVALID',
  REPLAY_WRITTEN_AS_LIVE = 'L8_8_REPLAY_WRITTEN_AS_LIVE',
  REPAIR_WRITTEN_AS_LIVE = 'L8_8_REPAIR_WRITTEN_AS_LIVE',
  LIVE_WRITTEN_AS_HISTORICAL = 'L8_8_LIVE_WRITTEN_AS_HISTORICAL',
  LATE_DATA_WRITTEN_AS_LIVE = 'L8_8_LATE_DATA_WRITTEN_AS_LIVE',
  AUTHORITY_CLASS_SURFACE_MISMATCH =
    'L8_8_AUTHORITY_CLASS_SURFACE_MISMATCH',

  // ── Historical surfaces ────────────────────────────────────────────
  HISTORICAL_ROW_MISSING_REPLAY_IDENTITY =
    'L8_8_HISTORICAL_ROW_MISSING_REPLAY_IDENTITY',
  HISTORICAL_ROW_MISSING_LINEAGE = 'L8_8_HISTORICAL_ROW_MISSING_LINEAGE',
  HISTORICAL_ROW_DESTRUCTIVE_OVERWRITE =
    'L8_8_HISTORICAL_ROW_DESTRUCTIVE_OVERWRITE',
  HISTORICAL_ROW_MODE_MISSING = 'L8_8_HISTORICAL_ROW_MODE_MISSING',
  HISTORICAL_ROW_EVIDENCE_REF_MISSING =
    'L8_8_HISTORICAL_ROW_EVIDENCE_REF_MISSING',
  HISTORICAL_ROW_POLICY_VERSION_MISSING =
    'L8_8_HISTORICAL_ROW_POLICY_VERSION_MISSING',
  CORRECTION_ROW_MISSING_PARENT = 'L8_8_CORRECTION_ROW_MISSING_PARENT',
  CORRECTION_ROW_MISSING_REASON = 'L8_8_CORRECTION_ROW_MISSING_REASON',
  CORRECTION_ROW_NOT_APPENDED = 'L8_8_CORRECTION_ROW_NOT_APPENDED',
  HISTORICAL_MUTATES_CURRENT_SILENTLY =
    'L8_8_HISTORICAL_MUTATES_CURRENT_SILENTLY',

  // ── Evidence storage ───────────────────────────────────────────────
  EVIDENCE_CLASS_UNKNOWN = 'L8_8_EVIDENCE_CLASS_UNKNOWN',
  EVIDENCE_ARCHIVE_URI_MISSING = 'L8_8_EVIDENCE_ARCHIVE_URI_MISSING',
  EVIDENCE_CHECKSUM_MISSING = 'L8_8_EVIDENCE_CHECKSUM_MISSING',
  EVIDENCE_MANIFEST_LINKAGE_MISSING =
    'L8_8_EVIDENCE_MANIFEST_LINKAGE_MISSING',
  EVIDENCE_SUBJECT_LINK_MISSING = 'L8_8_EVIDENCE_SUBJECT_LINK_MISSING',
  EVIDENCE_REPLAY_REF_MISSING = 'L8_8_EVIDENCE_REPLAY_REF_MISSING',
  EVIDENCE_CLASS_PAYLOAD_MISMATCH =
    'L8_8_EVIDENCE_CLASS_PAYLOAD_MISMATCH',
  EVIDENCE_SUBJECT_KIND_MISMATCH =
    'L8_8_EVIDENCE_SUBJECT_KIND_MISMATCH',
  ORPHAN_EVIDENCE = 'L8_8_ORPHAN_EVIDENCE',
  EVIDENCE_REQUIRED_BUT_ABSENT = 'L8_8_EVIDENCE_REQUIRED_BUT_ABSENT',
  EVIDENCE_PATH_NON_DETERMINISTIC =
    'L8_8_EVIDENCE_PATH_NON_DETERMINISTIC',

  // ── Read surfaces ──────────────────────────────────────────────────
  UNKNOWN_READ_SURFACE = 'L8_8_UNKNOWN_READ_SURFACE',
  READ_SURFACE_NOT_REGISTERED = 'L8_8_READ_SURFACE_NOT_REGISTERED',
  READ_MODE_INVALID_FOR_SURFACE = 'L8_8_READ_MODE_INVALID_FOR_SURFACE',
  CONSUMER_CLASS_NOT_ALLOWED = 'L8_8_CONSUMER_CLASS_NOT_ALLOWED',
  RAW_STORAGE_READ_ATTEMPT = 'L8_8_RAW_STORAGE_READ_ATTEMPT',
  REDIS_READ_AS_AUTHORITATIVE = 'L8_8_REDIS_READ_AS_AUTHORITATIVE',
  CURRENT_FROM_HISTORICAL_GUESS = 'L8_8_CURRENT_FROM_HISTORICAL_GUESS',
  HISTORICAL_FROM_CURRENT_GUESS = 'L8_8_HISTORICAL_FROM_CURRENT_GUESS',
  READ_SCOPE_REQUIRED_BUT_MISSING =
    'L8_8_READ_SCOPE_REQUIRED_BUT_MISSING',
  READ_SUBJECT_REQUIRED_BUT_MISSING =
    'L8_8_READ_SUBJECT_REQUIRED_BUT_MISSING',
  EVIDENCE_READ_WITHOUT_POINTER = 'L8_8_EVIDENCE_READ_WITHOUT_POINTER',

  // ── Downstream consumption (no-rebuild law) ────────────────────────
  DOWNSTREAM_BYPASSES_READ_SURFACE =
    'L8_8_DOWNSTREAM_BYPASSES_READ_SURFACE',
  DOWNSTREAM_REBUILDS_REGIME_LIVE =
    'L8_8_DOWNSTREAM_REBUILDS_REGIME_LIVE',
  DOWNSTREAM_REBUILDS_TRANSITION_LIVE =
    'L8_8_DOWNSTREAM_REBUILDS_TRANSITION_LIVE',
  DOWNSTREAM_REBUILDS_MULTIPLIER_LIVE =
    'L8_8_DOWNSTREAM_REBUILDS_MULTIPLIER_LIVE',
  DOWNSTREAM_RAW_ARCHIVE_ACCESS = 'L8_8_DOWNSTREAM_RAW_ARCHIVE_ACCESS',
  DOWNSTREAM_IGNORES_RELIANCE_POSTURE =
    'L8_8_DOWNSTREAM_IGNORES_RELIANCE_POSTURE',
  DOWNSTREAM_IGNORES_CAP_CHAIN = 'L8_8_DOWNSTREAM_IGNORES_CAP_CHAIN',
  DOWNSTREAM_READ_MODE_SPOOFED = 'L8_8_DOWNSTREAM_READ_MODE_SPOOFED',

  // ── Lineage + replay/repair ────────────────────────────────────────
  LINEAGE_LINK_BROKEN = 'L8_8_LINEAGE_LINK_BROKEN',
  REPLAY_GENERATION_REF_MISSING = 'L8_8_REPLAY_GENERATION_REF_MISSING',
  CURRENT_HISTORICAL_INCONSISTENCY =
    'L8_8_CURRENT_HISTORICAL_INCONSISTENCY',
  REPLAY_REPAIR_SEMANTIC_DRIFT = 'L8_8_REPLAY_REPAIR_SEMANTIC_DRIFT',
  REPAIR_REUSES_LIVE_RUN_ID = 'L8_8_REPAIR_REUSES_LIVE_RUN_ID',
  REPAIR_MISSING_PARENT_RUN = 'L8_8_REPAIR_MISSING_PARENT_RUN',
  REPAIR_MISSING_REASON = 'L8_8_REPAIR_MISSING_REASON',
}

export const ALL_L8_PERSISTENCE_VIOLATION_CODES:
  readonly L8PersistenceViolationCode[] =
    Object.values(L8PersistenceViolationCode);

export interface L8PersistenceViolation {
  readonly code: L8PersistenceViolationCode;
  readonly regime_subject_id: string | null;
  readonly surface: string | null;
  readonly detail: string;
  readonly context?: Readonly<Record<string, unknown>>;
}

export function buildL8PersistenceViolation(
  code: L8PersistenceViolationCode, detail: string,
  opts: {
    readonly regime_subject_id?: string | null;
    readonly surface?: string | null;
    readonly context?: Record<string, unknown>;
  } = {},
): L8PersistenceViolation {
  return {
    code,
    regime_subject_id: opts.regime_subject_id ?? null,
    surface: opts.surface ?? null,
    detail,
    context: opts.context,
  };
}
