/**
 * L14.6 — Calibration Findings, Observed Metrics, Severity
 *
 * §14.6.18–§14.6.22
 */

export enum L14CalibrationFindingClass {
  ALIGNMENT_RATE = 'ALIGNMENT_RATE',
  MISALIGNMENT_RATE = 'MISALIGNMENT_RATE',
  PARTIAL_ALIGNMENT_RATE = 'PARTIAL_ALIGNMENT_RATE',
  FALSE_POSITIVE_RATE = 'FALSE_POSITIVE_RATE',
  FALSE_NEGATIVE_RATE = 'FALSE_NEGATIVE_RATE',
  OVERCONFIDENCE_RATE = 'OVERCONFIDENCE_RATE',
  UNDERCONFIDENCE_RATE = 'UNDERCONFIDENCE_RATE',
  HYPOTHESIS_FAILURE_RATE = 'HYPOTHESIS_FAILURE_RATE',
  SCENARIO_PATH_FAILURE_RATE = 'SCENARIO_PATH_FAILURE_RATE',
  TRIGGER_SIGNIFICANCE_RATE = 'TRIGGER_SIGNIFICANCE_RATE',
  INVALIDATION_EFFECTIVENESS_RATE = 'INVALIDATION_EFFECTIVENESS_RATE',
  ALERT_IGNORE_RATE = 'ALERT_IGNORE_RATE',
  ALERT_DEEPER_INVESTIGATION_RATE = 'ALERT_DEEPER_INVESTIGATION_RATE',
  POSITIVE_FEEDBACK_RATE = 'POSITIVE_FEEDBACK_RATE',
  NEGATIVE_FEEDBACK_RATE = 'NEGATIVE_FEEDBACK_RATE',
  THRESHOLD_EVENT_FREQUENCY = 'THRESHOLD_EVENT_FREQUENCY',
  THRESHOLD_NOISE_RATIO = 'THRESHOLD_NOISE_RATIO',
  FEATURE_ASSOCIATION_STRENGTH = 'FEATURE_ASSOCIATION_STRENGTH',
}

export enum L14CalibrationObservedMetric {
  OUTCOME_ALIGNMENT_RATE = 'OUTCOME_ALIGNMENT_RATE',
  OUTCOME_MISALIGNMENT_RATE = 'OUTCOME_MISALIGNMENT_RATE',
  FALSE_POSITIVE_FREQUENCY = 'FALSE_POSITIVE_FREQUENCY',
  FALSE_NEGATIVE_FREQUENCY = 'FALSE_NEGATIVE_FREQUENCY',
  CONFIDENCE_OVERSTATEMENT_FREQUENCY = 'CONFIDENCE_OVERSTATEMENT_FREQUENCY',
  CONFIDENCE_UNDERSTATEMENT_FREQUENCY = 'CONFIDENCE_UNDERSTATEMENT_FREQUENCY',
  ALERT_DELIVERY_COUNT = 'ALERT_DELIVERY_COUNT',
  ALERT_IGNORE_RATE = 'ALERT_IGNORE_RATE',
  ALERT_OPEN_RATE = 'ALERT_OPEN_RATE',
  ALERT_DEEPER_INVESTIGATION_RATE = 'ALERT_DEEPER_INVESTIGATION_RATE',
  FEEDBACK_POSITIVE_RATE = 'FEEDBACK_POSITIVE_RATE',
  FEEDBACK_NEGATIVE_RATE = 'FEEDBACK_NEGATIVE_RATE',
  HYPOTHESIS_INVALIDATION_RATE = 'HYPOTHESIS_INVALIDATION_RATE',
  SCENARIO_FAILURE_CONDITION_RATE = 'SCENARIO_FAILURE_CONDITION_RATE',
  TRIGGER_DOWNSTREAM_EFFECT_RATE = 'TRIGGER_DOWNSTREAM_EFFECT_RATE',
  INVALIDATION_DOWNSTREAM_EFFECT_RATE = 'INVALIDATION_DOWNSTREAM_EFFECT_RATE',
  THRESHOLD_FIRING_RATE = 'THRESHOLD_FIRING_RATE',
  THRESHOLD_NOISE_RATE = 'THRESHOLD_NOISE_RATE',
  FEATURE_CONTRIBUTION_ASSOCIATION = 'FEATURE_CONTRIBUTION_ASSOCIATION',
}

export enum L14CalibrationFindingDirection {
  STRONGER_THAN_BASELINE = 'STRONGER_THAN_BASELINE',
  WEAKER_THAN_BASELINE = 'WEAKER_THAN_BASELINE',
  ABOVE_ALLOWED_RANGE = 'ABOVE_ALLOWED_RANGE',
  BELOW_ALLOWED_RANGE = 'BELOW_ALLOWED_RANGE',
  MIXED_OR_INCONCLUSIVE = 'MIXED_OR_INCONCLUSIVE',
}

export enum L14CalibrationFindingSeverity {
  TRACE = 'TRACE',
  MINOR = 'MINOR',
  MATERIAL = 'MATERIAL',
  MAJOR = 'MAJOR',
  CRITICAL = 'CRITICAL',
}

export interface L14CalibrationFinding {
  readonly finding_id: string;
  readonly finding_class: L14CalibrationFindingClass;
  readonly observed_metric: L14CalibrationObservedMetric;
  readonly observed_value: number | string;
  readonly comparison_baseline?: number | string;
  readonly direction_of_concern?: L14CalibrationFindingDirection;
  readonly severity_class: L14CalibrationFindingSeverity;
  readonly interpretation: string;
  readonly supporting_refs: readonly string[];
  readonly counterevidence_refs: readonly string[];
  readonly policy_version: string;
}
