/**
 * L14.1 — Constitutional Violation Codes
 *
 * §14.1.18 — Disjoint `L14C_` namespace (C = Constitution).
 */

export enum L14ConstitutionalViolationCode {
  L14C_MISSION_MISSING = 'L14C_MISSION_MISSING',
  L14C_MISSION_MUTATED = 'L14C_MISSION_MUTATED',
  L14C_FIRST_PRINCIPLE_MISSING = 'L14C_FIRST_PRINCIPLE_MISSING',
  L14C_UNREGISTERED_DEPENDENCY_SURFACE = 'L14C_UNREGISTERED_DEPENDENCY_SURFACE',
  L14C_RAW_LOWER_LAYER_REBUILD_ATTEMPT = 'L14C_RAW_LOWER_LAYER_REBUILD_ATTEMPT',
  L14C_L10_HYPOTHESIS_REBUILD_ATTEMPT = 'L14C_L10_HYPOTHESIS_REBUILD_ATTEMPT',
  L14C_L11_SCORE_REBUILD_ATTEMPT = 'L14C_L11_SCORE_REBUILD_ATTEMPT',
  L14C_L12_SCENARIO_REBUILD_ATTEMPT = 'L14C_L12_SCENARIO_REBUILD_ATTEMPT',
  L14C_L13_EXPLANATION_REBUILD_ATTEMPT = 'L14C_L13_EXPLANATION_REBUILD_ATTEMPT',
  L14C_ENGAGEMENT_AS_TRUTH = 'L14C_ENGAGEMENT_AS_TRUTH',
  L14C_FEEDBACK_AS_AUTOMATIC_TRUTH = 'L14C_FEEDBACK_AS_AUTOMATIC_TRUTH',
  L14C_OPEN_RATE_AS_CORRECTNESS = 'L14C_OPEN_RATE_AS_CORRECTNESS',
  L14C_CLICK_RATE_AS_CORRECTNESS = 'L14C_CLICK_RATE_AS_CORRECTNESS',
  L14C_SILENT_LOWER_LAYER_MUTATION = 'L14C_SILENT_LOWER_LAYER_MUTATION',
  L14C_AUTO_THRESHOLD_MUTATION = 'L14C_AUTO_THRESHOLD_MUTATION',
  L14C_AUTO_SCENARIO_TEMPLATE_MUTATION = 'L14C_AUTO_SCENARIO_TEMPLATE_MUTATION',
  L14C_AUTO_L13_POLICY_MUTATION = 'L14C_AUTO_L13_POLICY_MUTATION',
  L14C_OUTCOME_MISALIGNMENT_HIDDEN = 'L14C_OUTCOME_MISALIGNMENT_HIDDEN',
  L14C_FALSE_POSITIVE_HIDDEN = 'L14C_FALSE_POSITIVE_HIDDEN',
  L14C_CONFIDENCE_OVERSTATEMENT_HIDDEN = 'L14C_CONFIDENCE_OVERSTATEMENT_HIDDEN',
  L14C_DELIVERY_SOURCE_UNGOVERNED = 'L14C_DELIVERY_SOURCE_UNGOVERNED',
  L14C_DELIVERY_REWRITES_SOURCE_MEANING = 'L14C_DELIVERY_REWRITES_SOURCE_MEANING',
  L14C_DELIVERY_BYPASSES_RESTRICTION = 'L14C_DELIVERY_BYPASSES_RESTRICTION',
  L14C_CALIBRATION_EVIDENCE_WITHOUT_LINEAGE = 'L14C_CALIBRATION_EVIDENCE_WITHOUT_LINEAGE',
  L14C_CALIBRATION_PROPOSAL_AUTO_APPLY = 'L14C_CALIBRATION_PROPOSAL_AUTO_APPLY',
  L14C_EVALUATION_WITHOUT_HORIZON = 'L14C_EVALUATION_WITHOUT_HORIZON',
  L14C_OUTPUT_SURFACE_UNREGISTERED = 'L14C_OUTPUT_SURFACE_UNREGISTERED',
  L14C_OUTPUT_SURFACE_L5_ROUTE_MISSING = 'L14C_OUTPUT_SURFACE_L5_ROUTE_MISSING',
  L14C_OUTPUT_SURFACE_LINEAGE_MISSING = 'L14C_OUTPUT_SURFACE_LINEAGE_MISSING',
  L14C_OUTPUT_SURFACE_REPLAY_HASH_MISSING = 'L14C_OUTPUT_SURFACE_REPLAY_HASH_MISSING',
}

export const ALL_L14_CONSTITUTIONAL_VIOLATION_CODES:
  readonly L14ConstitutionalViolationCode[] =
  Object.values(L14ConstitutionalViolationCode);
