/**
 * L14.1 — Boundary Contract
 *
 * §14.1.5 — Closed sets of allowed and forbidden semantic
 * positions used by boundary validators and audit emitters.
 */

export enum L14BoundaryAllowedSemantic {
  CONSUMES_GOVERNED_L10_L13_OUTPUTS = 'CONSUMES_GOVERNED_L10_L13_OUTPUTS',
  DELIVERS_THROUGH_PRODUCT_SURFACES = 'DELIVERS_THROUGH_PRODUCT_SURFACES',
  OBSERVES_USER_INTERACTION = 'OBSERVES_USER_INTERACTION',
  OBSERVES_OUTCOME_SIGNALS = 'OBSERVES_OUTCOME_SIGNALS',
  PRODUCES_CALIBRATION_EVIDENCE = 'PRODUCES_CALIBRATION_EVIDENCE',
  PRODUCES_CALIBRATION_PROPOSALS = 'PRODUCES_CALIBRATION_PROPOSALS',
  SURFACES_ANALYST_REVIEW = 'SURFACES_ANALYST_REVIEW',
  SURFACES_OPERATIONAL_HEALTH = 'SURFACES_OPERATIONAL_HEALTH',
  ROUTES_THROUGH_L5_PERSISTENCE = 'ROUTES_THROUGH_L5_PERSISTENCE',
  RECORDS_OUTCOME_HONESTLY = 'RECORDS_OUTCOME_HONESTLY',
}

export const ALL_L14_BOUNDARY_ALLOWED_SEMANTICS:
  readonly L14BoundaryAllowedSemantic[] =
  Object.values(L14BoundaryAllowedSemantic);

export enum L14BoundaryForbiddenSemantic {
  REBUILD_L10_HYPOTHESIS = 'REBUILD_L10_HYPOTHESIS',
  REBUILD_L11_SCORE = 'REBUILD_L11_SCORE',
  REBUILD_L12_SCENARIO = 'REBUILD_L12_SCENARIO',
  REBUILD_L13_EXPLANATION = 'REBUILD_L13_EXPLANATION',
  ENGAGEMENT_AS_CORRECTNESS = 'ENGAGEMENT_AS_CORRECTNESS',
  FEEDBACK_AS_AUTOMATIC_TRUTH = 'FEEDBACK_AS_AUTOMATIC_TRUTH',
  SILENT_LOWER_LAYER_MUTATION = 'SILENT_LOWER_LAYER_MUTATION',
  AUTO_THRESHOLD_MUTATION = 'AUTO_THRESHOLD_MUTATION',
  AUTO_SCENARIO_TEMPLATE_MUTATION = 'AUTO_SCENARIO_TEMPLATE_MUTATION',
  AUTO_L13_POLICY_MUTATION = 'AUTO_L13_POLICY_MUTATION',
  HIDE_OUTCOME_MISALIGNMENT = 'HIDE_OUTCOME_MISALIGNMENT',
  HIDE_FALSE_POSITIVE_PATTERN = 'HIDE_FALSE_POSITIVE_PATTERN',
  HIDE_CONFIDENCE_OVERSTATEMENT = 'HIDE_CONFIDENCE_OVERSTATEMENT',
  DELIVERY_REWRITES_SOURCE_MEANING = 'DELIVERY_REWRITES_SOURCE_MEANING',
  DELIVERY_BYPASSES_RESTRICTION = 'DELIVERY_BYPASSES_RESTRICTION',
  CALIBRATION_PROPOSAL_AUTO_APPLIED = 'CALIBRATION_PROPOSAL_AUTO_APPLIED',
  CALIBRATION_EVIDENCE_WITHOUT_LINEAGE = 'CALIBRATION_EVIDENCE_WITHOUT_LINEAGE',
  EVALUATION_WITHOUT_DECLARED_HORIZON = 'EVALUATION_WITHOUT_DECLARED_HORIZON',
  RAW_LOWER_LAYER_READ = 'RAW_LOWER_LAYER_READ',
  PERSISTENCE_BYPASS_L5 = 'PERSISTENCE_BYPASS_L5',
}

export const ALL_L14_BOUNDARY_FORBIDDEN_SEMANTICS:
  readonly L14BoundaryForbiddenSemantic[] =
  Object.values(L14BoundaryForbiddenSemantic);

export interface L14Boundary {
  readonly boundary_id: string;
  readonly allowed_semantics: readonly L14BoundaryAllowedSemantic[];
  readonly forbidden_semantics: readonly L14BoundaryForbiddenSemantic[];
  readonly policy_version: string;
  readonly replay_hash: string;
}
