/**
 * L14.1 — Forbidden Action Taxonomy
 *
 * §14.1.8 — Closed set of actions Layer 14 may never perform.
 */

export enum L14ForbiddenAction {
  REBUILD_L10_HYPOTHESIS = 'REBUILD_L10_HYPOTHESIS',
  REBUILD_L11_SCORE = 'REBUILD_L11_SCORE',
  REBUILD_L12_SCENARIO = 'REBUILD_L12_SCENARIO',
  REBUILD_L13_EXPLANATION = 'REBUILD_L13_EXPLANATION',
  TREAT_OPEN_RATE_AS_CORRECTNESS = 'TREAT_OPEN_RATE_AS_CORRECTNESS',
  TREAT_CLICK_RATE_AS_CORRECTNESS = 'TREAT_CLICK_RATE_AS_CORRECTNESS',
  TREAT_SAVE_RATE_AS_CORRECTNESS = 'TREAT_SAVE_RATE_AS_CORRECTNESS',
  TREAT_FEEDBACK_AS_AUTOMATIC_TRUTH = 'TREAT_FEEDBACK_AS_AUTOMATIC_TRUTH',
  SILENTLY_MUTATE_L11_FORMULA = 'SILENTLY_MUTATE_L11_FORMULA',
  SILENTLY_MUTATE_L11_THRESHOLD = 'SILENTLY_MUTATE_L11_THRESHOLD',
  SILENTLY_MUTATE_L12_SCENARIO_TEMPLATE = 'SILENTLY_MUTATE_L12_SCENARIO_TEMPLATE',
  SILENTLY_MUTATE_L13_GROUNDING_POLICY = 'SILENTLY_MUTATE_L13_GROUNDING_POLICY',
  SILENTLY_MUTATE_L13_SAFETY_POLICY = 'SILENTLY_MUTATE_L13_SAFETY_POLICY',
  HIDE_OUTCOME_MISALIGNMENT = 'HIDE_OUTCOME_MISALIGNMENT',
  HIDE_FALSE_POSITIVE_PATTERN = 'HIDE_FALSE_POSITIVE_PATTERN',
  HIDE_FALSE_NEGATIVE_PATTERN = 'HIDE_FALSE_NEGATIVE_PATTERN',
  HIDE_CONFIDENCE_OVERSTATEMENT = 'HIDE_CONFIDENCE_OVERSTATEMENT',
  DELIVER_UNGOVERNED_SOURCE_ARTIFACT = 'DELIVER_UNGOVERNED_SOURCE_ARTIFACT',
  DELIVERY_BYPASSES_RESTRICTION_PROFILE = 'DELIVERY_BYPASSES_RESTRICTION_PROFILE',
  DELIVERY_BYPASSES_CHANNEL_ENTITLEMENT = 'DELIVERY_BYPASSES_CHANNEL_ENTITLEMENT',
  DELIVERY_REWRITES_SOURCE_MEANING = 'DELIVERY_REWRITES_SOURCE_MEANING',
  CALIBRATION_PROPOSAL_AUTO_APPLIED = 'CALIBRATION_PROPOSAL_AUTO_APPLIED',
  CALIBRATION_EVIDENCE_WITHOUT_LINEAGE = 'CALIBRATION_EVIDENCE_WITHOUT_LINEAGE',
  OUTCOME_EVALUATION_WITHOUT_DECLARED_HORIZON = 'OUTCOME_EVALUATION_WITHOUT_DECLARED_HORIZON',
  DIRECT_RAW_LOWER_LAYER_READ = 'DIRECT_RAW_LOWER_LAYER_READ',
  DIRECT_PERSISTENCE_BYPASS_L5 = 'DIRECT_PERSISTENCE_BYPASS_L5',
  ENGAGEMENT_AS_TRUTH_SEMANTIC_LEAK = 'ENGAGEMENT_AS_TRUTH_SEMANTIC_LEAK',
  FEEDBACK_AS_TRUTH_SEMANTIC_LEAK = 'FEEDBACK_AS_TRUTH_SEMANTIC_LEAK',
}

export const ALL_L14_FORBIDDEN_ACTIONS:
  readonly L14ForbiddenAction[] =
  Object.values(L14ForbiddenAction);
