/**
 * L14.1 — Capability Policy Contract
 *
 * §14.1.6 / §14.1.7 — Closed sets enumerating the capabilities
 * Layer 14 may exercise and the high-level capability groups that
 * organize them.
 */

export enum L14AllowedCapability {
  CONSUME_GOVERNED_L10_OUTPUTS = 'CONSUME_GOVERNED_L10_OUTPUTS',
  CONSUME_GOVERNED_L11_OUTPUTS = 'CONSUME_GOVERNED_L11_OUTPUTS',
  CONSUME_GOVERNED_L12_OUTPUTS = 'CONSUME_GOVERNED_L12_OUTPUTS',
  CONSUME_GOVERNED_L13_OUTPUTS = 'CONSUME_GOVERNED_L13_OUTPUTS',
  DEFINE_DELIVERY_ELIGIBILITY = 'DEFINE_DELIVERY_ELIGIBILITY',
  ROUTE_DELIVERY_CHANNELS = 'ROUTE_DELIVERY_CHANNELS',
  ASSEMBLE_CHANNEL_PAYLOADS = 'ASSEMBLE_CHANNEL_PAYLOADS',
  SUPPRESS_DUPLICATE_OR_RESTRICTED_DELIVERY = 'SUPPRESS_DUPLICATE_OR_RESTRICTED_DELIVERY',
  RECORD_USER_INTERACTION_SIGNALS = 'RECORD_USER_INTERACTION_SIGNALS',
  RECORD_DELIVERY_EVENTS = 'RECORD_DELIVERY_EVENTS',
  RECORD_FEEDBACK_SIGNALS = 'RECORD_FEEDBACK_SIGNALS',
  EVALUATE_OUTCOME_ALIGNMENT = 'EVALUATE_OUTCOME_ALIGNMENT',
  EVALUATE_ALERT_EFFECTIVENESS = 'EVALUATE_ALERT_EFFECTIVENESS',
  EVALUATE_SCORE_CALIBRATION_OUTCOMES = 'EVALUATE_SCORE_CALIBRATION_OUTCOMES',
  EVALUATE_HYPOTHESIS_SUCCESS_RATE = 'EVALUATE_HYPOTHESIS_SUCCESS_RATE',
  EVALUATE_SCENARIO_ALIGNMENT = 'EVALUATE_SCENARIO_ALIGNMENT',
  PRODUCE_CALIBRATION_EVIDENCE = 'PRODUCE_CALIBRATION_EVIDENCE',
  PRODUCE_CALIBRATION_REVIEW_PROPOSALS = 'PRODUCE_CALIBRATION_REVIEW_PROPOSALS',
  SURFACE_ANALYST_REVIEW_PAYLOADS = 'SURFACE_ANALYST_REVIEW_PAYLOADS',
  SURFACE_OPERATIONAL_HEALTH_METRICS = 'SURFACE_OPERATIONAL_HEALTH_METRICS',
}

export const ALL_L14_ALLOWED_CAPABILITIES:
  readonly L14AllowedCapability[] =
  Object.values(L14AllowedCapability);

export enum L14CapabilityGroup {
  LOWER_LAYER_CONSUMPTION = 'LOWER_LAYER_CONSUMPTION',
  DELIVERY_CONTROL = 'DELIVERY_CONTROL',
  INTERACTION_OBSERVATION = 'INTERACTION_OBSERVATION',
  OUTCOME_EVALUATION = 'OUTCOME_EVALUATION',
  CALIBRATION_EVIDENCE = 'CALIBRATION_EVIDENCE',
  ANALYST_AND_OPERATIONS = 'ANALYST_AND_OPERATIONS',
}

export const ALL_L14_CAPABILITY_GROUPS:
  readonly L14CapabilityGroup[] =
  Object.values(L14CapabilityGroup);

export const L14_CAPABILITY_GROUP_OF:
  Readonly<Record<L14AllowedCapability, L14CapabilityGroup>> = {
  [L14AllowedCapability.CONSUME_GOVERNED_L10_OUTPUTS]: L14CapabilityGroup.LOWER_LAYER_CONSUMPTION,
  [L14AllowedCapability.CONSUME_GOVERNED_L11_OUTPUTS]: L14CapabilityGroup.LOWER_LAYER_CONSUMPTION,
  [L14AllowedCapability.CONSUME_GOVERNED_L12_OUTPUTS]: L14CapabilityGroup.LOWER_LAYER_CONSUMPTION,
  [L14AllowedCapability.CONSUME_GOVERNED_L13_OUTPUTS]: L14CapabilityGroup.LOWER_LAYER_CONSUMPTION,
  [L14AllowedCapability.DEFINE_DELIVERY_ELIGIBILITY]: L14CapabilityGroup.DELIVERY_CONTROL,
  [L14AllowedCapability.ROUTE_DELIVERY_CHANNELS]: L14CapabilityGroup.DELIVERY_CONTROL,
  [L14AllowedCapability.ASSEMBLE_CHANNEL_PAYLOADS]: L14CapabilityGroup.DELIVERY_CONTROL,
  [L14AllowedCapability.SUPPRESS_DUPLICATE_OR_RESTRICTED_DELIVERY]: L14CapabilityGroup.DELIVERY_CONTROL,
  [L14AllowedCapability.RECORD_USER_INTERACTION_SIGNALS]: L14CapabilityGroup.INTERACTION_OBSERVATION,
  [L14AllowedCapability.RECORD_DELIVERY_EVENTS]: L14CapabilityGroup.INTERACTION_OBSERVATION,
  [L14AllowedCapability.RECORD_FEEDBACK_SIGNALS]: L14CapabilityGroup.INTERACTION_OBSERVATION,
  [L14AllowedCapability.EVALUATE_OUTCOME_ALIGNMENT]: L14CapabilityGroup.OUTCOME_EVALUATION,
  [L14AllowedCapability.EVALUATE_ALERT_EFFECTIVENESS]: L14CapabilityGroup.OUTCOME_EVALUATION,
  [L14AllowedCapability.EVALUATE_SCORE_CALIBRATION_OUTCOMES]: L14CapabilityGroup.OUTCOME_EVALUATION,
  [L14AllowedCapability.EVALUATE_HYPOTHESIS_SUCCESS_RATE]: L14CapabilityGroup.OUTCOME_EVALUATION,
  [L14AllowedCapability.EVALUATE_SCENARIO_ALIGNMENT]: L14CapabilityGroup.OUTCOME_EVALUATION,
  [L14AllowedCapability.PRODUCE_CALIBRATION_EVIDENCE]: L14CapabilityGroup.CALIBRATION_EVIDENCE,
  [L14AllowedCapability.PRODUCE_CALIBRATION_REVIEW_PROPOSALS]: L14CapabilityGroup.CALIBRATION_EVIDENCE,
  [L14AllowedCapability.SURFACE_ANALYST_REVIEW_PAYLOADS]: L14CapabilityGroup.ANALYST_AND_OPERATIONS,
  [L14AllowedCapability.SURFACE_OPERATIONAL_HEALTH_METRICS]: L14CapabilityGroup.ANALYST_AND_OPERATIONS,
};
