/**
 * L13.1 — Dependency Surface Contract
 *
 * §13.1.3 / §13.1.7 — Hard constitutional dependency law for the
 * AI Judgment & Explanation Layer. Every registered dependency
 * surface declares its source layer (L3–L12), surface class, and the
 * disclosure / posture-awareness it requires.
 *
 * Layer 13 may consume only registered governed handoff surfaces
 * from L3–L12. L14+ consumption is forbidden. Raw lower-layer rebuild
 * surfaces are forbidden. L11 score requires the full
 * attribution / missing-data / drift / restriction context bundle.
 * L12 scenario requires triggers / invalidations / path confidence /
 * restrictions context.
 */

import {
  L13AllowedCapability,
  L13DependencyLayer,
  L13DependencySurfaceClass,
} from './l13-constitutional-types';

export interface L13DependencySurfaceDescriptor {
  readonly surfaceId: string;
  readonly sourceLayer: L13DependencyLayer;
  readonly surfaceClass: L13DependencySurfaceClass;

  readonly stableHandoffRequired: boolean;

  readonly evidenceRequired: boolean;
  readonly lineageRequired: boolean;
  readonly restrictionRequired: boolean;
  readonly confidenceRequired: boolean;

  readonly contradictionAware: boolean;
  readonly regimeAware: boolean;
  readonly sequenceAware: boolean;
  readonly hypothesisAware: boolean;
  readonly scoreContextAware: boolean;
  readonly scenarioAware: boolean;

  /** §13.1.3 — Raw rebuild is always forbidden for L13 surfaces. */
  readonly rawRebuildProhibited: true;

  /** §13.1.7 / §13.1.9 — Capabilities allowed to use this surface. */
  readonly allowedL13Uses: readonly L13AllowedCapability[];

  readonly required: boolean;
  readonly policyVersion: string;
  readonly description: string;
}

const POLICY_V = 'l13.constitution.v1';

const EXPLAIN_AND_REPORT: readonly L13AllowedCapability[] = [
  L13AllowedCapability.EXPLAIN_ENGINE_STATE,
  L13AllowedCapability.SUMMARIZE_MARKET_STATE,
  L13AllowedCapability.ANSWER_USER_QUESTION,
  L13AllowedCapability.WRITE_STRUCTURED_REPORT,
];

const FULL_EXPLANATION_USES: readonly L13AllowedCapability[] = [
  ...EXPLAIN_AND_REPORT,
  L13AllowedCapability.WRITE_ALERT_TEXT,
  L13AllowedCapability.COMPARE_ASSETS,
  L13AllowedCapability.COMPARE_THESES,
  L13AllowedCapability.DISCLOSE_CONTRADICTION,
  L13AllowedCapability.DISCLOSE_UNCERTAINTY,
  L13AllowedCapability.CITE_EVIDENCE_REFS,
  L13AllowedCapability.RESPECT_RESTRICTIONS,
];

/**
 * §13.1.7 — Registry of every governed dependency surface that L13
 * may consume. Each L3–L12 layer is represented by its frozen
 * handoff classes. Order is L3 → L12 to mirror the substrate.
 */
export const L13_DEPENDENCY_SURFACES:
  readonly L13DependencySurfaceDescriptor[] = [
  // ── L3 — identity ──
  {
    surfaceId: 'l3:canonical_entity_summary',
    sourceLayer: L13DependencyLayer.L3_IDENTITY,
    surfaceClass: L13DependencySurfaceClass.CANONICAL_ENTITY_SUMMARY,
    stableHandoffRequired: true,
    evidenceRequired: false,
    lineageRequired: true,
    restrictionRequired: false,
    confidenceRequired: false,
    contradictionAware: false,
    regimeAware: false,
    sequenceAware: false,
    hypothesisAware: false,
    scoreContextAware: false,
    scenarioAware: false,
    rawRebuildProhibited: true,
    allowedL13Uses: FULL_EXPLANATION_USES,
    required: true,
    policyVersion: POLICY_V,
    description: 'L3 canonical entity summary — used to name the asset; L13 must not reconcile identity locally',
  },
  {
    surfaceId: 'l3:scope_law',
    sourceLayer: L13DependencyLayer.L3_IDENTITY,
    surfaceClass: L13DependencySurfaceClass.SCOPE_LAW,
    stableHandoffRequired: true,
    evidenceRequired: false,
    lineageRequired: true,
    restrictionRequired: false,
    confidenceRequired: false,
    contradictionAware: false,
    regimeAware: false,
    sequenceAware: false,
    hypothesisAware: false,
    scoreContextAware: false,
    scenarioAware: false,
    rawRebuildProhibited: true,
    allowedL13Uses: EXPLAIN_AND_REPORT,
    required: true,
    policyVersion: POLICY_V,
    description: 'L3 scope law — used to declare scope; never overridden in L13',
  },

  // ── L4 — graph context ──
  {
    surfaceId: 'l4:graph_context',
    sourceLayer: L13DependencyLayer.L4_GRAPH,
    surfaceClass: L13DependencySurfaceClass.GRAPH_CONTEXT,
    stableHandoffRequired: true,
    evidenceRequired: true,
    lineageRequired: true,
    restrictionRequired: false,
    confidenceRequired: false,
    contradictionAware: false,
    regimeAware: false,
    sequenceAware: false,
    hypothesisAware: false,
    scoreContextAware: false,
    scenarioAware: false,
    rawRebuildProhibited: true,
    allowedL13Uses: FULL_EXPLANATION_USES,
    required: false,
    policyVersion: POLICY_V,
    description: 'L4 graph context — ecosystem/sector/propagation; only mentionable when L4 evidence supports it',
  },

  // ── L5 — storage / read services ──
  {
    surfaceId: 'l5:storage_read_service',
    sourceLayer: L13DependencyLayer.L5_STORAGE,
    surfaceClass: L13DependencySurfaceClass.STORAGE_READ_SERVICE,
    stableHandoffRequired: true,
    evidenceRequired: false,
    lineageRequired: true,
    restrictionRequired: false,
    confidenceRequired: false,
    contradictionAware: false,
    regimeAware: false,
    sequenceAware: false,
    hypothesisAware: false,
    scoreContextAware: false,
    scenarioAware: false,
    rawRebuildProhibited: true,
    allowedL13Uses: FULL_EXPLANATION_USES,
    required: true,
    policyVersion: POLICY_V,
    description: 'L5 governed storage read service — direct writes prohibited',
  },
  {
    surfaceId: 'l5:evidence_read_service',
    sourceLayer: L13DependencyLayer.L5_STORAGE,
    surfaceClass: L13DependencySurfaceClass.EVIDENCE_READ_SERVICE,
    stableHandoffRequired: true,
    evidenceRequired: true,
    lineageRequired: true,
    restrictionRequired: false,
    confidenceRequired: false,
    contradictionAware: false,
    regimeAware: false,
    sequenceAware: false,
    hypothesisAware: false,
    scoreContextAware: false,
    scenarioAware: false,
    rawRebuildProhibited: true,
    allowedL13Uses: FULL_EXPLANATION_USES,
    required: true,
    policyVersion: POLICY_V,
    description: 'L5 evidence read service — only governed retrieval',
  },
  {
    surfaceId: 'l5:lineage_read_service',
    sourceLayer: L13DependencyLayer.L5_STORAGE,
    surfaceClass: L13DependencySurfaceClass.LINEAGE_READ_SERVICE,
    stableHandoffRequired: true,
    evidenceRequired: false,
    lineageRequired: true,
    restrictionRequired: false,
    confidenceRequired: false,
    contradictionAware: false,
    regimeAware: false,
    sequenceAware: false,
    hypothesisAware: false,
    scoreContextAware: false,
    scenarioAware: false,
    rawRebuildProhibited: true,
    allowedL13Uses: FULL_EXPLANATION_USES,
    required: true,
    policyVersion: POLICY_V,
    description: 'L5 lineage read service — preserves replay identity',
  },

  // ── L6 — feature/event evidence (governed only) ──
  {
    surfaceId: 'l6:feature_evidence_ref',
    sourceLayer: L13DependencyLayer.L6_FEATURE_EVENT,
    surfaceClass: L13DependencySurfaceClass.FEATURE_EVIDENCE_REF_SURFACE,
    stableHandoffRequired: true,
    evidenceRequired: true,
    lineageRequired: true,
    restrictionRequired: false,
    confidenceRequired: false,
    contradictionAware: false,
    regimeAware: false,
    sequenceAware: false,
    hypothesisAware: false,
    scoreContextAware: false,
    scenarioAware: false,
    rawRebuildProhibited: true,
    allowedL13Uses: EXPLAIN_AND_REPORT,
    required: false,
    policyVersion: POLICY_V,
    description: 'L6 feature evidence ref — mentionable only via governed L7/L11/L12 evidence packs',
  },
  {
    surfaceId: 'l6:event_evidence_ref',
    sourceLayer: L13DependencyLayer.L6_FEATURE_EVENT,
    surfaceClass: L13DependencySurfaceClass.EVENT_EVIDENCE_REF_SURFACE,
    stableHandoffRequired: true,
    evidenceRequired: true,
    lineageRequired: true,
    restrictionRequired: false,
    confidenceRequired: false,
    contradictionAware: false,
    regimeAware: false,
    sequenceAware: false,
    hypothesisAware: false,
    scoreContextAware: false,
    scenarioAware: false,
    rawRebuildProhibited: true,
    allowedL13Uses: EXPLAIN_AND_REPORT,
    required: false,
    policyVersion: POLICY_V,
    description: 'L6 event evidence ref — mentionable only via governed evidence packs',
  },

  // ── L7 — validation / contradiction / restriction ──
  {
    surfaceId: 'l7:validation_assessment',
    sourceLayer: L13DependencyLayer.L7_VALIDATION,
    surfaceClass: L13DependencySurfaceClass.VALIDATION_ASSESSMENT,
    stableHandoffRequired: true,
    evidenceRequired: true,
    lineageRequired: true,
    restrictionRequired: true,
    confidenceRequired: true,
    contradictionAware: true,
    regimeAware: false,
    sequenceAware: false,
    hypothesisAware: false,
    scoreContextAware: false,
    scenarioAware: false,
    rawRebuildProhibited: true,
    allowedL13Uses: FULL_EXPLANATION_USES,
    required: true,
    policyVersion: POLICY_V,
    description: 'L7 validation assessment — disclose validation posture without overriding it',
  },
  {
    surfaceId: 'l7:contradiction_bundle',
    sourceLayer: L13DependencyLayer.L7_VALIDATION,
    surfaceClass: L13DependencySurfaceClass.CONTRADICTION_BUNDLE,
    stableHandoffRequired: true,
    evidenceRequired: true,
    lineageRequired: true,
    restrictionRequired: true,
    confidenceRequired: false,
    contradictionAware: true,
    regimeAware: false,
    sequenceAware: false,
    hypothesisAware: false,
    scoreContextAware: false,
    scenarioAware: false,
    rawRebuildProhibited: true,
    allowedL13Uses: [
      ...FULL_EXPLANATION_USES,
      L13AllowedCapability.REFUSE_UNSUPPORTED_CONCLUSION,
    ],
    required: true,
    policyVersion: POLICY_V,
    description: 'L7 contradiction bundle — must be disclosed when present',
  },
  {
    surfaceId: 'l7:validation_restriction_profile',
    sourceLayer: L13DependencyLayer.L7_VALIDATION,
    surfaceClass:
      L13DependencySurfaceClass.VALIDATION_RESTRICTION_PROFILE,
    stableHandoffRequired: true,
    evidenceRequired: false,
    lineageRequired: true,
    restrictionRequired: true,
    confidenceRequired: false,
    contradictionAware: true,
    regimeAware: false,
    sequenceAware: false,
    hypothesisAware: false,
    scoreContextAware: false,
    scenarioAware: false,
    rawRebuildProhibited: true,
    allowedL13Uses: FULL_EXPLANATION_USES,
    required: true,
    policyVersion: POLICY_V,
    description: 'L7 validation restriction profile — must be honoured by every L13 explanation',
  },

  // ── L8 — regime ──
  {
    surfaceId: 'l8:regime_state',
    sourceLayer: L13DependencyLayer.L8_REGIME,
    surfaceClass: L13DependencySurfaceClass.REGIME_STATE,
    stableHandoffRequired: true,
    evidenceRequired: true,
    lineageRequired: true,
    restrictionRequired: false,
    confidenceRequired: true,
    contradictionAware: false,
    regimeAware: true,
    sequenceAware: false,
    hypothesisAware: false,
    scoreContextAware: false,
    scenarioAware: false,
    rawRebuildProhibited: true,
    allowedL13Uses: [
      ...FULL_EXPLANATION_USES,
      L13AllowedCapability.EXPLAIN_REGIME,
    ],
    required: true,
    policyVersion: POLICY_V,
    description: 'L8 regime state — explainable, not classifiable in L13',
  },
  {
    surfaceId: 'l8:regime_confidence',
    sourceLayer: L13DependencyLayer.L8_REGIME,
    surfaceClass: L13DependencySurfaceClass.REGIME_CONFIDENCE,
    stableHandoffRequired: true,
    evidenceRequired: false,
    lineageRequired: true,
    restrictionRequired: false,
    confidenceRequired: true,
    contradictionAware: false,
    regimeAware: true,
    sequenceAware: false,
    hypothesisAware: false,
    scoreContextAware: false,
    scenarioAware: false,
    rawRebuildProhibited: true,
    allowedL13Uses: [
      ...EXPLAIN_AND_REPORT,
      L13AllowedCapability.EXPLAIN_REGIME,
      L13AllowedCapability.DISCLOSE_UNCERTAINTY,
    ],
    required: true,
    policyVersion: POLICY_V,
    description: 'L8 regime confidence — disclosed; never inflated',
  },
  {
    surfaceId: 'l8:regime_transition_risk',
    sourceLayer: L13DependencyLayer.L8_REGIME,
    surfaceClass: L13DependencySurfaceClass.REGIME_TRANSITION_RISK,
    stableHandoffRequired: true,
    evidenceRequired: true,
    lineageRequired: true,
    restrictionRequired: false,
    confidenceRequired: true,
    contradictionAware: false,
    regimeAware: true,
    sequenceAware: false,
    hypothesisAware: false,
    scoreContextAware: false,
    scenarioAware: false,
    rawRebuildProhibited: true,
    allowedL13Uses: [
      ...EXPLAIN_AND_REPORT,
      L13AllowedCapability.EXPLAIN_REGIME,
      L13AllowedCapability.DISCLOSE_UNCERTAINTY,
    ],
    required: true,
    policyVersion: POLICY_V,
    description: 'L8 regime transition risk — surfaced; never converted into prediction',
  },

  // ── L9 — sequence ──
  {
    surfaceId: 'l9:sequence_state',
    sourceLayer: L13DependencyLayer.L9_SEQUENCE,
    surfaceClass: L13DependencySurfaceClass.SEQUENCE_STATE,
    stableHandoffRequired: true,
    evidenceRequired: true,
    lineageRequired: true,
    restrictionRequired: true,
    confidenceRequired: true,
    contradictionAware: false,
    regimeAware: false,
    sequenceAware: true,
    hypothesisAware: false,
    scoreContextAware: false,
    scenarioAware: false,
    rawRebuildProhibited: true,
    allowedL13Uses: [
      ...FULL_EXPLANATION_USES,
      L13AllowedCapability.EXPLAIN_SEQUENCE,
    ],
    required: true,
    policyVersion: POLICY_V,
    description: 'L9 sequence state — explainable phase posture, never re-inferred in L13',
  },
  {
    surfaceId: 'l9:sequence_phase',
    sourceLayer: L13DependencyLayer.L9_SEQUENCE,
    surfaceClass: L13DependencySurfaceClass.SEQUENCE_PHASE,
    stableHandoffRequired: true,
    evidenceRequired: true,
    lineageRequired: true,
    restrictionRequired: true,
    confidenceRequired: true,
    contradictionAware: false,
    regimeAware: false,
    sequenceAware: true,
    hypothesisAware: false,
    scoreContextAware: false,
    scenarioAware: false,
    rawRebuildProhibited: true,
    allowedL13Uses: [
      ...EXPLAIN_AND_REPORT,
      L13AllowedCapability.EXPLAIN_SEQUENCE,
    ],
    required: true,
    policyVersion: POLICY_V,
    description: 'L9 sequence phase — early/validated/crowded/late/decay',
  },
  {
    surfaceId: 'l9:sequence_decay',
    sourceLayer: L13DependencyLayer.L9_SEQUENCE,
    surfaceClass: L13DependencySurfaceClass.SEQUENCE_DECAY,
    stableHandoffRequired: true,
    evidenceRequired: true,
    lineageRequired: true,
    restrictionRequired: true,
    confidenceRequired: true,
    contradictionAware: false,
    regimeAware: false,
    sequenceAware: true,
    hypothesisAware: false,
    scoreContextAware: false,
    scenarioAware: false,
    rawRebuildProhibited: true,
    allowedL13Uses: [
      ...EXPLAIN_AND_REPORT,
      L13AllowedCapability.EXPLAIN_SEQUENCE,
      L13AllowedCapability.DISCLOSE_UNCERTAINTY,
    ],
    required: true,
    policyVersion: POLICY_V,
    description: 'L9 sequence decay — must not be ignored when explaining late setups',
  },
  {
    surfaceId: 'l9:sequence_restriction_profile',
    sourceLayer: L13DependencyLayer.L9_SEQUENCE,
    surfaceClass:
      L13DependencySurfaceClass.SEQUENCE_RESTRICTION_PROFILE,
    stableHandoffRequired: true,
    evidenceRequired: false,
    lineageRequired: true,
    restrictionRequired: true,
    confidenceRequired: false,
    contradictionAware: false,
    regimeAware: false,
    sequenceAware: true,
    hypothesisAware: false,
    scoreContextAware: false,
    scenarioAware: false,
    rawRebuildProhibited: true,
    allowedL13Uses: FULL_EXPLANATION_USES,
    required: true,
    policyVersion: POLICY_V,
    description: 'L9 sequence restriction profile — must be honoured',
  },

  // ── L10 — hypothesis ──
  {
    surfaceId: 'l10:hypothesis_ranking',
    sourceLayer: L13DependencyLayer.L10_HYPOTHESIS,
    surfaceClass: L13DependencySurfaceClass.HYPOTHESIS_RANKING,
    stableHandoffRequired: true,
    evidenceRequired: true,
    lineageRequired: true,
    restrictionRequired: true,
    confidenceRequired: true,
    contradictionAware: true,
    regimeAware: false,
    sequenceAware: false,
    hypothesisAware: true,
    scoreContextAware: false,
    scenarioAware: false,
    rawRebuildProhibited: true,
    allowedL13Uses: [
      ...FULL_EXPLANATION_USES,
      L13AllowedCapability.EXPLAIN_HYPOTHESES,
    ],
    required: true,
    policyVersion: POLICY_V,
    description: 'L10 hypothesis ranking — primary/secondary; never reranked locally',
  },
  {
    surfaceId: 'l10:hypothesis_spread',
    sourceLayer: L13DependencyLayer.L10_HYPOTHESIS,
    surfaceClass: L13DependencySurfaceClass.HYPOTHESIS_SPREAD,
    stableHandoffRequired: true,
    evidenceRequired: false,
    lineageRequired: true,
    restrictionRequired: true,
    confidenceRequired: true,
    contradictionAware: true,
    regimeAware: false,
    sequenceAware: false,
    hypothesisAware: true,
    scoreContextAware: false,
    scenarioAware: false,
    rawRebuildProhibited: true,
    allowedL13Uses: [
      ...EXPLAIN_AND_REPORT,
      L13AllowedCapability.EXPLAIN_HYPOTHESES,
      L13AllowedCapability.DISCLOSE_UNCERTAINTY,
    ],
    required: true,
    policyVersion: POLICY_V,
    description: 'L10 hypothesis spread — narrow spread must be disclosed',
  },
  {
    surfaceId: 'l10:hypothesis_support_contradiction',
    sourceLayer: L13DependencyLayer.L10_HYPOTHESIS,
    surfaceClass:
      L13DependencySurfaceClass.HYPOTHESIS_SUPPORT_CONTRADICTION,
    stableHandoffRequired: true,
    evidenceRequired: true,
    lineageRequired: true,
    restrictionRequired: true,
    confidenceRequired: true,
    contradictionAware: true,
    regimeAware: false,
    sequenceAware: false,
    hypothesisAware: true,
    scoreContextAware: false,
    scenarioAware: false,
    rawRebuildProhibited: true,
    allowedL13Uses: [
      ...EXPLAIN_AND_REPORT,
      L13AllowedCapability.EXPLAIN_HYPOTHESES,
      L13AllowedCapability.DISCLOSE_CONTRADICTION,
    ],
    required: true,
    policyVersion: POLICY_V,
    description: 'L10 hypothesis support / contradiction evidence',
  },
  {
    surfaceId: 'l10:hypothesis_shift_conditions',
    sourceLayer: L13DependencyLayer.L10_HYPOTHESIS,
    surfaceClass: L13DependencySurfaceClass.HYPOTHESIS_SHIFT_CONDITIONS,
    stableHandoffRequired: true,
    evidenceRequired: false,
    lineageRequired: true,
    restrictionRequired: true,
    confidenceRequired: false,
    contradictionAware: false,
    regimeAware: false,
    sequenceAware: false,
    hypothesisAware: true,
    scoreContextAware: false,
    scenarioAware: false,
    rawRebuildProhibited: true,
    allowedL13Uses: [
      ...EXPLAIN_AND_REPORT,
      L13AllowedCapability.EXPLAIN_HYPOTHESES,
    ],
    required: true,
    policyVersion: POLICY_V,
    description: 'L10 hypothesis shift conditions — what would change ranking',
  },

  // ── L11 — score (always context-bundle bound) ──
  {
    surfaceId: 'l11:score_output',
    sourceLayer: L13DependencyLayer.L11_SCORE,
    surfaceClass: L13DependencySurfaceClass.SCORE_OUTPUT,
    stableHandoffRequired: true,
    evidenceRequired: true,
    lineageRequired: true,
    restrictionRequired: true,
    confidenceRequired: true,
    contradictionAware: false,
    regimeAware: false,
    sequenceAware: false,
    hypothesisAware: false,
    scoreContextAware: true,
    scenarioAware: false,
    rawRebuildProhibited: true,
    allowedL13Uses: [
      ...EXPLAIN_AND_REPORT,
      L13AllowedCapability.EXPLAIN_SCORES,
    ],
    required: true,
    policyVersion: POLICY_V,
    description: 'L11 score output — context-bundle required',
  },
  {
    surfaceId: 'l11:score_components',
    sourceLayer: L13DependencyLayer.L11_SCORE,
    surfaceClass: L13DependencySurfaceClass.SCORE_COMPONENTS,
    stableHandoffRequired: true,
    evidenceRequired: true,
    lineageRequired: true,
    restrictionRequired: true,
    confidenceRequired: false,
    contradictionAware: false,
    regimeAware: false,
    sequenceAware: false,
    hypothesisAware: false,
    scoreContextAware: true,
    scenarioAware: false,
    rawRebuildProhibited: true,
    allowedL13Uses: [
      ...EXPLAIN_AND_REPORT,
      L13AllowedCapability.EXPLAIN_SCORES,
    ],
    required: true,
    policyVersion: POLICY_V,
    description: 'L11 score components — used to explain composition',
  },
  {
    surfaceId: 'l11:score_attribution',
    sourceLayer: L13DependencyLayer.L11_SCORE,
    surfaceClass: L13DependencySurfaceClass.SCORE_ATTRIBUTION,
    stableHandoffRequired: true,
    evidenceRequired: true,
    lineageRequired: true,
    restrictionRequired: true,
    confidenceRequired: false,
    contradictionAware: false,
    regimeAware: false,
    sequenceAware: false,
    hypothesisAware: false,
    scoreContextAware: true,
    scenarioAware: false,
    rawRebuildProhibited: true,
    allowedL13Uses: [
      ...EXPLAIN_AND_REPORT,
      L13AllowedCapability.EXPLAIN_SCORES,
    ],
    required: true,
    policyVersion: POLICY_V,
    description: 'L11 score attribution — required for any score explanation',
  },
  {
    surfaceId: 'l11:score_missing_data_profile',
    sourceLayer: L13DependencyLayer.L11_SCORE,
    surfaceClass: L13DependencySurfaceClass.SCORE_MISSING_DATA_PROFILE,
    stableHandoffRequired: true,
    evidenceRequired: false,
    lineageRequired: true,
    restrictionRequired: true,
    confidenceRequired: false,
    contradictionAware: false,
    regimeAware: false,
    sequenceAware: false,
    hypothesisAware: false,
    scoreContextAware: true,
    scenarioAware: false,
    rawRebuildProhibited: true,
    allowedL13Uses: [
      ...EXPLAIN_AND_REPORT,
      L13AllowedCapability.EXPLAIN_SCORES,
      L13AllowedCapability.DISCLOSE_UNCERTAINTY,
    ],
    required: true,
    policyVersion: POLICY_V,
    description: 'L11 score missing-data profile — must be disclosed when not clean',
  },
  {
    surfaceId: 'l11:score_drift_status',
    sourceLayer: L13DependencyLayer.L11_SCORE,
    surfaceClass: L13DependencySurfaceClass.SCORE_DRIFT_STATUS,
    stableHandoffRequired: true,
    evidenceRequired: false,
    lineageRequired: true,
    restrictionRequired: true,
    confidenceRequired: false,
    contradictionAware: false,
    regimeAware: false,
    sequenceAware: false,
    hypothesisAware: false,
    scoreContextAware: true,
    scenarioAware: false,
    rawRebuildProhibited: true,
    allowedL13Uses: [
      ...EXPLAIN_AND_REPORT,
      L13AllowedCapability.EXPLAIN_SCORES,
      L13AllowedCapability.DISCLOSE_UNCERTAINTY,
    ],
    required: true,
    policyVersion: POLICY_V,
    description: 'L11 score drift status — must be disclosed when not stable',
  },
  {
    surfaceId: 'l11:score_restrictions',
    sourceLayer: L13DependencyLayer.L11_SCORE,
    surfaceClass: L13DependencySurfaceClass.SCORE_RESTRICTIONS,
    stableHandoffRequired: true,
    evidenceRequired: false,
    lineageRequired: true,
    restrictionRequired: true,
    confidenceRequired: false,
    contradictionAware: false,
    regimeAware: false,
    sequenceAware: false,
    hypothesisAware: false,
    scoreContextAware: true,
    scenarioAware: false,
    rawRebuildProhibited: true,
    allowedL13Uses: FULL_EXPLANATION_USES,
    required: true,
    policyVersion: POLICY_V,
    description: 'L11 score restrictions — block recommendation framing',
  },

  // ── L12 — scenario (always with triggers/invalidations/path-confidence) ──
  {
    surfaceId: 'l12:scenario_set',
    sourceLayer: L13DependencyLayer.L12_SCENARIO,
    surfaceClass: L13DependencySurfaceClass.SCENARIO_SET,
    stableHandoffRequired: true,
    evidenceRequired: true,
    lineageRequired: true,
    restrictionRequired: true,
    confidenceRequired: true,
    contradictionAware: true,
    regimeAware: true,
    sequenceAware: true,
    hypothesisAware: true,
    scoreContextAware: true,
    scenarioAware: true,
    rawRebuildProhibited: true,
    allowedL13Uses: [
      ...FULL_EXPLANATION_USES,
      L13AllowedCapability.EXPLAIN_SCENARIOS,
    ],
    required: true,
    policyVersion: POLICY_V,
    description: 'L12 scenario set — never rebuilt or re-ranked in L13',
  },
  {
    surfaceId: 'l12:base_case',
    sourceLayer: L13DependencyLayer.L12_SCENARIO,
    surfaceClass: L13DependencySurfaceClass.BASE_CASE,
    stableHandoffRequired: true,
    evidenceRequired: true,
    lineageRequired: true,
    restrictionRequired: true,
    confidenceRequired: true,
    contradictionAware: true,
    regimeAware: false,
    sequenceAware: false,
    hypothesisAware: false,
    scoreContextAware: false,
    scenarioAware: true,
    rawRebuildProhibited: true,
    allowedL13Uses: [
      ...EXPLAIN_AND_REPORT,
      L13AllowedCapability.EXPLAIN_SCENARIOS,
    ],
    required: true,
    policyVersion: POLICY_V,
    description: 'L12 base case — referenced as the engine\'s current interpretation',
  },
  {
    surfaceId: 'l12:alternative_paths',
    sourceLayer: L13DependencyLayer.L12_SCENARIO,
    surfaceClass: L13DependencySurfaceClass.ALTERNATIVE_PATHS,
    stableHandoffRequired: true,
    evidenceRequired: true,
    lineageRequired: true,
    restrictionRequired: true,
    confidenceRequired: true,
    contradictionAware: true,
    regimeAware: false,
    sequenceAware: false,
    hypothesisAware: false,
    scoreContextAware: false,
    scenarioAware: true,
    rawRebuildProhibited: true,
    allowedL13Uses: [
      ...EXPLAIN_AND_REPORT,
      L13AllowedCapability.EXPLAIN_SCENARIOS,
    ],
    required: true,
    policyVersion: POLICY_V,
    description: 'L12 alternative paths — preserved, never collapsed into one',
  },
  {
    surfaceId: 'l12:scenario_triggers',
    sourceLayer: L13DependencyLayer.L12_SCENARIO,
    surfaceClass: L13DependencySurfaceClass.SCENARIO_TRIGGERS,
    stableHandoffRequired: true,
    evidenceRequired: true,
    lineageRequired: true,
    restrictionRequired: true,
    confidenceRequired: false,
    contradictionAware: false,
    regimeAware: false,
    sequenceAware: false,
    hypothesisAware: false,
    scoreContextAware: false,
    scenarioAware: true,
    rawRebuildProhibited: true,
    allowedL13Uses: [
      ...FULL_EXPLANATION_USES,
      L13AllowedCapability.EXPLAIN_SCENARIOS,
    ],
    required: true,
    policyVersion: POLICY_V,
    description: 'L12 scenario triggers — required disclosure when explaining a path',
  },
  {
    surfaceId: 'l12:scenario_invalidations',
    sourceLayer: L13DependencyLayer.L12_SCENARIO,
    surfaceClass: L13DependencySurfaceClass.SCENARIO_INVALIDATIONS,
    stableHandoffRequired: true,
    evidenceRequired: true,
    lineageRequired: true,
    restrictionRequired: true,
    confidenceRequired: false,
    contradictionAware: true,
    regimeAware: false,
    sequenceAware: false,
    hypothesisAware: false,
    scoreContextAware: false,
    scenarioAware: true,
    rawRebuildProhibited: true,
    allowedL13Uses: [
      ...FULL_EXPLANATION_USES,
      L13AllowedCapability.EXPLAIN_SCENARIOS,
    ],
    required: true,
    policyVersion: POLICY_V,
    description: 'L12 scenario invalidations — required disclosure',
  },
  {
    surfaceId: 'l12:path_confidence',
    sourceLayer: L13DependencyLayer.L12_SCENARIO,
    surfaceClass: L13DependencySurfaceClass.PATH_CONFIDENCE,
    stableHandoffRequired: true,
    evidenceRequired: false,
    lineageRequired: true,
    restrictionRequired: true,
    confidenceRequired: true,
    contradictionAware: false,
    regimeAware: false,
    sequenceAware: false,
    hypothesisAware: false,
    scoreContextAware: false,
    scenarioAware: true,
    rawRebuildProhibited: true,
    allowedL13Uses: [
      ...EXPLAIN_AND_REPORT,
      L13AllowedCapability.EXPLAIN_SCENARIOS,
      L13AllowedCapability.DISCLOSE_UNCERTAINTY,
    ],
    required: true,
    policyVersion: POLICY_V,
    description: 'L12 path confidence — never presented as probability of outcome',
  },
  {
    surfaceId: 'l12:scenario_spread',
    sourceLayer: L13DependencyLayer.L12_SCENARIO,
    surfaceClass: L13DependencySurfaceClass.SCENARIO_SPREAD,
    stableHandoffRequired: true,
    evidenceRequired: false,
    lineageRequired: true,
    restrictionRequired: true,
    confidenceRequired: true,
    contradictionAware: false,
    regimeAware: false,
    sequenceAware: false,
    hypothesisAware: false,
    scoreContextAware: false,
    scenarioAware: true,
    rawRebuildProhibited: true,
    allowedL13Uses: [
      ...EXPLAIN_AND_REPORT,
      L13AllowedCapability.EXPLAIN_SCENARIOS,
      L13AllowedCapability.DISCLOSE_UNCERTAINTY,
    ],
    required: true,
    policyVersion: POLICY_V,
    description: 'L12 scenario spread — narrow spread must be disclosed',
  },
  {
    surfaceId: 'l12:scenario_shift_conditions',
    sourceLayer: L13DependencyLayer.L12_SCENARIO,
    surfaceClass: L13DependencySurfaceClass.SCENARIO_SHIFT_CONDITIONS,
    stableHandoffRequired: true,
    evidenceRequired: false,
    lineageRequired: true,
    restrictionRequired: true,
    confidenceRequired: false,
    contradictionAware: false,
    regimeAware: false,
    sequenceAware: false,
    hypothesisAware: false,
    scoreContextAware: false,
    scenarioAware: true,
    rawRebuildProhibited: true,
    allowedL13Uses: [
      ...EXPLAIN_AND_REPORT,
      L13AllowedCapability.EXPLAIN_SCENARIOS,
    ],
    required: true,
    policyVersion: POLICY_V,
    description: 'L12 scenario shift conditions — describe what would shift ranking',
  },
  {
    surfaceId: 'l12:scenario_restrictions',
    sourceLayer: L13DependencyLayer.L12_SCENARIO,
    surfaceClass: L13DependencySurfaceClass.SCENARIO_RESTRICTIONS,
    stableHandoffRequired: true,
    evidenceRequired: false,
    lineageRequired: true,
    restrictionRequired: true,
    confidenceRequired: false,
    contradictionAware: false,
    regimeAware: false,
    sequenceAware: false,
    hypothesisAware: false,
    scoreContextAware: false,
    scenarioAware: true,
    rawRebuildProhibited: true,
    allowedL13Uses: FULL_EXPLANATION_USES,
    required: true,
    policyVersion: POLICY_V,
    description: 'L12 scenario restrictions — must be honoured by every explanation',
  },
  {
    surfaceId: 'l12:scenario_evidence',
    sourceLayer: L13DependencyLayer.L12_SCENARIO,
    surfaceClass: L13DependencySurfaceClass.SCENARIO_EVIDENCE,
    stableHandoffRequired: true,
    evidenceRequired: true,
    lineageRequired: true,
    restrictionRequired: true,
    confidenceRequired: false,
    contradictionAware: true,
    regimeAware: false,
    sequenceAware: false,
    hypothesisAware: false,
    scoreContextAware: false,
    scenarioAware: true,
    rawRebuildProhibited: true,
    allowedL13Uses: FULL_EXPLANATION_USES,
    required: true,
    policyVersion: POLICY_V,
    description: 'L12 scenario evidence — citation source for L13 explanation',
  },
  {
    surfaceId: 'l12:scenario_lineage',
    sourceLayer: L13DependencyLayer.L12_SCENARIO,
    surfaceClass: L13DependencySurfaceClass.SCENARIO_LINEAGE,
    stableHandoffRequired: true,
    evidenceRequired: false,
    lineageRequired: true,
    restrictionRequired: true,
    confidenceRequired: false,
    contradictionAware: false,
    regimeAware: false,
    sequenceAware: false,
    hypothesisAware: false,
    scoreContextAware: false,
    scenarioAware: true,
    rawRebuildProhibited: true,
    allowedL13Uses: FULL_EXPLANATION_USES,
    required: true,
    policyVersion: POLICY_V,
    description: 'L12 scenario lineage — replay/repair anchor for L13',
  },
];

/**
 * §13.1.3.9 — The L11 score-context bundle ids that must accompany
 * any L11 score consumption by L13. Reading score output without
 * attribution / missing-data / drift / restriction is illegal.
 */
export const L13_L11_SCORE_CONTEXT_BUNDLE_SURFACE_IDS:
  readonly string[] = [
  'l11:score_output',
  'l11:score_components',
  'l11:score_attribution',
  'l11:score_missing_data_profile',
  'l11:score_drift_status',
  'l11:score_restrictions',
];

/**
 * §13.1.3.10 — The L12 scenario bundle ids that must accompany any
 * L12 scenario consumption. Reading scenario set without
 * triggers / invalidations / path confidence / restrictions is
 * illegal.
 */
export const L13_L12_SCENARIO_BUNDLE_SURFACE_IDS:
  readonly string[] = [
  'l12:scenario_set',
  'l12:base_case',
  'l12:alternative_paths',
  'l12:scenario_triggers',
  'l12:scenario_invalidations',
  'l12:path_confidence',
  'l12:scenario_restrictions',
];

export function getL13DependencySurface(
  surfaceId: string,
): L13DependencySurfaceDescriptor | undefined {
  return L13_DEPENDENCY_SURFACES.find(s => s.surfaceId === surfaceId);
}

export function isL13RegisteredDependency(surfaceId: string): boolean {
  return L13_DEPENDENCY_SURFACES.some(s => s.surfaceId === surfaceId);
}

export function getL13SurfacesForLayer(
  layer: L13DependencyLayer,
): readonly L13DependencySurfaceDescriptor[] {
  return L13_DEPENDENCY_SURFACES.filter(s => s.sourceLayer === layer);
}

export function getL13RequiredDependencySurfaces():
  readonly L13DependencySurfaceDescriptor[] {
  return L13_DEPENDENCY_SURFACES.filter(s => s.required);
}

export function getL13ContradictionAwareSurfaces():
  readonly L13DependencySurfaceDescriptor[] {
  return L13_DEPENDENCY_SURFACES.filter(s => s.contradictionAware);
}

export function getL13ScoreContextSurfaces():
  readonly L13DependencySurfaceDescriptor[] {
  return L13_DEPENDENCY_SURFACES.filter(s => s.scoreContextAware);
}

export function getL13ScenarioSurfaces():
  readonly L13DependencySurfaceDescriptor[] {
  return L13_DEPENDENCY_SURFACES.filter(s => s.scenarioAware);
}

export function getL13RestrictionAwareSurfaces():
  readonly L13DependencySurfaceDescriptor[] {
  return L13_DEPENDENCY_SURFACES.filter(s => s.restrictionRequired);
}

export function isL13UseAllowed(
  surfaceId: string,
  capability: L13AllowedCapability,
): boolean {
  const s = getL13DependencySurface(surfaceId);
  if (!s) return false;
  return s.allowedL13Uses.includes(capability);
}
