/**
 * L13.1 — Constitutional Violation Codes
 *
 * §13.1.11 — Every constitutional boundary failure carries a typed
 * code in the disjoint `L13C_` namespace so audit records and
 * validator decisions stay deterministic and disjoint from L11/L12.
 */

export enum L13ConstitutionalViolationCode {
  // Mission and first principle
  L13C_MISSION_MISSING = 'L13C_MISSION_MISSING',
  L13C_FIRST_PRINCIPLE_MISSING = 'L13C_FIRST_PRINCIPLE_MISSING',
  L13C_MISSION_MISMATCH = 'L13C_MISSION_MISMATCH',

  // Layer-role confusion
  L13C_LAYER_ROLE_CONFUSED = 'L13C_LAYER_ROLE_CONFUSED',
  L13C_AI_ACTS_AS_ENGINE = 'L13C_AI_ACTS_AS_ENGINE',

  // Dependency / consumption
  L13C_DEPENDENCY_SURFACE_UNREGISTERED =
    'L13C_DEPENDENCY_SURFACE_UNREGISTERED',
  L13C_LATE_LAYER_DEPENDENCY = 'L13C_LATE_LAYER_DEPENDENCY',
  L13C_RAW_LOWER_LAYER_BYPASS = 'L13C_RAW_LOWER_LAYER_BYPASS',
  L13C_ILLEGAL_DEPENDENCY_USAGE = 'L13C_ILLEGAL_DEPENDENCY_USAGE',

  // Lower-layer rebuild
  L13C_REBUILDS_SCENARIO = 'L13C_REBUILDS_SCENARIO',
  L13C_REBUILDS_SCORE = 'L13C_REBUILDS_SCORE',
  L13C_REBUILDS_HYPOTHESIS = 'L13C_REBUILDS_HYPOTHESIS',
  L13C_REBUILDS_SEQUENCE = 'L13C_REBUILDS_SEQUENCE',
  L13C_REBUILDS_REGIME = 'L13C_REBUILDS_REGIME',

  // Invention / hiding / restriction bypass
  L13C_INVENTS_SUPPORT = 'L13C_INVENTS_SUPPORT',
  L13C_HIDES_CONTRADICTION = 'L13C_HIDES_CONTRADICTION',
  L13C_IGNORES_RESTRICTION = 'L13C_IGNORES_RESTRICTION',
  L13C_OVERRIDES_CONFIDENCE = 'L13C_OVERRIDES_CONFIDENCE',
  L13C_PRETENDS_MISSING_DATA_COMPLETE =
    'L13C_PRETENDS_MISSING_DATA_COMPLETE',

  // Engine creation by L13
  L13C_CREATES_NEW_SCENARIO = 'L13C_CREATES_NEW_SCENARIO',
  L13C_CREATES_NEW_HYPOTHESIS = 'L13C_CREATES_NEW_HYPOTHESIS',
  L13C_COMPUTES_SCORE_LOCALLY = 'L13C_COMPUTES_SCORE_LOCALLY',

  // Recommendation leakage (buy/sell/hold/avoid/leverage/size/entry)
  L13C_BUY_SELL_HOLD_AVOID_LEAK = 'L13C_BUY_SELL_HOLD_AVOID_LEAK',
  L13C_LEVERAGE_ADVICE_LEAK = 'L13C_LEVERAGE_ADVICE_LEAK',
  L13C_POSITION_SIZE_LEAK = 'L13C_POSITION_SIZE_LEAK',
  L13C_ENTRY_EXIT_LEAK = 'L13C_ENTRY_EXIT_LEAK',

  // Prediction / certainty / final-judgment
  L13C_PREDICTION_THEATER = 'L13C_PREDICTION_THEATER',
  L13C_UNSUPPORTED_CERTAINTY = 'L13C_UNSUPPORTED_CERTAINTY',
  L13C_SCENARIO_AS_PROBABILITY = 'L13C_SCENARIO_AS_PROBABILITY',
  L13C_SCENARIO_AS_WINNER = 'L13C_SCENARIO_AS_WINNER',
  L13C_HYPOTHESIS_AS_FINAL_TRUTH = 'L13C_HYPOTHESIS_AS_FINAL_TRUTH',
  L13C_SCORE_AS_RECOMMENDATION = 'L13C_SCORE_AS_RECOMMENDATION',
  L13C_FINAL_JUDGMENT_LEAK = 'L13C_FINAL_JUDGMENT_LEAK',

  // Output law
  L13C_OUTPUT_SURFACE_UNREGISTERED = 'L13C_OUTPUT_SURFACE_UNREGISTERED',
  L13C_ILLEGAL_OUTPUT_CLASS = 'L13C_ILLEGAL_OUTPUT_CLASS',
  L13C_EVIDENCE_REFS_MISSING = 'L13C_EVIDENCE_REFS_MISSING',
  L13C_LINEAGE_REFS_MISSING = 'L13C_LINEAGE_REFS_MISSING',
  L13C_CONFIDENCE_DISCLOSURE_MISSING =
    'L13C_CONFIDENCE_DISCLOSURE_MISSING',
  L13C_RESTRICTION_DISCLOSURE_MISSING =
    'L13C_RESTRICTION_DISCLOSURE_MISSING',
  L13C_FORBIDDEN_NAMING = 'L13C_FORBIDDEN_NAMING',
  L13C_REPLAY_HASH_MISSING = 'L13C_REPLAY_HASH_MISSING',

  // Scenario disclosure law
  L13C_SCENARIO_WITHOUT_TRIGGER_DISCLOSURE =
    'L13C_SCENARIO_WITHOUT_TRIGGER_DISCLOSURE',
  L13C_SCENARIO_WITHOUT_INVALIDATION_DISCLOSURE =
    'L13C_SCENARIO_WITHOUT_INVALIDATION_DISCLOSURE',

  // Capability / audit / invariant
  L13C_ILLEGAL_CAPABILITY_CLAIM = 'L13C_ILLEGAL_CAPABILITY_CLAIM',
  L13C_CAPABILITY_DENIED = 'L13C_CAPABILITY_DENIED',
  L13C_AUDIT_RECORD_MISSING = 'L13C_AUDIT_RECORD_MISSING',
  L13C_INVARIANT_FAILED = 'L13C_INVARIANT_FAILED',
}

export const ALL_L13_VIOLATION_CODES:
  readonly L13ConstitutionalViolationCode[] =
  Object.values(L13ConstitutionalViolationCode);

export class L13ConstitutionalError extends Error {
  public readonly code: L13ConstitutionalViolationCode;
  public readonly details: Record<string, unknown>;

  constructor(
    code: L13ConstitutionalViolationCode,
    message: string,
    details: Record<string, unknown> = {},
  ) {
    super(`[${code}] ${message}`);
    this.name = 'L13ConstitutionalError';
    this.code = code;
    this.details = details;
  }
}
