/**
 * L13.1 — Constitutional Types
 *
 * §13.1.0–§13.1.5 — Core enums for the entire Layer 13 constitution.
 * Layer 13 is the AI Judgment & Explanation Layer. It is the *voice*
 * of the engine, not a second hidden reasoning engine. Layer 13 may
 * explain governed truth (L3–L12) but may never manufacture
 * judgment, recommendation, prediction, or final answer.
 *
 * §13.1.1.3 First principle:
 *   "The AI may explain judgment, but it may not manufacture
 *    judgment."
 */

/**
 * §13.1.0 — Layer 13 sublayer identities. L13.1 freezes the
 * constitutional boundary; later sublayers (L13.2+) layer on
 * grounding, explanation construction, persistence, and ratification.
 */
export enum L13SublayerId {
  L13_1_CONSTITUTION = 'L13.1_CONSTITUTION',
  L13_2_INPUT_PACKAGE = 'L13.2_INPUT_PACKAGE',
  L13_3_OUTPUT_CONTRACTS = 'L13.3_OUTPUT_CONTRACTS',
  L13_4_GROUNDING = 'L13.4_GROUNDING',
  L13_5_UNCERTAINTY_RESTRICTIONS = 'L13.5_UNCERTAINTY_RESTRICTIONS',
  L13_6_RUNTIME = 'L13.6_RUNTIME',
  L13_7_OUTPUT_MODES = 'L13.7_OUTPUT_MODES',
  L13_8_STYLE_LANGUAGE = 'L13.8_STYLE_LANGUAGE',
  L13_9_SAFETY = 'L13.9_SAFETY',
  L13_10_PERSISTENCE_FEEDBACK = 'L13.10_PERSISTENCE_FEEDBACK',
  L13_11_REPLAY_REPAIR_ADVERSARIAL = 'L13.11_REPLAY_REPAIR_ADVERSARIAL',
  L13_12_RATIFICATION = 'L13.12_RATIFICATION',
}

export const ALL_L13_SUBLAYER_IDS: readonly L13SublayerId[] =
  Object.values(L13SublayerId);

/**
 * §13.1.2 — Subject classes that L13 reasons about. L13 explains
 * engine state — it never owns truth.
 */
export enum L13SubjectClass {
  ENGINE_STATE_SUBJECT = 'ENGINE_STATE_SUBJECT',
  MARKET_STATE_SUBJECT = 'MARKET_STATE_SUBJECT',
  USER_QUESTION_SUBJECT = 'USER_QUESTION_SUBJECT',
  ALERT_SUBJECT = 'ALERT_SUBJECT',
  REPORT_SUBJECT = 'REPORT_SUBJECT',
  COMPARISON_SUBJECT = 'COMPARISON_SUBJECT',
  SCENARIO_EXPLANATION_SUBJECT = 'SCENARIO_EXPLANATION_SUBJECT',
  SCORE_EXPLANATION_SUBJECT = 'SCORE_EXPLANATION_SUBJECT',
  HYPOTHESIS_EXPLANATION_SUBJECT = 'HYPOTHESIS_EXPLANATION_SUBJECT',
  REGIME_EXPLANATION_SUBJECT = 'REGIME_EXPLANATION_SUBJECT',
  SEQUENCE_EXPLANATION_SUBJECT = 'SEQUENCE_EXPLANATION_SUBJECT',
  CONTRADICTION_DISCLOSURE_SUBJECT = 'CONTRADICTION_DISCLOSURE_SUBJECT',
  UNCERTAINTY_DISCLOSURE_SUBJECT = 'UNCERTAINTY_DISCLOSURE_SUBJECT',
  REFUSAL_SUBJECT = 'REFUSAL_SUBJECT',
}

export const ALL_L13_SUBJECT_CLASSES: readonly L13SubjectClass[] =
  Object.values(L13SubjectClass);

/**
 * §13.1.4 — Allowed Layer 13 capabilities. Each capability is
 * explanation-class only; no engine logic and no decision logic.
 */
export enum L13AllowedCapability {
  EXPLAIN_ENGINE_STATE = 'EXPLAIN_ENGINE_STATE',
  SUMMARIZE_MARKET_STATE = 'SUMMARIZE_MARKET_STATE',
  ANSWER_USER_QUESTION = 'ANSWER_USER_QUESTION',
  WRITE_ALERT_TEXT = 'WRITE_ALERT_TEXT',
  WRITE_STRUCTURED_REPORT = 'WRITE_STRUCTURED_REPORT',
  COMPARE_ASSETS = 'COMPARE_ASSETS',
  COMPARE_THESES = 'COMPARE_THESES',
  EXPLAIN_SCENARIOS = 'EXPLAIN_SCENARIOS',
  EXPLAIN_SCORES = 'EXPLAIN_SCORES',
  EXPLAIN_HYPOTHESES = 'EXPLAIN_HYPOTHESES',
  EXPLAIN_REGIME = 'EXPLAIN_REGIME',
  EXPLAIN_SEQUENCE = 'EXPLAIN_SEQUENCE',
  DISCLOSE_CONTRADICTION = 'DISCLOSE_CONTRADICTION',
  DISCLOSE_UNCERTAINTY = 'DISCLOSE_UNCERTAINTY',
  CITE_EVIDENCE_REFS = 'CITE_EVIDENCE_REFS',
  RESPECT_RESTRICTIONS = 'RESPECT_RESTRICTIONS',
  ADAPT_TONE_AND_LANGUAGE = 'ADAPT_TONE_AND_LANGUAGE',
  REFUSE_UNSUPPORTED_CONCLUSION = 'REFUSE_UNSUPPORTED_CONCLUSION',
}

export const ALL_L13_ALLOWED_CAPABILITIES:
  readonly L13AllowedCapability[] =
  Object.values(L13AllowedCapability);

/**
 * §13.1.4 — Capability groups for the AI Judgment & Explanation
 * Layer.
 */
export enum L13CapabilityGroup {
  EXPLANATION = 'EXPLANATION',
  QUESTION_ANSWERING = 'QUESTION_ANSWERING',
  ALERTING = 'ALERTING',
  REPORTING = 'REPORTING',
  COMPARISON = 'COMPARISON',
  DISCLOSURE = 'DISCLOSURE',
  STYLE_CONTROL = 'STYLE_CONTROL',
  REFUSAL_AND_BOUNDARY = 'REFUSAL_AND_BOUNDARY',
}

export const ALL_L13_CAPABILITY_GROUPS: readonly L13CapabilityGroup[] =
  Object.values(L13CapabilityGroup);

/**
 * §13.1.9 — Capability contexts. Each capability is allowed only
 * inside specific contexts; outside them the policy map returns
 * DENIED. Includes adversarial user contexts that the AI must refuse
 * (advice / certainty / one-label-only requests).
 */
export enum L13CapabilityContext {
  CHAT_ANSWER = 'CHAT_ANSWER',
  ALERT_GENERATION = 'ALERT_GENERATION',
  REPORT_GENERATION = 'REPORT_GENERATION',
  ASSET_COMPARISON = 'ASSET_COMPARISON',
  THESIS_COMPARISON = 'THESIS_COMPARISON',
  SCENARIO_EXPLANATION = 'SCENARIO_EXPLANATION',
  SCORE_EXPLANATION = 'SCORE_EXPLANATION',
  CONTRADICTION_EXPLANATION = 'CONTRADICTION_EXPLANATION',
  DEBUG_EXPLANATION = 'DEBUG_EXPLANATION',
  USER_REQUESTS_ADVICE = 'USER_REQUESTS_ADVICE',
  USER_REQUESTS_CERTAINTY = 'USER_REQUESTS_CERTAINTY',
  USER_REQUESTS_BULLISH_BEARISH_ONLY = 'USER_REQUESTS_BULLISH_BEARISH_ONLY',
}

export const ALL_L13_CAPABILITY_CONTEXTS:
  readonly L13CapabilityContext[] =
  Object.values(L13CapabilityContext);

/**
 * §13.1.9 — Decision return type for the L13 capability policy.
 */
export enum L13CapabilityDecision {
  ALLOWED = 'ALLOWED',
  CONDITIONALLY_ALLOWED = 'CONDITIONALLY_ALLOWED',
  DENIED = 'DENIED',
}

/**
 * §13.1.5 — Forbidden actions at Layer 13. Each is rejected by the
 * forbidden-action registry and the boundary validators.
 */
export enum L13ForbiddenAction {
  INVENT_MISSING_SUPPORT = 'INVENT_MISSING_SUPPORT',
  HIDE_CONTRADICTION = 'HIDE_CONTRADICTION',
  IGNORE_RESTRICTION = 'IGNORE_RESTRICTION',
  OVERRIDE_CONFIDENCE_CAP = 'OVERRIDE_CONFIDENCE_CAP',
  REBUILD_SCENARIO = 'REBUILD_SCENARIO',
  REBUILD_SCORE = 'REBUILD_SCORE',
  REBUILD_HYPOTHESIS = 'REBUILD_HYPOTHESIS',
  REBUILD_SEQUENCE = 'REBUILD_SEQUENCE',
  REBUILD_REGIME = 'REBUILD_REGIME',
  CREATE_NEW_SCENARIO = 'CREATE_NEW_SCENARIO',
  CREATE_NEW_HYPOTHESIS = 'CREATE_NEW_HYPOTHESIS',
  COMPUTE_SCORE_LOCALLY = 'COMPUTE_SCORE_LOCALLY',
  TREAT_SCENARIO_CONFIDENCE_AS_PROBABILITY =
    'TREAT_SCENARIO_CONFIDENCE_AS_PROBABILITY',
  EMIT_BUY_INSTRUCTION = 'EMIT_BUY_INSTRUCTION',
  EMIT_SELL_INSTRUCTION = 'EMIT_SELL_INSTRUCTION',
  EMIT_HOLD_INSTRUCTION = 'EMIT_HOLD_INSTRUCTION',
  EMIT_AVOID_INSTRUCTION = 'EMIT_AVOID_INSTRUCTION',
  EMIT_LEVERAGE_INSTRUCTION = 'EMIT_LEVERAGE_INSTRUCTION',
  EMIT_POSITION_SIZE_INSTRUCTION = 'EMIT_POSITION_SIZE_INSTRUCTION',
  EMIT_ENTRY_EXIT_INSTRUCTION = 'EMIT_ENTRY_EXIT_INSTRUCTION',
  CLAIM_GUARANTEE = 'CLAIM_GUARANTEE',
  CLAIM_CERTAINTY_UNSUPPORTED = 'CLAIM_CERTAINTY_UNSUPPORTED',
  CALL_SCENARIO_WINNER = 'CALL_SCENARIO_WINNER',
  CALL_HYPOTHESIS_FINAL_TRUTH = 'CALL_HYPOTHESIS_FINAL_TRUTH',
  SAY_SCORE_MEANS_RECOMMENDATION = 'SAY_SCORE_MEANS_RECOMMENDATION',
  PRETEND_MISSING_DATA_COMPLETE = 'PRETEND_MISSING_DATA_COMPLETE',
  OMIT_ACTIVE_INVALIDATION = 'OMIT_ACTIVE_INVALIDATION',
  OMIT_REQUIRED_TRIGGER = 'OMIT_REQUIRED_TRIGGER',
  USE_RAW_LOWER_LAYER_BYPASS = 'USE_RAW_LOWER_LAYER_BYPASS',
  OUTPUT_UNGROUNDED_CLAIM = 'OUTPUT_UNGROUNDED_CLAIM',
}

export const ALL_L13_FORBIDDEN_ACTIONS: readonly L13ForbiddenAction[] =
  Object.values(L13ForbiddenAction);

/**
 * §13.1.3 — Hard dependency law. Layer 13 depends on L3–L12 only.
 * Late-layer (L14+) dependencies are forbidden.
 */
export enum L13DependencyLayer {
  L3_IDENTITY = 'L3_IDENTITY',
  L4_GRAPH = 'L4_GRAPH',
  L5_STORAGE = 'L5_STORAGE',
  L6_FEATURE_EVENT = 'L6_FEATURE_EVENT',
  L7_VALIDATION = 'L7_VALIDATION',
  L8_REGIME = 'L8_REGIME',
  L9_SEQUENCE = 'L9_SEQUENCE',
  L10_HYPOTHESIS = 'L10_HYPOTHESIS',
  L11_SCORE = 'L11_SCORE',
  L12_SCENARIO = 'L12_SCENARIO',
}

export const ALL_L13_DEPENDENCY_LAYERS: readonly L13DependencyLayer[] =
  Object.values(L13DependencyLayer);

/**
 * §13.1.7 — Dependency surface classes that L13 may consume from
 * each frozen layer L3–L12. Each maps to a stable governed handoff;
 * raw lower-layer rebuild surfaces are NOT permitted.
 */
export enum L13DependencySurfaceClass {
  // L3 — identity and scope
  CANONICAL_ENTITY_SUMMARY = 'CANONICAL_ENTITY_SUMMARY',
  SCOPE_LAW = 'SCOPE_LAW',

  // L4 — graph context
  GRAPH_CONTEXT = 'GRAPH_CONTEXT',

  // L5 — storage / read services
  STORAGE_READ_SERVICE = 'STORAGE_READ_SERVICE',
  EVIDENCE_READ_SERVICE = 'EVIDENCE_READ_SERVICE',
  LINEAGE_READ_SERVICE = 'LINEAGE_READ_SERVICE',

  // L6 — feature/event summaries (governed only)
  FEATURE_EVIDENCE_REF_SURFACE = 'FEATURE_EVIDENCE_REF_SURFACE',
  EVENT_EVIDENCE_REF_SURFACE = 'EVENT_EVIDENCE_REF_SURFACE',

  // L7 — validation / contradiction / restriction
  VALIDATION_ASSESSMENT = 'VALIDATION_ASSESSMENT',
  CONTRADICTION_BUNDLE = 'CONTRADICTION_BUNDLE',
  VALIDATION_RESTRICTION_PROFILE = 'VALIDATION_RESTRICTION_PROFILE',

  // L8 — regime
  REGIME_STATE = 'REGIME_STATE',
  REGIME_CONFIDENCE = 'REGIME_CONFIDENCE',
  REGIME_TRANSITION_RISK = 'REGIME_TRANSITION_RISK',

  // L9 — sequence
  SEQUENCE_STATE = 'SEQUENCE_STATE',
  SEQUENCE_PHASE = 'SEQUENCE_PHASE',
  SEQUENCE_DECAY = 'SEQUENCE_DECAY',
  SEQUENCE_RESTRICTION_PROFILE = 'SEQUENCE_RESTRICTION_PROFILE',

  // L10 — hypothesis
  HYPOTHESIS_RANKING = 'HYPOTHESIS_RANKING',
  HYPOTHESIS_SPREAD = 'HYPOTHESIS_SPREAD',
  HYPOTHESIS_SUPPORT_CONTRADICTION = 'HYPOTHESIS_SUPPORT_CONTRADICTION',
  HYPOTHESIS_SHIFT_CONDITIONS = 'HYPOTHESIS_SHIFT_CONDITIONS',

  // L11 — score (always context-bundle-bound)
  SCORE_OUTPUT = 'SCORE_OUTPUT',
  SCORE_COMPONENTS = 'SCORE_COMPONENTS',
  SCORE_ATTRIBUTION = 'SCORE_ATTRIBUTION',
  SCORE_MISSING_DATA_PROFILE = 'SCORE_MISSING_DATA_PROFILE',
  SCORE_DRIFT_STATUS = 'SCORE_DRIFT_STATUS',
  SCORE_RESTRICTIONS = 'SCORE_RESTRICTIONS',

  // L12 — scenario
  SCENARIO_SET = 'SCENARIO_SET',
  BASE_CASE = 'BASE_CASE',
  ALTERNATIVE_PATHS = 'ALTERNATIVE_PATHS',
  SCENARIO_TRIGGERS = 'SCENARIO_TRIGGERS',
  SCENARIO_INVALIDATIONS = 'SCENARIO_INVALIDATIONS',
  PATH_CONFIDENCE = 'PATH_CONFIDENCE',
  SCENARIO_SPREAD = 'SCENARIO_SPREAD',
  SCENARIO_SHIFT_CONDITIONS = 'SCENARIO_SHIFT_CONDITIONS',
  SCENARIO_RESTRICTIONS = 'SCENARIO_RESTRICTIONS',
  SCENARIO_EVIDENCE = 'SCENARIO_EVIDENCE',
  SCENARIO_LINEAGE = 'SCENARIO_LINEAGE',
}

export const ALL_L13_DEPENDENCY_SURFACE_CLASSES:
  readonly L13DependencySurfaceClass[] =
  Object.values(L13DependencySurfaceClass);

/**
 * §13.1.8 — Legal Layer 13 output surface classes. Every legal class
 * is an explanation-class output — no decision-class output is
 * permitted.
 */
export enum L13OutputSurfaceClass {
  AI_EXPLANATION_OUTPUT = 'AI_EXPLANATION_OUTPUT',
  AI_QUESTION_ANSWER_OUTPUT = 'AI_QUESTION_ANSWER_OUTPUT',
  AI_ALERT_OUTPUT = 'AI_ALERT_OUTPUT',
  AI_STRUCTURED_REPORT_OUTPUT = 'AI_STRUCTURED_REPORT_OUTPUT',
  AI_COMPARISON_OUTPUT = 'AI_COMPARISON_OUTPUT',
  AI_UNCERTAINTY_DISCLOSURE_OUTPUT = 'AI_UNCERTAINTY_DISCLOSURE_OUTPUT',
  AI_CONTRADICTION_DISCLOSURE_OUTPUT =
    'AI_CONTRADICTION_DISCLOSURE_OUTPUT',
  AI_BLOCKED_OUTPUT = 'AI_BLOCKED_OUTPUT',
  AI_GROUNDING_AUDIT_OUTPUT = 'AI_GROUNDING_AUDIT_OUTPUT',
}

export const ALL_L13_OUTPUT_SURFACE_CLASSES:
  readonly L13OutputSurfaceClass[] =
  Object.values(L13OutputSurfaceClass);

/**
 * §13.1.11 — Severity tiers used by L13 audit and by validators.
 */
export enum L13ViolationSeverity {
  CRITICAL = 'CRITICAL',
  ERROR = 'ERROR',
  WARNING = 'WARNING',
}

/**
 * §13.1.7 — Allowed downstream consumers of L13 explanation surfaces.
 * L13 outputs are user-facing or feed governed delivery / feedback /
 * governance layers — never lower-layer engines.
 */
export enum L13DownstreamConsumer {
  USER_FACING_DELIVERY = 'USER_FACING_DELIVERY',
  L14_DELIVERY = 'L14_DELIVERY',
  L15_FEEDBACK = 'L15_FEEDBACK',
  L16_GOVERNANCE = 'L16_GOVERNANCE',
  INTERNAL_AUDIT = 'INTERNAL_AUDIT',
}

export const ALL_L13_DOWNSTREAM_CONSUMERS:
  readonly L13DownstreamConsumer[] =
  Object.values(L13DownstreamConsumer);
