/**
 * L13.10 — Persistence Class + Write Intent Contracts
 *
 * §13.10.14 — Closed set of persistence classes drives the
 * materializer's dispatch and per-shape validation.
 */

export enum L13PersistenceClass {
  INPUT_PACKAGE = 'INPUT_PACKAGE',
  PROMPT_ASSEMBLY = 'PROMPT_ASSEMBLY',
  MODEL_RUN = 'MODEL_RUN',
  MODEL_RESPONSE_ARTIFACT = 'MODEL_RESPONSE_ARTIFACT',
  FINAL_AI_OUTPUT = 'FINAL_AI_OUTPUT',
  PRODUCT_MODE_PAYLOAD = 'PRODUCT_MODE_PAYLOAD',
  STYLED_RESPONSE = 'STYLED_RESPONSE',
  SAFETY_GATE_RESULT = 'SAFETY_GATE_RESULT',
  FINAL_GATE_RESULT = 'FINAL_GATE_RESULT',
  GROUNDED_CLAIM = 'GROUNDED_CLAIM',
  BLOCKED_CLAIM = 'BLOCKED_CLAIM',
  USER_FEEDBACK = 'USER_FEEDBACK',
  OUTPUT_QUALITY_METRIC = 'OUTPUT_QUALITY_METRIC',
  OUTPUT_QUALITY_EVALUATION = 'OUTPUT_QUALITY_EVALUATION',
  OUTPUT_FAILURE = 'OUTPUT_FAILURE',
  AUDIT_EVENT = 'AUDIT_EVENT',
  CURRENT_OUTPUT_AUTHORITY = 'CURRENT_OUTPUT_AUTHORITY',
  CURRENT_FEEDBACK_SUMMARY = 'CURRENT_FEEDBACK_SUMMARY',
  HISTORICAL_AI_OUTPUT_FACT = 'HISTORICAL_AI_OUTPUT_FACT',
}

export const ALL_L13_PERSISTENCE_CLASSES:
  readonly L13PersistenceClass[] =
  Object.values(L13PersistenceClass);

export enum L13PersistenceWriteIntent {
  WRITE_NEW = 'WRITE_NEW',
  UPSERT_CURRENT_AUTHORITY = 'UPSERT_CURRENT_AUTHORITY',
  APPEND_HISTORICAL_FACT = 'APPEND_HISTORICAL_FACT',
  APPEND_AUDIT_EVENT = 'APPEND_AUDIT_EVENT',
  RECOMPUTE_RECOMPUTABLE_CURRENT = 'RECOMPUTE_RECOMPUTABLE_CURRENT',
}

export const ALL_L13_PERSISTENCE_WRITE_INTENTS:
  readonly L13PersistenceWriteIntent[] =
  Object.values(L13PersistenceWriteIntent);
