/**
 * L13.12 — Layer 13 Final Definition Contract
 *
 * §13.12.2 / §13.12.3 / §13.12.5 / §13.12.6 — Canonical sublayer
 * ids, certification levels/bands, and the layer's final-definition
 * shape (used by the ratification artifact).
 */

// L13SublayerId + ALL_L13_SUBLAYER_IDS are owned by L13.1
// (l13-constitutional-types). Re-imported here for use, and
// L13.12 consumers can pick them up from either entry.
import {
  ALL_L13_SUBLAYER_IDS,
  L13SublayerId,
} from './l13-constitutional-types';
export { ALL_L13_SUBLAYER_IDS, L13SublayerId };

export enum L13CertificationLevel {
  INCOMPLETE = 'INCOMPLETE',
  SUBLAYERS_PARTIAL = 'SUBLAYERS_PARTIAL',
  SUBLAYERS_GREEN = 'SUBLAYERS_GREEN',
  PRODUCTION_GREEN = 'PRODUCTION_GREEN',
  FROZEN_LIVE = 'FROZEN_LIVE',
}

export const ALL_L13_CERTIFICATION_LEVELS:
  readonly L13CertificationLevel[] =
  Object.values(L13CertificationLevel);

export enum L13CertificationBand {
  BAND_A_CONSTITUTION_AND_BOUNDARY = 'BAND_A_CONSTITUTION_AND_BOUNDARY',
  BAND_B_AI_INPUT_PACKAGE = 'BAND_B_AI_INPUT_PACKAGE',
  BAND_C_OUTPUT_CONTRACTS = 'BAND_C_OUTPUT_CONTRACTS',
  BAND_D_GROUNDING_NO_INVENTION = 'BAND_D_GROUNDING_NO_INVENTION',
  BAND_E_UNCERTAINTY_RESTRICTIONS = 'BAND_E_UNCERTAINTY_RESTRICTIONS',
  BAND_F_RUNTIME_PROMPT_ORCHESTRATION = 'BAND_F_RUNTIME_PROMPT_ORCHESTRATION',
  BAND_G_USER_OUTPUT_MODES = 'BAND_G_USER_OUTPUT_MODES',
  BAND_H_STYLE_AND_LANGUAGE = 'BAND_H_STYLE_AND_LANGUAGE',
  BAND_I_SAFETY = 'BAND_I_SAFETY',
  BAND_J_PERSISTENCE_AND_FEEDBACK = 'BAND_J_PERSISTENCE_AND_FEEDBACK',
  BAND_K_REPLAY_REPAIR_ADVERSARIAL = 'BAND_K_REPLAY_REPAIR_ADVERSARIAL',
  BAND_L_FINAL_RATIFICATION = 'BAND_L_FINAL_RATIFICATION',
}

export const ALL_L13_CERTIFICATION_BANDS:
  readonly L13CertificationBand[] =
  Object.values(L13CertificationBand);

export const L13_BAND_BY_SUBLAYER:
  Readonly<Record<L13SublayerId, L13CertificationBand>> = {
  [L13SublayerId.L13_1_CONSTITUTION]: L13CertificationBand.BAND_A_CONSTITUTION_AND_BOUNDARY,
  [L13SublayerId.L13_2_INPUT_PACKAGE]: L13CertificationBand.BAND_B_AI_INPUT_PACKAGE,
  [L13SublayerId.L13_3_OUTPUT_CONTRACTS]: L13CertificationBand.BAND_C_OUTPUT_CONTRACTS,
  [L13SublayerId.L13_4_GROUNDING]: L13CertificationBand.BAND_D_GROUNDING_NO_INVENTION,
  [L13SublayerId.L13_5_UNCERTAINTY_RESTRICTIONS]: L13CertificationBand.BAND_E_UNCERTAINTY_RESTRICTIONS,
  [L13SublayerId.L13_6_RUNTIME]: L13CertificationBand.BAND_F_RUNTIME_PROMPT_ORCHESTRATION,
  [L13SublayerId.L13_7_OUTPUT_MODES]: L13CertificationBand.BAND_G_USER_OUTPUT_MODES,
  [L13SublayerId.L13_8_STYLE_LANGUAGE]: L13CertificationBand.BAND_H_STYLE_AND_LANGUAGE,
  [L13SublayerId.L13_9_SAFETY]: L13CertificationBand.BAND_I_SAFETY,
  [L13SublayerId.L13_10_PERSISTENCE_FEEDBACK]: L13CertificationBand.BAND_J_PERSISTENCE_AND_FEEDBACK,
  [L13SublayerId.L13_11_REPLAY_REPAIR_ADVERSARIAL]: L13CertificationBand.BAND_K_REPLAY_REPAIR_ADVERSARIAL,
  [L13SublayerId.L13_12_RATIFICATION]: L13CertificationBand.BAND_L_FINAL_RATIFICATION,
};

export enum L13FinalInvariantId {
  INV_13_A_NO_INVENTED_SUPPORT = 'INV-13-A',
  INV_13_B_NO_HIDDEN_CONTRADICTION = 'INV-13-B',
  INV_13_C_NO_CONFIDENCE_OUTRUN = 'INV-13-C',
  INV_13_D_NO_RESTRICTION_BYPASS = 'INV-13-D',
  INV_13_E_NO_L7_L12_REBUILD = 'INV-13-E',
  INV_13_F_NO_TRADE_RECOMMENDATION = 'INV-13-F',
  INV_13_G_OBSERVATION_INFERENCE_SEPARATION = 'INV-13-G',
  INV_13_H_UNCERTAINTY_DISCLOSED_WHEN_REQUIRED = 'INV-13-H',
  INV_13_I_CLAIMS_GROUNDED_IN_EVIDENCE = 'INV-13-I',
  INV_13_J_SCENARIO_CONDITIONALITY_PRESERVED = 'INV-13-J',
  INV_13_K_REPLAY_REPAIR_AUDITABILITY = 'INV-13-K',
  INV_13_L_USEFUL_CONCISE_GOVERNED_OUTPUT = 'INV-13-L',
}

export const ALL_L13_FINAL_INVARIANT_IDS:
  readonly L13FinalInvariantId[] =
  Object.values(L13FinalInvariantId);

export enum L13FinalCapabilityClass {
  PRODUCE_GROUNDED_EXPLANATIONS = 'PRODUCE_GROUNDED_EXPLANATIONS',
  DISCLOSE_UNCERTAINTY = 'DISCLOSE_UNCERTAINTY',
  DISCLOSE_CONTRADICTIONS = 'DISCLOSE_CONTRADICTIONS',
  REFERENCE_TRIGGERS_AND_INVALIDATIONS = 'REFERENCE_TRIGGERS_AND_INVALIDATIONS',
  PRESERVE_SCENARIO_CONDITIONALITY = 'PRESERVE_SCENARIO_CONDITIONALITY',
  ANSWER_USER_QUESTIONS = 'ANSWER_USER_QUESTIONS',
  WRITE_ALERTS = 'WRITE_ALERTS',
  STRUCTURED_REPORTS = 'STRUCTURED_REPORTS',
  ASSET_AND_THESIS_COMPARISONS = 'ASSET_AND_THESIS_COMPARISONS',
  SCORE_EXPLANATIONS = 'SCORE_EXPLANATIONS',
  REPLAYABLE_OUTPUTS = 'REPLAYABLE_OUTPUTS',
  REPAIR_SAFE_CORRECTIONS = 'REPAIR_SAFE_CORRECTIONS',
  MULTILINGUAL_GOVERNED_OUTPUT = 'MULTILINGUAL_GOVERNED_OUTPUT',
}

export enum L13FinalForbiddenSemanticClass {
  INVENT_TRUTH = 'INVENT_TRUTH',
  REBUILD_LOWER_LAYERS = 'REBUILD_LOWER_LAYERS',
  EMIT_RECOMMENDATIONS = 'EMIT_RECOMMENDATIONS',
  EMIT_GUARANTEES = 'EMIT_GUARANTEES',
  EMIT_MARKET_MANIPULATION = 'EMIT_MARKET_MANIPULATION',
  HIDE_CONTRADICTION = 'HIDE_CONTRADICTION',
  HIDE_UNCERTAINTY = 'HIDE_UNCERTAINTY',
  OUTRUN_CONFIDENCE = 'OUTRUN_CONFIDENCE',
  BYPASS_RESTRICTIONS = 'BYPASS_RESTRICTIONS',
  IMPERSONATE_ENGINE = 'IMPERSONATE_ENGINE',
}

export interface L13FinalDefinition {
  readonly layer_id: 'L13';
  readonly layer_name: 'AI Judgment & Explanation Layer';
  readonly canonical_mission: string;
  readonly canonical_first_principle: string;
  readonly total_sublayers: 12;
  readonly required_sublayer_ids: readonly L13SublayerId[];
  readonly layer_capabilities: readonly L13FinalCapabilityClass[];
  readonly layer_forbidden_semantics:
    readonly L13FinalForbiddenSemanticClass[];
  readonly required_certification_bands:
    readonly L13CertificationBand[];
  readonly completion_standard_ref: string;
  readonly freeze_policy_ref: string;
  readonly policy_version: string;
  readonly replay_hash: string;
}
