/**
 * L13.9 — Market Manipulation Pattern Contract
 *
 * §13.9.13 — Closed set of market-manipulation pattern classes.
 * Distinct from ordinary scenario analysis: scenario explanations
 * may describe fragility, but may never recommend exploiting it.
 */

export enum L13MarketManipulationPatternClass {
  COORDINATED_PRICE_PUSH = 'COORDINATED_PRICE_PUSH',
  LOW_LIQUIDITY_EXPLOITATION = 'LOW_LIQUIDITY_EXPLOITATION',
  ARTIFICIAL_NARRATIVE_ENGINEERING = 'ARTIFICIAL_NARRATIVE_ENGINEERING',
  LIQUIDATION_HUNT_COORDINATION = 'LIQUIDATION_HUNT_COORDINATION',
  DECEPTIVE_PARTICIPATION_SIGNALING = 'DECEPTIVE_PARTICIPATION_SIGNALING',
}

export const ALL_L13_MARKET_MANIPULATION_PATTERN_CLASSES:
  readonly L13MarketManipulationPatternClass[] =
  Object.values(L13MarketManipulationPatternClass);

/**
 * §13.9.7 — Forbidden financial language family taxonomy.
 */
export enum L13ForbiddenFinancialLanguageFamily {
  DIRECT_BUY = 'DIRECT_BUY',
  DIRECT_SELL = 'DIRECT_SELL',
  DIRECT_HOLD = 'DIRECT_HOLD',
  DIRECT_AVOID = 'DIRECT_AVOID',
  LONG_SHORT_INSTRUCTION = 'LONG_SHORT_INSTRUCTION',
  ENTRY_EXIT_INSTRUCTION = 'ENTRY_EXIT_INSTRUCTION',
  LEVERAGE_RECOMMENDATION = 'LEVERAGE_RECOMMENDATION',
  POSITION_SIZING_RECOMMENDATION = 'POSITION_SIZING_RECOMMENDATION',
  STOP_LOSS_TAKE_PROFIT_INSTRUCTION = 'STOP_LOSS_TAKE_PROFIT_INSTRUCTION',
  LIQUIDATION_TARGETING = 'LIQUIDATION_TARGETING',
  GUARANTEE_OUTCOME = 'GUARANTEE_OUTCOME',
  PUMP_DUMP_PROPHECY = 'PUMP_DUMP_PROPHECY',
  CERTAIN_DIRECTIONAL_OUTCOME = 'CERTAIN_DIRECTIONAL_OUTCOME',
  TAX_LEGAL_ADVICE = 'TAX_LEGAL_ADVICE',
  MARKET_MANIPULATION_ASSISTANCE = 'MARKET_MANIPULATION_ASSISTANCE',
}

export const ALL_L13_FORBIDDEN_FINANCIAL_LANGUAGE_FAMILIES:
  readonly L13ForbiddenFinancialLanguageFamily[] =
  Object.values(L13ForbiddenFinancialLanguageFamily);

/**
 * §13.9.8 — Advice-adjacent language family taxonomy.
 */
export enum L13AdviceAdjacentLanguageFamily {
  IMPLIED_ENTRY_BIAS = 'IMPLIED_ENTRY_BIAS',
  IMPLIED_EXIT_BIAS = 'IMPLIED_EXIT_BIAS',
  BEST_SETUP_FRAMING = 'BEST_SETUP_FRAMING',
  BEST_ENTRY_FRAMING = 'BEST_ENTRY_FRAMING',
  ACTIONABLE_SOUNDING_OPPORTUNITY = 'ACTIONABLE_SOUNDING_OPPORTUNITY',
  IMPLIED_ASSET_PREFERENCE = 'IMPLIED_ASSET_PREFERENCE',
  IMPLIED_EXECUTION_TIMING = 'IMPLIED_EXECUTION_TIMING',
}

export const ALL_L13_ADVICE_ADJACENT_LANGUAGE_FAMILIES:
  readonly L13AdviceAdjacentLanguageFamily[] =
  Object.values(L13AdviceAdjacentLanguageFamily);

/**
 * §13.9.11 — Safety match-context classes. Mirrors the L13.8
 * multilingual safety context taxonomy.
 */
export enum L13SafetyMatchContextClass {
  USER_VISIBLE_ASSERTION = 'USER_VISIBLE_ASSERTION',
  LEGAL_REWRITE_EXAMPLE = 'LEGAL_REWRITE_EXAMPLE',
  REFUSAL_EXPLANATION = 'REFUSAL_EXPLANATION',
  BLOCKED_CLAIM_RECORD = 'BLOCKED_CLAIM_RECORD',
  INTERNAL_DEBUG = 'INTERNAL_DEBUG',
}

export const ALL_L13_SAFETY_MATCH_CONTEXT_CLASSES:
  readonly L13SafetyMatchContextClass[] =
  Object.values(L13SafetyMatchContextClass);

/**
 * §13.9.10 — Block level on individual safety phrase hits.
 */
export enum L13SafetyBlockLevel {
  NONE = 'NONE',
  REWRITE = 'REWRITE',
  REFUSAL = 'REFUSAL',
  HARD_BLOCK = 'HARD_BLOCK',
}

export const ALL_L13_SAFETY_BLOCK_LEVELS:
  readonly L13SafetyBlockLevel[] =
  Object.values(L13SafetyBlockLevel);

/**
 * §13.9.6 — Supported safety language scopes. Mirrors L13.8's
 * supported language taxonomy.
 */
export enum L13SafetyLanguageScope {
  ENGLISH = 'ENGLISH',
  GERMAN = 'GERMAN',
  SPANISH = 'SPANISH',
}

export const ALL_L13_SAFETY_LANGUAGE_SCOPES:
  readonly L13SafetyLanguageScope[] =
  Object.values(L13SafetyLanguageScope);

/**
 * §13.9.6 — Allowed / blocked output-class enums.
 */
export enum L13SafetyAllowedOutputClass {
  INFORMATIONAL_ANALYSIS = 'INFORMATIONAL_ANALYSIS',
  CONDITIONAL_SCENARIO = 'CONDITIONAL_SCENARIO',
  EVIDENCE_BASED_EXPLANATION = 'EVIDENCE_BASED_EXPLANATION',
  RISK_DISCLOSURE = 'RISK_DISCLOSURE',
  WHAT_TO_WATCH_TRIGGER = 'WHAT_TO_WATCH_TRIGGER',
  EDUCATIONAL_FRAMING = 'EDUCATIONAL_FRAMING',
  NEUTRAL_COMPARISON = 'NEUTRAL_COMPARISON',
  ALERT_STATE_CHANGE = 'ALERT_STATE_CHANGE',
  STRUCTURED_REPORT_SUMMARY = 'STRUCTURED_REPORT_SUMMARY',
}

export enum L13SafetyBlockedOutputClass {
  PERSONALIZED_FINANCIAL_ADVICE = 'PERSONALIZED_FINANCIAL_ADVICE',
  TRADE_INSTRUCTION = 'TRADE_INSTRUCTION',
  LEVERAGE_INSTRUCTION = 'LEVERAGE_INSTRUCTION',
  POSITION_SIZING_INSTRUCTION = 'POSITION_SIZING_INSTRUCTION',
  STOP_LOSS_TAKE_PROFIT_INSTRUCTION = 'STOP_LOSS_TAKE_PROFIT_INSTRUCTION',
  LIQUIDATION_TARGETING = 'LIQUIDATION_TARGETING',
  GUARANTEED_OUTCOME = 'GUARANTEED_OUTCOME',
  PUMP_DUMP_PROPHECY = 'PUMP_DUMP_PROPHECY',
  TAX_ADVICE = 'TAX_ADVICE',
  LEGAL_ADVICE = 'LEGAL_ADVICE',
  MARKET_MANIPULATION_ASSISTANCE = 'MARKET_MANIPULATION_ASSISTANCE',
}

/**
 * §13.9.14 — Recommendation reason codes. The non-recommendation
 * engine records each reason it flagged.
 */
export enum L13RecommendationReasonCode {
  ACTION_VERB_DETECTED = 'ACTION_VERB_DETECTED',
  YOU_SHOULD_PATTERN = 'YOU_SHOULD_PATTERN',
  BEST_ENTRY_FRAMING = 'BEST_ENTRY_FRAMING',
  ENTRY_EXIT_TIMING_PATTERN = 'ENTRY_EXIT_TIMING_PATTERN',
  LEVERAGE_NUMERIC_PATTERN = 'LEVERAGE_NUMERIC_PATTERN',
  POSITION_PERCENT_PATTERN = 'POSITION_PERCENT_PATTERN',
  STOP_LOSS_PATTERN = 'STOP_LOSS_PATTERN',
  TAKE_PROFIT_PATTERN = 'TAKE_PROFIT_PATTERN',
  GUARANTEE_PATTERN = 'GUARANTEE_PATTERN',
  CERTAINTY_TO_ACTION_LINK = 'CERTAINTY_TO_ACTION_LINK',
  COMPARISON_AS_RECOMMENDATION = 'COMPARISON_AS_RECOMMENDATION',
}

export const ALL_L13_RECOMMENDATION_REASON_CODES:
  readonly L13RecommendationReasonCode[] =
  Object.values(L13RecommendationReasonCode);
