/**
 * L13.9 — Safety Reason Code Contract
 *
 * §13.9.4 / §13.9.7 / §13.9.8 / §13.9.13 — Reason codes the
 * classifier and the final gate emit. Distinct from the
 * `L13SafetyViolationCode` (`L13Y_*`) namespace which is audit-
 * facing; reason codes are user-flow facing.
 */

export enum L13SafetyReasonCode {
  REASON_SAFE_INFORMATIONAL = 'REASON_SAFE_INFORMATIONAL',
  REASON_ADVICE_ADJACENT_REWRITEABLE = 'REASON_ADVICE_ADJACENT_REWRITEABLE',
  REASON_DIRECT_BUY_SELL_INSTRUCTION = 'REASON_DIRECT_BUY_SELL_INSTRUCTION',
  REASON_DIRECT_HOLD_AVOID_INSTRUCTION = 'REASON_DIRECT_HOLD_AVOID_INSTRUCTION',
  REASON_LONG_SHORT_INSTRUCTION = 'REASON_LONG_SHORT_INSTRUCTION',
  REASON_ENTRY_EXIT_INSTRUCTION = 'REASON_ENTRY_EXIT_INSTRUCTION',
  REASON_LEVERAGE_RECOMMENDATION = 'REASON_LEVERAGE_RECOMMENDATION',
  REASON_POSITION_SIZING_INSTRUCTION = 'REASON_POSITION_SIZING_INSTRUCTION',
  REASON_STOP_LOSS_TAKE_PROFIT_INSTRUCTION = 'REASON_STOP_LOSS_TAKE_PROFIT_INSTRUCTION',
  REASON_LIQUIDATION_TARGET_ADVICE = 'REASON_LIQUIDATION_TARGET_ADVICE',
  REASON_GUARANTEED_OUTCOME = 'REASON_GUARANTEED_OUTCOME',
  REASON_PUMP_DUMP_PROPHECY = 'REASON_PUMP_DUMP_PROPHECY',
  REASON_UNSUPPORTED_CERTAINTY = 'REASON_UNSUPPORTED_CERTAINTY',
  REASON_TAX_ADVICE = 'REASON_TAX_ADVICE',
  REASON_LEGAL_ADVICE = 'REASON_LEGAL_ADVICE',
  REASON_MARKET_MANIPULATION_COORDINATED_PUSH = 'REASON_MARKET_MANIPULATION_COORDINATED_PUSH',
  REASON_MARKET_MANIPULATION_LOW_LIQUIDITY = 'REASON_MARKET_MANIPULATION_LOW_LIQUIDITY',
  REASON_MARKET_MANIPULATION_NARRATIVE_ENGINEERING = 'REASON_MARKET_MANIPULATION_NARRATIVE_ENGINEERING',
  REASON_MARKET_MANIPULATION_LIQUIDATION_HUNT = 'REASON_MARKET_MANIPULATION_LIQUIDATION_HUNT',
  REASON_MARKET_MANIPULATION_DECEPTIVE_SIGNALING = 'REASON_MARKET_MANIPULATION_DECEPTIVE_SIGNALING',
  REASON_OUT_OF_SCOPE_REQUEST = 'REASON_OUT_OF_SCOPE_REQUEST',
  REASON_REWRITE_AVAILABLE = 'REASON_REWRITE_AVAILABLE',
  REASON_REWRITE_NOT_SAFE = 'REASON_REWRITE_NOT_SAFE',
  REASON_GROUNDING_OVERRIDE_ATTEMPTED = 'REASON_GROUNDING_OVERRIDE_ATTEMPTED',
  REASON_SAFETY_OVERRIDE_ATTEMPTED = 'REASON_SAFETY_OVERRIDE_ATTEMPTED',
}

export const ALL_L13_SAFETY_REASON_CODES:
  readonly L13SafetyReasonCode[] =
  Object.values(L13SafetyReasonCode);
