/**
 * L5.4 Universal Write Contract — Error Codes
 */

export enum L5EnvelopeErrorCode {
  MISSING_REQUIRED_FIELD = 'L5_ENVELOPE_MISSING_REQUIRED_FIELD',
  INVALID_TYPE = 'L5_ENVELOPE_INVALID_TYPE',
  INVALID_TIMESTAMP_ORDER = 'L5_ENVELOPE_INVALID_TIMESTAMP_ORDER',
  MISSING_SCHEMA_VERSION = 'L5_ENVELOPE_MISSING_SCHEMA_VERSION',
  MISSING_DEDUPE_KEY = 'L5_ENVELOPE_MISSING_DEDUPE_KEY',
  MISSING_PAYLOAD_HASH = 'L5_ENVELOPE_MISSING_PAYLOAD_HASH',
  MISSING_CANONICAL_REFERENCE = 'L5_ENVELOPE_MISSING_CANONICAL_REFERENCE',
  MISSING_METRIC_CONTRACT = 'L5_ENVELOPE_MISSING_METRIC_CONTRACT',
  UNREGISTERED_PRODUCER = 'L5_ENVELOPE_UNREGISTERED_PRODUCER',
  ILLEGAL_PRODUCER_LAYER = 'L5_ENVELOPE_ILLEGAL_PRODUCER_LAYER',
  ILLEGAL_DERIVATION = 'L5_ENVELOPE_ILLEGAL_DERIVATION',
  DUPLICATE_CONFLICT = 'L5_ENVELOPE_DUPLICATE_CONFLICT',
  PAYLOAD_PROJECTION_MISMATCH = 'L5_ENVELOPE_PAYLOAD_PROJECTION_MISMATCH',
  ARCHIVE_PROOF_REQUIRED = 'L5_ENVELOPE_ARCHIVE_PROOF_REQUIRED',
  ARCHIVE_CHECKSUM_MISMATCH = 'L5_ENVELOPE_ARCHIVE_CHECKSUM_MISMATCH',
  REPLAY_MINIMUM_UNSATISFIED = 'L5_ENVELOPE_REPLAY_MINIMUM_UNSATISFIED',
  TOPOLOGY_INCOMPATIBLE = 'L5_ENVELOPE_TOPOLOGY_INCOMPATIBLE',
  RESOLUTION_REQUIRED_BUT_UNRESOLVED = 'L5_ENVELOPE_RESOLUTION_REQUIRED_BUT_UNRESOLVED',
  ILLEGAL_LIFECYCLE_TRANSITION = 'L5_ENVELOPE_ILLEGAL_LIFECYCLE_TRANSITION',
  PAYLOAD_TOO_LARGE = 'L5_ENVELOPE_PAYLOAD_TOO_LARGE',
}

export class L5EnvelopeError extends Error {
  public readonly code: L5EnvelopeErrorCode;
  public readonly details: Record<string, unknown>;

  constructor(code: L5EnvelopeErrorCode, message: string, details: Record<string, unknown> = {}) {
    super(`[${code}] ${message}`);
    this.name = 'L5EnvelopeError';
    this.code = code;
    this.details = details;
  }
}
