/**
 * L11.2 — Score Doctrine Violation Codes (§11.2.16.1)
 *
 * Disjoint `L11D_` namespace so doctrine violations never collide with
 * L11.1 constitutional violation codes. Every code maps to a severity
 * used by the doctrine audit emitter.
 */

export enum L11ScoreDoctrineViolationCode {
  // ── Family-catalogue violations ──
  L11D_FAMILY_UNREGISTERED = 'L11D_FAMILY_UNREGISTERED',
  L11D_FAMILY_DUPLICATE = 'L11D_FAMILY_DUPLICATE',
  L11D_PRODUCTION_FAMILY_INCOMPLETE = 'L11D_PRODUCTION_FAMILY_INCOMPLETE',
  L11D_RESERVED_FAMILY_MISCONFIGURED = 'L11D_RESERVED_FAMILY_MISCONFIGURED',
  L11D_FAMILY_DEPENDENCY_MISSING = 'L11D_FAMILY_DEPENDENCY_MISSING',
  L11D_FAMILY_OUTPUT_SURFACE_MISSING = 'L11D_FAMILY_OUTPUT_SURFACE_MISSING',
  L11D_FAMILY_DISCLOSURE_MISSING = 'L11D_FAMILY_DISCLOSURE_MISSING',

  // ── Meaning-claim violations ──
  L11D_MEANING_CLAIM_MISSING = 'L11D_MEANING_CLAIM_MISSING',
  L11D_MEANING_CLAIM_INCOMPLETE = 'L11D_MEANING_CLAIM_INCOMPLETE',
  L11D_MEANING_CLAIM_DUPLICATE = 'L11D_MEANING_CLAIM_DUPLICATE',
  L11D_MEANING_CLAIM_ID_MISSING = 'L11D_MEANING_CLAIM_ID_MISSING',
  L11D_MEANING_CLAIM_HIGH_LOW_MISSING = 'L11D_MEANING_CLAIM_HIGH_LOW_MISSING',
  L11D_MEANING_CLAIM_FORBIDDEN_USES_INCOMPLETE = 'L11D_MEANING_CLAIM_FORBIDDEN_USES_INCOMPLETE',

  // ── Direction violations ──
  L11D_DIRECTION_MISSING = 'L11D_DIRECTION_MISSING',
  L11D_DIRECTION_MIXED = 'L11D_DIRECTION_MIXED',
  L11D_DIRECTION_MISMATCH = 'L11D_DIRECTION_MISMATCH',

  // ── Production-status violations ──
  L11D_RESERVED_FAMILY_EMITTED = 'L11D_RESERVED_FAMILY_EMITTED',
  L11D_DEPRECATED_FAMILY_EMITTED = 'L11D_DEPRECATED_FAMILY_EMITTED',
  L11D_EXPERIMENTAL_FAMILY_EMITTED = 'L11D_EXPERIMENTAL_FAMILY_EMITTED',
  L11D_PRODUCTION_STATUS_MISSING = 'L11D_PRODUCTION_STATUS_MISSING',

  // ── Numeric & band violations ──
  L11D_RAW_SCORE_OUT_OF_RANGE = 'L11D_RAW_SCORE_OUT_OF_RANGE',
  L11D_MODIFIED_SCORE_OUT_OF_RANGE = 'L11D_MODIFIED_SCORE_OUT_OF_RANGE',
  L11D_FINAL_SCORE_OUT_OF_RANGE = 'L11D_FINAL_SCORE_OUT_OF_RANGE',
  L11D_SCORE_VALUE_NOT_FINITE = 'L11D_SCORE_VALUE_NOT_FINITE',
  L11D_SCORE_BAND_MISMATCH = 'L11D_SCORE_BAND_MISMATCH',
  L11D_SCORE_BAND_POLICY_MISSING = 'L11D_SCORE_BAND_POLICY_MISSING',
  L11D_BAND_THRESHOLD_GAP_OR_OVERLAP = 'L11D_BAND_THRESHOLD_GAP_OR_OVERLAP',

  // ── Score object contract violations ──
  L11D_SCORE_IDENTITY_MISSING = 'L11D_SCORE_IDENTITY_MISSING',
  L11D_SCORE_SCOPE_MISSING = 'L11D_SCORE_SCOPE_MISSING',
  L11D_SCORE_VERSION_MISSING = 'L11D_SCORE_VERSION_MISSING',
  L11D_SCORE_AS_OF_MISSING = 'L11D_SCORE_AS_OF_MISSING',
  L11D_TRANSFORMATION_INCONSISTENT = 'L11D_TRANSFORMATION_INCONSISTENT',
  L11D_ATTRIBUTION_MISSING = 'L11D_ATTRIBUTION_MISSING',
  L11D_MISSING_DATA_PROFILE_MISSING = 'L11D_MISSING_DATA_PROFILE_MISSING',
  L11D_REGIME_MODIFIER_MISSING = 'L11D_REGIME_MODIFIER_MISSING',
  L11D_SEQUENCE_MODIFIER_MISSING = 'L11D_SEQUENCE_MODIFIER_MISSING',
  L11D_HYPOTHESIS_MODIFIER_MISSING = 'L11D_HYPOTHESIS_MODIFIER_MISSING',
  L11D_CALIBRATION_TARGET_MISSING = 'L11D_CALIBRATION_TARGET_MISSING',
  L11D_RESTRICTION_PROFILE_MISSING = 'L11D_RESTRICTION_PROFILE_MISSING',
  L11D_EVIDENCE_PACK_MISSING = 'L11D_EVIDENCE_PACK_MISSING',
  L11D_INPUT_SNAPSHOT_MISSING = 'L11D_INPUT_SNAPSHOT_MISSING',
  L11D_COMPUTE_RUN_MISSING = 'L11D_COMPUTE_RUN_MISSING',
  L11D_REQUIRED_DISCLOSURE_MISSING = 'L11D_REQUIRED_DISCLOSURE_MISSING',
  L11D_POLICY_VERSION_MISSING = 'L11D_POLICY_VERSION_MISSING',

  // ── Replay law violations ──
  L11D_REPLAY_HASH_MISSING = 'L11D_REPLAY_HASH_MISSING',
  L11D_REPLAY_HASH_MISMATCH = 'L11D_REPLAY_HASH_MISMATCH',
  L11D_REPLAY_HASH_NOT_DETERMINISTIC = 'L11D_REPLAY_HASH_NOT_DETERMINISTIC',

  // ── Interpretation / semantic-leak violations ──
  L11D_SCORE_ACTS_AS_RECOMMENDATION = 'L11D_SCORE_ACTS_AS_RECOMMENDATION',
  L11D_SCORE_ACTS_AS_JUDGMENT = 'L11D_SCORE_ACTS_AS_JUDGMENT',
  L11D_SCORE_ACTS_AS_SCENARIO_WINNER = 'L11D_SCORE_ACTS_AS_SCENARIO_WINNER',
  L11D_SCORE_ACTS_AS_TRADE_ACTION = 'L11D_SCORE_ACTS_AS_TRADE_ACTION',
  L11D_SCORE_ACTS_AS_CERTAINTY = 'L11D_SCORE_ACTS_AS_CERTAINTY',
  L11D_FAMILY_INTERPRETATION_LEAK = 'L11D_FAMILY_INTERPRETATION_LEAK',

  // ── Object readiness violations ──
  L11D_OBJECT_NOT_READY = 'L11D_OBJECT_NOT_READY',
}

export const ALL_L11_SCORE_DOCTRINE_VIOLATION_CODES:
  readonly L11ScoreDoctrineViolationCode[] =
  Object.values(L11ScoreDoctrineViolationCode);

export type L11ScoreDoctrineSeverity =
  | 'INFO'
  | 'WARNING'
  | 'ERROR'
  | 'CRITICAL';

const SEVERITY_MAP: Readonly<Record<L11ScoreDoctrineViolationCode, L11ScoreDoctrineSeverity>> = {
  // Critical violations — block emission entirely.
  [L11ScoreDoctrineViolationCode.L11D_RESERVED_FAMILY_EMITTED]: 'CRITICAL',
  [L11ScoreDoctrineViolationCode.L11D_DEPRECATED_FAMILY_EMITTED]: 'CRITICAL',
  [L11ScoreDoctrineViolationCode.L11D_EXPERIMENTAL_FAMILY_EMITTED]: 'CRITICAL',
  [L11ScoreDoctrineViolationCode.L11D_SCORE_ACTS_AS_RECOMMENDATION]: 'CRITICAL',
  [L11ScoreDoctrineViolationCode.L11D_SCORE_ACTS_AS_JUDGMENT]: 'CRITICAL',
  [L11ScoreDoctrineViolationCode.L11D_SCORE_ACTS_AS_SCENARIO_WINNER]: 'CRITICAL',
  [L11ScoreDoctrineViolationCode.L11D_SCORE_ACTS_AS_TRADE_ACTION]: 'CRITICAL',
  [L11ScoreDoctrineViolationCode.L11D_SCORE_ACTS_AS_CERTAINTY]: 'CRITICAL',
  [L11ScoreDoctrineViolationCode.L11D_FAMILY_INTERPRETATION_LEAK]: 'CRITICAL',
  [L11ScoreDoctrineViolationCode.L11D_MEANING_CLAIM_MISSING]: 'CRITICAL',
  [L11ScoreDoctrineViolationCode.L11D_DIRECTION_MISSING]: 'CRITICAL',
  [L11ScoreDoctrineViolationCode.L11D_DIRECTION_MIXED]: 'CRITICAL',
  [L11ScoreDoctrineViolationCode.L11D_DIRECTION_MISMATCH]: 'CRITICAL',
  [L11ScoreDoctrineViolationCode.L11D_RAW_SCORE_OUT_OF_RANGE]: 'CRITICAL',
  [L11ScoreDoctrineViolationCode.L11D_MODIFIED_SCORE_OUT_OF_RANGE]: 'CRITICAL',
  [L11ScoreDoctrineViolationCode.L11D_FINAL_SCORE_OUT_OF_RANGE]: 'CRITICAL',
  [L11ScoreDoctrineViolationCode.L11D_SCORE_VALUE_NOT_FINITE]: 'CRITICAL',
  [L11ScoreDoctrineViolationCode.L11D_REPLAY_HASH_MISSING]: 'CRITICAL',
  [L11ScoreDoctrineViolationCode.L11D_REPLAY_HASH_MISMATCH]: 'CRITICAL',
  [L11ScoreDoctrineViolationCode.L11D_REPLAY_HASH_NOT_DETERMINISTIC]: 'CRITICAL',
  [L11ScoreDoctrineViolationCode.L11D_ATTRIBUTION_MISSING]: 'CRITICAL',
  [L11ScoreDoctrineViolationCode.L11D_MISSING_DATA_PROFILE_MISSING]: 'CRITICAL',
  [L11ScoreDoctrineViolationCode.L11D_CALIBRATION_TARGET_MISSING]: 'CRITICAL',
  [L11ScoreDoctrineViolationCode.L11D_RESTRICTION_PROFILE_MISSING]: 'CRITICAL',
  [L11ScoreDoctrineViolationCode.L11D_EVIDENCE_PACK_MISSING]: 'CRITICAL',
  [L11ScoreDoctrineViolationCode.L11D_INPUT_SNAPSHOT_MISSING]: 'CRITICAL',
  [L11ScoreDoctrineViolationCode.L11D_REQUIRED_DISCLOSURE_MISSING]: 'CRITICAL',
  [L11ScoreDoctrineViolationCode.L11D_OBJECT_NOT_READY]: 'CRITICAL',

  // Errors — illegal state but recoverable in tests.
  [L11ScoreDoctrineViolationCode.L11D_FAMILY_UNREGISTERED]: 'ERROR',
  [L11ScoreDoctrineViolationCode.L11D_FAMILY_DUPLICATE]: 'ERROR',
  [L11ScoreDoctrineViolationCode.L11D_PRODUCTION_FAMILY_INCOMPLETE]: 'ERROR',
  [L11ScoreDoctrineViolationCode.L11D_RESERVED_FAMILY_MISCONFIGURED]: 'ERROR',
  [L11ScoreDoctrineViolationCode.L11D_FAMILY_DEPENDENCY_MISSING]: 'ERROR',
  [L11ScoreDoctrineViolationCode.L11D_FAMILY_OUTPUT_SURFACE_MISSING]: 'ERROR',
  [L11ScoreDoctrineViolationCode.L11D_FAMILY_DISCLOSURE_MISSING]: 'ERROR',
  [L11ScoreDoctrineViolationCode.L11D_MEANING_CLAIM_INCOMPLETE]: 'ERROR',
  [L11ScoreDoctrineViolationCode.L11D_MEANING_CLAIM_DUPLICATE]: 'ERROR',
  [L11ScoreDoctrineViolationCode.L11D_MEANING_CLAIM_ID_MISSING]: 'ERROR',
  [L11ScoreDoctrineViolationCode.L11D_MEANING_CLAIM_HIGH_LOW_MISSING]: 'ERROR',
  [L11ScoreDoctrineViolationCode.L11D_MEANING_CLAIM_FORBIDDEN_USES_INCOMPLETE]: 'ERROR',
  [L11ScoreDoctrineViolationCode.L11D_PRODUCTION_STATUS_MISSING]: 'ERROR',
  [L11ScoreDoctrineViolationCode.L11D_SCORE_BAND_MISMATCH]: 'ERROR',
  [L11ScoreDoctrineViolationCode.L11D_SCORE_BAND_POLICY_MISSING]: 'ERROR',
  [L11ScoreDoctrineViolationCode.L11D_BAND_THRESHOLD_GAP_OR_OVERLAP]: 'ERROR',
  [L11ScoreDoctrineViolationCode.L11D_SCORE_IDENTITY_MISSING]: 'ERROR',
  [L11ScoreDoctrineViolationCode.L11D_SCORE_SCOPE_MISSING]: 'ERROR',
  [L11ScoreDoctrineViolationCode.L11D_SCORE_VERSION_MISSING]: 'ERROR',
  [L11ScoreDoctrineViolationCode.L11D_SCORE_AS_OF_MISSING]: 'ERROR',
  [L11ScoreDoctrineViolationCode.L11D_TRANSFORMATION_INCONSISTENT]: 'ERROR',
  [L11ScoreDoctrineViolationCode.L11D_REGIME_MODIFIER_MISSING]: 'ERROR',
  [L11ScoreDoctrineViolationCode.L11D_SEQUENCE_MODIFIER_MISSING]: 'ERROR',
  [L11ScoreDoctrineViolationCode.L11D_HYPOTHESIS_MODIFIER_MISSING]: 'ERROR',
  [L11ScoreDoctrineViolationCode.L11D_COMPUTE_RUN_MISSING]: 'ERROR',
  [L11ScoreDoctrineViolationCode.L11D_POLICY_VERSION_MISSING]: 'ERROR',
};

export function severityForL11DoctrineCode(
  code: L11ScoreDoctrineViolationCode,
): L11ScoreDoctrineSeverity {
  return SEVERITY_MAP[code] ?? 'WARNING';
}

export interface L11ScoreDoctrineIssue {
  readonly code: L11ScoreDoctrineViolationCode;
  readonly severity: L11ScoreDoctrineSeverity;
  readonly message: string;
  readonly subject_ref?: string;
  readonly score_family?: string;
  readonly meaning_claim_id?: string;
  readonly band_policy_id?: string;
}

export function makeL11ScoreDoctrineIssue(
  code: L11ScoreDoctrineViolationCode,
  message: string,
  ctx: Partial<Omit<L11ScoreDoctrineIssue, 'code' | 'severity' | 'message'>> = {},
): L11ScoreDoctrineIssue {
  return {
    code,
    severity: severityForL11DoctrineCode(code),
    message,
    ...ctx,
  };
}
