/**
 * L11.4 — Score Attribution Violation Codes (§11.4.15.1)
 *
 * Disjoint `L11A_` namespace so attribution violations never collide
 * with L11.1 constitutional codes, L11.2 doctrine codes, or L11.3
 * formula codes.
 */

export enum L11ScoreAttributionViolationCode {
  // ── Attribution identity ──
  L11A_ATTRIBUTION_ID_MISSING = 'L11A_ATTRIBUTION_ID_MISSING',
  L11A_SCORE_REF_MISSING = 'L11A_SCORE_REF_MISSING',
  L11A_FORMULA_REF_MISSING = 'L11A_FORMULA_REF_MISSING',
  L11A_FORMULA_VERSION_MISSING = 'L11A_FORMULA_VERSION_MISSING',
  L11A_FORMULA_EVALUATION_REF_MISSING = 'L11A_FORMULA_EVALUATION_REF_MISSING',
  L11A_INPUT_SNAPSHOT_REF_MISSING = 'L11A_INPUT_SNAPSHOT_REF_MISSING',
  L11A_SCOPE_FIELDS_MISSING = 'L11A_SCOPE_FIELDS_MISSING',
  L11A_AS_OF_MISSING = 'L11A_AS_OF_MISSING',
  L11A_POLICY_VERSION_MISSING = 'L11A_POLICY_VERSION_MISSING',

  // ── Component contribution law ──
  L11A_COMPONENT_CONTRIBUTION_MISSING = 'L11A_COMPONENT_CONTRIBUTION_MISSING',
  L11A_COMPONENT_CONTRIBUTION_INVALID = 'L11A_COMPONENT_CONTRIBUTION_INVALID',
  L11A_COMPONENT_CONTRIBUTION_OUT_OF_BOUNDS = 'L11A_COMPONENT_CONTRIBUTION_OUT_OF_BOUNDS',
  L11A_COMPONENT_DIRECTION_MISMATCH = 'L11A_COMPONENT_DIRECTION_MISMATCH',
  L11A_MATERIAL_COMPONENT_LACKS_EVIDENCE = 'L11A_MATERIAL_COMPONENT_LACKS_EVIDENCE',

  // ── Cap / penalty / modifier / missing-data attribution law ──
  L11A_CAP_APPLIED_BUT_NOT_ATTRIBUTED = 'L11A_CAP_APPLIED_BUT_NOT_ATTRIBUTED',
  L11A_CAP_CONTRIBUTION_INVALID = 'L11A_CAP_CONTRIBUTION_INVALID',
  L11A_PENALTY_APPLIED_BUT_NOT_ATTRIBUTED = 'L11A_PENALTY_APPLIED_BUT_NOT_ATTRIBUTED',
  L11A_PENALTY_CONTRIBUTION_INVALID = 'L11A_PENALTY_CONTRIBUTION_INVALID',
  L11A_PENALTY_DIRECTION_INCONSISTENT = 'L11A_PENALTY_DIRECTION_INCONSISTENT',
  L11A_MODIFIER_APPLIED_BUT_NOT_ATTRIBUTED = 'L11A_MODIFIER_APPLIED_BUT_NOT_ATTRIBUTED',
  L11A_MODIFIER_CONTRIBUTION_INVALID = 'L11A_MODIFIER_CONTRIBUTION_INVALID',
  L11A_MODIFIER_SOURCE_LAYER_MISSING = 'L11A_MODIFIER_SOURCE_LAYER_MISSING',
  L11A_MISSING_DATA_EFFECT_NOT_ATTRIBUTED = 'L11A_MISSING_DATA_EFFECT_NOT_ATTRIBUTED',
  L11A_MISSING_DATA_CONTRIBUTION_INVALID = 'L11A_MISSING_DATA_CONTRIBUTION_INVALID',

  // ── Driver visibility law ──
  L11A_MATERIAL_DRIVER_HIDDEN = 'L11A_MATERIAL_DRIVER_HIDDEN',
  L11A_MATERIAL_CAP_HIDDEN = 'L11A_MATERIAL_CAP_HIDDEN',
  L11A_MATERIAL_MISSING_DATA_HIDDEN = 'L11A_MATERIAL_MISSING_DATA_HIDDEN',
  L11A_TOP_DRIVER_SELECTION_NONDETERMINISTIC = 'L11A_TOP_DRIVER_SELECTION_NONDETERMINISTIC',
  L11A_TOP_DRIVER_POLICY_INVALID = 'L11A_TOP_DRIVER_POLICY_INVALID',
  L11A_TOP_DRIVER_REF_UNKNOWN = 'L11A_TOP_DRIVER_REF_UNKNOWN',

  // ── Summary code law ──
  L11A_SUMMARY_CODE_UNSUPPORTED = 'L11A_SUMMARY_CODE_UNSUPPORTED',
  L11A_SUMMARY_CODE_INVALID = 'L11A_SUMMARY_CODE_INVALID',

  // ── Completeness law ──
  L11A_COMPLETENESS_CLASS_MISSING = 'L11A_COMPLETENESS_CLASS_MISSING',
  L11A_COMPLETENESS_BLOCKED_EMITTED = 'L11A_COMPLETENESS_BLOCKED_EMITTED',

  // ── Governed-input law ──
  L11A_UNGOVERNED_INPUT_REF = 'L11A_UNGOVERNED_INPUT_REF',
  L11A_EVIDENCE_REFS_MISSING = 'L11A_EVIDENCE_REFS_MISSING',
  L11A_LINEAGE_REFS_MISSING = 'L11A_LINEAGE_REFS_MISSING',

  // ── Replay law ──
  L11A_REPLAY_HASH_MISSING = 'L11A_REPLAY_HASH_MISSING',
  L11A_REPLAY_HASH_MISMATCH = 'L11A_REPLAY_HASH_MISMATCH',
  L11A_REPLAY_HASH_NOT_DETERMINISTIC = 'L11A_REPLAY_HASH_NOT_DETERMINISTIC',

  // ── Semantic-leak law ──
  L11A_ATTRIBUTION_ACTS_AS_RECOMMENDATION = 'L11A_ATTRIBUTION_ACTS_AS_RECOMMENDATION',
  L11A_ATTRIBUTION_ACTS_AS_JUDGMENT = 'L11A_ATTRIBUTION_ACTS_AS_JUDGMENT',
  L11A_ATTRIBUTION_ACTS_AS_SCENARIO_WINNER = 'L11A_ATTRIBUTION_ACTS_AS_SCENARIO_WINNER',
  L11A_ATTRIBUTION_ACTS_AS_TRADE_ACTION = 'L11A_ATTRIBUTION_ACTS_AS_TRADE_ACTION',
}

export const ALL_L11_SCORE_ATTRIBUTION_VIOLATION_CODES:
  readonly L11ScoreAttributionViolationCode[] =
  Object.values(L11ScoreAttributionViolationCode);

export type L11ScoreAttributionSeverity =
  | 'INFO' | 'WARNING' | 'ERROR' | 'CRITICAL';

const SEVERITY_MAP:
  Readonly<Record<L11ScoreAttributionViolationCode, L11ScoreAttributionSeverity>> = {
  // CRITICAL — blocks emission entirely
  [L11ScoreAttributionViolationCode.L11A_CAP_APPLIED_BUT_NOT_ATTRIBUTED]: 'CRITICAL',
  [L11ScoreAttributionViolationCode.L11A_MATERIAL_CAP_HIDDEN]: 'CRITICAL',
  [L11ScoreAttributionViolationCode.L11A_MISSING_DATA_EFFECT_NOT_ATTRIBUTED]: 'CRITICAL',
  [L11ScoreAttributionViolationCode.L11A_MATERIAL_MISSING_DATA_HIDDEN]: 'CRITICAL',
  [L11ScoreAttributionViolationCode.L11A_UNGOVERNED_INPUT_REF]: 'CRITICAL',
  [L11ScoreAttributionViolationCode.L11A_REPLAY_HASH_MISSING]: 'CRITICAL',
  [L11ScoreAttributionViolationCode.L11A_REPLAY_HASH_MISMATCH]: 'CRITICAL',
  [L11ScoreAttributionViolationCode.L11A_REPLAY_HASH_NOT_DETERMINISTIC]: 'CRITICAL',
  [L11ScoreAttributionViolationCode.L11A_ATTRIBUTION_ACTS_AS_RECOMMENDATION]: 'CRITICAL',
  [L11ScoreAttributionViolationCode.L11A_ATTRIBUTION_ACTS_AS_JUDGMENT]: 'CRITICAL',
  [L11ScoreAttributionViolationCode.L11A_ATTRIBUTION_ACTS_AS_SCENARIO_WINNER]: 'CRITICAL',
  [L11ScoreAttributionViolationCode.L11A_ATTRIBUTION_ACTS_AS_TRADE_ACTION]: 'CRITICAL',
  [L11ScoreAttributionViolationCode.L11A_COMPLETENESS_BLOCKED_EMITTED]: 'CRITICAL',

  // ERROR
  [L11ScoreAttributionViolationCode.L11A_ATTRIBUTION_ID_MISSING]: 'ERROR',
  [L11ScoreAttributionViolationCode.L11A_SCORE_REF_MISSING]: 'ERROR',
  [L11ScoreAttributionViolationCode.L11A_FORMULA_REF_MISSING]: 'ERROR',
  [L11ScoreAttributionViolationCode.L11A_FORMULA_VERSION_MISSING]: 'ERROR',
  [L11ScoreAttributionViolationCode.L11A_FORMULA_EVALUATION_REF_MISSING]: 'ERROR',
  [L11ScoreAttributionViolationCode.L11A_INPUT_SNAPSHOT_REF_MISSING]: 'ERROR',
  [L11ScoreAttributionViolationCode.L11A_SCOPE_FIELDS_MISSING]: 'ERROR',
  [L11ScoreAttributionViolationCode.L11A_AS_OF_MISSING]: 'ERROR',
  [L11ScoreAttributionViolationCode.L11A_POLICY_VERSION_MISSING]: 'ERROR',
  [L11ScoreAttributionViolationCode.L11A_COMPONENT_CONTRIBUTION_MISSING]: 'ERROR',
  [L11ScoreAttributionViolationCode.L11A_COMPONENT_CONTRIBUTION_INVALID]: 'ERROR',
  [L11ScoreAttributionViolationCode.L11A_COMPONENT_CONTRIBUTION_OUT_OF_BOUNDS]: 'ERROR',
  [L11ScoreAttributionViolationCode.L11A_COMPONENT_DIRECTION_MISMATCH]: 'ERROR',
  [L11ScoreAttributionViolationCode.L11A_MATERIAL_COMPONENT_LACKS_EVIDENCE]: 'ERROR',
  [L11ScoreAttributionViolationCode.L11A_CAP_CONTRIBUTION_INVALID]: 'ERROR',
  [L11ScoreAttributionViolationCode.L11A_PENALTY_APPLIED_BUT_NOT_ATTRIBUTED]: 'ERROR',
  [L11ScoreAttributionViolationCode.L11A_PENALTY_CONTRIBUTION_INVALID]: 'ERROR',
  [L11ScoreAttributionViolationCode.L11A_PENALTY_DIRECTION_INCONSISTENT]: 'ERROR',
  [L11ScoreAttributionViolationCode.L11A_MODIFIER_APPLIED_BUT_NOT_ATTRIBUTED]: 'ERROR',
  [L11ScoreAttributionViolationCode.L11A_MODIFIER_CONTRIBUTION_INVALID]: 'ERROR',
  [L11ScoreAttributionViolationCode.L11A_MODIFIER_SOURCE_LAYER_MISSING]: 'ERROR',
  [L11ScoreAttributionViolationCode.L11A_MISSING_DATA_CONTRIBUTION_INVALID]: 'ERROR',
  [L11ScoreAttributionViolationCode.L11A_MATERIAL_DRIVER_HIDDEN]: 'ERROR',
  [L11ScoreAttributionViolationCode.L11A_TOP_DRIVER_SELECTION_NONDETERMINISTIC]: 'ERROR',
  [L11ScoreAttributionViolationCode.L11A_TOP_DRIVER_POLICY_INVALID]: 'ERROR',
  [L11ScoreAttributionViolationCode.L11A_TOP_DRIVER_REF_UNKNOWN]: 'ERROR',
  [L11ScoreAttributionViolationCode.L11A_SUMMARY_CODE_UNSUPPORTED]: 'ERROR',
  [L11ScoreAttributionViolationCode.L11A_SUMMARY_CODE_INVALID]: 'ERROR',
  [L11ScoreAttributionViolationCode.L11A_COMPLETENESS_CLASS_MISSING]: 'ERROR',
  [L11ScoreAttributionViolationCode.L11A_EVIDENCE_REFS_MISSING]: 'ERROR',
  [L11ScoreAttributionViolationCode.L11A_LINEAGE_REFS_MISSING]: 'ERROR',
};

export function severityForL11AttributionCode(
  code: L11ScoreAttributionViolationCode,
): L11ScoreAttributionSeverity {
  return SEVERITY_MAP[code] ?? 'WARNING';
}

export interface L11ScoreAttributionIssue {
  readonly code: L11ScoreAttributionViolationCode;
  readonly severity: L11ScoreAttributionSeverity;
  readonly message: string;
  readonly subject_ref?: string;
  readonly score_id?: string;
  readonly score_family?: string;
  readonly attribution_id?: string;
  readonly contribution_id?: string;
}

export function makeL11ScoreAttributionIssue(
  code: L11ScoreAttributionViolationCode,
  message: string,
  ctx: Partial<Omit<L11ScoreAttributionIssue, 'code' | 'severity' | 'message'>> = {},
): L11ScoreAttributionIssue {
  return {
    code,
    severity: severityForL11AttributionCode(code),
    message,
    ...ctx,
  };
}
