/**
 * L11.3 — Score Formula Violation Codes (§11.3.19.1)
 *
 * Disjoint `L11F_` namespace so formula violations never collide
 * with L11.1 constitutional codes or L11.2 doctrine codes.
 */

export enum L11ScoreFormulaViolationCode {
  // ── Formula identity ──
  L11F_FORMULA_ID_MISSING = 'L11F_FORMULA_ID_MISSING',
  L11F_FORMULA_VERSION_MISSING = 'L11F_FORMULA_VERSION_MISSING',
  L11F_FORMULA_DUPLICATE = 'L11F_FORMULA_DUPLICATE',
  L11F_FORMULA_STATUS_MISSING = 'L11F_FORMULA_STATUS_MISSING',
  L11F_FORMULA_STATUS_NOT_PRODUCTION = 'L11F_FORMULA_STATUS_NOT_PRODUCTION',

  // ── Family / direction integrity ──
  L11F_RESERVED_FAMILY_HAS_FORMULA = 'L11F_RESERVED_FAMILY_HAS_FORMULA',
  L11F_FAMILY_HAS_NO_PRODUCTION_FORMULA = 'L11F_FAMILY_HAS_NO_PRODUCTION_FORMULA',
  L11F_FORMULA_DIRECTION_MISSING = 'L11F_FORMULA_DIRECTION_MISSING',
  L11F_FORMULA_DIRECTION_MISMATCH = 'L11F_FORMULA_DIRECTION_MISMATCH',
  L11F_FORMULA_FAMILY_MISMATCH = 'L11F_FORMULA_FAMILY_MISMATCH',

  // ── Component law ──
  L11F_COMPONENT_MISSING = 'L11F_COMPONENT_MISSING',
  L11F_COMPONENT_DUPLICATE = 'L11F_COMPONENT_DUPLICATE',
  L11F_COMPONENT_OUT_OF_BOUNDS = 'L11F_COMPONENT_OUT_OF_BOUNDS',
  L11F_COMPONENT_NORMALIZER_MISSING = 'L11F_COMPONENT_NORMALIZER_MISSING',
  L11F_COMPONENT_DIRECTION_MISMATCH = 'L11F_COMPONENT_DIRECTION_MISMATCH',
  L11F_COMPONENT_FAMILY_MISMATCH = 'L11F_COMPONENT_FAMILY_MISMATCH',
  L11F_COMPONENT_REQUIRED_ZERO_WEIGHT = 'L11F_COMPONENT_REQUIRED_ZERO_WEIGHT',
  L11F_COMPONENT_ATTRIBUTION_REQUIRED = 'L11F_COMPONENT_ATTRIBUTION_REQUIRED',

  // ── Input surface law ──
  L11F_REQUIRED_INPUT_SURFACE_MISSING = 'L11F_REQUIRED_INPUT_SURFACE_MISSING',
  L11F_UNREGISTERED_INPUT_SURFACE = 'L11F_UNREGISTERED_INPUT_SURFACE',
  L11F_EVIDENCE_ONLY_USED_AS_DECISIVE = 'L11F_EVIDENCE_ONLY_USED_AS_DECISIVE',

  // ── Weight law ──
  L11F_WEIGHT_SUM_INVALID = 'L11F_WEIGHT_SUM_INVALID',
  L11F_WEIGHT_PROFILE_MISSING = 'L11F_WEIGHT_PROFILE_MISSING',
  L11F_WEIGHT_PROFILE_DUPLICATE = 'L11F_WEIGHT_PROFILE_DUPLICATE',
  L11F_WEIGHT_PROFILE_FAMILY_MISMATCH = 'L11F_WEIGHT_PROFILE_FAMILY_MISMATCH',
  L11F_HIDDEN_COMPONENT_WEIGHT = 'L11F_HIDDEN_COMPONENT_WEIGHT',

  // ── Cap / penalty / modifier / missing-data law ──
  L11F_CAP_RULE_UNDECLARED = 'L11F_CAP_RULE_UNDECLARED',
  L11F_CAP_RULE_INVALID = 'L11F_CAP_RULE_INVALID',
  L11F_PENALTY_RULE_UNDECLARED = 'L11F_PENALTY_RULE_UNDECLARED',
  L11F_PENALTY_RULE_INVALID = 'L11F_PENALTY_RULE_INVALID',
  L11F_MODIFIER_RULE_UNDECLARED = 'L11F_MODIFIER_RULE_UNDECLARED',
  L11F_MODIFIER_RULE_INVALID = 'L11F_MODIFIER_RULE_INVALID',
  L11F_MISSING_DATA_RULE_MISSING = 'L11F_MISSING_DATA_RULE_MISSING',
  L11F_MISSING_DATA_RULE_ILLEGAL = 'L11F_MISSING_DATA_RULE_ILLEGAL',

  // ── Calibration / band policy ──
  L11F_CALIBRATION_TARGET_MISSING = 'L11F_CALIBRATION_TARGET_MISSING',
  L11F_OUTPUT_BAND_POLICY_MISSING = 'L11F_OUTPUT_BAND_POLICY_MISSING',

  // ── Evaluation result law ──
  L11F_RAW_SCORE_OUT_OF_RANGE = 'L11F_RAW_SCORE_OUT_OF_RANGE',
  L11F_RAW_SCORE_NOT_FINITE = 'L11F_RAW_SCORE_NOT_FINITE',
  L11F_COMPONENT_RESULT_OUT_OF_BOUNDS = 'L11F_COMPONENT_RESULT_OUT_OF_BOUNDS',
  L11F_REQUIRED_COMPONENT_RESULT_MISSING = 'L11F_REQUIRED_COMPONENT_RESULT_MISSING',
  L11F_PENALTY_APPLIED_NOT_DECLARED = 'L11F_PENALTY_APPLIED_NOT_DECLARED',
  L11F_CAP_APPLIED_NOT_DECLARED = 'L11F_CAP_APPLIED_NOT_DECLARED',
  L11F_MODIFIER_APPLIED_NOT_DECLARED = 'L11F_MODIFIER_APPLIED_NOT_DECLARED',
  L11F_MISSING_DATA_EFFECT_ABSENT = 'L11F_MISSING_DATA_EFFECT_ABSENT',
  L11F_FORMULA_READINESS_INCONSISTENT = 'L11F_FORMULA_READINESS_INCONSISTENT',
  L11F_FORMULA_EVALUATION_FAMILY_MISMATCH = 'L11F_FORMULA_EVALUATION_FAMILY_MISMATCH',

  // ── Replay law ──
  L11F_REPLAY_HASH_MISSING = 'L11F_REPLAY_HASH_MISSING',
  L11F_REPLAY_HASH_MISMATCH = 'L11F_REPLAY_HASH_MISMATCH',
  L11F_REPLAY_HASH_NOT_DETERMINISTIC = 'L11F_REPLAY_HASH_NOT_DETERMINISTIC',

  // ── Semantic-leak law ──
  L11F_RECOMMENDATION_LEAK = 'L11F_RECOMMENDATION_LEAK',
  L11F_JUDGMENT_LEAK = 'L11F_JUDGMENT_LEAK',
  L11F_SCENARIO_WINNER_LEAK = 'L11F_SCENARIO_WINNER_LEAK',
  L11F_TRADE_ACTION_LEAK = 'L11F_TRADE_ACTION_LEAK',
  L11F_FAMILY_INTERPRETATION_LEAK = 'L11F_FAMILY_INTERPRETATION_LEAK',
}

export const ALL_L11_SCORE_FORMULA_VIOLATION_CODES:
  readonly L11ScoreFormulaViolationCode[] =
  Object.values(L11ScoreFormulaViolationCode);

export type L11ScoreFormulaSeverity =
  | 'INFO' | 'WARNING' | 'ERROR' | 'CRITICAL';

const SEVERITY_MAP: Readonly<Record<L11ScoreFormulaViolationCode, L11ScoreFormulaSeverity>> = {
  // Critical violations — block any production emission
  [L11ScoreFormulaViolationCode.L11F_RESERVED_FAMILY_HAS_FORMULA]: 'CRITICAL',
  [L11ScoreFormulaViolationCode.L11F_FORMULA_DIRECTION_MISSING]: 'CRITICAL',
  [L11ScoreFormulaViolationCode.L11F_FORMULA_DIRECTION_MISMATCH]: 'CRITICAL',
  [L11ScoreFormulaViolationCode.L11F_FORMULA_FAMILY_MISMATCH]: 'CRITICAL',
  [L11ScoreFormulaViolationCode.L11F_RECOMMENDATION_LEAK]: 'CRITICAL',
  [L11ScoreFormulaViolationCode.L11F_JUDGMENT_LEAK]: 'CRITICAL',
  [L11ScoreFormulaViolationCode.L11F_SCENARIO_WINNER_LEAK]: 'CRITICAL',
  [L11ScoreFormulaViolationCode.L11F_TRADE_ACTION_LEAK]: 'CRITICAL',
  [L11ScoreFormulaViolationCode.L11F_FAMILY_INTERPRETATION_LEAK]: 'CRITICAL',
  [L11ScoreFormulaViolationCode.L11F_RAW_SCORE_OUT_OF_RANGE]: 'CRITICAL',
  [L11ScoreFormulaViolationCode.L11F_RAW_SCORE_NOT_FINITE]: 'CRITICAL',
  [L11ScoreFormulaViolationCode.L11F_REPLAY_HASH_MISSING]: 'CRITICAL',
  [L11ScoreFormulaViolationCode.L11F_REPLAY_HASH_MISMATCH]: 'CRITICAL',
  [L11ScoreFormulaViolationCode.L11F_REPLAY_HASH_NOT_DETERMINISTIC]: 'CRITICAL',
  [L11ScoreFormulaViolationCode.L11F_MISSING_DATA_EFFECT_ABSENT]: 'CRITICAL',
  [L11ScoreFormulaViolationCode.L11F_FORMULA_EVALUATION_FAMILY_MISMATCH]: 'CRITICAL',

  // Errors — well-formed but illegal definitions
  [L11ScoreFormulaViolationCode.L11F_FORMULA_ID_MISSING]: 'ERROR',
  [L11ScoreFormulaViolationCode.L11F_FORMULA_VERSION_MISSING]: 'ERROR',
  [L11ScoreFormulaViolationCode.L11F_FORMULA_DUPLICATE]: 'ERROR',
  [L11ScoreFormulaViolationCode.L11F_FORMULA_STATUS_MISSING]: 'ERROR',
  [L11ScoreFormulaViolationCode.L11F_FORMULA_STATUS_NOT_PRODUCTION]: 'ERROR',
  [L11ScoreFormulaViolationCode.L11F_FAMILY_HAS_NO_PRODUCTION_FORMULA]: 'ERROR',
  [L11ScoreFormulaViolationCode.L11F_COMPONENT_MISSING]: 'ERROR',
  [L11ScoreFormulaViolationCode.L11F_COMPONENT_DUPLICATE]: 'ERROR',
  [L11ScoreFormulaViolationCode.L11F_COMPONENT_OUT_OF_BOUNDS]: 'ERROR',
  [L11ScoreFormulaViolationCode.L11F_COMPONENT_NORMALIZER_MISSING]: 'ERROR',
  [L11ScoreFormulaViolationCode.L11F_COMPONENT_DIRECTION_MISMATCH]: 'ERROR',
  [L11ScoreFormulaViolationCode.L11F_COMPONENT_FAMILY_MISMATCH]: 'ERROR',
  [L11ScoreFormulaViolationCode.L11F_COMPONENT_REQUIRED_ZERO_WEIGHT]: 'ERROR',
  [L11ScoreFormulaViolationCode.L11F_COMPONENT_ATTRIBUTION_REQUIRED]: 'ERROR',
  [L11ScoreFormulaViolationCode.L11F_REQUIRED_INPUT_SURFACE_MISSING]: 'ERROR',
  [L11ScoreFormulaViolationCode.L11F_UNREGISTERED_INPUT_SURFACE]: 'ERROR',
  [L11ScoreFormulaViolationCode.L11F_EVIDENCE_ONLY_USED_AS_DECISIVE]: 'ERROR',
  [L11ScoreFormulaViolationCode.L11F_WEIGHT_SUM_INVALID]: 'ERROR',
  [L11ScoreFormulaViolationCode.L11F_WEIGHT_PROFILE_MISSING]: 'ERROR',
  [L11ScoreFormulaViolationCode.L11F_WEIGHT_PROFILE_DUPLICATE]: 'ERROR',
  [L11ScoreFormulaViolationCode.L11F_WEIGHT_PROFILE_FAMILY_MISMATCH]: 'ERROR',
  [L11ScoreFormulaViolationCode.L11F_HIDDEN_COMPONENT_WEIGHT]: 'ERROR',
  [L11ScoreFormulaViolationCode.L11F_CAP_RULE_UNDECLARED]: 'ERROR',
  [L11ScoreFormulaViolationCode.L11F_CAP_RULE_INVALID]: 'ERROR',
  [L11ScoreFormulaViolationCode.L11F_PENALTY_RULE_UNDECLARED]: 'ERROR',
  [L11ScoreFormulaViolationCode.L11F_PENALTY_RULE_INVALID]: 'ERROR',
  [L11ScoreFormulaViolationCode.L11F_MODIFIER_RULE_UNDECLARED]: 'ERROR',
  [L11ScoreFormulaViolationCode.L11F_MODIFIER_RULE_INVALID]: 'ERROR',
  [L11ScoreFormulaViolationCode.L11F_MISSING_DATA_RULE_MISSING]: 'ERROR',
  [L11ScoreFormulaViolationCode.L11F_MISSING_DATA_RULE_ILLEGAL]: 'ERROR',
  [L11ScoreFormulaViolationCode.L11F_CALIBRATION_TARGET_MISSING]: 'ERROR',
  [L11ScoreFormulaViolationCode.L11F_OUTPUT_BAND_POLICY_MISSING]: 'ERROR',
  [L11ScoreFormulaViolationCode.L11F_COMPONENT_RESULT_OUT_OF_BOUNDS]: 'ERROR',
  [L11ScoreFormulaViolationCode.L11F_REQUIRED_COMPONENT_RESULT_MISSING]: 'ERROR',
  [L11ScoreFormulaViolationCode.L11F_PENALTY_APPLIED_NOT_DECLARED]: 'ERROR',
  [L11ScoreFormulaViolationCode.L11F_CAP_APPLIED_NOT_DECLARED]: 'ERROR',
  [L11ScoreFormulaViolationCode.L11F_MODIFIER_APPLIED_NOT_DECLARED]: 'ERROR',
  [L11ScoreFormulaViolationCode.L11F_FORMULA_READINESS_INCONSISTENT]: 'ERROR',
};

export function severityForL11FormulaCode(
  code: L11ScoreFormulaViolationCode,
): L11ScoreFormulaSeverity {
  return SEVERITY_MAP[code] ?? 'WARNING';
}

export interface L11ScoreFormulaIssue {
  readonly code: L11ScoreFormulaViolationCode;
  readonly severity: L11ScoreFormulaSeverity;
  readonly message: string;
  readonly subject_ref?: string;
  readonly score_family?: string;
  readonly formula_id?: string;
  readonly component_id?: string;
}

export function makeL11ScoreFormulaIssue(
  code: L11ScoreFormulaViolationCode,
  message: string,
  ctx: Partial<Omit<L11ScoreFormulaIssue, 'code' | 'severity' | 'message'>> = {},
): L11ScoreFormulaIssue {
  return {
    code,
    severity: severityForL11FormulaCode(code),
    message,
    ...ctx,
  };
}
