/**
 * L11.6 — Calibration Violation Codes (§11.6.15.1)
 *
 * Disjoint `L11C_` namespace so calibration violations never
 * collide with L11.1 / L11.2 / L11.3 / L11.4 / L11.5 codes.
 */

export enum L11CalibrationViolationCode {
  // ── Target identity & structure ──
  L11C_CALIBRATION_TARGET_ID_MISSING = 'L11C_CALIBRATION_TARGET_ID_MISSING',
  L11C_CALIBRATION_TARGET_MISSING = 'L11C_CALIBRATION_TARGET_MISSING',
  L11C_TARGET_VERSION_MISSING = 'L11C_TARGET_VERSION_MISSING',
  L11C_TARGET_POLICY_VERSION_MISSING = 'L11C_TARGET_POLICY_VERSION_MISSING',
  L11C_TARGET_LINEAGE_MISSING = 'L11C_TARGET_LINEAGE_MISSING',
  L11C_TARGET_DESCRIPTION_MISSING = 'L11C_TARGET_DESCRIPTION_MISSING',

  // ── Outcome metric law (§11.6.7) ──
  L11C_OUTCOME_METRIC_MISSING = 'L11C_OUTCOME_METRIC_MISSING',
  L11C_OUTCOME_METRIC_UNSUPPORTED = 'L11C_OUTCOME_METRIC_UNSUPPORTED',
  L11C_OUTCOME_METRIC_NOT_ALLOWED_FOR_FAMILY = 'L11C_OUTCOME_METRIC_NOT_ALLOWED_FOR_FAMILY',
  L11C_OUTCOME_METRIC_LACKS_MEASUREMENT_SOURCE = 'L11C_OUTCOME_METRIC_LACKS_MEASUREMENT_SOURCE',
  L11C_OUTCOME_METRIC_LACKS_FUTURE_DATA_SURFACE = 'L11C_OUTCOME_METRIC_LACKS_FUTURE_DATA_SURFACE',

  // ── Horizon law (§11.6.6) ──
  L11C_HORIZON_MISSING = 'L11C_HORIZON_MISSING',
  L11C_HORIZON_UNSUPPORTED_FOR_FAMILY = 'L11C_HORIZON_UNSUPPORTED_FOR_FAMILY',
  L11C_HORIZON_UNSUPPORTED_FOR_METRIC = 'L11C_HORIZON_UNSUPPORTED_FOR_METRIC',
  L11C_EVALUATION_WINDOW_INVALID = 'L11C_EVALUATION_WINDOW_INVALID',
  L11C_EVALUATION_WINDOW_NOT_ANCHORED_TO_AS_OF = 'L11C_EVALUATION_WINDOW_NOT_ANCHORED_TO_AS_OF',

  // ── Expected direction law (§11.6.8) ──
  L11C_EXPECTED_DIRECTION_MISSING = 'L11C_EXPECTED_DIRECTION_MISSING',
  L11C_EXPECTED_DIRECTION_CONTRADICTS_SCORE_MEANING = 'L11C_EXPECTED_DIRECTION_CONTRADICTS_SCORE_MEANING',
  L11C_EXPECTED_DIRECTION_CONTRADICTS_OUTCOME_METRIC = 'L11C_EXPECTED_DIRECTION_CONTRADICTS_OUTCOME_METRIC',
  L11C_EXPECTED_DIRECTION_NOT_PRODUCTION_LEGAL = 'L11C_EXPECTED_DIRECTION_NOT_PRODUCTION_LEGAL',

  // ── Cohort law (§11.6.9) ──
  L11C_COHORT_DEFINITION_MISSING = 'L11C_COHORT_DEFINITION_MISSING',
  L11C_COHORT_FAMILY_MISMATCH = 'L11C_COHORT_FAMILY_MISMATCH',
  L11C_COHORT_LACKS_BAND_FILTER_CAPABILITY = 'L11C_COHORT_LACKS_BAND_FILTER_CAPABILITY',
  L11C_COHORT_IGNORES_FORMULA_VERSION = 'L11C_COHORT_IGNORES_FORMULA_VERSION',
  L11C_COHORT_IGNORES_VISIBILITY_CLASS = 'L11C_COHORT_IGNORES_VISIBILITY_CLASS',
  L11C_COHORT_MIXES_DEPRECATED_WITHOUT_MIGRATION_FLAG = 'L11C_COHORT_MIXES_DEPRECATED_WITHOUT_MIGRATION_FLAG',
  L11C_COHORT_MIN_OBSERVATION_COUNT_INVALID = 'L11C_COHORT_MIN_OBSERVATION_COUNT_INVALID',
  L11C_MINIMUM_SAMPLE_SIZE_MISSING = 'L11C_MINIMUM_SAMPLE_SIZE_MISSING',

  // ── Exclusion law (§11.6.10) ──
  L11C_EXCLUSION_RULES_MISSING = 'L11C_EXCLUSION_RULES_MISSING',
  L11C_EXCLUSION_RULE_NOT_VERSIONED = 'L11C_EXCLUSION_RULE_NOT_VERSIONED',
  L11C_EXCLUSION_CLASS_UNKNOWN = 'L11C_EXCLUSION_CLASS_UNKNOWN',
  L11C_EXCLUSION_CAUSES_SURVIVORSHIP_BIAS = 'L11C_EXCLUSION_CAUSES_SURVIVORSHIP_BIAS',
  L11C_REQUIRED_EXCLUSION_CLASS_MISSING = 'L11C_REQUIRED_EXCLUSION_CLASS_MISSING',

  // ── Family / version law (§11.6.13) ──
  L11C_RESERVED_FAMILY_HAS_TARGET = 'L11C_RESERVED_FAMILY_HAS_TARGET',
  L11C_PRODUCTION_FAMILY_LACKS_TARGET = 'L11C_PRODUCTION_FAMILY_LACKS_TARGET',
  L11C_DUPLICATE_TARGET_ID = 'L11C_DUPLICATE_TARGET_ID',
  L11C_FORMULA_VERSION_MISMATCH = 'L11C_FORMULA_VERSION_MISMATCH',
  L11C_SCORE_VERSION_MISMATCH = 'L11C_SCORE_VERSION_MISMATCH',

  // ── Hook law (§11.6.5) ──
  L11C_HOOK_ID_MISSING = 'L11C_HOOK_ID_MISSING',
  L11C_HOOK_SCORE_REF_MISSING = 'L11C_HOOK_SCORE_REF_MISSING',
  L11C_HOOK_TARGET_REF_MISSING = 'L11C_HOOK_TARGET_REF_MISSING',
  L11C_HOOK_TARGET_REF_UNRESOLVED = 'L11C_HOOK_TARGET_REF_UNRESOLVED',
  L11C_HOOK_HORIZON_MISSING = 'L11C_HOOK_HORIZON_MISSING',
  L11C_HOOK_OUTCOME_METRIC_MISSING = 'L11C_HOOK_OUTCOME_METRIC_MISSING',
  L11C_HOOK_EXPECTED_DIRECTION_MISSING = 'L11C_HOOK_EXPECTED_DIRECTION_MISSING',
  L11C_HOOK_COHORT_KEY_MISSING = 'L11C_HOOK_COHORT_KEY_MISSING',
  L11C_HOOK_COHORT_REF_MISSING = 'L11C_HOOK_COHORT_REF_MISSING',
  L11C_HOOK_EVAL_WINDOW_MISSING = 'L11C_HOOK_EVAL_WINDOW_MISSING',
  L11C_HOOK_LINEAGE_MISSING = 'L11C_HOOK_LINEAGE_MISSING',
  L11C_HOOK_REPLAY_HASH_MISSING = 'L11C_HOOK_REPLAY_HASH_MISSING',
  L11C_HOOK_REPLAY_HASH_MISMATCH = 'L11C_HOOK_REPLAY_HASH_MISMATCH',
  L11C_HOOK_TARGET_FAMILY_MISMATCH = 'L11C_HOOK_TARGET_FAMILY_MISMATCH',
  L11C_HOOK_TARGET_METRIC_MISMATCH = 'L11C_HOOK_TARGET_METRIC_MISMATCH',
  L11C_HOOK_TARGET_HORIZON_MISMATCH = 'L11C_HOOK_TARGET_HORIZON_MISMATCH',
  L11C_HOOK_TARGET_DIRECTION_MISMATCH = 'L11C_HOOK_TARGET_DIRECTION_MISMATCH',
  L11C_HOOK_TARGET_COHORT_MISMATCH = 'L11C_HOOK_TARGET_COHORT_MISMATCH',

  // ── Readiness law (§11.6.12) ──
  L11C_READINESS_CLASS_MISSING = 'L11C_READINESS_CLASS_MISSING',
  L11C_READINESS_CLASS_INCONSISTENT = 'L11C_READINESS_CLASS_INCONSISTENT',

  // ── Replay law (§11.6.16) ──
  L11C_TARGET_REPLAY_HASH_MISSING = 'L11C_TARGET_REPLAY_HASH_MISSING',
  L11C_TARGET_REPLAY_HASH_MISMATCH = 'L11C_TARGET_REPLAY_HASH_MISMATCH',

  // ── Boundary law (§11.6.3) ──
  L11C_CALIBRATION_IMPLIES_CAUSALITY = 'L11C_CALIBRATION_IMPLIES_CAUSALITY',
  L11C_CALIBRATION_ACTS_AS_JUDGMENT = 'L11C_CALIBRATION_ACTS_AS_JUDGMENT',
  L11C_CALIBRATION_OVERRIDES_DOCTRINE = 'L11C_CALIBRATION_OVERRIDES_DOCTRINE',

  // ── Score-family <-> calibration coverage (INV-11.6-A / INV-11.6-B) ──
  L11C_SCORE_LACKS_CALIBRATION_HOOK = 'L11C_SCORE_LACKS_CALIBRATION_HOOK',
}

export type L11CalibrationSeverity = 'CRITICAL' | 'ERROR' | 'WARNING';

const SEVERITY_MAP: Readonly<Record<L11CalibrationViolationCode, L11CalibrationSeverity>> = {
  // CRITICAL
  [L11CalibrationViolationCode.L11C_CALIBRATION_TARGET_MISSING]: 'CRITICAL',
  [L11CalibrationViolationCode.L11C_PRODUCTION_FAMILY_LACKS_TARGET]: 'CRITICAL',
  [L11CalibrationViolationCode.L11C_RESERVED_FAMILY_HAS_TARGET]: 'CRITICAL',
  [L11CalibrationViolationCode.L11C_EXPECTED_DIRECTION_MISSING]: 'CRITICAL',
  [L11CalibrationViolationCode.L11C_EXPECTED_DIRECTION_CONTRADICTS_SCORE_MEANING]: 'CRITICAL',
  [L11CalibrationViolationCode.L11C_EXPECTED_DIRECTION_CONTRADICTS_OUTCOME_METRIC]: 'CRITICAL',
  [L11CalibrationViolationCode.L11C_OUTCOME_METRIC_NOT_ALLOWED_FOR_FAMILY]: 'CRITICAL',
  [L11CalibrationViolationCode.L11C_CALIBRATION_IMPLIES_CAUSALITY]: 'CRITICAL',
  [L11CalibrationViolationCode.L11C_CALIBRATION_ACTS_AS_JUDGMENT]: 'CRITICAL',
  [L11CalibrationViolationCode.L11C_CALIBRATION_OVERRIDES_DOCTRINE]: 'CRITICAL',
  [L11CalibrationViolationCode.L11C_EXCLUSION_CAUSES_SURVIVORSHIP_BIAS]: 'CRITICAL',
  [L11CalibrationViolationCode.L11C_DUPLICATE_TARGET_ID]: 'CRITICAL',
  [L11CalibrationViolationCode.L11C_HOOK_TARGET_REF_UNRESOLVED]: 'CRITICAL',
  [L11CalibrationViolationCode.L11C_HOOK_REPLAY_HASH_MISMATCH]: 'CRITICAL',
  [L11CalibrationViolationCode.L11C_TARGET_REPLAY_HASH_MISMATCH]: 'CRITICAL',
  [L11CalibrationViolationCode.L11C_SCORE_LACKS_CALIBRATION_HOOK]: 'CRITICAL',

  // ERROR
  [L11CalibrationViolationCode.L11C_CALIBRATION_TARGET_ID_MISSING]: 'ERROR',
  [L11CalibrationViolationCode.L11C_TARGET_VERSION_MISSING]: 'ERROR',
  [L11CalibrationViolationCode.L11C_TARGET_POLICY_VERSION_MISSING]: 'ERROR',
  [L11CalibrationViolationCode.L11C_TARGET_LINEAGE_MISSING]: 'ERROR',
  [L11CalibrationViolationCode.L11C_TARGET_DESCRIPTION_MISSING]: 'ERROR',
  [L11CalibrationViolationCode.L11C_OUTCOME_METRIC_MISSING]: 'ERROR',
  [L11CalibrationViolationCode.L11C_OUTCOME_METRIC_UNSUPPORTED]: 'ERROR',
  [L11CalibrationViolationCode.L11C_OUTCOME_METRIC_LACKS_MEASUREMENT_SOURCE]: 'ERROR',
  [L11CalibrationViolationCode.L11C_OUTCOME_METRIC_LACKS_FUTURE_DATA_SURFACE]: 'ERROR',
  [L11CalibrationViolationCode.L11C_HORIZON_MISSING]: 'ERROR',
  [L11CalibrationViolationCode.L11C_HORIZON_UNSUPPORTED_FOR_FAMILY]: 'ERROR',
  [L11CalibrationViolationCode.L11C_HORIZON_UNSUPPORTED_FOR_METRIC]: 'ERROR',
  [L11CalibrationViolationCode.L11C_EVALUATION_WINDOW_INVALID]: 'ERROR',
  [L11CalibrationViolationCode.L11C_EVALUATION_WINDOW_NOT_ANCHORED_TO_AS_OF]: 'ERROR',
  [L11CalibrationViolationCode.L11C_EXPECTED_DIRECTION_NOT_PRODUCTION_LEGAL]: 'ERROR',
  [L11CalibrationViolationCode.L11C_COHORT_DEFINITION_MISSING]: 'ERROR',
  [L11CalibrationViolationCode.L11C_COHORT_FAMILY_MISMATCH]: 'ERROR',
  [L11CalibrationViolationCode.L11C_COHORT_LACKS_BAND_FILTER_CAPABILITY]: 'ERROR',
  [L11CalibrationViolationCode.L11C_COHORT_IGNORES_FORMULA_VERSION]: 'ERROR',
  [L11CalibrationViolationCode.L11C_COHORT_IGNORES_VISIBILITY_CLASS]: 'ERROR',
  [L11CalibrationViolationCode.L11C_COHORT_MIXES_DEPRECATED_WITHOUT_MIGRATION_FLAG]: 'ERROR',
  [L11CalibrationViolationCode.L11C_COHORT_MIN_OBSERVATION_COUNT_INVALID]: 'ERROR',
  [L11CalibrationViolationCode.L11C_MINIMUM_SAMPLE_SIZE_MISSING]: 'ERROR',
  [L11CalibrationViolationCode.L11C_EXCLUSION_RULES_MISSING]: 'ERROR',
  [L11CalibrationViolationCode.L11C_EXCLUSION_RULE_NOT_VERSIONED]: 'ERROR',
  [L11CalibrationViolationCode.L11C_EXCLUSION_CLASS_UNKNOWN]: 'ERROR',
  [L11CalibrationViolationCode.L11C_REQUIRED_EXCLUSION_CLASS_MISSING]: 'ERROR',
  [L11CalibrationViolationCode.L11C_FORMULA_VERSION_MISMATCH]: 'ERROR',
  [L11CalibrationViolationCode.L11C_SCORE_VERSION_MISMATCH]: 'ERROR',
  [L11CalibrationViolationCode.L11C_HOOK_ID_MISSING]: 'ERROR',
  [L11CalibrationViolationCode.L11C_HOOK_SCORE_REF_MISSING]: 'ERROR',
  [L11CalibrationViolationCode.L11C_HOOK_TARGET_REF_MISSING]: 'ERROR',
  [L11CalibrationViolationCode.L11C_HOOK_HORIZON_MISSING]: 'ERROR',
  [L11CalibrationViolationCode.L11C_HOOK_OUTCOME_METRIC_MISSING]: 'ERROR',
  [L11CalibrationViolationCode.L11C_HOOK_EXPECTED_DIRECTION_MISSING]: 'ERROR',
  [L11CalibrationViolationCode.L11C_HOOK_COHORT_KEY_MISSING]: 'ERROR',
  [L11CalibrationViolationCode.L11C_HOOK_COHORT_REF_MISSING]: 'ERROR',
  [L11CalibrationViolationCode.L11C_HOOK_EVAL_WINDOW_MISSING]: 'ERROR',
  [L11CalibrationViolationCode.L11C_HOOK_LINEAGE_MISSING]: 'ERROR',
  [L11CalibrationViolationCode.L11C_HOOK_REPLAY_HASH_MISSING]: 'ERROR',
  [L11CalibrationViolationCode.L11C_HOOK_TARGET_FAMILY_MISMATCH]: 'ERROR',
  [L11CalibrationViolationCode.L11C_HOOK_TARGET_METRIC_MISMATCH]: 'ERROR',
  [L11CalibrationViolationCode.L11C_HOOK_TARGET_HORIZON_MISMATCH]: 'ERROR',
  [L11CalibrationViolationCode.L11C_HOOK_TARGET_DIRECTION_MISMATCH]: 'ERROR',
  [L11CalibrationViolationCode.L11C_HOOK_TARGET_COHORT_MISMATCH]: 'ERROR',
  [L11CalibrationViolationCode.L11C_READINESS_CLASS_MISSING]: 'ERROR',
  [L11CalibrationViolationCode.L11C_READINESS_CLASS_INCONSISTENT]: 'ERROR',
  [L11CalibrationViolationCode.L11C_TARGET_REPLAY_HASH_MISSING]: 'ERROR',
};

export function severityForL11CalibrationCode(
  code: L11CalibrationViolationCode,
): L11CalibrationSeverity {
  return SEVERITY_MAP[code] ?? 'WARNING';
}

export interface L11CalibrationIssue {
  readonly code: L11CalibrationViolationCode;
  readonly severity: L11CalibrationSeverity;
  readonly message: string;
  readonly subject_ref?: string;
  readonly target_id?: string;
  readonly hook_id?: string;
  readonly score_id?: string;
  readonly score_family?: string;
  readonly cohort_id?: string;
  readonly exclusion_rule_id?: string;
  readonly metric?: string;
}

export function makeL11CalibrationIssue(
  code: L11CalibrationViolationCode,
  message: string,
  ctx: Partial<Omit<L11CalibrationIssue, 'code' | 'severity' | 'message'>> = {},
): L11CalibrationIssue {
  return { code, severity: severityForL11CalibrationCode(code), message, ...ctx };
}

export const ALL_L11_CALIBRATION_VIOLATION_CODES:
  readonly L11CalibrationViolationCode[] =
  Object.values(L11CalibrationViolationCode);
