/**
 * L11.5 — Missing-Data and Regime-Modifier Violation Codes (§11.5.14.1)
 *
 * Disjoint `L11M_` namespace so missing-data and regime-modifier
 * violations never collide with L11.1 / L11.2 / L11.3 / L11.4 codes.
 */

export enum L11MissingRegimeViolationCode {
  // ── Missing-data profile identity & structure ──
  L11M_MISSING_PROFILE_ID_MISSING = 'L11M_MISSING_PROFILE_ID_MISSING',
  L11M_MISSING_PROFILE_SCORE_REF_MISSING = 'L11M_MISSING_PROFILE_SCORE_REF_MISSING',
  L11M_MISSING_PROFILE_FORMULA_REF_MISSING = 'L11M_MISSING_PROFILE_FORMULA_REF_MISSING',
  L11M_MISSING_PROFILE_FORMULA_VERSION_MISSING = 'L11M_MISSING_PROFILE_FORMULA_VERSION_MISSING',
  L11M_MISSING_PROFILE_SCOPE_FIELDS_MISSING = 'L11M_MISSING_PROFILE_SCOPE_FIELDS_MISSING',
  L11M_MISSING_PROFILE_AS_OF_MISSING = 'L11M_MISSING_PROFILE_AS_OF_MISSING',
  L11M_MISSING_PROFILE_INPUT_SNAPSHOT_REF_MISSING = 'L11M_MISSING_PROFILE_INPUT_SNAPSHOT_REF_MISSING',
  L11M_MISSING_PROFILE_LINEAGE_REFS_MISSING = 'L11M_MISSING_PROFILE_LINEAGE_REFS_MISSING',
  L11M_MISSING_PROFILE_POLICY_VERSION_MISSING = 'L11M_MISSING_PROFILE_POLICY_VERSION_MISSING',
  L11M_MISSING_DATA_PROFILE_ABSENT = 'L11M_MISSING_DATA_PROFILE_ABSENT',

  // ── Missing-input ref law ──
  L11M_INPUT_REF_ID_MISSING = 'L11M_INPUT_REF_ID_MISSING',
  L11M_INPUT_SURFACE_REF_MISSING = 'L11M_INPUT_SURFACE_REF_MISSING',
  L11M_INPUT_SOURCE_LAYER_MISSING = 'L11M_INPUT_SOURCE_LAYER_MISSING',
  L11M_INPUT_DEPENDENCY_CLASS_MISSING = 'L11M_INPUT_DEPENDENCY_CLASS_MISSING',
  L11M_INPUT_CONDITION_CLASS_MISSING = 'L11M_INPUT_CONDITION_CLASS_MISSING',
  L11M_REQUIRED_INPUT_LACKS_COMPONENT_REFS = 'L11M_REQUIRED_INPUT_LACKS_COMPONENT_REFS',
  L11M_STALE_INPUT_LACKS_FRESHNESS_DATA = 'L11M_STALE_INPUT_LACKS_FRESHNESS_DATA',
  L11M_DEGRADED_INPUT_LACKS_REASON = 'L11M_DEGRADED_INPUT_LACKS_REASON',
  L11M_RESTRICTED_INPUT_LACKS_RESTRICTION_REFS = 'L11M_RESTRICTED_INPUT_LACKS_RESTRICTION_REFS',
  L11M_CONFLICTING_INPUT_LACKS_CONTRADICTION_REFS = 'L11M_CONFLICTING_INPUT_LACKS_CONTRADICTION_REFS',
  L11M_INPUT_REF_LINEAGE_MISSING = 'L11M_INPUT_REF_LINEAGE_MISSING',
  L11M_INSUFFICIENT_SET_INVALID = 'L11M_INSUFFICIENT_SET_INVALID',

  // ── Behaviour law (§11.5.4.2) ──
  L11M_REQUIRED_INPUT_MISSING_BUT_NEUTRAL = 'L11M_REQUIRED_INPUT_MISSING_BUT_NEUTRAL',
  L11M_STALE_INPUT_USED_AS_CURRENT = 'L11M_STALE_INPUT_USED_AS_CURRENT',
  L11M_DEGRADED_INPUT_USED_AS_FULL_SUPPORT = 'L11M_DEGRADED_INPUT_USED_AS_FULL_SUPPORT',
  L11M_EVIDENCE_ONLY_INPUT_USED_DECISIVELY = 'L11M_EVIDENCE_ONLY_INPUT_USED_DECISIVELY',
  L11M_RESTRICTED_INPUT_USED_BEYOND_RIGHTS = 'L11M_RESTRICTED_INPUT_USED_BEYOND_RIGHTS',
  L11M_CONFLICTING_INPUT_INCREASES_CONFIDENCE = 'L11M_CONFLICTING_INPUT_INCREASES_CONFIDENCE',
  L11M_BEHAVIOR_ABSENT_FOR_INPUT_CONDITION = 'L11M_BEHAVIOR_ABSENT_FOR_INPUT_CONDITION',
  L11M_BEHAVIOR_ILLEGAL_FOR_CONDITION = 'L11M_BEHAVIOR_ILLEGAL_FOR_CONDITION',
  L11M_BEHAVIOR_RESOLUTION_ORDER_VIOLATED = 'L11M_BEHAVIOR_RESOLUTION_ORDER_VIOLATED',

  // ── Visibility law (§11.5.5.3 / INV-11.5-C) ──
  L11M_VISIBILITY_CLASS_MISSING = 'L11M_VISIBILITY_CLASS_MISSING',
  L11M_VISIBILITY_CLASS_INCONSISTENT = 'L11M_VISIBILITY_CLASS_INCONSISTENT',
  L11M_BLOCKED_VISIBILITY_EMITTED = 'L11M_BLOCKED_VISIBILITY_EMITTED',
  L11M_READINESS_EFFECT_INCONSISTENT = 'L11M_READINESS_EFFECT_INCONSISTENT',

  // ── Regime modifier law (§11.5.9 / INV-11.5-D, E) ──
  L11M_REGIME_MODIFIER_ID_MISSING = 'L11M_REGIME_MODIFIER_ID_MISSING',
  L11M_REGIME_MODIFIER_SCORE_REF_MISSING = 'L11M_REGIME_MODIFIER_SCORE_REF_MISSING',
  L11M_REGIME_MODIFIER_WITHOUT_L8_REF = 'L11M_REGIME_MODIFIER_WITHOUT_L8_REF',
  L11M_REGIME_MODIFIER_STALE_REF = 'L11M_REGIME_MODIFIER_STALE_REF',
  L11M_REGIME_MODIFIER_PRIMARY_REGIME_UNKNOWN = 'L11M_REGIME_MODIFIER_PRIMARY_REGIME_UNKNOWN',
  L11M_REGIME_MODIFIER_STRENGTH_OUT_OF_BOUNDS = 'L11M_REGIME_MODIFIER_STRENGTH_OUT_OF_BOUNDS',
  L11M_REGIME_MODIFIER_MULTIPLIER_OUT_OF_BOUNDS = 'L11M_REGIME_MODIFIER_MULTIPLIER_OUT_OF_BOUNDS',
  L11M_REGIME_MODIFIER_HIGH_IMPACT_REASON_MISSING = 'L11M_REGIME_MODIFIER_HIGH_IMPACT_REASON_MISSING',
  L11M_REGIME_MODIFIER_AFFECTED_COMPONENTS_MISSING = 'L11M_REGIME_MODIFIER_AFFECTED_COMPONENTS_MISSING',
  L11M_REGIME_MODIFIER_REASON_CODES_MISSING = 'L11M_REGIME_MODIFIER_REASON_CODES_MISSING',
  L11M_REGIME_MODIFIER_LINEAGE_MISSING = 'L11M_REGIME_MODIFIER_LINEAGE_MISSING',
  L11M_REGIME_MODIFIER_DIRECTION_FLIP = 'L11M_REGIME_MODIFIER_DIRECTION_FLIP',
  L11M_REGIME_OVERRIDES_CONTRADICTION = 'L11M_REGIME_OVERRIDES_CONTRADICTION',
  L11M_REGIME_OVERRIDES_L10_RESTRICTION = 'L11M_REGIME_OVERRIDES_L10_RESTRICTION',
  L11M_MODIFIER_ACTS_AS_JUDGMENT = 'L11M_MODIFIER_ACTS_AS_JUDGMENT',
  L11M_MODIFIER_NOT_ATTRIBUTED = 'L11M_MODIFIER_NOT_ATTRIBUTED',
  L11M_REGIME_MODIFIER_OUTSIDE_MATRIX = 'L11M_REGIME_MODIFIER_OUTSIDE_MATRIX',
  L11M_REGIME_MODIFIER_HARD_CAP_VIOLATED = 'L11M_REGIME_MODIFIER_HARD_CAP_VIOLATED',

  // ── Missing-regime interaction law (§11.5.12 / INV-11.5-F) ──
  L11M_MISSING_REGIME_INTERACTION_OMITTED = 'L11M_MISSING_REGIME_INTERACTION_OMITTED',
  L11M_INTERACTION_CLASS_MISSING = 'L11M_INTERACTION_CLASS_MISSING',
  L11M_INTERACTION_LACKS_REASON_CODES = 'L11M_INTERACTION_LACKS_REASON_CODES',
  L11M_INTERACTION_LACKS_DISCLOSURE = 'L11M_INTERACTION_LACKS_DISCLOSURE',

  // ── Replay law (§11.5.15 / INV-11.5-H) ──
  L11M_REPLAY_HASH_MISSING = 'L11M_REPLAY_HASH_MISSING',
  L11M_REPLAY_HASH_MISMATCH = 'L11M_REPLAY_HASH_MISMATCH',

  // ── Attribution linkage (INV-11.5-G) ──
  L11M_MATERIAL_MISSING_NOT_ATTRIBUTED = 'L11M_MATERIAL_MISSING_NOT_ATTRIBUTED',
  L11M_MATERIAL_REGIME_MOD_NOT_ATTRIBUTED = 'L11M_MATERIAL_REGIME_MOD_NOT_ATTRIBUTED',
}

export const ALL_L11_MISSING_REGIME_VIOLATION_CODES:
  readonly L11MissingRegimeViolationCode[] =
  Object.values(L11MissingRegimeViolationCode);

export type L11MissingRegimeSeverity =
  | 'INFO' | 'WARNING' | 'ERROR' | 'CRITICAL';

const SEVERITY_MAP:
  Readonly<Record<L11MissingRegimeViolationCode, L11MissingRegimeSeverity>> = {
  // CRITICAL
  [L11MissingRegimeViolationCode.L11M_MISSING_DATA_PROFILE_ABSENT]: 'CRITICAL',
  [L11MissingRegimeViolationCode.L11M_REQUIRED_INPUT_MISSING_BUT_NEUTRAL]: 'CRITICAL',
  [L11MissingRegimeViolationCode.L11M_STALE_INPUT_USED_AS_CURRENT]: 'CRITICAL',
  [L11MissingRegimeViolationCode.L11M_DEGRADED_INPUT_USED_AS_FULL_SUPPORT]: 'CRITICAL',
  [L11MissingRegimeViolationCode.L11M_EVIDENCE_ONLY_INPUT_USED_DECISIVELY]: 'CRITICAL',
  [L11MissingRegimeViolationCode.L11M_RESTRICTED_INPUT_USED_BEYOND_RIGHTS]: 'CRITICAL',
  [L11MissingRegimeViolationCode.L11M_CONFLICTING_INPUT_INCREASES_CONFIDENCE]: 'CRITICAL',
  [L11MissingRegimeViolationCode.L11M_BLOCKED_VISIBILITY_EMITTED]: 'CRITICAL',
  [L11MissingRegimeViolationCode.L11M_REGIME_MODIFIER_WITHOUT_L8_REF]: 'CRITICAL',
  [L11MissingRegimeViolationCode.L11M_REGIME_MODIFIER_STALE_REF]: 'CRITICAL',
  [L11MissingRegimeViolationCode.L11M_REGIME_OVERRIDES_CONTRADICTION]: 'CRITICAL',
  [L11MissingRegimeViolationCode.L11M_REGIME_OVERRIDES_L10_RESTRICTION]: 'CRITICAL',
  [L11MissingRegimeViolationCode.L11M_REGIME_MODIFIER_DIRECTION_FLIP]: 'CRITICAL',
  [L11MissingRegimeViolationCode.L11M_MODIFIER_ACTS_AS_JUDGMENT]: 'CRITICAL',
  [L11MissingRegimeViolationCode.L11M_REPLAY_HASH_MISSING]: 'CRITICAL',
  [L11MissingRegimeViolationCode.L11M_REPLAY_HASH_MISMATCH]: 'CRITICAL',
  [L11MissingRegimeViolationCode.L11M_REGIME_MODIFIER_HARD_CAP_VIOLATED]: 'CRITICAL',

  // ERROR
  [L11MissingRegimeViolationCode.L11M_MISSING_PROFILE_ID_MISSING]: 'ERROR',
  [L11MissingRegimeViolationCode.L11M_MISSING_PROFILE_SCORE_REF_MISSING]: 'ERROR',
  [L11MissingRegimeViolationCode.L11M_MISSING_PROFILE_FORMULA_REF_MISSING]: 'ERROR',
  [L11MissingRegimeViolationCode.L11M_MISSING_PROFILE_FORMULA_VERSION_MISSING]: 'ERROR',
  [L11MissingRegimeViolationCode.L11M_MISSING_PROFILE_SCOPE_FIELDS_MISSING]: 'ERROR',
  [L11MissingRegimeViolationCode.L11M_MISSING_PROFILE_AS_OF_MISSING]: 'ERROR',
  [L11MissingRegimeViolationCode.L11M_MISSING_PROFILE_INPUT_SNAPSHOT_REF_MISSING]: 'ERROR',
  [L11MissingRegimeViolationCode.L11M_MISSING_PROFILE_LINEAGE_REFS_MISSING]: 'ERROR',
  [L11MissingRegimeViolationCode.L11M_MISSING_PROFILE_POLICY_VERSION_MISSING]: 'ERROR',
  [L11MissingRegimeViolationCode.L11M_INPUT_REF_ID_MISSING]: 'ERROR',
  [L11MissingRegimeViolationCode.L11M_INPUT_SURFACE_REF_MISSING]: 'ERROR',
  [L11MissingRegimeViolationCode.L11M_INPUT_SOURCE_LAYER_MISSING]: 'ERROR',
  [L11MissingRegimeViolationCode.L11M_INPUT_DEPENDENCY_CLASS_MISSING]: 'ERROR',
  [L11MissingRegimeViolationCode.L11M_INPUT_CONDITION_CLASS_MISSING]: 'ERROR',
  [L11MissingRegimeViolationCode.L11M_REQUIRED_INPUT_LACKS_COMPONENT_REFS]: 'ERROR',
  [L11MissingRegimeViolationCode.L11M_STALE_INPUT_LACKS_FRESHNESS_DATA]: 'ERROR',
  [L11MissingRegimeViolationCode.L11M_DEGRADED_INPUT_LACKS_REASON]: 'ERROR',
  [L11MissingRegimeViolationCode.L11M_RESTRICTED_INPUT_LACKS_RESTRICTION_REFS]: 'ERROR',
  [L11MissingRegimeViolationCode.L11M_CONFLICTING_INPUT_LACKS_CONTRADICTION_REFS]: 'ERROR',
  [L11MissingRegimeViolationCode.L11M_INPUT_REF_LINEAGE_MISSING]: 'ERROR',
  [L11MissingRegimeViolationCode.L11M_INSUFFICIENT_SET_INVALID]: 'ERROR',
  [L11MissingRegimeViolationCode.L11M_BEHAVIOR_ABSENT_FOR_INPUT_CONDITION]: 'ERROR',
  [L11MissingRegimeViolationCode.L11M_BEHAVIOR_ILLEGAL_FOR_CONDITION]: 'ERROR',
  [L11MissingRegimeViolationCode.L11M_BEHAVIOR_RESOLUTION_ORDER_VIOLATED]: 'ERROR',
  [L11MissingRegimeViolationCode.L11M_VISIBILITY_CLASS_MISSING]: 'ERROR',
  [L11MissingRegimeViolationCode.L11M_VISIBILITY_CLASS_INCONSISTENT]: 'ERROR',
  [L11MissingRegimeViolationCode.L11M_READINESS_EFFECT_INCONSISTENT]: 'ERROR',
  [L11MissingRegimeViolationCode.L11M_REGIME_MODIFIER_ID_MISSING]: 'ERROR',
  [L11MissingRegimeViolationCode.L11M_REGIME_MODIFIER_SCORE_REF_MISSING]: 'ERROR',
  [L11MissingRegimeViolationCode.L11M_REGIME_MODIFIER_PRIMARY_REGIME_UNKNOWN]: 'ERROR',
  [L11MissingRegimeViolationCode.L11M_REGIME_MODIFIER_STRENGTH_OUT_OF_BOUNDS]: 'ERROR',
  [L11MissingRegimeViolationCode.L11M_REGIME_MODIFIER_MULTIPLIER_OUT_OF_BOUNDS]: 'ERROR',
  [L11MissingRegimeViolationCode.L11M_REGIME_MODIFIER_HIGH_IMPACT_REASON_MISSING]: 'ERROR',
  [L11MissingRegimeViolationCode.L11M_REGIME_MODIFIER_AFFECTED_COMPONENTS_MISSING]: 'ERROR',
  [L11MissingRegimeViolationCode.L11M_REGIME_MODIFIER_REASON_CODES_MISSING]: 'ERROR',
  [L11MissingRegimeViolationCode.L11M_REGIME_MODIFIER_LINEAGE_MISSING]: 'ERROR',
  [L11MissingRegimeViolationCode.L11M_MODIFIER_NOT_ATTRIBUTED]: 'ERROR',
  [L11MissingRegimeViolationCode.L11M_REGIME_MODIFIER_OUTSIDE_MATRIX]: 'ERROR',
  [L11MissingRegimeViolationCode.L11M_INTERACTION_CLASS_MISSING]: 'ERROR',
  [L11MissingRegimeViolationCode.L11M_INTERACTION_LACKS_REASON_CODES]: 'ERROR',
  [L11MissingRegimeViolationCode.L11M_INTERACTION_LACKS_DISCLOSURE]: 'ERROR',
  [L11MissingRegimeViolationCode.L11M_MATERIAL_MISSING_NOT_ATTRIBUTED]: 'ERROR',
  [L11MissingRegimeViolationCode.L11M_MATERIAL_REGIME_MOD_NOT_ATTRIBUTED]: 'ERROR',
  [L11MissingRegimeViolationCode.L11M_MISSING_REGIME_INTERACTION_OMITTED]: 'ERROR',
};

export function severityForL11MissingRegimeCode(
  code: L11MissingRegimeViolationCode,
): L11MissingRegimeSeverity {
  return SEVERITY_MAP[code] ?? 'WARNING';
}

export interface L11MissingRegimeIssue {
  readonly code: L11MissingRegimeViolationCode;
  readonly severity: L11MissingRegimeSeverity;
  readonly message: string;
  readonly subject_ref?: string;
  readonly score_id?: string;
  readonly score_family?: string;
  readonly missing_profile_id?: string;
  readonly modifier_id?: string;
  readonly interaction_id?: string;
  readonly input_ref_id?: string;
}

export function makeL11MissingRegimeIssue(
  code: L11MissingRegimeViolationCode,
  message: string,
  ctx: Partial<Omit<L11MissingRegimeIssue, 'code' | 'severity' | 'message'>> = {},
): L11MissingRegimeIssue {
  return {
    code,
    severity: severityForL11MissingRegimeCode(code),
    message,
    ...ctx,
  };
}
