/**
 * L11.7 — Drift Violation Codes (§11.7.17.1)
 *
 * Disjoint `L11G_` namespace so drift / threshold / formula-change
 * governance violations never collide with L11.1 (L11_) /
 * L11.2 (L11D_) / L11.3 (L11F_) / L11.4 (L11A_) / L11.5 (L11M_) /
 * L11.6 (L11C_) codes.
 */

export enum L11DriftViolationCode {
  // ── Drift report identity & structure (§11.7.7) ──
  L11G_DRIFT_REPORT_ID_MISSING = 'L11G_DRIFT_REPORT_ID_MISSING',
  L11G_DRIFT_REPORT_INCOMPLETE = 'L11G_DRIFT_REPORT_INCOMPLETE',
  L11G_DRIFT_TYPE_MISSING = 'L11G_DRIFT_TYPE_MISSING',
  L11G_DRIFT_TYPE_UNKNOWN = 'L11G_DRIFT_TYPE_UNKNOWN',
  L11G_DRIFT_SEVERITY_MISSING = 'L11G_DRIFT_SEVERITY_MISSING',
  L11G_DRIFT_SEVERITY_UNKNOWN = 'L11G_DRIFT_SEVERITY_UNKNOWN',
  L11G_DRIFT_SCORE_FAMILY_MISSING = 'L11G_DRIFT_SCORE_FAMILY_MISSING',
  L11G_DRIFT_FORMULA_VERSION_MISSING = 'L11G_DRIFT_FORMULA_VERSION_MISSING',
  L11G_DRIFT_SCORE_VERSION_MISSING = 'L11G_DRIFT_SCORE_VERSION_MISSING',
  L11G_DRIFT_COHORT_REF_MISSING = 'L11G_DRIFT_COHORT_REF_MISSING',
  L11G_OBSERVATION_WINDOW_MISSING = 'L11G_OBSERVATION_WINDOW_MISSING',
  L11G_BASELINE_WINDOW_MISSING = 'L11G_BASELINE_WINDOW_MISSING',
  L11G_OBSERVED_CHANGE_MISSING = 'L11G_OBSERVED_CHANGE_MISSING',
  L11G_EXPECTED_BASELINE_MISSING = 'L11G_EXPECTED_BASELINE_MISSING',
  L11G_BASELINE_VERSION_MISSING = 'L11G_BASELINE_VERSION_MISSING',
  L11G_DRIFT_LINEAGE_MISSING = 'L11G_DRIFT_LINEAGE_MISSING',
  L11G_DRIFT_POLICY_VERSION_MISSING = 'L11G_DRIFT_POLICY_VERSION_MISSING',

  // ── Drift statistic law (§11.7.9) ──
  L11G_STATISTIC_TYPE_UNKNOWN = 'L11G_STATISTIC_TYPE_UNKNOWN',
  L11G_STATISTIC_VALUE_INVALID = 'L11G_STATISTIC_VALUE_INVALID',
  L11G_STATISTIC_THRESHOLD_INVALID = 'L11G_STATISTIC_THRESHOLD_INVALID',
  L11G_STATISTIC_DIRECTION_MISSING = 'L11G_STATISTIC_DIRECTION_MISSING',
  L11G_STATISTIC_PASSED_INCONSISTENT = 'L11G_STATISTIC_PASSED_INCONSISTENT',
  L11G_SAMPLE_SIZE_INVALID = 'L11G_SAMPLE_SIZE_INVALID',
  L11G_SAMPLE_SIZE_INSUFFICIENT = 'L11G_SAMPLE_SIZE_INSUFFICIENT',
  L11G_CONFIDENCE_CLASS_MISSING = 'L11G_CONFIDENCE_CLASS_MISSING',
  L11G_CONFIDENCE_CLASS_INCONSISTENT_WITH_SAMPLE = 'L11G_CONFIDENCE_CLASS_INCONSISTENT_WITH_SAMPLE',
  L11G_HIGH_SEVERITY_FROM_INSUFFICIENT_SAMPLE = 'L11G_HIGH_SEVERITY_FROM_INSUFFICIENT_SAMPLE',

  // ── Severity / action consistency (§11.7.10) ──
  L11G_RECOMMENDED_ACTION_MISSING = 'L11G_RECOMMENDED_ACTION_MISSING',
  L11G_RECOMMENDED_ACTION_INCOMPATIBLE_WITH_SEVERITY = 'L11G_RECOMMENDED_ACTION_INCOMPATIBLE_WITH_SEVERITY',
  L11G_CRITICAL_DRIFT_WITH_NO_ACTION = 'L11G_CRITICAL_DRIFT_WITH_NO_ACTION',
  L11G_SEVERE_CALIBRATION_DRIFT_PASSIVE_ACTION = 'L11G_SEVERE_CALIBRATION_DRIFT_PASSIVE_ACTION',
  L11G_THRESHOLD_DRIFT_NO_THRESHOLD_ACTION = 'L11G_THRESHOLD_DRIFT_NO_THRESHOLD_ACTION',
  L11G_STRUCTURAL_DRIFT_NO_MIGRATION_ACTION = 'L11G_STRUCTURAL_DRIFT_NO_MIGRATION_ACTION',

  // ── Threshold governance (§11.7.11 / §11.7.12) ──
  L11G_THRESHOLD_POLICY_ID_MISSING = 'L11G_THRESHOLD_POLICY_ID_MISSING',
  L11G_THRESHOLD_POLICY_GAP = 'L11G_THRESHOLD_POLICY_GAP',
  L11G_THRESHOLD_POLICY_OVERLAP = 'L11G_THRESHOLD_POLICY_OVERLAP',
  L11G_THRESHOLD_POLICY_BOUNDARY_AMBIGUOUS = 'L11G_THRESHOLD_POLICY_BOUNDARY_AMBIGUOUS',
  L11G_THRESHOLD_POLICY_DOES_NOT_COVER_FULL_RANGE = 'L11G_THRESHOLD_POLICY_DOES_NOT_COVER_FULL_RANGE',
  L11G_THRESHOLD_VERSION_MISSING = 'L11G_THRESHOLD_VERSION_MISSING',
  L11G_THRESHOLD_FORMULA_VERSION_MISSING = 'L11G_THRESHOLD_FORMULA_VERSION_MISSING',
  L11G_THRESHOLD_SCORE_FAMILY_MISSING = 'L11G_THRESHOLD_SCORE_FAMILY_MISSING',
  L11G_THRESHOLD_SEMANTIC_LABEL_MISSING = 'L11G_THRESHOLD_SEMANTIC_LABEL_MISSING',
  L11G_THRESHOLD_DUPLICATE_BAND = 'L11G_THRESHOLD_DUPLICATE_BAND',
  L11G_ACTIVE_THRESHOLD_LACKS_CALIBRATION_TARGET = 'L11G_ACTIVE_THRESHOLD_LACKS_CALIBRATION_TARGET',
  L11G_ACTIVE_THRESHOLD_LACKS_REPLAY_HASH = 'L11G_ACTIVE_THRESHOLD_LACKS_REPLAY_HASH',
  L11G_THRESHOLD_REPLAY_HASH_MISSING = 'L11G_THRESHOLD_REPLAY_HASH_MISSING',
  L11G_THRESHOLD_REPLAY_HASH_MISMATCH = 'L11G_THRESHOLD_REPLAY_HASH_MISMATCH',
  L11G_THRESHOLD_CHANGE_UNCLASSIFIED = 'L11G_THRESHOLD_CHANGE_UNCLASSIFIED',
  L11G_THRESHOLD_CHANGE_PROHIBITED = 'L11G_THRESHOLD_CHANGE_PROHIBITED',
  L11G_THRESHOLD_CHANGE_REQUIRES_VERSION_BUMP = 'L11G_THRESHOLD_CHANGE_REQUIRES_VERSION_BUMP',
  L11G_THRESHOLD_CHANGE_REQUIRES_MIGRATION = 'L11G_THRESHOLD_CHANGE_REQUIRES_MIGRATION',
  L11G_THRESHOLD_CHANGE_HISTORICAL_AMBIGUITY = 'L11G_THRESHOLD_CHANGE_HISTORICAL_AMBIGUITY',

  // ── Formula change (§11.7.13) ──
  L11G_FORMULA_CHANGE_ID_MISSING = 'L11G_FORMULA_CHANGE_ID_MISSING',
  L11G_FORMULA_CHANGE_OLD_REF_MISSING = 'L11G_FORMULA_CHANGE_OLD_REF_MISSING',
  L11G_FORMULA_CHANGE_NEW_REF_MISSING = 'L11G_FORMULA_CHANGE_NEW_REF_MISSING',
  L11G_FORMULA_CHANGE_FAMILY_MISMATCH = 'L11G_FORMULA_CHANGE_FAMILY_MISMATCH',
  L11G_FORMULA_CHANGE_NO_SURFACES = 'L11G_FORMULA_CHANGE_NO_SURFACES',
  L11G_FORMULA_CHANGE_NO_REASONS = 'L11G_FORMULA_CHANGE_NO_REASONS',
  L11G_FORMULA_CHANGE_UNCLASSIFIED = 'L11G_FORMULA_CHANGE_UNCLASSIFIED',
  L11G_FORMULA_CHANGE_PROHIBITED = 'L11G_FORMULA_CHANGE_PROHIBITED',
  L11G_FORMULA_CHANGE_REQUIRES_MIGRATION = 'L11G_FORMULA_CHANGE_REQUIRES_MIGRATION',
  L11G_FORMULA_CHANGE_REQUIRES_RECALIBRATION = 'L11G_FORMULA_CHANGE_REQUIRES_RECALIBRATION',
  L11G_FORMULA_CHANGE_BACKFILL_REQUIRED = 'L11G_FORMULA_CHANGE_BACKFILL_REQUIRED',
  L11G_FORMULA_CHANGE_REPLAY_HASH_MISSING = 'L11G_FORMULA_CHANGE_REPLAY_HASH_MISSING',
  L11G_FORMULA_CHANGE_REPLAY_HASH_MISMATCH = 'L11G_FORMULA_CHANGE_REPLAY_HASH_MISMATCH',
  L11G_MEANING_CHANGE_SILENT = 'L11G_MEANING_CHANGE_SILENT',
  L11G_DIRECTION_CHANGE_PROHIBITED = 'L11G_DIRECTION_CHANGE_PROHIBITED',
  L11G_OLD_FORMULA_OVERWRITTEN = 'L11G_OLD_FORMULA_OVERWRITTEN',
  L11G_HISTORICAL_REINTERPRETATION = 'L11G_HISTORICAL_REINTERPRETATION',

  // ── Boundary law (§11.7.3) ──
  L11G_DRIFT_ACTS_AS_JUDGMENT = 'L11G_DRIFT_ACTS_AS_JUDGMENT',
  L11G_DRIFT_OVERRIDES_MEANING_LAW = 'L11G_DRIFT_OVERRIDES_MEANING_LAW',
  L11G_DRIFT_OVERRIDES_FORMULA_LAW = 'L11G_DRIFT_OVERRIDES_FORMULA_LAW',
  L11G_DRIFT_OVERRIDES_CALIBRATION_TARGET_LAW = 'L11G_DRIFT_OVERRIDES_CALIBRATION_TARGET_LAW',

  // ── Replay law (§11.7.18) ──
  L11G_REPLAY_HASH_MISSING = 'L11G_REPLAY_HASH_MISSING',
  L11G_REPLAY_HASH_MISMATCH = 'L11G_REPLAY_HASH_MISMATCH',
}

export type L11DriftSeverityClass = 'CRITICAL' | 'ERROR' | 'WARNING';

const SEVERITY_MAP:
  Readonly<Record<L11DriftViolationCode, L11DriftSeverityClass>> = {
  // CRITICAL ──────────────────────────────────────────────────
  [L11DriftViolationCode.L11G_CRITICAL_DRIFT_WITH_NO_ACTION]: 'CRITICAL',
  [L11DriftViolationCode.L11G_SEVERE_CALIBRATION_DRIFT_PASSIVE_ACTION]: 'CRITICAL',
  [L11DriftViolationCode.L11G_STRUCTURAL_DRIFT_NO_MIGRATION_ACTION]: 'CRITICAL',
  [L11DriftViolationCode.L11G_THRESHOLD_CHANGE_PROHIBITED]: 'CRITICAL',
  [L11DriftViolationCode.L11G_THRESHOLD_CHANGE_HISTORICAL_AMBIGUITY]: 'CRITICAL',
  [L11DriftViolationCode.L11G_FORMULA_CHANGE_PROHIBITED]: 'CRITICAL',
  [L11DriftViolationCode.L11G_MEANING_CHANGE_SILENT]: 'CRITICAL',
  [L11DriftViolationCode.L11G_DIRECTION_CHANGE_PROHIBITED]: 'CRITICAL',
  [L11DriftViolationCode.L11G_OLD_FORMULA_OVERWRITTEN]: 'CRITICAL',
  [L11DriftViolationCode.L11G_HISTORICAL_REINTERPRETATION]: 'CRITICAL',
  [L11DriftViolationCode.L11G_DRIFT_ACTS_AS_JUDGMENT]: 'CRITICAL',
  [L11DriftViolationCode.L11G_DRIFT_OVERRIDES_MEANING_LAW]: 'CRITICAL',
  [L11DriftViolationCode.L11G_DRIFT_OVERRIDES_FORMULA_LAW]: 'CRITICAL',
  [L11DriftViolationCode.L11G_DRIFT_OVERRIDES_CALIBRATION_TARGET_LAW]: 'CRITICAL',
  [L11DriftViolationCode.L11G_HIGH_SEVERITY_FROM_INSUFFICIENT_SAMPLE]: 'CRITICAL',
  [L11DriftViolationCode.L11G_REPLAY_HASH_MISMATCH]: 'CRITICAL',
  [L11DriftViolationCode.L11G_THRESHOLD_REPLAY_HASH_MISMATCH]: 'CRITICAL',
  [L11DriftViolationCode.L11G_FORMULA_CHANGE_REPLAY_HASH_MISMATCH]: 'CRITICAL',

  // ERROR ─────────────────────────────────────────────────────
  [L11DriftViolationCode.L11G_DRIFT_REPORT_ID_MISSING]: 'ERROR',
  [L11DriftViolationCode.L11G_DRIFT_REPORT_INCOMPLETE]: 'ERROR',
  [L11DriftViolationCode.L11G_DRIFT_TYPE_MISSING]: 'ERROR',
  [L11DriftViolationCode.L11G_DRIFT_TYPE_UNKNOWN]: 'ERROR',
  [L11DriftViolationCode.L11G_DRIFT_SEVERITY_MISSING]: 'ERROR',
  [L11DriftViolationCode.L11G_DRIFT_SEVERITY_UNKNOWN]: 'ERROR',
  [L11DriftViolationCode.L11G_DRIFT_SCORE_FAMILY_MISSING]: 'ERROR',
  [L11DriftViolationCode.L11G_DRIFT_FORMULA_VERSION_MISSING]: 'ERROR',
  [L11DriftViolationCode.L11G_DRIFT_SCORE_VERSION_MISSING]: 'ERROR',
  [L11DriftViolationCode.L11G_DRIFT_COHORT_REF_MISSING]: 'ERROR',
  [L11DriftViolationCode.L11G_OBSERVATION_WINDOW_MISSING]: 'ERROR',
  [L11DriftViolationCode.L11G_BASELINE_WINDOW_MISSING]: 'ERROR',
  [L11DriftViolationCode.L11G_OBSERVED_CHANGE_MISSING]: 'ERROR',
  [L11DriftViolationCode.L11G_EXPECTED_BASELINE_MISSING]: 'ERROR',
  [L11DriftViolationCode.L11G_BASELINE_VERSION_MISSING]: 'ERROR',
  [L11DriftViolationCode.L11G_DRIFT_LINEAGE_MISSING]: 'ERROR',
  [L11DriftViolationCode.L11G_DRIFT_POLICY_VERSION_MISSING]: 'ERROR',
  [L11DriftViolationCode.L11G_STATISTIC_TYPE_UNKNOWN]: 'ERROR',
  [L11DriftViolationCode.L11G_STATISTIC_VALUE_INVALID]: 'ERROR',
  [L11DriftViolationCode.L11G_STATISTIC_THRESHOLD_INVALID]: 'ERROR',
  [L11DriftViolationCode.L11G_STATISTIC_DIRECTION_MISSING]: 'ERROR',
  [L11DriftViolationCode.L11G_STATISTIC_PASSED_INCONSISTENT]: 'ERROR',
  [L11DriftViolationCode.L11G_SAMPLE_SIZE_INVALID]: 'ERROR',
  [L11DriftViolationCode.L11G_SAMPLE_SIZE_INSUFFICIENT]: 'ERROR',
  [L11DriftViolationCode.L11G_CONFIDENCE_CLASS_MISSING]: 'ERROR',
  [L11DriftViolationCode.L11G_CONFIDENCE_CLASS_INCONSISTENT_WITH_SAMPLE]: 'ERROR',
  [L11DriftViolationCode.L11G_RECOMMENDED_ACTION_MISSING]: 'ERROR',
  [L11DriftViolationCode.L11G_RECOMMENDED_ACTION_INCOMPATIBLE_WITH_SEVERITY]: 'ERROR',
  [L11DriftViolationCode.L11G_THRESHOLD_DRIFT_NO_THRESHOLD_ACTION]: 'ERROR',
  [L11DriftViolationCode.L11G_THRESHOLD_POLICY_ID_MISSING]: 'ERROR',
  [L11DriftViolationCode.L11G_THRESHOLD_POLICY_GAP]: 'ERROR',
  [L11DriftViolationCode.L11G_THRESHOLD_POLICY_OVERLAP]: 'ERROR',
  [L11DriftViolationCode.L11G_THRESHOLD_POLICY_BOUNDARY_AMBIGUOUS]: 'ERROR',
  [L11DriftViolationCode.L11G_THRESHOLD_POLICY_DOES_NOT_COVER_FULL_RANGE]: 'ERROR',
  [L11DriftViolationCode.L11G_THRESHOLD_VERSION_MISSING]: 'ERROR',
  [L11DriftViolationCode.L11G_THRESHOLD_FORMULA_VERSION_MISSING]: 'ERROR',
  [L11DriftViolationCode.L11G_THRESHOLD_SCORE_FAMILY_MISSING]: 'ERROR',
  [L11DriftViolationCode.L11G_THRESHOLD_SEMANTIC_LABEL_MISSING]: 'ERROR',
  [L11DriftViolationCode.L11G_THRESHOLD_DUPLICATE_BAND]: 'ERROR',
  [L11DriftViolationCode.L11G_ACTIVE_THRESHOLD_LACKS_CALIBRATION_TARGET]: 'ERROR',
  [L11DriftViolationCode.L11G_ACTIVE_THRESHOLD_LACKS_REPLAY_HASH]: 'ERROR',
  [L11DriftViolationCode.L11G_THRESHOLD_REPLAY_HASH_MISSING]: 'ERROR',
  [L11DriftViolationCode.L11G_THRESHOLD_CHANGE_UNCLASSIFIED]: 'ERROR',
  [L11DriftViolationCode.L11G_THRESHOLD_CHANGE_REQUIRES_VERSION_BUMP]: 'ERROR',
  [L11DriftViolationCode.L11G_THRESHOLD_CHANGE_REQUIRES_MIGRATION]: 'ERROR',
  [L11DriftViolationCode.L11G_FORMULA_CHANGE_ID_MISSING]: 'ERROR',
  [L11DriftViolationCode.L11G_FORMULA_CHANGE_OLD_REF_MISSING]: 'ERROR',
  [L11DriftViolationCode.L11G_FORMULA_CHANGE_NEW_REF_MISSING]: 'ERROR',
  [L11DriftViolationCode.L11G_FORMULA_CHANGE_FAMILY_MISMATCH]: 'ERROR',
  [L11DriftViolationCode.L11G_FORMULA_CHANGE_NO_SURFACES]: 'ERROR',
  [L11DriftViolationCode.L11G_FORMULA_CHANGE_NO_REASONS]: 'ERROR',
  [L11DriftViolationCode.L11G_FORMULA_CHANGE_UNCLASSIFIED]: 'ERROR',
  [L11DriftViolationCode.L11G_FORMULA_CHANGE_REQUIRES_MIGRATION]: 'ERROR',
  [L11DriftViolationCode.L11G_FORMULA_CHANGE_REQUIRES_RECALIBRATION]: 'ERROR',
  [L11DriftViolationCode.L11G_FORMULA_CHANGE_BACKFILL_REQUIRED]: 'ERROR',
  [L11DriftViolationCode.L11G_FORMULA_CHANGE_REPLAY_HASH_MISSING]: 'ERROR',
  [L11DriftViolationCode.L11G_REPLAY_HASH_MISSING]: 'ERROR',
};

export function severityForL11DriftCode(
  code: L11DriftViolationCode,
): L11DriftSeverityClass {
  return SEVERITY_MAP[code] ?? 'WARNING';
}

export interface L11DriftIssue {
  readonly code: L11DriftViolationCode;
  readonly severity: L11DriftSeverityClass;
  readonly message: string;
  readonly subject_ref?: string;
  readonly drift_report_id?: string;
  readonly threshold_policy_id?: string;
  readonly formula_change_assessment_id?: string;
  readonly statistic_id?: string;
  readonly score_family?: string;
}

export function makeL11DriftIssue(
  code: L11DriftViolationCode,
  message: string,
  ctx: Partial<Omit<L11DriftIssue, 'code' | 'severity' | 'message'>> = {},
): L11DriftIssue {
  return { code, severity: severityForL11DriftCode(code), message, ...ctx };
}

export const ALL_L11_DRIFT_VIOLATION_CODES:
  readonly L11DriftViolationCode[] = Object.values(L11DriftViolationCode);
