/**
 * ╔═══════════════════════════════════════════════════════════════════════════════╗
 * ║     🏛️ CIS LAYER 7 - EXPLANATION OBJECTS                                     ║
 * ║                                                                               ║
 * ║   THE SOURCE OF TRUTH CONTRACT                                               ║
 * ║                                                                               ║
 * ║   "The Explanation Object (EO) is a mathematically verifiable structured     ║
 * ║    data package generated by the fully validated data pipeline (Layers 1-6). ║
 * ║    The EO is the ONLY input source from which the Coinet AI is permitted     ║
 * ║    to generate narrative."                                                   ║
 * ║                                                                               ║
 * ║   This transforms the AI from a potentially autonomous "agent" into a        ║
 * ║   verifiable "strict renderer".                                              ║
 * ╚═══════════════════════════════════════════════════════════════════════════════╝
 */

import { z } from 'zod';

// ═══════════════════════════════════════════════════════════════════════════════
// VERSION
// ═══════════════════════════════════════════════════════════════════════════════

export const CIS_LAYER7_VERSION = '1.0.0' as const;
export const EO_SCHEMA_VERSION = 'EO-v1.0' as const;

// ═══════════════════════════════════════════════════════════════════════════════
// CLAIM TYPES (THE ATOMIC UNIT OF TRUTH)
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * A single factual claim that can be asserted in the narrative
 * 
 * MANDATE: The Coinet AI is FORBIDDEN from asserting any numeric statement
 * or fact that is not mathematically present within the claims array.
 */
export const ClaimSchema = z.object({
  /** Unique claim identifier */
  claim_id: z.string(),
  
  /** Canonical metric ID (links to Layer 1) */
  metric_id: z.string(),
  
  /** Human-readable metric name */
  metric_name: z.string(),
  
  /** Raw value before normalization */
  raw_value: z.number(),
  
  /** Normalized value used for scoring (0-100) */
  normalized_value: z.number().min(0).max(100),
  
  /** Unit of the raw value */
  unit: z.string(),
  
  /** Reconciled/audited source identity (from Layer 3) */
  source_id: z.string(),
  
  /** Additional sources that agreed (if multi-source) */
  corroborating_sources: z.array(z.string()),
  
  /** Observation timestamp (ISO 8601) */
  timestamp: z.string().datetime(),
  
  /** Data age at time of EO generation (seconds) */
  data_age_seconds: z.number().int().min(0),
  
  /** Direction: how this metric affects the score */
  direction: z.enum(['higher_is_better', 'higher_is_worse', 'neutral']),
  
  /** Score category this claim contributes to */
  score_category: z.enum(['QS', 'OS', 'RISK', 'META']),
  
  /** Validation status from Layer 4 */
  validation_status: z.enum(['PASS', 'WARN', 'FAIL']),
  
  /** Any quality flags */
  quality_flags: z.array(z.string()),
  
  /** Human-readable assertion that can be made from this claim */
  assertion_template: z.string(),
  
  /** Reliability score (0-1) from reconciliation */
  reliability: z.number().min(0).max(1),
});

export type Claim = z.infer<typeof ClaimSchema>;

// ═══════════════════════════════════════════════════════════════════════════════
// DRIVER TYPES (SCORE CONTRIBUTORS)
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * A driver represents a metric's contribution to the overall score
 */
export const DriverSchema = z.object({
  /** Reference to claim_id */
  claim_id: z.string(),
  
  /** Metric ID */
  metric_id: z.string(),
  
  /** Metric name */
  metric_name: z.string(),
  
  /** Contribution to score (positive = helps, negative = hurts) */
  contribution: z.number(),
  
  /** Contribution as percentage of category total */
  contribution_percent: z.number(),
  
  /** Impact direction: positive or negative */
  impact: z.enum(['positive', 'negative', 'neutral']),
  
  /** Brief explanation of why this drives the score */
  explanation: z.string(),
  
  /** Relevance to asset type (from Layer 5) */
  relevance: z.enum(['CRITICAL', 'IMPORTANT', 'RELEVANT', 'OPTIONAL']),
});

export type Driver = z.infer<typeof DriverSchema>;

// ═══════════════════════════════════════════════════════════════════════════════
// WARNING TYPES (RISK FLAGS)
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Warning severity levels
 */
export const WarningSeverityEnum = z.enum([
  'CRITICAL',   // Must be prominently stated
  'HIGH',       // Should be clearly noted
  'MEDIUM',     // Should be mentioned
  'LOW',        // May be mentioned
  'INFO',       // Informational only
]);

export type WarningSeverity = z.infer<typeof WarningSeverityEnum>;

/**
 * A warning from validation/reconciliation layers
 */
export const WarningSchema = z.object({
  /** Warning identifier */
  warning_id: z.string(),
  
  /** Warning type */
  type: z.enum([
    'SUSPICIOUS',           // Potential manipulation
    'DISPUTED',             // Multi-source disagreement
    'STALE',                // Data freshness concern
    'WASH_TRADE_RISK',      // Volume manipulation signal
    'CONCENTRATION_RISK',   // Whale concentration
    'SOCIAL_DIVERGENCE',    // Hype without fundamentals
    'COVERAGE_GAP',         // Missing critical data
    'IDENTITY_UNCERTAIN',   // Asset classification uncertain
    'BEHAVIORAL_ANOMALY',   // Neuroeconomic bias signal
    'DATA_QUALITY',         // General data quality issue
  ]),
  
  /** Severity level */
  severity: WarningSeverityEnum,
  
  /** Human-readable warning message */
  message: z.string(),
  
  /** Affected metrics (if specific) */
  affected_metrics: z.array(z.string()),
  
  /** Evidence supporting this warning */
  evidence: z.record(z.unknown()).optional(),
  
  /** Recommended narrative treatment */
  narrative_treatment: z.enum([
    'PROMINENT_CAUTION',    // Must be stated prominently
    'NOTED_RISK',           // Should be noted as risk
    'CONTEXTUAL_NOTE',      // Add as context
    'SUPPRESS_IF_MINOR',    // Only mention if significant
  ]),
  
  /** Source layer that generated this warning */
  source_layer: z.enum(['LAYER_3', 'LAYER_4', 'LAYER_5', 'LAYER_6']),
});

export type Warning = z.infer<typeof WarningSchema>;

// ═══════════════════════════════════════════════════════════════════════════════
// COVERAGE SUMMARY
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Summary of data coverage and quality
 */
export const CoverageSummarySchema = z.object({
  /** Overall coverage percentage (0-1) */
  overall_coverage: z.number().min(0).max(1),
  
  /** Critical metrics coverage (0-1) */
  critical_coverage: z.number().min(0).max(1),
  
  /** List of missing critical metrics */
  missing_critical_metrics: z.array(z.string()),
  
  /** List of missing important metrics */
  missing_important_metrics: z.array(z.string()),
  
  /** List of disputed metrics */
  disputed_metrics: z.array(z.object({
    metric_id: z.string(),
    agreement_score: z.number(),
    dispute_description: z.string(),
  })),
  
  /** List of stale metrics */
  stale_metrics: z.array(z.object({
    metric_id: z.string(),
    age_seconds: z.number(),
    threshold_seconds: z.number(),
  })),
  
  /** Staleness summary */
  staleness_summary: z.object({
    average_age_seconds: z.number(),
    max_age_seconds: z.number(),
    stale_count: z.number(),
    total_metrics: z.number(),
  }),
  
  /** Source count statistics */
  source_statistics: z.object({
    total_sources: z.number(),
    min_sources_per_metric: z.number(),
    max_sources_per_metric: z.number(),
    avg_sources_per_metric: z.number(),
  }),
});

export type CoverageSummary = z.infer<typeof CoverageSummarySchema>;

// ═══════════════════════════════════════════════════════════════════════════════
// SCORE SUMMARY
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Summary of computed scores
 */
export const ScoreSummarySchema = z.object({
  /** Quality Score */
  qs: z.object({
    value: z.number().min(0).max(100),
    tier: z.string(),
    coverage: z.number().min(0).max(1),
    confidence: z.number().min(0).max(1),
  }),
  
  /** Opportunity Score */
  os: z.object({
    value: z.number().min(0).max(100).nullable(),
    tier: z.string().nullable(),
    coverage: z.number().min(0).max(1),
    confidence: z.number().min(0).max(1),
    gated: z.boolean(),
  }),
  
  /** Risk Score */
  risk: z.object({
    value: z.number().min(0).max(100),
    tier: z.string(),
    coverage: z.number().min(0).max(1),
    confidence: z.number().min(0).max(1),
  }),
  
  /** Final POS (Position Score) */
  pos: z.object({
    raw: z.number().min(0).max(100).nullable(),
    smoothed: z.number().min(0).max(100).nullable(),
    final: z.number().min(0).max(100).nullable(),
    tier: z.string().nullable(),
    gated: z.boolean(),
    gating_reason: z.string().nullable(),
  }),
  
  /** Formula used */
  formula: z.object({
    version: z.string(),
    weights: z.object({
      qs: z.number(),
      os: z.number(),
      safety: z.number(),
    }),
    os_gated_weights: z.object({
      qs: z.number(),
      safety: z.number(),
    }).optional(),
  }),
});

export type ScoreSummary = z.infer<typeof ScoreSummarySchema>;

// ═══════════════════════════════════════════════════════════════════════════════
// ASSET CONTEXT
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Asset classification and context
 */
export const AssetContextSchema = z.object({
  /** Canonical entity ID */
  entity_id: z.string(),
  
  /** Symbol */
  symbol: z.string(),
  
  /** Name */
  name: z.string(),
  
  /** Primary category */
  category: z.string(),
  
  /** Sector group */
  sector: z.string(),
  
  /** Identity confidence from Layer 5 */
  identity_confidence: z.number().min(0).max(100),
  
  /** Is this a well-known asset? */
  is_well_known: z.boolean(),
  
  /** Interpretation context (guidance for narrative) */
  interpretation_context: z.string(),
  
  /** Metrics that were excluded due to context */
  excluded_metrics: z.array(z.object({
    metric_id: z.string(),
    reason: z.string(),
  })),
});

export type AssetContext = z.infer<typeof AssetContextSchema>;

// ═══════════════════════════════════════════════════════════════════════════════
// EXPLANATION OBJECT (THE COMPLETE CONTRACT)
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * ┌─────────────────────────────────────────────────────────────────────────────┐
 * │  EXPLANATION OBJECT (EO)                                                    │
 * │                                                                             │
 * │  The Source of Truth Contract                                               │
 * │                                                                             │
 * │  MANDATE: The Coinet AI is FORBIDDEN from asserting ANY numeric statement  │
 * │  or fact that is not mathematically present within this object.            │
 * │                                                                             │
 * │  This ensures the output is grounded in verifiable evidence, defeating     │
 * │  the risks of hallucination and numerical non-determinism.                 │
 * └─────────────────────────────────────────────────────────────────────────────┘
 */
export const ExplanationObjectSchema = z.object({
  // ═══════════════════════════════════════════════════════════════════════════
  // METADATA
  // ═══════════════════════════════════════════════════════════════════════════
  
  /** EO schema version */
  schema_version: z.literal(EO_SCHEMA_VERSION),
  
  /** Generation timestamp */
  generated_at: z.string().datetime(),
  
  /** Unique EO identifier */
  eo_id: z.string().uuid(),
  
  /** Pipeline execution ID (for audit trail) */
  pipeline_execution_id: z.string(),
  
  // ═══════════════════════════════════════════════════════════════════════════
  // ASSET CONTEXT (FROM LAYER 5)
  // ═══════════════════════════════════════════════════════════════════════════
  
  /** Asset classification and context */
  asset: AssetContextSchema,
  
  // ═══════════════════════════════════════════════════════════════════════════
  // CONFIDENCE (FROM LAYER 6)
  // ═══════════════════════════════════════════════════════════════════════════
  
  /** Overall confidence score (0-100) */
  confidence: z.number().min(0).max(100),
  
  /** Confidence level classification */
  confidence_level: z.enum(['HIGH', 'MEDIUM', 'LOW', 'INSUFFICIENT']),
  
  /** Gate status */
  gate_status: z.object({
    /** All gates passed? */
    passed: z.boolean(),
    
    /** Specific gate results */
    confidence_gate: z.boolean(),
    coverage_gate: z.boolean(),
    identity_gate: z.boolean(),
    
    /** Gate failure reason (if any) */
    failure_reason: z.string().nullable(),
  }),
  
  // ═══════════════════════════════════════════════════════════════════════════
  // COVERAGE SUMMARY (FROM LAYERS 3, 6)
  // ═══════════════════════════════════════════════════════════════════════════
  
  /** Data coverage and quality summary */
  coverage_summary: CoverageSummarySchema,
  
  // ═══════════════════════════════════════════════════════════════════════════
  // CLAIMS (FROM LAYERS 1, 3, 4) - THE ATOMIC TRUTHS
  // ═══════════════════════════════════════════════════════════════════════════
  
  /**
   * MANDATORY TRACEABILITY
   * 
   * Every factual assertion about performance MUST trace back to a claim.
   * The AI may ONLY assert facts present in this array.
   */
  claims: z.array(ClaimSchema),
  
  // ═══════════════════════════════════════════════════════════════════════════
  // SCORES (FROM OMNISCORE)
  // ═══════════════════════════════════════════════════════════════════════════
  
  /** Score summary */
  scores: ScoreSummarySchema,
  
  // ═══════════════════════════════════════════════════════════════════════════
  // DRIVERS (FROM LAYER 2 DIRECTION)
  // ═══════════════════════════════════════════════════════════════════════════
  
  /** Top positive drivers (helping the score) */
  positive_drivers: z.array(DriverSchema),
  
  /** Top negative drivers (hurting the score) */
  negative_drivers: z.array(DriverSchema),
  
  // ═══════════════════════════════════════════════════════════════════════════
  // WARNINGS (FROM LAYERS 3, 4)
  // ═══════════════════════════════════════════════════════════════════════════
  
  /**
   * Critical flags from validation layers
   * 
   * MUST be integrated into narrative as cautionary notes
   */
  warnings: z.array(WarningSchema),
  
  // ═══════════════════════════════════════════════════════════════════════════
  // LEGITIMACY (FROM LAYER 5)
  // ═══════════════════════════════════════════════════════════════════════════
  
  /** Legitimacy assessment */
  legitimacy: z.object({
    status: z.enum(['LEGIT', 'WATCH', 'SUSPICIOUS', 'NOT_LEGIT', 'INSUFFICIENT_DATA']),
    confidence: z.number().min(0).max(1),
    flags: z.array(z.string()),
  }),
  
  // ═══════════════════════════════════════════════════════════════════════════
  // NARRATIVE GUIDANCE
  // ═══════════════════════════════════════════════════════════════════════════
  
  /** Guidance for narrative generation */
  narrative_guidance: z.object({
    /** Primary narrative focus */
    focus: z.string(),
    
    /** Key points that MUST be mentioned */
    required_points: z.array(z.string()),
    
    /** Points that SHOULD be mentioned */
    recommended_points: z.array(z.string()),
    
    /** Topics to AVOID (due to missing data or context) */
    avoid_topics: z.array(z.string()),
    
    /** Tone recommendation */
    recommended_tone: z.enum(['BULLISH_CAUTIOUS', 'NEUTRAL', 'CAUTIOUS', 'BEARISH_CAUTIOUS']),
  }),
});

export type ExplanationObject = z.infer<typeof ExplanationObjectSchema>;

// ═══════════════════════════════════════════════════════════════════════════════
// GATED OUTPUT (WHEN CONFIDENCE IS INSUFFICIENT)
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Output when EO confidence is below threshold
 */
export const GatedOutputSchema = z.object({
  /** Indicates this is a gated output */
  gated: z.literal(true),
  
  /** Entity ID */
  entity_id: z.string(),
  
  /** Gate failure reason */
  reason: z.string(),
  
  /** Confidence score (below threshold) */
  confidence: z.number(),
  
  /** Required threshold */
  threshold: z.number(),
  
  /** What would be needed to pass */
  requirements: z.array(z.string()),
  
  /** Timestamp */
  timestamp: z.string().datetime(),
});

export type GatedOutput = z.infer<typeof GatedOutputSchema>;
