/**
 * L7.7 — Evidence Storage Validator
 *
 * §7.7.5.6 — Reject evidence bundles that are missing archive URI,
 * checksum, manifest linkage, or replay identity; block class/payload
 * mismatches; block orphan bundles that lack subject / assessment /
 * bundle linkage.
 */

import {
  L7EvidenceClass,
  L7EvidencePointer,
  L7EvidencePointerCheckContext,
  L7_EVIDENCE_CLASS_SUBJECT_KIND,
  evidencePathFor,
  isL7EvidenceClass,
} from '../contracts/l7-evidence-storage';
import {
  L7PersistenceViolation,
  L7PersistenceViolationCode,
  buildL7PersistenceViolation,
} from './l7-persistence-violation-codes';

export class L7EvidenceStorageValidator {
  validate(
    pointer: L7EvidencePointer,
    ctx: L7EvidencePointerCheckContext,
  ): { readonly ok: boolean; readonly violations: readonly L7PersistenceViolation[] } {
    const violations: L7PersistenceViolation[] = [];

    // Class legality.
    if (!isL7EvidenceClass(pointer.evidence_class)) {
      violations.push(
        v(
          L7PersistenceViolationCode.EVIDENCE_CLASS_UNKNOWN,
          pointer,
          `unknown evidence class ${pointer.evidence_class}`,
        ),
      );
      return { ok: false, violations };
    }

    // Class ↔ subject kind consistency.
    const expectedKind = L7_EVIDENCE_CLASS_SUBJECT_KIND[pointer.evidence_class];
    if (pointer.subject_kind !== expectedKind) {
      violations.push(
        v(
          L7PersistenceViolationCode.EVIDENCE_CLASS_PAYLOAD_MISMATCH,
          pointer,
          `evidence class ${pointer.evidence_class} expects subject kind ${expectedKind}, got ${pointer.subject_kind}`,
        ),
      );
    }
    if (pointer.subject_kind !== ctx.expected_subject_kind) {
      violations.push(
        v(
          L7PersistenceViolationCode.EVIDENCE_CLASS_PAYLOAD_MISMATCH,
          pointer,
          `pointer subject_kind ${pointer.subject_kind} ≠ context expected ${ctx.expected_subject_kind}`,
        ),
      );
    }

    // Required anchors.
    if (!pointer.archive_uri) {
      violations.push(v(L7PersistenceViolationCode.EVIDENCE_ARCHIVE_URI_MISSING, pointer, 'archive_uri missing'));
    }
    if (!pointer.checksum) {
      violations.push(v(L7PersistenceViolationCode.EVIDENCE_CHECKSUM_MISSING, pointer, 'checksum missing'));
    }
    if (!pointer.manifest_id) {
      violations.push(v(L7PersistenceViolationCode.EVIDENCE_MANIFEST_LINKAGE_MISSING, pointer, 'manifest_id missing'));
    }
    if (!pointer.subject_ref) {
      violations.push(v(L7PersistenceViolationCode.EVIDENCE_SUBJECT_LINK_MISSING, pointer, 'subject_ref missing'));
    } else if (pointer.subject_ref !== ctx.expected_subject_ref) {
      violations.push(
        v(
          L7PersistenceViolationCode.ORPHAN_EVIDENCE,
          pointer,
          `pointer subject_ref ${pointer.subject_ref} ≠ expected ${ctx.expected_subject_ref}`,
        ),
      );
    }

    // Replay identity.
    if (ctx.replay_required && !pointer.replay_generation_ref) {
      violations.push(v(L7PersistenceViolationCode.EVIDENCE_REPLAY_REF_MISSING, pointer, 'replay_generation_ref required but missing'));
    }

    if (pointer.compute_run_id !== ctx.expected_compute_run_id) {
      violations.push(
        v(
          L7PersistenceViolationCode.ORPHAN_EVIDENCE,
          pointer,
          `pointer compute_run_id ${pointer.compute_run_id} ≠ expected ${ctx.expected_compute_run_id}`,
        ),
      );
    }

    // Deterministic path check: the `archive_uri` must end with the
    // deterministic path suffix generated by `evidencePathFor(..)`.
    if (pointer.archive_uri && pointer.subject_ref && pointer.checksum) {
      const expectedPathTail = evidencePathFor(
        pointer.evidence_class,
        pointer.subject_ref,
        pointer.compute_run_id,
        pointer.checksum,
      );
      if (!pointer.archive_uri.endsWith(expectedPathTail)) {
        violations.push(
          v(
            L7PersistenceViolationCode.EVIDENCE_PATH_NON_DETERMINISTIC,
            pointer,
            `archive_uri '${pointer.archive_uri}' does not match deterministic suffix '${expectedPathTail}'`,
          ),
        );
      }
    }

    if (pointer.payload_byte_length <= 0) {
      violations.push(v(L7PersistenceViolationCode.ORPHAN_EVIDENCE, pointer, 'payload_byte_length must be > 0'));
    }
    if (!pointer.content_type) {
      violations.push(v(L7PersistenceViolationCode.ORPHAN_EVIDENCE, pointer, 'content_type missing'));
    }
    if (!pointer.schema_version) {
      violations.push(v(L7PersistenceViolationCode.ORPHAN_EVIDENCE, pointer, 'schema_version missing'));
    }

    return { ok: violations.length === 0, violations };
  }

  /** §7.7.4.7 — check that an "evidence required" materialization brings pointers. */
  validateEvidenceRequired(
    subjectId: string,
    surface: string,
    pointers: readonly L7EvidencePointer[],
  ): { readonly ok: boolean; readonly violations: readonly L7PersistenceViolation[] } {
    if (pointers.length > 0) return { ok: true, violations: [] };
    return {
      ok: false,
      violations: [
        buildL7PersistenceViolation(
          L7PersistenceViolationCode.EVIDENCE_REQUIRED_BUT_ABSENT,
          `surface ${surface} requires evidence pointers but got none`,
          { subject_id: subjectId, surface },
        ),
      ],
    };
  }
}

function v(
  code: L7PersistenceViolationCode,
  pointer: L7EvidencePointer,
  detail: string,
): L7PersistenceViolation {
  return buildL7PersistenceViolation(code, detail, {
    subject_id: pointer.subject_ref,
    surface: 'l7.evidence_pointers',
    context: { evidence_class: pointer.evidence_class, evidence_id: pointer.evidence_id },
  });
}

export function isL7EvidenceClassName(x: unknown): x is L7EvidenceClass {
  return isL7EvidenceClass(x);
}
