/**
 * L7.7 — Persistence / Materialization / Read Violation Codes
 *
 * §7.7 — A dedicated, disjoint code space for the persistence-and-serving
 * constitution of Layer 7. These codes are emitted by the durable-surface
 * registry, persistence validators, evidence-storage validator, read-surface
 * validator, and downstream-consumption validator.
 *
 * Disjoint from:
 *   - L7 contract violation codes
 *   - L7.4 runtime violation codes
 *   - L7.5 semantic violation codes
 *   - L7.6 confidence violation codes
 */

export enum L7PersistenceViolationCode {
  // ── Durable surfaces + authority ──────────────────────────────────
  UNKNOWN_DURABLE_SURFACE = 'L7_7_UNKNOWN_DURABLE_SURFACE',
  DURABLE_SURFACE_NOT_REGISTERED = 'L7_7_DURABLE_SURFACE_NOT_REGISTERED',
  AUTHORITY_STORE_MISMATCH = 'L7_7_AUTHORITY_STORE_MISMATCH',
  AUTHORITY_STORE_INVALID_FOR_SURFACE = 'L7_7_AUTHORITY_STORE_INVALID_FOR_SURFACE',
  MUTATION_DISCIPLINE_VIOLATED = 'L7_7_MUTATION_DISCIPLINE_VIOLATED',
  SHADOW_AUTHORITY_DETECTED = 'L7_7_SHADOW_AUTHORITY_DETECTED',
  REDIS_AS_AUTHORITY_ATTEMPT = 'L7_7_REDIS_AS_AUTHORITY_ATTEMPT',
  OBJECT_STORE_AS_CURRENT_AUTHORITY = 'L7_7_OBJECT_STORE_AS_CURRENT_AUTHORITY',
  DIRECT_STORE_BYPASS = 'L7_7_DIRECT_STORE_BYPASS',
  L5_BYPASS_ATTEMPT = 'L7_7_L5_BYPASS_ATTEMPT',

  // ── Current-state materialization ────────────────────────────────
  CURRENT_STATE_OVERWRITE_WITHOUT_SUPERSESSION = 'L7_7_CURRENT_STATE_OVERWRITE_WITHOUT_SUPERSESSION',
  SUPERSEDED_PRIOR_REF_MISSING = 'L7_7_SUPERSEDED_PRIOR_REF_MISSING',
  CURRENT_MATERIALIZATION_NOT_READY = 'L7_7_CURRENT_MATERIALIZATION_NOT_READY',
  CURRENT_MATERIALIZATION_MODE_INVALID = 'L7_7_CURRENT_MATERIALIZATION_MODE_INVALID',
  REPLAY_WRITTEN_AS_LIVE = 'L7_7_REPLAY_WRITTEN_AS_LIVE',
  REPAIR_WRITTEN_AS_LIVE = 'L7_7_REPAIR_WRITTEN_AS_LIVE',
  LIVE_WRITTEN_AS_REPLAY = 'L7_7_LIVE_WRITTEN_AS_REPLAY',

  // ── Historical surfaces ──────────────────────────────────────────
  HISTORICAL_ROW_MISSING_REPLAY_IDENTITY = 'L7_7_HISTORICAL_ROW_MISSING_REPLAY_IDENTITY',
  HISTORICAL_ROW_MISSING_LINEAGE = 'L7_7_HISTORICAL_ROW_MISSING_LINEAGE',
  HISTORICAL_ROW_DESTRUCTIVE_OVERWRITE = 'L7_7_HISTORICAL_ROW_DESTRUCTIVE_OVERWRITE',
  HISTORICAL_ROW_MODE_MISSING = 'L7_7_HISTORICAL_ROW_MODE_MISSING',
  HISTORICAL_ROW_EVIDENCE_REF_MISSING = 'L7_7_HISTORICAL_ROW_EVIDENCE_REF_MISSING',
  HISTORICAL_ROW_POLICY_VERSION_MISSING = 'L7_7_HISTORICAL_ROW_POLICY_VERSION_MISSING',
  CORRECTION_ROW_MISSING_PARENT = 'L7_7_CORRECTION_ROW_MISSING_PARENT',
  CORRECTION_ROW_MISSING_REASON = 'L7_7_CORRECTION_ROW_MISSING_REASON',
  CORRECTION_ROW_NOT_APPENDED = 'L7_7_CORRECTION_ROW_NOT_APPENDED',
  HISTORICAL_MUTATES_CURRENT_SILENTLY = 'L7_7_HISTORICAL_MUTATES_CURRENT_SILENTLY',

  // ── Evidence storage ─────────────────────────────────────────────
  EVIDENCE_CLASS_UNKNOWN = 'L7_7_EVIDENCE_CLASS_UNKNOWN',
  EVIDENCE_ARCHIVE_URI_MISSING = 'L7_7_EVIDENCE_ARCHIVE_URI_MISSING',
  EVIDENCE_CHECKSUM_MISSING = 'L7_7_EVIDENCE_CHECKSUM_MISSING',
  EVIDENCE_MANIFEST_LINKAGE_MISSING = 'L7_7_EVIDENCE_MANIFEST_LINKAGE_MISSING',
  EVIDENCE_SUBJECT_LINK_MISSING = 'L7_7_EVIDENCE_SUBJECT_LINK_MISSING',
  EVIDENCE_REPLAY_REF_MISSING = 'L7_7_EVIDENCE_REPLAY_REF_MISSING',
  EVIDENCE_CLASS_PAYLOAD_MISMATCH = 'L7_7_EVIDENCE_CLASS_PAYLOAD_MISMATCH',
  ORPHAN_EVIDENCE = 'L7_7_ORPHAN_EVIDENCE',
  EVIDENCE_REQUIRED_BUT_ABSENT = 'L7_7_EVIDENCE_REQUIRED_BUT_ABSENT',
  EVIDENCE_PATH_NON_DETERMINISTIC = 'L7_7_EVIDENCE_PATH_NON_DETERMINISTIC',

  // ── Read surfaces ────────────────────────────────────────────────
  UNKNOWN_READ_SURFACE = 'L7_7_UNKNOWN_READ_SURFACE',
  READ_SURFACE_NOT_REGISTERED = 'L7_7_READ_SURFACE_NOT_REGISTERED',
  READ_MODE_INVALID_FOR_SURFACE = 'L7_7_READ_MODE_INVALID_FOR_SURFACE',
  CONSUMER_CLASS_NOT_ALLOWED = 'L7_7_CONSUMER_CLASS_NOT_ALLOWED',
  RAW_STORAGE_READ_ATTEMPT = 'L7_7_RAW_STORAGE_READ_ATTEMPT',
  REDIS_READ_AS_AUTHORITATIVE = 'L7_7_REDIS_READ_AS_AUTHORITATIVE',
  CURRENT_FROM_HISTORICAL_GUESS = 'L7_7_CURRENT_FROM_HISTORICAL_GUESS',
  HISTORICAL_FROM_CURRENT_GUESS = 'L7_7_HISTORICAL_FROM_CURRENT_GUESS',
  AD_HOC_REVALIDATION_FROM_L6 = 'L7_7_AD_HOC_REVALIDATION_FROM_L6',
  EVIDENCE_READ_WITHOUT_POINTER = 'L7_7_EVIDENCE_READ_WITHOUT_POINTER',

  // ── Downstream consumption ───────────────────────────────────────
  DOWNSTREAM_BYPASSES_READ_SURFACE = 'L7_7_DOWNSTREAM_BYPASSES_READ_SURFACE',
  DOWNSTREAM_BYPASSES_RESTRICTION = 'L7_7_DOWNSTREAM_BYPASSES_RESTRICTION',
  DOWNSTREAM_REBUILDS_VALIDATION = 'L7_7_DOWNSTREAM_REBUILDS_VALIDATION',
  DOWNSTREAM_RAW_ARCHIVE_ACCESS = 'L7_7_DOWNSTREAM_RAW_ARCHIVE_ACCESS',
  DOWNSTREAM_IGNORES_CAP_CHAIN = 'L7_7_DOWNSTREAM_IGNORES_CAP_CHAIN',
  DOWNSTREAM_IGNORES_RESTRICTION_POSTURE = 'L7_7_DOWNSTREAM_IGNORES_RESTRICTION_POSTURE',
  DOWNSTREAM_READ_MODE_SPOOFED = 'L7_7_DOWNSTREAM_READ_MODE_SPOOFED',

  // ── Lineage + replay ─────────────────────────────────────────────
  LINEAGE_LINK_BROKEN = 'L7_7_LINEAGE_LINK_BROKEN',
  REPLAY_GENERATION_REF_MISSING = 'L7_7_REPLAY_GENERATION_REF_MISSING',
  CURRENT_HISTORICAL_INCONSISTENCY = 'L7_7_CURRENT_HISTORICAL_INCONSISTENCY',
  REPLAY_REPAIR_SEMANTIC_DRIFT = 'L7_7_REPLAY_REPAIR_SEMANTIC_DRIFT',
}

export const ALL_L7_PERSISTENCE_VIOLATION_CODES: readonly L7PersistenceViolationCode[] =
  Object.values(L7PersistenceViolationCode);

export interface L7PersistenceViolation {
  readonly code: L7PersistenceViolationCode;
  readonly subject_id: string | null;
  readonly surface: string | null;
  readonly detail: string;
  readonly context?: Readonly<Record<string, unknown>>;
}

export function buildL7PersistenceViolation(
  code: L7PersistenceViolationCode,
  detail: string,
  opts: {
    readonly subject_id?: string | null;
    readonly surface?: string | null;
    readonly context?: Record<string, unknown>;
  } = {},
): L7PersistenceViolation {
  return {
    code,
    subject_id: opts.subject_id ?? null,
    surface: opts.surface ?? null,
    detail,
    context: opts.context,
  };
}
