apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-control-plane
spec:
  profile: demo
  meshConfig:
    enablePrometheusMerge: true
    accessLogFile: /dev/stdout
  components:
    pilot:
      enabled: true
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
  values:
    global:
      proxy:
        autoInject: enabled
      mtls:
        enabled: true 