/**
 * L8.3 — Contract Violation Codes
 *
 * §8.3.9.2 — Typed violation codes for every L8.3 contract validator.
 * Disjoint from L8.1 constitutional codes and L8.2 object-model codes so
 * audit records are unambiguous about which tier rejected an artifact.
 */

export enum L8RegimeContractViolationCode {
  // ── Subject contract (§8.3.2) ──
  SUBJECT_MISSING_IDENTITY = 'L8C_SUBJECT_MISSING_IDENTITY',
  SUBJECT_MISSING_FAMILY = 'L8C_SUBJECT_MISSING_FAMILY',
  SUBJECT_MISSING_TEMPLATE = 'L8C_SUBJECT_MISSING_TEMPLATE',
  SUBJECT_MISSING_VERSION = 'L8C_SUBJECT_MISSING_VERSION',
  SUBJECT_MISSING_CONTRACT_VERSION = 'L8C_SUBJECT_MISSING_CONTRACT_VERSION',
  SUBJECT_MISSING_SCHEMA_VERSION = 'L8C_SUBJECT_MISSING_SCHEMA_VERSION',
  SUBJECT_MISSING_SCOPE = 'L8C_SUBJECT_MISSING_SCOPE',
  SUBJECT_MISSING_SCOPE_GRANULARITY = 'L8C_SUBJECT_MISSING_SCOPE_GRANULARITY',
  SUBJECT_MISSING_INPUTS = 'L8C_SUBJECT_MISSING_INPUTS',
  SUBJECT_MISSING_VALIDATION_INPUTS = 'L8C_SUBJECT_MISSING_VALIDATION_INPUTS',
  SUBJECT_MISSING_TEMPORAL = 'L8C_SUBJECT_MISSING_TEMPORAL',
  SUBJECT_MISSING_CLASSIFICATION_RULES = 'L8C_SUBJECT_MISSING_CLASSIFICATION_RULES',
  SUBJECT_MISSING_CONFIDENCE_SPEC = 'L8C_SUBJECT_MISSING_CONFIDENCE_SPEC',
  SUBJECT_MISSING_MULTIPLIER_SPEC = 'L8C_SUBJECT_MISSING_MULTIPLIER_SPEC',
  SUBJECT_MISSING_PERSISTENCE_POLICY = 'L8C_SUBJECT_MISSING_PERSISTENCE_POLICY',
  SUBJECT_MISSING_EVIDENCE_POLICY = 'L8C_SUBJECT_MISSING_EVIDENCE_POLICY',
  SUBJECT_MISSING_RESTRICTION_POLICY = 'L8C_SUBJECT_MISSING_RESTRICTION_POLICY',
  SUBJECT_MISSING_VALIDATION_POLICY = 'L8C_SUBJECT_MISSING_VALIDATION_POLICY',
  SUBJECT_MISSING_ALLOWED_CLASS_SET = 'L8C_SUBJECT_MISSING_ALLOWED_CLASS_SET',
  SUBJECT_MISSING_MULTIPLIER_DIMENSIONS = 'L8C_SUBJECT_MISSING_MULTIPLIER_DIMENSIONS',
  SUBJECT_MISSING_LINEAGE_POLICY = 'L8C_SUBJECT_MISSING_LINEAGE_POLICY',
  SUBJECT_MISSING_POLICY_VERSION = 'L8C_SUBJECT_MISSING_POLICY_VERSION',
  SUBJECT_INPUT_FAMILY_MIX = 'L8C_SUBJECT_INPUT_FAMILY_MIX',
  SUBJECT_JUDGMENT_LEAK = 'L8C_SUBJECT_JUDGMENT_LEAK',

  // ── Output contract (§8.3.3) ──
  OUTPUT_MISSING_IDENTITY = 'L8C_OUTPUT_MISSING_IDENTITY',
  OUTPUT_MISSING_SUBJECT_REF = 'L8C_OUTPUT_MISSING_SUBJECT_REF',
  OUTPUT_MISSING_CONTRACT_VERSION = 'L8C_OUTPUT_MISSING_CONTRACT_VERSION',
  OUTPUT_MISSING_SCHEMA_VERSION = 'L8C_OUTPUT_MISSING_SCHEMA_VERSION',
  OUTPUT_MISSING_PRIMARY_REGIME = 'L8C_OUTPUT_MISSING_PRIMARY_REGIME',
  OUTPUT_MISSING_FAMILY = 'L8C_OUTPUT_MISSING_FAMILY',
  OUTPUT_MISSING_SCOPE = 'L8C_OUTPUT_MISSING_SCOPE',
  OUTPUT_MISSING_TIME_ANCHOR = 'L8C_OUTPUT_MISSING_TIME_ANCHOR',
  OUTPUT_CONFIDENCE_OUT_OF_RANGE = 'L8C_OUTPUT_CONFIDENCE_OOR',
  OUTPUT_CONFIDENCE_BAND_INCONSISTENT = 'L8C_OUTPUT_CONFIDENCE_BAND_INCONSISTENT',
  OUTPUT_TRANSITION_SCORE_OUT_OF_RANGE = 'L8C_OUTPUT_TRANSITION_SCORE_OOR',
  OUTPUT_TRANSITION_CLASS_INCONSISTENT = 'L8C_OUTPUT_TRANSITION_CLASS_INCONSISTENT',
  OUTPUT_SCORE_OUT_OF_RANGE = 'L8C_OUTPUT_SCORE_OOR',
  OUTPUT_MISSING_MULTIPLIER_PROFILE = 'L8C_OUTPUT_MISSING_MULTIPLIER_PROFILE',
  OUTPUT_MISSING_CONFIDENCE_PROFILE_REF = 'L8C_OUTPUT_MISSING_CONFIDENCE_REF',
  OUTPUT_MISSING_TRANSITION_PROFILE_REF = 'L8C_OUTPUT_MISSING_TRANSITION_REF',
  OUTPUT_MISSING_VALIDATION_REFS = 'L8C_OUTPUT_MISSING_VALIDATION_REFS',
  OUTPUT_MISSING_EVIDENCE_PACK_REF = 'L8C_OUTPUT_MISSING_EVIDENCE_PACK_REF',
  OUTPUT_MISSING_INPUT_SNAPSHOT_REF = 'L8C_OUTPUT_MISSING_INPUT_SNAPSHOT_REF',
  OUTPUT_MISSING_RUN_ID = 'L8C_OUTPUT_MISSING_RUN_ID',
  OUTPUT_MISSING_REPLAY_HASH = 'L8C_OUTPUT_MISSING_REPLAY_HASH',
  OUTPUT_MISSING_LINEAGE = 'L8C_OUTPUT_MISSING_LINEAGE',
  OUTPUT_MISSING_POLICY_VERSION = 'L8C_OUTPUT_MISSING_POLICY_VERSION',
  OUTPUT_MISSING_MATERIALIZATION_MODE = 'L8C_OUTPUT_MISSING_MATERIALIZATION',
  OUTPUT_SECONDARY_EQUALS_PRIMARY = 'L8C_OUTPUT_SECONDARY_EQUALS_PRIMARY',
  OUTPUT_SECONDARY_WRONG_FAMILY = 'L8C_OUTPUT_SECONDARY_WRONG_FAMILY',
  OUTPUT_SECONDARY_CONFIDENCE_MISSING = 'L8C_OUTPUT_SECONDARY_CONFIDENCE_MISSING',
  OUTPUT_SECONDARY_CONFIDENCE_DANGLING = 'L8C_OUTPUT_SECONDARY_CONFIDENCE_DANGLING',
  OUTPUT_MISSING_COEXISTENCE_CLASS = 'L8C_OUTPUT_MISSING_COEXISTENCE',
  OUTPUT_JUDGMENT_LEAK = 'L8C_OUTPUT_JUDGMENT_LEAK',

  // ── Confidence contract (§8.3.4) ──
  CONFIDENCE_MISSING_IDENTITY = 'L8C_CONFIDENCE_MISSING_IDENTITY',
  CONFIDENCE_MISSING_RESULT_REF = 'L8C_CONFIDENCE_MISSING_RESULT_REF',
  CONFIDENCE_MISSING_CONTRACT_VERSION = 'L8C_CONFIDENCE_MISSING_CONTRACT_VERSION',
  CONFIDENCE_MISSING_FACTORS = 'L8C_CONFIDENCE_MISSING_FACTORS',
  CONFIDENCE_FACTORS_OUT_OF_RANGE = 'L8C_CONFIDENCE_FACTORS_OOR',
  CONFIDENCE_BAND_INCONSISTENT = 'L8C_CONFIDENCE_BAND_INCONSISTENT',
  CONFIDENCE_CAP_CHAIN_ILLEGAL = 'L8C_CONFIDENCE_CAP_CHAIN_ILLEGAL',
  CONFIDENCE_MISSING_CAPS_WHEN_REQUIRED = 'L8C_CONFIDENCE_MISSING_CAPS',
  CONFIDENCE_MISSING_RATIONALE = 'L8C_CONFIDENCE_MISSING_RATIONALE',
  CONFIDENCE_MISSING_POLICY_VERSION = 'L8C_CONFIDENCE_MISSING_POLICY_VERSION',
  CONFIDENCE_MISSING_REPLAY_HASH = 'L8C_CONFIDENCE_MISSING_REPLAY_HASH',
  CONFIDENCE_CLEAN_WHILE_AMBIGUOUS = 'L8C_CONFIDENCE_CLEAN_WHILE_AMBIGUOUS',

  // ── Transition contract (§8.3.5) ──
  TRANSITION_MISSING_IDENTITY = 'L8C_TRANSITION_MISSING_IDENTITY',
  TRANSITION_MISSING_RESULT_REF = 'L8C_TRANSITION_MISSING_RESULT_REF',
  TRANSITION_MISSING_CONTRACT_VERSION = 'L8C_TRANSITION_MISSING_CONTRACT_VERSION',
  TRANSITION_SCORE_OUT_OF_RANGE = 'L8C_TRANSITION_SCORE_OOR',
  TRANSITION_CLASS_INCONSISTENT = 'L8C_TRANSITION_CLASS_INCONSISTENT',
  TRANSITION_MISSING_COEXISTENCE = 'L8C_TRANSITION_MISSING_COEXISTENCE',
  TRANSITION_MISSING_INSTABILITY_REASONS = 'L8C_TRANSITION_MISSING_INSTABILITY_REASONS',
  TRANSITION_STABLE_WHILE_AMBIGUOUS = 'L8C_TRANSITION_STABLE_WHILE_AMBIGUOUS',
  TRANSITION_MISSING_REPLAY_HASH = 'L8C_TRANSITION_MISSING_REPLAY_HASH',

  // ── Multiplier contract (§8.3.6) ──
  MULTIPLIER_MISSING_IDENTITY = 'L8C_MULTIPLIER_MISSING_IDENTITY',
  MULTIPLIER_MISSING_RESULT_REF = 'L8C_MULTIPLIER_MISSING_RESULT_REF',
  MULTIPLIER_MISSING_CONTRACT_VERSION = 'L8C_MULTIPLIER_MISSING_CONTRACT_VERSION',
  MULTIPLIER_MISSING_REGIME_ANCHOR = 'L8C_MULTIPLIER_MISSING_REGIME_ANCHOR',
  MULTIPLIER_MISSING_DIMENSION = 'L8C_MULTIPLIER_MISSING_DIMENSION',
  MULTIPLIER_DIMENSION_OUT_OF_RANGE = 'L8C_MULTIPLIER_DIMENSION_OOR',
  MULTIPLIER_MISSING_DERIVATION_SPEC = 'L8C_MULTIPLIER_MISSING_DERIVATION_SPEC',
  MULTIPLIER_MISSING_RESTRICTION_CONSUMPTION = 'L8C_MULTIPLIER_MISSING_RESTRICTION',
  MULTIPLIER_MISSING_POLICY_VERSION = 'L8C_MULTIPLIER_MISSING_POLICY_VERSION',
  MULTIPLIER_MISSING_REPLAY_HASH = 'L8C_MULTIPLIER_MISSING_REPLAY_HASH',
  MULTIPLIER_IS_SCORE_SHAPED = 'L8C_MULTIPLIER_IS_SCORE_SHAPED',
  MULTIPLIER_ACTION_BIAS = 'L8C_MULTIPLIER_ACTION_BIAS',

  // ── Cleanliness / runtime legality (§8.3.8) ──
  CLEAN_WHILE_AMBIGUOUS = 'L8C_CLEAN_WHILE_AMBIGUOUS',
  CLEAN_WHILE_STALE = 'L8C_CLEAN_WHILE_STALE',
  CLEAN_WHILE_DEGRADED = 'L8C_CLEAN_WHILE_DEGRADED',
  CLEAN_WHILE_TRANSITION_HIGH = 'L8C_CLEAN_WHILE_TRANSITION_HIGH',
  CONTRADICTION_POSTURE_REQUIRED = 'L8C_CONTRADICTION_POSTURE_REQUIRED',
  RESTRICTION_POSTURE_REQUIRED = 'L8C_RESTRICTION_POSTURE_REQUIRED',
  AMBIGUITY_POSTURE_REQUIRED = 'L8C_AMBIGUITY_POSTURE_REQUIRED',

  // ── Compatibility (§8.3.7) ──
  COMPATIBILITY_PROHIBITED = 'L8C_COMPATIBILITY_PROHIBITED',
  COMPATIBILITY_BREAKING_SEMANTIC_UNAPPROVED = 'L8C_COMPATIBILITY_BREAKING_UNAPPROVED',
  COMPATIBILITY_NON_MONOTONIC_VERSION = 'L8C_COMPATIBILITY_NON_MONOTONIC',
  COMPATIBILITY_REQUIRED_FIELD_REMOVED = 'L8C_COMPATIBILITY_REQUIRED_FIELD_REMOVED',
  COMPATIBILITY_CLASSIFICATION_MISMATCH = 'L8C_COMPATIBILITY_CLASSIFICATION_MISMATCH',
}

export const ALL_L8_REGIME_CONTRACT_VIOLATION_CODES:
  readonly L8RegimeContractViolationCode[] =
    Object.values(L8RegimeContractViolationCode);
