/**
 * L8.7 — Reliance-governance violation codes.
 *
 * Every L8.7 validator emits violations tagged with one of these
 * codes. The enum is flat (not hierarchical) so downstream dashboards
 * and auditors can match on exact code strings.
 */

export enum L8RegimeRelianceViolationCode {
  // ---- Confidence-policy violations (§8.7.3) ----
  CONFIDENCE_MISSING_FACTOR_GROUP = 'CONFIDENCE_MISSING_FACTOR_GROUP',
  CONFIDENCE_FACTOR_OUT_OF_RANGE = 'CONFIDENCE_FACTOR_OUT_OF_RANGE',
  CONFIDENCE_SCORE_BAND_MISMATCH = 'CONFIDENCE_SCORE_BAND_MISMATCH',
  CONFIDENCE_SCORE_OUT_OF_RANGE = 'CONFIDENCE_SCORE_OUT_OF_RANGE',
  CONFIDENCE_CAP_REQUIRED_BUT_MISSING = 'CONFIDENCE_CAP_REQUIRED_BUT_MISSING',
  CONFIDENCE_MASQUERADE_CLEAN = 'CONFIDENCE_MASQUERADE_CLEAN',
  CONFIDENCE_RESTRICTION_NOT_CONSUMED =
    'CONFIDENCE_RESTRICTION_NOT_CONSUMED',
  CONFIDENCE_CONTRADICTION_NOT_CONSUMED =
    'CONFIDENCE_CONTRADICTION_NOT_CONSUMED',
  CONFIDENCE_CAPPED_EXCEEDS_MAX = 'CONFIDENCE_CAPPED_EXCEEDS_MAX',
  CONFIDENCE_CAPPED_ABOVE_RAW = 'CONFIDENCE_CAPPED_ABOVE_RAW',

  // ---- Transition-risk-policy violations (§8.7.4) ----
  TRANSITION_SCORE_OUT_OF_RANGE = 'TRANSITION_SCORE_OUT_OF_RANGE',
  TRANSITION_CLASS_SCORE_MISMATCH = 'TRANSITION_CLASS_SCORE_MISMATCH',
  TRANSITION_HIGH_WITHOUT_REASONS = 'TRANSITION_HIGH_WITHOUT_REASONS',
  TRANSITION_CLEAN_WITH_OVERLAP = 'TRANSITION_CLEAN_WITH_OVERLAP',
  TRANSITION_FLIP_PRESSURE_INCOHERENT =
    'TRANSITION_FLIP_PRESSURE_INCOHERENT',
  TRANSITION_FAMILY_PRESSURE_INCOHERENT =
    'TRANSITION_FAMILY_PRESSURE_INCOHERENT',
  TRANSITION_ABSORBED_INTO_CONFIDENCE =
    'TRANSITION_ABSORBED_INTO_CONFIDENCE',
  TRANSITION_COEXISTENCE_MISSING_WITH_OVERLAP =
    'TRANSITION_COEXISTENCE_MISSING_WITH_OVERLAP',
  TRANSITION_LOW_WITH_AMBIGUITY_UNRESOLVED =
    'TRANSITION_LOW_WITH_AMBIGUITY_UNRESOLVED',

  // ---- Multiplier-policy violations (§8.7.5 / §8.7.6) ----
  MULTIPLIER_MISSING_DIMENSION = 'MULTIPLIER_MISSING_DIMENSION',
  MULTIPLIER_DIMENSION_OUT_OF_RANGE = 'MULTIPLIER_DIMENSION_OUT_OF_RANGE',
  MULTIPLIER_SCORE_SHAPED = 'MULTIPLIER_SCORE_SHAPED',
  MULTIPLIER_UNIFORMLY_DIRECTIONAL = 'MULTIPLIER_UNIFORMLY_DIRECTIONAL',
  MULTIPLIER_ACTION_BIASED = 'MULTIPLIER_ACTION_BIASED',
  MULTIPLIER_PARENT_REGIME_MISSING = 'MULTIPLIER_PARENT_REGIME_MISSING',
  MULTIPLIER_CONFIDENCE_BAND_MISSING = 'MULTIPLIER_CONFIDENCE_BAND_MISSING',
  MULTIPLIER_TRANSITION_CLASS_MISSING =
    'MULTIPLIER_TRANSITION_CLASS_MISSING',
  MULTIPLIER_NARROWING_REASON_MISSING =
    'MULTIPLIER_NARROWING_REASON_MISSING',
  MULTIPLIER_IGNORES_TRANSITION = 'MULTIPLIER_IGNORES_TRANSITION',
  MULTIPLIER_IGNORES_RESTRICTION = 'MULTIPLIER_IGNORES_RESTRICTION',
  MULTIPLIER_IGNORES_CONTRADICTION = 'MULTIPLIER_IGNORES_CONTRADICTION',
  MULTIPLIER_NARROWING_WIDENS_RIGHTS = 'MULTIPLIER_NARROWING_WIDENS_RIGHTS',

  // ---- Cap-chain violations (§8.7.7) ----
  CAP_CHAIN_PRE_CAP_OUT_OF_RANGE = 'CAP_CHAIN_PRE_CAP_OUT_OF_RANGE',
  CAP_CHAIN_CAPPED_OUT_OF_RANGE = 'CAP_CHAIN_CAPPED_OUT_OF_RANGE',
  CAP_CHAIN_CAPPED_ABOVE_PRE_CAP = 'CAP_CHAIN_CAPPED_ABOVE_PRE_CAP',
  CAP_CHAIN_DOMINANT_NOT_IN_APPLIED =
    'CAP_CHAIN_DOMINANT_NOT_IN_APPLIED',
  CAP_CHAIN_MISSING_DOMINANT = 'CAP_CHAIN_MISSING_DOMINANT',
  CAP_CHAIN_DOMINANT_WRONG_PRECEDENCE =
    'CAP_CHAIN_DOMINANT_WRONG_PRECEDENCE',
  CAP_CHAIN_REQUIRED_CAP_MISSING = 'CAP_CHAIN_REQUIRED_CAP_MISSING',
  CAP_CHAIN_DUPLICATE_REASON = 'CAP_CHAIN_DUPLICATE_REASON',
  CAP_CHAIN_READINESS_HINT_WRONG = 'CAP_CHAIN_READINESS_HINT_WRONG',
  CAP_CHAIN_CAP_VALUE_INCOHERENT = 'CAP_CHAIN_CAP_VALUE_INCOHERENT',

  // ---- Reliance-profile violations (§8.7.2 / §8.7.10) ----
  RELIANCE_MISSING_CONFIDENCE_REF = 'RELIANCE_MISSING_CONFIDENCE_REF',
  RELIANCE_MISSING_TRANSITION_REF = 'RELIANCE_MISSING_TRANSITION_REF',
  RELIANCE_MISSING_MULTIPLIER_REF = 'RELIANCE_MISSING_MULTIPLIER_REF',
  RELIANCE_READINESS_INCOHERENT = 'RELIANCE_READINESS_INCOHERENT',
  RELIANCE_SURFACES_COLLAPSED = 'RELIANCE_SURFACES_COLLAPSED',
  RELIANCE_BAND_MISMATCH = 'RELIANCE_BAND_MISMATCH',
  RELIANCE_RISK_CLASS_MISMATCH = 'RELIANCE_RISK_CLASS_MISMATCH',
  RELIANCE_REPLAY_HASH_MISSING = 'RELIANCE_REPLAY_HASH_MISSING',
  RELIANCE_STRONG_WITH_CRITICAL_CAP =
    'RELIANCE_STRONG_WITH_CRITICAL_CAP',
  RELIANCE_BLOCKED_WITH_CLEAN_HINT =
    'RELIANCE_BLOCKED_WITH_CLEAN_HINT',
}

export const ALL_L8_REGIME_RELIANCE_VIOLATION_CODES:
  readonly L8RegimeRelianceViolationCode[] =
    Object.values(L8RegimeRelianceViolationCode);

/** A single emitted violation record. */
export interface L8RegimeRelianceViolation {
  readonly code: L8RegimeRelianceViolationCode;
  readonly detail: string;
  readonly subject_ref?: string;
}
