/**
 * L8.4 — Runtime Violation Codes
 *
 * §8.4.8.2 / §8.4.9.1 — `L8RuntimeViolationCode`. Disjoint from L8.1
 * boundary codes, L8.2 object codes, and L8.3 contract codes so that an
 * audit record's tier is unambiguous from its violation code alone.
 *
 * Every code begins with the prefix `L8R_` to identify the runtime tier.
 */

export enum L8RuntimeViolationCode {
  // ── DAG legality (§8.4.2) ──
  DAG_ILLEGAL_NODE_CLASS = 'L8R_DAG_ILLEGAL_NODE_CLASS',
  DAG_ILLEGAL_EDGE_CLASS = 'L8R_DAG_ILLEGAL_EDGE_CLASS',
  DAG_ILLEGAL_EDGE_TRANSITION = 'L8R_DAG_ILLEGAL_EDGE_TRANSITION',
  DAG_NODE_STAGE_MISMATCH = 'L8R_DAG_NODE_STAGE_MISMATCH',
  DAG_CYCLE_DETECTED = 'L8R_DAG_CYCLE_DETECTED',
  DAG_UNRESOLVED_DEPENDENCY = 'L8R_DAG_UNRESOLVED_DEPENDENCY',
  DAG_MISSING_TERMINAL_NODE = 'L8R_DAG_MISSING_TERMINAL_NODE',
  DAG_NON_DETERMINISTIC_ORDER = 'L8R_DAG_NON_DETERMINISTIC_ORDER',
  DAG_DUPLICATE_NODE_ID = 'L8R_DAG_DUPLICATE_NODE_ID',
  DAG_ORPHAN_CLASSIFICATION = 'L8R_DAG_ORPHAN_CLASSIFICATION',
  DAG_INPUT_TO_CONFIDENCE_JUMP = 'L8R_DAG_INPUT_TO_CONFIDENCE_JUMP',
  DAG_CANDIDATE_TO_MATERIALIZATION_JUMP = 'L8R_DAG_CANDIDATE_TO_MATERIALIZATION_JUMP',
  DAG_MULTIPLIER_BEFORE_CLASSIFICATION = 'L8R_DAG_MULTIPLIER_BEFORE_CLASSIFICATION',
  DAG_CLASSIFICATION_BEFORE_QUALITY = 'L8R_DAG_CLASSIFICATION_BEFORE_QUALITY',

  // ── Run lineage (§8.4.2.7) ──
  RUN_LINEAGE_MISSING = 'L8R_RUN_LINEAGE_MISSING',
  RUN_MODE_MISSING = 'L8R_RUN_MODE_MISSING',
  RUN_ENGINE_SET_INCOMPLETE = 'L8R_RUN_ENGINE_SET_INCOMPLETE',
  RUN_DETERMINISM_BROKEN = 'L8R_RUN_DETERMINISM_BROKEN',
  RUN_PARENT_REQUIRED = 'L8R_RUN_PARENT_REQUIRED',

  // ── Subject assembly (§8.4.4.1) ──
  ASSEMBLY_UNREGISTERED_TEMPLATE = 'L8R_ASSEMBLY_UNREGISTERED_TEMPLATE',
  ASSEMBLY_ILLEGAL_SCOPE_BINDING = 'L8R_ASSEMBLY_ILLEGAL_SCOPE_BINDING',
  ASSEMBLY_FAMILY_SCOPE_ILLEGAL = 'L8R_ASSEMBLY_FAMILY_SCOPE_ILLEGAL',
  ASSEMBLY_LINEAGE_INCOMPLETE = 'L8R_ASSEMBLY_LINEAGE_INCOMPLETE',
  ASSEMBLY_CONTRACT_INCOMPLETE = 'L8R_ASSEMBLY_CONTRACT_INCOMPLETE',
  ASSEMBLY_JUDGMENT_LEAK = 'L8R_ASSEMBLY_JUDGMENT_LEAK',
  ASSEMBLY_NON_DETERMINISTIC_ID = 'L8R_ASSEMBLY_NON_DETERMINISTIC_ID',

  // ── Input / validation consumption (§8.4.4.3-7) ──
  INPUT_UNREGISTERED_SURFACE = 'L8R_INPUT_UNREGISTERED_SURFACE',
  INPUT_RAW_UNGATED = 'L8R_INPUT_RAW_UNGATED',
  INPUT_STALE_MASQUERADING_CURRENT = 'L8R_INPUT_STALE_MASQUERADING_CURRENT',
  INPUT_MISSING_REQUIRED_VALIDATION = 'L8R_INPUT_MISSING_REQUIRED_VALIDATION',
  INPUT_MISSING_REQUIRED_FEATURE = 'L8R_INPUT_MISSING_REQUIRED_FEATURE',
  INPUT_EVIDENCE_ONLY_USED_AS_HARD = 'L8R_INPUT_EVIDENCE_ONLY_USED_AS_HARD',
  INPUT_RESTRICTION_BYPASS = 'L8R_INPUT_RESTRICTION_BYPASS',
  INPUT_BLOCKED_VALIDATION_ACCEPTED = 'L8R_INPUT_BLOCKED_VALIDATION_ACCEPTED',
  INPUT_SCOPE_INCOMPATIBLE = 'L8R_INPUT_SCOPE_INCOMPATIBLE',
  INPUT_READINESS_INCONSISTENT = 'L8R_INPUT_READINESS_INCONSISTENT',

  // ── Candidate detection (§8.4.5.1-3) ──
  CANDIDATE_ASSIGNED_PRIMARY = 'L8R_CANDIDATE_ASSIGNED_PRIMARY',
  CANDIDATE_ASSIGNED_SECONDARY = 'L8R_CANDIDATE_ASSIGNED_SECONDARY',
  CANDIDATE_UNREGISTERED_CLASS = 'L8R_CANDIDATE_UNREGISTERED_CLASS',
  CANDIDATE_CLASS_NOT_IN_FAMILY = 'L8R_CANDIDATE_CLASS_NOT_IN_FAMILY',
  CANDIDATE_STRENGTH_OUT_OF_RANGE = 'L8R_CANDIDATE_STRENGTH_OOR',
  CANDIDATE_MISSING_REASON = 'L8R_CANDIDATE_MISSING_REASON',
  CANDIDATE_NON_DETERMINISTIC = 'L8R_CANDIDATE_NON_DETERMINISTIC',

  // ── Transition / ambiguity / staleness / degradation (§8.4.5.4-9) ──
  TRANSITION_ASSIGNED_PRIMARY = 'L8R_TRANSITION_ASSIGNED_PRIMARY',
  TRANSITION_SCORE_OUT_OF_RANGE = 'L8R_TRANSITION_SCORE_OOR',
  TRANSITION_CLASS_INCONSISTENT = 'L8R_TRANSITION_CLASS_INCONSISTENT',
  TRANSITION_HIGH_WITHOUT_REASONS = 'L8R_TRANSITION_HIGH_WITHOUT_REASONS',
  QUALITY_DOMAINS_COLLAPSED = 'L8R_QUALITY_DOMAINS_COLLAPSED',
  QUALITY_STALENESS_AS_DEGRADATION = 'L8R_QUALITY_STALENESS_AS_DEGRADATION',
  QUALITY_AMBIGUITY_AS_TRANSITION = 'L8R_QUALITY_AMBIGUITY_AS_TRANSITION',
  QUALITY_OUT_OF_ORDER = 'L8R_QUALITY_OUT_OF_ORDER',
  QUALITY_SCORE_OUT_OF_RANGE = 'L8R_QUALITY_SCORE_OUT_OF_RANGE',

  // ── Classification (§8.4.6.1-3) ──
  CLASSIFY_BEFORE_QUALITY = 'L8R_CLASSIFY_BEFORE_QUALITY',
  CLASSIFY_ILLEGAL_COEXISTENCE = 'L8R_CLASSIFY_ILLEGAL_COEXISTENCE',
  CLASSIFY_FAKE_CLEAN_SINGLE = 'L8R_CLASSIFY_FAKE_CLEAN_SINGLE',
  CLASSIFY_STABLE_WHILE_TRANSITION_HIGH = 'L8R_CLASSIFY_STABLE_WHILE_TRANSITION_HIGH',
  CLASSIFY_RESTRICTED_INPUT_USED_STRONGLY = 'L8R_CLASSIFY_RESTRICTED_INPUT_USED_STRONGLY',
  CLASSIFY_PRIMARY_NOT_IN_FAMILY = 'L8R_CLASSIFY_PRIMARY_NOT_IN_FAMILY',
  CLASSIFY_SECONDARY_SAME_AS_PRIMARY = 'L8R_CLASSIFY_SECONDARY_SAME_AS_PRIMARY',
  CLASSIFY_DOUBLE_ASSIGNMENT = 'L8R_CLASSIFY_DOUBLE_ASSIGNMENT',

  // ── Confidence runtime (§8.4.6.4) ──
  CONFIDENCE_BEFORE_CLASSIFICATION = 'L8R_CONFIDENCE_BEFORE_CLASSIFICATION',
  CONFIDENCE_IGNORES_TRANSITION = 'L8R_CONFIDENCE_IGNORES_TRANSITION',
  CONFIDENCE_IGNORES_AMBIGUITY = 'L8R_CONFIDENCE_IGNORES_AMBIGUITY',
  CONFIDENCE_IGNORES_STALENESS = 'L8R_CONFIDENCE_IGNORES_STALENESS',
  CONFIDENCE_IGNORES_DEGRADATION = 'L8R_CONFIDENCE_IGNORES_DEGRADATION',
  CONFIDENCE_MISSING_RESTRICTION_REFS = 'L8R_CONFIDENCE_MISSING_RESTRICTION_REFS',
  CONFIDENCE_CAP_CHAIN_ILLEGAL = 'L8R_CONFIDENCE_CAP_CHAIN_ILLEGAL',
  CONFIDENCE_SCORE_OUT_OF_RANGE = 'L8R_CONFIDENCE_SCORE_OOR',

  // ── Multiplier runtime (§8.4.6.5) ──
  MULTIPLIER_BEFORE_CLASSIFICATION = 'L8R_MULTIPLIER_BEFORE_CLASSIFICATION',
  MULTIPLIER_IGNORES_TRANSITION = 'L8R_MULTIPLIER_IGNORES_TRANSITION',
  MULTIPLIER_IGNORES_CONFIDENCE = 'L8R_MULTIPLIER_IGNORES_CONFIDENCE',
  MULTIPLIER_IGNORES_RESTRICTION = 'L8R_MULTIPLIER_IGNORES_RESTRICTION',
  MULTIPLIER_SCORE_SHAPED = 'L8R_MULTIPLIER_SCORE_SHAPED',
  MULTIPLIER_ACTION_BIAS = 'L8R_MULTIPLIER_ACTION_BIAS',
  MULTIPLIER_DIMENSION_OUT_OF_RANGE = 'L8R_MULTIPLIER_DIMENSION_OOR',

  // ── Evidence pack (§8.4.7.1) ──
  EVIDENCE_PACK_INCOMPLETE = 'L8R_EVIDENCE_PACK_INCOMPLETE',
  EVIDENCE_PACK_MISSING_LINEAGE = 'L8R_EVIDENCE_PACK_MISSING_LINEAGE',
  EVIDENCE_PACK_NON_DETERMINISTIC = 'L8R_EVIDENCE_PACK_NON_DETERMINISTIC',
  EVIDENCE_PACK_MISSING_CANDIDATES = 'L8R_EVIDENCE_PACK_MISSING_CANDIDATES',
  EVIDENCE_PACK_MISSING_QUALITY = 'L8R_EVIDENCE_PACK_MISSING_QUALITY',

  // ── Materialization (§8.4.7.2) ──
  MATERIALIZATION_DIRECT_STORE_WRITE = 'L8R_MATERIALIZATION_DIRECT_STORE_WRITE',
  MATERIALIZATION_BYPASSES_L5 = 'L8R_MATERIALIZATION_BYPASSES_L5',
  MATERIALIZATION_PREREQUISITES_MISSING = 'L8R_MATERIALIZATION_PREREQUISITES_MISSING',
  MATERIALIZATION_CONTRACT_INVALID = 'L8R_MATERIALIZATION_CONTRACT_INVALID',
  MATERIALIZATION_READINESS_INCONSISTENT = 'L8R_MATERIALIZATION_READINESS_INCONSISTENT',

  // ── Replay / repair (§8.4.7.4-6) ──
  REPLAY_HASH_DIVERGED = 'L8R_REPLAY_HASH_DIVERGED',
  REPLAY_PRETENDS_LIVE = 'L8R_REPLAY_PRETENDS_LIVE',
  REPLAY_INVENTED_EVIDENCE = 'L8R_REPLAY_INVENTED_EVIDENCE',
  REPLAY_ERASED_AMBIGUITY = 'L8R_REPLAY_ERASED_AMBIGUITY',
  REPAIR_LINEAGE_BROKEN = 'L8R_REPAIR_LINEAGE_BROKEN',
  REPAIR_UNMARKED = 'L8R_REPAIR_UNMARKED',
  REPAIR_REASON_MISSING = 'L8R_REPAIR_REASON_MISSING',
}

export const ALL_L8_RUNTIME_VIOLATION_CODES:
  readonly L8RuntimeViolationCode[] =
    Object.values(L8RuntimeViolationCode);

export interface L8RuntimeViolation {
  readonly code: L8RuntimeViolationCode;
  readonly source: string;
  readonly nodeId: string | null;
  readonly regime_run_id: string | null;
  readonly regime_subject_id: string | null;
  readonly detail: string;
  readonly context: Record<string, unknown>;
}

export class L8RuntimeError extends Error {
  public readonly code: L8RuntimeViolationCode;
  public readonly details: Record<string, unknown>;

  constructor(
    code: L8RuntimeViolationCode,
    message: string,
    details: Record<string, unknown> = {},
  ) {
    super(`[${code}] ${message}`);
    this.name = 'L8RuntimeError';
    this.code = code;
    this.details = details;
  }
}
