/**
 * L8.6 — Template Violation Codes
 *
 * §8.6.8.2 — Typed violation codes for every L8.6 template, family-
 * rollout, and consistency validator. Disjoint from L8.1 / L8.2 / L8.3 /
 * L8.4 / L8.5 codes so audit records remain unambiguous.
 */

export enum L8RegimeTemplateViolationCode {
  // ── Template identity / registration ──
  TEMPLATE_UNREGISTERED = 'L8T_TEMPLATE_UNREGISTERED',
  TEMPLATE_MISSING_ID = 'L8T_TEMPLATE_MISSING_ID',
  TEMPLATE_MISSING_VERSION = 'L8T_TEMPLATE_MISSING_VERSION',
  TEMPLATE_ID_MISMATCH = 'L8T_TEMPLATE_ID_MISMATCH',

  // ── Template semantics (§8.6.5.5) ──
  TEMPLATE_MISSING_SUPPORT_DOMAINS = 'L8T_MISSING_SUPPORT_DOMAINS',
  TEMPLATE_MISSING_CHALLENGE_DOMAINS = 'L8T_MISSING_CHALLENGE_DOMAINS',
  TEMPLATE_MISSING_TRANSITION_SIGNATURES = 'L8T_MISSING_TRANSITION_SIGNATURES',
  TEMPLATE_MISSING_AMBIGUITY_SIGNATURES = 'L8T_MISSING_AMBIGUITY_SIGNATURES',
  TEMPLATE_MISSING_CONFIDENCE_DEFAULTS = 'L8T_MISSING_CONFIDENCE_DEFAULTS',
  TEMPLATE_MISSING_MULTIPLIER_DEFAULTS = 'L8T_MISSING_MULTIPLIER_DEFAULTS',
  TEMPLATE_MISSING_ROLLOUT_PRIORITY = 'L8T_MISSING_ROLLOUT_PRIORITY',
  TEMPLATE_MISSING_VALIDATION_PATTERNS = 'L8T_MISSING_VALIDATION_PATTERNS',
  TEMPLATE_MISSING_FEATURE_PATTERNS = 'L8T_MISSING_FEATURE_PATTERNS',
  TEMPLATE_MISSING_APPLICABLE_SCOPES = 'L8T_MISSING_APPLICABLE_SCOPES',
  TEMPLATE_MISSING_LEGAL_INPUTS = 'L8T_MISSING_LEGAL_INPUTS',

  // ── Template/family consistency (§8.6.7.6) ──
  TEMPLATE_UNKNOWN_FAMILY = 'L8T_UNKNOWN_FAMILY',
  TEMPLATE_CLASS_NOT_IN_FAMILY = 'L8T_CLASS_NOT_IN_FAMILY',
  TEMPLATE_SCOPE_NOT_IN_FAMILY = 'L8T_SCOPE_NOT_IN_FAMILY',
  TEMPLATE_INPUT_FAMILY_NOT_ALLOWED = 'L8T_INPUT_FAMILY_NOT_ALLOWED',
  TEMPLATE_VALIDATION_PATTERN_NOT_ALLOWED = 'L8T_VALIDATION_PATTERN_NOT_ALLOWED',

  // ── Domain/input overlaps (§8.6.3.7) ──
  TEMPLATE_SUPPORT_CHALLENGE_OVERLAP = 'L8T_SUPPORT_CHALLENGE_OVERLAP',
  TEMPLATE_SUPPORT_DOMAIN_NOT_REGISTERED = 'L8T_SUPPORT_DOMAIN_NOT_REGISTERED',
  TEMPLATE_CHALLENGE_DOMAIN_NOT_REGISTERED = 'L8T_CHALLENGE_DOMAIN_NOT_REGISTERED',
  TEMPLATE_SUPPORT_DOMAIN_NOT_FOR_FAMILY = 'L8T_SUPPORT_DOMAIN_NOT_FOR_FAMILY',

  // ── Signatures (§8.6.5.3 / §8.6.5.4) ──
  SIGNATURE_WEIGHT_OUT_OF_RANGE = 'L8T_SIGNATURE_WEIGHT_OOR',
  SIGNATURE_MISSING_DOMAINS = 'L8T_SIGNATURE_MISSING_DOMAINS',
  SIGNATURE_ID_MISSING = 'L8T_SIGNATURE_ID_MISSING',
  SIGNATURE_ID_DUPLICATE = 'L8T_SIGNATURE_ID_DUPLICATE',
  SIGNATURE_WRONG_CLASS = 'L8T_SIGNATURE_WRONG_CLASS',

  // ── Rollout (§8.6.6) ──
  FAMILY_ROLLOUT_PHASE_MISMATCH = 'L8T_FAMILY_ROLLOUT_PHASE_MISMATCH',
  TEMPLATE_SKIPS_EARLIER_PHASE = 'L8T_TEMPLATE_SKIPS_EARLIER_PHASE',
  TEMPLATE_STATE_ILLEGAL_FOR_MODE = 'L8T_STATE_ILLEGAL_FOR_MODE',
  SHADOW_EMITS_PRODUCTION_CLEAN = 'L8T_SHADOW_EMITS_PRODUCTION_CLEAN',
  FAMILY_ROLLOUT_SCOPE_WIDENED = 'L8T_FAMILY_ROLLOUT_SCOPE_WIDENED',
  FAMILY_PRODUCTION_ENABLED_WITHOUT_TEMPLATES =
    'L8T_FAMILY_ENABLED_WITHOUT_TEMPLATES',
  TEMPLATE_ROLLOUT_PRIORITY_OUT_OF_RANGE = 'L8T_ROLLOUT_PRIORITY_OOR',

  // ── Cleanliness / drift bans (§8.6.5.6 / §8.6.5.7) ──
  TEMPLATE_FAKE_CLEAN_GUARANTEE = 'L8T_FAKE_CLEAN_GUARANTEE',
  TEMPLATE_IGNORES_TRANSITION = 'L8T_IGNORES_TRANSITION',
  TEMPLATE_IGNORES_AMBIGUITY = 'L8T_IGNORES_AMBIGUITY',
  TEMPLATE_SEMANTIC_DRIFT = 'L8T_SEMANTIC_DRIFT',
  TEMPLATE_JUDGMENT_LEAK = 'L8T_JUDGMENT_LEAK',
  TEMPLATE_WIDENS_LOWER_LAYER_RIGHTS = 'L8T_WIDENS_LOWER_LAYER_RIGHTS',
}

export const ALL_L8_REGIME_TEMPLATE_VIOLATION_CODES:
  readonly L8RegimeTemplateViolationCode[] =
    Object.values(L8RegimeTemplateViolationCode);

export interface L8RegimeTemplateViolation {
  readonly code: L8RegimeTemplateViolationCode;
  readonly source: string;
  readonly templateId: string | null;
  readonly family: string | null;
  readonly detail: string;
  readonly context: Record<string, unknown>;
}

export class L8RegimeTemplateError extends Error {
  public readonly code: L8RegimeTemplateViolationCode;
  public readonly details: Record<string, unknown>;

  constructor(
    code: L8RegimeTemplateViolationCode,
    message: string,
    details: Record<string, unknown> = {},
  ) {
    super(`[${code}] ${message}`);
    this.name = 'L8RegimeTemplateError';
    this.code = code;
    this.details = details;
  }
}
