/**
 * L10.8 — Persistence & Serving Violation Codes
 *
 * §10.8.12 — Typed violation codes for every L10.8 validator.
 * Disjoint from L10.1 (`L10_`), L10.2 (`L10O_`), L10.3 (`L10C_`),
 * L10.4 (`L10R_`), L10.5 (`L10E_`), L10.6 (`L10F_`), and L10.7
 * (`L10REL_`) code spaces. L10.8 uses the `L10P_` prefix
 * (persistence).
 */

export enum L10PersistenceViolationCode {
  // ── Persistence principle (§10.8.2 / INV-10.8-A) ──
  PERSIST_NOT_ROUTED_THROUGH_L5 = 'L10P_PERSIST_NOT_ROUTED_THROUGH_L5',
  PERSIST_SURFACE_UNREGISTERED = 'L10P_PERSIST_SURFACE_UNREGISTERED',
  PERSIST_DIRECT_STORE_WRITE = 'L10P_PERSIST_DIRECT_STORE_WRITE',
  PERSIST_MODE_ILLEGAL_FOR_SURFACE =
    'L10P_PERSIST_MODE_ILLEGAL_FOR_SURFACE',
  PERSIST_IDENTITY_FIELD_MISSING = 'L10P_PERSIST_IDENTITY_FIELD_MISSING',
  PERSIST_LINEAGE_FIELD_MISSING = 'L10P_PERSIST_LINEAGE_FIELD_MISSING',
  PERSIST_REPLAY_FIELD_MISSING = 'L10P_PERSIST_REPLAY_FIELD_MISSING',
  PERSIST_EVIDENCE_FIELD_MISSING = 'L10P_PERSIST_EVIDENCE_FIELD_MISSING',
  PERSIST_POLICY_VERSION_MISSING = 'L10P_PERSIST_POLICY_VERSION_MISSING',
  PERSIST_ENVELOPE_ID_MISSING = 'L10P_PERSIST_ENVELOPE_ID_MISSING',
  PERSIST_SUBJECT_ID_MISSING = 'L10P_PERSIST_SUBJECT_ID_MISSING',
  PERSIST_SERVING_CLASS_MISMATCH = 'L10P_PERSIST_SERVING_CLASS_MISMATCH',
  PERSIST_MUTATION_DISCIPLINE_VIOLATED =
    'L10P_PERSIST_MUTATION_DISCIPLINE_VIOLATED',

  // ── Current authority law (§10.8.5 / INV-10.8-B) ──
  CURRENT_AUTHORITY_WRONG_STORE = 'L10P_CURRENT_AUTHORITY_WRONG_STORE',
  CURRENT_AUTHORITY_REDIS_SHADOW = 'L10P_CURRENT_AUTHORITY_REDIS_SHADOW',
  CURRENT_AUTHORITY_ILLEGAL_MODE = 'L10P_CURRENT_AUTHORITY_ILLEGAL_MODE',
  CURRENT_AUTHORITY_SILENT_OVERWRITE =
    'L10P_CURRENT_AUTHORITY_SILENT_OVERWRITE',
  CURRENT_AUTHORITY_SUPERSEDE_SELF_LINK =
    'L10P_CURRENT_AUTHORITY_SUPERSEDE_SELF_LINK',
  CURRENT_AUTHORITY_PRIOR_LINK_MISSING =
    'L10P_CURRENT_AUTHORITY_PRIOR_LINK_MISSING',
  CURRENT_AUTHORITY_REASON_MISSING =
    'L10P_CURRENT_AUTHORITY_REASON_MISSING',
  CURRENT_AUTHORITY_REPAIR_NOT_MARKED =
    'L10P_CURRENT_AUTHORITY_REPAIR_NOT_MARKED',
  CURRENT_AUTHORITY_REPLAY_AS_LIVE =
    'L10P_CURRENT_AUTHORITY_REPLAY_AS_LIVE',
  CURRENT_AUTHORITY_ASPECT_UNREGISTERED =
    'L10P_CURRENT_AUTHORITY_ASPECT_UNREGISTERED',

  // ── Historical surface law (§10.8.4 / INV-10.8-C) ──
  HIST_DESTRUCTIVE_OVERWRITE = 'L10P_HIST_DESTRUCTIVE_OVERWRITE',
  HIST_MUTATES_CURRENT = 'L10P_HIST_MUTATES_CURRENT',
  HIST_CORRECTION_SEMANTICS_MISSING =
    'L10P_HIST_CORRECTION_SEMANTICS_MISSING',
  HIST_REPLAY_IDENTITY_MISSING = 'L10P_HIST_REPLAY_IDENTITY_MISSING',
  HIST_MODE_MISMATCH = 'L10P_HIST_MODE_MISMATCH',
  HIST_LINEAGE_LINK_MISSING = 'L10P_HIST_LINEAGE_LINK_MISSING',

  // ── Evidence storage law (§10.8.6 / INV-10.8-D) ──
  EVID_SUBJECT_LINKAGE_MISSING = 'L10P_EVID_SUBJECT_LINKAGE_MISSING',
  EVID_MANIFEST_LINK_MISSING = 'L10P_EVID_MANIFEST_LINK_MISSING',
  EVID_ARCHIVE_URI_MISSING = 'L10P_EVID_ARCHIVE_URI_MISSING',
  EVID_CHECKSUM_MISSING = 'L10P_EVID_CHECKSUM_MISSING',
  EVID_REPLAY_REF_MISSING = 'L10P_EVID_REPLAY_REF_MISSING',
  EVID_SUBJECT_KIND_MISMATCH = 'L10P_EVID_SUBJECT_KIND_MISMATCH',
  EVID_PATH_NOT_DETERMINISTIC = 'L10P_EVID_PATH_NOT_DETERMINISTIC',
  EVID_CLASS_UNREGISTERED = 'L10P_EVID_CLASS_UNREGISTERED',
  EVID_ORPHAN_BUNDLE = 'L10P_EVID_ORPHAN_BUNDLE',

  // ── Read surface law (§10.8.7 / INV-10.8-E) ──
  READ_SURFACE_UNREGISTERED = 'L10P_READ_SURFACE_UNREGISTERED',
  READ_MODE_ILLEGAL_FOR_SURFACE = 'L10P_READ_MODE_ILLEGAL_FOR_SURFACE',
  READ_CONSUMER_NOT_ALLOWED = 'L10P_READ_CONSUMER_NOT_ALLOWED',
  READ_GUARD_FLAG_MISSING = 'L10P_READ_GUARD_FLAG_MISSING',
  READ_RAW_STORAGE_BYPASS = 'L10P_READ_RAW_STORAGE_BYPASS',
  READ_REPLAY_MODE_ON_NON_REPLAY_SURFACE =
    'L10P_READ_REPLAY_MODE_ON_NON_REPLAY_SURFACE',
  READ_REPAIR_MODE_ON_NON_REPAIR_SURFACE =
    'L10P_READ_REPAIR_MODE_ON_NON_REPAIR_SURFACE',
  READ_CURRENT_FROM_HISTORICAL_ONLY_SURFACE =
    'L10P_READ_CURRENT_FROM_HISTORICAL_ONLY_SURFACE',
  READ_SCOPE_IDENTITY_MISSING = 'L10P_READ_SCOPE_IDENTITY_MISSING',
  READ_WINDOW_INVALID = 'L10P_READ_WINDOW_INVALID',

  // ── Downstream consumption law (§10.8.9 / INV-10.8-F) ──
  DOWNSTREAM_REBUILD_FROM_LOWER_LAYERS =
    'L10P_DOWNSTREAM_REBUILD_FROM_LOWER_LAYERS',
  DOWNSTREAM_CONSUMER_BYPASSED_SURFACE =
    'L10P_DOWNSTREAM_CONSUMER_BYPASSED_SURFACE',
  DOWNSTREAM_ADAPTER_OUTSIDE_GOVERNED_FLOW =
    'L10P_DOWNSTREAM_ADAPTER_OUTSIDE_GOVERNED_FLOW',
  DOWNSTREAM_IGNORES_RESTRICTION = 'L10P_DOWNSTREAM_IGNORES_RESTRICTION',

  // ── Replay / repair law (§10.8.8 / INV-10.8-G) ──
  REPLAY_READ_AS_LIVE_CURRENT = 'L10P_REPLAY_READ_AS_LIVE_CURRENT',
  REPLAY_HASH_MISSING = 'L10P_REPLAY_HASH_MISSING',
  REPAIR_WITHOUT_PARENT_LINEAGE = 'L10P_REPAIR_WITHOUT_PARENT_LINEAGE',
  REPAIR_WITHOUT_REASON = 'L10P_REPAIR_WITHOUT_REASON',
  REPAIR_INVENTED_EVIDENCE = 'L10P_REPAIR_INVENTED_EVIDENCE',
  REPLAY_USES_RAW_STORAGE_BYPASS = 'L10P_REPLAY_USES_RAW_STORAGE_BYPASS',
  REPAIR_MODE_MASQUERADE = 'L10P_REPAIR_MODE_MASQUERADE',

  // ── Materialization readiness (§10.8.10) ──
  MAT_READINESS_BLOCKED = 'L10P_MAT_READINESS_BLOCKED',
  MAT_CONTRACT_INVALID = 'L10P_MAT_CONTRACT_INVALID',
  MAT_EVIDENCE_REQUIRED_MISSING = 'L10P_MAT_EVIDENCE_REQUIRED_MISSING',
  MAT_LINEAGE_INCOMPLETE = 'L10P_MAT_LINEAGE_INCOMPLETE',
  MAT_REPLAY_IDENTITY_MISSING = 'L10P_MAT_REPLAY_IDENTITY_MISSING',
  MAT_MODE_ILLEGAL_FOR_TARGET = 'L10P_MAT_MODE_ILLEGAL_FOR_TARGET',
  MAT_REPAIR_PRETENDS_LIVE = 'L10P_MAT_REPAIR_PRETENDS_LIVE',
  MAT_APPEND_PRETENDS_CURRENT = 'L10P_MAT_APPEND_PRETENDS_CURRENT',
}

export const ALL_L10_PERSISTENCE_VIOLATION_CODES:
  readonly L10PersistenceViolationCode[] =
    Object.values(L10PersistenceViolationCode);

/**
 * §10.8.12 — Tier label so the audit layer can partition results by
 * the law they violate.
 */
export enum L10PersistenceViolationTier {
  PERSISTENCE = 'PERSISTENCE',
  CURRENT_AUTHORITY = 'CURRENT_AUTHORITY',
  HISTORICAL = 'HISTORICAL',
  EVIDENCE = 'EVIDENCE',
  READ_SURFACE = 'READ_SURFACE',
  DOWNSTREAM = 'DOWNSTREAM',
  REPLAY_REPAIR = 'REPLAY_REPAIR',
  MATERIALIZATION = 'MATERIALIZATION',
}

export const ALL_L10_PERSISTENCE_VIOLATION_TIERS:
  readonly L10PersistenceViolationTier[] =
    Object.values(L10PersistenceViolationTier);

export interface L10PersistenceViolation {
  readonly code: L10PersistenceViolationCode;
  readonly tier: L10PersistenceViolationTier;
  readonly detail: string;
  readonly offending_refs?: readonly string[];
}

export class L10PersistenceValidationError extends Error {
  constructor(
    public readonly violations: readonly L10PersistenceViolation[],
  ) {
    super(
      `L10.8 persistence validation failed with ${violations.length} ` +
        `violation(s): ${violations.map(v => v.code).join(', ')}`,
    );
    this.name = 'L10PersistenceValidationError';
  }
}

/**
 * §10.8.12 — Canonical code→tier mapping.
 */
export function l10PersistenceViolationTier(
  code: L10PersistenceViolationCode,
): L10PersistenceViolationTier {
  const s = String(code);
  if (s.startsWith('L10P_PERSIST_'))
    return L10PersistenceViolationTier.PERSISTENCE;
  if (s.startsWith('L10P_CURRENT_AUTHORITY_'))
    return L10PersistenceViolationTier.CURRENT_AUTHORITY;
  if (s.startsWith('L10P_HIST_'))
    return L10PersistenceViolationTier.HISTORICAL;
  if (s.startsWith('L10P_EVID_'))
    return L10PersistenceViolationTier.EVIDENCE;
  if (s.startsWith('L10P_READ_'))
    return L10PersistenceViolationTier.READ_SURFACE;
  if (s.startsWith('L10P_DOWNSTREAM_'))
    return L10PersistenceViolationTier.DOWNSTREAM;
  if (s.startsWith('L10P_REPLAY_') || s.startsWith('L10P_REPAIR_'))
    return L10PersistenceViolationTier.REPLAY_REPAIR;
  if (s.startsWith('L10P_MAT_'))
    return L10PersistenceViolationTier.MATERIALIZATION;
  return L10PersistenceViolationTier.PERSISTENCE;
}
