/**
 * L6.3 — Contract Violation Codes
 *
 * §6.3.7.5 — Audit codes must be typed, machine-readable, deterministic, and
 * stable across runs. These codes are emitted by L6.3 contract validators
 * and consumed by the L6.3 contract audit log.
 */

export enum L6ContractViolationCode {
  DEF_MISSING_BLOCK = 'L6C_DEF_MISSING_BLOCK',
  DEF_MISSING_FIELD = 'L6C_DEF_MISSING_FIELD',
  DEF_INVALID_VERSION = 'L6C_DEF_INVALID_VERSION',
  DEF_INVALID_SCOPE = 'L6C_DEF_INVALID_SCOPE',
  DEF_INVALID_INPUT_ROLE = 'L6C_DEF_INVALID_INPUT_ROLE',
  DEF_MISSING_TRUTH_INPUT = 'L6C_DEF_MISSING_TRUTH_INPUT',
  DEF_MISSING_COVERAGE_REQUIREMENT = 'L6C_DEF_MISSING_COVERAGE',
  DEF_MISSING_FRESHNESS_CLASS = 'L6C_DEF_MISSING_FRESHNESS_CLASS',
  DEF_MISSING_BOUNDS = 'L6C_DEF_MISSING_BOUNDS',
  DEF_MISSING_NORMALIZATION_METHOD = 'L6C_DEF_MISSING_NORM_METHOD',
  DEF_MISSING_LIFECYCLE_COMPLETENESS = 'L6C_DEF_MISSING_LIFECYCLE',
  DEF_MISSING_EVIDENCE_SOURCES = 'L6C_DEF_MISSING_EVIDENCE_SOURCES',
  DEF_MISSING_SUPPRESSION_TAXONOMY = 'L6C_DEF_MISSING_SUPPRESSION_TAX',
  DEF_MISSING_MATERIALIZATION_POLICY = 'L6C_DEF_MISSING_MATERIALIZATION',
  DEF_UNDERLYING_PRIMITIVE_INVALID = 'L6C_DEF_UNDERLYING_INVALID',

  OUT_MISSING_FIELD = 'L6C_OUT_MISSING_FIELD',
  OUT_MISSING_LINEAGE_FIELD = 'L6C_OUT_MISSING_LINEAGE_FIELD',
  OUT_MISSING_REPLAY_HASH = 'L6C_OUT_MISSING_REPLAY_HASH',
  OUT_MISSING_EVIDENCE_REF = 'L6C_OUT_MISSING_EVIDENCE_REF',
  OUT_MISSING_INPUT_SNAPSHOT = 'L6C_OUT_MISSING_INPUT_SNAPSHOT',
  OUT_VALUE_KIND_MISMATCH = 'L6C_OUT_VALUE_KIND_MISMATCH',
  OUT_INVALID_VALIDITY_STATE = 'L6C_OUT_INVALID_VALIDITY_STATE',
  OUT_ILLEGAL_VALID_EMISSION = 'L6C_OUT_ILLEGAL_VALID',
  OUT_INVALID_LIFECYCLE_STATE = 'L6C_OUT_INVALID_LIFECYCLE',
  OUT_IMPOSSIBLE_TIMESTAMP_ORDER = 'L6C_OUT_BAD_TIMESTAMPS',
  OUT_ILLEGAL_CONFIRMATION = 'L6C_OUT_ILLEGAL_CONFIRMATION',
  OUT_MISSING_DEDUPE_KEY = 'L6C_OUT_MISSING_DEDUPE_KEY',
  OUT_MISSING_SUPPRESSION_GROUP = 'L6C_OUT_MISSING_SUPPRESSION_GROUP',
  OUT_UNSTABLE_REPLAY_HASH = 'L6C_OUT_UNSTABLE_REPLAY_HASH',
  OUT_CONTRACT_VERSION_MISMATCH = 'L6C_OUT_CONTRACT_VERSION_MISMATCH',

  COMPAT_INVALID_VERSION_DELTA = 'L6C_COMPAT_INVALID_DELTA',
  COMPAT_BREAKING_SCOPE_CHANGE = 'L6C_COMPAT_BREAKING_SCOPE',
  COMPAT_BREAKING_VALUE_KIND_CHANGE = 'L6C_COMPAT_BREAKING_VALUE_KIND',
  COMPAT_BREAKING_UNIT_CHANGE = 'L6C_COMPAT_BREAKING_UNIT',
  COMPAT_BREAKING_MATERIALIZATION_CHANGE = 'L6C_COMPAT_BREAKING_MATERIALIZATION',
  COMPAT_BREAKING_NORMALIZATION_CHANGE = 'L6C_COMPAT_BREAKING_NORMALIZATION',
  COMPAT_BREAKING_LIFECYCLE_CHANGE = 'L6C_COMPAT_BREAKING_LIFECYCLE',
  COMPAT_BREAKING_DEDUPE_CHANGE = 'L6C_COMPAT_BREAKING_DEDUPE',
  COMPAT_BREAKING_SUPPRESSION_CHANGE = 'L6C_COMPAT_BREAKING_SUPPRESSION',
  COMPAT_BREAKING_TRIGGER_CHANGE = 'L6C_COMPAT_BREAKING_TRIGGER',
  COMPAT_PRIMITIVE_ID_CHANGED = 'L6C_COMPAT_ID_CHANGED',
  COMPAT_VERSION_NOT_MONOTONIC = 'L6C_COMPAT_VERSION_NOT_MONOTONIC',
}

export const ALL_CONTRACT_VIOLATION_CODES: readonly L6ContractViolationCode[] =
  Object.values(L6ContractViolationCode);

export interface L6ContractViolation {
  readonly code: L6ContractViolationCode;
  readonly path: string;
  readonly detail: string;
  readonly context: Record<string, unknown>;
}

export interface L6ContractValidationResult {
  readonly valid: boolean;
  readonly violations: readonly L6ContractViolation[];
}

export function contractOk(): L6ContractValidationResult {
  return { valid: true, violations: [] };
}

export function contractFail(
  violations: readonly L6ContractViolation[],
): L6ContractValidationResult {
  return { valid: violations.length === 0, violations };
}

export function contractMerge(
  ...results: readonly L6ContractValidationResult[]
): L6ContractValidationResult {
  const all: L6ContractViolation[] = [];
  for (const r of results) all.push(...r.violations);
  return { valid: all.length === 0, violations: all };
}

export function contractViolation(
  code: L6ContractViolationCode,
  path: string,
  detail: string,
  context: Record<string, unknown> = {},
): L6ContractViolation {
  return { code, path, detail, context };
}
