/**
 * L14.2 — Delivery Violation Codes
 *
 * §14.2.25 — Disjoint `L14D_` namespace (D = Delivery).
 */

export enum L14DeliveryViolationCode {
  L14D_CHANNEL_UNREGISTERED = 'L14D_CHANNEL_UNREGISTERED',
  L14D_CHANNEL_STATUS_ILLEGAL = 'L14D_CHANNEL_STATUS_ILLEGAL',
  L14D_RESERVED_CHANNEL_PRODUCTION_EMISSION = 'L14D_RESERVED_CHANNEL_PRODUCTION_EMISSION',
  L14D_DELIVERY_CLASS_NOT_ALLOWED_FOR_CHANNEL = 'L14D_DELIVERY_CLASS_NOT_ALLOWED_FOR_CHANNEL',
  L14D_AUDIENCE_CLASS_NOT_ALLOWED_FOR_CHANNEL = 'L14D_AUDIENCE_CLASS_NOT_ALLOWED_FOR_CHANNEL',
  L14D_SOURCE_ARTIFACT_NOT_ALLOWED_FOR_CHANNEL = 'L14D_SOURCE_ARTIFACT_NOT_ALLOWED_FOR_CHANNEL',
  L14D_RENDERING_PROFILE_NOT_ALLOWED_FOR_CHANNEL = 'L14D_RENDERING_PROFILE_NOT_ALLOWED_FOR_CHANNEL',
  L14D_AI_CHAT_REQUIRES_FINAL_L13_ARTIFACT = 'L14D_AI_CHAT_REQUIRES_FINAL_L13_ARTIFACT',
  L14D_TELEGRAM_REQUIRES_FINAL_L13_ALERT_ARTIFACT = 'L14D_TELEGRAM_REQUIRES_FINAL_L13_ALERT_ARTIFACT',
  L14D_INTERNAL_CONSOLE_USER_FACING_LEAK = 'L14D_INTERNAL_CONSOLE_USER_FACING_LEAK',
  L14D_DELIVERY_PAYLOAD_SOURCE_MISSING = 'L14D_DELIVERY_PAYLOAD_SOURCE_MISSING',
  L14D_DELIVERY_PAYLOAD_CONTENT_REF_MISSING = 'L14D_DELIVERY_PAYLOAD_CONTENT_REF_MISSING',
  L14D_DELIVERY_PAYLOAD_DISCLOSURE_REF_MISSING = 'L14D_DELIVERY_PAYLOAD_DISCLOSURE_REF_MISSING',
  L14D_DELIVERY_PAYLOAD_RESTRICTION_REF_MISSING = 'L14D_DELIVERY_PAYLOAD_RESTRICTION_REF_MISSING',
  L14D_DELIVERY_PAYLOAD_LINEAGE_MISSING = 'L14D_DELIVERY_PAYLOAD_LINEAGE_MISSING',
  L14D_DELIVERY_PAYLOAD_REPLAY_HASH_MISSING = 'L14D_DELIVERY_PAYLOAD_REPLAY_HASH_MISSING',
  L14D_ENTITLEMENT_PROFILE_REQUIRED = 'L14D_ENTITLEMENT_PROFILE_REQUIRED',
  L14D_ENTITLEMENT_OPT_IN_MISSING = 'L14D_ENTITLEMENT_OPT_IN_MISSING',
  L14D_ENTITLEMENT_WATCHLIST_MISSING = 'L14D_ENTITLEMENT_WATCHLIST_MISSING',
  L14D_ENTITLEMENT_SUBSCRIPTION_MISSING = 'L14D_ENTITLEMENT_SUBSCRIPTION_MISSING',
  L14D_ENTITLEMENT_INTERNAL_ROLE_MISSING = 'L14D_ENTITLEMENT_INTERNAL_ROLE_MISSING',
  L14D_RENDERING_REGENERATES_MEANING = 'L14D_RENDERING_REGENERATES_MEANING',
  L14D_RENDERING_REMOVES_REQUIRED_DISCLOSURE = 'L14D_RENDERING_REMOVES_REQUIRED_DISCLOSURE',
  L14D_RENDERING_REMOVES_RESTRICTION = 'L14D_RENDERING_REMOVES_RESTRICTION',
  L14D_RENDERING_CONVERTS_CONDITIONAL_TO_CERTAINTY = 'L14D_RENDERING_CONVERTS_CONDITIONAL_TO_CERTAINTY',
  L14D_RENDERING_INTENSIFIES_URGENCY = 'L14D_RENDERING_INTENSIFIES_URGENCY',
  L14D_DELIVERABILITY_STATUS_FALSE_GREEN = 'L14D_DELIVERABILITY_STATUS_FALSE_GREEN',
  L14D_INTERNAL_ONLY_PAYLOAD_MARKED_USER_DELIVERABLE = 'L14D_INTERNAL_ONLY_PAYLOAD_MARKED_USER_DELIVERABLE',
}

export const ALL_L14_DELIVERY_VIOLATION_CODES:
  readonly L14DeliveryViolationCode[] =
  Object.values(L14DeliveryViolationCode);
