/**
 * L14.7 — Calibration Proposal Violation Codes
 *
 * §14.7.49 / §14.7.50 — Disjoint `L14Q_` namespace (Q = Proposal/Queue).
 */

export enum L14CalibrationProposalViolationCode {
  L14Q_PROPOSAL_REQUEST_MISSING = 'L14Q_PROPOSAL_REQUEST_MISSING',
  L14Q_PROPOSAL_CLASS_MISSING = 'L14Q_PROPOSAL_CLASS_MISSING',
  L14Q_SOURCE_EVIDENCE_REFS_MISSING = 'L14Q_SOURCE_EVIDENCE_REFS_MISSING',
  L14Q_EVIDENCE_NOT_PROPOSAL_ELIGIBLE = 'L14Q_EVIDENCE_NOT_PROPOSAL_ELIGIBLE',
  L14Q_HUMAN_REVIEW_ONLY_EVIDENCE_PROMOTED_TO_FORMAL_PROPOSAL = 'L14Q_HUMAN_REVIEW_ONLY_EVIDENCE_PROMOTED_TO_FORMAL_PROPOSAL',
  L14Q_COUNTEREVIDENCE_BLOCKED_PROPOSAL_GENERATED = 'L14Q_COUNTEREVIDENCE_BLOCKED_PROPOSAL_GENERATED',
  L14Q_PROPOSAL_CLASS_EVIDENCE_CLASS_MISMATCH = 'L14Q_PROPOSAL_CLASS_EVIDENCE_CLASS_MISMATCH',
  L14Q_AFFECTED_LAYER_CLASS_MISMATCH = 'L14Q_AFFECTED_LAYER_CLASS_MISMATCH',
  L14Q_AFFECTED_TARGET_MAPPING_MISSING = 'L14Q_AFFECTED_TARGET_MAPPING_MISSING',
  L14Q_ILLEGAL_TARGET_CLASS_FOR_PROPOSAL = 'L14Q_ILLEGAL_TARGET_CLASS_FOR_PROPOSAL',
  L14Q_MUTATION_REQUESTED_BY_PROPOSAL = 'L14Q_MUTATION_REQUESTED_BY_PROPOSAL',
  L14Q_AUTOMATIC_APPLICATION_FLAG_NOT_FALSE = 'L14Q_AUTOMATIC_APPLICATION_FLAG_NOT_FALSE',
  L14Q_REQUIRES_REVIEW_FLAG_NOT_TRUE = 'L14Q_REQUIRES_REVIEW_FLAG_NOT_TRUE',
  L14Q_PROPOSAL_SUMMARY_MISSING = 'L14Q_PROPOSAL_SUMMARY_MISSING',
  L14Q_PROPOSED_ACTION_MISSING = 'L14Q_PROPOSED_ACTION_MISSING',
  L14Q_PROPOSED_ACTION_TOO_EXECUTABLE = 'L14Q_PROPOSED_ACTION_TOO_EXECUTABLE',
  L14Q_PROPOSAL_ACTION_CLASS_ILLEGAL = 'L14Q_PROPOSAL_ACTION_CLASS_ILLEGAL',
  L14Q_NON_CLAIMS_MISSING = 'L14Q_NON_CLAIMS_MISSING',
  L14Q_COUNTEREVIDENCE_NOT_DISCLOSED = 'L14Q_COUNTEREVIDENCE_NOT_DISCLOSED',
  L14Q_EVIDENCE_PACK_MISSING = 'L14Q_EVIDENCE_PACK_MISSING',
  L14Q_REVIEW_PRIORITY_UNSUPPORTED = 'L14Q_REVIEW_PRIORITY_UNSUPPORTED',
  L14Q_RECERTIFICATION_REQUIRED_BUT_MISSING = 'L14Q_RECERTIFICATION_REQUIRED_BUT_MISSING',
  L14Q_RECERTIFICATION_SCOPE_FALSE_GREEN = 'L14Q_RECERTIFICATION_SCOPE_FALSE_GREEN',
  L14Q_READINESS_FALSE_GREEN = 'L14Q_READINESS_FALSE_GREEN',
  L14Q_REVIEW_QUEUE_MISSING = 'L14Q_REVIEW_QUEUE_MISSING',
  L14Q_LOWER_LAYER_HANDOFF_MISSING = 'L14Q_LOWER_LAYER_HANDOFF_MISSING',
  L14Q_HANDOFF_LAYER_MISMATCH = 'L14Q_HANDOFF_LAYER_MISMATCH',
  L14Q_HUMAN_REVIEW_NOTE_MISSING_FOR_REVIEW_ONLY_EVIDENCE = 'L14Q_HUMAN_REVIEW_NOTE_MISSING_FOR_REVIEW_ONLY_EVIDENCE',
  L14Q_LINEAGE_MISSING = 'L14Q_LINEAGE_MISSING',
  L14Q_REPLAY_HASH_MISSING = 'L14Q_REPLAY_HASH_MISSING',
}

export const ALL_L14_CALIBRATION_PROPOSAL_VIOLATION_CODES:
  readonly L14CalibrationProposalViolationCode[] =
  Object.values(L14CalibrationProposalViolationCode);
