/**
 * L14.3 — Runtime Violation Codes
 *
 * §14.3.52 — Disjoint `L14R_` namespace (R = Runtime/Routing).
 */

export enum L14RuntimeViolationCode {
  L14R_RUNTIME_REQUEST_MISSING = 'L14R_RUNTIME_REQUEST_MISSING',
  L14R_RUNTIME_CONTEXT_MISSING = 'L14R_RUNTIME_CONTEXT_MISSING',
  L14R_STAGE_ORDER_ILLEGAL = 'L14R_STAGE_ORDER_ILLEGAL',
  L14R_STAGE_MUTATION_AFTER_SEAL = 'L14R_STAGE_MUTATION_AFTER_SEAL',
  L14R_DELIVERY_CANDIDATE_MISSING = 'L14R_DELIVERY_CANDIDATE_MISSING',
  L14R_CANDIDATE_SOURCE_UNGOVERNED = 'L14R_CANDIDATE_SOURCE_UNGOVERNED',
  L14R_ELIGIBILITY_FALSE_GREEN = 'L14R_ELIGIBILITY_FALSE_GREEN',
  L14R_INELIGIBLE_CANDIDATE_ROUTED = 'L14R_INELIGIBLE_CANDIDATE_ROUTED',
  L14R_AUDIENCE_RESOLUTION_MISSING = 'L14R_AUDIENCE_RESOLUTION_MISSING',
  L14R_AUDIENCE_NOT_ALLOWED_FOR_CHANNEL = 'L14R_AUDIENCE_NOT_ALLOWED_FOR_CHANNEL',
  L14R_CHANNEL_RESOLUTION_MISSING = 'L14R_CHANNEL_RESOLUTION_MISSING',
  L14R_CHANNEL_RESERVED_ROUTED = 'L14R_CHANNEL_RESERVED_ROUTED',
  L14R_CHANNEL_CONTRACT_IGNORED = 'L14R_CHANNEL_CONTRACT_IGNORED',
  L14R_ENTITLEMENT_BINDING_MISSING = 'L14R_ENTITLEMENT_BINDING_MISSING',
  L14R_MUTED_CHANNEL_EXECUTED = 'L14R_MUTED_CHANNEL_EXECUTED',
  L14R_MUTED_ALERT_CLASS_EXECUTED = 'L14R_MUTED_ALERT_CLASS_EXECUTED',
  L14R_QUIET_HOURS_EXECUTION_ILLEGAL = 'L14R_QUIET_HOURS_EXECUTION_ILLEGAL',
  L14R_FREQUENCY_CAP_EXECUTION_ILLEGAL = 'L14R_FREQUENCY_CAP_EXECUTION_ILLEGAL',
  L14R_PRIORITY_PROFILE_MISSING = 'L14R_PRIORITY_PROFILE_MISSING',
  L14R_PRIORITY_SCORE_OUT_OF_BOUNDS = 'L14R_PRIORITY_SCORE_OUT_OF_BOUNDS',
  L14R_PRIORITY_CLASS_MISMATCH = 'L14R_PRIORITY_CLASS_MISMATCH',
  L14R_PRIORITY_IGNORES_RESTRICTION_CAP = 'L14R_PRIORITY_IGNORES_RESTRICTION_CAP',
  L14R_URGENCY_PROFILE_MISSING = 'L14R_URGENCY_PROFILE_MISSING',
  L14R_FALSE_URGENCY_ESCALATION = 'L14R_FALSE_URGENCY_ESCALATION',
  L14R_DIGEST_ELIGIBLE_MARKED_IMMEDIATE = 'L14R_DIGEST_ELIGIBLE_MARKED_IMMEDIATE',
  L14R_DUPLICATION_CHECK_MISSING = 'L14R_DUPLICATION_CHECK_MISSING',
  L14R_DUPLICATE_ALERT_EXECUTED = 'L14R_DUPLICATE_ALERT_EXECUTED',
  L14R_COOLDOWN_CHECK_MISSING = 'L14R_COOLDOWN_CHECK_MISSING',
  L14R_COOLDOWN_ACTIVE_EXECUTED = 'L14R_COOLDOWN_ACTIVE_EXECUTED',
  L14R_COOLDOWN_OVERRIDE_WITHOUT_REASON = 'L14R_COOLDOWN_OVERRIDE_WITHOUT_REASON',
  L14R_SUPPRESSION_REQUIRED_BUT_MISSING = 'L14R_SUPPRESSION_REQUIRED_BUT_MISSING',
  L14R_SUPPRESSION_SILENT = 'L14R_SUPPRESSION_SILENT',
  L14R_MERGE_REQUIRED_BUT_NOT_RECORDED = 'L14R_MERGE_REQUIRED_BUT_NOT_RECORDED',
  L14R_PAYLOAD_ASSEMBLY_BEFORE_DISPOSITION = 'L14R_PAYLOAD_ASSEMBLY_BEFORE_DISPOSITION',
  L14R_PAYLOAD_ASSEMBLY_RENDERING_ILLEGAL = 'L14R_PAYLOAD_ASSEMBLY_RENDERING_ILLEGAL',
  L14R_EXECUTION_WITHOUT_PAYLOAD = 'L14R_EXECUTION_WITHOUT_PAYLOAD',
  L14R_EXECUTION_BEFORE_DELIVERABILITY = 'L14R_EXECUTION_BEFORE_DELIVERABILITY',
  L14R_EXECUTION_RETRY_REGENERATED_MEANING = 'L14R_EXECUTION_RETRY_REGENERATED_MEANING',
  L14R_MATERIALIZATION_INTENT_MISSING = 'L14R_MATERIALIZATION_INTENT_MISSING',
  L14R_FEEDBACK_EXPECTATION_MISSING = 'L14R_FEEDBACK_EXPECTATION_MISSING',
  L14R_LINEAGE_MISSING = 'L14R_LINEAGE_MISSING',
  L14R_REPLAY_HASH_MISSING = 'L14R_REPLAY_HASH_MISSING',
}

export const ALL_L14_RUNTIME_VIOLATION_CODES:
  readonly L14RuntimeViolationCode[] =
  Object.values(L14RuntimeViolationCode);
