/**
 * L14.6 — Calibration Evidence Violation Codes
 *
 * §14.6.65 / §14.6.66 — Disjoint `L14E_` namespace (E = Evidence).
 */

export enum L14CalibrationEvidenceViolationCode {
  L14E_REQUEST_MISSING = 'L14E_REQUEST_MISSING',
  L14E_EVIDENCE_CLASS_MISSING = 'L14E_EVIDENCE_CLASS_MISSING',
  L14E_SUBJECT_REF_MISSING = 'L14E_SUBJECT_REF_MISSING',
  L14E_EVIDENCE_WINDOW_MISSING = 'L14E_EVIDENCE_WINDOW_MISSING',
  L14E_SAMPLE_SIZE_MISSING = 'L14E_SAMPLE_SIZE_MISSING',
  L14E_SAMPLE_INSUFFICIENT_BUT_PROMOTED = 'L14E_SAMPLE_INSUFFICIENT_BUT_PROMOTED',
  L14E_SAMPLE_SUFFICIENCY_CLASS_FALSE_GREEN = 'L14E_SAMPLE_SUFFICIENCY_CLASS_FALSE_GREEN',
  L14E_STRUCTURED_FINDINGS_MISSING = 'L14E_STRUCTURED_FINDINGS_MISSING',
  L14E_AGGREGATE_COMPUTATION_MISSING = 'L14E_AGGREGATE_COMPUTATION_MISSING',
  L14E_COUNTEREVIDENCE_HIDDEN = 'L14E_COUNTEREVIDENCE_HIDDEN',
  L14E_BEHAVIOR_USED_FOR_OUTCOME_ONLY_CLASS = 'L14E_BEHAVIOR_USED_FOR_OUTCOME_ONLY_CLASS',
  L14E_FEEDBACK_TREATED_AS_CORRECTNESS = 'L14E_FEEDBACK_TREATED_AS_CORRECTNESS',
  L14E_ENGAGEMENT_COLLAPSED_INTO_TRUTH = 'L14E_ENGAGEMENT_COLLAPSED_INTO_TRUTH',
  L14E_THRESHOLD_NOISE_WITHOUT_OUTCOME_WEAKNESS = 'L14E_THRESHOLD_NOISE_WITHOUT_OUTCOME_WEAKNESS',
  L14E_HYPOTHESIS_FAILURE_PATTERN_WITHOUT_INVALIDATION_EVIDENCE = 'L14E_HYPOTHESIS_FAILURE_PATTERN_WITHOUT_INVALIDATION_EVIDENCE',
  L14E_SCENARIO_CONFIDENCE_REVIEW_WITHOUT_MISALIGNMENT = 'L14E_SCENARIO_CONFIDENCE_REVIEW_WITHOUT_MISALIGNMENT',
  L14E_ALERT_USEFULNESS_DECLARED_FROM_OPEN_RATE_ONLY = 'L14E_ALERT_USEFULNESS_DECLARED_FROM_OPEN_RATE_ONLY',
  L14E_FEATURE_IMPORTANCE_STATED_CAUSALLY = 'L14E_FEATURE_IMPORTANCE_STATED_CAUSALLY',
  L14E_REVIEW_PRIORITY_UNSUPPORTED = 'L14E_REVIEW_PRIORITY_UNSUPPORTED',
  L14E_PROPOSAL_ELIGIBILITY_OVERSTATED = 'L14E_PROPOSAL_ELIGIBILITY_OVERSTATED',
  L14E_PROPOSAL_ELIGIBILITY_GRANTED_DESPITE_COUNTEREVIDENCE = 'L14E_PROPOSAL_ELIGIBILITY_GRANTED_DESPITE_COUNTEREVIDENCE',
  L14E_AFFECTED_TARGETS_MISSING = 'L14E_AFFECTED_TARGETS_MISSING',
  L14E_MUTATION_ALLOWED_IN_L14_6 = 'L14E_MUTATION_ALLOWED_IN_L14_6',
  L14E_WINDOW_INCOMPATIBLE_HORIZONS_MERGED = 'L14E_WINDOW_INCOMPATIBLE_HORIZONS_MERGED',
  L14E_COHORT_DEFINITION_MISSING = 'L14E_COHORT_DEFINITION_MISSING',
  L14E_REGIME_COMPARISON_REQUIRED_BUT_MISSING = 'L14E_REGIME_COMPARISON_REQUIRED_BUT_MISSING',
  L14E_CONFIDENCE_CLASS_MISSING = 'L14E_CONFIDENCE_CLASS_MISSING',
  L14E_CONFIDENCE_CLASS_FALSE_GREEN = 'L14E_CONFIDENCE_CLASS_FALSE_GREEN',
  L14E_LINEAGE_MISSING = 'L14E_LINEAGE_MISSING',
  L14E_REPLAY_HASH_MISSING = 'L14E_REPLAY_HASH_MISSING',
}

export const ALL_L14_CALIBRATION_EVIDENCE_VIOLATION_CODES:
  readonly L14CalibrationEvidenceViolationCode[] =
  Object.values(L14CalibrationEvidenceViolationCode);
