/**
 * L14.8 — Persistence Violation Codes
 *
 * §14.8.44 / §14.8.45 — Disjoint `L14P_` namespace (P = Persistence/Processing).
 */

export enum L14PersistenceViolationCode {
  L14P_L5_ROUTE_MISSING = 'L14P_L5_ROUTE_MISSING',
  L14P_DIRECT_WRITE_ATTEMPT = 'L14P_DIRECT_WRITE_ATTEMPT',
  L14P_UNKNOWN_DURABLE_SURFACE = 'L14P_UNKNOWN_DURABLE_SURFACE',
  L14P_ILLEGAL_MATERIALIZATION_MODE = 'L14P_ILLEGAL_MATERIALIZATION_MODE',
  L14P_LINEAGE_REFS_MISSING = 'L14P_LINEAGE_REFS_MISSING',
  L14P_REPLAY_HASH_MISSING = 'L14P_REPLAY_HASH_MISSING',
  L14P_APPEND_ONLY_SURFACE_MUTATION_ATTEMPT = 'L14P_APPEND_ONLY_SURFACE_MUTATION_ATTEMPT',
  L14P_CURRENT_REGISTRY_WRITE_WITHOUT_SUPERSESSION = 'L14P_CURRENT_REGISTRY_WRITE_WITHOUT_SUPERSESSION',
  L14P_REGISTRY_NOT_RECOMPUTABLE_FROM_HISTORY = 'L14P_REGISTRY_NOT_RECOMPUTABLE_FROM_HISTORY',
  L14P_HISTORICAL_FACT_SOURCE_REF_MISSING = 'L14P_HISTORICAL_FACT_SOURCE_REF_MISSING',
  L14P_HISTORICAL_FACT_FAMILY_MISMATCH = 'L14P_HISTORICAL_FACT_FAMILY_MISMATCH',
  L14P_READ_SURFACE_UNKNOWN = 'L14P_READ_SURFACE_UNKNOWN',
  L14P_READ_MODE_NOT_ALLOWED = 'L14P_READ_MODE_NOT_ALLOWED',
  L14P_READ_CONSUMER_NOT_ALLOWED = 'L14P_READ_CONSUMER_NOT_ALLOWED',
  L14P_CACHE_CLAIMED_AUTHORITY = 'L14P_CACHE_CLAIMED_AUTHORITY',
  L14P_DELIVERY_REPLAY_POLICY_REF_MISSING = 'L14P_DELIVERY_REPLAY_POLICY_REF_MISSING',
  L14P_DELIVERY_REPLAY_PREFERENCE_SNAPSHOT_MISSING = 'L14P_DELIVERY_REPLAY_PREFERENCE_SNAPSHOT_MISSING',
  L14P_DELIVERY_REPLAY_ARTIFACT_MISMATCH = 'L14P_DELIVERY_REPLAY_ARTIFACT_MISMATCH',
  L14P_SUPPRESSION_REPLAY_REASON_MISMATCH = 'L14P_SUPPRESSION_REPLAY_REASON_MISMATCH',
  L14P_INTERACTION_TIMELINE_REPLAY_MISMATCH = 'L14P_INTERACTION_TIMELINE_REPLAY_MISMATCH',
  L14P_REPAIR_SOURCE_HISTORY_MISSING = 'L14P_REPAIR_SOURCE_HISTORY_MISSING',
  L14P_REPAIR_ATTEMPTED_HISTORICAL_MUTATION = 'L14P_REPAIR_ATTEMPTED_HISTORICAL_MUTATION',
  L14P_REPAIR_ATTEMPTED_INTERACTION_INVENTION = 'L14P_REPAIR_ATTEMPTED_INTERACTION_INVENTION',
  L14P_REPAIR_ATTEMPTED_FEEDBACK_REWRITE = 'L14P_REPAIR_ATTEMPTED_FEEDBACK_REWRITE',
  L14P_REPAIR_ATTEMPTED_OUTCOME_FABRICATION = 'L14P_REPAIR_ATTEMPTED_OUTCOME_FABRICATION',
  L14P_ALERT_PERFORMANCE_FACT_SOURCE_INCOMPLETE = 'L14P_ALERT_PERFORMANCE_FACT_SOURCE_INCOMPLETE',
  L14P_CHANNEL_HEALTH_FACT_SOURCE_INCOMPLETE = 'L14P_CHANNEL_HEALTH_FACT_SOURCE_INCOMPLETE',
  L14P_CALIBRATION_QUEUE_REGISTRY_MISMATCH = 'L14P_CALIBRATION_QUEUE_REGISTRY_MISMATCH',
  L14P_CHANNEL_HEALTH_REGISTRY_MISMATCH = 'L14P_CHANNEL_HEALTH_REGISTRY_MISMATCH',
  L14P_AUDIT_EVENT_NOT_DETERMINISTIC = 'L14P_AUDIT_EVENT_NOT_DETERMINISTIC',
}
export const ALL_L14_PERSISTENCE_VIOLATION_CODES:
  readonly L14PersistenceViolationCode[] =
  Object.values(L14PersistenceViolationCode);
