/**
 * L14.10 — Final Certification Violation Codes
 *
 * §14.10.46 / §14.10.47 — Disjoint `L14F_` namespace (F = Final).
 */

export enum L14FinalViolationCode {
  L14F_FINAL_DEFINITION_MISSING = 'L14F_FINAL_DEFINITION_MISSING',
  L14F_COMPLETION_STANDARD_MISSING = 'L14F_COMPLETION_STANDARD_MISSING',
  L14F_REQUIRED_SUBLAYER_NOT_GREEN = 'L14F_REQUIRED_SUBLAYER_NOT_GREEN',
  L14F_REQUIRED_BAND_NOT_GREEN = 'L14F_REQUIRED_BAND_NOT_GREEN',
  L14F_FINAL_INVARIANT_FAILED = 'L14F_FINAL_INVARIANT_FAILED',
  L14F_EXTERNAL_REGRESSION_FAILED = 'L14F_EXTERNAL_REGRESSION_FAILED',
  L14F_ROLLOUT_GATE_NOT_APPROVED = 'L14F_ROLLOUT_GATE_NOT_APPROVED',
  L14F_FREEZE_NOT_ACTIVATED = 'L14F_FREEZE_NOT_ACTIVATED',
  L14F_RATIFICATION_ARTIFACT_BLOCKED = 'L14F_RATIFICATION_ARTIFACT_BLOCKED',
  L14F_ARCHITECTURE_COMPLETION_BLOCKED = 'L14F_ARCHITECTURE_COMPLETION_BLOCKED',
  L14F_CRITICAL_BREACH_PRESENT = 'L14F_CRITICAL_BREACH_PRESENT',
  L14F_FINAL_FINGERPRINT_UNSTABLE = 'L14F_FINAL_FINGERPRINT_UNSTABLE',
  L14F_UPSTREAM_FINGERPRINT_MISSING = 'L14F_UPSTREAM_FINGERPRINT_MISSING',
  L14F_PUSH_RESERVED_STATUS_NOT_PRESERVED = 'L14F_PUSH_RESERVED_STATUS_NOT_PRESERVED',
  L14F_TELEGRAM_GATE_NOT_VALID = 'L14F_TELEGRAM_GATE_NOT_VALID',
  L14F_USER_CONTROL_LAW_NOT_VALID = 'L14F_USER_CONTROL_LAW_NOT_VALID',
  L14F_EXPERIMENT_NON_CORRUPTION_NOT_VALID = 'L14F_EXPERIMENT_NON_CORRUPTION_NOT_VALID',
  L14F_CALIBRATION_NON_AUTO_MUTATION_NOT_VALID = 'L14F_CALIBRATION_NON_AUTO_MUTATION_NOT_VALID',
  L14F_REPLAY_REPAIR_HONESTY_NOT_VALID = 'L14F_REPLAY_REPAIR_HONESTY_NOT_VALID',
  L14F_EXTENSION_CLASSIFICATION_MISSING = 'L14F_EXTENSION_CLASSIFICATION_MISSING',
  L14F_PROHIBITED_POST_FREEZE_CHANGE = 'L14F_PROHIBITED_POST_FREEZE_CHANGE',
  L14F_AUDIT_EVENT_NOT_DETERMINISTIC = 'L14F_AUDIT_EVENT_NOT_DETERMINISTIC',
}
export const ALL_L14_FINAL_VIOLATION_CODES:
  readonly L14FinalViolationCode[] =
  Object.values(L14FinalViolationCode);
