/**
 * L14.5 — Outcome Violation Codes
 *
 * §14.5.67 / §14.5.68 — Disjoint `L14O_` namespace (O = Outcome).
 */

export enum L14OutcomeViolationCode {
  L14O_EVALUATION_REQUEST_MISSING = 'L14O_EVALUATION_REQUEST_MISSING',
  L14O_EVALUATED_ARTIFACT_REF_MISSING = 'L14O_EVALUATED_ARTIFACT_REF_MISSING',
  L14O_UNREGISTERED_ARTIFACT_CLASS = 'L14O_UNREGISTERED_ARTIFACT_CLASS',
  L14O_HORIZON_MISSING = 'L14O_HORIZON_MISSING',
  L14O_HORIZON_NOT_ELAPSED_BUT_FINALIZED = 'L14O_HORIZON_NOT_ELAPSED_BUT_FINALIZED',
  L14O_HORIZON_SOURCE_ILLEGAL = 'L14O_HORIZON_SOURCE_ILLEGAL',
  L14O_REALIZED_OUTCOME_REF_MISSING = 'L14O_REALIZED_OUTCOME_REF_MISSING',
  L14O_REALIZED_FACTS_INCOMPLETE_BUT_MARKED_ALIGNED = 'L14O_REALIZED_FACTS_INCOMPLETE_BUT_MARKED_ALIGNED',
  L14O_CALIBRATION_TARGET_REQUIRED_BUT_MISSING = 'L14O_CALIBRATION_TARGET_REQUIRED_BUT_MISSING',
  L14O_EXPECTED_EFFECT_PROFILE_MISSING = 'L14O_EXPECTED_EFFECT_PROFILE_MISSING',
  L14O_EXPECTED_EFFECT_CLASS_ILLEGAL_FOR_ARTIFACT = 'L14O_EXPECTED_EFFECT_CLASS_ILLEGAL_FOR_ARTIFACT',
  L14O_SCORE_EVALUATED_WITHOUT_L11_TARGET = 'L14O_SCORE_EVALUATED_WITHOUT_L11_TARGET',
  L14O_HYPOTHESIS_EVALUATED_BY_PRICE_ONLY = 'L14O_HYPOTHESIS_EVALUATED_BY_PRICE_ONLY',
  L14O_SCENARIO_EVALUATED_AS_BINARY_PREDICTION = 'L14O_SCENARIO_EVALUATED_AS_BINARY_PREDICTION',
  L14O_TRIGGER_EVALUATED_WITHOUT_DOWNSTREAM_EFFECT = 'L14O_TRIGGER_EVALUATED_WITHOUT_DOWNSTREAM_EFFECT',
  L14O_INVALIDATION_EVALUATED_BY_PRICE_DIP_ONLY = 'L14O_INVALIDATION_EVALUATED_BY_PRICE_DIP_ONLY',
  L14O_ALERT_EVALUATED_BY_OPEN_RATE = 'L14O_ALERT_EVALUATED_BY_OPEN_RATE',
  L14O_EXPLANATION_EVALUATED_AS_STYLE_SCORE = 'L14O_EXPLANATION_EVALUATED_AS_STYLE_SCORE',
  L14O_ALIGNMENT_FALSE_GREEN = 'L14O_ALIGNMENT_FALSE_GREEN',
  L14O_MISALIGNMENT_HIDDEN = 'L14O_MISALIGNMENT_HIDDEN',
  L14O_INCONCLUSIVE_FORCED_TO_ALIGNED = 'L14O_INCONCLUSIVE_FORCED_TO_ALIGNED',
  L14O_NOT_YET_EVALUABLE_FORCED_TO_VERDICT = 'L14O_NOT_YET_EVALUABLE_FORCED_TO_VERDICT',
  L14O_FALSE_POSITIVE_DECLARED_FROM_IMMEDIATE_PRICE_MOVE = 'L14O_FALSE_POSITIVE_DECLARED_FROM_IMMEDIATE_PRICE_MOVE',
  L14O_FALSE_NEGATIVE_WITHOUT_ELIGIBLE_OMISSION_BASIS = 'L14O_FALSE_NEGATIVE_WITHOUT_ELIGIBLE_OMISSION_BASIS',
  L14O_CONFIDENCE_ACCURACY_MISSING_WHEN_REQUIRED = 'L14O_CONFIDENCE_ACCURACY_MISSING_WHEN_REQUIRED',
  L14O_OVERCONFIDENCE_HIDDEN = 'L14O_OVERCONFIDENCE_HIDDEN',
  L14O_REGIME_CONTEXT_MISSING_WHEN_REQUIRED = 'L14O_REGIME_CONTEXT_MISSING_WHEN_REQUIRED',
  L14O_REGIME_SHIFT_IGNORED = 'L14O_REGIME_SHIFT_IGNORED',
  L14O_ALERT_EFFECTIVENESS_COLLAPSES_BEHAVIOR_INTO_TRUTH = 'L14O_ALERT_EFFECTIVENESS_COLLAPSES_BEHAVIOR_INTO_TRUTH',
  L14O_LINEAGE_MISSING = 'L14O_LINEAGE_MISSING',
  L14O_REPLAY_HASH_MISSING = 'L14O_REPLAY_HASH_MISSING',
}

export const ALL_L14_OUTCOME_VIOLATION_CODES:
  readonly L14OutcomeViolationCode[] =
  Object.values(L14OutcomeViolationCode);
