/**
 * L14.4 — Interaction Violation Codes
 *
 * §14.4.43 — Disjoint `L14I_` namespace (I = Interaction).
 */

export enum L14InteractionViolationCode {
  L14I_INTERACTION_EVENT_ID_MISSING = 'L14I_INTERACTION_EVENT_ID_MISSING',
  L14I_INTERACTION_TYPE_MISSING = 'L14I_INTERACTION_TYPE_MISSING',
  L14I_INTERACTION_CONTEXT_MISSING = 'L14I_INTERACTION_CONTEXT_MISSING',
  L14I_OCCURRED_AT_MISSING = 'L14I_OCCURRED_AT_MISSING',
  L14I_RAW_USER_IDENTIFIER_PRESENT = 'L14I_RAW_USER_IDENTIFIER_PRESENT',
  L14I_USER_HASH_REQUIRED_BUT_MISSING = 'L14I_USER_HASH_REQUIRED_BUT_MISSING',
  L14I_ALERT_EVENT_MISSING_EXECUTION_REF = 'L14I_ALERT_EVENT_MISSING_EXECUTION_REF',
  L14I_CHAT_FOLLOWUP_MISSING_PRIOR_OUTPUT_REF = 'L14I_CHAT_FOLLOWUP_MISSING_PRIOR_OUTPUT_REF',
  L14I_REPORT_SAVE_MISSING_REPORT_REF = 'L14I_REPORT_SAVE_MISSING_REPORT_REF',
  L14I_WATCHLIST_ACTION_MISSING_SCOPE_REF = 'L14I_WATCHLIST_ACTION_MISSING_SCOPE_REF',
  L14I_FEEDBACK_EVENT_MISSING_L13_FEEDBACK_REF = 'L14I_FEEDBACK_EVENT_MISSING_L13_FEEDBACK_REF',
  L14I_ATTRIBUTION_QUALITY_ILLEGAL = 'L14I_ATTRIBUTION_QUALITY_ILLEGAL',
  L14I_DIRECT_ATTRIBUTION_WITHOUT_SOURCE_REF = 'L14I_DIRECT_ATTRIBUTION_WITHOUT_SOURCE_REF',
  L14I_WEAK_ATTRIBUTION_PRESENTED_AS_DIRECT = 'L14I_WEAK_ATTRIBUTION_PRESENTED_AS_DIRECT',
  L14I_DUPLICATE_EVENT_DOUBLE_COUNTED = 'L14I_DUPLICATE_EVENT_DOUBLE_COUNTED',
  L14I_DEDUPLICATION_KEY_MISSING = 'L14I_DEDUPLICATION_KEY_MISSING',
  L14I_IGNORED_DERIVED_BEFORE_WINDOW_ELAPSED = 'L14I_IGNORED_DERIVED_BEFORE_WINDOW_ELAPSED',
  L14I_IGNORED_DERIVED_AFTER_FAILED_DELIVERY = 'L14I_IGNORED_DERIVED_AFTER_FAILED_DELIVERY',
  L14I_IGNORED_DERIVED_DESPITE_QUALIFYING_INTERACTION = 'L14I_IGNORED_DERIVED_DESPITE_QUALIFYING_INTERACTION',
  L14I_DISMISSED_AND_IGNORED_CONFLATED = 'L14I_DISMISSED_AND_IGNORED_CONFLATED',
  L14I_BEHAVIOR_INTERPRETED_AS_CORRECTNESS = 'L14I_BEHAVIOR_INTERPRETED_AS_CORRECTNESS',
  L14I_FEEDBACK_INTERPRETED_AS_TRUTH = 'L14I_FEEDBACK_INTERPRETED_AS_TRUTH',
  L14I_REPORT_SAVE_INTERPRETED_AS_FACTUAL_VALIDATION = 'L14I_REPORT_SAVE_INTERPRETED_AS_FACTUAL_VALIDATION',
  L14I_ALERT_IGNORE_INTERPRETED_AS_WRONG_ALERT = 'L14I_ALERT_IGNORE_INTERPRETED_AS_WRONG_ALERT',
  L14I_CONVERSION_RECORD_MISSING_TARGET = 'L14I_CONVERSION_RECORD_MISSING_TARGET',
  L14I_CONVERSION_ATTRIBUTION_ILLEGAL = 'L14I_CONVERSION_ATTRIBUTION_ILLEGAL',
  L14I_EXPECTATION_RESOLUTION_MISSING_EXPECTATION_REF = 'L14I_EXPECTATION_RESOLUTION_MISSING_EXPECTATION_REF',
  L14I_EXPECTATION_EXPIRED_WITHOUT_RESOLUTION = 'L14I_EXPECTATION_EXPIRED_WITHOUT_RESOLUTION',
  L14I_LINEAGE_MISSING = 'L14I_LINEAGE_MISSING',
  L14I_REPLAY_HASH_MISSING = 'L14I_REPLAY_HASH_MISSING',
}

export const ALL_L14_INTERACTION_VIOLATION_CODES:
  readonly L14InteractionViolationCode[] =
  Object.values(L14InteractionViolationCode);
