/**
 * L14.9 — Live Operations Violation Codes
 *
 * §14.9.55 / §14.9.56 — Disjoint `L14L_` namespace (L = Live operations).
 */

export enum L14LiveOperationsViolationCode {
  L14L_CHANNEL_ROLLOUT_STATUS_ILLEGAL = 'L14L_CHANNEL_ROLLOUT_STATUS_ILLEGAL',
  L14L_RESERVED_PUSH_ENABLEMENT_ATTEMPT = 'L14L_RESERVED_PUSH_ENABLEMENT_ATTEMPT',
  L14L_TELEGRAM_GATE_MISSING_OPT_IN = 'L14L_TELEGRAM_GATE_MISSING_OPT_IN',
  L14L_TELEGRAM_GATE_BINDING_MISSING = 'L14L_TELEGRAM_GATE_BINDING_MISSING',
  L14L_TELEGRAM_HEALTH_BELOW_THRESHOLD = 'L14L_TELEGRAM_HEALTH_BELOW_THRESHOLD',
  L14L_ALERT_CLASS_ROLLOUT_STATUS_ILLEGAL = 'L14L_ALERT_CLASS_ROLLOUT_STATUS_ILLEGAL',
  L14L_ALERT_CLASS_CHANNEL_NOT_ALLOWED = 'L14L_ALERT_CLASS_CHANNEL_NOT_ALLOWED',
  L14L_PREFERENCE_PROFILE_CONFLICTING_CHANNEL_STATE = 'L14L_PREFERENCE_PROFILE_CONFLICTING_CHANNEL_STATE',
  L14L_PREFERENCE_PROFILE_CONFLICTING_ALERT_CLASS_STATE = 'L14L_PREFERENCE_PROFILE_CONFLICTING_ALERT_CLASS_STATE',
  L14L_PREFERENCE_PROFILE_CAP_INVALID = 'L14L_PREFERENCE_PROFILE_CAP_INVALID',
  L14L_PREFERENCE_SNAPSHOT_MISSING = 'L14L_PREFERENCE_SNAPSHOT_MISSING',
  L14L_QUIET_HOURS_PROFILE_INVALID = 'L14L_QUIET_HOURS_PROFILE_INVALID',
  L14L_QUIET_HOURS_OVERRIDE_ILLEGAL = 'L14L_QUIET_HOURS_OVERRIDE_ILLEGAL',
  L14L_FREQUENCY_CAP_BYPASS_ILLEGAL = 'L14L_FREQUENCY_CAP_BYPASS_ILLEGAL',
  L14L_DIGEST_DOWNGRADE_POLICY_MISSING = 'L14L_DIGEST_DOWNGRADE_POLICY_MISSING',
  L14L_SEVERITY_OVERRIDE_POLICY_MISSING = 'L14L_SEVERITY_OVERRIDE_POLICY_MISSING',
  L14L_SEVERITY_OVERRIDE_USED_ON_INELIGIBLE_ALERT = 'L14L_SEVERITY_OVERRIDE_USED_ON_INELIGIBLE_ALERT',
  L14L_EXPERIMENT_SURFACE_PROHIBITED = 'L14L_EXPERIMENT_SURFACE_PROHIBITED',
  L14L_EXPERIMENT_TRUTH_MUTATION_ATTEMPT = 'L14L_EXPERIMENT_TRUTH_MUTATION_ATTEMPT',
  L14L_EXPERIMENT_SAFETY_MUTATION_ATTEMPT = 'L14L_EXPERIMENT_SAFETY_MUTATION_ATTEMPT',
  L14L_EXPERIMENT_GROUNDING_MUTATION_ATTEMPT = 'L14L_EXPERIMENT_GROUNDING_MUTATION_ATTEMPT',
  L14L_EXPERIMENT_DISCLOSURE_MUTATION_ATTEMPT = 'L14L_EXPERIMENT_DISCLOSURE_MUTATION_ATTEMPT',
  L14L_EXPERIMENT_ASSIGNMENT_NOT_DETERMINISTIC = 'L14L_EXPERIMENT_ASSIGNMENT_NOT_DETERMINISTIC',
  L14L_EXPERIMENT_METRIC_NOT_ALLOWED = 'L14L_EXPERIMENT_METRIC_NOT_ALLOWED',
  L14L_OPERATIONAL_SIGNAL_SOURCE_READ_SURFACE_MISSING = 'L14L_OPERATIONAL_SIGNAL_SOURCE_READ_SURFACE_MISSING',
  L14L_OPERATIONAL_INCIDENT_WITHOUT_PLAYBOOK = 'L14L_OPERATIONAL_INCIDENT_WITHOUT_PLAYBOOK',
  L14L_PLAYBOOK_PROHIBITED_ACTION_PRESENT = 'L14L_PLAYBOOK_PROHIBITED_ACTION_PRESENT',
  L14L_ANALYST_ACTION_ATTEMPTED_LOWER_LAYER_MUTATION = 'L14L_ANALYST_ACTION_ATTEMPTED_LOWER_LAYER_MUTATION',
  L14L_ANALYST_ACTION_ATTEMPTED_HISTORY_MUTATION = 'L14L_ANALYST_ACTION_ATTEMPTED_HISTORY_MUTATION',
  L14L_ANALYST_ACTION_ATTEMPTED_USER_PREFERENCE_BYPASS = 'L14L_ANALYST_ACTION_ATTEMPTED_USER_PREFERENCE_BYPASS',
  L14L_AUDIT_EVENT_NOT_DETERMINISTIC = 'L14L_AUDIT_EVENT_NOT_DETERMINISTIC',
}
export const ALL_L14_LIVE_OPERATIONS_VIOLATION_CODES:
  readonly L14LiveOperationsViolationCode[] =
  Object.values(L14LiveOperationsViolationCode);
