/**
 * 🗄️ COINET RETENTION PRISMA CLIENT
 * 
 * Provides type-safe access to retention-specific Prisma models.
 * 
 * After running `npx prisma generate`, this will have full type support for:
 * - UserSession
 * - UserQuery
 * - NotificationDelivery
 * - RetentionReward
 * - UserLifecycleState
 * - UserInvestmentAction
 * - RetentionABTest
 * - UserABTestAssignment
 * - RetentionMetricsDaily
 * - RetentionFailureEvent
 * - MarketRegimeState
 * - CoinStateSnapshot
 * 
 * @module retention/prisma-retention
 * @version 1.0.0
 */

import { PrismaClient } from '@prisma/client';

// Export a dynamically-typed prisma instance for retention models
// This avoids TypeScript errors before `prisma generate` is run
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const prismaRetention: any = new PrismaClient();

// Type aliases for documentation (actual types generated by Prisma)
export type UserSessionModel = {
  id: string;
  userId: string;
  sessionStart: Date;
  sessionEnd?: Date | null;
  entryTrigger?: string | null;
  deviceType?: string | null;
  platform?: string | null;
  queriesCount: number;
  rewardsViewed: number;
  actionsCompleted: number;
  createdAt: Date;
};

export type UserQueryModel = {
  id: string;
  userId: string;
  sessionId?: string | null;
  query: string;
  symbols: string[];
  intent?: string | null;
  responseTimeMs?: number | null;
  wasHelpful?: boolean | null;
  createdAt: Date;
};

export type NotificationDeliveryModel = {
  id: string;
  userId: string;
  type: string;
  channel: string;
  title: string;
  body: string;
  symbol?: string | null;
  priority: string;
  status: string;
  scheduledFor?: Date | null;
  sentAt?: Date | null;
  openedAt?: Date | null;
  clickedAt?: Date | null;
  abTestId?: string | null;
  variant?: string | null;
  createdAt: Date;
};

export type RetentionRewardModel = {
  id: string;
  userId: string;
  category: string;
  type: string;
  title: string;
  body: string;
  cta: string;
  symbol?: string | null;
  metadata: Record<string, unknown>;
  signalStrength: number;
  dataQuality: number;
  surfaceType: string;
  isViewed: boolean;
  viewedAt?: Date | null;
  isClicked: boolean;
  clickedAt?: Date | null;
  expiresAt?: Date | null;
  createdAt: Date;
};

export type UserLifecycleStateModel = {
  id: string;
  userId: string;
  segment: string;
  segmentEnteredAt: Date;
  daysSinceSignup: number;
  totalSessions: number;
  sessionsLast7Days: number;
  currentStreak: number;
  longestStreak: number;
  watchlistSize: number;
  alertsConfigured: number;
  portfolioShared: boolean;
  riskToleranceSet: boolean;
  morningDigestEnabled: boolean;
  churnProbability: number;
  lastSessionDate?: Date | null;
  updatedAt: Date;
  createdAt: Date;
};

export type UserInvestmentActionModel = {
  id: string;
  userId: string;
  action: string;
  metadata: Record<string, unknown>;
  promptShown: boolean;
  promptAccepted?: boolean | null;
  skippedUntil?: Date | null;
  completedAt?: Date | null;
  createdAt: Date;
};

export type RetentionABTestModel = {
  id: string;
  name: string;
  type: string;
  hypothesis: string;
  variants: unknown;
  trafficSplit: unknown;
  targetSegments: string[];
  minSampleSize: number;
  primaryMetric: string;
  secondaryMetrics: string[];
  expectedRisk: string;
  status: string;
  startedAt?: Date | null;
  endedAt?: Date | null;
  createdAt: Date;
};

export type UserABTestAssignmentModel = {
  id: string;
  userId: string;
  testId: string;
  variant: string;
  assignedAt: Date;
  convertedAt?: Date | null;
  conversionValue?: number | null;
};

export type RetentionMetricsDailyModel = {
  id: string;
  date: Date;
  weeklyActiveUsers: number;
  dailyActiveUsers: number;
  dailyHabitFormationRate: number;
  medianTimeToFirstInsight: number;
  watchlistReturnRate: number;
  omniscoreEngagementDepth: number;
  alertResponseRate: number;
  notificationCtr: number;
  avgSessionsPerUser: number;
  churnRate: number;
  createdAt: Date;
};

export type RetentionFailureEventModel = {
  id: string;
  type: string;
  severity: string;
  userId?: string | null;
  description: string;
  metadata: Record<string, unknown>;
  isResolved: boolean;
  resolvedAt?: Date | null;
  resolution?: string | null;
  detectedAt: Date;
  createdAt: Date;
};

export type MarketRegimeStateModel = {
  id: string;
  regime: string;
  previousRegime?: string | null;
  fearGreedIndex: number;
  fearGreedLabel: string;
  isStable: boolean;
  changedAt: Date;
  summary: string;
  createdAt: Date;
};

export type CoinStateSnapshotModel = {
  id: string;
  symbol: string;
  price: number;
  change24h: number;
  omniscore?: number | null;
  quadrant?: string | null;
  snapshotTime: Date;
  createdAt: Date;
};

// Helper function to check if retention models exist
export function areRetentionModelsAvailable(): boolean {
  try {
    return typeof prismaRetention.userSession !== 'undefined';
  } catch {
    return false;
  }
}
