/**
 * L9.8 — Persistence & Serving Violation Codes
 *
 * §9.8.12 — Typed violation codes for every L9.8 validator. Disjoint
 * from the L9.1 (`L9_`), L9.2 (`L9O_`), L9.3 (`L9C_`), L9.4 (`L9R_`),
 * L9.5 (`L9T_`), L9.6 (`L9F_`), and L9.7 (`L9REL_`) code spaces. L9.8
 * uses the `L9P_` prefix (persistence).
 */

export enum L9PersistenceViolationCode {
  // ── Persistence principle (§9.8.2 / INV-9.8-A) ──
  PERSIST_NOT_ROUTED_THROUGH_L5 = 'L9P_PERSIST_NOT_ROUTED_THROUGH_L5',
  PERSIST_SURFACE_UNREGISTERED = 'L9P_PERSIST_SURFACE_UNREGISTERED',
  PERSIST_DIRECT_STORE_WRITE = 'L9P_PERSIST_DIRECT_STORE_WRITE',
  PERSIST_MODE_ILLEGAL_FOR_SURFACE =
    'L9P_PERSIST_MODE_ILLEGAL_FOR_SURFACE',
  PERSIST_IDENTITY_FIELD_MISSING = 'L9P_PERSIST_IDENTITY_FIELD_MISSING',
  PERSIST_LINEAGE_FIELD_MISSING = 'L9P_PERSIST_LINEAGE_FIELD_MISSING',
  PERSIST_REPLAY_FIELD_MISSING = 'L9P_PERSIST_REPLAY_FIELD_MISSING',
  PERSIST_EVIDENCE_FIELD_MISSING = 'L9P_PERSIST_EVIDENCE_FIELD_MISSING',
  PERSIST_POLICY_VERSION_MISSING = 'L9P_PERSIST_POLICY_VERSION_MISSING',
  PERSIST_ENVELOPE_ID_MISSING = 'L9P_PERSIST_ENVELOPE_ID_MISSING',
  PERSIST_SUBJECT_ID_MISSING = 'L9P_PERSIST_SUBJECT_ID_MISSING',
  PERSIST_SERVING_CLASS_MISMATCH = 'L9P_PERSIST_SERVING_CLASS_MISMATCH',
  PERSIST_MUTATION_DISCIPLINE_VIOLATED =
    'L9P_PERSIST_MUTATION_DISCIPLINE_VIOLATED',

  // ── Current authority law (§9.8.5 / INV-9.8-B) ──
  CURRENT_AUTHORITY_WRONG_STORE = 'L9P_CURRENT_AUTHORITY_WRONG_STORE',
  CURRENT_AUTHORITY_REDIS_SHADOW = 'L9P_CURRENT_AUTHORITY_REDIS_SHADOW',
  CURRENT_AUTHORITY_ILLEGAL_MODE = 'L9P_CURRENT_AUTHORITY_ILLEGAL_MODE',
  CURRENT_AUTHORITY_SILENT_OVERWRITE =
    'L9P_CURRENT_AUTHORITY_SILENT_OVERWRITE',
  CURRENT_AUTHORITY_SUPERSEDE_SELF_LINK =
    'L9P_CURRENT_AUTHORITY_SUPERSEDE_SELF_LINK',
  CURRENT_AUTHORITY_PRIOR_LINK_MISSING =
    'L9P_CURRENT_AUTHORITY_PRIOR_LINK_MISSING',
  CURRENT_AUTHORITY_REASON_MISSING = 'L9P_CURRENT_AUTHORITY_REASON_MISSING',
  CURRENT_AUTHORITY_REPAIR_NOT_MARKED =
    'L9P_CURRENT_AUTHORITY_REPAIR_NOT_MARKED',
  CURRENT_AUTHORITY_REPLAY_AS_LIVE = 'L9P_CURRENT_AUTHORITY_REPLAY_AS_LIVE',
  CURRENT_AUTHORITY_ASPECT_UNREGISTERED =
    'L9P_CURRENT_AUTHORITY_ASPECT_UNREGISTERED',

  // ── Historical surface law (§9.8.4 / INV-9.8-C) ──
  HIST_DESTRUCTIVE_OVERWRITE = 'L9P_HIST_DESTRUCTIVE_OVERWRITE',
  HIST_MUTATES_CURRENT = 'L9P_HIST_MUTATES_CURRENT',
  HIST_CORRECTION_SEMANTICS_MISSING =
    'L9P_HIST_CORRECTION_SEMANTICS_MISSING',
  HIST_REPLAY_IDENTITY_MISSING = 'L9P_HIST_REPLAY_IDENTITY_MISSING',
  HIST_MODE_MISMATCH = 'L9P_HIST_MODE_MISMATCH',
  HIST_LINEAGE_LINK_MISSING = 'L9P_HIST_LINEAGE_LINK_MISSING',

  // ── Evidence storage law (§9.8.6 / INV-9.8-D) ──
  EVID_SUBJECT_LINKAGE_MISSING = 'L9P_EVID_SUBJECT_LINKAGE_MISSING',
  EVID_MANIFEST_LINK_MISSING = 'L9P_EVID_MANIFEST_LINK_MISSING',
  EVID_ARCHIVE_URI_MISSING = 'L9P_EVID_ARCHIVE_URI_MISSING',
  EVID_CHECKSUM_MISSING = 'L9P_EVID_CHECKSUM_MISSING',
  EVID_REPLAY_REF_MISSING = 'L9P_EVID_REPLAY_REF_MISSING',
  EVID_SUBJECT_KIND_MISMATCH = 'L9P_EVID_SUBJECT_KIND_MISMATCH',
  EVID_PATH_NOT_DETERMINISTIC = 'L9P_EVID_PATH_NOT_DETERMINISTIC',
  EVID_CLASS_UNREGISTERED = 'L9P_EVID_CLASS_UNREGISTERED',
  EVID_ORPHAN_BUNDLE = 'L9P_EVID_ORPHAN_BUNDLE',

  // ── Read surface law (§9.8.7 / INV-9.8-E) ──
  READ_SURFACE_UNREGISTERED = 'L9P_READ_SURFACE_UNREGISTERED',
  READ_MODE_ILLEGAL_FOR_SURFACE = 'L9P_READ_MODE_ILLEGAL_FOR_SURFACE',
  READ_CONSUMER_NOT_ALLOWED = 'L9P_READ_CONSUMER_NOT_ALLOWED',
  READ_GUARD_FLAG_MISSING = 'L9P_READ_GUARD_FLAG_MISSING',
  READ_RAW_STORAGE_BYPASS = 'L9P_READ_RAW_STORAGE_BYPASS',
  READ_REPLAY_MODE_ON_NON_REPLAY_SURFACE =
    'L9P_READ_REPLAY_MODE_ON_NON_REPLAY_SURFACE',
  READ_REPAIR_MODE_ON_NON_REPAIR_SURFACE =
    'L9P_READ_REPAIR_MODE_ON_NON_REPAIR_SURFACE',
  READ_CURRENT_FROM_HISTORICAL_ONLY_SURFACE =
    'L9P_READ_CURRENT_FROM_HISTORICAL_ONLY_SURFACE',
  READ_SCOPE_IDENTITY_MISSING = 'L9P_READ_SCOPE_IDENTITY_MISSING',
  READ_WINDOW_INVALID = 'L9P_READ_WINDOW_INVALID',

  // ── Downstream consumption law (§9.8.9 / INV-9.8-F) ──
  DOWNSTREAM_REBUILD_FROM_LOWER_LAYERS =
    'L9P_DOWNSTREAM_REBUILD_FROM_LOWER_LAYERS',
  DOWNSTREAM_CONSUMER_BYPASSED_SURFACE =
    'L9P_DOWNSTREAM_CONSUMER_BYPASSED_SURFACE',
  DOWNSTREAM_ADAPTER_OUTSIDE_GOVERNED_FLOW =
    'L9P_DOWNSTREAM_ADAPTER_OUTSIDE_GOVERNED_FLOW',
  DOWNSTREAM_IGNORES_RESTRICTION = 'L9P_DOWNSTREAM_IGNORES_RESTRICTION',

  // ── Replay / repair law (§9.8.8 / INV-9.8-G) ──
  REPLAY_READ_AS_LIVE_CURRENT = 'L9P_REPLAY_READ_AS_LIVE_CURRENT',
  REPLAY_HASH_MISSING = 'L9P_REPLAY_HASH_MISSING',
  REPAIR_WITHOUT_PARENT_LINEAGE = 'L9P_REPAIR_WITHOUT_PARENT_LINEAGE',
  REPAIR_WITHOUT_REASON = 'L9P_REPAIR_WITHOUT_REASON',
  REPAIR_INVENTED_EVIDENCE = 'L9P_REPAIR_INVENTED_EVIDENCE',
  REPLAY_USES_RAW_STORAGE_BYPASS = 'L9P_REPLAY_USES_RAW_STORAGE_BYPASS',
  REPAIR_MODE_MASQUERADE = 'L9P_REPAIR_MODE_MASQUERADE',

  // ── Materialization readiness (§9.8.10) ──
  MAT_READINESS_BLOCKED = 'L9P_MAT_READINESS_BLOCKED',
  MAT_CONTRACT_INVALID = 'L9P_MAT_CONTRACT_INVALID',
  MAT_EVIDENCE_REQUIRED_MISSING = 'L9P_MAT_EVIDENCE_REQUIRED_MISSING',
  MAT_LINEAGE_INCOMPLETE = 'L9P_MAT_LINEAGE_INCOMPLETE',
  MAT_REPLAY_IDENTITY_MISSING = 'L9P_MAT_REPLAY_IDENTITY_MISSING',
  MAT_MODE_ILLEGAL_FOR_TARGET = 'L9P_MAT_MODE_ILLEGAL_FOR_TARGET',
  MAT_REPAIR_PRETENDS_LIVE = 'L9P_MAT_REPAIR_PRETENDS_LIVE',
  MAT_APPEND_PRETENDS_CURRENT = 'L9P_MAT_APPEND_PRETENDS_CURRENT',
}

export const ALL_L9_PERSISTENCE_VIOLATION_CODES:
  readonly L9PersistenceViolationCode[] =
    Object.values(L9PersistenceViolationCode);

/**
 * §9.8.12.1 — Tier label so the audit layer can partition results by
 * the law they violate (parallels L9.6 / L9.7 tier enums).
 */
export enum L9PersistenceViolationTier {
  PERSISTENCE = 'PERSISTENCE',
  CURRENT_AUTHORITY = 'CURRENT_AUTHORITY',
  HISTORICAL = 'HISTORICAL',
  EVIDENCE = 'EVIDENCE',
  READ_SURFACE = 'READ_SURFACE',
  DOWNSTREAM = 'DOWNSTREAM',
  REPLAY_REPAIR = 'REPLAY_REPAIR',
  MATERIALIZATION = 'MATERIALIZATION',
}

export const ALL_L9_PERSISTENCE_VIOLATION_TIERS:
  readonly L9PersistenceViolationTier[] =
    Object.values(L9PersistenceViolationTier);

export interface L9PersistenceViolation {
  readonly code: L9PersistenceViolationCode;
  readonly tier: L9PersistenceViolationTier;
  readonly detail: string;
  readonly offending_refs?: readonly string[];
}

export class L9PersistenceValidationError extends Error {
  constructor(
    public readonly violations: readonly L9PersistenceViolation[],
  ) {
    super(
      `L9.8 persistence validation failed with ${violations.length} ` +
        `violation(s): ${violations.map(v => v.code).join(', ')}`,
    );
    this.name = 'L9PersistenceValidationError';
  }
}

/**
 * §9.8.12 — Canonical code→tier mapping.
 */
export function l9PersistenceViolationTier(
  code: L9PersistenceViolationCode,
): L9PersistenceViolationTier {
  const s = String(code);
  if (s.startsWith('L9P_PERSIST_')) return L9PersistenceViolationTier.PERSISTENCE;
  if (s.startsWith('L9P_CURRENT_AUTHORITY_'))
    return L9PersistenceViolationTier.CURRENT_AUTHORITY;
  if (s.startsWith('L9P_HIST_')) return L9PersistenceViolationTier.HISTORICAL;
  if (s.startsWith('L9P_EVID_')) return L9PersistenceViolationTier.EVIDENCE;
  if (s.startsWith('L9P_READ_')) return L9PersistenceViolationTier.READ_SURFACE;
  if (s.startsWith('L9P_DOWNSTREAM_'))
    return L9PersistenceViolationTier.DOWNSTREAM;
  if (s.startsWith('L9P_REPLAY_') || s.startsWith('L9P_REPAIR_'))
    return L9PersistenceViolationTier.REPLAY_REPAIR;
  if (s.startsWith('L9P_MAT_'))
    return L9PersistenceViolationTier.MATERIALIZATION;
  return L9PersistenceViolationTier.PERSISTENCE;
}
