// ====== PRODUCTION DATABASE TYPES ======
// This file defines the database schema types that will be generated by Supabase

export interface User {
  id: string;
  email: string;
  created_at: string;
  updated_at: string;
  last_sign_in_at?: string;
}

export interface UserProfile {
  id: string;
  email?: string;
  first_name?: string;
  last_name?: string;
  avatar_url?: string;
  bio?: string;
  created_at: string;
  updated_at: string;
}

export interface ChatSession {
  id: string;
  user_id: string;
  title: string;
  preview: string;
  agent_id?: string;
  status: 'active' | 'archived' | 'deleted';
  metadata: {
    total_messages: number;
    last_activity: string;
    tags?: string[];
  };
  created_at: string;
  updated_at: string;
}

export interface ChatMessage {
  id: string;
  session_id: string;
  user_id: string;
  content: string;
  role: 'user' | 'assistant' | 'system';
  agent_id?: string;
  metadata: {
    tokens_used?: number;
    processing_time?: number;
    model_version?: string;
    confidence_score?: number;
  };
  created_at: string;
}

export interface SavedAgent {
  id: string;
  user_id: string;
  name: string;
  description: string;
  configuration: any; // JSON field matching CustomAgent type
  is_public: boolean;
  is_active: boolean;
  usage_stats: {
    total_sessions: number;
    avg_rating: number;
    last_used: string;
  };
  created_at: string;
  updated_at: string;
}

export interface Alert {
  id: string;
  user_id: string;
  agent_id?: string;
  name: string;
  description: string;
  conditions: any; // JSON field for alert conditions
  notification_channels: ('email' | 'push' | 'webhook')[];
  is_active: boolean;
  triggered_at?: string;
  trigger_count: number;
  metadata: any;
  created_at: string;
  updated_at: string;
}

export interface MarketData {
  id: string;
  symbol: string;
  price: number;
  price_change_24h: number;
  volume_24h: number;
  market_cap: number;
  timestamp: string;
  source: 'coingecko' | 'binance' | 'coinbase' | 'internal';
  metadata: any;
  created_at: string;
}

export interface TechnicalIndicator {
  id: string;
  symbol: string;
  indicator_type: 'rsi' | 'macd' | 'bollinger' | 'sma' | 'ema' | 'stochastic';
  timeframe: string;
  value: number;
  signal?: 'buy' | 'sell' | 'neutral';
  confidence?: number;
  timestamp: string;
  created_at: string;
}

export interface NewsArticle {
  id: string;
  title: string;
  content: string;
  url: string;
  source: string;
  sentiment_score: number;
  impact_score: number;
  mentioned_symbols: string[];
  published_at: string;
  processed_at: string;
}

export interface BacktestSession {
  id: string;
  user_id: string;
  agent_id: string;
  name: string;
  parameters: {
    start_date: string;
    end_date: string;
    initial_capital: number;
    symbols: string[];
    strategy_config: any;
  };
  results: {
    total_return: number;
    sharpe_ratio: number;
    max_drawdown: number;
    win_rate: number;
    total_trades: number;
  };
  status: 'running' | 'completed' | 'failed';
  progress: number;
  created_at: string;
  completed_at?: string;
}

export interface UserPortfolio {
  id: string;
  user_id: string;
  name: string;
  is_paper_trading: boolean;
  initial_value: number;
  current_value: number;
  positions: {
    symbol: string;
    quantity: number;
    avg_price: number;
    current_price: number;
    pnl: number;
  }[];
  performance_history: {
    date: string;
    value: number;
    return_pct: number;
  }[];
  created_at: string;
  updated_at: string;
}

export interface FeedbackTracking {
  id: string;
  user_id: string;
  first_feedback_submitted_at: string | null;
  second_feedback_submitted_at: string | null;
  feedback_count: number;
  dismissed_count: number;
  created_at: string;
  updated_at: string;
}

// Database query result types
export type DatabaseResult<T> = {
  data: T | null;
  error: Error | null;
}

export type DatabaseListResult<T> = {
  data: T[] | null;
  error: Error | null;
  count?: number;
}

// Real-time subscription types
export type RealtimeChannel = 'market_data' | 'chat_messages' | 'alerts' | 'portfolio_updates';

export interface RealtimeEvent<T = any> {
  eventType: 'INSERT' | 'UPDATE' | 'DELETE';
  new?: T;
  old?: T;
  table: string;
  schema: string;
}
