/**
 * L5.7 Assurance — Error Codes
 */

export enum L5AssuranceErrorCode {
  REPLAY_LINEAGE_GAP = 'L5_ASSUR_REPLAY_LINEAGE_GAP',
  REPLAY_CHECKSUM_MISMATCH = 'L5_ASSUR_REPLAY_CHECKSUM_MISMATCH',
  REPLAY_FIDELITY_UNMET = 'L5_ASSUR_REPLAY_FIDELITY_UNMET',
  REPLAY_ILLEGAL_MUTATION = 'L5_ASSUR_REPLAY_ILLEGAL_MUTATION',
  REPLAY_MISSING_EVIDENCE = 'L5_ASSUR_REPLAY_MISSING_EVIDENCE',
  REPAIR_INVENTED_TRUTH = 'L5_ASSUR_REPAIR_INVENTED_TRUTH',
  REPAIR_EXHAUSTED = 'L5_ASSUR_REPAIR_EXHAUSTED',
  REPAIR_ILLEGAL_MUTATION = 'L5_ASSUR_REPAIR_ILLEGAL_MUTATION',
  FAILURE_INVISIBLE = 'L5_ASSUR_FAILURE_INVISIBLE',
  SECURITY_UNAUTHORIZED_WRITE = 'L5_ASSUR_SECURITY_UNAUTHORIZED_WRITE',
  SECURITY_UNAUTHORIZED_READ = 'L5_ASSUR_SECURITY_UNAUTHORIZED_READ',
  SECURITY_PII_VIOLATION = 'L5_ASSUR_SECURITY_PII_VIOLATION',
  SECURITY_PUBLIC_EXPOSURE = 'L5_ASSUR_SECURITY_PUBLIC_EXPOSURE',
  DONE_GATE_FAILED = 'L5_ASSUR_DONE_GATE_FAILED',
}

export class L5AssuranceError extends Error {
  public readonly code: L5AssuranceErrorCode;
  public readonly details: Record<string, unknown>;

  constructor(code: L5AssuranceErrorCode, message: string, details: Record<string, unknown> = {}) {
    super(`[${code}] ${message}`);
    this.name = 'L5AssuranceError';
    this.code = code;
    this.details = details;
  }
}
