/**
 * L5.7 Assurance — Failure Ontology
 *
 * §5.7.7 — Seven failure families (F1–F7) with exhaustive failure codes.
 */

export enum L5FailureFamily {
  F1_INGRESS_VALIDATION = 'F1_INGRESS_VALIDATION',
  F2_QUARANTINE_SEMANTIC = 'F2_QUARANTINE_SEMANTIC',
  F3_ARCHIVE_INTEGRITY = 'F3_ARCHIVE_INTEGRITY',
  F4_TRANSACTION_COORDINATION = 'F4_TRANSACTION_COORDINATION',
  F5_PROJECTION_MATERIALIZATION = 'F5_PROJECTION_MATERIALIZATION',
  F6_SECURITY_ACCESS = 'F6_SECURITY_ACCESS',
  F7_REPLAY_REPAIR = 'F7_REPLAY_REPAIR',
}

export enum L5FailureCode {
  // F1 — Ingress and validation
  VALIDATION_REJECTED = 'VALIDATION_REJECTED',
  MISSING_CANONICAL_REFERENCE = 'MISSING_CANONICAL_REFERENCE',
  MISSING_METRIC_CONTRACT = 'MISSING_METRIC_CONTRACT',
  ILLEGAL_PRODUCER_LAYER = 'ILLEGAL_PRODUCER_LAYER',
  ILLEGAL_RIGHTS_USAGE = 'ILLEGAL_RIGHTS_USAGE',
  INVALID_TIMESTAMP_ORDER = 'INVALID_TIMESTAMP_ORDER',
  PAYLOAD_PROJECTION_MISMATCH = 'PAYLOAD_PROJECTION_MISMATCH',

  // F2 — Quarantine and semantic conflict
  QUARANTINED_IDENTITY = 'QUARANTINED_IDENTITY',
  QUARANTINED_SCHEMA = 'QUARANTINED_SCHEMA',
  DUPLICATE_PAYLOAD_CONFLICT = 'DUPLICATE_PAYLOAD_CONFLICT',
  LATE_DATA_REQUIRES_REVIEW = 'LATE_DATA_REQUIRES_REVIEW',
  PROJECTION_CONTRADICTION = 'PROJECTION_CONTRADICTION',
  UNRESOLVED_IDENTITY_FOR_RESOLVED_CLASS = 'UNRESOLVED_IDENTITY_FOR_RESOLVED_CLASS',

  // F3 — Archive and integrity
  ARCHIVE_WRITE_FAILED = 'ARCHIVE_WRITE_FAILED',
  CHECKSUM_MISMATCH = 'CHECKSUM_MISMATCH',
  ARCHIVE_POINTER_MISSING = 'ARCHIVE_POINTER_MISSING',
  ARCHIVE_TAG_POLICY_VIOLATION = 'ARCHIVE_TAG_POLICY_VIOLATION',
  REPLAY_BUNDLE_CORRUPTED = 'REPLAY_BUNDLE_CORRUPTED',

  // F4 — Transaction and coordination
  POSTGRES_TX_FAILED = 'POSTGRES_TX_FAILED',
  MANIFEST_TRANSITION_ILLEGAL = 'MANIFEST_TRANSITION_ILLEGAL',
  OUTBOX_EMIT_FAILED = 'OUTBOX_EMIT_FAILED',
  FINALIZATION_BLOCKED = 'FINALIZATION_BLOCKED',
  REQUIRED_PROJECTION_MISSING = 'REQUIRED_PROJECTION_MISSING',

  // F5 — Projection and materialization
  CLICKHOUSE_PROJECTION_FAILED = 'CLICKHOUSE_PROJECTION_FAILED',
  REDIS_PROJECTION_FAILED = 'REDIS_PROJECTION_FAILED',
  MATERIALIZATION_FAILED = 'MATERIALIZATION_FAILED',
  PROJECTION_IDEMPOTENCY_VIOLATION = 'PROJECTION_IDEMPOTENCY_VIOLATION',
  STALE_PROJECTION_RESURRECTION_ATTEMPT = 'STALE_PROJECTION_RESURRECTION_ATTEMPT',

  // F6 — Security and access
  UNAUTHORIZED_WRITE_ATTEMPT = 'UNAUTHORIZED_WRITE_ATTEMPT',
  UNAUTHORIZED_REPLAY_ATTEMPT = 'UNAUTHORIZED_REPLAY_ATTEMPT',
  UNAUTHORIZED_ARTIFACT_ACCESS = 'UNAUTHORIZED_ARTIFACT_ACCESS',
  PUBLIC_BUCKET_EXPOSURE = 'PUBLIC_BUCKET_EXPOSURE',
  PII_POLICY_VIOLATION = 'PII_POLICY_VIOLATION',

  // F7 — Replay and repair
  REPLAY_LINEAGE_GAP = 'REPLAY_LINEAGE_GAP',
  REPAIR_EXHAUSTED = 'REPAIR_EXHAUSTED',
  REPAIR_ILLEGAL_MUTATION_ATTEMPT = 'REPAIR_ILLEGAL_MUTATION_ATTEMPT',
  REMATERIALIZATION_POLICY_MISSING = 'REMATERIALIZATION_POLICY_MISSING',
}

export const FAILURE_FAMILY_MAP: Record<L5FailureCode, L5FailureFamily> = {
  [L5FailureCode.VALIDATION_REJECTED]: L5FailureFamily.F1_INGRESS_VALIDATION,
  [L5FailureCode.MISSING_CANONICAL_REFERENCE]: L5FailureFamily.F1_INGRESS_VALIDATION,
  [L5FailureCode.MISSING_METRIC_CONTRACT]: L5FailureFamily.F1_INGRESS_VALIDATION,
  [L5FailureCode.ILLEGAL_PRODUCER_LAYER]: L5FailureFamily.F1_INGRESS_VALIDATION,
  [L5FailureCode.ILLEGAL_RIGHTS_USAGE]: L5FailureFamily.F1_INGRESS_VALIDATION,
  [L5FailureCode.INVALID_TIMESTAMP_ORDER]: L5FailureFamily.F1_INGRESS_VALIDATION,
  [L5FailureCode.PAYLOAD_PROJECTION_MISMATCH]: L5FailureFamily.F1_INGRESS_VALIDATION,

  [L5FailureCode.QUARANTINED_IDENTITY]: L5FailureFamily.F2_QUARANTINE_SEMANTIC,
  [L5FailureCode.QUARANTINED_SCHEMA]: L5FailureFamily.F2_QUARANTINE_SEMANTIC,
  [L5FailureCode.DUPLICATE_PAYLOAD_CONFLICT]: L5FailureFamily.F2_QUARANTINE_SEMANTIC,
  [L5FailureCode.LATE_DATA_REQUIRES_REVIEW]: L5FailureFamily.F2_QUARANTINE_SEMANTIC,
  [L5FailureCode.PROJECTION_CONTRADICTION]: L5FailureFamily.F2_QUARANTINE_SEMANTIC,
  [L5FailureCode.UNRESOLVED_IDENTITY_FOR_RESOLVED_CLASS]: L5FailureFamily.F2_QUARANTINE_SEMANTIC,

  [L5FailureCode.ARCHIVE_WRITE_FAILED]: L5FailureFamily.F3_ARCHIVE_INTEGRITY,
  [L5FailureCode.CHECKSUM_MISMATCH]: L5FailureFamily.F3_ARCHIVE_INTEGRITY,
  [L5FailureCode.ARCHIVE_POINTER_MISSING]: L5FailureFamily.F3_ARCHIVE_INTEGRITY,
  [L5FailureCode.ARCHIVE_TAG_POLICY_VIOLATION]: L5FailureFamily.F3_ARCHIVE_INTEGRITY,
  [L5FailureCode.REPLAY_BUNDLE_CORRUPTED]: L5FailureFamily.F3_ARCHIVE_INTEGRITY,

  [L5FailureCode.POSTGRES_TX_FAILED]: L5FailureFamily.F4_TRANSACTION_COORDINATION,
  [L5FailureCode.MANIFEST_TRANSITION_ILLEGAL]: L5FailureFamily.F4_TRANSACTION_COORDINATION,
  [L5FailureCode.OUTBOX_EMIT_FAILED]: L5FailureFamily.F4_TRANSACTION_COORDINATION,
  [L5FailureCode.FINALIZATION_BLOCKED]: L5FailureFamily.F4_TRANSACTION_COORDINATION,
  [L5FailureCode.REQUIRED_PROJECTION_MISSING]: L5FailureFamily.F4_TRANSACTION_COORDINATION,

  [L5FailureCode.CLICKHOUSE_PROJECTION_FAILED]: L5FailureFamily.F5_PROJECTION_MATERIALIZATION,
  [L5FailureCode.REDIS_PROJECTION_FAILED]: L5FailureFamily.F5_PROJECTION_MATERIALIZATION,
  [L5FailureCode.MATERIALIZATION_FAILED]: L5FailureFamily.F5_PROJECTION_MATERIALIZATION,
  [L5FailureCode.PROJECTION_IDEMPOTENCY_VIOLATION]: L5FailureFamily.F5_PROJECTION_MATERIALIZATION,
  [L5FailureCode.STALE_PROJECTION_RESURRECTION_ATTEMPT]: L5FailureFamily.F5_PROJECTION_MATERIALIZATION,

  [L5FailureCode.UNAUTHORIZED_WRITE_ATTEMPT]: L5FailureFamily.F6_SECURITY_ACCESS,
  [L5FailureCode.UNAUTHORIZED_REPLAY_ATTEMPT]: L5FailureFamily.F6_SECURITY_ACCESS,
  [L5FailureCode.UNAUTHORIZED_ARTIFACT_ACCESS]: L5FailureFamily.F6_SECURITY_ACCESS,
  [L5FailureCode.PUBLIC_BUCKET_EXPOSURE]: L5FailureFamily.F6_SECURITY_ACCESS,
  [L5FailureCode.PII_POLICY_VIOLATION]: L5FailureFamily.F6_SECURITY_ACCESS,

  [L5FailureCode.REPLAY_LINEAGE_GAP]: L5FailureFamily.F7_REPLAY_REPAIR,
  [L5FailureCode.REPAIR_EXHAUSTED]: L5FailureFamily.F7_REPLAY_REPAIR,
  [L5FailureCode.REPAIR_ILLEGAL_MUTATION_ATTEMPT]: L5FailureFamily.F7_REPLAY_REPAIR,
  [L5FailureCode.REMATERIALIZATION_POLICY_MISSING]: L5FailureFamily.F7_REPLAY_REPAIR,
};

export function getFailureFamily(code: L5FailureCode): L5FailureFamily {
  return FAILURE_FAMILY_MAP[code];
}

export const ALL_FAILURE_CODES: readonly L5FailureCode[] = Object.values(L5FailureCode);
export const ALL_FAILURE_FAMILIES: readonly L5FailureFamily[] = Object.values(L5FailureFamily);
