/**
 * L11.8 — Persistence Violation Codes (§11.8.17)
 *
 * Disjoint `L11P_` namespace so persistence / read-surface / replay /
 * repair / downstream-consumption violations never collide with the
 * earlier L11 sublayers (L11_, L11D_, L11F_, L11A_, L11M_, L11C_, L11G_).
 */

export enum L11PersistenceViolationCode {
  // ── L5 routing & direct-store law (§11.8.2) ──
  L11P_L5_ROUTE_MISSING = 'L11P_L5_ROUTE_MISSING',
  L11P_DIRECT_STORE_WRITE_ATTEMPT = 'L11P_DIRECT_STORE_WRITE_ATTEMPT',
  L11P_REDIS_USED_AS_AUTHORITY = 'L11P_REDIS_USED_AS_AUTHORITY',

  // ── Surface registry & class matching (§11.8.3 / §11.8.6) ──
  L11P_SURFACE_UNREGISTERED = 'L11P_SURFACE_UNREGISTERED',
  L11P_SURFACE_ID_MISSING = 'L11P_SURFACE_ID_MISSING',
  L11P_PERSISTENCE_CLASS_MISSING = 'L11P_PERSISTENCE_CLASS_MISSING',
  L11P_PERSISTENCE_CLASS_SURFACE_MISMATCH = 'L11P_PERSISTENCE_CLASS_SURFACE_MISMATCH',
  L11P_MATERIALIZATION_MODE_MISSING = 'L11P_MATERIALIZATION_MODE_MISSING',
  L11P_MODE_NOT_ALLOWED_FOR_SURFACE = 'L11P_MODE_NOT_ALLOWED_FOR_SURFACE',

  // ── Envelope identity / payload (§11.8.6.3) ──
  L11P_ENVELOPE_ID_MISSING = 'L11P_ENVELOPE_ID_MISSING',
  L11P_ENVELOPE_PAYLOAD_MISSING = 'L11P_ENVELOPE_PAYLOAD_MISSING',
  L11P_ENVELOPE_AS_OF_MISSING = 'L11P_ENVELOPE_AS_OF_MISSING',
  L11P_REPLAY_HASH_MISSING = 'L11P_REPLAY_HASH_MISSING',
  L11P_LINEAGE_REFS_MISSING = 'L11P_LINEAGE_REFS_MISSING',
  L11P_POLICY_VERSION_MISSING = 'L11P_POLICY_VERSION_MISSING',
  L11P_EVIDENCE_REF_MISSING = 'L11P_EVIDENCE_REF_MISSING',

  // ── Current authority law (§11.8.7) ──
  L11P_CURRENT_AUTHORITY_NOT_POSTGRES = 'L11P_CURRENT_AUTHORITY_NOT_POSTGRES',
  L11P_CURRENT_RECORD_INCOMPLETE = 'L11P_CURRENT_RECORD_INCOMPLETE',
  L11P_CURRENT_FORMULA_VERSION_MISSING = 'L11P_CURRENT_FORMULA_VERSION_MISSING',
  L11P_CURRENT_ATTRIBUTION_REF_MISSING = 'L11P_CURRENT_ATTRIBUTION_REF_MISSING',
  L11P_CURRENT_COMPONENT_REF_MISSING = 'L11P_CURRENT_COMPONENT_REF_MISSING',
  L11P_CURRENT_MISSING_DATA_REF_MISSING = 'L11P_CURRENT_MISSING_DATA_REF_MISSING',
  L11P_SUPERSESSION_PRIOR_REF_MISSING = 'L11P_SUPERSESSION_PRIOR_REF_MISSING',
  L11P_SUPERSESSION_REASON_MISSING = 'L11P_SUPERSESSION_REASON_MISSING',
  L11P_CURRENT_WRITTEN_UNDER_REPLAY = 'L11P_CURRENT_WRITTEN_UNDER_REPLAY',
  L11P_CURRENT_INVALID_MATERIALIZATION_MODE = 'L11P_CURRENT_INVALID_MATERIALIZATION_MODE',

  // ── Historical fact law (§11.8.8) ──
  L11P_HISTORICAL_FACT_INCOMPLETE = 'L11P_HISTORICAL_FACT_INCOMPLETE',
  L11P_HISTORICAL_FACT_MUTATION = 'L11P_HISTORICAL_FACT_MUTATION',
  L11P_HISTORICAL_REPLAY_HASH_MISSING = 'L11P_HISTORICAL_REPLAY_HASH_MISSING',
  L11P_HISTORICAL_FORMULA_VERSION_MISSING = 'L11P_HISTORICAL_FORMULA_VERSION_MISSING',
  L11P_HISTORICAL_CORRECTION_LINK_MISSING = 'L11P_HISTORICAL_CORRECTION_LINK_MISSING',
  L11P_HISTORICAL_PRETENDS_CURRENT_AUTHORITY = 'L11P_HISTORICAL_PRETENDS_CURRENT_AUTHORITY',
  L11P_HISTORICAL_ATTRIBUTION_REF_MISSING = 'L11P_HISTORICAL_ATTRIBUTION_REF_MISSING',
  L11P_HISTORICAL_COMPONENT_REFS_MISSING = 'L11P_HISTORICAL_COMPONENT_REFS_MISSING',

  // ── Evidence storage law (§11.8.9) ──
  L11P_EVIDENCE_POINTER_INCOMPLETE = 'L11P_EVIDENCE_POINTER_INCOMPLETE',
  L11P_EVIDENCE_ARCHIVE_URI_MISSING = 'L11P_EVIDENCE_ARCHIVE_URI_MISSING',
  L11P_EVIDENCE_MANIFEST_MISSING = 'L11P_EVIDENCE_MANIFEST_MISSING',
  L11P_EVIDENCE_CHECKSUM_MISSING = 'L11P_EVIDENCE_CHECKSUM_MISSING',
  L11P_EVIDENCE_REPLAY_REF_MISSING = 'L11P_EVIDENCE_REPLAY_REF_MISSING',
  L11P_EVIDENCE_PATH_INVALID = 'L11P_EVIDENCE_PATH_INVALID',
  L11P_EVIDENCE_PATH_TRAVERSAL = 'L11P_EVIDENCE_PATH_TRAVERSAL',
  L11P_EVIDENCE_SUBJECT_KIND_MISMATCH = 'L11P_EVIDENCE_SUBJECT_KIND_MISMATCH',
  L11P_EVIDENCE_CLASS_MISMATCH = 'L11P_EVIDENCE_CLASS_MISMATCH',
  L11P_EVIDENCE_POINTER_ORPHANED = 'L11P_EVIDENCE_POINTER_ORPHANED',

  // ── Read surface law (§11.8.11 / §11.8.12) ──
  L11P_READ_SURFACE_UNREGISTERED = 'L11P_READ_SURFACE_UNREGISTERED',
  L11P_READ_REQUEST_INCOMPLETE = 'L11P_READ_REQUEST_INCOMPLETE',
  L11P_READ_MODE_NOT_ALLOWED = 'L11P_READ_MODE_NOT_ALLOWED',
  L11P_CONSUMER_NOT_ALLOWED = 'L11P_CONSUMER_NOT_ALLOWED',
  L11P_CURRENT_READ_BYPASSES_CURRENT_REGISTRY = 'L11P_CURRENT_READ_BYPASSES_CURRENT_REGISTRY',
  L11P_RAW_STORAGE_READ_FOR_OFFICIAL_STATE = 'L11P_RAW_STORAGE_READ_FOR_OFFICIAL_STATE',
  L11P_REDIS_AS_AUTHORITY_READ = 'L11P_REDIS_AS_AUTHORITY_READ',
  L11P_LINEAGE_REQUIRED_BUT_ABSENT = 'L11P_LINEAGE_REQUIRED_BUT_ABSENT',
  L11P_EVIDENCE_REQUIRED_BUT_ABSENT = 'L11P_EVIDENCE_REQUIRED_BUT_ABSENT',
  L11P_REPLAY_HASH_REQUIRED_BUT_ABSENT = 'L11P_REPLAY_HASH_REQUIRED_BUT_ABSENT',

  // ── Downstream consumption (§11.8.13 / §11.8.14) ──
  L11P_DOWNSTREAM_REQUEST_INCOMPLETE = 'L11P_DOWNSTREAM_REQUEST_INCOMPLETE',
  L11P_DOWNSTREAM_RECOMPUTE_ATTEMPT = 'L11P_DOWNSTREAM_RECOMPUTE_ATTEMPT',
  L11P_DOWNSTREAM_RECOMPUTE_NOT_REPLAY_OR_REPAIR = 'L11P_DOWNSTREAM_RECOMPUTE_NOT_REPLAY_OR_REPAIR',
  L11P_DOWNSTREAM_RECOMPUTE_REASON_MISSING = 'L11P_DOWNSTREAM_RECOMPUTE_REASON_MISSING',
  L11P_DOWNSTREAM_USES_SCORE_WITHOUT_ATTRIBUTION = 'L11P_DOWNSTREAM_USES_SCORE_WITHOUT_ATTRIBUTION',
  L11P_DOWNSTREAM_USES_SCORE_WITHOUT_MISSING_DATA = 'L11P_DOWNSTREAM_USES_SCORE_WITHOUT_MISSING_DATA',
  L11P_DOWNSTREAM_SCORING_USE_WITHOUT_DRIFT = 'L11P_DOWNSTREAM_SCORING_USE_WITHOUT_DRIFT',
  L11P_DOWNSTREAM_CONSUMER_NOT_ALLOWED = 'L11P_DOWNSTREAM_CONSUMER_NOT_ALLOWED',
  L11P_DOWNSTREAM_READ_MODE_NOT_ALLOWED = 'L11P_DOWNSTREAM_READ_MODE_NOT_ALLOWED',

  // ── Replay (§11.8.15) ──
  L11P_REPLAY_HASH_MISMATCH = 'L11P_REPLAY_HASH_MISMATCH',
  L11P_REPLAY_ATTRIBUTION_MISMATCH = 'L11P_REPLAY_ATTRIBUTION_MISMATCH',
  L11P_REPLAY_MISSING_DATA_MISMATCH = 'L11P_REPLAY_MISSING_DATA_MISMATCH',
  L11P_REPLAY_MODIFIER_MISMATCH = 'L11P_REPLAY_MODIFIER_MISMATCH',
  L11P_REPLAY_CALIBRATION_MISMATCH = 'L11P_REPLAY_CALIBRATION_MISMATCH',
  L11P_REPLAY_FORMULA_VERSION_MISMATCH = 'L11P_REPLAY_FORMULA_VERSION_MISMATCH',
  L11P_REPLAY_THRESHOLD_POLICY_MISMATCH = 'L11P_REPLAY_THRESHOLD_POLICY_MISMATCH',
  L11P_REPLAY_INVENTED_EVIDENCE = 'L11P_REPLAY_INVENTED_EVIDENCE',
  L11P_REPLAY_UPDATES_CURRENT = 'L11P_REPLAY_UPDATES_CURRENT',
  L11P_REPLAY_OVERWRITES_HISTORICAL = 'L11P_REPLAY_OVERWRITES_HISTORICAL',
  L11P_REPLAY_RESULT_INCOMPLETE = 'L11P_REPLAY_RESULT_INCOMPLETE',
  L11P_REPLAY_SOURCE_RUN_MISSING = 'L11P_REPLAY_SOURCE_RUN_MISSING',

  // ── Repair (§11.8.16) ──
  L11P_REPAIR_PARENT_RUN_MISSING = 'L11P_REPAIR_PARENT_RUN_MISSING',
  L11P_REPAIR_REASON_MISSING = 'L11P_REPAIR_REASON_MISSING',
  L11P_REPAIR_REUSES_RUN_ID = 'L11P_REPAIR_REUSES_RUN_ID',
  L11P_REPAIR_NO_CORRECTION_REFS = 'L11P_REPAIR_NO_CORRECTION_REFS',
  L11P_REPAIR_INVENTS_EVIDENCE = 'L11P_REPAIR_INVENTS_EVIDENCE',
  L11P_REPAIR_MASQUERADES_AS_LIVE = 'L11P_REPAIR_MASQUERADES_AS_LIVE',
  L11P_REPAIR_DESTRUCTIVE_HISTORICAL_MUTATION = 'L11P_REPAIR_DESTRUCTIVE_HISTORICAL_MUTATION',
  L11P_REPAIR_REQUEST_INCOMPLETE = 'L11P_REPAIR_REQUEST_INCOMPLETE',

  // ── Run / failure record law (§11.8.10) ──
  L11P_RUN_RECORD_INCOMPLETE = 'L11P_RUN_RECORD_INCOMPLETE',
  L11P_FAILURE_RECORD_INCOMPLETE = 'L11P_FAILURE_RECORD_INCOMPLETE',
  L11P_CRITICAL_FAILURE_DID_NOT_BLOCK_CURRENT = 'L11P_CRITICAL_FAILURE_DID_NOT_BLOCK_CURRENT',

  // ── Catch-all envelope guard ──
  L11P_ENVELOPE_INCOMPLETE = 'L11P_ENVELOPE_INCOMPLETE',
}

export interface L11PersistenceIssueContext {
  readonly envelope_id?: string;
  readonly surface_id?: string;
  readonly score_id?: string;
  readonly run_id?: string;
  readonly current_record_id?: string;
  readonly historical_fact_id?: string;
  readonly evidence_pointer_id?: string;
  readonly read_request_id?: string;
  readonly downstream_request_id?: string;
  readonly replay_id?: string;
  readonly repair_request_id?: string;
  readonly path?: string;
  readonly extra?: Readonly<Record<string, string>>;
}

export interface L11PersistenceIssue {
  readonly code: L11PersistenceViolationCode;
  readonly message: string;
  readonly context?: L11PersistenceIssueContext;
}

export function makeL11PersistenceIssue(
  code: L11PersistenceViolationCode,
  message: string,
  context?: L11PersistenceIssueContext,
): L11PersistenceIssue {
  return context === undefined
    ? { code, message }
    : { code, message, context };
}

export const ALL_L11_PERSISTENCE_VIOLATION_CODES:
  readonly L11PersistenceViolationCode[] =
  Object.values(L11PersistenceViolationCode);
