/**
 * L12.5 — Template / trigger / confidence violation codes (§12.5.20).
 *
 * Disjoint namespace `L12T_`.
 */

export enum L12TemplateViolationCode {
  // Template structural
  L12T_TEMPLATE_ID_MISSING = 'L12T_TEMPLATE_ID_MISSING',
  L12T_TEMPLATE_FAMILY_MISSING = 'L12T_TEMPLATE_FAMILY_MISSING',
  L12T_TEMPLATE_TYPE_ILLEGAL = 'L12T_TEMPLATE_TYPE_ILLEGAL',
  L12T_TEMPLATE_TRIGGER_PATTERN_MISSING = 'L12T_TEMPLATE_TRIGGER_PATTERN_MISSING',
  L12T_TEMPLATE_INVALIDATION_PATTERN_MISSING = 'L12T_TEMPLATE_INVALIDATION_PATTERN_MISSING',
  L12T_TEMPLATE_SCORE_CONTEXT_REQUIREMENT_MISSING = 'L12T_TEMPLATE_SCORE_CONTEXT_REQUIREMENT_MISSING',
  L12T_PRODUCTION_TEMPLATE_WITHOUT_EVIDENCE_CLASSES = 'L12T_PRODUCTION_TEMPLATE_WITHOUT_EVIDENCE_CLASSES',
  L12T_TEMPLATE_DUPLICATE_ID = 'L12T_TEMPLATE_DUPLICATE_ID',
  L12T_TEMPLATE_RESERVED_EMITS_PRODUCTION = 'L12T_TEMPLATE_RESERVED_EMITS_PRODUCTION',
  L12T_TEMPLATE_POLICY_REF_MISSING = 'L12T_TEMPLATE_POLICY_REF_MISSING',

  // Trigger strength
  L12T_TRIGGER_STRENGTH_OUT_OF_RANGE = 'L12T_TRIGGER_STRENGTH_OUT_OF_RANGE',
  L12T_TRIGGER_DECISIVE_WITH_WEAK_EVIDENCE = 'L12T_TRIGGER_DECISIVE_WITH_WEAK_EVIDENCE',
  L12T_TRIGGER_STRONG_WHILE_UNMONITORABLE = 'L12T_TRIGGER_STRONG_WHILE_UNMONITORABLE',
  L12T_TRIGGER_GUARANTEED_OUTCOME = 'L12T_TRIGGER_GUARANTEED_OUTCOME',
  L12T_TRIGGER_AS_TRADE_INSTRUCTION = 'L12T_TRIGGER_AS_TRADE_INSTRUCTION',
  L12T_TRIGGER_CONFIDENCE_EFFECT_INCONSISTENT = 'L12T_TRIGGER_CONFIDENCE_EFFECT_INCONSISTENT',

  // Invalidation strength
  L12T_INVALIDATION_STRENGTH_OUT_OF_RANGE = 'L12T_INVALIDATION_STRENGTH_OUT_OF_RANGE',
  L12T_ACTIVE_INVALIDATION_WITHOUT_CONFIDENCE_CAP = 'L12T_ACTIVE_INVALIDATION_WITHOUT_CONFIDENCE_CAP',
  L12T_BLOCKING_INVALIDATION_WITH_CLEAN_READINESS = 'L12T_BLOCKING_INVALIDATION_WITH_CLEAN_READINESS',
  L12T_INVALIDATION_GUARANTEED_FAILURE = 'L12T_INVALIDATION_GUARANTEED_FAILURE',
  L12T_INVALIDATION_UNMONITORABLE_USED_AS_PROTECTION = 'L12T_INVALIDATION_UNMONITORABLE_USED_AS_PROTECTION',

  // Confidence policy / cap chain
  L12T_CONFIDENCE_FACTOR_MISSING = 'L12T_CONFIDENCE_FACTOR_MISSING',
  L12T_CONFIDENCE_WEIGHT_SUM_ILLEGAL = 'L12T_CONFIDENCE_WEIGHT_SUM_ILLEGAL',
  L12T_CONFIDENCE_DIRECTION_MISSING = 'L12T_CONFIDENCE_DIRECTION_MISSING',
  L12T_CONFIDENCE_CAP_REQUIRED_BUT_ABSENT = 'L12T_CONFIDENCE_CAP_REQUIRED_BUT_ABSENT',
  L12T_CAPPED_SCORE_EXCEEDS_PRE_CAP = 'L12T_CAPPED_SCORE_EXCEEDS_PRE_CAP',
  L12T_DOMINANT_CAP_REASON_MISSING = 'L12T_DOMINANT_CAP_REASON_MISSING',
  L12T_INCOMPLETE_SCORE_CONTEXT_NOT_BLOCKED = 'L12T_INCOMPLETE_SCORE_CONTEXT_NOT_BLOCKED',
  L12T_BLOCKING_INVALIDATION_NOT_BLOCKED = 'L12T_BLOCKING_INVALIDATION_NOT_BLOCKED',

  // Spread
  L12T_SPREAD_MISSING_SECONDARY = 'L12T_SPREAD_MISSING_SECONDARY',
  L12T_NARROW_SPREAD_WITHOUT_SHIFT_CONDITIONS = 'L12T_NARROW_SPREAD_WITHOUT_SHIFT_CONDITIONS',
  L12T_CLEAR_PRIMARY_UNDER_INVALIDATION = 'L12T_CLEAR_PRIMARY_UNDER_INVALIDATION',
  L12T_CLEAR_PRIMARY_UNDER_UNRESOLVED_CONTRADICTION = 'L12T_CLEAR_PRIMARY_UNDER_UNRESOLVED_CONTRADICTION',
  L12T_PRIMARY_CALLED_WINNER = 'L12T_PRIMARY_CALLED_WINNER',
  L12T_SPREAD_HIDDEN_FROM_SET = 'L12T_SPREAD_HIDDEN_FROM_SET',

  // Readiness
  L12T_CLEAN_READINESS_UNDER_ACTIVE_INVALIDATION = 'L12T_CLEAN_READINESS_UNDER_ACTIVE_INVALIDATION',
  L12T_CLEAN_READINESS_WITH_MISSING_TRIGGER = 'L12T_CLEAN_READINESS_WITH_MISSING_TRIGGER',
  L12T_CLEAN_READINESS_WITH_MISSING_INVALIDATION = 'L12T_CLEAN_READINESS_WITH_MISSING_INVALIDATION',
  L12T_CLEAN_READINESS_UNDER_MATERIAL_DRIFT = 'L12T_CLEAN_READINESS_UNDER_MATERIAL_DRIFT',
  L12T_CLEAN_READINESS_UNDER_INCOMPLETE_SCORE_CONTEXT = 'L12T_CLEAN_READINESS_UNDER_INCOMPLETE_SCORE_CONTEXT',
  L12T_CLEAN_READINESS_UNDER_UNRESOLVED_MULTI_PATH = 'L12T_CLEAN_READINESS_UNDER_UNRESOLVED_MULTI_PATH',

  // Interaction
  L12T_TRIGGER_OVERRIDES_BLOCKING_INVALIDATION = 'L12T_TRIGGER_OVERRIDES_BLOCKING_INVALIDATION',
  L12T_INTERACTION_TRIGGER_DOMINANT_UNDER_BLOCKING = 'L12T_INTERACTION_TRIGGER_DOMINANT_UNDER_BLOCKING',
  L12T_INTERACTION_BALANCED_AS_CLEAN = 'L12T_INTERACTION_BALANCED_AS_CLEAN',

  // Non-prediction template law
  L12T_PREDICTION_THEATER = 'L12T_PREDICTION_THEATER',
  L12T_RECOMMENDATION_LEAK = 'L12T_RECOMMENDATION_LEAK',
  L12T_JUDGMENT_LEAK = 'L12T_JUDGMENT_LEAK',
  L12T_TRADE_LEAK = 'L12T_TRADE_LEAK',
  L12T_CERTAINTY_LANGUAGE = 'L12T_CERTAINTY_LANGUAGE',

  // Match-result
  L12T_MATCH_BAND_INCONSISTENT_WITH_PATTERNS = 'L12T_MATCH_BAND_INCONSISTENT_WITH_PATTERNS',
  L12T_BASE_CASE_WITHOUT_ALTERNATIVE_PATH = 'L12T_BASE_CASE_WITHOUT_ALTERNATIVE_PATH',
}

export const ALL_L12_TEMPLATE_VIOLATION_CODES: readonly L12TemplateViolationCode[] =
  Object.values(L12TemplateViolationCode);

export interface L12TemplateViolationIssue {
  readonly code: L12TemplateViolationCode;
  readonly message: string;
  readonly subject_ref?: string;
}

export function l12TemplateIssueOf(
  code: L12TemplateViolationCode,
  message: string,
  subject_ref?: string,
): L12TemplateViolationIssue {
  return { code, message, subject_ref };
}

export interface L12TemplateValidationResult {
  readonly ok: boolean;
  readonly issues: readonly L12TemplateViolationIssue[];
}
