/**
 * L12.7 — Final / Finalization Violation Codes (§12.7.14)
 *
 * Disjoint `L12F_` namespace covering ratification, freeze,
 * certification report, ratification artifact, extension policy,
 * rollout gate, and L13 handoff violations.
 *
 * Disjointness law: this namespace MUST NOT collide with the
 * existing L12 namespaces (`L12_`, `L12T_`, `L12P_`, `L12R_`, etc.).
 */

export const L12_FINAL_VIOLATION_POLICY_VERSION = 'l12.7.violations.v1';

export enum L12FinalViolationCode {
  // Sublayer / band / invariant gaps
  L12F_SUBLAYER_CERTIFICATION_MISSING = 'L12F_SUBLAYER_CERTIFICATION_MISSING',
  L12F_CERTIFICATION_BAND_MISSING = 'L12F_CERTIFICATION_BAND_MISSING',
  L12F_CERTIFICATION_BAND_FAILED = 'L12F_CERTIFICATION_BAND_FAILED',
  L12F_INVARIANT_MISSING = 'L12F_INVARIANT_MISSING',
  L12F_INVARIANT_FAILED = 'L12F_INVARIANT_FAILED',
  L12F_CRITICAL_BREACH_PRESENT = 'L12F_CRITICAL_BREACH_PRESENT',

  // Semantic breach categories
  L12F_PREDICTION_THEATER_BREACH = 'L12F_PREDICTION_THEATER_BREACH',
  L12F_RECOMMENDATION_LEAK = 'L12F_RECOMMENDATION_LEAK',
  L12F_FINAL_JUDGMENT_LEAK = 'L12F_FINAL_JUDGMENT_LEAK',
  L12F_LOWER_LAYER_REBUILD_ALLOWED = 'L12F_LOWER_LAYER_REBUILD_ALLOWED',

  // Sub-law not certified
  L12F_TRIGGER_LAW_NOT_CERTIFIED = 'L12F_TRIGGER_LAW_NOT_CERTIFIED',
  L12F_INVALIDATION_LAW_NOT_CERTIFIED =
    'L12F_INVALIDATION_LAW_NOT_CERTIFIED',
  L12F_CONFIDENCE_CAP_LAW_NOT_CERTIFIED =
    'L12F_CONFIDENCE_CAP_LAW_NOT_CERTIFIED',
  L12F_L11_SCORE_CONTEXT_LAW_NOT_CERTIFIED =
    'L12F_L11_SCORE_CONTEXT_LAW_NOT_CERTIFIED',
  L12F_L5_PERSISTENCE_LAW_NOT_CERTIFIED =
    'L12F_L5_PERSISTENCE_LAW_NOT_CERTIFIED',
  L12F_REPLAY_LAW_NOT_CERTIFIED = 'L12F_REPLAY_LAW_NOT_CERTIFIED',
  L12F_REPAIR_LAW_NOT_CERTIFIED = 'L12F_REPAIR_LAW_NOT_CERTIFIED',

  // Ratification artifact / fingerprint
  L12F_RATIFICATION_ARTIFACT_INCOMPLETE =
    'L12F_RATIFICATION_ARTIFACT_INCOMPLETE',
  L12F_FINGERPRINT_MISSING = 'L12F_FINGERPRINT_MISSING',
  L12F_FINGERPRINT_NON_DETERMINISTIC = 'L12F_FINGERPRINT_NON_DETERMINISTIC',
  L12F_REPLAY_HASH_MISSING = 'L12F_REPLAY_HASH_MISSING',
  L12F_FROZEN_SURFACES_MISSING = 'L12F_FROZEN_SURFACES_MISSING',

  // Freeze
  L12F_FREEZE_ACTIVATION_ILLEGAL = 'L12F_FREEZE_ACTIVATION_ILLEGAL',
  L12F_FREEZE_POLICY_INACTIVE = 'L12F_FREEZE_POLICY_INACTIVE',

  // Extension policy
  L12F_EXTENSION_UNCLASSIFIED = 'L12F_EXTENSION_UNCLASSIFIED',
  L12F_PROHIBITED_EXTENSION = 'L12F_PROHIBITED_EXTENSION',
  L12F_WEAKENS_TRIGGER_REQUIREMENT = 'L12F_WEAKENS_TRIGGER_REQUIREMENT',
  L12F_WEAKENS_INVALIDATION_REQUIREMENT =
    'L12F_WEAKENS_INVALIDATION_REQUIREMENT',
  L12F_WEAKENS_NO_REBUILD_LAW = 'L12F_WEAKENS_NO_REBUILD_LAW',
  L12F_EXTENSION_REQUIRES_RECERT = 'L12F_EXTENSION_REQUIRES_RECERT',

  // Rollout gate
  L12F_ROLLOUT_GATE_ILLEGAL = 'L12F_ROLLOUT_GATE_ILLEGAL',
  L12F_ROLLOUT_FLAG_MISSING = 'L12F_ROLLOUT_FLAG_MISSING',
  L12F_ROLLOUT_LEVEL_TOO_LOW = 'L12F_ROLLOUT_LEVEL_TOO_LOW',

  // Downstream / L13 handoff
  L12F_L13_HANDOFF_NOT_APPROVED = 'L12F_L13_HANDOFF_NOT_APPROVED',
  L12F_DOWNSTREAM_DEPENDENCY_INVALID =
    'L12F_DOWNSTREAM_DEPENDENCY_INVALID',

  // Completion standard
  L12F_COMPLETION_CLAUSE_UNSATISFIED =
    'L12F_COMPLETION_CLAUSE_UNSATISFIED',

  // Done definition (§12.7.18.J)
  L12F_DONE_DEFINITION_UNSATISFIED = 'L12F_DONE_DEFINITION_UNSATISFIED',
}

export const ALL_L12_FINAL_VIOLATION_CODES:
  readonly L12FinalViolationCode[] = Object.values(L12FinalViolationCode);

export interface L12FinalViolationIssue {
  readonly code: L12FinalViolationCode;
  readonly message: string;
  readonly subject_ref?: string;
}

/** Convenience helper: build a final-namespace issue object. */
export function makeL12FinalIssue(
  code: L12FinalViolationCode,
  message: string,
  subject_ref?: string,
): L12FinalViolationIssue {
  return { code, message, subject_ref };
}
