/**
 * L12.2 — Object violation codes (§12.2.19).
 *
 * Disjoint namespace `L12O_*` for object-level violations. Constitutional
 * violations remain in `L12C_*` (L12.1).
 */

export enum L12ObjectViolationCode {
  // Subject
  L12O_SUBJECT_ID_MISSING = 'L12O_SUBJECT_ID_MISSING',
  L12O_SUBJECT_SCOPE_MISSING = 'L12O_SUBJECT_SCOPE_MISSING',
  L12O_SUBJECT_AS_OF_MISSING = 'L12O_SUBJECT_AS_OF_MISSING',
  L12O_SUBJECT_NO_REQUESTED_FAMILY = 'L12O_SUBJECT_NO_REQUESTED_FAMILY',
  L12O_SUBJECT_REQUESTED_BLOCKED_FAMILY = 'L12O_SUBJECT_REQUESTED_BLOCKED_FAMILY',
  L12O_SUBJECT_SCORE_CONTEXT_REFS_ABSENT = 'L12O_SUBJECT_SCORE_CONTEXT_REFS_ABSENT',
  L12O_SUBJECT_LINEAGE_ABSENT = 'L12O_SUBJECT_LINEAGE_ABSENT',
  L12O_SUBJECT_INPUT_SNAPSHOT_ABSENT = 'L12O_SUBJECT_INPUT_SNAPSHOT_ABSENT',
  L12O_SUBJECT_REPLAY_HASH_ABSENT = 'L12O_SUBJECT_REPLAY_HASH_ABSENT',
  L12O_SUBJECT_TRADE_INTENT = 'L12O_SUBJECT_TRADE_INTENT',
  L12O_SUBJECT_REFERENCES_L13_PLUS = 'L12O_SUBJECT_REFERENCES_L13_PLUS',

  // Family
  L12O_FAMILY_UNREGISTERED = 'L12O_FAMILY_UNREGISTERED',
  L12O_FAMILY_BLOCKED = 'L12O_FAMILY_BLOCKED',
  L12O_FAMILY_DUPLICATE = 'L12O_FAMILY_DUPLICATE',
  L12O_FAMILY_LEGAL_TYPES_EMPTY = 'L12O_FAMILY_LEGAL_TYPES_EMPTY',
  L12O_FAMILY_REQUIRED_CONTEXTS_EMPTY = 'L12O_FAMILY_REQUIRED_CONTEXTS_EMPTY',
  L12O_FAMILY_NO_INVALIDATION_REQUIREMENT = 'L12O_FAMILY_NO_INVALIDATION_REQUIREMENT',
  L12O_FAMILY_NO_SCORE_CONTEXT_REQUIREMENT = 'L12O_FAMILY_NO_SCORE_CONTEXT_REQUIREMENT',

  // Set
  L12O_SCENARIO_SET_ID_MISSING = 'L12O_SCENARIO_SET_ID_MISSING',
  L12O_SUBJECT_REF_MISSING = 'L12O_SUBJECT_REF_MISSING',
  L12O_BASE_CASE_MISSING = 'L12O_BASE_CASE_MISSING',
  L12O_PRIMARY_SCENARIO_MISSING = 'L12O_PRIMARY_SCENARIO_MISSING',
  L12O_SECONDARY_REQUIRED_UNDER_NARROW_SPREAD = 'L12O_SECONDARY_REQUIRED_UNDER_NARROW_SPREAD',
  L12O_SCENARIO_COUNT_ZERO = 'L12O_SCENARIO_COUNT_ZERO',
  L12O_SPREAD_CLASS_MISSING = 'L12O_SPREAD_CLASS_MISSING',
  L12O_PATH_CONFIDENCE_REF_MISSING = 'L12O_PATH_CONFIDENCE_REF_MISSING',
  L12O_TRIGGER_PROFILE_REF_MISSING = 'L12O_TRIGGER_PROFILE_REF_MISSING',
  L12O_INVALIDATION_PROFILE_REF_MISSING = 'L12O_INVALIDATION_PROFILE_REF_MISSING',
  L12O_RESTRICTION_PROFILE_REF_MISSING = 'L12O_RESTRICTION_PROFILE_REF_MISSING',
  L12O_SINGLE_PATH_FAKE_CERTAINTY = 'L12O_SINGLE_PATH_FAKE_CERTAINTY',
  L12O_BASE_CASE_AS_FINAL_JUDGMENT = 'L12O_BASE_CASE_AS_FINAL_JUDGMENT',
  L12O_PRIMARY_AS_GUARANTEED_WINNER = 'L12O_PRIMARY_AS_GUARANTEED_WINNER',

  // Scenario
  L12O_SCENARIO_TYPE_MISSING = 'L12O_SCENARIO_TYPE_MISSING',
  L12O_SCENARIO_FAMILY_MISSING = 'L12O_SCENARIO_FAMILY_MISSING',
  L12O_ILLEGAL_TYPE_FAMILY_PAIR = 'L12O_ILLEGAL_TYPE_FAMILY_PAIR',
  L12O_PATH_CLAIM_MISSING = 'L12O_PATH_CLAIM_MISSING',
  L12O_CONDITION_REFS_MISSING = 'L12O_CONDITION_REFS_MISSING',
  L12O_TRIGGER_REFS_MISSING = 'L12O_TRIGGER_REFS_MISSING',
  L12O_INVALIDATION_REFS_MISSING = 'L12O_INVALIDATION_REFS_MISSING',
  L12O_EVIDENCE_REFS_MISSING = 'L12O_EVIDENCE_REFS_MISSING',
  L12O_LINEAGE_REFS_MISSING = 'L12O_LINEAGE_REFS_MISSING',
  L12O_REPLAY_HASH_MISSING = 'L12O_REPLAY_HASH_MISSING',

  // Confidence
  L12O_CONFIDENCE_SCORE_OUT_OF_RANGE = 'L12O_CONFIDENCE_SCORE_OUT_OF_RANGE',
  L12O_CONFIDENCE_BAND_MISMATCH = 'L12O_CONFIDENCE_BAND_MISMATCH',
  L12O_HIGH_CONFIDENCE_WITH_ACTIVE_INVALIDATION = 'L12O_HIGH_CONFIDENCE_WITH_ACTIVE_INVALIDATION',
  L12O_HIGH_CONFIDENCE_WITH_UNRESOLVED_CONTRADICTION = 'L12O_HIGH_CONFIDENCE_WITH_UNRESOLVED_CONTRADICTION',
  L12O_HIGH_CONFIDENCE_WITH_MISSING_VISIBILITY = 'L12O_HIGH_CONFIDENCE_WITH_MISSING_VISIBILITY',
  L12O_HIGH_CONFIDENCE_WITH_CRITICAL_DRIFT = 'L12O_HIGH_CONFIDENCE_WITH_CRITICAL_DRIFT',
  L12O_CONFIDENCE_SPREAD_MISSING = 'L12O_CONFIDENCE_SPREAD_MISSING',
  L12O_READINESS_MISSING = 'L12O_READINESS_MISSING',
  L12O_READINESS_MISMATCH = 'L12O_READINESS_MISMATCH',

  // Condition
  L12O_CONDITION_ID_MISSING = 'L12O_CONDITION_ID_MISSING',
  L12O_CONDITION_SCENARIO_REF_MISSING = 'L12O_CONDITION_SCENARIO_REF_MISSING',
  L12O_CONDITION_SOURCE_LAYER_MISSING = 'L12O_CONDITION_SOURCE_LAYER_MISSING',
  L12O_CONDITION_REQUIRED_SURFACE_REF_MISSING = 'L12O_CONDITION_REQUIRED_SURFACE_REF_MISSING',
  L12O_CONDITION_ROLE_MISSING = 'L12O_CONDITION_ROLE_MISSING',
  L12O_CONDITION_STATUS_MISSING = 'L12O_CONDITION_STATUS_MISSING',
  L12O_CONDITION_TYPE_LAYER_MISMATCH = 'L12O_CONDITION_TYPE_LAYER_MISMATCH',
  L12O_CONDITION_USES_RAW_DATA = 'L12O_CONDITION_USES_RAW_DATA',
  L12O_CONDITION_RECOMMENDATION_LANGUAGE = 'L12O_CONDITION_RECOMMENDATION_LANGUAGE',
  L12O_CONDITION_CERTAINTY_LANGUAGE = 'L12O_CONDITION_CERTAINTY_LANGUAGE',

  // Trigger
  L12O_TRIGGER_ID_MISSING = 'L12O_TRIGGER_ID_MISSING',
  L12O_TRIGGER_SCENARIO_REF_MISSING = 'L12O_TRIGGER_SCENARIO_REF_MISSING',
  L12O_TRIGGER_CONDITION_REFS_MISSING = 'L12O_TRIGGER_CONDITION_REFS_MISSING',
  L12O_TRIGGER_STATUS_MISSING = 'L12O_TRIGGER_STATUS_MISSING',
  L12O_TRIGGER_EFFECT_MISSING = 'L12O_TRIGGER_EFFECT_MISSING',
  L12O_TRIGGER_STRENGTH_OUT_OF_RANGE = 'L12O_TRIGGER_STRENGTH_OUT_OF_RANGE',
  L12O_TRIGGER_GUARANTEED_OUTCOME = 'L12O_TRIGGER_GUARANTEED_OUTCOME',
  L12O_TRIGGER_TRADE_INSTRUCTION = 'L12O_TRIGGER_TRADE_INSTRUCTION',
  L12O_TRIGGER_ILLEGAL_TYPE_EFFECT_PAIR = 'L12O_TRIGGER_ILLEGAL_TYPE_EFFECT_PAIR',
  L12O_TRIGGER_ILLEGAL_TYPE_STATUS_PAIR = 'L12O_TRIGGER_ILLEGAL_TYPE_STATUS_PAIR',

  // Invalidation
  L12O_INVALIDATION_ID_MISSING = 'L12O_INVALIDATION_ID_MISSING',
  L12O_INVALIDATION_SCENARIO_REF_MISSING = 'L12O_INVALIDATION_SCENARIO_REF_MISSING',
  L12O_INVALIDATION_CONDITION_REFS_MISSING = 'L12O_INVALIDATION_CONDITION_REFS_MISSING',
  L12O_INVALIDATION_STRENGTH_OUT_OF_RANGE = 'L12O_INVALIDATION_STRENGTH_OUT_OF_RANGE',
  L12O_INVALIDATION_STATUS_MISSING = 'L12O_INVALIDATION_STATUS_MISSING',
  L12O_INVALIDATION_EFFECT_MISSING = 'L12O_INVALIDATION_EFFECT_MISSING',
  L12O_INVALIDATION_HIDDEN = 'L12O_INVALIDATION_HIDDEN',
  L12O_INVALIDATION_NOT_MONITORABLE = 'L12O_INVALIDATION_NOT_MONITORABLE',
  L12O_INVALIDATION_ILLEGAL_TYPE_EFFECT_PAIR = 'L12O_INVALIDATION_ILLEGAL_TYPE_EFFECT_PAIR',

  // Shift conditions
  L12O_SHIFT_PRIMARY_REF_MISSING = 'L12O_SHIFT_PRIMARY_REF_MISSING',
  L12O_SHIFT_SECONDARY_REF_MISSING = 'L12O_SHIFT_SECONDARY_REF_MISSING',
  L12O_SHIFT_CONDITIONS_MISSING_UNDER_CLOSE_SPREAD = 'L12O_SHIFT_CONDITIONS_MISSING_UNDER_CLOSE_SPREAD',
  L12O_SHIFT_CONDITIONS_TRADE_LANGUAGE = 'L12O_SHIFT_CONDITIONS_TRADE_LANGUAGE',

  // Restriction
  L12O_RESTRICTION_PROFILE_INCOMPLETE = 'L12O_RESTRICTION_PROFILE_INCOMPLETE',
  L12O_RESTRICTION_RECOMMENDATION_NOT_BLOCKED = 'L12O_RESTRICTION_RECOMMENDATION_NOT_BLOCKED',
  L12O_RESTRICTION_PREDICTION_NOT_BLOCKED = 'L12O_RESTRICTION_PREDICTION_NOT_BLOCKED',
  L12O_RESTRICTION_TRADE_NOT_BLOCKED = 'L12O_RESTRICTION_TRADE_NOT_BLOCKED',
  L12O_RESTRICTION_FINAL_JUDGMENT_NOT_BLOCKED = 'L12O_RESTRICTION_FINAL_JUDGMENT_NOT_BLOCKED',
  L12O_RESTRICTION_CERTAINTY_NOT_BLOCKED = 'L12O_RESTRICTION_CERTAINTY_NOT_BLOCKED',
  L12O_RESTRICTION_SCORE_REPLACEMENT_NOT_BLOCKED = 'L12O_RESTRICTION_SCORE_REPLACEMENT_NOT_BLOCKED',
  L12O_RESTRICTION_ALLOWED_USES_EMPTY = 'L12O_RESTRICTION_ALLOWED_USES_EMPTY',

  // Coexistence
  L12O_COEXISTENCE_ILLEGAL_COLLAPSED_SINGLE_PATH = 'L12O_COEXISTENCE_ILLEGAL_COLLAPSED_SINGLE_PATH',
  L12O_COEXISTENCE_BULLISH_WITHOUT_BEARISH = 'L12O_COEXISTENCE_BULLISH_WITHOUT_BEARISH',
  L12O_COEXISTENCE_BEARISH_WITHOUT_RECOVERY_OR_INVALIDATION = 'L12O_COEXISTENCE_BEARISH_WITHOUT_RECOVERY_OR_INVALIDATION',
  L12O_COEXISTENCE_NARROW_WITHOUT_SECONDARY = 'L12O_COEXISTENCE_NARROW_WITHOUT_SECONDARY',
  L12O_COEXISTENCE_HIDDEN_CONTRADICTORY_PATHS = 'L12O_COEXISTENCE_HIDDEN_CONTRADICTORY_PATHS',
  L12O_COEXISTENCE_SINGLE_PATH_WITHOUT_DISCLOSURE = 'L12O_COEXISTENCE_SINGLE_PATH_WITHOUT_DISCLOSURE',
  L12O_COEXISTENCE_CLEAN_BUT_CONTRADICTION_UNRESOLVED = 'L12O_COEXISTENCE_CLEAN_BUT_CONTRADICTION_UNRESOLVED',

  // Semantic / leakage
  L12O_RECOMMENDATION_LEAK = 'L12O_RECOMMENDATION_LEAK',
  L12O_JUDGMENT_LEAK = 'L12O_JUDGMENT_LEAK',
  L12O_PREDICTION_THEATER = 'L12O_PREDICTION_THEATER',
  L12O_TRADE_ACTION_LEAK = 'L12O_TRADE_ACTION_LEAK',
  L12O_CERTAINTY_LANGUAGE = 'L12O_CERTAINTY_LANGUAGE',
}

export const ALL_L12_OBJECT_VIOLATION_CODES: readonly L12ObjectViolationCode[] =
  Object.values(L12ObjectViolationCode);

export interface L12ObjectViolation {
  readonly code: L12ObjectViolationCode;
  readonly subject_id: string;
  readonly detail: string;
}

export class L12ObjectError extends Error {
  public readonly code: L12ObjectViolationCode;
  constructor(code: L12ObjectViolationCode, message: string) {
    super(`[${code}] ${message}`);
    this.code = code;
    this.name = 'L12ObjectError';
  }
}
