/**
 * L12.3 — Contract violation codes (§12.3.18).
 *
 * Disjoint namespace `L12K_*` for contract-level violations.
 * (L12.1 = `L12C_*` constitutional, L12.2 = `L12O_*` object-level.)
 */

export enum L12ContractViolationCode {
  // Subject contract
  L12K_SUBJECT_CONTRACT_ID_MISSING = 'L12K_SUBJECT_CONTRACT_ID_MISSING',
  L12K_SUBJECT_REF_MISSING = 'L12K_SUBJECT_REF_MISSING',
  L12K_SCOPE_MISSING = 'L12K_SCOPE_MISSING',
  L12K_AS_OF_MISSING = 'L12K_AS_OF_MISSING',
  L12K_ALLOWED_FAMILIES_MISSING = 'L12K_ALLOWED_FAMILIES_MISSING',
  L12K_SCORE_CONTEXT_POLICY_MISSING = 'L12K_SCORE_CONTEXT_POLICY_MISSING',
  L12K_SCORE_CONTEXT_POLICY_WEAKENED = 'L12K_SCORE_CONTEXT_POLICY_WEAKENED',
  L12K_RESTRICTION_POLICY_MISSING = 'L12K_RESTRICTION_POLICY_MISSING',
  L12K_CONTRADICTION_POLICY_MISSING = 'L12K_CONTRADICTION_POLICY_MISSING',
  L12K_DRIFT_POLICY_MISSING = 'L12K_DRIFT_POLICY_MISSING',
  L12K_TRIGGER_POLICY_MISSING = 'L12K_TRIGGER_POLICY_MISSING',
  L12K_INVALIDATION_POLICY_MISSING = 'L12K_INVALIDATION_POLICY_MISSING',
  L12K_SHIFT_POLICY_MISSING = 'L12K_SHIFT_POLICY_MISSING',
  L12K_BASE_CASE_POLICY_MISSING = 'L12K_BASE_CASE_POLICY_MISSING',
  L12K_ALT_PATH_POLICY_MISSING = 'L12K_ALT_PATH_POLICY_MISSING',
  L12K_EVIDENCE_POLICY_MISSING = 'L12K_EVIDENCE_POLICY_MISSING',
  L12K_MATERIALIZATION_POLICY_MISSING = 'L12K_MATERIALIZATION_POLICY_MISSING',
  L12K_LINEAGE_POLICY_MISSING = 'L12K_LINEAGE_POLICY_MISSING',
  L12K_REPLAY_HASH_MISSING = 'L12K_REPLAY_HASH_MISSING',
  L12K_SUBJECT_REFERENCES_L13_PLUS = 'L12K_SUBJECT_REFERENCES_L13_PLUS',
  L12K_SUBJECT_TRADE_INTENT = 'L12K_SUBJECT_TRADE_INTENT',

  // Input requirement
  L12K_INPUT_REQUIREMENT_ID_MISSING = 'L12K_INPUT_REQUIREMENT_ID_MISSING',
  L12K_INPUT_RAW_LOWER_LAYER = 'L12K_INPUT_RAW_LOWER_LAYER',
  L12K_INPUT_SCORE_VALUE_ONLY_USED = 'L12K_INPUT_SCORE_VALUE_ONLY_USED',
  L12K_INPUT_EVIDENCE_ONLY_USED_AS_DECISIVE = 'L12K_INPUT_EVIDENCE_ONLY_USED_AS_DECISIVE',
  L12K_INPUT_STALE_AS_LIVE_TRIGGER = 'L12K_INPUT_STALE_AS_LIVE_TRIGGER',
  L12K_INPUT_HISTORICAL_AS_LIVE = 'L12K_INPUT_HISTORICAL_AS_LIVE',
  L12K_INPUT_RESTRICTION_NOT_CONSUMED = 'L12K_INPUT_RESTRICTION_NOT_CONSUMED',
  L12K_INPUT_CONTRADICTION_IGNORED = 'L12K_INPUT_CONTRADICTION_IGNORED',
  L12K_INPUT_POSTURE_MISSING = 'L12K_INPUT_POSTURE_MISSING',
  L12K_INPUT_REQUIRED_FIELD_MISSING = 'L12K_INPUT_REQUIRED_FIELD_MISSING',

  // Set contract
  L12K_SCENARIO_SET_CONTRACT_ID_MISSING = 'L12K_SCENARIO_SET_CONTRACT_ID_MISSING',
  L12K_SET_REF_MISSING = 'L12K_SET_REF_MISSING',
  L12K_BASE_CASE_ABSENT = 'L12K_BASE_CASE_ABSENT',
  L12K_NO_SCENARIO_REFS = 'L12K_NO_SCENARIO_REFS',
  L12K_PRIMARY_ABSENT = 'L12K_PRIMARY_ABSENT',
  L12K_SCENARIO_COUNT_MISMATCH = 'L12K_SCENARIO_COUNT_MISMATCH',
  L12K_ALTERNATIVE_PATH_ABSENT = 'L12K_ALTERNATIVE_PATH_ABSENT',
  L12K_TRIGGER_PROFILE_ABSENT = 'L12K_TRIGGER_PROFILE_ABSENT',
  L12K_INVALIDATION_ABSENT = 'L12K_INVALIDATION_ABSENT',
  L12K_PATH_CONFIDENCE_ABSENT = 'L12K_PATH_CONFIDENCE_ABSENT',
  L12K_SHIFT_CONDITIONS_REQUIRED_BUT_ABSENT = 'L12K_SHIFT_CONDITIONS_REQUIRED_BUT_ABSENT',
  L12K_RESTRICTION_PROFILE_ABSENT = 'L12K_RESTRICTION_PROFILE_ABSENT',
  L12K_EVIDENCE_REFS_ABSENT = 'L12K_EVIDENCE_REFS_ABSENT',
  L12K_LINEAGE_REFS_ABSENT = 'L12K_LINEAGE_REFS_ABSENT',
  L12K_BASE_CASE_GUARANTEED_OUTCOME = 'L12K_BASE_CASE_GUARANTEED_OUTCOME',
  L12K_PRIMARY_FINAL_WINNER = 'L12K_PRIMARY_FINAL_WINNER',

  // Path contract
  L12K_SCENARIO_CONTRACT_ID_MISSING = 'L12K_SCENARIO_CONTRACT_ID_MISSING',
  L12K_PATH_CLAIM_MISSING = 'L12K_PATH_CLAIM_MISSING',
  L12K_PATH_CLAIM_NOT_CONDITIONAL = 'L12K_PATH_CLAIM_NOT_CONDITIONAL',
  L12K_REQUIRED_CONDITIONS_ABSENT = 'L12K_REQUIRED_CONDITIONS_ABSENT',
  L12K_TRIGGER_REFS_ABSENT = 'L12K_TRIGGER_REFS_ABSENT',
  L12K_INVALIDATION_REFS_ABSENT = 'L12K_INVALIDATION_REFS_ABSENT',
  L12K_PATH_CONFIDENCE_BAND_MISMATCH = 'L12K_PATH_CONFIDENCE_BAND_MISMATCH',
  L12K_PATH_EVIDENCE_REFS_ABSENT = 'L12K_PATH_EVIDENCE_REFS_ABSENT',
  L12K_PATH_RESTRICTION_PROFILE_ABSENT = 'L12K_PATH_RESTRICTION_PROFILE_ABSENT',
  L12K_PATH_READINESS_MISSING = 'L12K_PATH_READINESS_MISSING',

  // Condition contract
  L12K_CONDITION_CONTRACT_INCOMPLETE = 'L12K_CONDITION_CONTRACT_INCOMPLETE',
  L12K_CONDITION_NOT_MONITORABLE_BUT_USED_AS_TRIGGER = 'L12K_CONDITION_NOT_MONITORABLE_BUT_USED_AS_TRIGGER',
  L12K_CONDITION_RAW_SOURCE = 'L12K_CONDITION_RAW_SOURCE',
  L12K_CONDITION_CAUSALITY_OR_CERTAINTY = 'L12K_CONDITION_CAUSALITY_OR_CERTAINTY',
  L12K_CONDITION_MATERIAL_WITHOUT_EVIDENCE = 'L12K_CONDITION_MATERIAL_WITHOUT_EVIDENCE',

  // Trigger contract
  L12K_TRIGGER_CONTRACT_INCOMPLETE = 'L12K_TRIGGER_CONTRACT_INCOMPLETE',
  L12K_TRIGGER_NOT_MONITORABLE_BUT_ACTIVE = 'L12K_TRIGGER_NOT_MONITORABLE_BUT_ACTIVE',
  L12K_TRIGGER_GUARANTEED_OUTCOME = 'L12K_TRIGGER_GUARANTEED_OUTCOME',
  L12K_TRIGGER_TRADE_INSTRUCTION = 'L12K_TRIGGER_TRADE_INSTRUCTION',
  L12K_TRIGGER_MONITORING_REQ_MISSING = 'L12K_TRIGGER_MONITORING_REQ_MISSING',

  // Invalidation contract
  L12K_INVALIDATION_CONTRACT_INCOMPLETE = 'L12K_INVALIDATION_CONTRACT_INCOMPLETE',
  L12K_INVALIDATION_NOT_MONITORABLE_USED_CLEAN = 'L12K_INVALIDATION_NOT_MONITORABLE_USED_CLEAN',
  L12K_ACTIVE_INVALIDATION_NOT_REFLECTED_IN_CONFIDENCE = 'L12K_ACTIVE_INVALIDATION_NOT_REFLECTED_IN_CONFIDENCE',
  L12K_INVALIDATION_HIDDEN = 'L12K_INVALIDATION_HIDDEN',
  L12K_INVALIDATION_MONITORING_REQ_MISSING = 'L12K_INVALIDATION_MONITORING_REQ_MISSING',

  // Confidence contract
  L12K_CONFIDENCE_OUT_OF_RANGE = 'L12K_CONFIDENCE_OUT_OF_RANGE',
  L12K_CONFIDENCE_BAND_MISMATCH = 'L12K_CONFIDENCE_BAND_MISMATCH',
  L12K_CONFIDENCE_UNCAPPED_UNDER_CONTRADICTION = 'L12K_CONFIDENCE_UNCAPPED_UNDER_CONTRADICTION',
  L12K_CONFIDENCE_UNCAPPED_UNDER_INVALIDATION = 'L12K_CONFIDENCE_UNCAPPED_UNDER_INVALIDATION',
  L12K_CONFIDENCE_UNCAPPED_UNDER_MISSING_VISIBILITY = 'L12K_CONFIDENCE_UNCAPPED_UNDER_MISSING_VISIBILITY',
  L12K_CONFIDENCE_UNCAPPED_UNDER_DRIFT = 'L12K_CONFIDENCE_UNCAPPED_UNDER_DRIFT',
  L12K_CONFIDENCE_CAP_REFS_MISSING = 'L12K_CONFIDENCE_CAP_REFS_MISSING',
  L12K_CONFIDENCE_READINESS_CLEAN_UNDER_NARROWED = 'L12K_CONFIDENCE_READINESS_CLEAN_UNDER_NARROWED',
  L12K_CONFIDENCE_CERTAINTY_CLAIM = 'L12K_CONFIDENCE_CERTAINTY_CLAIM',

  // Shift contract
  L12K_SHIFT_CONTRACT_INCOMPLETE = 'L12K_SHIFT_CONTRACT_INCOMPLETE',
  L12K_SHIFT_PRIMARY_REF_MISSING = 'L12K_SHIFT_PRIMARY_REF_MISSING',
  L12K_SHIFT_SECONDARY_REF_MISSING_UNDER_CLOSE = 'L12K_SHIFT_SECONDARY_REF_MISSING_UNDER_CLOSE',
  L12K_SHIFT_PROMOTION_MISSING_UNDER_CLOSE = 'L12K_SHIFT_PROMOTION_MISSING_UNDER_CLOSE',
  L12K_SHIFT_COLLAPSE_MISSING_UNDER_CLOSE = 'L12K_SHIFT_COLLAPSE_MISSING_UNDER_CLOSE',
  L12K_SHIFT_TRADE_LANGUAGE = 'L12K_SHIFT_TRADE_LANGUAGE',
  L12K_SHIFT_UNGOVERNED_INPUT = 'L12K_SHIFT_UNGOVERNED_INPUT',
  L12K_SHIFT_RECOMMENDATION = 'L12K_SHIFT_RECOMMENDATION',

  // Restriction contract
  L12K_RESTRICTION_CONTRACT_INCOMPLETE = 'L12K_RESTRICTION_CONTRACT_INCOMPLETE',
  L12K_RESTRICTION_ALLOWED_USES_EMPTY = 'L12K_RESTRICTION_ALLOWED_USES_EMPTY',
  L12K_RESTRICTION_BLOCKED_USES_EMPTY = 'L12K_RESTRICTION_BLOCKED_USES_EMPTY',
  L12K_RESTRICTION_RECOMMENDATION_NOT_BLOCKED = 'L12K_RESTRICTION_RECOMMENDATION_NOT_BLOCKED',
  L12K_RESTRICTION_PREDICTION_NOT_BLOCKED = 'L12K_RESTRICTION_PREDICTION_NOT_BLOCKED',
  L12K_RESTRICTION_TRADE_NOT_BLOCKED = 'L12K_RESTRICTION_TRADE_NOT_BLOCKED',
  L12K_RESTRICTION_FINAL_JUDGMENT_NOT_BLOCKED = 'L12K_RESTRICTION_FINAL_JUDGMENT_NOT_BLOCKED',
  L12K_RESTRICTION_CERTAINTY_NOT_BLOCKED = 'L12K_RESTRICTION_CERTAINTY_NOT_BLOCKED',
  L12K_RESTRICTION_DISCLOSURE_REQUIRED_BUT_ABSENT = 'L12K_RESTRICTION_DISCLOSURE_REQUIRED_BUT_ABSENT',
  L12K_RESTRICTION_BROADER_THAN_READINESS = 'L12K_RESTRICTION_BROADER_THAN_READINESS',
  L12K_RESTRICTION_REASON_CODES_MISSING = 'L12K_RESTRICTION_REASON_CODES_MISSING',

  // Evidence pack contract
  L12K_EVIDENCE_PACK_INCOMPLETE = 'L12K_EVIDENCE_PACK_INCOMPLETE',
  L12K_EVIDENCE_REFS_RAW_LOWER_LAYER = 'L12K_EVIDENCE_REFS_RAW_LOWER_LAYER',
  L12K_EVIDENCE_REFS_UNGOVERNED = 'L12K_EVIDENCE_REFS_UNGOVERNED',
  L12K_EVIDENCE_INPUT_SNAPSHOT_MISSING = 'L12K_EVIDENCE_INPUT_SNAPSHOT_MISSING',
  L12K_EVIDENCE_REPLAY_SAFE_REF_MISSING = 'L12K_EVIDENCE_REPLAY_SAFE_REF_MISSING',
  L12K_EVIDENCE_SCORE_REFS_MISSING = 'L12K_EVIDENCE_SCORE_REFS_MISSING',

  // Replay identity contract
  L12K_REPLAY_IDENTITY_INCOMPLETE = 'L12K_REPLAY_IDENTITY_INCOMPLETE',
  L12K_REPLAY_SUBJECT_HASH_MISSING = 'L12K_REPLAY_SUBJECT_HASH_MISSING',
  L12K_REPLAY_SET_HASH_MISSING = 'L12K_REPLAY_SET_HASH_MISSING',
  L12K_REPLAY_SCENARIO_HASHES_MISSING = 'L12K_REPLAY_SCENARIO_HASHES_MISSING',
  L12K_REPLAY_CONDITION_HASHES_MISSING = 'L12K_REPLAY_CONDITION_HASHES_MISSING',
  L12K_REPLAY_TRIGGER_HASHES_MISSING = 'L12K_REPLAY_TRIGGER_HASHES_MISSING',
  L12K_REPLAY_INVALIDATION_HASHES_MISSING = 'L12K_REPLAY_INVALIDATION_HASHES_MISSING',
  L12K_REPLAY_CONFIDENCE_HASH_MISSING = 'L12K_REPLAY_CONFIDENCE_HASH_MISSING',
  L12K_REPLAY_RESTRICTION_HASH_MISSING = 'L12K_REPLAY_RESTRICTION_HASH_MISSING',
  L12K_REPLAY_EVIDENCE_PACK_HASH_MISSING = 'L12K_REPLAY_EVIDENCE_PACK_HASH_MISSING',
  L12K_REPLAY_LOWER_LAYER_SNAPSHOT_REFS_MISSING = 'L12K_REPLAY_LOWER_LAYER_SNAPSHOT_REFS_MISSING',
  L12K_REPLAY_MATERIAL_EXCLUDES_SCORE_CONTEXT = 'L12K_REPLAY_MATERIAL_EXCLUDES_SCORE_CONTEXT',

  // Output readiness law
  L12K_OUTPUT_CLEAN_WHILE_INVALIDATION_ACTIVE = 'L12K_OUTPUT_CLEAN_WHILE_INVALIDATION_ACTIVE',
  L12K_OUTPUT_CLEAN_WHILE_TRIGGER_MISSING = 'L12K_OUTPUT_CLEAN_WHILE_TRIGGER_MISSING',
  L12K_OUTPUT_CLEAN_WHILE_INVALIDATION_MISSING = 'L12K_OUTPUT_CLEAN_WHILE_INVALIDATION_MISSING',
  L12K_OUTPUT_CLEAN_WHILE_MULTI_PATH_UNRESOLVED = 'L12K_OUTPUT_CLEAN_WHILE_MULTI_PATH_UNRESOLVED',
  L12K_OUTPUT_CLEAN_WHILE_SCORE_CONTEXT_INCOMPLETE = 'L12K_OUTPUT_CLEAN_WHILE_SCORE_CONTEXT_INCOMPLETE',
  L12K_OUTPUT_CLEAN_WHILE_DRIFT_HIDDEN = 'L12K_OUTPUT_CLEAN_WHILE_DRIFT_HIDDEN',
  L12K_OUTPUT_CLEAN_WHILE_RESTRICTION_REQUIRED = 'L12K_OUTPUT_CLEAN_WHILE_RESTRICTION_REQUIRED',
  L12K_OUTPUT_CLEAN_WHILE_CONTRADICTION_UNRESOLVED = 'L12K_OUTPUT_CLEAN_WHILE_CONTRADICTION_UNRESOLVED',
  L12K_OUTPUT_CLEAN_WHILE_VISIBILITY_MISSING = 'L12K_OUTPUT_CLEAN_WHILE_VISIBILITY_MISSING',
  L12K_OUTPUT_CLEAN_WHILE_ALT_PATH_ABSENT = 'L12K_OUTPUT_CLEAN_WHILE_ALT_PATH_ABSENT',
  L12K_OUTPUT_CLEAN_WHILE_SHIFT_REQUIRED = 'L12K_OUTPUT_CLEAN_WHILE_SHIFT_REQUIRED',
  L12K_OUTPUT_LEAKAGE_DETECTED = 'L12K_OUTPUT_LEAKAGE_DETECTED',
  L12K_OUTPUT_READINESS_DERIVATION_MISMATCH = 'L12K_OUTPUT_READINESS_DERIVATION_MISMATCH',

  // Compatibility law
  L12K_CONTRACT_DELTA_UNCLASSIFIED = 'L12K_CONTRACT_DELTA_UNCLASSIFIED',
  L12K_REQUIRED_FIELD_REMOVED = 'L12K_REQUIRED_FIELD_REMOVED',
  L12K_REPLAY_MATERIAL_CHANGED_WITHOUT_VERSION = 'L12K_REPLAY_MATERIAL_CHANGED_WITHOUT_VERSION',
  L12K_TRIGGER_LAW_WEAKENED = 'L12K_TRIGGER_LAW_WEAKENED',
  L12K_INVALIDATION_LAW_WEAKENED = 'L12K_INVALIDATION_LAW_WEAKENED',
  L12K_SCORE_CONTEXT_LAW_WEAKENED = 'L12K_SCORE_CONTEXT_LAW_WEAKENED',
  L12K_RESTRICTION_LAW_WEAKENED = 'L12K_RESTRICTION_LAW_WEAKENED',
  L12K_PREDICTION_THEATER_SCAN_REMOVED = 'L12K_PREDICTION_THEATER_SCAN_REMOVED',
  L12K_OLD_OUTPUTS_REINTERPRETED = 'L12K_OLD_OUTPUTS_REINTERPRETED',

  // Semantic
  L12K_PREDICTION_THEATER = 'L12K_PREDICTION_THEATER',
  L12K_RECOMMENDATION_LEAK = 'L12K_RECOMMENDATION_LEAK',
  L12K_JUDGMENT_LEAK = 'L12K_JUDGMENT_LEAK',
  L12K_TRADE_ACTION_LEAK = 'L12K_TRADE_ACTION_LEAK',
  L12K_CERTAINTY_LANGUAGE = 'L12K_CERTAINTY_LANGUAGE',
}

export const ALL_L12_CONTRACT_VIOLATION_CODES: readonly L12ContractViolationCode[] =
  Object.values(L12ContractViolationCode);

export interface L12ContractViolation {
  readonly code: L12ContractViolationCode;
  readonly subject_id: string;
  readonly detail: string;
}

export class L12ContractError extends Error {
  public readonly code: L12ContractViolationCode;
  constructor(code: L12ContractViolationCode, message: string) {
    super(`[${code}] ${message}`);
    this.code = code;
    this.name = 'L12ContractError';
  }
}
