/**
 * L12.4 — Runtime violation codes (§12.4.28).
 *
 * Disjoint namespace `L12R_` for L12.4 runtime issues.
 */

export enum L12RuntimeViolationCode {
  L12R_DAG_NODE_MISSING = 'L12R_DAG_NODE_MISSING',
  L12R_DAG_NODE_DUPLICATE = 'L12R_DAG_NODE_DUPLICATE',
  L12R_DAG_NODE_CLASS_STAGE_MISMATCH = 'L12R_DAG_NODE_CLASS_STAGE_MISMATCH',
  L12R_DAG_EDGE_ILLEGAL = 'L12R_DAG_EDGE_ILLEGAL',
  L12R_DAG_EDGE_DUPLICATE = 'L12R_DAG_EDGE_DUPLICATE',
  L12R_DAG_EDGE_BACKWARD = 'L12R_DAG_EDGE_BACKWARD',
  L12R_DAG_EDGE_UNREGISTERED = 'L12R_DAG_EDGE_UNREGISTERED',
  L12R_DAG_NODE_COUNT_INVALID = 'L12R_DAG_NODE_COUNT_INVALID',
  L12R_DAG_EDGE_COUNT_INVALID = 'L12R_DAG_EDGE_COUNT_INVALID',
  L12R_DAG_CYCLE_DETECTED = 'L12R_DAG_CYCLE_DETECTED',
  L12R_TOPO_ORDER_UNSTABLE = 'L12R_TOPO_ORDER_UNSTABLE',
  L12R_STAGE_BYPASS = 'L12R_STAGE_BYPASS',
  L12R_STAGE_MUTATED_AFTER_SEAL = 'L12R_STAGE_MUTATED_AFTER_SEAL',

  L12R_COMPUTE_RUN_MODE_LAW = 'L12R_COMPUTE_RUN_MODE_LAW',
  L12R_COMPUTE_RUN_REPLAY_HASH_MISSING = 'L12R_COMPUTE_RUN_REPLAY_HASH_MISSING',
  L12R_EXECUTION_CONTEXT_INVALID = 'L12R_EXECUTION_CONTEXT_INVALID',

  L12R_SUBJECT_CONTRACT_INCOMPLETE = 'L12R_SUBJECT_CONTRACT_INCOMPLETE',
  L12R_INPUT_RESOLUTION_BLOCKED = 'L12R_INPUT_RESOLUTION_BLOCKED',
  L12R_INPUT_RESOLUTION_RAW_LOWER_LAYER = 'L12R_INPUT_RESOLUTION_RAW_LOWER_LAYER',
  L12R_L11_SCORE_CONTEXT_INCOMPLETE = 'L12R_L11_SCORE_CONTEXT_INCOMPLETE',
  L12R_NAKED_SCORE_CONSUMPTION = 'L12R_NAKED_SCORE_CONSUMPTION',

  L12R_CANDIDATE_NO_REASON_CODES = 'L12R_CANDIDATE_NO_REASON_CODES',
  L12R_CANDIDATE_ASSIGNED_PRIMARY = 'L12R_CANDIDATE_ASSIGNED_PRIMARY',
  L12R_ILLEGAL_TYPE_FAMILY_PAIR = 'L12R_ILLEGAL_TYPE_FAMILY_PAIR',
  L12R_BULLISH_ONLY_FAKE_CERTAINTY = 'L12R_BULLISH_ONLY_FAKE_CERTAINTY',

  L12R_CONDITION_RAW_INPUT = 'L12R_CONDITION_RAW_INPUT',
  L12R_CONDITION_TYPE_LAYER_MISMATCH = 'L12R_CONDITION_TYPE_LAYER_MISMATCH',
  L12R_CONDITION_NOT_MONITORABLE = 'L12R_CONDITION_NOT_MONITORABLE',
  L12R_CONDITION_NO_EVIDENCE = 'L12R_CONDITION_NO_EVIDENCE',

  L12R_TRIGGER_MISSING = 'L12R_TRIGGER_MISSING',
  L12R_TRIGGER_UNMONITORABLE_ACTIVE = 'L12R_TRIGGER_UNMONITORABLE_ACTIVE',
  L12R_TRIGGER_NO_EVIDENCE = 'L12R_TRIGGER_NO_EVIDENCE',
  L12R_TRIGGER_GUARANTEED_OUTCOME = 'L12R_TRIGGER_GUARANTEED_OUTCOME',

  L12R_INVALIDATION_MISSING = 'L12R_INVALIDATION_MISSING',
  L12R_INVALIDATION_HIDDEN_FROM_CONFIDENCE = 'L12R_INVALIDATION_HIDDEN_FROM_CONFIDENCE',
  L12R_INVALIDATION_UNMONITORABLE_ACTIVE = 'L12R_INVALIDATION_UNMONITORABLE_ACTIVE',
  L12R_INVALIDATION_NO_EVIDENCE = 'L12R_INVALIDATION_NO_EVIDENCE',

  L12R_PATH_WITHOUT_TRIGGER = 'L12R_PATH_WITHOUT_TRIGGER',
  L12R_PATH_WITHOUT_INVALIDATION = 'L12R_PATH_WITHOUT_INVALIDATION',
  L12R_PATH_NOT_CONDITIONAL = 'L12R_PATH_NOT_CONDITIONAL',
  L12R_PATH_CERTAINTY_LANGUAGE = 'L12R_PATH_CERTAINTY_LANGUAGE',
  L12R_SINGLE_PATH_WITHOUT_INSUFFICIENT = 'L12R_SINGLE_PATH_WITHOUT_INSUFFICIENT',

  L12R_CONFIDENCE_UNCAPPED = 'L12R_CONFIDENCE_UNCAPPED',
  L12R_CONFIDENCE_HIGH_UNDER_INVALIDATION = 'L12R_CONFIDENCE_HIGH_UNDER_INVALIDATION',
  L12R_RANKING_BEFORE_CONFIDENCE = 'L12R_RANKING_BEFORE_CONFIDENCE',
  L12R_RANKING_NO_BASE_CASE = 'L12R_RANKING_NO_BASE_CASE',
  L12R_RANKING_NO_PRIMARY = 'L12R_RANKING_NO_PRIMARY',
  L12R_RANKING_FAKE_CLEAN = 'L12R_RANKING_FAKE_CLEAN',
  L12R_RANKING_SCENARIO_WINNER_LANGUAGE = 'L12R_RANKING_SCENARIO_WINNER_LANGUAGE',

  L12R_SHIFT_REQUIRED_BUT_ABSENT = 'L12R_SHIFT_REQUIRED_BUT_ABSENT',
  L12R_SHIFT_TRADE_LANGUAGE = 'L12R_SHIFT_TRADE_LANGUAGE',

  L12R_RESTRICTION_BROADER_THAN_READINESS = 'L12R_RESTRICTION_BROADER_THAN_READINESS',
  L12R_RESTRICTION_MISSING_MANDATORY_BLOCKED_USE = 'L12R_RESTRICTION_MISSING_MANDATORY_BLOCKED_USE',
  L12R_RESTRICTION_DISCLOSURE_MISSING = 'L12R_RESTRICTION_DISCLOSURE_MISSING',

  L12R_EVIDENCE_PACK_INCOMPLETE = 'L12R_EVIDENCE_PACK_INCOMPLETE',
  L12R_EVIDENCE_RAW_DECISIVE_INPUT = 'L12R_EVIDENCE_RAW_DECISIVE_INPUT',
  L12R_EVIDENCE_REPLAY_HASH_MISSING = 'L12R_EVIDENCE_REPLAY_HASH_MISSING',

  L12R_L5_ROUTE_MISSING = 'L12R_L5_ROUTE_MISSING',
  L12R_DIRECT_STORE_WRITE = 'L12R_DIRECT_STORE_WRITE',
  L12R_MATERIALIZATION_WITHOUT_EVIDENCE_PACK = 'L12R_MATERIALIZATION_WITHOUT_EVIDENCE_PACK',
  L12R_MATERIALIZATION_BLOCKED_READINESS = 'L12R_MATERIALIZATION_BLOCKED_READINESS',

  L12R_REPLAY_HASH_MISMATCH = 'L12R_REPLAY_HASH_MISMATCH',
  L12R_REPLAY_INVENTED_EVIDENCE = 'L12R_REPLAY_INVENTED_EVIDENCE',
  L12R_REPLAY_ERASED_INVALIDATION = 'L12R_REPLAY_ERASED_INVALIDATION',
  L12R_REPLAY_ERASED_TRIGGER = 'L12R_REPLAY_ERASED_TRIGGER',
  L12R_REPLAY_CHANGED_RANKING_WITHOUT_DRIFT = 'L12R_REPLAY_CHANGED_RANKING_WITHOUT_DRIFT',

  L12R_REPAIR_PARENT_MISSING = 'L12R_REPAIR_PARENT_MISSING',
  L12R_REPAIR_REASON_MISSING = 'L12R_REPAIR_REASON_MISSING',
  L12R_REPAIR_SAME_RUN_ID = 'L12R_REPAIR_SAME_RUN_ID',
  L12R_REPAIR_REMOVED_TRIGGER = 'L12R_REPAIR_REMOVED_TRIGGER',
  L12R_REPAIR_REMOVED_INVALIDATION = 'L12R_REPAIR_REMOVED_INVALIDATION',
  L12R_REPAIR_UPGRADED_CONFIDENCE_NO_NEW_EVIDENCE = 'L12R_REPAIR_UPGRADED_CONFIDENCE_NO_NEW_EVIDENCE',

  L12R_PREDICTION_THEATER = 'L12R_PREDICTION_THEATER',
  L12R_RECOMMENDATION_LEAK = 'L12R_RECOMMENDATION_LEAK',
  L12R_JUDGMENT_LEAK = 'L12R_JUDGMENT_LEAK',
  L12R_TRADE_LEAK = 'L12R_TRADE_LEAK',
}

export const ALL_L12_RUNTIME_VIOLATION_CODES: readonly L12RuntimeViolationCode[] =
  Object.values(L12RuntimeViolationCode);

export interface L12RuntimeViolationIssue {
  readonly code: L12RuntimeViolationCode;
  readonly message: string;
  readonly subject_ref?: string;
  readonly stage_ref?: number | string;
}

export function l12IssueOf(
  code: L12RuntimeViolationCode,
  message: string,
  subject_ref?: string,
  stage_ref?: number | string,
): L12RuntimeViolationIssue {
  return { code, message, subject_ref, stage_ref };
}
